-- Root private expected snapshot injected as JSON parameter; no authority generated.
DECLARE expected jsonb := __EXPECTED_JSON__; before_state jsonb; after_state jsonb; target_campaign public.campaigns%ROWTYPE; n integer; actual_time timestamptz;
BEGIN
LOCK TABLE public.campaigns,public.campaign_lists,public.campaign_media,public.lists,public.templates,public.media,public.crm_familia_campanha,crm_audience_v2.campaign_binding,crm_audience_v2.regular_delivery_campaign IN SHARE ROW EXCLUSIVE MODE;
LOCK TABLE public.subscribers,public.subscriber_lists,public.crm_ab_arm_v2,public.crm_ab_experiment_v2 IN SHARE MODE;

SELECT jsonb_build_object(
 'campaigns',(SELECT jsonb_agg(to_jsonb(c) ORDER BY c.id) FROM public.campaigns c WHERE c.id BETWEEN 171 AND 177),
 'campaignLists',(SELECT coalesce(jsonb_agg(to_jsonb(cl) ORDER BY cl.campaign_id,cl.list_id),'[]'::jsonb) FROM public.campaign_lists cl WHERE cl.campaign_id BETWEEN 171 AND 177),
 'list156',(SELECT to_jsonb(l) FROM public.lists l WHERE id=156),
 'template175',(SELECT to_jsonb(t) FROM public.templates t JOIN public.campaigns c ON c.template_id=t.id WHERE c.id=175),
 'campaignMedia',(SELECT coalesce(jsonb_agg(to_jsonb(cm) ORDER BY cm.media_id),'[]'::jsonb) FROM public.campaign_media cm WHERE cm.campaign_id=175),
 'media',(SELECT coalesce(jsonb_agg(to_jsonb(m) ORDER BY m.id),'[]'::jsonb) FROM public.media m WHERE EXISTS(SELECT 1 FROM public.campaign_media cm WHERE cm.campaign_id=175 AND cm.media_id=m.id)),
 'bindings',(SELECT coalesce(jsonb_agg(to_jsonb(b) ORDER BY campaign_id),'[]'::jsonb) FROM crm_audience_v2.campaign_binding b WHERE campaign_id BETWEEN 171 AND 177),
 'controls',(SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY campaign_id),'[]'::jsonb) FROM crm_audience_v2.regular_delivery_campaign d WHERE campaign_id BETWEEN 171 AND 177),
 'alias',(SELECT coalesce(jsonb_agg(to_jsonb(f)),'[]'::jsonb) FROM public.crm_familia_campanha f WHERE marca='aristo' AND utm_campaign='black-antecipada-1010'),
 'selection175',crm_audience_v2.selection_worker_context(175),
 'maternalOptouts',(SELECT count(*) FROM public.subscriber_lists sl JOIN public.subscribers s ON s.id=sl.subscriber_id WHERE sl.list_id=156 AND s.status::text='enabled' AND sl.status::text IN('confirmed','unconfirmed') AND EXISTS(SELECT 1 FROM public.subscriber_lists m WHERE m.subscriber_id=sl.subscriber_id AND m.list_id IN(7,10,16,19,21) AND m.status::text='unsubscribed')),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('relation',c.conrelid::regclass::text,'name',c.conname,'definition',pg_get_constraintdef(c.oid)) ORDER BY c.conrelid,c.conname),'[]'::jsonb) FROM pg_constraint c WHERE c.conrelid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass)),
 'relations',(SELECT jsonb_agg(jsonb_build_object('relation',c.oid::regclass::text,'kind',c.relkind,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity) ORDER BY c.oid) FROM pg_class c WHERE c.oid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass)),
 'triggers',(SELECT jsonb_agg(jsonb_build_object('relation',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid),'function',pg_get_functiondef(t.tgfoid)) ORDER BY c.relname,t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal AND t.tgrelid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass))
) INTO before_state;
IF expected IS NULL OR before_state IS DISTINCT FROM expected THEN RAISE EXCEPTION 'WAVE175_CURRENT_DRIFT'; END IF;
IF EXISTS(SELECT 1 FROM jsonb_array_elements(before_state->'relations') r WHERE r->>'kind'<>'r' OR r->>'rls'<>'false' OR r->>'forceRls'<>'false') THEN RAISE EXCEPTION 'WAVE175_RELATION_SCOPE'; END IF;
SELECT * INTO STRICT target_campaign FROM public.campaigns WHERE id=175;
actual_time:=clock_timestamp();
IF target_campaign.status::text IS DISTINCT FROM 'draft' OR target_campaign.type::text IS DISTINCT FROM 'regular' OR target_campaign.messenger IS DISTINCT FROM 'email' OR target_campaign.sent IS DISTINCT FROM 0 OR target_campaign.to_send IS DISTINCT FROM 0 OR target_campaign.last_subscriber_id IS DISTINCT FROM 0 OR target_campaign.max_subscriber_id IS DISTINCT FROM 0 OR target_campaign.started_at IS NOT NULL OR target_campaign.attribs#>'{crm}' IS NOT NULL OR target_campaign.send_at IS DISTINCT FROM timestamptz '2026-10-10 16:00:00+00' OR target_campaign.send_at<actual_time+interval '15 minutes' OR NOT(coalesce(target_campaign.tags,'{}')::text[] @> ARRAY['black-antecipada','compradores']) THEN RAISE EXCEPTION 'WAVE175_NATIVE_PRECONDITION'; END IF;
IF before_state->'selection175' IS DISTINCT FROM '{"bound":false}'::jsonb OR EXISTS(SELECT 1 FROM crm_audience_v2.campaign_binding WHERE campaign_id IN(175,176,177)) OR EXISTS(SELECT 1 FROM crm_audience_v2.regular_delivery_campaign WHERE campaign_id IN(175,176,177)) OR EXISTS(SELECT 1 FROM public.crm_ab_arm_v2 WHERE campaign_id=175) OR before_state->>'maternalOptouts' IS DISTINCT FROM '0' THEN RAISE EXCEPTION 'WAVE175_UNBOUND_REQUIRED'; END IF;
IF (SELECT array_agg(list_id ORDER BY list_id) FROM public.campaign_lists WHERE campaign_id=175) IS DISTINCT FROM ARRAY[156] OR before_state#>>'{list156,status}' IS DISTINCT FROM 'active' OR NOT(coalesce(ARRAY(SELECT jsonb_array_elements_text(before_state#>'{list156,tags}')),ARRAY[]::text[]) && ARRAY['aristo','aristocrata']) OR coalesce(ARRAY(SELECT jsonb_array_elements_text(before_state#>'{list156,tags}')),ARRAY[]::text[]) && ARRAY['fish','fishermans','olivas','cross','aposentada'] THEN RAISE EXCEPTION 'WAVE175_LIST_SCOPE'; END IF;
IF (SELECT array_agg(status::text ORDER BY id) FROM public.campaigns WHERE id BETWEEN 171 AND 177) IS DISTINCT FROM ARRAY['paused','scheduled','scheduled','paused','draft','draft','draft'] THEN RAISE EXCEPTION 'WAVE175_OTHER_WAVE_STATE'; END IF;
IF EXISTS(SELECT 1 FROM public.crm_familia_campanha WHERE marca='aristo' AND utm_campaign='black-antecipada-1010' AND familia IS DISTINCT FROM 'black-antecipada') THEN RAISE EXCEPTION 'WAVE175_ALIAS_CONFLICT'; END IF;
INSERT INTO public.crm_familia_campanha(marca,utm_campaign,familia) SELECT 'aristo','black-antecipada-1010','black-antecipada' WHERE NOT EXISTS(SELECT 1 FROM public.crm_familia_campanha WHERE marca='aristo' AND utm_campaign='black-antecipada-1010');
UPDATE public.campaigns SET status='scheduled',updated_at=clock_timestamp() WHERE id=175 AND status::text='draft';
GET DIAGNOSTICS n=ROW_COUNT;IF n<>1 THEN RAISE EXCEPTION 'WAVE175_CAS_FAILED'; END IF;
SELECT jsonb_build_object(
 'campaigns',(SELECT jsonb_agg(to_jsonb(c) ORDER BY c.id) FROM public.campaigns c WHERE c.id BETWEEN 171 AND 177),
 'campaignLists',(SELECT coalesce(jsonb_agg(to_jsonb(cl) ORDER BY cl.campaign_id,cl.list_id),'[]'::jsonb) FROM public.campaign_lists cl WHERE cl.campaign_id BETWEEN 171 AND 177),
 'list156',(SELECT to_jsonb(l) FROM public.lists l WHERE id=156),
 'template175',(SELECT to_jsonb(t) FROM public.templates t JOIN public.campaigns c ON c.template_id=t.id WHERE c.id=175),
 'campaignMedia',(SELECT coalesce(jsonb_agg(to_jsonb(cm) ORDER BY cm.media_id),'[]'::jsonb) FROM public.campaign_media cm WHERE cm.campaign_id=175),
 'media',(SELECT coalesce(jsonb_agg(to_jsonb(m) ORDER BY m.id),'[]'::jsonb) FROM public.media m WHERE EXISTS(SELECT 1 FROM public.campaign_media cm WHERE cm.campaign_id=175 AND cm.media_id=m.id)),
 'bindings',(SELECT coalesce(jsonb_agg(to_jsonb(b) ORDER BY campaign_id),'[]'::jsonb) FROM crm_audience_v2.campaign_binding b WHERE campaign_id BETWEEN 171 AND 177),
 'controls',(SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY campaign_id),'[]'::jsonb) FROM crm_audience_v2.regular_delivery_campaign d WHERE campaign_id BETWEEN 171 AND 177),
 'alias',(SELECT coalesce(jsonb_agg(to_jsonb(f)),'[]'::jsonb) FROM public.crm_familia_campanha f WHERE marca='aristo' AND utm_campaign='black-antecipada-1010'),
 'selection175',crm_audience_v2.selection_worker_context(175),
 'maternalOptouts',(SELECT count(*) FROM public.subscriber_lists sl JOIN public.subscribers s ON s.id=sl.subscriber_id WHERE sl.list_id=156 AND s.status::text='enabled' AND sl.status::text IN('confirmed','unconfirmed') AND EXISTS(SELECT 1 FROM public.subscriber_lists m WHERE m.subscriber_id=sl.subscriber_id AND m.list_id IN(7,10,16,19,21) AND m.status::text='unsubscribed')),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('relation',c.conrelid::regclass::text,'name',c.conname,'definition',pg_get_constraintdef(c.oid)) ORDER BY c.conrelid,c.conname),'[]'::jsonb) FROM pg_constraint c WHERE c.conrelid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass)),
 'relations',(SELECT jsonb_agg(jsonb_build_object('relation',c.oid::regclass::text,'kind',c.relkind,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity) ORDER BY c.oid) FROM pg_class c WHERE c.oid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass)),
 'triggers',(SELECT jsonb_agg(jsonb_build_object('relation',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid),'function',pg_get_functiondef(t.tgfoid)) ORDER BY c.relname,t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal AND t.tgrelid IN('public.campaigns'::regclass,'public.campaign_lists'::regclass,'public.campaign_media'::regclass,'public.lists'::regclass,'public.templates'::regclass,'public.media'::regclass,'public.crm_familia_campanha'::regclass))
) INTO after_state;
IF (after_state-ARRAY['campaigns','alias']) IS DISTINCT FROM (before_state-ARRAY['campaigns','alias']) THEN RAISE EXCEPTION 'WAVE175_DEPENDENCY_CHANGED'; END IF;
IF (SELECT jsonb_agg(value ORDER BY (value->>'id')::integer) FROM jsonb_array_elements(after_state->'campaigns') WHERE value->>'id'<>'175') IS DISTINCT FROM (SELECT jsonb_agg(value ORDER BY (value->>'id')::integer) FROM jsonb_array_elements(before_state->'campaigns') WHERE value->>'id'<>'175') THEN RAISE EXCEPTION 'WAVE175_OTHER_CHANGED'; END IF;
IF (SELECT value-ARRAY['status','updated_at'] FROM jsonb_array_elements(after_state->'campaigns') WHERE value->>'id'='175') IS DISTINCT FROM (to_jsonb(target_campaign)-ARRAY['status','updated_at']) OR (SELECT value->>'status' FROM jsonb_array_elements(after_state->'campaigns') WHERE value->>'id'='175') IS DISTINCT FROM 'scheduled' OR clock_timestamp()>target_campaign.send_at-interval '15 minutes' THEN RAISE EXCEPTION 'WAVE175_POST_DIFF'; END IF;
IF NOT EXISTS(SELECT 1 FROM public.crm_familia_campanha WHERE marca='aristo' AND utm_campaign='black-antecipada-1010' AND familia='black-antecipada') THEN RAISE EXCEPTION 'WAVE175_ALIAS_POST'; END IF;
END
