'use strict';
// Disposable HTTP fixture: no identity, production DB, grant or upstream.
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{Readable,Writable}=require('node:stream');
const runtime=process.env.PRESENTATION_STYLE_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const {createServer}=require(runtime+'/server.cjs'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(t,{enabled=true}={}){
 const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'crm-style-fixture-'))),file=dir+'/crm-presentation.css',data=Buffer.from('.crm-sidebar{display:grid}');fs.writeFileSync(file,data);fs.mkdirSync(dir+'/assets/panels',{recursive:true});fs.writeFileSync(dir+'/assets/panels/growth.css','old inherited style');
 const s={mode:'synthetic',upstreamProfile:'production',managerHost:'master.synthetic.invalid',areaHosts:{growth:'crm.synthetic.invalid',organico:'organic.synthetic.invalid',influs:'affiliate.synthetic.invalid'},publicDir:dir,crmNativeEnabled:true,...(enabled?{crmPresentationStyle:{path:file,bytes:data.length,sha256:sha(data)}}:{})};
 const server=createServer(s,{auth:{nativeConnections:{}}});t.after(()=>{server.close();fs.rmSync(dir,{recursive:true,force:true});});
 async function request(url,{method='GET',host=s.managerHost}={}){const req=Readable.from([]);req.url=url;req.method=method;req.headers={host};req.socket={remoteAddress:'isolated-style-fixture'};const chunks=[],headers={};const res=new Writable({write(c,_e,cb){chunks.push(Buffer.from(c));cb();}});res.statusCode=200;res.setHeader=(k,v)=>headers[k.toLowerCase()]=v;res.getHeader=k=>headers[k.toLowerCase()];const done=new Promise(r=>res.once('finish',r));server.emit('request',req,res);await done;return {status:res.statusCode,data:Buffer.concat(chunks),headers};}
 return {dir,file,data,s,request};
}
test('actual CSS dispatcher serves the immutable matching style for GET and HEAD while preserving the old public file',async t=>{const f=fixture(t),r=await f.request('/assets/panels/growth.css?v=fixture');a.equal(r.status,200);a.deepEqual(r.data,f.data);a.equal(r.headers['content-type'],'text/css; charset=utf-8');a.equal(fs.readFileSync(f.dir+'/assets/panels/growth.css','utf8'),'old inherited style');const head=await f.request('/assets/panels/growth.css',{method:'HEAD'});a.equal(head.status,200);a.equal(head.data.length,0);});
test('missing native CSS selection keeps the inherited asset',async t=>{const f=fixture(t,{enabled:false}),r=await f.request('/assets/panels/growth.css');a.equal(r.status,200);a.equal(r.data.toString(),'old inherited style');});
test('hash changes and symlink replacement fail closed instead of serving unverified or inherited bytes',async t=>{const f=fixture(t);fs.writeFileSync(f.file,'.crm-sidebar{display:flex}');a.equal((await f.request('/assets/panels/growth.css')).status,503);fs.unlinkSync(f.file);fs.symlinkSync(f.dir+'/assets/panels/growth.css',f.file);a.equal((await f.request('/assets/panels/growth.css')).status,503);});
test('public style preserves allowed hosts and read method restrictions',async t=>{const f=fixture(t);a.equal((await f.request('/assets/panels/growth.css',{host:f.s.areaHosts.organico})).status,200);a.equal((await f.request('/assets/panels/growth.css',{host:'foreign.synthetic.invalid'})).status,421);a.equal((await f.request('/assets/panels/growth.css',{method:'POST'})).status,405);a.equal((await f.request('/assets/panels/growth.css',{host:f.s.areaHosts.growth})).status,200);});
