'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {HTML,JS}=require('./load-operator.cjs');
const {baseEvidence}=require('./fixture.cjs');
const id='11111111-1111-1111-1111-111111111111';
const status=()=>({schema:'shrigma-delivery-health-status-v1',enabled:true,databaseLinked:true,connections:[{id,label:'Minha conexão',brands:['fish','aristo']}],operational:false});
const consent=()=>({authorized:true,scope:'crm.delivery-health',brand:'aristo',operational:false});
const dto=()=>{const v=baseEvidence(),{marca,...brandMetrics}=v.brands[1];return {schema:'shrigma-original-email-health-read-v1',brand:'aristo',checkedAt:'2026-10-08T20:00:00Z',sourceCheckedAt:v.checked_at,collector:v.collector,queue:v.queue,brandMetrics,pendingIngest15min:0,conflicts:0,sharedQueue:true,authorizesSend:false,authorizesRecovery:false,operational:false};};
function harness(handler){const nodes={},events={},calls=[],timers=new Map();let seq=0;
 class E{constructor(){this.value='';this.checked=false;this.disabled=false;this.children=[];this._text='';}set textContent(v){this._text=v;this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('\n');}append(x){this.children.push(x);if(!this.value)this.value=x.value;}replaceChildren(){this.children=[];this.value='';}}
 for(const match of HTML.matchAll(/id="([^"]+)"/g))nodes[match[1]]=new E();
 const response=(v,code=200)=>({ok:code===200,status:code,headers:{get:()=>null},body:{getReader(){let done=false;return {async read(){if(done)return {done:true};done=true;return {done:false,value:new TextEncoder().encode(JSON.stringify(v))};},async cancel(){}};}}});
 const context={document:{getElementById:id=>nodes[id],createElement:()=>new E()},window:{addEventListener:(n,f)=>events[n]=f},AbortController,TextDecoder,Date,JSON,Number,Set,Error,Promise,setTimeout:(f,n)=>{const id=++seq;timers.set(id,{f,n});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,options)=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,options,body});const custom=handler?.(body,url,response);if(custom!==undefined)return custom;return response(body?.action==='status'?status():body?.action==='authorize'?consent():body?.action==='inspect'?dto():{authenticated:true,user:{role:'superadmin'},csrf:'session-csrf'});}};
 nodes['health-brand'].value='aristo';vm.runInNewContext(JS,context);return {nodes,events,calls,timers,response,async settle(){await new Promise(resolve=>setImmediate(resolve));},async authorize(){await this.settle();nodes['health-agree'].checked=true;nodes['health-agree'].onchange();await nodes['health-authorize'].onclick();await this.settle();}};
}

test('standalone original page no secrets and aggregate caveat',()=>{assert.match(HTML,/Leitura agregada; execução e entrega por fluxo ainda exigem evidência própria/);assert.match(HTML,/WhatsApp/);assert.doesNotMatch(HTML,/password|textarea|name="key"/);new vm.Script(JS);assert.doesNotMatch(JS,/innerHTML|setInterval|randomUUID/);});
test('automatic session/status only, own consent CSRF and redirect refusal',async()=>{const h=harness();await h.settle();assert.deepEqual(h.calls.map(x=>x.body?.action||'session'),['session','status']);assert.equal(h.nodes['health-read'].disabled,true);await h.authorize();assert.equal(h.nodes['health-read'].disabled,false);assert.deepEqual(h.calls.at(-1).body,{action:'authorize',connectionId:id,brand:'aristo',consent:true});for(const c of h.calls){assert.equal(c.options.redirect,'error');assert.equal(c.options.cache,'no-store');assert.equal(c.options.credentials,'same-origin');}assert.equal(h.calls.at(-1).options.headers['X-CSRF-Token'],'session-csrf');});
test('one explicit query displays unknown and zero distinctly',async()=>{const h=harness();await h.authorize();await h.nodes['health-read'].onclick();assert.deepEqual(h.calls.at(-1).body,{action:'inspect',connectionId:id,brand:'aristo'});const text=h.nodes['health-result'].textContent;assert.match(text,/desconhecido/);assert.match(text,/Finalização pendente: 0/);assert.match(text,/compartilhada/);assert.match(text,/evidência própria/);assert.equal(h.calls.filter(x=>x.body?.action==='inspect').length,1);});
for(const trigger of ['brand','connection','reload','pagehide'])test(trigger+' cancels and suppresses pending result',async()=>{let resolve;const h=harness((b,u,r)=>{if(b?.action==='inspect')return new Promise(res=>resolve=()=>res(r(dto())));});await h.authorize();const pending=h.nodes['health-read'].onclick();await h.settle();const signal=h.calls.at(-1).options.signal;if(trigger==='brand')h.nodes['health-brand'].onchange();if(trigger==='connection')h.nodes['health-connection'].onchange();if(trigger==='reload')await h.nodes['health-reload'].onclick();if(trigger==='pagehide')h.events.pagehide();assert.equal(signal.aborted,true);resolve();await pending;await h.settle();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
for(const [name,mutate] of [['other brand',v=>v.brand='fish'],['extra PII',v=>v.email='private'],['unknown count',v=>v.brandMetrics.falhas_24h=null],['queue string',v=>v.queue.visible='0'],['authorizes send',v=>v.authorizesSend=true]])test('UI refuses '+name,async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const v=dto();mutate(v);return r(v);}});await h.authorize();await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-authorize'].disabled,true);});
test('revocation 403 clears confirmed evidence and consent',async()=>{let revoke=false;const h=harness((b,u,r)=>b?.action==='inspect'&&revoke?r({},403):undefined);await h.authorize();await h.nodes['health-read'].onclick();assert.notEqual(h.nodes['health-result'].textContent,'');revoke=true;await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
test('bounded deadline aborts no retry; reload available',async()=>{const h=harness(b=>b?.action==='inspect'?new Promise(()=>{}):undefined);await h.authorize();const pending=h.nodes['health-read'].onclick();await h.settle();const timer=[...h.timers.values()][0];assert.equal(timer.n,70000);timer.f();await pending;assert.equal(h.calls.filter(x=>x.body?.action==='inspect').length,1);assert.equal(h.nodes['health-reload'].disabled,false);assert.equal(h.calls.at(-1).options.signal.aborted,true);});
test('oversized stream rejected; labels text only',async()=>{const h=harness((b,u,r)=>{if(b?.action==='status'){const v=status();v.connections[0].label='<img onerror=alert(1)>';return r(v);}if(b?.action==='inspect'){const v=r(dto());v.body.getReader=()=>({read:async()=>({done:false,value:new Uint8Array(32769)}),cancel:async()=>{}});return v;}});await h.authorize();assert.equal(h.nodes['health-connection'].children[0].textContent,'<img onerror=alert(1)>');await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');});
test('missing database no actions and reload clears confirmed data',async()=>{const h=harness();await h.authorize();await h.nodes['health-read'].onclick();await h.nodes['health-reload'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);const unlinked=harness((b,u,r)=>{if(b?.action==='status')return r({...status(),databaseLinked:false});});await unlinked.settle();unlinked.nodes['health-agree'].checked=true;unlinked.nodes['health-agree'].onchange();assert.equal(unlinked.nodes['health-authorize'].disabled,true);});

for(const [name,mutate] of [['invalid source calendar',v=>v.sourceCheckedAt='2026-02-30T12:00:00Z'],['error code array',v=>v.collector.last_error_code=['ERROR']],['collector extra',v=>v.collector.customerId='PII']])test('strict UI '+name,async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const v=dto();mutate(v);return r(v);}});await h.authorize();await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
