'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),pins=require('./pins.json');
const fail=()=>{throw Error('FACTS_CI_INPUT_REFUSED');};
function physical(p,file=false){if(!path.isAbsolute(p)||path.resolve(p)!==p)fail();let walk=path.parse(p).root;for(const segment of p.slice(walk.length).split('/').filter(Boolean)){walk=path.join(walk,segment);const s=fs.lstatSync(walk);if(s.isSymbolicLink())fail();if(walk!==p&&!s.isDirectory())fail();}const s=fs.lstatSync(p);if(file?(!s.isFile()||s.nlink!==1):!s.isDirectory())fail();}
function checked(root,e){const p=path.join(root,e.path);if(!p.startsWith(root+path.sep))fail();physical(p,true);const b=fs.readFileSync(p);if(b.length!==e.bytes||crypto.createHash('sha256').update(b).digest('hex')!==e.sha256||crypto.createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex')!==e.gitBlobSha1)fail();return b;}
function verifyInputs(root){physical(root);checked(root,pins.factsDelivery);checked(root,pins.contextManifest);checked(root,pins.custodyReference);if(pins.facts.length!==8||pins.context.length!==14)fail();return {facts:pins.facts.map(e=>[e.repoPath,checked(root,e)]),context:[['CONTEXT-MANIFEST.json',checked(root,pins.contextManifest)],...pins.context.map(e=>[e.relativePath,checked(root,e)])],schema:checked(root,pins.originalSchema)};}
function prepare({repositoryRoot,runnerTemp}){const input=verifyInputs(repositoryRoot);physical(runnerTemp);const prepared=path.join(runnerTemp,'control-facts-pg17-prepared');if(fs.existsSync(prepared))fail();let owned=false;try{fs.mkdirSync(prepared,{mode:0o700});owned=true;const source=path.join(prepared,'facts-source'),context=path.join(prepared,'public-context');for(const [root,entries] of [[source,input.facts],[context,input.context]]){fs.mkdirSync(root,{mode:0o700});for(const [relative,bytes] of entries){if(path.normalize(relative)!==relative||relative.startsWith('..')||path.isAbsolute(relative))fail();const p=path.join(root,relative);fs.mkdirSync(path.dirname(p),{recursive:true,mode:0o700});fs.writeFileSync(p,bytes,{flag:'wx',mode:0o600});physical(p,true);if(!fs.readFileSync(p).equals(bytes))fail();}}
 const originalSchema=path.join(prepared,'original-schema.sql');fs.writeFileSync(originalSchema,input.schema,{flag:'wx',mode:0o600});return Object.freeze({source,context,originalSchema,prepared,sourceFiles:8,contextFiles:14});
 }catch{if(owned)fs.rmSync(prepared,{recursive:true,force:true});fail();}}
function verifyPrepared(p){physical(p.prepared);for(const [root,entries,field] of [[p.source,pins.facts,'repoPath'],[p.context,pins.context,'relativePath']])for(const e of entries)checked(root,{...e,path:e[field]});checked(p.context,{...pins.contextManifest,path:'CONTEXT-MANIFEST.json'});checked(p.prepared,{...pins.originalSchema,path:'original-schema.sql'});}
module.exports=Object.freeze({physical,checked,verifyInputs,prepare,verifyPrepared});
