/* Public email images: legacy URL preparation plus an opt-in Listmonk library.
   Upload attempts are single-shot. An uncertain result is read back by the
   same generated filename and is never posted again automatically. */
const GMedia=(()=>{
 'use strict';
 const brands={fish:'Fishermans',aristo:'O Aristocrata'},drafts=new Map(),states=new Map(),VERSION='crm-media-v1',MAX=2*1024*1024,PIXELS=4*1024*1024,LEGACY='Arquivo antigo (sem marca)';
 let brand=null,context={};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clone=v=>JSON.parse(JSON.stringify(v));
 function publicImage(value){
  if(typeof value!=='string'||value.length>2048||/[\s<>"'\\]/.test(value))return null;
  try{const u=new URL(value),shopify=u.hostname==='cdn.shopify.com'&&u.pathname.startsWith('/s/files/'),listmonk=u.hostname==='email.shrigma.com.br'&&u.pathname.startsWith('/uploads/');if(u.protocol!=='https:'||u.username||u.password||u.port||u.hash||(!shopify&&!listmonk)||!/[.](png|jpe?g|gif|webp)$/i.test(u.pathname))return null;if([...u.searchParams.keys()].some(k=>!['v','width','height','crop','format','quality'].includes(k)))return null;return {url:u.href,host:shopify?'Shopify':'Listmonk'};}catch{return null;}
 }
 function snippet(url,alt){const image=publicImage(url);return image?`<img src="${esc(image.url)}" alt="${esc(alt)}" width="600" style="display:block;max-width:100%;height:auto;border:0;">`:null;}
 function inspect(bytes,type){
  const b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes),be=(at)=>(b[at]<<24>>>0)+(b[at+1]<<16)+(b[at+2]<<8)+b[at+3],le=at=>b[at]+(b[at+1]<<8);let image=null;
  if(b.length>=45&&[137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v)&&be(8)===13&&String.fromCharCode(...b.slice(12,16))==='IHDR'){let at=8,ended=false;while(at+12<=b.length){const size=be(at),kind=String.fromCharCode(...b.slice(at+4,at+8));if(size>MAX||at+12+size>b.length)break;at+=12+size;if(kind==='IEND'){ended=size===0&&at===b.length;break;}}if(ended)image={type:'image/png',ext:'png',width:be(16),height:be(20)};}
  else if(b.length>=14&&['GIF87a','GIF89a'].includes(String.fromCharCode(...b.slice(0,6)))&&b.at(-1)===59)image={type:'image/gif',ext:'gif',width:le(6),height:le(8)};
  else if(b.length>=4&&b[0]===255&&b[1]===216){const sof=new Set([192,193,194,195,197,198,199,201,202,203,205,206,207]);let at=2;while(at+3<b.length){while(at<b.length&&b[at]===255)at++;const marker=b[at++];if(marker===217||marker===218)break;if(marker===1||(marker>=208&&marker<=215))continue;if(at+1>=b.length)break;const size=(b[at]<<8)+b[at+1];if(size<2||at+size>b.length)break;if(sof.has(marker)&&size>=7){image={type:'image/jpeg',ext:'jpg',height:(b[at+3]<<8)+b[at+4],width:(b[at+5]<<8)+b[at+6]};break;}at+=size;}if(!(b.at(-2)===255&&b.at(-1)===217))image=null;}
  return image&&image.type===type&&image.width>0&&image.height>0&&image.width*image.height<=PIXELS?image:null;
 }
 function caps(api){
  const c=api?.capabilities?.campaigns;let endpoint=null;try{const u=new URL(api?.capabilities?.endpoints?.campaigns);if(u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash){u.pathname=u.pathname.replace(/\/$/,'')+'/media';endpoint=u.href;}}catch{}
  return {endpoint,available:c?.contract_version==='crm-campaign-v1'&&c.read===true&&Array.isArray(c.brands)?c.brands.filter(x=>Object.hasOwn(brands,x)):[]};
 }
 function stateFor(name){if(!states.has(name))states.set(name,{loaded:false,busy:false,page:0,next:null,items:[],selected:null,error:'',notice:''});return states.get(name);}
 function storage(){return context.storage||(typeof sessionStorage!=='undefined'?sessionStorage:null);}
 function journalSlot(name){return 'shrigma_media_upload_v1:'+name;}
 function validJournal(value,name,endpoint){return value?.version===1&&value.brand===name&&value.endpoint===endpoint&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value.operation_id)&&/^[0-9a-f]{64}$/.test(value.sha256)&&typeof value.filename==='string'&&value.filename.length<=180&&['pending','uncertain','missing','confirmed','rejected'].includes(value.phase);}
 function readJournal(name,endpoint){const box=storage();if(!box)return null;let value;try{value=JSON.parse(box.getItem(journalSlot(name))||'null');}catch{throw Error('O registro do upload não pôde ser lido. Preserve esta sessão e não repita o envio.');}if(value&&!validJournal(value,name,endpoint))throw Error('O registro do upload não confere. Preserve esta sessão e não repita o envio.');return value;}
 function saveJournal(value){const box=storage();if(!box)throw Error('O navegador não conseguiu preservar a tentativa. Nenhum upload foi iniciado.');const text=JSON.stringify(value);box.setItem(journalSlot(value.brand),text);if(box.getItem(journalSlot(value.brand))!==text)throw Error('O navegador não conseguiu preservar a tentativa. Nenhum upload foi iniciado.');}
 const readKey=()=>context.readKey?context.readKey():typeof GTA!=='undefined'?GTA.chaveLeitura():'';
 const writeKey=()=>context.writeKey?context.writeKey():typeof GRU!=='undefined'?GRU.chaveEscrita(true):'';
 const uuid=()=>context.uuid?context.uuid():crypto.randomUUID();
 async function digest(bytes){const out=context.digest?await context.digest(bytes):await crypto.subtle.digest('SHA-256',bytes);return typeof out==='string'?out:[...new Uint8Array(out)].map(x=>x.toString(16).padStart(2,'0')).join('');}
 async function call(method,endpoint,{params,form,key}){try{const u=new URL(endpoint);if(params)u.search=new URLSearchParams(params);const init={method,headers:{Authorization:'Bearer '+key},cache:'no-store',credentials:'omit',redirect:'error',signal:typeof AbortSignal!=='undefined'&&AbortSignal.timeout?AbortSignal.timeout(method==='POST'?30000:20000):undefined};if(form)init.body=form;const r=await (context.fetch||fetch)(u.href,init);let body=null;try{body=await r.json();}catch{}return {ok:r.status>=200&&r.status<300,status:r.status,body};}catch{return {ok:false,status:0,body:null};}}
 function validMedia(item){return Number.isSafeInteger(item?.id)&&item.id>0&&typeof item.filename==='string'&&item.filename.length<=180&&['image/png','image/jpeg','image/gif'].includes(item.content_type)&&Number.isSafeInteger(item.width)&&item.width>0&&Number.isSafeInteger(item.height)&&item.height>0&&item.width*item.height<=PIXELS&&publicImage(item.url)?.host==='Listmonk';}
 function endpoint(){const c=caps(context.api);return brand&&c.available.includes(brand)?c.endpoint:null;}
 function filename(name,id,hash,ext){return `crm-${name}-${id}-${hash}.${ext}`;}
 function resetPrepared(root){root.querySelector('#crm-media-picture').replaceChildren();root.querySelector('#crm-media-picture').hidden=true;root.querySelector('#crm-media-output-label').hidden=true;root.querySelector('#crm-media-output').value='';const valid=!!brand&&!!publicImage(root.querySelector('#crm-media-url').value);for(const id of ['crm-media-copy-url','crm-media-copy-html'])root.querySelector('#'+id).disabled=!valid;}
 function renderLibrary(){
  const root=document.getElementById('crm-media');if(!root)return;const state=brand?stateFor(brand):null,service=endpoint(),box=root.querySelector('#crm-media-library'),upload=root.querySelector('#crm-media-upload-fields');let journal=null,journalBlocked=false;try{journal=brand&&service?readJournal(brand,service):null;}catch(e){journalBlocked=true;if(state)state.error=e.message;}
  root.querySelector('#crm-media-library-load').disabled=!brand||state?.busy;upload.hidden=!service||!state?.loaded;root.querySelector('#crm-media-file').disabled=!service||!state?.loaded||state?.busy||journalBlocked||['pending','uncertain'].includes(journal?.phase);root.querySelector('#crm-media-upload').disabled=!state?.selected||state?.busy||journalBlocked||['pending','uncertain','missing'].includes(journal?.phase);
  const retry=root.querySelector('#crm-media-retry'),recover=root.querySelector('#crm-media-recover');recover.hidden=!['pending','uncertain'].includes(journal?.phase);retry.hidden=journal?.phase!=='missing'||!state?.selected;retry.disabled=state?.busy;
  root.querySelector('#crm-media-library-status').textContent=state?.error||state?.notice||(!service?'A biblioteca integrada ainda não está disponível. Use os atalhos ou cole um endereço público.':journal?.phase==='missing'?'A biblioteca confirmou que o arquivo ainda não aparece. Uma nova tentativa manual pode criar uma cópia caso o primeiro upload termine com atraso.':journal&&['pending','uncertain'].includes(journal.phase)?'O resultado do upload está pendente. Confira a mesma tentativa; nenhum novo envio será feito automaticamente.':state?.loaded?'Biblioteca carregada.':'Abra a biblioteca para consultar os arquivos públicos.');
  if(!state?.loaded){box.replaceChildren();return;}
  // legacy:true (formato do validador, §9.2): arquivo sem marca no nome; aparece nas duas marcas e nunca conta como da marca.
  box.innerHTML=state.items.length?state.items.map((item,i)=>`<button type="button" data-media-index="${i}"${item.legacy===true?' data-media-legacy':''}><img src="${esc(item.thumb_url||item.url)}" alt="" referrerpolicy="no-referrer"><span>${esc(item.filename)}</span><small>${esc(item.width)} × ${esc(item.height)}</small>${item.legacy===true?`<small class="crm-media-legacy">${esc(LEGACY)}</small>`:''}</button>`).join(''):'<p class="mini">Nenhuma imagem encontrada.</p>';
  for(const button of box.querySelectorAll('[data-media-index]'))button.onclick=()=>{const item=state.items[Number(button.dataset.mediaIndex)];if(!validMedia(item))return;root.querySelector('#crm-media-url').value=item.url;resetPrepared(root);root.querySelector('#crm-media-status').textContent='Imagem da biblioteca selecionada. Confira a prévia antes de copiar.';};
  root.querySelector('#crm-media-next').hidden=!state.next;root.querySelector('#crm-media-next').disabled=state.busy;
 }
 async function loadLibrary(next=false){
  const state=stateFor(brand),service=endpoint(),selection=brand;if(!service||state.busy)return;state.busy=true;state.error='';state.notice='Consultando a biblioteca…';renderLibrary();
  const page=next&&state.next?state.next:1,res=await call('GET',service,{params:{brand:selection,page,per_page:24},key:readKey()});state.busy=false;
  if(!res.ok||res.body?.contract!==VERSION||res.body.brand!==selection||!Array.isArray(res.body.items)||res.body.items.some(x=>!validMedia(x)||x.legacy!==undefined&&typeof x.legacy!=='boolean')){state.loaded=false;state.error=res.status===401?'Informe novamente o acesso de leitura para abrir a biblioteca.':res.status===403?(res.body?.error==='ORIGIN_DENIED'?'O serviço de imagens recusou a origem deste painel. Abra o painel pelo endereço oficial; nada foi enviado.':'Este acesso não tem permissão para consultar a biblioteca de imagens. Peça um acesso com leitura de conteúdo.'):'A biblioteca integrada não está disponível agora. Use os atalhos ou cole um endereço público.';state.notice='';if(brand===selection)renderLibrary();return;}
  state.loaded=true;state.page=res.body.page;state.next=res.body.next_page;state.items=next?[...state.items,...res.body.items]:res.body.items;const legacy=state.items.filter(x=>x.legacy===true).length;state.notice=legacy?`${state.items.length-legacy} imagem(ns) da marca e ${legacy} arquivo(s) antigo(s) sem marca carregado(s).`:`${state.items.length} imagem(ns) carregada(s).`;if(brand===selection)renderLibrary();
 }
 async function selectFile(file){
  const selection=brand,state=stateFor(selection),root=document.getElementById('crm-media');state.selected=null;resetPrepared(root);if(!file)return renderLibrary();if(file.size>MAX||!['image/png','image/jpeg','image/gif'].includes(file.type)){state.error='Escolha PNG, JPEG ou GIF com até 2 MB.';return renderLibrary();}
  const bytes=new Uint8Array(await file.arrayBuffer()),image=inspect(bytes,file.type);if(brand!==selection)return;if(!image){state.error='A imagem é inválida ou excede 4 megapixels.';return renderLibrary();}const hash=await digest(bytes.buffer);if(brand!==selection)return;state.selected={file,bytes,image,hash};state.error='';state.notice=`Arquivo pronto: ${image.width} × ${image.height}.`;
  const picture=root.querySelector('#crm-media-picture'),img=document.createElement('img');picture.replaceChildren(img);picture.hidden=false;img.alt=root.querySelector('#crm-media-alt').value;const objectURL=(context.createObjectURL||(typeof URL!=='undefined'&&URL.createObjectURL?.bind(URL)))?.(file);if(objectURL)img.src=objectURL;renderLibrary();
 }
 function validateUploadResponse(body,operation){return body?.contract===VERSION&&body.brand===operation.brand&&body.operation_id===operation.operation_id&&body.sha256===operation.sha256&&['created','existing'].includes(body.state)&&validMedia(body.media);}
 async function upload(retry=false){
  const state=stateFor(brand),service=endpoint(),selection=brand;if(!service||state.busy||!state.selected)return;const locks=context.locks||(typeof navigator!=='undefined'?navigator.locks:null);if(typeof locks?.request!=='function'){state.error='O navegador não oferece proteção entre abas. O upload não foi iniciado.';return renderLibrary();}
  await locks.request('shrigma_media_upload_v1:'+selection,{mode:'exclusive',ifAvailable:true},async lock=>{if(brand!==selection)return;if(!lock){state.error='Outra aba está operando a biblioteca desta marca.';return renderLibrary();}let prior=readJournal(selection,service),operation;
   if(retry){if(prior?.phase!=='missing'||prior.sha256!==state.selected.hash||!confirm('A biblioteca não encontrou o arquivo. Tentar novamente pode criar uma cópia se o primeiro upload terminar com atraso. Deseja continuar?'))return;operation={...prior,phase:'pending',retried_at:new Date().toISOString()};}
   else{if(prior&&['pending','uncertain','missing'].includes(prior.phase)){state.error='Confira a tentativa preservada antes de iniciar outro upload.';return renderLibrary();}const id=uuid();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)){state.error='O navegador não conseguiu criar a identidade do upload. Nada foi enviado.';return renderLibrary();}operation={version:1,brand:selection,endpoint:service,operation_id:id,sha256:state.selected.hash,filename:filename(selection,id,state.selected.hash,state.selected.image.ext),phase:'pending',created_at:new Date().toISOString()};}
   saveJournal(operation);state.busy=true;state.error='';state.notice='Enviando uma única vez…';renderLibrary();const form=new FormData();form.append('brand',selection);form.append('operation_id',operation.operation_id);form.append('sha256',operation.sha256);form.append('file',state.selected.file,operation.filename);const key=writeKey();let res=key?await call('POST',service,{form,key}):{ok:false,status:401,body:{posted:false,error:'UNAUTHORIZED'}};state.busy=false;
   if(res.ok&&validateUploadResponse(res.body,operation)){operation={...operation,phase:'confirmed',media:clone(res.body.media),confirmed_at:new Date().toISOString()};saveJournal(operation);state.items=[res.body.media,...state.items.filter(x=>x.id!==res.body.media.id)];state.loaded=true;state.selected=null;if(brand===selection){document.getElementById('crm-media-url').value=res.body.media.url;resetPrepared(document.getElementById('crm-media'));}state.notice='Upload confirmado e imagem selecionada.';state.error='';}
   else if(res.body?.posted===false&&[401,403,409,413,422,503].includes(res.status)){saveJournal({...operation,phase:'rejected',error:res.body?.error||'MEDIA_REJECTED'});state.error=res.status===401?'Informe novamente o acesso de edição. Nenhum arquivo foi enviado.':res.body?.message||'O arquivo foi recusado antes do envio.';}
   else{saveJournal({...operation,phase:'uncertain',uncertain_at:new Date().toISOString()});state.error='O resultado não foi confirmado. Use “Conferir tentativa”; nenhum novo upload será feito automaticamente.';}if(brand===selection)renderLibrary();
  });
 }
 async function recover(){
  const state=stateFor(brand),service=endpoint(),selection=brand,journal=readJournal(brand,service);if(!journal||!['pending','uncertain'].includes(journal.phase)||state.busy)return;state.busy=true;state.error='';state.notice='Conferindo a mesma tentativa…';renderLibrary();const res=await call('GET',service,{params:{brand:selection,operation_id:journal.operation_id,filename:journal.filename,sha256:journal.sha256},key:readKey()});state.busy=false;
  const same=res.ok&&res.body?.contract===VERSION&&res.body.brand===selection&&res.body.operation_id===journal.operation_id&&res.body.filename===journal.filename&&res.body.sha256===journal.sha256;
  if(same&&res.body.state==='found'&&validMedia(res.body.media)){saveJournal({...journal,phase:'confirmed',media:clone(res.body.media),confirmed_at:new Date().toISOString()});state.items=[res.body.media,...state.items.filter(x=>x.id!==res.body.media.id)];state.loaded=true;if(brand===selection){document.getElementById('crm-media-url').value=res.body.media.url;resetPrepared(document.getElementById('crm-media'));}state.notice='Upload encontrado na biblioteca e imagem selecionada.';state.error='';}
  else if(same&&res.body.state==='missing'&&res.body.media===null){saveJournal({...journal,phase:'missing',checked_at:new Date().toISOString()});state.notice='';state.error='';}
  else{state.error='A consulta não confirmou o resultado. Preserve esta sessão e tente conferir novamente.';state.notice='';}if(brand===selection)renderLibrary();
 }
 function mount(options={}){
  const root=document.getElementById('crm-media');if(!root)return;const next=Object.hasOwn(brands,options.marca)?options.marca:null;context={...context,...options};
  if(root.querySelector('#crm-media-url')&&brand!==next&&brand)drafts.set(brand,{url:root.querySelector('#crm-media-url').value,alt:root.querySelector('#crm-media-alt').value});
  if(!root.querySelector('#crm-media-url')){
   root.innerHTML=`<div class="painel-cab"><h2>Imagens públicas</h2></div><p id="crm-media-brand" class="mini"></p><p>Use uma imagem já publicada ou abra a biblioteca integrada quando estiver disponível.</p><div class="crm-media-hosts"><button type="button" class="btn sec" id="crm-media-library-load">Abrir biblioteca no painel</button><a class="btn sec" href="https://email.shrigma.com.br/admin/campaigns/media" target="_blank" rel="noopener noreferrer">Abrir Listmonk ↗</a><a class="btn sec" href="https://admin.shopify.com/" target="_blank" rel="noopener noreferrer">Abrir Shopify ↗</a></div><p class="mini">Os atalhos usam o acesso próprio de cada serviço. Links públicos existentes continuam disponíveis mesmo quando a biblioteca integrada está desligada.</p><div class="crm-media-integrated"><p id="crm-media-library-status" role="status" class="mini"></p><fieldset id="crm-media-upload-fields" hidden><legend>Novo arquivo</legend><label for="crm-media-file">PNG, JPEG ou GIF, até 2 MB e 4 megapixels<input id="crm-media-file" type="file" accept="image/png,image/jpeg,image/gif"></label><div class="crm-media-actions"><button type="button" class="btn sec" id="crm-media-upload" disabled>Subir imagem</button><button type="button" class="btn sec" id="crm-media-recover" hidden>Conferir tentativa</button><button type="button" class="btn sec" id="crm-media-retry" hidden>Tentar novamente</button></div></fieldset><div id="crm-media-library" class="crm-media-library"></div><button type="button" class="btn sec" id="crm-media-next" hidden>Carregar mais</button></div><fieldset id="crm-media-fields"><legend>Preparar imagem para o e-mail</legend><label for="crm-media-url">Endereço público da imagem<input id="crm-media-url" type="url" inputmode="url" maxlength="2048" placeholder="https://cdn.shopify.com/s/files/…/imagem.jpg" autocomplete="off" spellcheck="false"></label><label for="crm-media-alt">Descrição da imagem<input id="crm-media-alt" type="text" maxlength="240" placeholder="Descrição curta para quem não consegue ver a imagem"></label><div class="crm-media-actions"><button type="button" class="btn sec" id="crm-media-preview">Conferir imagem</button><button type="button" class="btn sec" id="crm-media-copy-url" disabled>Copiar endereço</button><button type="button" class="btn sec" id="crm-media-copy-html" disabled>Copiar HTML para o e-mail</button></div><p id="crm-media-status" role="status" class="mini"></p><div id="crm-media-picture" hidden></div><label for="crm-media-output" id="crm-media-output-label" hidden>Conteúdo pronto para copiar<textarea id="crm-media-output" readonly rows="3"></textarea></label></fieldset>`;
   const reset=()=>{resetPrepared(root);root.querySelector('#crm-media-status').textContent='';};root.querySelector('#crm-media-url').addEventListener('input',reset);root.querySelector('#crm-media-alt').addEventListener('input',reset);
   root.querySelector('#crm-media-preview').onclick=()=>{const image=publicImage(root.querySelector('#crm-media-url').value),status=root.querySelector('#crm-media-status');if(!brand||!image){status.textContent='Selecione uma marca e informe um link HTTPS público de PNG, JPG, GIF ou WebP da Shopify ou do Listmonk.';return;}const box=root.querySelector('#crm-media-picture'),img=document.createElement('img'),selection=brand;box.replaceChildren(img);box.hidden=false;img.alt=root.querySelector('#crm-media-alt').value;img.referrerPolicy='no-referrer';status.textContent='Carregando a prévia…';img.onload=()=>{if(brand===selection&&box.contains(img))status.textContent='Prévia carregada. Confira a marca e o conteúdo.';};img.onerror=()=>{if(brand===selection&&box.contains(img))status.textContent='A prévia não pôde ser carregada. Confira o link público.';};img.src=image.url;};
   for(const kind of ['url','html'])root.querySelector('#crm-media-copy-'+kind).onclick=async()=>{const image=publicImage(root.querySelector('#crm-media-url').value);if(!brand||!image)return;const selection=brand,text=kind==='url'?image.url:snippet(image.url,root.querySelector('#crm-media-alt').value),output=root.querySelector('#crm-media-output');output.value=text;root.querySelector('#crm-media-output-label').hidden=false;output.focus();output.select?.();try{await navigator.clipboard.writeText(text);if(brand===selection)root.querySelector('#crm-media-status').textContent='Copiado. Cole no conteúdo do e-mail e confira a prévia antes de salvar.';}catch{if(brand===selection)root.querySelector('#crm-media-status').textContent='Selecione e copie o conteúdo exibido abaixo.';}};
   root.querySelector('#crm-media-library-load').onclick=()=>loadLibrary(false);root.querySelector('#crm-media-next').onclick=()=>loadLibrary(true);root.querySelector('#crm-media-file').onchange=e=>selectFile(e.target.files?.[0]);root.querySelector('#crm-media-upload').onclick=()=>upload(false);root.querySelector('#crm-media-recover').onclick=recover;root.querySelector('#crm-media-retry').onclick=()=>upload(true);
  }
  if(brand!==next){brand=next;const saved=drafts.get(brand)||{url:'',alt:''};root.querySelector('#crm-media-url').value=saved.url;root.querySelector('#crm-media-alt').value=saved.alt;resetPrepared(root);root.querySelector('#crm-media-status').textContent='';}
  root.querySelector('#crm-media-brand').textContent=brand?'Preparando imagem para '+brands[brand]+'. O link não identifica a marca automaticamente.':'Selecione Fishermans ou O Aristocrata para preparar a imagem.';root.querySelector('#crm-media-fields').disabled=!brand;renderLibrary();
 }
 return {publicImage,snippet,inspect,caps,mount};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=GMedia;
