'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const sourceRoot=process.env.DB_INVENTORY_SOURCE||path.resolve(__dirname,'../../..'),runtime=process.env.DB_INVENTORY_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const S=require(path.join(runtime,'native-health-view-structure.cjs')),I=require(path.join(runtime,'native-database-inventory.cjs'));
const canonical=fs.readFileSync(path.join(sourceRoot,'inputs/canonical/CANONICAL-NORMALIZED.sql'),'utf8');
const keys=['structure_status','definition_tokens_sha256','recent_cte_tokens_sha256','brands_cte_tokens_sha256','brands_value_tokens_sha256','canonical_recent_match','canonical_brands_cte_match','canonical_brands_value_match'];
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),sort=x=>JSON.stringify(x,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
const compare=x=>S.compareHealthViewStructure(x);
function safe(v,status){assert.deepEqual(Object.keys(v),keys);assert(Object.isFrozen(v));if(status)assert.equal(v.structure_status,status);for(const k of keys.slice(1,5))assert(v[k]===null||typeof v[k]==='string'&&/^[a-f0-9]{64}$/.test(v[k]));for(const k of keys.slice(5))assert(v[k]===null||typeof v[k]==='boolean');if(v.structure_status==='unknown')assert(keys.slice(1).every(k=>v[k]===null));return v;}
const context={ownerId:'original-owner-fixture'},privateSecret='SYNTHETIC_DB_PASSWORD',marker='PRIVATE_DEFINITION_MARKER_NOT_FOR_OUTPUT';
function rawRow(source=canonical){return {oid:'135626',namespace:'public',name:'shrigma_growth_email_ses_health_v1',ownerRole:'postgres',acl:null,definition_utf8_bytes:Buffer.byteLength(source),definition_sha256:sha(source),fixed_fish_aristo_values_seed:false,empty_brands_literal:false,brands_jsonb_agg:true,_definition_source:source};}
function fixture(options={}){
 const calls=[],clients=[],proofs=[],credential={schema:'shrigma-private-database-credential-v1',revision:1,ownerId:context.ownerId,username:'fixture-reader',password:privateSecret,resource:{...I.RESOURCE},transport:{mode:'admitted-private-network'}};
 class Client extends EventEmitter{
  constructor(config){super();this.config=config;this.processID=101;this.connection=new EventEmitter();this.connection.stream={encrypted:false};this.ends=0;this.tx='I';clients.push(this);}
  ack(state){this.tx=state;this.connection.emit('readyForQuery',{status:state});}
  async connect(){this.ack('I');}
  async query(sql){calls.push(sql);let r,state;if(sql===I.PEER){state='I';r={command:'SELECT',rowCount:1,rows:[{database:'listmonk',sessionRole:credential.username,currentRole:credential.username,pid:101,port:5432,engine:170010,ssl:false,read_only:'on'}]};}else if(sql===I.BEGIN||sql===I.ROLLBACK){state=sql===I.BEGIN?'T':'I';r={command:sql===I.BEGIN?'BEGIN':'ROLLBACK',rowCount:null,rows:[]};}else{assert(Object.values(I.CATALOG).some(d=>d.sql===sql));state='T';const rows=sql===I.CATALOG.healthView.sql?[options.row===undefined?rawRow(options.source):options.row]:[];r={command:'SELECT',rowCount:rows.length,rows};}if(options.result)r=options.result(sql,r);this.ack(options.badAck===sql?'E':state);return r;}
  async end(){this.ends++;if(options.endThrow)throw Error(marker);if(!options.noEndEvent)this.emit('end');}
 }
 const service=I.createDatabaseInventory({enabled:true,driver:{Client,version:'8.23.1',packageSha256:'c'.repeat(64)},getPrivateCredential:()=>credential,admitInspection:p=>{proofs.push(p);if(p.phase===options.deny)throw Error(marker);const {password,...pub}=credential;return {admitted:true,ownerId:context.ownerId,profileRevision:credential.revision,credentialBindingHash:sha(sort(pub)),resourceHash:sha(sort(I.RESOURCE)),purpose:'read-only-migration-inventory'};}});
 return {service,calls,clients,proofs,inspect:()=>service.inspect({},context)};
}
const decoded=v=>Object.fromEntries(v.data.healthView.fields.map((k,i)=>[k,v.data.healthView.rows[0][i]]));
test('canonical provenance4739/hash, linked components all match, primitives only',()=>{assert.equal(Buffer.byteLength(canonical),S.CANONICAL.bytes);assert.equal(sha(canonical),S.CANONICAL.sha256);assert.equal(S.CANONICAL.postgresVersionNum,170005);const v=safe(compare(canonical),'parsed');assert.equal(v.canonical_recent_match,true);assert.equal(v.canonical_brands_cte_match,true);assert.equal(v.canonical_brands_value_match,true);assert(!JSON.stringify(v).includes('SELECT'));});
test('whitespace/comments preserve identity; normalized FROM((VALUES parses',()=>{const expected=compare(canonical);for(const sql of [canonical.replace(/\n[ \t]*/g,'\n '),'/* WITH brands AS (SELECT foreign()) */\n'+canonical,canonical.replace('WITH recent','WITH /* nested /* comment */ safe */ recent'),canonical.replace('jsonb_build_object(',"jsonb_build_object(/* 'brands', SELECT unknown */ ")])assert.deepEqual(safe(compare(sql),'parsed'),expected);assert.match(canonical,/FROM \(\( VALUES/);const less=canonical.replace("FROM (( VALUES ('fish'::text), ('aristo'::text)) b(marca)","FROM (VALUES ('fish'::text), ('aristo'::text)) b(marca)").replace('USING (marca))))','USING (marca)))');safe(compare(less),'parsed');});
for(const [name,modify,expected] of [
 ['recent',x=>x.replace("'delivery'::text","'OTHER_PRIVATE_STATUS'::text"),[false,true,true]],
 ['brands CTE',x=>x.replace("recent.transport_state = 'outcome_unknown'::text","recent.transport_state = 'accepted'::text"),[true,false,true]],
 ['brands value',x=>x.replace("('fish'::text), ('aristo'::text)","('aristo'::text), ('fish'::text)"),[true,true,false]],
 ['final collector expression',x=>x.replace('clock_timestamp()','now()'),[true,true,true]],
 ['quoted identifier recent',x=>x.replace('d.dispatch_id','d."dispatch_id"'),[false,true,true]],
 ['preserved whitespace within string',x=>x.replace("'delivery'::text","'delivery  brands'::text"),[false,true,true]]
])test('identity change isolated '+name,()=>{const v=safe(compare(modify(canonical)),'parsed');assert.deepEqual(keys.slice(5).map(k=>v[k]),expected);assert.notEqual(v.definition_tokens_sha256,compare(canonical).definition_tokens_sha256);assert.doesNotMatch(JSON.stringify(v),/OTHER_PRIVATE|delivery|dispatch_id/);});
for(const literal of ["'it''s brands SELECT'",String.raw`E'it\'s brands SELECT'`,'$private$WITH brands AS (SELECT foreign()) "brands"$private$','$$brands, SELECT foreign()$$'])test('string/escaped/dollar content cannot become structure '+literal.slice(0,10),()=>{const v=safe(compare(canonical.replace("'delivery'::text",()=>literal+'::text')),'parsed');assert.equal(v.canonical_recent_match,false);assert.equal(v.canonical_brands_cte_match,true);assert.equal(v.canonical_brands_value_match,true);assert.doesNotMatch(JSON.stringify(v),/foreign|private|SELECT/);});
for(const [name,source] of [
 ['incidental only',"SELECT 'WITH recent AS (SELECT 1), brands AS (SELECT 1) SELECT jsonb_build_object(''brands'', 1) AS payload'"],
 ['foreign function',canonical.replace('clock_timestamp()','foreign_secret()')],
 ['foreign qualified builtin',canonical.replace('clock_timestamp()','public.clock_timestamp()')],
 ['foreign quoted function',canonical.replace('clock_timestamp()','"foreign"()')],
 ['duplicate key',canonical.replace("'conflicts', ( SELECT","'brands', ( SELECT")],
 ['duplicate CTE',canonical.replace('), brands AS (', '), recent AS (')],
 ['third CTE',canonical.replace('\n SELECT jsonb_build_object', ', extra AS (SELECT 1)\n SELECT jsonb_build_object')],
 ['UNION',canonical.replace('FROM recent', 'FROM recent UNION SELECT 1')],
 ['extra SELECT',canonical.replace('FROM recent', 'FROM recent SELECT 1')],
 ['SELECT union final',canonical.replace(/;$/, ' UNION SELECT 1;')],
 ['foreign final relation',canonical.replace('public.shrigma_email_consumer_health','public.other_private_table')],
 ['wrong final alias',canonical.replace(' AS payload',' AS other_payload')],
 ['final builder absent',canonical.replace('SELECT jsonb_build_object','SELECT foreign_object')],
 ['duplicate statement',canonical+' SELECT 1;'],
 ['unterminated comment',canonical+' /*'],
 ['unterminated quote',canonical+" 'private"],
 ['unterminated dollar',canonical+' $private$missing'],
 ['NUL',canonical+'\0']
])test('closed grammar safely unknown '+name,()=>safe(compare(source),'unknown'));
test('source/depth/token/comment bounds and nonprimitive/proxies/getters safe',()=>{const exact=canonical+' '.repeat(S.LIMITS.bytes-Buffer.byteLength(canonical));safe(compare(exact),'parsed');safe(compare(exact+' '),'unknown');const many=canonical.replace('SELECT d.dispatch_id,','SELECT '+ '1,'.repeat(9000)+'d.dispatch_id,');assert(Buffer.byteLength(many)<S.LIMITS.bytes);safe(compare(many),'unknown');safe(compare(canonical.replace('d.dispatch_id','('.repeat(65)+'d.dispatch_id'+')'.repeat(65))),'unknown');safe(compare('/*'.repeat(65)+'*/'.repeat(65)+canonical),'unknown');safe(compare(canonical+'\ud800'),'unknown');let calls=0;const getter=()=>{calls++;throw Error(marker);};for(const x of [null,undefined,1,[],{toString:getter},new Proxy({}, {get:getter,getPrototypeOf:getter}),Object.create({toJSON:getter})])safe(compare(x),'unknown');assert.equal(calls,0);});
test('inventory private11 to public18 projects safe linked hashes only, original purpose/ACK/end',async()=>{const f=fixture(),v=await f.inspect(),r=decoded(v);assert.equal(v.schema,'shrigma-database-inventory-v4');assert.equal(v.data.healthView.fields.length,18);assert(!v.data.healthView.fields.includes('_definition_source'));assert.equal(r.structure_status,'parsed');assert.equal(r.canonical_recent_match,true);assert.equal(r.canonical_brands_cte_match,true);assert.equal(r.canonical_brands_value_match,true);const serialized=JSON.stringify(v);assert(!serialized.includes(canonical));assert(!serialized.includes('_definition_source'));assert(!serialized.includes('SELECT d.dispatch_id'));assert(!serialized.includes(privateSecret));assert.equal(v.operational,false);assert.equal(v.classification,'unknown');assert.deepEqual(f.proofs.map(p=>p.phase),['connect','catalog']);assert(f.proofs.every(p=>p.purpose==='read-only-migration-inventory'));assert.deepEqual(f.calls,[I.PEER,I.BEGIN,...Object.values(I.CATALOG).map(d=>d.sql),I.ROLLBACK]);assert.equal(f.clients[0].ends,1);await f.service.close();});
test('unknown parser with valid source binding does not fail catalog or expose source',async()=>{const source='SELECT unknown_'+marker+'();',f=fixture({source}),v=await f.inspect(),r=decoded(v);assert.equal(r.structure_status,'unknown');for(const k of keys.slice(1))assert.equal(r[k],null);assert.equal(v.complete,true);assert.equal(v.operational,false);assert(!JSON.stringify(v).includes(marker));await f.service.close();});
for(const [name,modify] of [['missing',r=>{delete r._definition_source;return r;}],['bytes mismatch',r=>({...r,definition_utf8_bytes:r.definition_utf8_bytes+1})],['hash mismatch',r=>({...r,definition_sha256:'f'.repeat(64)})],['nonstring source',r=>({...r,_definition_source:{toString(){assert.fail('coercion');}}})],['source overflow',r=>({...r,...rawRow('x'.repeat(65537))})],['raw extra',r=>({...r,unknown_source:marker})],['public extra',r=>({...r,structure_status:'parsed'})]])test('private projection refuses '+name,async()=>{const f=fixture({row:modify(rawRow())});await assert.rejects(f.inspect(),e=>{assert.equal(e.code,'INVENTORY_VIEW_PROTOCOL_REFUSED');assert(!String(e).includes(marker));return true;});assert.equal(f.clients[0].ends,1);assert.equal(f.calls.filter(q=>q===I.CATALOG.healthView.sql).length,1);await f.service.close();});
test('private getter/proxy/hidden/symbol refused before access/coercion',async()=>{let calls=0;const getter=()=>{calls++;throw Error(marker);};for(const modify of [r=>Object.defineProperty(r,'_definition_source',{enumerable:true,get:getter}),r=>new Proxy(r,{get:getter,getPrototypeOf:getter,ownKeys:getter}),r=>Object.assign(r,{[Symbol('secret')]:marker}),r=>Object.defineProperty(r,'_definition_source',{enumerable:false,value:canonical})]){const f=fixture({row:modify(rawRow())});await assert.rejects(f.inspect(),{code:'INVENTORY_VIEW_PROTOCOL_REFUSED'});assert.equal(f.clients[0].ends,1);await f.service.close();}assert.equal(calls,0);});
for(const options of [{deny:'connect'},{deny:'catalog'},{badAck:I.CATALOG.healthView.sql},{noEndEvent:true},{endThrow:true}])test('admission/ACK/end failure cannot publish private projection '+Object.keys(options),async()=>{const f=fixture(options);await assert.rejects(f.inspect(),e=>{assert(!String(e).includes(marker));assert(!String(e).includes(canonical));return true;});assert(f.clients.every(c=>c.ends===1));if(options.deny)assert(!f.calls.includes(I.CATALOG.healthView.sql));await f.service.close().catch(()=>{});});

test('final brands empty literal is linked component difference, never incidental CTE match or health proof',()=>{const at=canonical.lastIndexOf("'brands',"),end=canonical.indexOf(' AS payload',at);const sql=canonical.slice(0,at)+"'brands', '[]'::jsonb)"+canonical.slice(end);const v=safe(compare(sql),'parsed');assert.equal(v.canonical_recent_match,true);assert.equal(v.canonical_brands_cte_match,true);assert.equal(v.canonical_brands_value_match,false);assert(!JSON.stringify(v).includes('[]'));});
test('foreign function within a CTE and duplicate SELECT within brands value stay unknown',()=>{safe(compare(canonical.replace("COALESCE(s.complaint_type",'public.foreign_fn(s.complaint_type')),'unknown');safe(compare(canonical.replace("FROM (( VALUES",'SELECT 1 FROM (( VALUES')),'unknown');});
test('literal whitespace and quoted identifier escapes are retained as identity',()=>{const a=compare(canonical.replace("'delivery'::text","'a  brands'::text")),b=compare(canonical.replace("'delivery'::text","'a brands'::text"));safe(a,'parsed');safe(b,'parsed');assert.notEqual(a.recent_cte_tokens_sha256,b.recent_cte_tokens_sha256);const quoted=safe(compare(canonical.replace('d.dispatch_id','d."dispatch""id"')),'parsed');assert.equal(quoted.canonical_recent_match,false);});
test('source primitive evaluated once from own descriptor; Unicode UTF8 bytes/hash precede safe parse',async()=>{const source=canonical.replace("'delivery'::text","'á marcas 私'::text"),f=fixture({source}),v=await f.inspect();assert.equal(decoded(v).definition_utf8_bytes,Buffer.byteLength(source));assert.equal(decoded(v).definition_sha256,sha(source));assert.equal(decoded(v).canonical_recent_match,false);assert(!JSON.stringify(v).includes('私'));assert.equal(f.clients[0].ends,1);await f.service.close();});
test('parser has no variable regex/eval/SQL execution surface and canonical constants are frozen',()=>{const source=fs.readFileSync(path.join(runtime,'native-health-view-structure.cjs'),'utf8');assert.doesNotMatch(source,/\beval\s*\(|new\s+Function|new\s+RegExp|\.query\s*\(|pg_get_viewdef/);assert(Object.isFrozen(S.CANONICAL));assert(Object.isFrozen(S.LIMITS));assert.equal(S.LIMITS.bytes,65536);assert.equal(S.LIMITS.depth,64);assert.equal(S.LIMITS.tokens,16384);});

test('line comment terminates at CR or LF without dropping structural tokens',()=>{const expected=compare(canonical);for(const newline of ['\r','\n','\r\n'])assert.deepEqual(compare(canonical.replace('WITH recent','WITH -- ignored brands SELECT foreign()'+newline+'recent')),expected);safe(compare(canonical.replace('clock_timestamp()','-- ignored'+ '\r'+'foreign_fn()')),'unknown');});
