'use strict';
// Entire fixture is synthetic; no SQL engine, authority, fallback or native ACK proof.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=process.env.CONTROL_FACTS_PUBLIC_CONTEXT;if(!root||!path.isAbsolute(root))throw Error('FACTS_TEST_CONTEXT_REQUIRED');
const manifestBytes=fs.readFileSync(path.join(root,'CONTEXT-MANIFEST.json'));if(crypto.createHash('sha256').update(manifestBytes).digest('hex')!=='2d05b7bcf711b9244b96441ed9c422d4ea19cf52ffefd0bfcf7097dbccd866a5')throw Error('FACTS_TEST_CONTEXT_REFUSED');const manifest=JSON.parse(manifestBytes);for(const e of manifest.files){const b=fs.readFileSync(path.join(root,e.path));if(b.length!==e.bytes||crypto.createHash('sha256').update(b).digest('hex')!==e.sha256||crypto.createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex')!==e.gitBlobSha1)throw Error('FACTS_TEST_CONTEXT_REFUSED');}
const kernel=require(path.join(root,'context/source/domain/audience-slices/kernel.cjs')),deliverability=require(path.join(root,'context/source/services/dashboard-operational/domain/deliverability/policy.cjs')),decide=require(path.join(root,'context/source/services/dashboard-operational/domain/crm-mvp-controls/decision.cjs')).createDecision({kernel,deliverability});
const C=require('../../../services/dashboard-operational/domain/crm-mvp-controls-persistence/facts/codec.cjs'),SQL=require('../../../services/dashboard-operational/domain/crm-mvp-controls-persistence/facts/sql.cjs');
const H='a'.repeat(64),E='b'.repeat(64),uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),N=1000;
const composite=(brand,kind,key)=>JSON.stringify([brand,kind,key]),eventKey=(brand,source,event)=>JSON.stringify([brand,source,event]);
function database(){return {brands:new Map(),events:new Map(),versions:new Map(),heads:new Map(),operations:new Map(),generation:0};}
function client(db){let state=null,started=0,write=false,changed=false;const c={logs:[],before:null,after:null,ownership:{connect:0,end:0,release:0}};for(const method of ['connect','end','release'])c[method]=()=>{c.ownership[method]++;throw Error('ownership must remain Root');};
 c.query=async(sql,p=[])=>{c.logs.push({sql,params:p});if(c.before)await c.before(sql,p);let rows=[],command=sql.split(' ')[0],r;
 if(sql===SQL.BEGIN_READ||sql===SQL.BEGIN_WRITE){if(state)throw Error('nested synthetic tx');state=structuredClone(db);started=db.generation;write=sql===SQL.BEGIN_WRITE;changed=false;r={command:'BEGIN',rows:[],rowCount:null};}
 else if(sql===SQL.COMMIT){if(write&&changed&&db.generation!==started)throw Object.assign(Error('synthetic SERIALIZABLE conflict'),{code:'40001'});if(write&&changed){for(const k of ['brands','events','versions','heads','operations'])db[k]=state[k];db.generation++;}state=null;r={command:'COMMIT',rows:[],rowCount:null};}
 else if(sql===SQL.ROLLBACK){state=null;r={command:'ROLLBACK',rows:[],rowCount:null};}
 else{if(!state)throw Error('fixture query outside tx');const key=composite(p[0],p[1],p[2]);
 if(sql===SQL.BRAND||sql===SQL.LOCK_BRAND){const rev=state.brands.get(p[0]);if(rev!==undefined)rows=[{brand:p[0],revision:rev}];}
 else if(sql===SQL.EVENT){const e=state.events.get(eventKey(...p));if(e)rows=[e];}
 else if(sql===SQL.HEADS||sql===SQL.HISTORY){const keys=sql===SQL.HEADS?JSON.parse(p[1]).map(k=>[p[0],k.kind,k.fact_key,state.heads.get(composite(p[0],k.kind,k.fact_key))]):[[...p.slice(0,3),p[3]]];for(const args of keys){const v=state.versions.get(JSON.stringify(args));if(v){const b=state.events.get(eventKey(v.brand,v.source_ref,v.event_ref));rows.push({...v,batch_payload_hash:b.payload_hash,authority_ref:b.authority_ref,envelope:b.envelope});}}}
 else if(sql===SQL.INSERT_EVENT){const k=eventKey(p[0],p[1],p[2]);if(!state.events.has(k)){state.events.set(k,{brand:p[0],source_ref:p[1],event_ref:p[2],brand_revision:p[3],payload_hash:p[4],authority_ref:p[5],recorded_at:p[6],envelope:JSON.parse(p[7])});rows=[{brand_revision:p[3]}];changed=true;}}
 else if(sql===SQL.INSERT_VERSION){state.versions.set(JSON.stringify(p.slice(0,4)),{brand:p[0],kind:p[1],fact_key:p[2],revision:p[3],body:JSON.parse(p[4]),body_hash:p[5],observed_at:p[6],expires_at:p[7],source_ref:p[8],event_ref:p[9],brand_revision:p[10]});rows=[{revision:p[3]}];changed=true;}
 else if(sql===SQL.INSERT_HEAD){if(!state.heads.has(key)){state.heads.set(key,p[3]);rows=[{revision:p[3]}];changed=true;}}
 else if(sql===SQL.UPDATE_HEAD){if(state.heads.get(key)===p[3]){state.heads.set(key,p[4]);rows=[{revision:p[4]}];changed=true;}}
 else if(sql===SQL.INSERT_BRAND){if(!state.brands.has(p[0])){state.brands.set(p[0],p[1]);rows=[{revision:p[1]}];changed=true;}}
 else if(sql===SQL.UPDATE_BRAND){if(state.brands.get(p[0])===p[1]){state.brands.set(p[0],p[2]);rows=[{revision:p[2]}];changed=true;}}
 else if(sql===SQL.ORIGINAL){const o=state.operations.get(JSON.stringify(p));if(o)rows=[o];}
 else throw Error('unlisted synthetic SQL');r={command,rows:structuredClone(rows),rowCount:rows.length};}
 return c.after?c.after(sql,r):r;};return c;
}
const options=c=>({enabled:true,client:c,withDomainSession:work=>work(),clock:()=>N,kernel,deliverability,verifyFacts:async i=>({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,payloadHash:C.digest(i),authorityRef:H}),verifyOriginalAttempt:async(i,r)=>({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,bindingHash:C.digest(i.binding),requirementsHash:C.digest(i.requirements),operationReceiptHash:r.receipt_hash}),verifyLiveContext:async i=>({brand:i.brand,operationId:i.operationId,contextHash:C.digest(i)})});
async function policyState(brand='fish'){const policy=deliverability.createPolicy({brand,softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:async e=>e,authorizePolicyChange:async()=>({brand,actorRef:H}),clock:()=>N});const token=await policy.admitPolicyChange({operationId:uuid(80),softBounceAttempts:2});return policy.apply(policy.initialState(),token).state;}
function fact(kind,body,expectedRevision=null){return {kind,body,expectedRevision,revision:C.revision(body)};}
function batch(facts,overrides={}){return {brand:'fish',inputKind:'verified_snapshot',sourceRef:H,eventRef:E,evidenceHash:H,expectedBrandRevision:null,brandRevision:7,observedAt:N,expiresAt:N+60000,facts,bindings:[],...overrides};}
function consent(subjectId=uuid(1),recipientRef=H,consent='current',consentRevision=9){return {subjectId,recipientRef,consent,consentRevision};}
async function prepared(){const distribution={schema:'crm-audience-slices-v1',brand:'fish',id:uuid(3),revision:2,key:H,identity_contract:'crm-contact-id-v1',algorithm:'sha256-rejection-bp-v1'},plan={schema:'crm-audience-slices-v1',brand:'fish',distribution_id:distribution.id,distribution_revision:2,key_hash:kernel.keyHash(distribution),slices:[{id:uuid(4),name:'All',from_bp:0,to_bp:10000}]},snapshot={schema:'crm-audience-slice-source-v1',brand:'fish',audience_id:uuid(5),audience_revision:3,definition_hash:H,snapshot_id:uuid(6),source_hash:H,observed_at:new Date(N).toISOString(),expires_at:new Date(N+60000).toISOString(),complete:true,identity_complete:true,members:[uuid(1)]};
 const claims={schema:'crm-audience-slice-claims-v1',brand:'fish',distribution_id:distribution.id,distribution_revision:2,key_hash:plan.key_hash,revision:4,complete:true,claims:[]},selection={plan,distribution,slice_id:uuid(4),snapshot},before=kernel.select({...selection,claims,now:N}),campaign={brand:'fish',campaign_id:10,campaign_version:3,content_hash:H,audience_definition_hash:H};
 const facts=[fact('consent',consent()),fact('capping',{subjectId:uuid(1),recipientRef:H,cappingRevision:8,windowStart:N,windowEnd:N+60000,limit:2,acceptedCount:0,reservedCount:0}),fact('capacity',{distributionId:uuid(3),distributionRevision:2,campaignId:10,campaignVersion:3,capacityRevision:5,limit:1,acceptedCount:0,reservedCount:0}),fact('policy',await policyState()),fact('suspension',{suspension:'clear',suspensionRevision:2}),fact('claims',claims)];
 const guards={brand:'fish',campaign_id:10,campaign_version:3,content_hash:H,definition_hash:H,members_hash:before.members_hash,observed_at:new Date(N).toISOString(),expires_at:new Date(N+60000).toISOString(),content_current:true,consent_current:true,bounce_current:true,frequency_current:true};
 return {facts,request:{brand:'fish',operationId:uuid(7),selection,before,campaign,beforeCampaign:campaign,contentGuards:guards,memberBindings:[{subjectId:uuid(1),recipientRef:H}]}};
}
module.exports={C,SQL,kernel,deliverability,decide,H,E,N,uuid,composite,database,client,options,policyState,fact,batch,consent,prepared};
