'use strict';
const C=require('../../services/dashboard-operational/native-installer/catalog.cjs'),S=require('../../services/dashboard-operational/native-installer/sql.cjs');
const target={project:'comunicacao',service:'postgres',database:'listmonk',ownNamespace:'test_owned_shrigma',installerRole:'test_installer',runtimeRole:'test_runtime'};
const clone=x=>JSON.parse(JSON.stringify(x)),result=(command,rows=[],rowCount=rows.length)=>({command,rows,rowCount}),ack=c=>result(c,[],null);
const role=name=>({name,login:false,super:false,createDB:false,createRole:false,inherit:false,replication:false,bypassRls:false,memberships:0});
const relation=name=>({name,owner:target.installerRole,kind:'r',persistent:true,rls:false,partition:false,triggers:false,inheritance:false,publicAccess:false,columns:[]});
function ledger(){return {owner:target.installerRole,kind:'r',persistent:true,rls:false,triggers:false,inheritance:false,otherAccess:false,columns:[['operation_id','uuid',true],['migration_id','text',true],['source_sha256','text',true],['request_sha256','text',true],['target_sha256','text',true],['manifest_sha256','text',true],['state','text',true],['attempted_at','timestamp with time zone',true],['applied_at','timestamp with time zone',false]].map(([name,type,notNull])=>({name,type,notNull})),constraints:[['p','PRIMARY KEY (operation_id)'],['u','UNIQUE (migration_id)'],['c',"CHECK ((state = ANY (ARRAY['attempted'::text, 'applied'::text])))"]].map(([kind,definition])=>({kind,sha256:C.hash(definition)}))};}
function database(){return {inventory:{database:'listmonk',sessionRole:target.installerRole,currentRole:target.installerRole,engine:170011,runtimeInstallationRights:false,installerSuper:true,installerCreateRole:true,databaseCreate:true,databaseOwner:target.installerRole,ownSchema:{name:target.ownNamespace,owner:target.installerRole,create:true,otherCreate:false},publicCreate:true,publicCreateExposed:false,databaseCreateExposed:false,security:{tls:true,statementLoggingOff:true,parameterLoggingOff:true,errorParameterLoggingOff:true},relations:['crm_dash_chave','shrigma_panel_permission_v1'].map(relation),functions:[],types:[],roles:[role(target.runtimeRole)],otherPublicRelationCount:10,defaultGrants:[],ledger:null},operations:[]};}
function client(db=database(),hook){let tx=null,leased=false,poisoned=false;const calls=[],sql=S.ledger(target.ownNamespace);function current(){return tx||db;}
 const raw={async query(text,params){if(!leased)throw Error('MODEL_LEASE');calls.push({text,params});if(hook){const r=await hook({text,params,db,current:current(),calls});if(r!==undefined)return r;}
  if(text===S.BEGIN_READ||text===S.BEGIN_WRITE){if(tx)throw Error('nested');tx=clone(db);return ack('BEGIN');}if(text==='ROLLBACK'){tx=null;return ack('ROLLBACK');}if(text==='COMMIT'){Object.assign(db,tx);tx=null;return ack('COMMIT');}if(text===S.LIMITS)return Array.from({length:4},()=>ack('SET'));if(text===S.LOCK)return result('SELECT',[{locked:''}]);if(text===S.INVENTORY)return result('SELECT',[{inventory:clone(current().inventory)}]);if(text===sql.create){current().inventory.ledger=ledger();return [ack('CREATE'),ack('REVOKE')];}if(text===sql.find)return result('SELECT',current().operations.filter(r=>r.operation_id===params[0]||r.migration_id===params[1]).map(clone));if(text===sql.status)return result('SELECT',current().operations.filter(r=>r.operation_id===params[0]).map(clone));if(text===sql.dependencies)return result('SELECT',current().operations.filter(r=>params[0].includes(r.migration_id)).map(r=>({migration_id:r.migration_id,source_sha256:r.source_sha256,state:r.state})));
  if(text===sql.insert){const r={operation_id:params[0],migration_id:params[1],source_sha256:params[2],request_sha256:params[3],target_sha256:params[4],manifest_sha256:params[5],state:'attempted',attempted_at:'1000',applied_at:null};current().operations.push(r);return result('INSERT',[clone(r)]);}
  if(text===sql.applied){const r=current().operations.find(r=>r.operation_id===params[0]&&r.request_sha256===params[1]&&r.state==='attempted');if(!r)return result('UPDATE');r.state='applied';r.applied_at='1001';return result('UPDATE',[clone(r)]);}
  const m=C.manifest().migrations.map(m=>C.get(m.id)).find(m=>m.sql===text);if(!m)throw Error('unreviewed SQL');const v=current().inventory,owner=m.createdOwner==='installer'?target.installerRole:m.createdOwner;for(const n of [...m.creates.tables,...m.creates.indexes])v.relations.push({...relation(n),owner,kind:m.creates.indexes.includes(n)?'i':'r'});for(const n of m.creates.functions)v.functions.push({name:n,argumentTypes:'jsonb',owner,definer:/_(prepare|commit|revoke|status)_/.test(n),bodySha256:'a'.repeat(64),safeSearchPath:true,configSha256:'b'.repeat(64),publicExecute:false});for(const n of m.creates.roles)v.roles.push({...role(n),login:n==='crm_manager_provisioner'});if(m.id==='crm-read-role-install-v1')for(const o of [...v.relations,...v.functions])if(m.ownPublicObjects.includes(o.name)&&!['crm_dash_chave','shrigma_panel_permission_v1'].includes(o.name))o.owner=owner;return [ack('SET'),ack('CREATE'),ack('REVOKE')];
 },connect(){throw Error('product lifecycle');},end(){throw Error('product lifecycle');},release(){throw Error('product lifecycle');}};
 return {raw,db,calls,withInstallerSession:async work=>{if(poisoned||leased)throw Error('lease denied');leased=true;try{return await work();}finally{leased=false;}},poisonSession:()=>{poisoned=true;},poisoned:()=>poisoned};}
async function admission(i){return {admitted:true,action:i.action,targetHash:i.targetHash,manifestHash:i.manifestHash,inventoryHash:i.inventoryHash,migrationId:i.migrationId,operationId:i.operationId,ownNamespace:target.ownNamespace,installerRole:target.installerRole,runtimeRole:target.runtimeRole,ownedPublicObjects:C.manifest().migrations.flatMap(m=>m.ownPublicObjects),reviewedRoles:C.manifest().migrations.flatMap(m=>m.creates.roles),inputs:Object.fromEntries(C.manifest().migrations.flatMap(m=>m.requires).map(k=>[k,true])),recoveryReady:true};}
function options(c,extra={}){return {enabled:true,client:c.raw,manifest:C.manifest(),target,admission,withInstallerSession:c.withInstallerSession,poisonSession:c.poisonSession,...extra};}
const uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),request=(id='crm-read-provision-v1',n=1)=>({migrationId:id,expectedSha256:C.get(id).sha256,operationId:uuid(n)});
module.exports={C,S,target,database,client,admission,options,request,uuid,ledger,ack,result};
