-- PREPARED ONLY. No campaigns, templates, identities or grants are created.
-- Run after the reviewed ownership/provider/guards and brand-bound gateway
-- upgrade. Every GET checks current function sources and active trigger shapes.
DO $owner$ BEGIN IF current_user<>'postgres' THEN RAISE EXCEPTION 'CONTENT_AUTHORITY_OWNER_REQUIRED';END IF; END $owner$;
CREATE FUNCTION public.shrigma_crm_campaign_content_authority_v1(p_key text,p_brand text) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $authority$
DECLARE a jsonb;c public.crm_dash_chave%ROWTYPE;w jsonb;scope_name text;cat jsonb;
BEGIN
 IF p_brand IS NULL OR p_brand NOT IN ('fish','aristo') THEN RETURN NULL; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_crm_operator_auth_v1(text)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['cc84c93a796fe79b410c1f1e89a80847fd13d3f0362dcbf9e742d5fbe2e8eefd']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_crm_campaign_auth_v1(text)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=true AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['145b196f90ae374331987d4593083de035587dbd3fddd444d80cb0d6de805add']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_crm_campaign_effect_v1(text,jsonb,jsonb)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=true AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['c05811fe1381e459c05cf302212587bc849ee015fc5fd69a6f2b185e516bde52']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_catalog(text)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM NULL::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['ef3709381bff199863c81ab6a830f95dc46d16d965b1dfbccdba98a18c6bd31e']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_template_owned_v1(integer,text)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['592aa8d508bbccec27c1f16ea76dfb2749036bac215ed93bb48f052ff49d9249']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_template_registry_guard_v1()') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=true AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog','lock_timeout=3s']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['0ade431d7bcaad56ba69efb6dd8e57ef211386b226187ece08197a164b5495b6']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_template_create_guard_v1()') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=true AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog','lock_timeout=3s']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['93c8c287c7cf8aeaa5ca7a91853fde2aafa54dfb255348a6bcb5698f65952373']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_provider(text,jsonb)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public','lock_timeout=3s']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['6aa286c758a14166d7a7c32ff86a5e8342b97e027016957d2f143cd4d487bd75']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_list_brand(public.lists)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM NULL::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['abe40c47221a72e26b885d0f3cd1adb2544320d845de10f22dd05327b0dd4fc6']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_current(integer)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM NULL::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['014fd83f6b7e7b33ea4dce3d7c5d2471f5c35f04a2234e285496f09545f7aaef']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_audience(integer)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='s' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['00a4907802dc10cb216f558960265f878cf4a912db3044ccda27711c2014e96c']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_is_managed(public.campaigns)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='i' AND l.lanname='sql' AND p.proconfig IS NOT DISTINCT FROM NULL::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['2f027fee52e4475ae5981bd5c7ad1a909ee838910ada05ffc8433501ac3647d1']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_guard()') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['68b2f8be775d10b201ef1d7344d833f7ad6469fde31569a04fb35a6b93ff1915']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_relation_guard()') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['cf578e04d77da5ac3da8edb4830ca6f1093b501067377be3a10734a313721a3a']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_dependency_guard()') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['5a98ce7c2fdd16b335ff3595ab94ac260d155d97a365b26b049760b16bbb9479']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.shrigma_campaign_store(text,jsonb)') AND p.proowner='postgres'::regrole AND p.prokind='f' AND p.prosecdef=false AND p.provolatile='v' AND l.lanname='plpgsql' AND p.proconfig IS NOT DISTINCT FROM ARRAY['search_path=pg_catalog, public','lock_timeout=3s']::text[] AND NOT EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')=ANY(ARRAY['0cff53470625297c1d04049234ba6020a567e6e9ae036b77570a8db8f943d394']::text[]))
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.shrigma_template_email_registry') AND g.tgname='shrigma_campaign_template_registry_guard_v1' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_template_registry_guard_v1()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=31 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.shrigma_template_email_registry') AND g.tgname='shrigma_campaign_template_registry_truncate_guard_v1' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_template_registry_guard_v1()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=34 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.campaigns') AND g.tgname='shrigma_campaign_template_create_guard_v1' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_template_create_guard_v1()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=7 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.campaigns') AND g.tgname='shrigma_campaign_write_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=31 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.campaign_lists') AND g.tgname='shrigma_campaign_lists_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_relation_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=31 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.campaign_media') AND g.tgname='shrigma_campaign_media_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_relation_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=31 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.templates') AND g.tgname='shrigma_campaign_template_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_dependency_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=27 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.lists') AND g.tgname='shrigma_campaign_list_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_dependency_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=27 AND g.tgqual IS NULL AND g.tgnargs=0)
 OR NOT EXISTS(SELECT 1 FROM pg_trigger g WHERE g.tgrelid=to_regclass('public.media') AND g.tgname='shrigma_campaign_media_asset_guard' AND g.tgfoid=to_regprocedure('public.shrigma_campaign_dependency_guard()') AND NOT g.tgisinternal AND g.tgenabled='O' AND g.tgtype=27 AND g.tgqual IS NULL AND g.tgnargs=0) THEN RETURN NULL; END IF;
 IF EXISTS(SELECT 1 FROM pg_roles r WHERE r.rolname='crm_campaign_api' AND (r.rolsuper OR r.rolcreatedb OR r.rolcreaterole OR r.rolinherit OR r.rolreplication OR r.rolbypassrls))
  OR EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid IN(m.member,m.roleid) WHERE r.rolname='crm_campaign_api')
  OR EXISTS(SELECT 1 FROM unnest(ARRAY['crm_dash_chave','shrigma_panel_permission_v1','crm_manager_writer_issuer_v1','crm_manager_writer_subject_v1','crm_manager_writer_generation_v1','shrigma_template_email_registry','campaigns','templates','campaign_lists','campaign_media','lists','media','shrigma_campaign_operation','shrigma_campaign_validation']) name WHERE has_table_privilege('crm_campaign_api','public.'||name,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') OR has_any_column_privilege('crm_campaign_api','public.'||name,'SELECT,INSERT,UPDATE,REFERENCES')) THEN RETURN NULL; END IF;
 a:=public.shrigma_crm_campaign_auth_v1(p_key);IF a IS NULL THEN RETURN NULL; END IF;
 SELECT * INTO c FROM public.crm_dash_chave k WHERE a->>'actor'='panel:'||k.chave AND k.painel='growth' AND k.ativo AND k.revogada_em IS NULL AND (k.expira_em IS NULL OR k.expira_em>clock_timestamp());
 IF NOT FOUND OR c.dono IS NULL THEN RETURN NULL; END IF;
 IF a->'caps'='["read_content","list_history","submission"]'::jsonb AND NOT(a ? 'brand') THEN scope_name:='reader';w:=NULL;
 ELSIF a->'caps'='["read_content","draft","validate","submit"]'::jsonb AND a->>'brand'=p_brand THEN
  SELECT jsonb_build_object('issuerId',i.issuer_id,'namespaceId',g.namespace_id,'userId',g.user_id,'lifecycleId',g.lifecycle_id,'principalId',g.principal_id,'generation',g.generation,'expiresAt',g.expires_at_ms) INTO w
  FROM public.crm_manager_writer_generation_v1 g JOIN public.crm_manager_writer_subject_v1 s USING(namespace_id,user_id,lifecycle_id) JOIN public.crm_manager_writer_issuer_v1 i USING(namespace_id)
  WHERE g.principal_id=c.chave AND g.state='active' AND s.state='active' AND i.active AND s.active_generation=g.generation AND g.brand=s.brand AND g.brand=p_brand AND s.owner=c.dono AND g.expires_at_ms>floor(extract(epoch FROM clock_timestamp())*1000)::bigint;
  IF NOT FOUND THEN RETURN NULL; END IF;scope_name:='single';
 ELSE RETURN NULL; END IF;
 cat:=public.shrigma_campaign_catalog(p_brand);
 IF cat->>'template_ownership_contract' IS DISTINCT FROM 'crm-campaign-template-brand-v1' OR cat->>'brand' IS DISTINCT FROM p_brand THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('schema','crm-campaign-content-authority-v1','profileSha256','7def247d57d8d6fb3d7ef79d2a246212d205c9a2b13a8fe821bbacb03a71b52b','brand',p_brand,'actor',a->>'actor','owner',c.dono,'role','manager','scope',scope_name,'caps',a->'caps','writerBinding',w,'catalogue',jsonb_build_object('current',cat->'current','templates',jsonb_array_length(cat->'templates'),'lists',(SELECT count(*) FROM jsonb_array_elements(cat->'lists') l WHERE l->'available'='true'::jsonb),'initiatives',jsonb_array_length(cat->'initiatives')));
END $authority$;
REVOKE ALL ON FUNCTION public.shrigma_crm_campaign_content_authority_v1(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.shrigma_crm_campaign_content_authority_v1(text,text) TO crm_campaign_api;
