'use strict';
// Synthetic DTOs only. Loading the pinned contract/validator performs no transport or DB call.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const runtime=path.resolve(__dirname,'../../services/dashboard-operational'),contractPath=fs.existsSync(runtime+'/segment-audience-contract.js')?runtime+'/segment-audience-contract.js':path.resolve(__dirname,'../../../../source/services/dashboard-operational/segment-audience-contract.js');
const Contract=require(contractPath),box={exports:{}};vm.runInThisContext('(function(require,module,exports){'+fs.readFileSync(runtime+'/crm-master-audience-read.cjs','utf8')+'\n})')(name=>name==='./segment-audience-contract.js'?Contract:require(name),box,box.exports);const {validateAudienceRead:validate,audienceSummary:summary}=box.exports;
const clone=x=>JSON.parse(JSON.stringify(x)),hash='a'.repeat(64),uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),stamp='2026-10-07T12:00:00.000Z';
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
function segment(brand='fish',n=1){const name='Nome privado '+n;return {id:uuid(n),brand,name,definition:{schema_version:Contract.VERSION,brand,name,rule:{op:'in_list',list_id:11}},version:7,archived:n===2,created_at:'2026-09-01T12:00:00.000Z',updated_at:stamp,updated_by:'panel:synthetic-actor',semantic_context:{currency:'BRL',timezone:'America/Sao_Paulo',current:true}};}
function catalog(brand='fish'){return {brand,current:true,currency:'BRL',timezone:'America/Sao_Paulo',shop_id:'gid://shopify/Shop/1',fields:[{key:'purchase.count',available:true,source_hash:hash},{key:'email.clicked',available:false,source_hash:null}],products:[{id:'gid://shopify/Product/1',brand,name:'Produto privado',available:true}],origins:[{key:brand==='fish'?'popup':'vip_alma',brand,name:'Origem privada',available:true,provenance_hash:hash}],lists:[{id:11,brand,name:'Lista privada',available:true}],coverage:'unconfirmed',checked_at:stamp,catalog_hash:hash};}
function result(brand='fish'){return {status:200,body:{segments:[segment(brand),segment(brand,2)],limit:50,offset:0,catalog:catalog(brand),capabilities:{draft:true,count:true,send:false}}};}
const query=(extra={})=>new URLSearchParams(extra),opts=(brand='fish',extra={})=>({brand,action:'segmentos_listar',query:query(),...extra});
function deny(r,o=opts()){const v=validate(r,o);assert.equal(v.status,502);assert.deepEqual(v.body,{error:'AUDIENCE_READ_RESPONSE_DENIED'});assert.equal(v.sourceCapabilities,undefined);return v;}
test('native READ Fish/Aristo preserves archived/current definitions and actor history in body, masks all client write/count capabilities',()=>{for(const brand of ['fish','aristo']){const r=result(brand),original=clone(r),v=validate(r,opts(brand));assert.equal(v.status,200);assert.deepEqual(v.body.segments,r.body.segments);assert.deepEqual(v.body.catalog,r.body.catalog);assert.deepEqual(v.body.capabilities,{draft:false,count:false,send:false});assert.deepEqual(v.sourceCapabilities,{draft:true,count:true,send:false});assert.deepEqual(r,original);assert(Object.isFrozen(v.body.segments[0].definition));}});
test('summary gives returned count, scoped metadata and source permissions only; no names/ids/actor/shop/client/key data or total',()=>{const v=validate(result(),opts()),s=summary(v,{brand:'fish'});assert.deepEqual(s,{brand:'fish',status:200,available:true,countReturned:2,limit:50,offset:0,current:true,catalogHash:hash,checked_at:stamp,availableFields:1,availableLists:1,availableProducts:1,availableOrigins:1,availableRecordedOrigins:null,originalDraftAuthorized:true,originalCountAuthorized:true,send:false,gatewayWrite:false,operational:false});const encoded=JSON.stringify(s);for(const x of ['Nome privado','Produto privado','Origem privada','Lista privada','synthetic-actor',uuid(1),'gid://','definition','total'])assert(!encoded.includes(x));});
test('mixed or crossed brand rejected throughout segments/catalog/lists/products/origins/definition',()=>{for(const change of [r=>r.body.segments.push(segment('aristo',3)),r=>r.body.catalog.brand='aristo',r=>r.body.catalog.lists[0].brand='aristo',r=>r.body.catalog.products[0].brand='aristo',r=>r.body.catalog.origins[0].brand='aristo',r=>r.body.segments[0].definition.brand='aristo']){const r=result();change(r);deny(r);}});
test('credential echoes case insensitive anywhere, including names/actors/headers/error/escaped JSON strings/unknown keys; fixed refusal contains no echo',()=>{const secret='SYNTHETIC-Key',changes=[r=>r.body.segments[0].name=secret.toLowerCase(),r=>r.body.catalog.lists[0].name='prefix '+secret.toLowerCase(),r=>r.body.segments[0].updated_by='panel:prefix-'+secret.toLowerCase(),r=>r.headers={'Cache-Control':secret.toLowerCase()},r=>r.body.extra=secret.toLowerCase(),r=>r.body={error:secret.toLowerCase()}];for(const change of changes){const r=result();change(r);const v=deny(r,opts('fish',{secrets:[secret]}));assert(!JSON.stringify(v).toLowerCase().includes(secret.toLowerCase()));}const r=result();r.body.catalog.lists[0].name='A\nB';deny(r,opts('fish',{secrets:['a\nb']}));});
test('pagination matches exact requested bounds; returned is not total; duplicates and oversized page rejected',()=>{const r=result();r.body.limit=2;r.body.offset=100;let v=validate(r,opts('fish',{query:query({limit:'2',offset:'100'})}));assert.equal(v.status,200);assert.equal(summary(v,{brand:'fish'}).countReturned,2);deny(r);r.body.segments.push(segment('fish',3));deny(r,opts('fish',{query:query({limit:'2',offset:'100'})}));const duplicate=result();duplicate.body.segments[1].id=duplicate.body.segments[0].id.toUpperCase();deny(duplicate);for(const q of [{limit:'0'},{limit:'101'},{limit:'2.0'},{offset:'10001'},{offset:'-1'}])assert.equal(validate(result(),opts('fish',{query:query(q)})).status,400);});
test('zero on actual empty returned array only; source current false stays false regardless recent/future date and requires original permissions false',()=>{const r=result();r.body.segments=[];r.body.catalog.current=false;r.body.catalog.checked_at='2099-01-01T00:00:00.000Z';r.body.capabilities={draft:false,count:false,send:false};const v=validate(r,opts());assert.equal(v.status,200);assert.equal(v.body.catalog.current,false);assert.equal(summary(v,{brand:'fish'}).countReturned,0);assert.equal(summary(v,{brand:'fish'}).current,false);for(const k of ['draft','count']){const b=clone(r);b.body.capabilities[k]=true;deny(b);}});
test('native count may be true; send true or nonboolean capabilities/extra flag always denied',()=>{for(const caps of [{draft:false,count:true,send:false},{draft:true,count:false,send:false}]){const r=result();r.body.capabilities=caps;const v=validate(r,opts());assert.equal(v.status,200);assert.deepEqual(v.sourceCapabilities,caps);assert.deepEqual(v.body.capabilities,{draft:false,count:false,send:false});}for(const change of [r=>r.body.capabilities.send=true,r=>r.body.capabilities.count='true',r=>r.body.capabilities.extra=true,r=>delete r.body.capabilities.draft]){const r=result();change(r);deny(r);}});
test('GET original id match accepts uppercase query; metadata lacks catalog/capability data and never invents permission; mismatch denied',()=>{const r={status:200,body:{segment:segment('aristo',2)}},o={brand:'aristo',action:'segmento_obter',query:query({id:uuid(2).toUpperCase()})},v=validate(r,o);assert.equal(v.status,200);assert.deepEqual(v.body,r.body);assert.deepEqual(v.sourceCapabilities,{draft:null,count:null,send:false});const s=summary(v,{brand:'aristo'});assert.equal(s.countReturned,1);assert.equal(s.current,true);assert.equal(s.originalDraftAuthorized,null);assert.equal(s.originalCountAuthorized,null);assert.equal(s.limit,null);assert.equal(s.availableLists,null);deny(r,{...o,query:query({id:uuid(3)})});deny({status:200,body:{segment:segment('fish',2)}},o);});
test('source absent/errors remain unavailable, no payload/stack/transport/header leakage; only closed original GET errors accepted',()=>{for(const r of [null,undefined]){const v=validate(r,opts());assert.equal(v.status,503);assert.deepEqual(v.body,{error:'AUDIENCE_READ_SOURCE_UNAVAILABLE'});assert.equal(summary(v,{brand:'fish'}).countReturned,null);}for(const [status,error]of [[401,'SEGMENT_UNAUTHORIZED'],[403,'SEGMENT_ACCESS_DENIED'],[404,'SEGMENT_NOT_FOUND'],[503,'SEGMENT_SERVICE_UNAVAILABLE']]){const v=validate({status,body:{error}},opts());assert.deepEqual(v,{status,body:{error}});}deny({status:503,body:{error:'SEGMENT_SERVICE_UNAVAILABLE',stack:'private'}});deny({status:200,body:{error:'SEGMENT_SERVICE_UNAVAILABLE'}});deny({status:500,body:{error:'private'}});deny({_http:200,_body:result().body});const r=result();r.headers={'Cache-Control':'no-store'};assert.equal(validate(r,opts()).status,200);});
test('strict shape/id/version/date/hash/catalog checks reject malformed/native-incompatible rows without coercion',()=>{for(const change of [r=>r.body.segments[0].version='7',r=>r.body.segments[0].version=1000000000,r=>r.body.segments[0].id='fake',r=>r.body.segments[0].created_at='2026-02-30T12:00:00.000Z',r=>r.body.segments[0].updated_at='2020-01-01T00:00:00.000Z',r=>r.body.segments[0].updated_by='not-panel',r=>r.body.segments[0].semantic_context.timezone='invalid/timezone',r=>r.body.catalog.catalog_hash='bad',r=>r.body.catalog.fields[0].source_hash=null,r=>r.body.catalog.lists[0].id='11',r=>r.body.catalog.fields.push(r.body.catalog.fields[0]),r=>r.body.catalog.products[0].id='gid://shopify/Product/0',r=>r.body.catalog.origins[0].provenance_hash=null,r=>r.body.catalog.currency='brl',r=>r.body.catalog.timezone='invalid/timezone',r=>r.body.catalog.coverage='confirmed',r=>r.body.catalog.rfm_snapshot={current:true}]){const r=result();change(r);deny(r);}});
test('canonical original definition preserved and noncanonical rewrites/extra properties rejected',()=>{const r=result();r.body.segments[0].definition.rule={op:'condition',field:'purchase.amount',operator:'eq',value:'10.00'};assert.equal(validate(r,opts()).status,200);r.body.segments[0].definition.rule.value='10';deny(r);const v=result();v.body.segments[0].definition.extra='bad';deny(v);});
test('optional original Shopify snapshot exact shapes/dates/duration validated without deriving freshness',()=>{for(const s of [{current:false},{current:true,started_at:'2026-10-01T00:00:00.000Z',observed_at:'2026-10-01T00:10:00.000Z',expires_at:'2026-10-02T02:00:00.000Z'}]){const r=result();r.body.catalog.shopify_snapshot=s;assert.equal(validate(r,opts()).status,200);}for(const s of [{current:true},{current:false,customers:1},{current:true,started_at:stamp,observed_at:stamp,expires_at:stamp}]){const r=result();r.body.catalog.shopify_snapshot=s;deny(r);}});
test('original recorded origin validates brand/producer/canonical provenance; preserves body but summary counts no identifiers',()=>{const r=result('aristo'),o={key:'vip_alma',brand:'aristo',name:'Origem registrada',available:true,scope_id:uuid(4),producer_id:'NAmTWZ7vddQ8LX1k',producer_revision:hash,coverage_started_at:stamp,provenance_hash:''};const pinned={contract:'crm-recorded-origin-exists-v1',brand:o.brand,origin:o.key,scope_id:o.scope_id,producer_id:o.producer_id,producer_revision:o.producer_revision,coverage_started_at:o.coverage_started_at};o.provenance_hash=crypto.createHash('sha256').update(canonical(pinned)).digest('hex');r.body.catalog.recorded_origins=[o];const v=validate(r,opts('aristo'));assert.equal(v.status,200);assert.equal(summary(v,{brand:'aristo'}).availableRecordedOrigins,1);for(const change of [x=>x.brand='fish',x=>x.provenance_hash=hash,x=>x.producer_id='fake']){const b=clone(r);change(b.body.catalog.recorded_origins[0]);deny(b,opts('aristo'));}});
test('getter/toJSON/custom prototype/cycle/sparse/nonJSON/oversize refuse without invoking user code',()=>{let calls=0;const r=result();Object.defineProperty(r.body,'catalog',{enumerable:true,get(){calls++;throw Error('secret');}});deny(r);assert.equal(calls,0);for(const make of [()=>{const r=result();r.toJSON=()=>{calls++;return {};};return r;},()=>{const r=result();Object.setPrototypeOf(r.body.catalog,{toJSON(){calls++;}});return r;},()=>{const r=result();r.body.extra=r;return r;},()=>{const r=result();r.body.segments.length=4;return r;},()=>{const r=result();r.body.offset=Infinity;return r;},()=>{const r=result();r.body.catalog.lists[0].name='x'.repeat(2000001);return r;}])deny(make());assert.equal(calls,0);});
test('summary accepts only this validator frozen return with matching brand; forged/mutated/cross-brand values reveal nothing',()=>{const v=validate(result(),opts());assert.throws(()=>{v.sourceCapabilities.draft=false;},TypeError);for(const r of [result(),clone(v),undefined,null]){const s=summary(r,{brand:'fish'});assert.equal(s.available,false);assert.equal(s.countReturned,null);assert.equal(s.originalDraftAuthorized,null);}assert.equal(summary(v,{brand:'aristo'}).available,false);assert.equal(summary().available,false);});
test('only READ actions valid, configuration/query scope and duplicate parameters cannot broaden authority',()=>{for(const action of ['segmento_arquivar','segmento_contar','segmento_operacao','segmento_criar'])assert.equal(validate(result(),opts('fish',{action})).status,400);for(const o of [opts('foreign'),opts('fish',{query:query({brand:'aristo'})}),opts('fish',{query:query({acao:'segmento_arquivar'})}),opts('fish',{query:new URLSearchParams('limit=50&limit=50')}),opts('fish',{secrets:[42]}),opts('fish',{query:{}})])assert.equal(validate(result(),o).status,400);});

test('exact historical Mestre secret reference only in updated_by is response-pseudonymized after validation; native source and history stay intact',()=>{
 const secret='synthetic-master-key',actor='panel:'+secret,expected='panel:sha256:'+crypto.createHash('sha256').update(actor,'utf8').digest('hex');
 for(const brand of ['fish','aristo'])for(const action of ['segmentos_listar','segmento_obter']){
  const native=result(brand);native.body.segments[0].updated_by=actor;
  const r=action==='segmentos_listar'?native:{status:200,body:{segment:native.body.segments[0]}};const original=clone(r),o={brand,action,query:query(action==='segmento_obter'?{id:uuid(1)}:{}),secrets:[secret]},v=validate(r,o);assert.equal(v.status,200);
  const got=action==='segmentos_listar'?v.body.segments[0]:v.body.segment,before=action==='segmentos_listar'?original.body.segments[0]:original.body.segment;
  assert.equal(got.updated_by,expected);assert.deepEqual({...got,updated_by:before.updated_by},before);assert.equal(got.version,7);assert.deepEqual(got.definition,before.definition);assert.deepEqual(r,original);assert(!JSON.stringify(v).includes(secret));const safe=summary(v,{brand});assert(!JSON.stringify(safe).includes('panel:'));assert(!JSON.stringify(safe).includes(expected));assert(!JSON.stringify(safe).includes(secret));
 }
});
test('partial/mixed/case-variant historical secret and secret anywhere else still reject; exact actor cannot rescue invalid DTO',()=>{
 const secret='synthetic-master-key';for(const actor of ['panel:prefix-'+secret,'panel:'+secret+'-suffix','panel:'+secret.toUpperCase(),'panel:'+secret+':other','PANEL:'+secret]){const r=result();r.body.segments[0].updated_by=actor;deny(r,opts('fish',{secrets:[secret]}));}
 for(const change of [r=>{r.body.segments[0].name=secret;r.body.segments[0].definition.name=secret;},r=>r.body.catalog.lists[0].name=secret,r=>r.body.catalog.products[0].name=secret,r=>r.body.segments[1].updated_by='panel:prefix-'+secret,r=>r.body.segments[0].version=0,r=>r.body.segments[0].brand='aristo',r=>r.body.segments[0].extra=secret]){const r=result();r.body.segments[0].updated_by='panel:'+secret;change(r);deny(r,opts('fish',{secrets:[secret]}));}
 const r=result();r.body.catalog.updated_by='panel:'+secret;deny(r,opts('fish',{secrets:[secret]}));
});
