'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const P=require('../../../tools/dashboard-crm-control-facts-pg17/prepare.cjs'),R=require('../../../tools/dashboard-crm-control-facts-pg17/fixture.cjs');
// Only lifecycle/ordering model. No database, native facts runner or native proof.
function setup(fault){const made=[],calls=[];let n=0;const makeClient=()=>{const index=n++;if(fault==='constructor'&&index===1)throw Error('PRIVATE');let ready,error;const c={processID:index+1,connection:{on(name,fn){ready=fn;}},on(name,fn){error=fn;},async connect(){calls.push('connect'+index);if(fault==='connect'&&index===1)throw Error('PRIVATE');ready({status:'I'});},async end(){calls.push('end'+index);if(fault==='end'&&index===0)throw Error('PRIVATE');},async query(sql){calls.push(sql);if(sql==='SHOW server_version_num')return {command:'SHOW',rowCount:null,rows:[{server_version_num:fault==='major'&&index===1?'160010':'170011'}]};if(sql.startsWith('SELECT current_database'))return {command:'SELECT',rowCount:1,rows:[{database_name:fault==='database'?'other':'crm_borrowed_source_test',backend_pid:fault==='pid'?1:c.processID}]};if(fault==='schema'&&sql==='FACTS_SCHEMA')throw Error('PRIVATE');return {command:'CREATE',rows:[],rowCount:null};},setIdle(status){ready({status});},emitError(){error(Error('PRIVATE'));}};made.push(c);return c;};
 const options={makeClient,originalSchema:'ORIGINAL_SCHEMA',factsSchema:'FACTS_SCHEMA',runFacts:async args=>{calls.push('runner');assert.deepEqual(await args.admitIsolatedClients(args.clients),{isolated:true,existingNamespace:'dashboard_crm_controls',dedicatedClients:true,factsSchemaInstalled:true,production:false});await args.withDomainSessions[0](async()=>{await assert.rejects(args.withDomainSessions[0](async()=>{}));});if(fault==='runner')throw Error('PRIVATE');if(fault==='idle'){made[0].setIdle('T');await args.withDomainSessions[0](async()=>{});}if(fault==='event'){made[0].emitError();await args.admitIsolatedClients(args.clients);}return {executed:true,engine:'170011',scenarios:4,operational:false,productionAdmitted:false};}};return {options,made,calls};}
test('facts CI synthetic: all two-client lifecycle stages close each constructed client even on failure',async()=>{for(const fault of [undefined,'constructor','connect','major','database','pid','schema','runner','idle','event','end']){const s=setup(fault),r=await R.runOwned(s.options);assert.equal(r.fixtureScope,'injected-test-only');assert.equal(r.productionDurabilityProved,false);assert.equal(r.executed,fault===undefined);assert.equal(r.cleanup.created,fault==='constructor'?1:2);assert.equal(r.cleanup.endCalls,r.cleanup.created);assert.equal(r.cleanup.closed,r.cleanup.created-(fault==='end'?1:0));assert.equal(s.calls.filter(x=>x.startsWith('end')).length,r.cleanup.created);assert(!JSON.stringify(r).includes('PRIVATE'));if(['major','database','pid','connect','constructor'].includes(fault))assert(!s.calls.some(x=>x.includes('SCHEMA')));if(fault==='end')assert.equal(r.code,'FACTS_CI_CLEANUP_REFUSED');}});
test('facts CI synthetic: exclusive leases and exact custody refuse foreign clients without running work',async()=>{const s=setup();s.options.runFacts=async args=>{let calls=0;await assert.rejects(args.admitIsolatedClients([args.clients[1],args.clients[0]]));args.clients[1].setIdle('T');await assert.rejects(args.withDomainSessions[1](async()=>{calls++;}));args.clients[1].setIdle('I');await args.withDomainSessions[0](async()=>{await assert.rejects(args.withDomainSessions[0](async()=>{calls++;}));});assert.equal(calls,0);return {executed:true,engine:'170011',scenarios:4,operational:false,productionAdmitted:false};};assert.equal((await R.runOwned(s.options)).executed,true);});
test('facts CI prepare: eight pinned payloads and exact public context, tamper refuses and existing output stays untouched',()=>{const runnerTemp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'control-facts-ci-test-')));try{const p=P.prepare({repositoryRoot:fs.realpathSync(process.cwd()),runnerTemp});assert.equal(p.sourceFiles,8);assert.equal(p.contextFiles,14);P.verifyPrepared(p);const target=path.join(p.source,'tests/crm-mvp-controls-persistence/facts/pg17.cjs');fs.appendFileSync(target,'\n// tampered');assert.throws(()=>P.verifyPrepared(p),/FACTS_CI_INPUT_REFUSED/);assert.throws(()=>P.prepare({repositoryRoot:fs.realpathSync(process.cwd()),runnerTemp}));assert(fs.readFileSync(target,'utf8').endsWith('// tampered'));}finally{fs.rmSync(runnerTemp,{recursive:true,force:true});}});
test('facts CI prepare: physical symlink or hardlink cannot satisfy pinned file identity',()=>{const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'control-facts-ci-link-')));try{const source=path.join(temp,'a'),hard=path.join(temp,'b'),link=path.join(temp,'c');fs.writeFileSync(source,'test');fs.linkSync(source,hard);fs.symlinkSync(source,link);assert.throws(()=>P.physical(hard,true));assert.throws(()=>P.physical(link,true));}finally{fs.rmSync(temp,{recursive:true,force:true});}});
test('facts CI default OFF: current local runtime cannot prepare or connect',async()=>{const before=process.env.CONTROL_FACTS_PG17_CI;delete process.env.CONTROL_FACTS_PG17_CI;try{const r=await R.execute();assert.equal(r.executed,false);assert.equal(r.nativeFactsProof,false);}finally{if(before!==undefined)process.env.CONTROL_FACTS_PG17_CI=before;}});
