'use strict';
const crypto=require('node:crypto'),MAX=Number.MAX_SAFE_INTEGER;
const fail=()=>{throw Object.assign(new Error('CONTROL_FACTS_REFUSED'),{code:'CONTROL_FACTS_REFUSED'});};
const hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x),uuid=x=>typeof x==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(x),op=x=>uuid(x)&&x[14]==='4',positive=x=>Number.isSafeInteger(x)&&x>0,nonnegative=x=>Number.isSafeInteger(x)&&x>=0;
function exact(v,keys){if(!v||typeof v!=='object'||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail();const names=Reflect.ownKeys(v);if(names.length!==keys.length||names.some(k=>typeof k!=='string'||!keys.includes(k)||!Object.getOwnPropertyDescriptor(v,k).enumerable||!Object.hasOwn(Object.getOwnPropertyDescriptor(v,k),'value')))fail();}
function capture(v,depth=0,budget={n:0}){if(++budget.n>2000000||depth>20)fail();if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isSafeInteger(v))fail();return v;}if(Array.isArray(v)){if(v.length>100000||Reflect.ownKeys(v).length!==v.length+1)fail();const out=[];for(let i=0;i<v.length;i++){const d=Object.getOwnPropertyDescriptor(v,String(i));if(!d?.enumerable||!Object.hasOwn(d,'value'))fail();out.push(capture(d.value,depth+1,budget));}return Object.freeze(out);}if(!v||typeof v!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail();const out={};for(const k of Reflect.ownKeys(v).sort()){if(typeof k!=='string'||k==='__proto__')fail();const d=Object.getOwnPropertyDescriptor(v,k);if(!d.enumerable||!Object.hasOwn(d,'value'))fail();out[k]=capture(d.value,depth+1,budget);}return Object.freeze(out);}
const digest=v=>crypto.createHash('sha256').update(JSON.stringify(capture(v))).digest('hex');
function integer(v){if(typeof v!=='string'||!/^(0|[1-9][0-9]*)$/.test(v)||BigInt(v)>BigInt(MAX))fail();return Number(v);}
function assert(v){if(!v)fail();}
function key(kind,b){if(['policy','suspension'].includes(kind))return 'brand';if(['consent','capping'].includes(kind))return JSON.stringify([b.subjectId,b.recipientRef]);if(kind==='capacity')return JSON.stringify([b.distributionId,b.distributionRevision,b.campaignId,b.campaignVersion]);if(kind==='claims')return JSON.stringify([b.distribution_id,b.distribution_revision]);fail();}
const revision=b=>b.consentRevision??b.cappingRevision??b.capacityRevision??b.suspensionRevision??b.revision;
function body(kind,raw,brand){const b=capture(raw);
 if(kind==='consent'){exact(b,['subjectId','recipientRef','consent','consentRevision']);assert(uuid(b.subjectId)&&hash(b.recipientRef)&&['current','revoked','unknown'].includes(b.consent)&&positive(b.consentRevision));}
 else if(kind==='capping'){exact(b,['subjectId','recipientRef','cappingRevision','windowStart','windowEnd','limit','acceptedCount','reservedCount']);assert(uuid(b.subjectId)&&hash(b.recipientRef)&&positive(b.cappingRevision)&&nonnegative(b.windowStart)&&positive(b.windowEnd)&&b.windowEnd>b.windowStart&&[b.limit,b.acceptedCount,b.reservedCount].every(nonnegative)&&b.acceptedCount<=MAX-b.reservedCount);}
 else if(kind==='capacity'){exact(b,['distributionId','distributionRevision','campaignId','campaignVersion','capacityRevision','limit','acceptedCount','reservedCount']);assert(uuid(b.distributionId)&&[b.distributionRevision,b.campaignId,b.campaignVersion,b.capacityRevision].every(positive)&&[b.limit,b.acceptedCount,b.reservedCount].every(nonnegative)&&b.acceptedCount<=MAX-b.reservedCount);}
 else if(kind==='suspension'){exact(b,['suspension','suspensionRevision']);assert(['clear','suspended','unknown'].includes(b.suspension)&&positive(b.suspensionRevision));}
 else if(kind==='policy'){exact(b,['schema','brand','initialSoftBounceAttempts','revision','records','historyHash']);assert(b.schema==='crm-deliverability-state-v1'&&b.brand===brand&&positive(b.initialSoftBounceAttempts)&&b.initialSoftBounceAttempts<=100&&positive(b.revision)&&b.revision===b.records?.length&&b.records.length<=10000&&hash(b.historyHash));}
 else if(kind==='claims'){exact(b,['schema','brand','distribution_id','distribution_revision','key_hash','revision','complete','claims']);assert(b.schema==='crm-audience-slice-claims-v1'&&b.brand===brand&&uuid(b.distribution_id)&&positive(b.distribution_revision)&&hash(b.key_hash)&&positive(b.revision)&&b.complete===true&&Array.isArray(b.claims)&&b.claims.length<=100000);const seen=new Set();for(const c of b.claims){exact(c,['subject_id','operation_id','state','receipt_hash']);assert(uuid(c.subject_id)&&op(c.operation_id)&&!seen.has(c.subject_id)&&['reserved','uncertain','accepted','rejected_before_send'].includes(c.state)&&(['accepted','rejected_before_send'].includes(c.state)?hash(c.receipt_hash):c.receipt_hash===null));seen.add(c.subject_id);}}
 else fail();return b;
}
function batch(raw){exact(raw,['brand','inputKind','sourceRef','eventRef','evidenceHash','expectedBrandRevision','brandRevision','observedAt','expiresAt','facts','bindings']);const r=capture(raw);assert(['fish','aristo'].includes(r.brand)&&['verified_snapshot','original_attempt_event'].includes(r.inputKind)&&[r.sourceRef,r.eventRef,r.evidenceHash].every(hash)&&(r.expectedBrandRevision===null||positive(r.expectedBrandRevision))&&positive(r.brandRevision)&&nonnegative(r.observedAt)&&positive(r.expiresAt)&&r.expiresAt>r.observedAt&&r.expiresAt-r.observedAt<=60000&&Array.isArray(r.facts)&&r.facts.length>0&&r.facts.length<=10000&&Array.isArray(r.bindings)&&r.bindings.length<=10000);const seen=new Set();for(const f of r.facts){exact(f,['kind','expectedRevision','revision','body']);assert(f.expectedRevision===null||positive(f.expectedRevision));const b=body(f.kind,f.body,r.brand);assert(positive(f.revision)&&f.revision===revision(b));const k=f.kind+':'+key(f.kind,b);assert(!seen.has(k));seen.add(k);}for(const b of r.bindings){exact(b,['eventRef','attemptRef','operationId','attemptId','subjectId','recipientRef','distributionId','operationReceiptHash']);assert(hash(b.eventRef)&&hash(b.attemptRef)&&op(b.operationId)&&b.attemptId===b.operationId&&uuid(b.subjectId)&&hash(b.recipientRef)&&uuid(b.distributionId)&&hash(b.operationReceiptHash));}return r;}
function transition(kind,prior,next){if(!prior)return;if(kind==='policy'){assert(prior.initialSoftBounceAttempts===next.initialSoftBounceAttempts&&next.records.length>=prior.records.length&&prior.records.every((r,i)=>digest(r)===digest(next.records[i])));}
 if(kind==='claims'){assert(prior.key_hash===next.key_hash&&prior.distribution_revision===next.distribution_revision&&prior.distribution_id===next.distribution_id);const current=new Map(next.claims.map(c=>[c.subject_id,c]));for(const p of prior.claims){const n=current.get(p.subject_id);assert(n&&n.operation_id===p.operation_id);if(['accepted','rejected_before_send'].includes(p.state))assert(digest(p)===digest(n));if(p.state==='uncertain')assert(n.state!=='reserved');}}
}
function row(raw){exact(raw,['brand','kind','fact_key','revision','body','body_hash','observed_at','expires_at','source_ref','event_ref','brand_revision','batch_payload_hash','authority_ref','envelope']);const r={...raw,revision:integer(raw.revision),observed_at:integer(raw.observed_at),expires_at:integer(raw.expires_at),brand_revision:integer(raw.brand_revision)};assert(['fish','aristo'].includes(r.brand)&&positive(r.revision)&&positive(r.brand_revision)&&hash(r.body_hash)&&hash(r.source_ref)&&hash(r.event_ref));const batchEnvelope=batch(r.envelope);assert(hash(r.authority_ref)&&digest(batchEnvelope)===r.batch_payload_hash&&batchEnvelope.brand===r.brand&&batchEnvelope.sourceRef===r.source_ref&&batchEnvelope.eventRef===r.event_ref&&batchEnvelope.brandRevision===r.brand_revision&&batchEnvelope.observedAt===r.observed_at&&batchEnvelope.expiresAt===r.expires_at&&batchEnvelope.facts.some(f=>f.kind===r.kind&&key(f.kind,f.body)===r.fact_key&&f.revision===r.revision&&digest(f.body)===r.body_hash));r.body=body(r.kind,r.body,r.brand);assert(r.revision===revision(r.body)&&r.fact_key===key(r.kind,r.body)&&digest(r.body)===r.body_hash&&r.expires_at>r.observed_at&&r.expires_at-r.observed_at<=60000);return capture(r);}
function liveRequest(raw){exact(raw,['brand','operationId','selection','before','campaign','beforeCampaign','contentGuards','memberBindings']);const r=capture(raw);assert(['fish','aristo'].includes(r.brand)&&op(r.operationId)&&r.selection?.plan?.brand===r.brand&&Array.isArray(r.memberBindings)&&r.memberBindings.length<=100000);const seen=new Set();for(const b of r.memberBindings){exact(b,['subjectId','recipientRef']);assert(uuid(b.subjectId)&&hash(b.recipientRef)&&!seen.has(b.subjectId));seen.add(b.subjectId);}return r;}
module.exports=Object.freeze({MAX,fail,exact,capture,digest,integer,assert,key,revision,body,batch,transition,row,liveRequest,hash,uuid,op,positive,nonnegative});
