'use strict';
const C=require('./codec.cjs'),SQL=require('./sql.cjs');
const sessions=new WeakMap(),closed=(code,sqlstate)=>{const e=Object.assign(new Error(code),{code});if(typeof sqlstate==='string'&&/^[0-9A-Z]{5}$/.test(sqlstate))e.sqlstate=sqlstate;return e;};
// Root supplies its existing exclusive domain-session lease. No new broker/client
// is created and this store cannot join/reclaim an external operation transaction.
function create({enabled=false,client,withDomainSession,verifyFacts,verifyOriginalAttempt,verifyLiveContext,clock,kernel,deliverability}={}){
 const ready=enabled===true&&client&&typeof client.query==='function'&&[withDomainSession,verifyFacts,verifyOriginalAttempt,verifyLiveContext,clock,kernel?.select,deliverability?.createPolicy].every(x=>typeof x==='function');
 let session;if(ready){session=sessions.get(client);if(!session){session={busy:false,poisoned:false};sessions.set(client,session);}}
 const now=()=>{const n=clock();if(!C.nonnegative(n))throw closed('CONTROL_FACTS_CLOCK_REFUSED');return n;};
 async function use(work){if(!ready)throw closed('CONTROL_FACTS_OFF');if(session.poisoned)throw closed('CONTROL_FACTS_SESSION_UNAVAILABLE');if(session.busy)throw closed('CONTROL_FACTS_CLIENT_BUSY');session.busy=true;let calls=0,inner;try{const value=await withDomainSession(async()=>{if(++calls!==1)throw closed('CONTROL_FACTS_LEASE_REFUSED');inner=await work();return inner;});if(calls!==1||value!==inner)throw closed('CONTROL_FACTS_LEASE_REFUSED');return value;}catch(e){const allow=['CONTROL_FACTS_REFUSED','CONTROL_FACTS_OFF','CONTROL_FACTS_CLOCK_REFUSED','CONTROL_FACTS_LEASE_REFUSED','CONTROL_FACTS_CAS_REFUSED','CONTROL_FACTS_BINDING_REFUSED','CONTROL_FACTS_VERIFY_REFUSED','CONTROL_FACTS_ACK_UNKNOWN','CONTROL_FACTS_LOOKUP_UNKNOWN','CONTROL_FACTS_VETO','CONTROL_FACTS_FACT_MISSING'];const out=closed(allow.includes(e?.code)?e.code:'CONTROL_FACTS_REFUSED');if(typeof e?.sqlstate==='string'&&/^[0-9A-Z]{5}$/.test(e.sqlstate))out.sqlstate=e.sqlstate;else if(typeof e?.code==='string'&&/^[0-9A-Z]{5}$/.test(e.code))out.sqlstate=e.code;throw out;}finally{session.busy=false;}}
 async function tx(write,work){let begun=false,finish=false;try{begun=true;const start=await client.query(write?SQL.BEGIN_WRITE:SQL.BEGIN_READ);if(start?.command!=='BEGIN'){session.poisoned=true;throw closed('CONTROL_FACTS_ACK_UNKNOWN');}const value=await work();finish=true;const done=await client.query(write?SQL.COMMIT:SQL.ROLLBACK);if(done?.command!==(write?'COMMIT':'ROLLBACK'))throw closed('CONTROL_FACTS_ACK_UNKNOWN');return value;}catch(e){if(finish||['40001','57014','ECONNRESET','EPIPE','ETIMEDOUT','ENOTCONN'].includes(e?.code)||typeof e?.code==='string'&&e.code.startsWith('08')||!e?.code||!e.code.startsWith('CONTROL_FACTS_')&&!/^[0-9A-Z]{5}$/.test(e.code))session.poisoned=true;if(begun&&!finish){try{if((await client.query(SQL.ROLLBACK))?.command!=='ROLLBACK')throw Error();}catch{session.poisoned=true;throw closed('CONTROL_FACTS_ACK_UNKNOWN');}}if(finish){session.poisoned=true;throw closed('CONTROL_FACTS_ACK_UNKNOWN',e?.sqlstate||e?.code);}throw e;}}
 async function query(sql,params,command,max=1){const r=await client.query(sql,params);if(r?.command!==command||!Array.isArray(r.rows)||r.rows.length>max||r.rowCount!==r.rows.length)C.fail();for(let i=0;i<r.rows.length;i++)if(!Object.hasOwn(r.rows,String(i)))C.fail();return r.rows;}
 async function brand(brand,lock=false){const rows=await query(lock?SQL.LOCK_BRAND:SQL.BRAND,[brand],'SELECT');if(!rows.length)return null;C.exact(rows[0],['brand','revision']);C.assert(rows[0].brand===brand);const r=C.integer(rows[0].revision);C.assert(C.positive(r));return r;}
 async function heads(brand,keys){const rows=await query(SQL.HEADS,[brand,JSON.stringify(keys.map(k=>({kind:k.kind,fact_key:k.key})))],'SELECT',keys.length),map=new Map();const requested=new Set(keys.map(k=>k.kind+':'+k.key));for(const raw of rows){const r=C.row(raw),key=r.kind+':'+r.fact_key;C.assert(r.brand===brand&&requested.has(key)&&!map.has(key));map.set(key,r);}return map;}
 function event(raw,i){C.exact(raw,['brand','source_ref','event_ref','brand_revision','payload_hash','authority_ref','recorded_at','envelope']);C.assert(raw.brand===i.brand&&raw.source_ref===i.sourceRef&&raw.event_ref===i.eventRef&&C.hash(raw.authority_ref));const envelope=C.batch(raw.envelope);C.assert(C.digest(envelope)===raw.payload_hash&&envelope.brand===raw.brand&&envelope.sourceRef===raw.source_ref&&envelope.eventRef===raw.event_ref&&envelope.brandRevision===C.integer(raw.brand_revision));C.integer(raw.recorded_at);return C.capture({envelope,payloadHash:raw.payload_hash,brandRevision:envelope.brandRevision});}
 async function lookup(i){const rows=await query(SQL.EVENT,[i.brand,i.sourceRef,i.eventRef],'SELECT');return rows.length?event(rows[0],i):null;}
 const receipt=(i,h)=>C.capture({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,brandRevision:i.brandRevision,payloadHash:h,durable:true,sourceOnly:true,authorizesSend:false,operational:false});
 function policy(body,at){return deliverability.createPolicy({brand:body.brand,softBounceAttempts:body.initialSoftBounceAttempts,providers:['synthetic'],verifyClassifiedEvent:()=>{throw Error('read-only');},clock:()=>at});}
 async function bind(i,b,requirements){const rows=await query(SQL.ORIGINAL,[i.brand,b.operationId,b.attemptId],'SELECT');if(rows.length!==1)throw closed('CONTROL_FACTS_BINDING_REFUSED');const r=C.capture(rows[0]);C.assert(r.brand===i.brand&&r.operation_id===b.operationId&&r.attempt_id===b.attemptId&&['reserved','uncertain','accepted','rejected_before_send'].includes(r.state)&&r.reservation===true&&r.receipt_hash===b.operationReceiptHash&&C.positive(C.integer(r.revision))&&r.scope?.brand===i.brand&&r.scope.operationId===b.operationId&&r.scope.distributionId===b.distributionId&&C.integer(r.reserved_member_count)===r.scope.memberCount&&r.reserved_members_hash===r.scope.membersHash&&r.capacity_evidence_hash===r.scope.evidenceHash);
  for(const requirement of requirements)if(requirement.kind==='claim')C.assert(requirement.claim.state===r.state&&(!['accepted','rejected_before_send'].includes(r.state)||requirement.claim.receipt_hash===r.receipt_hash));
  let proof;try{proof=await verifyOriginalAttempt(C.capture({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,binding:b,requirements}),r);}catch{throw closed('CONTROL_FACTS_BINDING_REFUSED');}C.exact(proof,['brand','sourceRef','eventRef','bindingHash','requirementsHash','operationReceiptHash']);C.assert(proof.brand===i.brand&&proof.sourceRef===i.sourceRef&&proof.eventRef===i.eventRef&&proof.bindingHash===C.digest(b)&&proof.requirementsHash===C.digest(requirements)&&proof.operationReceiptHash===b.operationReceiptHash);
 }
 async function publish(raw){const i=C.batch(raw),payloadHash=C.digest(i);return use(async()=>{
  let proof;try{proof=await verifyFacts(i);}catch{throw closed('CONTROL_FACTS_VERIFY_REFUSED');}C.exact(proof,['brand','sourceRef','eventRef','payloadHash','authorityRef']);C.assert(proof.brand===i.brand&&proof.sourceRef===i.sourceRef&&proof.eventRef===i.eventRef&&proof.payloadHash===payloadHash&&C.hash(proof.authorityRef));
  await tx(true,async()=>{const current=await brand(i.brand,true),existing=await lookup(i);if(existing){if(existing.payloadHash!==payloadHash)throw closed('CONTROL_FACTS_VERIFY_REFUSED');return;}
   const at=now();if(i.observedAt>at||i.expiresAt<=at)throw closed('CONTROL_FACTS_VERIFY_REFUSED');if(current!==i.expectedBrandRevision||current!==null&&(current===C.MAX||i.brandRevision!==current+1))throw closed('CONTROL_FACTS_CAS_REFUSED');
   const prior=await heads(i.brand,i.facts.map(f=>({kind:f.kind,key:C.key(f.kind,f.body)}))),needed=new Set(),requirements=new Map();
   const requireBinding=(b,requirement)=>{const key=C.digest(b);if(!requirements.has(key))requirements.set(key,[]);requirements.get(key).push(requirement);needed.add(b.eventRef);};
   for(const f of i.facts){const old=prior.get(f.kind+':'+C.key(f.kind,f.body));if((old?.revision??null)!==f.expectedRevision||old&&f.revision<=old.revision)throw closed('CONTROL_FACTS_CAS_REFUSED');C.transition(f.kind,old?.body,f.body);
    if(f.kind==='policy'){policy(f.body,at).inspect(f.body,'0'.repeat(64));for(const r of f.body.records.slice(old?.body.records.length??0))if(r.type==='event'){needed.add(r.eventRef);const bindings=i.bindings.filter(b=>b.eventRef===r.eventRef&&b.attemptRef===r.attemptRef&&b.recipientRef===r.recipientRef);if(bindings.length!==1)throw closed('CONTROL_FACTS_BINDING_REFUSED');requireBinding(bindings[0],{kind:'policy-event',record:r});}}
    if(f.kind==='claims')for(const claim of f.body.claims){const previous=old?.body.claims.find(c=>c.subject_id===claim.subject_id);if(!previous||C.digest(previous)!==C.digest(claim)){const bindings=i.bindings.filter(b=>b.operationId===claim.operation_id&&b.subjectId===claim.subject_id&&b.distributionId===f.body.distribution_id);if(bindings.length!==1)throw closed('CONTROL_FACTS_BINDING_REFUSED');if(['accepted','rejected_before_send'].includes(claim.state)&&claim.receipt_hash!==bindings[0].operationReceiptHash)throw closed('CONTROL_FACTS_BINDING_REFUSED');requireBinding(bindings[0],{kind:'claim',claim});}}
   }
   if(i.inputKind==='original_attempt_event'){if(!i.bindings.length)throw closed('CONTROL_FACTS_BINDING_REFUSED');for(const b of i.bindings)requireBinding(b,{kind:'original-attempt-event',factsHash:C.digest(i.facts)});}
   const seen=new Set();for(const b of i.bindings){if(!needed.has(b.eventRef)||seen.has(C.digest(b)))throw closed('CONTROL_FACTS_BINDING_REFUSED');seen.add(C.digest(b));if(!requirements.has(C.digest(b)))throw closed('CONTROL_FACTS_BINDING_REFUSED');await bind(i,b,requirements.get(C.digest(b)));}if(needed.size&&!i.bindings.length)throw closed('CONTROL_FACTS_BINDING_REFUSED');
   const inserted=await query(SQL.INSERT_EVENT,[i.brand,i.sourceRef,i.eventRef,String(i.brandRevision),payloadHash,proof.authorityRef,String(at),JSON.stringify(i)],'INSERT');if(inserted.length!==1||C.integer(inserted[0].brand_revision)!==i.brandRevision)throw closed('CONTROL_FACTS_CAS_REFUSED');
   for(const f of i.facts){const k=C.key(f.kind,f.body),p=[i.brand,f.kind,k,String(f.revision)];const v=await query(SQL.INSERT_VERSION,[...p,JSON.stringify(f.body),C.digest(f.body),String(i.observedAt),String(i.expiresAt),i.sourceRef,i.eventRef,String(i.brandRevision)],'INSERT');if(v.length!==1||C.integer(v[0].revision)!==f.revision)C.fail();const h=await query(f.expectedRevision===null?SQL.INSERT_HEAD:SQL.UPDATE_HEAD,f.expectedRevision===null?p:[i.brand,f.kind,k,String(f.expectedRevision),String(f.revision)],f.expectedRevision===null?'INSERT':'UPDATE');if(h.length!==1||C.integer(h[0].revision)!==f.revision)throw closed('CONTROL_FACTS_CAS_REFUSED');}
   const rows=await query(current===null?SQL.INSERT_BRAND:SQL.UPDATE_BRAND,current===null?[i.brand,String(i.brandRevision)]:[i.brand,String(current),String(i.brandRevision)],current===null?'INSERT':'UPDATE');if(rows.length!==1||C.integer(rows[0].revision)!==i.brandRevision)throw closed('CONTROL_FACTS_CAS_REFUSED');
  });return receipt(i,payloadHash);
 });}
 async function inspectBatch(raw){C.exact(raw,['brand','sourceRef','eventRef']);const i=C.capture(raw);C.assert(['fish','aristo'].includes(i.brand)&&C.hash(i.sourceRef)&&C.hash(i.eventRef));return use(async()=>{try{const r=await tx(false,()=>lookup(i));return r?receipt(r.envelope,r.payloadHash):C.capture({state:'unknown',sourceOnly:true,operational:false,authorizesSend:false});}catch{throw closed('CONTROL_FACTS_LOOKUP_UNKNOWN');}});}
 async function readHistorical(raw){C.exact(raw,['brand','kind','key','revision']);const i=C.capture(raw);C.assert(['fish','aristo'].includes(i.brand)&&['consent','policy','suspension','capping','capacity','claims'].includes(i.kind)&&typeof i.key==='string'&&i.key.length>0&&i.key.length<=300&&C.positive(i.revision));return use(async()=>{try{const r=await tx(false,async()=>{const rows=await query(SQL.HISTORY,[i.brand,i.kind,i.key,String(i.revision)],'SELECT');if(!rows.length)return null;const row=C.row(rows[0]);C.assert(row.brand===i.brand&&row.kind===i.kind&&row.fact_key===i.key&&row.revision===i.revision);return row;});return C.capture({state:r?'historical':'unknown',fact:r,sourceOnly:true,operational:false,authorizesSend:false});}catch{throw closed('CONTROL_FACTS_LOOKUP_UNKNOWN');}});}
 async function liveInside(i){const at=now(),brandRevision=await brand(i.brand);if(!brandRevision)throw closed('CONTROL_FACTS_FACT_MISSING');const distribution=kernel.distribution(i.selection.distribution);C.assert(distribution.brand===i.brand);const capacityKey=JSON.stringify([distribution.id,distribution.revision,i.campaign.campaign_id,i.campaign.campaign_version]),ledgerKey=JSON.stringify([distribution.id,distribution.revision]);const rows=await heads(i.brand,[{kind:'policy',key:'brand'},{kind:'suspension',key:'brand'},{kind:'claims',key:ledgerKey},{kind:'capacity',key:capacityKey}]);const used=[];
  const get=(map,kind,key)=>{const r=map.get(kind+':'+key);if(!r||r.brand_revision>brandRevision)throw closed('CONTROL_FACTS_FACT_MISSING');if(r.observed_at>at||r.expires_at<=at)throw closed('CONTROL_FACTS_VETO');used.push(r);return r.body;};
  const policyState=get(rows,'policy','brand'),suspension=get(rows,'suspension','brand'),claims=get(rows,'claims',ledgerKey),capacity=get(rows,'capacity',capacityKey);
  const selection={...i.selection,claims,now:at},current=kernel.select(selection);if(current.state!=='prepared'||current.selected_count===0||suspension.suspension!=='clear'||capacity.limit-capacity.acceptedCount-capacity.reservedCount<current.selected_count)throw closed('CONTROL_FACTS_VETO');
  const map=new Map(i.memberBindings.map(b=>[b.subjectId,b.recipientRef])),keys=[];for(const subjectId of current.member_ids){const recipientRef=map.get(subjectId);if(!recipientRef)throw closed('CONTROL_FACTS_BINDING_REFUSED');keys.push({kind:'consent',key:JSON.stringify([subjectId,recipientRef])},{kind:'capping',key:JSON.stringify([subjectId,recipientRef])});}
  const membersRows=await heads(i.brand,keys),members=[];for(const subjectId of current.member_ids){const recipientRef=map.get(subjectId),key=JSON.stringify([subjectId,recipientRef]),consent=get(membersRows,'consent',key),capping=get(membersRows,'capping',key);if(consent.consent!=='current'||at<capping.windowStart||at>=capping.windowEnd||capping.limit-capping.acceptedCount-capping.reservedCount<=0||policy(policyState,at).inspect(policyState,recipientRef).houseSuppressed)throw closed('CONTROL_FACTS_VETO');members.push({subjectId,recipientRef,consent:'current',consentRevision:consent.consentRevision,capping:'clear',cappingRevision:capping.cappingRevision,bounce:'current',policyState,policyRevision:policyState.revision});}
  const observedAt=used.reduce((minimum,r)=>Math.min(minimum,r.observed_at),C.MAX),expiresAt=used.reduce((minimum,r)=>Math.min(minimum,r.expires_at),C.MAX);const finishedAt=now();C.assert(finishedAt>=at&&expiresAt>finishedAt&&expiresAt-observedAt<=60000);
  const evidence={brand:i.brand,membersHash:current.members_hash,campaignId:i.campaign.campaign_id,campaignVersion:i.campaign.campaign_version,ledgerRevision:claims.revision,revision:brandRevision,observedAt,expiresAt,authority:'admitted',suspension:'clear',members};
  const guards=i.contentGuards;C.assert(guards.consent_current===true&&guards.bounce_current===true&&guards.frequency_current===true);
  return C.capture({live:{operationId:i.operationId,selection,before:i.before,campaign:i.campaign,beforeCampaign:i.beforeCampaign,guards,evidence,now:at},revisionVector:{brandRevision,facts:used.map(r=>({kind:r.kind,key:r.fact_key,revision:r.revision,bodyHash:r.body_hash}))},expiresAt,sourceOnly:true,operational:false,authorizesSend:false});
 }
 async function readForEvaluation(raw,evaluate){const i=C.liveRequest(raw);if(evaluate!==undefined&&typeof evaluate!=='function')C.fail();return use(async()=>{let proof;try{proof=await verifyLiveContext(i);}catch{throw closed('CONTROL_FACTS_VERIFY_REFUSED');}C.exact(proof,['brand','operationId','contextHash']);C.assert(proof.brand===i.brand&&proof.operationId===i.operationId&&proof.contextHash===C.digest(i));return tx(false,async()=>{const result=await liveInside(i);if(evaluate===undefined)return result;const decision=evaluate(result.live);if(decision&&typeof decision.then==='function')C.fail();return C.capture({...result,decision});});});}
 return Object.freeze({sourceOnly:true,operational:false,completeReservation:false,publish,inspectBatch,readHistorical,readForEvaluation});
}
module.exports=Object.freeze({ENABLED:false,create});
