const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../n8n/growth/attribution.js');
const v=(at,source='email',campaign='launch',extra={})=>({occurredAt:at,source:source==='direct'?'direct':source,utmParameters:source==='direct'?null:{source,medium:'campanha',campaign,content:'cta'},...extra});
const base=()=>({_marca:'aristo',id:'gid://shopify/Order/1',name:'#1',createdAt:'2026-09-15T12:00:00Z',updatedAt:'2026-09-15T12:00:00Z',test:false,cancelledAt:null,displayFinancialStatus:'PAID',netPaymentSet:{shopMoney:{amount:'99.50',currencyCode:'BRL'}},customerJourneySummary:{ready:true,customerOrderIndex:1,moments:{pageInfo:{hasNextPage:false},nodes:[]}}});
test('strict last click and non-direct are different and each has one winner',()=>{
 const o=base(),e=v('2026-09-14T12:00:00Z'),d=v('2026-09-15T11:59:00Z','direct');o.customerJourneySummary.moments.nodes=[e,d];o.customerJourneySummary.lastVisit=d;
 const r=A.classify(o);assert.equal(r.last_click.channel,null);assert.equal(r.last_non_direct.channel,'email');assert.equal(r.net_amount,99.5);
});
test('lastVisit is considered even when not in the moments page',()=>{const o=base();o.customerJourneySummary.moments.nodes=[v('2026-09-14T12:00:00Z')];o.customerJourneySummary.lastVisit=v('2026-09-15T11:00:00Z','whatsapp');assert.equal(A.classify(o).last_non_direct.channel,'whatsapp');});
test('future and older than 30 day visits cannot win or assist',()=>{const o=base();o.customerJourneySummary.moments.nodes=[v('2026-09-16T00:00:00Z'),v('2026-08-01T00:00:00Z')];const r=A.classify(o);assert.equal(r.last_non_direct,null);assert.equal(r.touches.length,0);});
test('own-store referral does not steal credit, external referrer does',()=>{const o=base(),e=v('2026-09-14T12:00:00Z');o.customerJourneySummary.moments.nodes=[e,v('2026-09-15T11:00:00Z','direct','',{referrerUrl:'https://oaristocrata.com/cart'})];assert.equal(A.classify(o).last_non_direct.channel,'email');o.customerJourneySummary.lastVisit=v('2026-09-15T11:59:00Z','direct','',{referrerUrl:'https://google.com/search?q=soap'});assert.equal(A.classify(o).last_non_direct.channel,null);});
test('only recognized CRM sources count, including legacy Reportana',()=>{for(const [s,c]of [['listmonk','email'],['disparoreportana','whatsapp'],['whatsapp','whatsapp'],['google',null]])assert.equal(A.channel({source:s}),c);assert.equal(A.channel({source:'email',medium:'organico'}),null);});
test('unresolved and truncated journeys remain explicit',()=>{const o=base();o.customerJourneySummary.ready=false;assert.equal(A.classify(o).ready,false);o.customerJourneySummary.ready=true;o.customerJourneySummary.moments.pageInfo.hasNextPage=true;assert.equal(A.classify(o).non_direct_known,false);o.customerJourneySummary.moments.nodes=[v('2026-09-15T11:00:00Z')];assert.equal(A.classify(o).non_direct_known,true);assert.equal(A.classify(o).complete,false);});
test('paid, partially refunded, cancelled, test, currency and payment amount guards',()=>{const o=base();assert.equal(A.classify(o).eligible,true);o.displayFinancialStatus='PARTIALLY_REFUNDED';assert.equal(A.classify(o).eligible,true);for(const change of [{displayFinancialStatus:'PENDING'},{test:true},{cancelledAt:'2026-09-15T12:00:01Z'},{netPaymentSet:{shopMoney:{amount:'0',currencyCode:'BRL'}}},{netPaymentSet:{shopMoney:{amount:'50',currencyCode:'USD'}}},{netPaymentSet:null}])assert.equal(A.classify({...base(),...change}).eligible,false);});
test('repeated visits do not create repeated touches',()=>{const o=base(),e=v('2026-09-15T11:00:00Z');o.customerJourneySummary.moments.nodes=[e,e];o.customerJourneySummary.lastVisit=e;assert.equal(A.classify(o).touches.length,1);});
test('customer type uses the index of this order, not the customer current order total',()=>{const o=base();o.customer={numberOfOrders:10};assert.equal(A.classify(o).customer_order_index,1);});
test('portable classification does not depend on URL global in the automation runtime',()=>{const vm=require('node:vm'),fs=require('node:fs'),source=fs.readFileSync(require.resolve('../n8n/growth/attribution.js'),'utf8');const ctx={module:{exports:{}}};vm.runInNewContext(source,ctx);const o=base();o.customerJourneySummary.moments.nodes=[v('2026-09-14T12:00:00Z'),v('2026-09-15T11:00:00Z','direct','',{referrerUrl:'https://www.oaristocrata.com/cart'})];assert.equal(JSON.stringify(ctx.module.exports.classify(o)),JSON.stringify(A.classify(o)));assert.equal(A.classify(o).last_non_direct.channel,'email');});
test('first visit cannot fill a gap in a truncated recent-first journey',()=>{const o=base();o.customerJourneySummary.moments.pageInfo.hasNextPage=true;o.customerJourneySummary.firstVisit=v('2026-09-01T11:00:00Z');o.customerJourneySummary.moments.nodes=[v('2026-09-15T11:00:00Z','direct')];assert.equal(A.classify(o).non_direct_known,false);assert.equal(A.classify(o).last_non_direct,null);});
test('internal full-URL sources and PIX payment returns cannot steal non-direct credit',()=>{for(const url of ['https://www.fishermans.com.br/','https://conta.oaristocrata.com/','https://pix-on-site.appmax.com.br/']){const o=base();if(url.includes('fishermans'))o._marca='fish';o.customerJourneySummary.moments.nodes=[v('2026-09-14T12:00:00Z'),v('2026-09-15T11:00:00Z','direct','',{referrerUrl:url,source:url})];o.customerJourneySummary.lastVisit=o.customerJourneySummary.moments.nodes.at(-1);const r=A.classify(o);assert.equal(r.last_non_direct.channel,'email');assert.equal(r.last_click.channel,null);}});

test('Olivas uses its verified store domain and the same strict attribution guards',()=>{const o=base();o._marca='olivas';const e=v('2026-09-14T12:00:00Z');o.customerJourneySummary.moments.nodes=[e];o.customerJourneySummary.lastVisit=v('2026-09-15T11:00:00Z','direct','',{referrerUrl:'https://www.olivasdocampo.com.br/cart',source:'https://olivasdocampo.com.br/'});const r=A.classify(o);assert.equal(r.brand,'olivas');assert.equal(r.last_non_direct.channel,'email');assert.equal(r.last_click.channel,null);o.displayFinancialStatus='PENDING';assert.equal(A.classify(o).eligible,false);});
