-- Run after campaign-store.sql in ONE transaction, then ROLLBACK.
DO $test$
DECLARE c jsonb;r jsonb;p jsonb;k text:='campaign-store-test-000001';v jsonb;bad boolean;
BEGIN
 p:=jsonb_build_object('actor','campaign-store-test','key',k,'hash',repeat('a',64),'brand','fish','action','salvar');
 c:=public.shrigma_campaign_store('claim',p);
 ASSERT (c->>'acquired')::boolean AND c->>'lease' IS NOT NULL,'first claim';
 r:=public.shrigma_campaign_store('claim',p);
 ASSERT NOT (r->>'acquired')::boolean AND r->>'lease' IS NULL,'repeat must not acquire or expose lease';
 r:=public.shrigma_campaign_store('claim',p||jsonb_build_object('hash',repeat('b',64)));
 ASSERT r->>'hash'=repeat('a',64) AND NOT (r->>'acquired')::boolean,'conflicting digest preserved';
 r:=public.shrigma_campaign_store('claim',p||'{"actor":"other-actor"}'::jsonb);
 ASSERT (r->>'acquired')::boolean AND r->>'id'<>c->>'id','actor scoped key';
 bad:=false;
 BEGIN PERFORM public.shrigma_campaign_store('provider',jsonb_build_object('id',c->>'id','lease',gen_random_uuid(),'providerId',123));
 EXCEPTION WHEN raise_exception THEN bad:=true;END;
 ASSERT bad,'wrong lease refused';
 PERFORM public.shrigma_campaign_store('provider',jsonb_build_object('id',c->>'id','lease',c->>'lease','providerId',123));
 bad:=false;
 BEGIN PERFORM public.shrigma_campaign_store('provider',jsonb_build_object('id',c->>'id','lease',c->>'lease','providerId',456));
 EXCEPTION WHEN raise_exception THEN bad:=true;END;
 ASSERT bad,'provider identity cannot change';
 v:=jsonb_build_object('id',c->>'id','lease',c->>'lease','state','outcome_unknown','response',jsonb_build_object('status',502,'body',jsonb_build_object('error','OUTCOME_UNKNOWN')));
 PERFORM public.shrigma_campaign_store('finish',v);
 PERFORM public.shrigma_campaign_store('finish',v);
 r:=public.shrigma_campaign_store('get',p);
 ASSERT r->>'state'='outcome_unknown' AND r->>'providerId'='123' AND NOT (r ? 'lease'),'unknown result retains provider but no lease';
 UPDATE public.shrigma_campaign_operation SET created_at=clock_timestamp()-interval '1 year' WHERE id=(c->>'id')::uuid;
 r:=public.shrigma_campaign_store('claim',p);
 ASSERT NOT (r->>'acquired')::boolean AND r->>'state'='outcome_unknown','old unknown never automatically retried';
 bad:=false;
 BEGIN PERFORM public.shrigma_campaign_store('finish',v||'{"state":"succeeded"}'::jsonb);
 EXCEPTION WHEN raise_exception THEN bad:=true;END;
 ASSERT bad,'late success cannot overwrite terminal uncertainty';
 r:=public.shrigma_campaign_store('get',p||'{"actor":"missing-actor"}'::jsonb);
 ASSERT r='null'::jsonb,'polling cannot access another actor';
 v:='{"policy":"crm-campaign-v1","version":"v2","ok":true,"validated_at":"2026-09-18T00:00:00Z"}'::jsonb;
 PERFORM public.shrigma_campaign_store('validation_set',jsonb_build_object('providerId',123,'validation',v));
 ASSERT public.shrigma_campaign_store('validation_get','{"providerId":123}')=v,'validation version retained';
 PERFORM public.shrigma_campaign_store('validation_invalidate','{"providerId":123}');
 ASSERT public.shrigma_campaign_store('validation_get','{"providerId":123}')='null'::jsonb,'edited draft invalidates validation';
 bad:=false;
 BEGIN PERFORM public.shrigma_campaign_store('claim',p||'{"brand":"olivas","key":"campaign-store-olivas-test"}');
 EXCEPTION WHEN raise_exception THEN bad:=true;END;
 ASSERT bad,'Olivas expansion paused';
 bad:=false;
 BEGIN PERFORM public.shrigma_campaign_store('claim',p||'{"hash":"invalid"}');
 EXCEPTION WHEN raise_exception THEN bad:=true;END;
 ASSERT bad,'invalid hash rejected';
END $test$;
SELECT 'passed' AS campaign_store_tests, count(*) AS synthetic_operations FROM public.shrigma_campaign_operation WHERE actor IN ('campaign-store-test','other-actor');
