const audience=require('./campaign-audience-fixture.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),{createService}=require('../n8n/growth/campaign-service'),C=require('../n8n/growth/campaign-contract');
const d=()=>({schema_version:C.VERSION,brand:'fish',channel:'email',initiative:{key:'cliente-2026',name:'Dia do Cliente'},utm_campaign:'fish-cliente',name:'Clientes',subject:'Novos kits',from_email:'Fishermans <contato@fishermans.com.br>',reply_to:'contato@fishermans.com.br',list_ids:[125],template_id:1,html:'<a href="https://fishermans.com.br/products/kit">Kit</a> {{ UnsubscribeURL }}',text:'https://fishermans.com.br/products/kit\n{{ UnsubscribeURL }}',tags:[],send_at:'2026-09-18T19:00:00-03:00'});
const auth={actor:'content',caps:['read_content','draft','validate','submit']};
function fixture(){const rows=new Map(),ops=new Map(),valid=new Map(),calls={create:0,update:0,schedule:0};let next=100;
 const store={async claim(p){const key=p.actor+'|'+p.key;if(ops.has(key))return {...ops.get(key),acquired:false};const o={...p,id:key,lease:'lease',acquired:true};ops.set(key,o);return o;},async setProviderId(id,l,pid){ops.get(id).providerId=pid;},async finish(id,l,r){Object.assign(ops.get(id),r);},async getOperation(a,k){return ops.get(a+'|'+k);},async invalidateValidation(id){valid.delete(id);},async setValidation(id,v){valid.set(id,v);},async getValidation(id){return valid.get(id);}};
 const provider={async catalog(brand){return {brand,current:true,lists:[{id:125,brand:'fish',available:true}],templates:[{id:1,type:'campaign',available:true}],initiatives:[]};},async list(){return [...rows.values()];},async get(id){return structuredClone(rows.get(id));},async createDraft(def){calls.create++;const r={id:next++,version:'v1',status:'draft',sent:0,started_at:null,send_at:C.normalize(def).send_at,definition:C.normalize(def)};rows.set(r.id,r);return structuredClone(r);},async updateDraft(id,p,{expectedVersion}){calls.update++;const r=rows.get(id);if(r.version!==expectedVersion)throw Object.assign(Error('conflict'),{code:'VERSION_CONFLICT',status:409,nothingChanged:true});Object.assign(r,{version:'v2',definition:p.definition,send_at:p.definition.send_at});return structuredClone(r);},async reviewAudience(id){const c=rows.get(id),v={policy:C.VERSION,version:c.version,ok:true,validated_at:'2026-09-17T12:00:00Z',audience:audience(c,Date.parse('2026-09-17T12:00:00Z'))};valid.set(id,v);return {campaign:structuredClone(c),validation:v};},async schedule(id,{expectedVersion,audienceReviewId}){calls.schedule++;const r=rows.get(id);if(r.version!==expectedVersion)throw Object.assign(Error('conflict'),{code:'VERSION_CONFLICT',status:409,nothingChanged:true});r.status='scheduled';return {...structuredClone(r),audience:valid.get(id).audience};}};
 const service=createService({store,provider,now:()=>Date.parse('2026-09-17T12:00:00Z')});return {service,provider,store,rows,ops,calls};}
const req=(acao,extra={})=>({acao:'campanha_'+acao,brand:'fish',idempotency_key:'operation-'+acao+'-000001',...extra});
test('save creates only a draft; validate binds a version; scheduling requires its own action',async()=>{const f=fixture(),saved=await f.service.handle(auth,req('salvar',{definition:d()}));assert.equal(saved.status,201);assert.equal(saved.body.campaign.status,'draft');assert.equal(f.calls.schedule,0);const {id,version}=saved.body.campaign;const v=await f.service.handle(auth,req('validar',{id,expected_version:version}));assert.equal(v.status,200);const s=await f.service.handle(auth,req('agendar',{id,expected_version:version,confirm:'agendar',audience_review_id:v.body.validation.audience.review_id}));assert.equal(s.status,200);assert.equal(f.calls.schedule,1);});
test('same idempotency key does not create another campaign, including simultaneous requests',async()=>{const f=fixture(),r=req('salvar',{definition:d()});await Promise.all([f.service.handle(auth,r),f.service.handle(auth,r)]);assert.equal(f.calls.create,1);const replay=await f.service.handle(auth,r);assert.equal(replay.status,201);assert.equal(f.calls.create,1);});
test('idempotency key reused with another payload fails without another provider call',async()=>{const f=fixture();await f.service.handle(auth,req('salvar',{definition:d()}));const r=await f.service.handle(auth,req('salvar',{definition:{...d(),subject:'Changed'}}));assert.equal(r.status,409);assert.equal(f.calls.create,1);});
test('a timeout after remote creation remains uncertain and cannot repeat creation',async()=>{const f=fixture(),create=f.provider.createDraft;f.provider.createDraft=async(...a)=>{await create(...a);throw Error('timeout');};const r=req('salvar',{definition:d()});const a=await f.service.handle(auth,r);assert.equal(a.status,502);assert.equal(a.body.error,'OUTCOME_UNKNOWN');await f.service.handle(auth,r);assert.equal(f.calls.create,1);});
test('a failed update after draft reservation keeps its provider ID in the operation',async()=>{const f=fixture();f.provider.updateDraft=async()=>{throw Error('timeout');};const r=await f.service.handle(auth,req('salvar',{definition:d()}));assert.equal(r.status,502);assert.equal(r.body.provider_id,100);assert.equal([...f.ops.values()][0].providerId,100);assert.equal(f.calls.schedule,0);});
test('a read-only key cannot save or schedule',async()=>{const f=fixture();const r=await f.service.handle({...auth,caps:['read_content']},req('salvar',{definition:d()}));assert.equal(r.status,403);assert.equal(f.calls.create,0);});
test('external changes invalidate the previously checked version before scheduling',async()=>{const f=fixture();const s=await f.service.handle(auth,req('salvar',{definition:d()}));const {id,version}=s.body.campaign;await f.service.handle(auth,req('validar',{id,expected_version:version}));f.rows.get(id).version='v3';const r=await f.service.handle(auth,req('agendar',{id,expected_version:version,confirm:'agendar'}));assert.equal(r.status,409);assert.equal(f.calls.schedule,0);});
test('unknown finalization keeps the operation claimed and blocks a new transmission',async()=>{const f=fixture();f.store.finish=async()=>{throw Error('db unavailable');};const r=req('salvar',{definition:d()});const a=await f.service.handle(auth,r);assert.equal(a.status,502);await f.service.handle(auth,r);assert.equal(f.calls.create,1);});

test('legacy validation stays readable but cannot authorize a fresh schedule',async()=>{const f=fixture(),saved=await f.service.handle(auth,req('salvar',{definition:d()})),{id,version}=saved.body.campaign;await f.store.setValidation(id,{policy:C.VERSION,version,ok:true,validated_at:'2026-09-17T12:00:00Z'});const old=await f.service.handle(auth,req('obter',{id}));assert.equal(old.status,200);assert.equal(old.body.campaign.id,id);assert.equal((await f.store.getValidation(id)).ok,true);const r=await f.service.handle(auth,req('agendar',{id,expected_version:version,confirm:'agendar'}));assert.equal(r.body.error,'AUDIENCE_REVIEW_REQUIRED');assert.equal(f.calls.schedule,0);});
