const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../n8n/growth/campaign-contract'),T=require('../n8n/growth/campaign-tracking');
const base=()=>({schema_version:C.VERSION,brand:'aristo',channel:'email',initiative:{key:'semana-cliente-2026',name:'Semana do Cliente'},utm_campaign:'aristo-cliente',name:'Abertura · base quente',subject:'Um presente para você',from_email:'O Aristocrata <avisos@oaristocrata.com>',reply_to:'contato@oaristocrata.com',list_ids:[123],template_id:1,html:'<a href="https://oaristocrata.com/products/kit?variant=10">Kit</a><a href="{{ UnsubscribeURL }}">Sair</a>',text:'Kit: https://oaristocrata.com/products/kit?variant=10\nSair: {{ UnsubscribeURL }}',tags:['abertura'],send_at:'2026-09-17T18:00:00-03:00'});
const catalog={brand:'aristo',current:true,lists:[{id:123,brand:'aristo',available:true}],templates:[{id:1,type:'campaign',available:true}],initiatives:[]};
test('AI JSON and dashboard fields normalize into the same explicit contract',()=>{const d=C.normalize(base());assert.equal(d.send_at,'2026-09-17T21:00:00.000Z');assert.deepEqual(d.list_ids,[123]);assert.equal(d.initiative.key,'semana-cliente-2026');});
test('server-reserved identity tags HTML and text while keeping initiative separate from dispatch',()=>{const r=C.prepare(base(),{catalog,tracking:T,trackingId:987});assert.equal(r.tracking.term,'lm-987-l123');assert.match(r.definition.text,/utm_term=lm-987-l123/);assert.match(r.definition.html,/variant=10/);assert.equal(r.payload.attribs.crm.initiative_key,'semana-cliente-2026');assert.equal(r.payload.attribs.crm.tracking_term,'lm-987-l123');});
test('scope cannot be expanded by a different sender, brand, list or transactional template',()=>{assert.throws(()=>C.normalize({...base(),from_email:'other@elsewhere.example'}),{code:'SENDER_BRAND'});assert.throws(()=>C.prepare({...base(),list_ids:[555]},{catalog,tracking:T,trackingId:987}),{code:'LIST_SCOPE'});assert.throws(()=>C.prepare(base(),{catalog:{...catalog,templates:[{id:1,type:'tx',available:true}]},tracking:T,trackingId:987}),{code:'TEMPLATE_SCOPE'});assert.throws(()=>C.normalize({...base(),channel:'whatsapp'}),{code:'CHANNEL_UNAVAILABLE'});});
test('commercial initiative cannot silently override a previous mapping',()=>{assert.throws(()=>C.prepare(base(),{catalog:{...catalog,initiatives:[{utm_campaign:'aristo-cliente',key:'other'}]},tracking:T,trackingId:987}),{code:'INITIATIVE_CONFLICT'});});
test('HTML, text, timezone and unsubscribe are mandatory',()=>{for(const [patch,code] of [[{text:''},'FIELD_INVALID'],[{html:'<p>Hello</p>'},'UNSUBSCRIBE_MISSING'],[{send_at:'2026-09-17T18:00'},'SCHEDULE_TIMEZONE'],[{html:base().html+'<script>alert(1)</script>'},'HTML_ACTIVE_CONTENT']])assert.throws(()=>C.normalize({...base(),...patch}),{code});});
test('no fake campaign identity or missing catalog can prepare links',()=>{assert.throws(()=>C.prepare(base(),{catalog,tracking:T}),{code:'TRACKING_ID_REQUIRED'});assert.throws(()=>C.prepare(base(),{catalog:{...catalog,current:false},tracking:T,trackingId:123}),{code:'CATALOG_UNAVAILABLE'});});
test('scheduling binds the exact reviewed version and never starts a campaign immediately',()=>{const current={id:987,status:'draft',sent:0,started_at:null,version:'v1',validation:{policy:C.VERSION,version:'v1',ok:true},send_at:'2026-09-17T21:00:00Z'},opts={now:Date.parse('2026-09-17T19:00:00Z'),canPublish:true};const req={confirm:'agendar',expected_version:'v1'};assert.deepEqual(C.schedule(req,current,opts),{method:'PUT',path:'/api/campaigns/987/status',body:{status:'scheduled'}});for(const [patch,code] of [[{version:'v2'},'VERSION_CONFLICT'],[{status:'running'},'CAMPAIGN_ALREADY_STARTED'],[{sent:1},'CAMPAIGN_ALREADY_STARTED'],[{validation:{ok:false}},'VALIDATION_STALE'],[{send_at:'2026-09-17T19:01:00Z'},'SCHEDULE_TOO_SOON']])assert.throws(()=>C.schedule(req,{...current,...patch},opts),{code});assert.throws(()=>C.schedule(req,current,{...opts,canPublish:false}),{code:'CAPABILITY_MISSING'});});
test('write operations require idempotency and an explicit scheduling confirmation',()=>{assert.throws(()=>C.request('salvar',{definition:base()}),{code:'IDEMPOTENCY_REQUIRED'});assert.equal(C.request('salvar',{definition:base()},{idempotencyKey:'request-000000000001'}).acao,'campanha_salvar');assert.throws(()=>C.schedule({expected_version:'v1'},{id:1,version:'v1'},{canPublish:true}),{code:'CONFIRM_REQUIRED'});});
test('sender brackets, subject injection, invalid dates and action overrides are rejected',()=>{
 for(const from_email of ['Nome <avisos@oaristocrata.com','avisos@oaristocrata.com>'])assert.throws(()=>C.normalize({...base(),from_email}),{code:'SENDER_BRAND'});
 assert.throws(()=>C.normalize({...base(),subject:'Hello\r\nBcc: other@example.org'}),{code:'SUBJECT_INVALID'});
 assert.equal(C.request('catalogo',{acao:'campanha_agendar'}).acao,'campanha_catalogo');
 const current={id:1,version:'1',status:'draft',sent:0,validation:{policy:C.VERSION,version:'1',ok:true},send_at:'invalid'};
 assert.throws(()=>C.schedule({confirm:'agendar',expected_version:'1'},current,{canPublish:true}),{code:'SCHEDULE_TOO_SOON'});
});
test('an existing audience term and coupon redirect retain valid tracking across saves',()=>{
 const d=base();d.html='<a href="https://oaristocrata.com/discount/OFF?redirect=%2Fproducts%2Fkit%3Futm_term%3Dquentes">Kit</a> {{ UnsubscribeURL }}';d.text='https://oaristocrata.com/products/kit?utm_term=quentes\n{{ UnsubscribeURL }}';
 const p=C.prepare(d,{catalog,tracking:T,trackingId:987});assert.match(p.definition.text,/utm_term=quentes--lm-987-l123/);
 assert.deepEqual(C.prepare(p.definition,{catalog,tracking:T,trackingId:987}).definition,p.definition);
});

test('Olivas preserves its distinct email domain and shop domain with scoped lists and tracked links',()=>{const d={...base(),brand:'olivas',from_email:'Olivas do Campo <sac@olivasdocampo.com>',reply_to:'sac@olivasdocampo.com',list_ids:[40],html:base().html.replaceAll('oaristocrata.com','olivasdocampo.com.br'),text:base().text.replaceAll('oaristocrata.com','olivasdocampo.com.br')};const cat={...catalog,brand:'olivas',lists:[{id:40,brand:'olivas',available:true}]};const r=C.prepare(d,{catalog:cat,tracking:T,trackingId:987});assert.match(r.definition.html,/olivasdocampo.com.br/);assert.match(r.definition.text,/utm_term=lm-987-l40/);assert.equal(r.definition.from_email,d.from_email);assert.throws(()=>C.normalize({...d,from_email:'sac@oaristocrata.com'}),{code:'SENDER_BRAND'});assert.throws(()=>C.prepare(d,{catalog,tracking:T,trackingId:987}),{code:'CATALOG_UNAVAILABLE'});});
