'use strict';
// Exact public families + extracted cold runtime. Synthetic public assets and
// private descriptors only; no tools tree, listeners, transports, sends or IAM.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib'),{spawnSync}=require('node:child_process');
const DIR=path.resolve(__dirname,'../services/dashboard-operational'),P=require(DIR+'/artifact-policy.cjs'),{pack}=require(DIR+'/pack-runtime.cjs');
const entries=names=>names.map(file=>({path:file,encoding:P.isText(file)?'utf8':'base64',content:P.isText(file)?'synthetic fixture':Buffer.from('synthetic binary').toString('base64')}));
function wrap(files,schema){const raw=Buffer.from(JSON.stringify(files)),key=schema===P.SCHEMA?'gzipBase64':'brotliBase64';return JSON.stringify({schema,sha256:P.sha(raw),[key]:(schema===P.SCHEMA?zlib.gzipSync(raw):zlib.brotliCompressSync(raw)).toString('base64')});}
function temporary(t){const d=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'coexist-package-')));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));return d;}
function fixture(t){const d=temporary(t),dist=path.join(d,'dist');for(const f of entries(P.PUBLIC_FILES.map(f=>'public/'+f))){const p=path.join(dist,f.path);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,Buffer.from(f.content,f.encoding));}const meta=pack(dist,path.join(d,'pack')),packFile=path.join(d,'pack/runtime-pack.json'),artifact=P.unpack(packFile,path.join(d,'extracted'),{expectedSha256:meta.packSha256});return {d,meta,packFile,artifact};}
test('all four complete historical families and current29 decode exactly under both algorithms; partial/extra/duplicate sets refuse',()=>{
 for(const [names,count]of [[P.LEGACY_FILES,18],[P.PRE_PARITY_FILES,23],[P.PARITY_FILES,26],[P.PRE_COEXISTENCE_FILES,28],[P.FILES,29]]){
  assert.equal(names.length,P.PUBLIC_FILES.length+count);const files=entries(names);
  for(const schema of [P.SCHEMA,P.SCHEMA_V2]){const w=wrap(files,schema),d=P.decodePack(w,JSON.parse(w).sha256);assert.deepEqual(d.files,files);assert.equal(d.stats.runtimeFiles,count);}
  for(const mutate of [a=>a.pop(),a=>a.push({path:'runtime/unreviewed.cjs',encoding:'utf8',content:'extra'}),a=>{a[0]=a[1];},a=>{a[0]={...a[0],path:'runtime/unreviewed.cjs'};}]){const f=structuredClone(files);mutate(f);assert.throws(()=>P.validateFiles(f));}
 }
 assert.equal(P.PRE_COEXISTENCE_RUNTIME_FILES.length,28);assert.deepEqual(P.COEXISTENCE_RUNTIME_FILES,['crm-individual-coexistence.cjs']);assert.deepEqual(P.RUNTIME_FILES,[...P.PRE_COEXISTENCE_RUNTIME_FILES,...P.COEXISTENCE_RUNTIME_FILES].sort());
});
test('Docker build copies coexistence dependency once, leaves runtime image defaults OFF and retains pinned base/UID',()=>{const docker=fs.readFileSync(DIR+'/Dockerfile','utf8');assert.equal((docker.match(/COPY services\/dashboard-operational\/crm-individual-coexistence.cjs/g)||[]).length,1);assert.match(docker,/USER 1000:1000/);assert.doesNotMatch(docker,/DASHBOARD_CRM_INDIVIDUAL_COEXISTENCE=enabled/);assert.match(docker,/DASHBOARD_MODE=synthetic/);assert.equal((docker.match(/node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402/g)||[]).length,2);});
test('original CREATE cold subprocess regression passes against current extracted package with heap128',t=>{const f=fixture(t),cold=spawnSync(process.execPath,['--no-warnings','--max-old-space-size=128',path.join(__dirname,'dashboard-operational-campaign-create-packaging.test.cjs'),'cold',f.packFile],{env:{},encoding:'utf8',timeout:15000});assert.equal(cold.status,0,cold.stderr);const proof=JSON.parse(cold.stdout);assert.equal(proof.offNoCreateTable,true);assert.equal(proof.onCreateTable,true);assert.equal(proof.upstreamCalls,0);assert.equal(proof.noServerListen,true);assert.equal(proof.configuredOldSpaceMiB,128);});
test('current package is self-contained; fresh isolated process constructs coexistence OFF and ON, retaining CURRENT guards without tools',t=>{
 const f=fixture(t);assert.equal(f.meta.runtimeFiles,29);assert.equal(f.meta.files,59);assert(f.meta.packBytes<=950000&&f.meta.seedMountsBytes<=960000);assert.equal(fs.existsSync(path.join(f.artifact.root,'tools')),false);for(const name of P.RUNTIME_FILES)assert.deepEqual(fs.readFileSync(path.join(f.artifact.runtimeDir,name)),fs.readFileSync(path.join(DIR,name)));
 const script=`'use strict';const assert=require('node:assert/strict'),path=require('node:path');const no=()=>{throw Error('NO_NETWORK');};require('node:net').Server.prototype.listen=no;for(const n of ['node:http','node:https']){const m=require(n);m.get=no;m.request=no;}globalThis.fetch=no;const dir=process.argv[1],S=require(path.join(dir,'server.cjs')),A=require(path.join(dir,'auth.cjs')),G=require(path.join(dir,'crm-individual-coexistence.cjs'));const base={dbPath:':memory:',managerHost:'gerencial.shrigma.com.br',areaHosts:{growth:'crm.shrigma.com.br',organico:'organico.shrigma.com.br',influs:'influs.shrigma.com.br'},allowedEmailDomains:['oaristocrata.com','shrigma.com.br','fishermans.com.br'],bootstrapAdminEmail:'felipebandeira@oaristocrata.com',bootstrapTokenSha256:'a'.repeat(64),encryptionKey:Buffer.alloc(32,3),crmCampaignWriterProfile:'own-master-production-v1',crmCampaignSubmitWrite:true};const u=n=>String(n).padStart(8,'0')+'-0000-4000-8000-000000000000';const on={...base,crmIndividualCoexistence:true,crmManagedRead:{issuerId:u(1),namespaceId:u(2),provisionerToken:'r'.repeat(43)},crmManagedWriter:{mode:'corporate-read-writer-v1',issuerId:u(3),namespaceId:u(4),provisionerToken:'w'.repeat(43)}};const P=require(path.join(dir,'proxy.cjs')),routes={'crm-read':P.FIXED_DESTINATIONS['crm-read'],campaigns:P.REVIEWED_DYNAMIC.routes.campaigns};for(const v of [base,on]){const auth=A.createAuth(S.authOptionsFor(v));try{const settings={...v,mode:'operational',upstreamProfile:'production',crmManagedReadUi:v.crmIndividualCoexistence===true,upstreams:routes,allowedUpstreamHosts:[...new Set(Object.values(routes).map(x=>new URL(x).hostname))],dynamicRouteManifest:{schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:routes.campaigns}}};const server=S.createServer(settings,{auth,...(v.crmIndividualCoexistence?{managedCrmRuntime:{kick:async()=>assert.fail('no startup'),close:async()=>{}}}:{}),fetchImpl:no});assert.equal(server.address(),null);assert.equal(Boolean(auth.managedCrmJournal),v.crmIndividualCoexistence===true);assert.equal(typeof auth.ownMasterPublishedJourneyReadBinding,'function');}finally{auth.close();}}assert.throws(()=>A.createAuth({...on,crmIndividualCoexistence:false}));(async()=>{let version=1;const transport=G.guardedTransport(async()=>{version++;return 'late';},()=>String(version));await assert.rejects(transport({}, {command:{brand:'fish'}}),e=>e.code==='CRM_CURRENT_BINDING_CHANGED');process.stdout.write(JSON.stringify({off:true,on:true,currentGuard:true,listeners:0,upstreamCalls:0}));})().catch(()=>process.exitCode=1);`;
 const cold=spawnSync(process.execPath,['--no-warnings','--max-old-space-size=128','-e',script,f.artifact.runtimeDir],{cwd:f.artifact.root,env:{},encoding:'utf8',timeout:15000});assert.equal(cold.status,0,cold.stderr);assert.deepEqual(JSON.parse(cold.stdout),{off:true,on:true,currentGuard:true,listeners:0,upstreamCalls:0});
});
test('reviewed CREATE slice still refuses READ-only identity and requires CURRENT FULL writer admission',async t=>{
 const f=await require('./corporate-writer-fixture.cjs').fixture(t),id=await f.manager(),ctx=await f.login(),creator=f.auth.campaignCreateFor(async()=>assert.fail('no transport'));
 assert.equal(f.auth.campaignWriterReady(ctx),false);
 const selector={brand:'fish',idempotency_key:'synthetic_unknown_attempt'};
 assert.throws(()=>creator.describe(ctx,selector),e=>e.code==='CAMPAIGN_CREATE_DENIED');
 const admitted=await f.issue(id);assert.equal(admitted.state,'ready');assert.equal(f.auth.campaignWriterReady(ctx),true);
 const proof=f.auth.campaignWriterAuthorization(ctx,{brand:'fish',action:'criar'});assert.equal(proof.canEdit,true);assert.deepEqual([...proof.caps],['read_content','draft','validate','submit']);
 assert.throws(()=>creator.describe(ctx,selector),e=>e.code==='CAMPAIGN_CREATE_UNKNOWN');
 f.auth.revokeUser({context:f.context,userId:id});assert.equal(f.auth.campaignWriterReady(ctx),false);assert.throws(()=>creator.describe(ctx,selector),e=>e.code==='CAMPAIGN_CREATE_DENIED');
});
