'use strict';
// Disposable SQLite, individual synthetic FULL proof and in-process HTTP only.
// The backend effect is an in-memory campaign provider; no socket or real SQL.
const test=require('node:test'),assert=require('node:assert/strict');
const {Readable}=require('node:stream'),{EventEmitter}=require('node:events');
const {fixture,hosts,CAPS}=require('./corporate-writer-fixture.cjs');
const {createOrigin,definition}=require('./dashboard-operational-campaign-create-fixture.cjs');
const S=require('../services/dashboard-operational/server.cjs'),P=require('../services/dashboard-operational/proxy.cjs');
const Backend=require('../services/crm-campaign/server.cjs');
const campaignUrl=P.REVIEWED_DYNAMIC.routes.campaigns,readUrl=P.FIXED_DESTINATIONS['crm-read'];
const q=(key='corporate_create_attempt_01',brand='fish')=>({acao:'campanha_criar',brand,definition:definition(brand),idempotency_key:key});
const route=q=>'/auth/campaign-create?brand='+q.brand+'&idempotency_key='+q.idempotency_key;
const manifest=()=>({schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:campaignUrl}});
function settings(f,on=false){return{...f.config,mode:'operational',upstreamProfile:'production',crmManagedReadUi:true,crmManagedWriter:{...f.config.crmManagedWriter,provisionerToken:'S'.repeat(43)},upstreams:{'crm-read':readUrl,campaigns:campaignUrl},allowedUpstreamHosts:[new URL(readUrl).hostname,new URL(campaignUrl).hostname],dynamicRouteManifest:manifest(),crmCorporateCreate:on};}
function env(f){const s=settings(f);return{DASHBOARD_MODE:'operational',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_MANAGER_HOST:f.config.managerHost,DASHBOARD_AREA_HOSTS:JSON.stringify(f.config.areaHosts),DASHBOARD_EMAIL_DOMAINS:'["oaristocrata.com"]',DASHBOARD_UPSTREAMS:JSON.stringify(s.upstreams),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify(s.allowedUpstreamHosts),DASHBOARD_DYNAMIC_ROUTE_MANIFEST:JSON.stringify(manifest()),DASHBOARD_CRM_MANAGED_READ:'enabled',DASHBOARD_CRM_MANAGED_READ_UI:'enabled',DASHBOARD_CRM_MANAGER_ISSUER_ID:f.config.crmManagedRead.issuerId,DASHBOARD_CRM_MANAGER_NAMESPACE_ID:f.config.crmManagedRead.namespaceId,DASHBOARD_CRM_MANAGER_PROVISIONER_TOKEN:'R'.repeat(43),DASHBOARD_CRM_MANAGED_WRITER:'enabled',DASHBOARD_CRM_WRITER_DESCRIPTOR:JSON.stringify(f.config.crmManagedWriter),DASHBOARD_CRM_WRITER_PROVISIONER_TOKEN:'S'.repeat(43),DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'enabled',DASHBOARD_ADMIN_EMAIL:f.config.bootstrapAdminEmail};}
function request(app,ctx,path,{method='GET',body,patch={}}={}){return new Promise(resolve=>{const req=Readable.from(body===undefined?[]:[Buffer.from(JSON.stringify(body))],{objectMode:false});Object.assign(req,{url:path,method,headers:{host:ctx.host,origin:ctx.origin,cookie:ctx.cookieHeader,'x-csrf-token':ctx.csrf,...(body===undefined?{}:{'content-type':'application/json'}),...patch},socket:{remoteAddress:'127.0.0.1'}});const res=new EventEmitter();res.setHeader=()=>{};res.end=bytes=>{res.emit('finish');resolve({status:res.statusCode,body:JSON.parse(String(bytes))});};app.emit('request',req,res);});}
async function setup(t,{issue=true}={}){
 const f=await fixture(t),id=await f.manager(),ctx=await f.login();if(issue)assert.deepEqual(await f.issue(id),{state:'ready'});
 const origin=createOrigin(()=>f.now),calls=[];let behavior=null;
 const fetchImpl=async(url,options)=>{
  const u=new URL(url);assert.equal(u.origin+u.pathname,campaignUrl);assert.equal(options.redirect,'manual');assert.equal(options.cache,'no-store');assert.equal(options.headers.Cookie,undefined);assert.equal(options.headers.Origin,undefined);
  const parsed=Backend.parse({method:options.method,headers:Object.fromEntries(Object.entries(options.headers).map(([k,v])=>[k.toLowerCase(),v])),rawHeaders:Object.entries(options.headers).flat()},u,options.method==='POST'?JSON.parse(options.body):undefined);
  const bearer=parsed.key,slot=f.db.prepare("SELECT c.user_id,c.encrypted_key,b.principal_id FROM upstream_credentials c JOIN crm_writer_auth_binding_v1 b ON c.user_id=b.user_id WHERE c.slot='growth-campaign' AND c.key_digest=?").get(f.digest(bearer));assert.ok(slot,'only the individual WRITER slot is accepted');assert.equal(f.decrypt(slot.encrypted_key),bearer);
  const reader=f.db.prepare("SELECT encrypted_key FROM upstream_credentials WHERE user_id=? AND slot='crm-panel-read'").get(slot.user_id);if(reader)assert.notEqual(f.decrypt(reader.encrypted_key),bearer);
  const payload=parsed.command;assert.equal(Object.hasOwn(payload,'k'),false);if(options.method==='POST'){assert.equal(options.headers.Authorization,undefined);assert.equal(JSON.parse(options.body).k,bearer);}else assert.equal(options.headers.Authorization,'Bearer '+bearer);
  calls.push({method:options.method,action:payload.acao,brand:payload.brand,key:payload.idempotency_key,actor:'panel:'+slot.principal_id});
  if(options.method==='POST'){const row=f.db.prepare('SELECT * FROM crm_campaign_create_v1 WHERE remote_key=?').get(payload.idempotency_key);assert.ok(row);assert.equal(f.db.isTransaction,false);assert.equal(row.phase,'uncertain');assert.match(row.input_ciphertext,/^v1\./);assert.match(row.catalog_ciphertext,/^v1\./);assert.match(row.normalized_ciphertext,/^v1\./);assert.equal(row.campaign_id,null);assert.notEqual(row.client_key,row.remote_key);assert.equal(payload.acao,'campanha_salvar');assert.equal(payload.definition.send_at,null);assert.equal(Object.hasOwn(payload,'id'),false);assert.equal(Object.hasOwn(payload,'expected_version'),false);}
  const dispatch=()=>origin.service.handle({actor:'panel:'+slot.principal_id,caps:[...CAPS]},payload);const out=behavior?await behavior({payload,options,dispatch}):await dispatch();return new Response(JSON.stringify(out.body),{status:out.status,headers:{'content-type':'application/json'}});
 };
 const make=on=>{const app=S.createServer(settings(f,on),{auth:f.auth,fetchImpl,managedCrmRuntime:{kick:async()=>{},close:async()=>{}}});t.after(()=>app.removeAllListeners());assert.equal(app.listening,false);return app;};
 return{f,id,ctx,origin,calls,fetchImpl,make,setBehavior:v=>{behavior=v;},post:(app,command,context=ctx)=>request(app,context,'/auth/campaign-create',{method:'POST',body:command}),get:(app,command,context=ctx)=>request(app,context,route(command)),count:()=>f.db.prepare('SELECT count(*) n FROM crm_campaign_create_v1').get().n};
}

test('corporate CREATE gate defaults OFF, rejects malformed/unbranded activation and advertises OFF/ON only with ready FULL',async t=>{
 const legacy={DASHBOARD_MODE:'synthetic',DASHBOARD_MANAGER_HOST:'gerencial.synthetic.invalid',DASHBOARD_AREA_HOSTS:JSON.stringify({growth:'crm.synthetic.invalid',organico:'organico.synthetic.invalid',influs:'influs.synthetic.invalid'}),DASHBOARD_EMAIL_DOMAINS:'[\"synthetic.invalid\"]'};const legacyOff=S.settingsFromEnv(legacy);assert.equal(legacyOff.crmCorporateCreate,false);assert.deepEqual(S.settingsFromEnv({...legacy,DASHBOARD_CRM_CORPORATE_CREATE:'disabled'}),legacyOff);assert.throws(()=>S.settingsFromEnv({...legacy,DASHBOARD_CRM_CORPORATE_CREATE:'enabled'}),/Corporate campaign create gate invalid/);
 const a=await setup(t),v=env(a.f);assert.equal(S.settingsFromEnv(v).crmCorporateCreate,false);assert.equal(S.settingsFromEnv({...v,DASHBOARD_CRM_CORPORATE_CREATE:'enabled'}).crmCorporateCreate,true);for(const bad of ['true','on','false','ENABLED'])assert.throws(()=>S.settingsFromEnv({...v,DASHBOARD_CRM_CORPORATE_CREATE:bad}));
 assert.throws(()=>S.settingsFromEnv({...v,DASHBOARD_CRM_MANAGED_WRITER:'disabled',DASHBOARD_CRM_CORPORATE_CREATE:'enabled'}));assert.throws(()=>S.createServer({...settings(a.f,true),crmCorporateCreate:'enabled'},{auth:a.f.auth}));assert.throws(()=>S.createServer({...settings(a.f,true),crmManagedWriter:undefined},{auth:a.f.auth}));
 const off=a.make(false),on=a.make(true);assert.equal((await a.post(off,q())).status,403);assert.equal(a.count(),0);assert.equal(a.calls.length,0);const before=await request(off,a.ctx,'/auth/session'),after=await request(on,a.ctx,'/auth/session');assert.equal(before.body.features.campaignSubmitWrite,true);assert.equal(before.body.features.campaignCreate,false);assert.equal(after.body.features.campaignCreate,true);
});

test('corporate FULL CREATE commits encrypted intent before its only POST and binds receipt ID without scheduling either brand',async t=>{
 const a=await setup(t),app=a.make(true),master=a.f.masterBaseline(),reader=a.f.db.prepare("SELECT * FROM upstream_credentials WHERE user_id=? AND slot='crm-panel-read'").get(a.id);
 for(const [brand,key] of [['fish','corporate_fish_create_01'],['aristo','corporate_aristo_create_01']]){const reply=await a.post(app,q(key,brand));assert.equal(reply.status,200);assert.equal(reply.body.state,'succeeded');assert.equal(reply.body.campaign.status,'draft');assert.equal(reply.body.campaign.sendAt,null);assert.equal(reply.body.campaign.sent,0);const saved=a.f.db.prepare('SELECT * FROM crm_campaign_create_v1 WHERE user_id=? AND client_key=?').get(a.id,key);assert.equal(saved.phase,'succeeded');assert.equal(saved.campaign_id,reply.body.campaign.id);assert.equal(JSON.stringify(reply).includes(saved.remote_key),false);assert.equal(JSON.stringify(reply).includes('Synthetic HTML canary'),false);}
 assert.equal(a.origin.effects.create,2);assert.equal(a.origin.effects.schedule,0);assert.equal(a.calls.filter(v=>v.method==='POST').length,2);assert.deepEqual(a.f.masterBaseline(),master);assert.deepEqual(a.f.db.prepare("SELECT * FROM upstream_credentials WHERE user_id=? AND slot='crm-panel-read'").get(a.id),reader);assert.equal(a.f.events.filter(v=>v==='FULL_ATTEST').length,1);
});

test('lost CREATE ACK restarts through GET of the same actor, brand and remote key; gate OFF never repeats POST',async t=>{
 const a=await setup(t),command=q(),on=a.make(true);a.setBehavior(async({options,dispatch})=>{const r=await dispatch();if(options.method==='POST')throw Error('SYNTHETIC_LOST_ACK');return r;});assert.equal((await a.post(on,command)).status,202);const prior=a.f.db.prepare('SELECT * FROM crm_campaign_create_v1').get();assert.equal(prior.phase,'uncertain');assert.equal(prior.campaign_id,null);assert.equal(a.origin.effects.create,1);a.f.restart();a.setBehavior(null);const off=a.make(false),out=await a.get(off,command);assert.equal(out.status,200);assert.equal(out.body.campaign.id,1001);assert.equal((await a.post(off,command)).status,403);assert.equal(a.calls.filter(v=>v.method==='POST').length,1);assert.equal(a.calls.filter(v=>v.action==='campanha_operacao').every(v=>v.key===prior.remote_key&&v.actor===a.calls[0].actor&&v.brand===prior.brand),true);assert.equal(a.f.db.prepare('SELECT remote_key FROM crm_campaign_create_v1').get().remote_key,prior.remote_key);
});

test('lost request and repeated 404 retain CREATE pending, block a new key/UPDATE and isolate another actor and brand',async t=>{
 const a=await setup(t),command=q(),app=a.make(true);const otherId=await a.f.manager('other@oaristocrata.com');assert.deepEqual(await a.f.issue(otherId),{state:'ready'});const other=await a.f.login('other@oaristocrata.com');a.setBehavior(({options,dispatch})=>options.method==='POST'?Promise.reject(Error('SYNTHETIC_LOST_REQUEST')):dispatch());assert.equal((await a.post(app,command)).status,202);const prior=a.f.db.prepare('SELECT * FROM crm_campaign_create_v1').get();a.f.restart();a.setBehavior(null);const re=a.make(true);for(let i=0;i<2;i++)assert.equal((await a.get(re,command)).status,202);assert.equal((await a.post(re,command)).status,202);assert.equal((await a.post(re,q('corporate_next_attempt_02'))).status,409);assert.equal(a.calls.filter(v=>v.method==='POST').length,1);assert.equal(a.origin.effects.create,0);assert.equal(a.f.db.prepare('SELECT phase,remote_key FROM crm_campaign_create_v1').get().remote_key,prior.remote_key);
 const changed=q();changed.definition.subject='Changed payload';assert.equal((await a.post(re,changed)).status,409);assert.equal((await a.get(re,{...command,brand:'aristo'})).status,404);
 assert.equal((await a.get(re,command,other)).status,404);assert.equal((await a.post(re,command,other)).status,200);assert.equal((await a.post(re,q('corporate_aristo_attempt_02','aristo'))).status,200);assert.equal(a.origin.effects.create,2);assert.equal(a.origin.effects.schedule,0);
 assert.throws(()=>a.f.auth.campaignWriterAuthorization(a.ctx,{brand:'fish',action:'salvar'}),e=>e.code==='CAMPAIGN_CREATE_PENDING');
});

test('READ-only, unpromoted/tampered FULL, master, foreign Origin/CSRF and malformed bodies create no effect or shared-key fallback',async t=>{
 const a=await setup(t,{issue:false}),app=a.make(true);assert.equal((await request(app,a.ctx,'/auth/session')).body.features.campaignCreate,false);assert.equal((await a.post(app,q())).status,403);a.f.approval(a.id);assert.equal((await a.post(app,q())).status,403);assert.equal(a.calls.length,0);assert.deepEqual(await a.f.coordinator.run(a.f.operation(a.id)),{state:'ready'});
 for(const ctx of [a.f.context,{...a.ctx,csrf:'forged'},{...a.ctx,origin:'https://foreign.shrigma.com.br'},{...a.ctx,host:hosts.organico}])assert.ok([401,403].includes((await a.post(app,q(),ctx)).status));
 for(const bad of [{...q(),id:167},{...q(),expected_version:'a'.repeat(32)},{...q(),k:'synthetic-shared-key'},{...q(),definition:{...definition(),send_at:new Date(a.f.now+3600000).toISOString()}}])assert.equal((await a.post(app,bad)).status,400);assert.equal(a.calls.length,0);assert.equal(a.count(),0);
 a.f.db.prepare("UPDATE crm_writer_bridge_op_v1 SET committed_mac=? WHERE kind='issue'").run('f'.repeat(64));assert.equal((await request(app,a.ctx,'/auth/session')).body.features.campaignCreate,false);assert.equal((await a.post(app,q())).status,403);assert.equal(a.calls.length,0);assert.equal(a.count(),0);
});

test('READ loss after CREATE effect suppresses POST ACK; the same unrotated WRITER recovers by GET and no new CREATE is admitted',async t=>{
 const a=await setup(t),app=a.make(true),command=q();a.setBehavior(async({options,dispatch})=>{const r=await dispatch();if(options.method==='POST')a.f.db.prepare("DELETE FROM upstream_credentials WHERE user_id=? AND slot='crm-panel-read'").run(a.id);return r;});assert.equal((await a.post(app,command)).status,403);assert.equal(a.origin.effects.create,1);assert.equal(a.f.db.prepare('SELECT phase FROM crm_campaign_create_v1').get().phase,'uncertain');a.setBehavior(null);assert.equal((await a.get(app,command)).status,200);assert.equal((await a.post(app,q('corporate_readlost_new_02'))).status,403);assert.equal(a.calls.filter(v=>v.method==='POST').length,1);assert.equal(a.f.auth.managedCampaignWriterJournal.pending().length,0);
});

test('disable/expiry preserve CREATE evidence and deny further transport; no automatic TTL release or credential reuse',async t=>{
 for(const mode of ['disable','expiry']){const a=await setup(t),app=a.make(true);a.setBehavior(({options,dispatch})=>options.method==='POST'?Promise.reject(Error('SYNTHETIC_UNKNOWN')):dispatch());assert.equal((await a.post(app,q())).status,202);const prior=a.f.db.prepare('SELECT * FROM crm_campaign_create_v1').get(),calls=a.calls.length;
  if(mode==='disable')a.f.auth.revokeUser({context:a.f.context,userId:a.id});else{a.f.advance(1209600001);a.ctx=await a.f.login();}
  assert.ok([401,403].includes((await a.get(app,q(),a.ctx)).status));assert.ok([401,403].includes((await a.post(app,q('corporate_expired_next_02'),a.ctx)).status));assert.equal(a.calls.length,calls);assert.deepEqual(a.f.db.prepare('SELECT * FROM crm_campaign_create_v1').get(),prior);assert.equal(a.origin.effects.create,0);
 }
});
