'use strict';
// Actual compiled portal + real Auth/SQLite + real same-origin HTTP handlers.
// Synthetic identities only. Failure injection is at the browser transport,
// after a genuine mutation reply; no upstream, broker, activation or socket.
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite'),{createAuth}=require('../services/dashboard-operational/auth.cjs');
const S=require('../services/dashboard-operational/server.cjs'),P=require('../services/dashboard-operational/proxy.cjs');
const {transport,shell,until}=require('./helpers/claude-portal-pages.cjs');
const hosts={manager:'gerencial.shrigma.com.br',growth:'crm.shrigma.com.br',organico:'organico.shrigma.com.br',influs:'influs.shrigma.com.br'},owner='felipebandeira@oaristocrata.com',password='Synthetic account confirmation password 2026!';
async function setup(t,{member=true,legacy=false,loseAck=null,hold=null,holdList=null}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'account-confirmation-')),dbPath=path.join(dir,'identity.sqlite'),encryptionKey=crypto.randomBytes(32);
 const config={dbPath,encryptionKey,managerHost:hosts.manager,areaHosts:{growth:hosts.growth,organico:hosts.organico,influs:hosts.influs},allowedEmailDomains:['oaristocrata.com','shrigma.com.br','fishermans.com.br'],bootstrapAdminEmail:owner,bootstrapTokenSha256:crypto.createHash('sha256').update('synthetic-bootstrap').digest('hex'),now:()=>1791000000000,crmCampaignSubmitWrite:true,crmCampaignWriterProfile:'own-master-production-v1'};
 const auth=createAuth(config);await auth.completeBootstrap({email:owner,token:'synthetic-bootstrap',password,host:hosts.manager,origin:'https://'+hosts.manager});
 const login=await auth.login({email:owner,password,host:hosts.manager,origin:'https://'+hosts.manager}),context={host:hosts.manager,method:'POST',origin:'https://'+hosts.manager,cookieHeader:login.cookie.split(';')[0],csrf:login.csrf},db=new DatabaseSync(dbPath),masterId=auth.session(context).user.id;
 let id=null;if(member){const invite=auth.createInvite({context,email:'member@fishermans.com.br',areas:['growth'],brand:'fish',requestedAccess:'read'});id=invite.userId;await auth.acceptInvite({token:invite.token,password,host:hosts.growth,origin:'https://'+hosts.growth});}
 const read=P.FIXED_DESTINATIONS['crm-read'],campaign=P.REVIEWED_DYNAMIC.routes.campaigns,settings={...config,mode:'operational',upstreamProfile:'production',upstreams:{'crm-read':read,campaigns:campaign},allowedUpstreamHosts:[new URL(read).hostname,new URL(campaign).hostname],dynamicRouteManifest:{schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:campaign}}};
 let upstreamCalls=0;const app=S.createServer(settings,{auth,fetchImpl:()=>{upstreamCalls++;throw Error('NO_UPSTREAM');}}),http=transport(app),values=new Map([['synthetic-campaign-journal','unchanged uncertain draft']]);let failList=false;
 const browser={post:async(...args)=>{const reply=await http.post(...args);if(hold)await hold(args[2],reply);return reply;},get:async(host,p,ctx)=>{if(p==='/auth/users'&&failList)return{status:503,headers:{},text:'{"error":"SYNTHETIC_LIST_UNAVAILABLE"}',json:{error:'SYNTHETIC_LIST_UNAVAILABLE'}};const reply=await http.get(host,p,ctx);if(p==='/auth/users'&&holdList)await holdList(reply);
 // Declared legacy DTO compatibility projection; server identity/grants remain real.
 if(legacy&&p==='/auth/users'&&reply.status===200){const json=JSON.parse(JSON.stringify(reply.json));for(const u of Array.isArray(json)?json:json.users)delete u.profileRevision;return{...reply,json,text:JSON.stringify(json)};}return reply;}};
 const ui=shell(browser,{host:hosts.manager,area:'gestao',cookie:context.cookieHeader,confirm:()=>true,values,loseAck});await ui.ready();await until(()=>!ui.el('entry-shell').hidden,'Master session');ui.el('entry-manage').click();await until(()=>ui.document.querySelector('.user-row'),'real account list');
 const baseline=()=>({user:db.prepare('SELECT * FROM users WHERE id=?').get(masterId),grants:db.prepare('SELECT * FROM grants WHERE user_id=? ORDER BY area').all(masterId),sessions:db.prepare('SELECT * FROM sessions WHERE user_id=? ORDER BY token_hash').all(masterId)}),before=baseline();
 t.after(()=>{app.removeAllListeners();auth.close();db.close();fs.rmSync(dir,{recursive:true,force:true});encryptionKey.fill(0);});
 return{ui,auth,db,id,context,baseline,before,values,get upstreamCalls(){return upstreamCalls;},set failList(v){failList=v;}};
}
const posts=(a,action)=>a.ui.calls.filter(c=>c.method==='POST'&&c.body?.action===action);
const profile=a=>a.ui.document.querySelector('[data-user-profile="'+a.id+'"]');
const field=(form,name)=>form.querySelector('[data-profile-field="'+name+'"]');
const row=a=>[...a.ui.document.querySelectorAll('.user-row')].find(r=>r.textContent.includes('member@fishermans.com.br'));
const revoke=a=>[...row(a).querySelectorAll('button')].find(b=>b.textContent==='Revogar acesso');
const submit=(a,form)=>form.dispatchEvent(new a.ui.window.Event('submit',{cancelable:true}));
function preserved(a){assert.deepEqual(a.baseline(),a.before);assert.deepEqual([...a.values],[['synthetic-campaign-journal','unchanged uncertain draft']]);assert.equal(a.upstreamCalls,0);assert.equal(a.auth.managedCrmJournal,undefined);assert.equal(a.auth.managedCampaignWriterJournal,undefined);}

test('confirmed invitation keeps its host-checked link when the subsequent account read fails; retry only reads',async t=>{
 const a=await setup(t,{member:false}),u=a.ui;a.failList=true;u.input('admin-email','analyst@fishermans.com.br');u.select('admin-brand','aristo');u.select('admin-access','edit');await u.submit('admin-invite-form');await u.submit('admin-invite-form');
 await until(()=>posts(a,'invite').length===1&&u.el('admin-invite-form').getAttribute('aria-busy')==='false','completed invitation handler');assert.match(u.el('admin-message').textContent,/link recebido continua disponível/);assert.equal(posts(a,'invite').length,1);assert.equal(posts(a,'invite')[0].status,201);assert.equal(u.el('admin-invite-result').hidden,false);const link=u.el('admin-invite-link').value;assert.match(link,/^https:\/\/crm\.shrigma\.com\.br\/#invite=/);assert.match(u.el('admin-message').textContent,/Convite criado.*Solicitação de Edição registrada; acesso individual ainda não habilitado/);assert.doesNotMatch(u.el('admin-message').textContent,/Não foi possível criar|Edição ativa/);assert.equal(u.document.querySelector('.user-row'),null);
 const actual=a.auth.users({context:a.context}).find(x=>x.email==='analyst@fishermans.com.br');assert.equal(actual.status,'invited');assert.equal(actual.brand,'aristo');assert.equal(actual.requestedAccess,'edit');assert.equal(actual.permissions.growth.edit,false);
 a.failList=false;u.el('admin-users-refresh').click();await until(()=>u.el('admin-message').textContent.startsWith('Lista de acessos atualizada'),'read-only refresh');assert.equal(posts(a,'invite').length,1);assert.equal(u.el('admin-invite-link').value,link);preserved(a);
});

test('confirmed portal revocation survives a failed list read and removes stale editable rows without claiming CRM revocation',async t=>{
 const a=await setup(t);a.failList=true;revoke(a).click();await until(()=>a.ui.el('admin-message').textContent.startsWith('Acesso ao portal revogado.'),'confirmed revoke');assert.equal(posts(a,'revoke').length,1);assert.equal(posts(a,'revoke')[0].status,200);assert.equal(a.db.prepare('SELECT state FROM users WHERE id=?').get(a.id).state,'disabled');assert.equal(a.ui.document.querySelector('.user-row'),null);assert.match(a.ui.el('admin-users').textContent,/lista de acessos está indisponível/);assert.doesNotMatch(a.ui.el('admin-message').textContent,/Não foi possível revogar|portal e ao CRM revogado/);assert.match(a.ui.confirms[0],/Chaves individuais.*revogação separada/);
 a.failList=false;a.ui.el('admin-users-refresh').click();await until(()=>a.ui.el('admin-message').textContent.startsWith('Lista de acessos atualizada'),'fresh disabled row');assert.match(row(a).textContent,/Revogado/);assert.equal([...row(a).querySelectorAll('button')].some(b=>b.textContent==='Revogar acesso'),false);assert.equal(posts(a,'revoke').length,1);preserved(a);
});

test('lost revocation ACK reconciles the genuinely disabled identity by GET and never replays the mutation',async t=>{
 const a=await setup(t,{loseAck:(method,body)=>method==='POST'&&body?.action==='revoke'});revoke(a).click();await until(()=>a.ui.el('admin-message').textContent.includes('nenhuma revogação foi reenviada'),'lost revoke ACK');assert.equal(posts(a,'revoke').length,1);assert.equal(posts(a,'revoke')[0].status,200);assert.equal(a.db.prepare('SELECT state FROM users WHERE id=?').get(a.id).state,'disabled');assert.match(row(a).textContent,/Revogado/);assert.match(a.ui.el('admin-message').textContent,/resposta da revogação não foi confirmada/);assert.doesNotMatch(a.ui.el('admin-message').textContent,/Não foi possível revogar|CRM revogado/);preserved(a);
});

test('confirmed access-only profile update retains its intent result and password when the following read fails',async t=>{
 const a=await setup(t),before=a.db.prepare('SELECT password_hash FROM users WHERE id=?').get(a.id).password_hash,form=profile(a);a.failList=true;field(form,'access').value='edit';submit(a,form);submit(a,form);await until(()=>a.ui.el('admin-message').textContent.startsWith('Solicitação de Edição registrada'),'confirmed profile');assert.equal(posts(a,'update').length,1);assert.equal(posts(a,'update')[0].status,200);assert.match(a.ui.el('admin-message').textContent,/acesso individual ainda não habilitado.*senha foi preservada.*lista de acessos ainda não pôde/);assert.equal(a.db.prepare('SELECT password_hash FROM users WHERE id=?').get(a.id).password_hash,before);const user=a.auth.users({context:a.context}).find(x=>x.id===a.id);assert.equal(user.requestedAccess,'edit');assert.equal(user.permissions.growth.edit,false);assert.equal(a.ui.document.querySelector('.user-row'),null);preserved(a);
});

test('confirmed profile-finish preserves the same safe new invitation even if account refresh fails',async t=>{
 const a=await setup(t),form=profile(a);field(form,'email').value='updated@fishermans.com.br';field(form,'brand').value='aristo';submit(a,form);await until(()=>a.ui.document.querySelector('[data-user-action="update-finish"]'),'real replacement invitation');const user=a.auth.users({context:a.context}).find(x=>x.id===a.id);assert.equal(user.email,'updated@fishermans.com.br');assert.equal(user.brand,'aristo');a.failList=true;a.ui.document.querySelector('[data-user-action="update-finish"]').click();await until(()=>a.ui.el('admin-message').textContent.startsWith('Cadastro atualizado.'),'confirmed profile finish');assert.equal(posts(a,'update_finish').length,1);assert.equal(posts(a,'update_finish')[0].status,200);assert.equal(a.ui.el('admin-invite-result').hidden,false);const link=a.ui.el('admin-invite-link').value;assert.match(link,/^https:\/\/crm\.shrigma\.com\.br\/#invite=/);assert.match(a.ui.el('admin-message').textContent,/link recebido continua disponível/);assert.doesNotMatch(a.ui.el('admin-message').textContent,/resposta do convite não foi confirmada/);assert.equal(a.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(a.id).n,1);assert.equal(posts(a,'update').length,1);preserved(a);
});

test('legacy access-request handler keeps its confirmed intent on a failed read without asserting an unavailable broker',async t=>{
 const a=await setup(t,{legacy:true}),actions=row(a).querySelector('.user-row-actions'),select=actions.querySelector('select'),save=[...actions.querySelectorAll('button')].find(b=>b.textContent==='Salvar');select.value='edit';select.dispatchEvent(new a.ui.window.Event('change'));a.failList=true;save.click();save.click();await until(()=>a.ui.el('admin-message').textContent.startsWith('Solicitação de Edição registrada'),'legacy confirmed access');assert.equal(posts(a,'access_request').length,1);assert.equal(posts(a,'access_request')[0].status,200);assert.match(a.ui.el('admin-message').textContent,/acesso individual ainda não habilitado.*lista de acessos ainda não pôde/);assert.equal(a.auth.users({context:a.context}).find(x=>x.id===a.id).requestedAccess,'edit');assert.equal(a.ui.document.querySelector('.user-row'),null);preserved(a);
});

test('confirmed invitation arriving after logout cannot reappear in the old session or refresh its account list',async t=>{
 let release,held=false;const wait=new Promise(r=>{release=r;});const a=await setup(t,{member:false,hold:async(body,reply)=>{if(body?.action==='invite'&&reply.status===201){held=true;await wait;}}}),u=a.ui;u.input('admin-email','later@fishermans.com.br');u.select('admin-brand','fish');await u.submit('admin-invite-form');await until(()=>held,'genuine POST committed before delayed ACK');const listReads=u.calls.filter(c=>c.path==='/auth/users'&&c.method==='GET').length;u.el('entry-logout').click();await until(()=>!u.el('entry-login').hidden,'real logout');release();await until(()=>posts(a,'invite').length===1,'delayed reply');await new Promise(r=>setTimeout(r,15));assert.equal(u.el('admin-invite-result').hidden,true);assert.equal(u.el('admin-invite-link').value,'');assert.equal(u.document.querySelector('.user-row'),null);assert.equal(u.calls.filter(c=>c.path==='/auth/users'&&c.method==='GET').length,listReads);assert.equal(a.db.prepare('SELECT count(*) n FROM users WHERE email=?').get('later@fishermans.com.br').n,1);assert.equal(a.upstreamCalls,0);
});

test('a delayed profile-finish account read cannot restore the old session link or rows after logout',async t=>{
 let release,armed=false,held=false;const wait=new Promise(r=>{release=r;});const a=await setup(t,{holdList:async()=>{if(armed){held=true;await wait;}}}),u=a.ui,form=profile(a);field(form,'email').value='updated@fishermans.com.br';submit(a,form);await until(()=>u.document.querySelector('[data-user-action="update-finish"]'),'replacement invitation');armed=true;u.document.querySelector('[data-user-action="update-finish"]').click();await until(()=>held&&!u.el('admin-invite-result').hidden,'confirmed link awaiting list read');u.el('entry-logout').click();await until(()=>!u.el('entry-login').hidden,'logout during list read');release();await new Promise(r=>setTimeout(r,15));assert.equal(posts(a,'update_finish').length,1);assert.equal(posts(a,'update_finish')[0].status,200);assert.equal(u.el('admin-invite-result').hidden,true);assert.equal(u.el('admin-invite-link').value,'');assert.equal(u.document.querySelector('.user-row'),null);assert.equal(a.upstreamCalls,0);
});
