'use strict';
// Real Master login/CSRF, disposable SQLite, original READ/WRITER journals.
// Synthetic issuer receipts only; no network socket, provider, send or email.
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture,hosts,pending}=require('./corporate-writer-fixture.cjs');
const {transport}=require('./helpers/claude-portal-pages.cjs');
const S=require('../services/dashboard-operational/server.cjs'),P=require('../services/dashboard-operational/proxy.cjs');
const row=(f,id)=>f.auth.users({context:f.context}).find(u=>u.id===id);
function app(t,f){const read=P.FIXED_DESTINATIONS['crm-read'],campaign=P.REVIEWED_DYNAMIC.routes.campaigns;const server=S.createServer({...f.config,mode:'operational',upstreamProfile:'production',crmManagedReadUi:true,crmManagedWriter:{...f.config.crmManagedWriter,provisionerToken:'S'.repeat(43)},upstreams:{'crm-read':read,campaigns:campaign},allowedUpstreamHosts:[new URL(read).hostname,new URL(campaign).hostname],dynamicRouteManifest:{schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:campaign}},crmCorporateCreate:true},{auth:f.auth,managedCrmRuntime:{kick:async()=>{},close:async()=>{}},fetchImpl:()=>{throw Error('NO_UPSTREAM');}});t.after(()=>server.removeAllListeners());return transport(server);}
const fields=(f,id,delta={})=>{const u=row(f,id);return {action:'update',userId:id,expectedRevision:u.profileRevision,email:u.email,area:u.areas[0],brand:u.brand,access:u.requestedAccess,...delta};};
const post=(http,f,body,ctx=f.context)=>http.post(ctx.host,'/auth/users',body,{cookie:ctx.cookieHeader,csrf:ctx.csrf,origin:ctx.origin});
const complete=(http,f,id)=>post(http,f,{action:'update_finish',userId:id,expectedRevision:row(f,id).profileRevision});
const snapshot=(f,id)=>JSON.stringify({u:f.db.prepare('SELECT * FROM users WHERE id=?').get(id),g:f.db.prepare('SELECT * FROM grants WHERE user_id=?').all(id),b:f.db.prepare('SELECT * FROM user_brand_grants_v1 WHERE user_id=?').get(id),i:f.db.prepare('SELECT * FROM invites WHERE user_id=?').all(id),q:f.db.prepare('SELECT * FROM user_profile_updates_v1 WHERE user_id=?').get(id)});

test('permission-only choice is effective Master intent with original password, session and identity; READ-to-WRITER uses signed authorization',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f),ctx=await f.login();
 const before=f.db.prepare('SELECT password_hash FROM users WHERE id=?').get(id).password_hash,scope=f.db.prepare('SELECT * FROM user_brand_grants_v1 WHERE user_id=?').get(id);
 const r=await post(http,f,fields(f,id,{access:'edit'}));assert.equal(r.status,200);assert.equal(r.json.state,'configured');assert.equal(f.auth.fulfillManagedCampaignWriterRequests().queued,1);
 const op=f.operation(id);assert.ok(op);assert.deepEqual(await f.coordinator.run(op),{state:'ready'});assert.equal(row(f,id).permissions.growth.edit,true);assert.equal(f.auth.session(ctx).authenticated,true);assert.equal(f.db.prepare('SELECT password_hash FROM users WHERE id=?').get(id).password_hash,before);assert.deepEqual(f.db.prepare('SELECT * FROM user_brand_grants_v1 WHERE user_id=?').get(id),scope);assert.equal(f.db.prepare('SELECT count(*) n FROM user_profile_updates_v1').get().n,0);
 const r2=await post(http,f,fields(f,id,{access:'read'}));assert.equal(r2.status,200);assert.equal(row(f,id).permissions.growth.edit,false);assert.equal(f.auth.session(ctx).authenticated,false);assert.equal(f.db.prepare('SELECT password_hash FROM users WHERE id=?').get(id).password_hash,before);assert.equal(f.auth.fulfillManagedCampaignWriterRequests().queued,0);assert.equal(f.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(id).n,0);
});

test('changing active WRITER owner and brand blocks old session immediately, waits for both real journal revocations and rotates lifecycles before new invitation',async t=>{
 const f=await fixture(t),id=await f.manager();await f.issue(id);const http=app(t,f),ctx=await f.login();
 const oldRead=f.auth.managedCrmJournal.readBinding(id),oldWriter=f.db.prepare('SELECT * FROM crm_writer_auth_admission_v1 WHERE user_id=?').get(id),oldKey=f.db.prepare("SELECT key_digest FROM upstream_credentials WHERE user_id=? AND slot='growth-campaign'").get(id).key_digest;
 const body=fields(f,id,{email:'new@fishermans.com.br',brand:'aristo',access:'edit'});const first=await post(http,f,body);assert.equal(first.status,202);assert.equal(first.json.state,'revoking');assert.equal(f.auth.session(ctx).authenticated,false);assert.equal(row(f,id).email,'manager@oaristocrata.com');assert.equal(row(f,id).brand,'fish');assert.equal(row(f,id).status,'disabled');assert.equal(row(f,id).permissions.growth.edit,false);
 assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:1});assert.equal((await complete(http,f,id)).status,409);
 const revoke=f.db.prepare("SELECT o.operation_id FROM crm_writer_bridge_op_v1 o JOIN crm_writer_bridge_life_v1 l USING(lifecycle_id) WHERE l.user_id=? AND o.kind='revoke'").get(id).operation_id;
 f.confirmReadRevoke(id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:1});assert.deepEqual(await f.coordinator.run(revoke),{state:'revoked'});
 assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:1,pending:0});const u=row(f,id);assert.equal(u.email,'new@fishermans.com.br');assert.equal(u.brand,'aristo');assert.equal(u.status,'invited');assert.equal(u.permissions.growth.edit,false);assert.equal(u.profileUpdate.inviteAvailable,true);
 const read=f.db.prepare('SELECT * FROM crm_manager_current_v1 WHERE user_id=?').get(id),writer=f.db.prepare('SELECT * FROM crm_writer_auth_admission_v1 WHERE user_id=?').get(id);assert.notEqual(read.lifecycle_id,oldRead.lifecycleId);assert.notEqual(writer.lifecycle_id,oldWriter.lifecycle_id);assert.equal(f.db.prepare('SELECT state FROM crm_manager_lifecycles_v1 WHERE lifecycle_id=?').get(oldRead.lifecycleId).state,'revoked');assert.equal(f.db.prepare('SELECT state FROM crm_writer_bridge_life_v1 WHERE lifecycle_id=?').get(oldWriter.lifecycle_id).state,'revoked');assert.equal(f.db.prepare('SELECT count(*) n FROM upstream_credentials WHERE user_id=?').get(id).n,0);
 const link=await complete(http,f,id);assert.equal(link.status,200);assert.match(link.json.inviteUrl,/^https:\/\/crm\.shrigma\.com\.br\/#invite=/);const token=new URL(link.json.inviteUrl).hash.slice(8);await f.accept({token,host:hosts.growth});f.promoteRead(id);assert.equal(f.auth.fulfillManagedCampaignWriterRequests().queued,1);assert.deepEqual(await f.coordinator.run(f.operation(id)),{state:'ready'});const current=f.db.prepare("SELECT key_digest FROM upstream_credentials WHERE user_id=? AND slot='growth-campaign'").get(id);assert.notEqual(current.key_digest,oldKey);const q=JSON.parse(f.db.prepare("SELECT request_json FROM crm_writer_bridge_op_v1 WHERE operation_id=?").get(f.operation(id)).request_json);assert.equal(q.owner,'new@fishermans.com.br');assert.equal(q.brand,'aristo');
});

test('lost update ACK/restart reuses the same sealed intention and recovered new invitation token without repeated revocation or grant',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f),body=fields(f,id,{area:'organico',brand:'aristo',access:'read'});
 assert.equal((await post(http,f,body)).status,202);const saved=f.db.prepare('SELECT * FROM user_profile_updates_v1 WHERE user_id=?').get(id),count=f.db.prepare("SELECT count(*) n FROM crm_manager_operations_v1 WHERE kind='revoke'").get().n;
 f.restart();const next=app(t,f);assert.equal((await post(next,f,body)).status,202);assert.equal(f.db.prepare("SELECT count(*) n FROM crm_manager_operations_v1 WHERE kind='revoke'").get().n,count);assert.equal(f.db.prepare('SELECT request_mac FROM user_profile_updates_v1 WHERE user_id=?').get(id).request_mac,saved.request_mac);
 f.confirmReadRevoke(id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:1,pending:0});const a=await complete(next,f,id),b=await complete(next,f,id);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(a.json.inviteUrl,b.json.inviteUrl);assert.match(a.json.inviteUrl,/^https:\/\/organico\.shrigma\.com\.br\/#invite=/);assert.equal(f.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(id).n,1);assert.equal(row(f,id).brand,'aristo');assert.deepEqual(row(f,id).areas,['organico']);assert.equal(f.auth.fulfillManagedCampaignWriterRequests().queued,0);
});

test('stale revision, foreign email collision, wrong CSRF/manager context and widened API payload leave existing identity intact',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f),ctx=await f.login();f.invite('occupied@fishermans.com.br');const before=snapshot(f,id);
 for(const [body,context,status]of [[fields(f,id,{expectedRevision:'0'.repeat(64)}),f.context,409],[fields(f,id,{email:'occupied@fishermans.com.br'}),f.context,409],[fields(f,id,{brand:'aristo'}),{...f.context,csrf:'wrong'},403],[fields(f,id,{brand:'aristo'}),ctx,403],[{...fields(f,id),principalId:'forged'},f.context,400]]){assert.equal((await post(http,f,body,context)).status,status);assert.equal(snapshot(f,id),before);}
});

test('pending campaign journal prevents profile transfer without deleting journal, slot, password or session',async t=>{
 const f=await fixture(t),id=await f.manager();await f.issue(id);const http=app(t,f),ctx=await f.login();pending(f,id,'campaign_draft_operations','uncertain');const before=snapshot(f,id),raw=f.db.prepare('SELECT * FROM campaign_draft_operations WHERE user_id=?').get(id);
 const r=await post(http,f,fields(f,id,{brand:'aristo'}));assert.equal(r.status,409);assert.equal(r.json.error,'CAMPAIGN_RECONCILIATION_REQUIRED');assert.equal(snapshot(f,id),before);assert.deepEqual(f.db.prepare('SELECT * FROM campaign_draft_operations WHERE user_id=?').get(id),raw);assert.equal(f.auth.session(ctx).authenticated,true);
});

test('tampered sealed update or lifecycle drift cannot rebind identity, grant edit or issue a new invitation',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f);assert.equal((await post(http,f,fields(f,id,{brand:'aristo'}))).status,202);f.confirmReadRevoke(id);
 const raw=f.db.prepare('SELECT request_json FROM user_profile_updates_v1 WHERE user_id=?').get(id).request_json,q=JSON.parse(raw);q.email='forged@fishermans.com.br';f.db.prepare('UPDATE user_profile_updates_v1 SET request_json=? WHERE user_id=?').run(JSON.stringify(q),id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:1});assert.equal(f.db.prepare('SELECT email FROM users WHERE id=?').get(id).email,'manager@oaristocrata.com');assert.equal(f.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(id).n,0);
 f.db.prepare('UPDATE user_profile_updates_v1 SET request_json=? WHERE user_id=?').run(raw,id);f.db.prepare('UPDATE crm_manager_lifecycles_v1 SET version=version+1 WHERE lifecycle_id=(SELECT lifecycle_id FROM crm_manager_current_v1 WHERE user_id=?)').run(id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:1});assert.equal(f.db.prepare('SELECT can_edit FROM grants WHERE user_id=?').get(id).can_edit,0);
});

test('explicit Master revoke cancels pending transfer and prevents background recovery from recreating access',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f);assert.equal((await post(http,f,fields(f,id,{brand:'aristo'}))).status,202);assert.equal((await post(http,f,{action:'revoke',userId:id})).status,200);f.confirmReadRevoke(id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:0});assert.equal(row(f,id).status,'disabled');assert.equal(row(f,id).profileUpdate,undefined);assert.equal(f.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(id).n,0);
});

test('Master corrects a queued destination conflict with current revision without repeating revocation or reviving the old identity',async t=>{
 const f=await fixture(t),id=await f.manager(),http=app(t,f),original=fields(f,id,{email:'later@fishermans.com.br',brand:'aristo',access:'edit'});assert.equal((await post(http,f,original)).status,202);
 const operations=f.db.prepare("SELECT * FROM crm_manager_operations_v1 WHERE kind='revoke'").all(),admission=f.db.prepare('SELECT * FROM crm_writer_auth_admission_v1 WHERE user_id=?').get(id),mac=f.db.prepare('SELECT request_mac FROM user_profile_updates_v1 WHERE user_id=?').get(id).request_mac;
 f.invite('later@fishermans.com.br');f.confirmReadRevoke(id);assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:0,pending:1});assert.equal(row(f,id).profileUpdate.canCorrect,true);assert.equal((await complete(http,f,id)).json.error,'USER_EXISTS');assert.equal(row(f,id).status,'disabled');
 assert.equal((await post(http,f,{...original,email:'corrected@fishermans.com.br'})).status,409);assert.equal((await post(http,f,fields(f,id,{email:'corrected@fishermans.com.br',brand:'aristo',access:'edit'}),{...f.context,csrf:'wrong'})).status,403);
 assert.equal((await post(http,f,fields(f,id,{email:'corrected@fishermans.com.br',brand:'aristo',access:'edit'}))).status,202);assert.notEqual(f.db.prepare('SELECT request_mac FROM user_profile_updates_v1 WHERE user_id=?').get(id).request_mac,mac);assert.deepEqual(f.db.prepare('SELECT * FROM crm_writer_auth_admission_v1 WHERE user_id=?').get(id),admission);assert.equal(f.db.prepare("SELECT count(*) n FROM crm_manager_operations_v1 WHERE kind='revoke'").get().n,operations.length);assert.equal(row(f,id).email,'manager@oaristocrata.com');assert.equal(row(f,id).status,'disabled');
 assert.deepEqual(f.auth.reconcileUserProfileUpdates(),{completed:1,pending:0});assert.equal(row(f,id).email,'corrected@fishermans.com.br');assert.equal(row(f,id).brand,'aristo');assert.equal(row(f,id).permissions.growth.edit,false);assert.equal((await complete(http,f,id)).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM invites WHERE user_id=? AND used_at IS NULL').get(id).n,1);
});
