'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture:originalFixture,hosts,command}=require('./dashboard-operational-campaign-submit.test.cjs');
const {definition}=require('./dashboard-operational-campaign-create-fixture.cjs');
async function fixture(t,options){const f=await originalFixture(t,options);return {...f,get:(p,h,r,extra={})=>f.get(h,r,{...p,...extra}),post:(p,h,r,q,extra={})=>f.post(h,r,q,{...p,...extra})};}
const create=(key='http_create_attempt_0001',brand='fish')=>({acao:'campanha_criar',brand,definition:definition(brand),idempotency_key:key});
const route=q=>'/auth/campaign-create?brand='+q.brand+'&idempotency_key='+q.idempotency_key;
const posts=f=>f.calls.filter(x=>x.method==='POST');
test('authenticated CREATE 201 source receipt then save/review/schedule/cancel with same derived ID',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('writer@synthetic.invalid');let q=create(),r=await f.post(p,hosts.growth,'/auth/campaign-create',q);assert.equal(r.status,200);assert.equal(r.json.action,'campanha_criar');assert.equal(r.json.state,'succeeded');assert.equal(r.json.campaign.id,1001);assert.equal(r.json.campaign.sendAt,null);assert.equal(f.origin.effects.schedule,0);const privateRow=f.inspect(db=>db.prepare('SELECT * FROM crm_campaign_create_v1').get());assert.equal(r.raw.includes(privateRow.remote_key),false);assert.equal(r.raw.includes(p.bearer),false);assert.equal(r.raw.includes('Synthetic HTML canary'),false);
 const current=()=>f.origin.rows.get(1001);const save=command('salvar',current(),'http_new_save_attempt_01',{definition:{...current().definition,subject:'Updated synthetic',send_at:new Date(Date.now()+3600000).toISOString()}});r=await f.post(p,hosts.growth,'/api/campaigns',save);assert.equal(r.status,200);assert.equal(f.origin.effects.schedule,0);r=await f.post(p,hosts.growth,'/api/campaigns',command('validar',current(),'http_new_check_attempt_01'));assert.equal(r.status,200);assert.ok(r.json.validation);r=await f.post(p,hosts.growth,'/api/campaigns',command('agendar',current(),'http_new_schedule_0001',{audience_review_id:r.json.validation.audience.review_id}));assert.equal(r.status,200);assert.equal(r.json.campaign.status,'scheduled');r=await f.post(p,hosts.growth,'/api/campaigns',command('cancelar',current(),'http_new_cancel_attempt_01'));assert.equal(r.status,200);assert.equal(r.json.campaign.status,'cancelled');assert.equal(f.origin.effects.create,1);assert.equal(f.origin.effects.schedule,1);assert.equal(f.origin.effects.cancel,1);});
test('HTTP lost ACK after effect: public202, restart STATUS binds ID without a second POST',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('lost@synthetic.invalid'),q=create();f.behavior(async({options,dispatch})=>{if(options.method==='POST'){await dispatch();throw Error('PRIVATE_RAW_CANARY');}return dispatch();});let r=await f.post(p,hosts.growth,'/auth/campaign-create',q);assert.equal(r.status,202);assert.equal(r.json.campaign,null);assert.equal(f.inspect(db=>db.prepare('SELECT campaign_id FROM crm_campaign_create_v1').get()).campaign_id,null);await f.restart();f.behavior(null);r=await f.get(p,hosts.growth,route(q));assert.equal(r.status,200);assert.equal(r.json.campaign.id,1001);assert.equal(posts(f).length,1);});
test('HTTP lost request/404 preserves same attempt, new key denied, no status repeats POST',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('unknown@synthetic.invalid'),q=create();f.behavior(({options,dispatch})=>options.method==='POST'?Promise.reject(Error('PRIVATE_RAW_CANARY')):dispatch());let r=await f.post(p,hosts.growth,'/auth/campaign-create',q);assert.equal(r.status,202);await f.restart();for(let i=0;i<2;i++){r=await f.get(p,hosts.growth,route(q));assert.equal(r.status,202);}r=await f.post(p,hosts.growth,'/auth/campaign-create',q);assert.equal(r.status,202);assert.equal(posts(f).length,1);assert.equal(f.origin.effects.create,0);r=await f.post(p,hosts.growth,'/auth/campaign-create',create('http_new_attempt_0002'));assert.equal(r.status,409);f.behavior(null);for(const brand of ['fish','aristo']){r=await f.get(p,hosts.growth,'/api/campaigns?acao=campanha_catalogo&brand='+brand);assert.equal(r.status,200);}});
test('host/Origin/CSRF/read role/admin/crossuser cannot CREATE or obtain attempt',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('guard@synthetic.invalid'),other=await f.manager('other@synthetic.invalid'),read=await f.manager('reader@synthetic.invalid',{writer:false});const q=create();for(const [who,host,extra] of [[p,hosts.manager,{}],[p,hosts.organico,{}],[p,hosts.growth,{origin:'https://foreign.invalid'}],[p,hosts.growth,{csrf:'invalid'}],[read,hosts.growth,{}],[f.admin,hosts.manager,{}]]){const r=await f.post(who,host,'/auth/campaign-create',q,extra);assert.ok([401,403,421].includes(r.status),String(r.status));}assert.equal(posts(f).length,0);assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',q)).status,200);assert.equal((await f.get(other,hosts.growth,route(q))).status,404);assert.equal((await f.get(p,hosts.growth,route(q),{csrf:'invalid'})).status,403);assert.equal(posts(f).length,1);});
test('OFF/default exposes no CREATE factory/table and rejects HTTP',async t=>{const f=await fixture(t,{enabled:false,createMode:true}),p=await f.manager('off@synthetic.invalid');assert.equal(f.auth().campaignCreateFor,undefined);assert.equal(f.inspect(db=>db.prepare("SELECT 1 FROM sqlite_master WHERE name='crm_campaign_create_v1'").get()),undefined);assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',create())).status,403);assert.equal(f.calls.length,0);});
test('CREATE pending blocks UPDATE within same brand; other user and brand stay independent',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('pending@synthetic.invalid'),other=await f.manager('independent@synthetic.invalid'),q=create();f.behavior(({options,dispatch})=>options.method==='POST'?Promise.reject(Error('Lost')):dispatch());assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',q)).status,202);const fakeRow={id:1001,version:'a'.repeat(32)};let r=await f.post(p,hosts.growth,'/api/campaigns',command('salvar',fakeRow,'blocked_update_attempt_01',{definition:definition()}));assert.equal(r.status,409);assert.equal(posts(f).length,1);f.behavior(null);assert.equal((await f.post(other,hosts.growth,'/auth/campaign-create',q)).status,200);assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',create('aristo_create_attempt_01','aristo'))).status,200);});
test('UPDATE queued intent blocks new CREATE under same SQLite reservation',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('reverse@synthetic.invalid');assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',create())).status,200);const row=f.origin.rows.get(1001);f.behavior(({payload,dispatch})=>payload.acao==='campanha_obter'?Promise.reject(Error('Lost GET')):dispatch());let r=await f.post(p,hosts.growth,'/api/campaigns',command('salvar',row,'queued_update_attempt_01',{definition:{...row.definition,subject:'Queued'}}));assert.equal(r.status,202);r=await f.post(p,hosts.growth,'/auth/campaign-create',create('blocked_create_attempt_02'));assert.equal(r.status,409);assert.equal(f.origin.effects.create,1);});
test('closed CREATE body/status query cannot supply ID/version/remote key or credentials',async t=>{const f=await fixture(t,{createMode:true}),p=await f.manager('shape@synthetic.invalid');for(const q of [{...create(),id:168},{...create(),expected_version:'a'.repeat(32)},{...create(),k:'PRIVATE_KEY_CANARY'},{...create(),definition:{...definition(),send_at:new Date(Date.now()+3600000).toISOString()}}])assert.equal((await f.post(p,hosts.growth,'/auth/campaign-create',q)).status,400);assert.equal((await f.get(p,hosts.growth,route(create())+'&id=168')).status,400);assert.equal(f.calls.length,0);});
