'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createCampaignBffClient}=require('../services/dashboard-operational/public/campaign-bff-client.js');
function setup(){const rows=new Map(),calls=[],scope=s=>s.uiKey+':'+s.brand;let response,owner='a';const session=()=>({authenticated:true,uiKey:'ui-'+owner.repeat(32),csrf:'c'.repeat(43),features:{campaignSubmitWrite:true},user:{role:'manager',areas:['growth'],permissions:{growth:{read:true,edit:true}}}});const make=()=>createCampaignBffClient({getSession:session,readJournal:s=>rows.get(scope(s))??null,writeJournal:(s,r)=>rows.set(scope(s),structuredClone(r)),request:async q=>{calls.push(q);const brand=q.body?.brand??new URL(q.path,'https://synthetic.invalid').searchParams.get('brand'),r=rows.get(scope({uiKey:session().uiKey,brand}));assert.ok(r);if(q.method==='POST')assert.equal(r.phase,'pending');return response(q,r);}});return{rows,calls,make,session,answer:fn=>{response=fn;},owner:v=>{owner=v;}};}
const q=(key='create_client_attempt_01')=>({brand:'fish',idempotency_key:key,definition:{brand:'fish',send_at:null}});
const answer=(r,state='succeeded',id=1001)=>({status:state==='pending'?202:200,body:{schema:'crm-campaign-bff-operation-v1',action:r.action,attemptKey:r.attemptKey,state,campaign:state==='pending'?null:{id,version:'a'.repeat(32),status:'draft',sent:0,startedAt:null,sendAt:null},validation:null}});
test('CREATE client exact body persists first and binds only first proven DTO ID across GET restart',async()=>{const f=setup();f.answer((_,r)=>answer(r));const c=f.make();for(const bad of [{...q(),id:167},{...q(),expected_version:'a'.repeat(32)},{...q(),definition:{brand:'fish',send_at:'2026-10-04T12:00:00.000Z'}},{...q(),k:'PRIVATE'}])await assert.rejects(c.create(bad),{code:'CAMPAIGN_BFF_INPUT'});assert.equal(f.calls.length,0);assert.equal((await c.create(q())).campaign.id,1001);assert.equal(f.calls[0].path,'/auth/campaign-create');assert.equal(Object.hasOwn(f.calls[0].body,'id'),false);assert.equal(f.rows.values().next().value.createdId,1001);f.answer((_,r)=>answer(r,'succeeded',1002));await assert.rejects(f.make().consult('fish'),{code:'CAMPAIGN_BFF_UNCERTAIN'});assert.equal(f.rows.values().next().value.createdId,1001);assert.deepEqual(f.calls.map(x=>x.method),['POST','GET']);});
test('legacy 201/non-BFF and partial CREATE responses remain uncertain and only STATUS can follow',async()=>{for(const response of [{status:201,body:{campaign:{id:1001}}},{status:200,body:{schema:'crm-campaign-bff-operation-v1',action:'campanha_criar',attemptKey:q().idempotency_key,state:'succeeded',campaign:{id:1001},validation:null}}]){const f=setup();f.answer(()=>response);await assert.rejects(f.make().create(q()),{code:'CAMPAIGN_BFF_UNCERTAIN'});await assert.rejects(f.make().create(q()),{code:'CAMPAIGN_BFF_UNCERTAIN'});await assert.rejects(f.make().create(q('new_other_attempt_key_02')),{code:'CAMPAIGN_BFF_PENDING'});assert.deepEqual(f.calls.map(x=>x.method),['POST','GET']);assert.equal(f.rows.values().next().value.createdId,undefined);}});
test('CREATE and existing UPDATE share one browser intent per actor/brand, terminal proof permits next action',async()=>{const f=setup();f.answer((_,r)=>answer(r,'pending'));const c=f.make();await c.create(q());await assert.rejects(c.save({brand:'fish',id:1001,expected_version:'a'.repeat(32),idempotency_key:'update_browser_attempt_02',definition:{brand:'fish'}}),{code:'CAMPAIGN_BFF_PENDING'});f.answer((_,r)=>answer(r));await c.consult('fish');await c.save({brand:'fish',id:1001,expected_version:'a'.repeat(32),idempotency_key:'update_browser_attempt_02',definition:{brand:'fish'}});assert.equal(f.calls.filter(x=>x.method==='POST').length,2);assert.equal(f.calls.at(-1).path,'/api/campaigns');});
