'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {uiFixture,until,stored,postRequests,checked,clickEffect,hosts}=require('./dashboard-operational-campaign-create-ui-fixture.cjs');
function forgeBrand(ui,brand){const option=ui.document.createElement('option');option.value=brand;option.textContent='Forged other brand';ui.element('campaign-brand').append(option);ui.change('campaign-brand',brand);}
function fillCreate(ui,brand='fish'){
 ui.element('campaign-new').click();assert.equal(ui.document.activeElement.id,'campaign-name');
 ui.input('campaign-name','UI new draft '+brand);ui.input('campaign-subject','UI CREATE subject');ui.input('campaign-initiative-key','create-ui');ui.input('campaign-initiative-name','UI initiative');ui.input('campaign-utm',brand+'-create-ui');
 const domain=brand==='fish'?'fishermans.com.br':'oaristocrata.com';ui.input('campaign-html','<a href="https://'+domain+'/products/ui">UI</a>{{ UnsubscribeURL }}');ui.input('campaign-text','https://'+domain+'/products/ui {{ UnsubscribeURL }}');
 const list=ui.element('campaign-lists').querySelector('input');assert.ok(list);list.checked=true;list.dispatchEvent(new ui.window.Event('input',{bubbles:true}));
}
test('compiled DOM CREATE unbound form derives receipt ID then supports save/review/schedule/cancel',async t=>{const ui=await uiFixture(t);await ui.controller.open();assert.equal(ui.element('campaign-new').disabled,false);assert.equal(ui.element('campaign-save').disabled,true);fillCreate(ui);assert.match(ui.element('campaign-state').textContent,/sem ID/);assert.equal(ui.element('campaign-time').disabled,true);assert.equal(ui.element('campaign-create').disabled,false);assert.equal(ui.element('campaign-validate').disabled,true);await clickEffect(ui,'create',1);assert.equal(ui.f.origin.row().id,1001);assert.equal(ui.f.origin.row().send_at,null);assert.equal(ui.f.origin.effects.schedule,0);let row=stored(ui);assert.equal(row.createdId,1001);assert.equal(Object.hasOwn(row.command,'id'),false);assert.equal(Object.hasOwn(row.command,'expected_version'),false);assert.equal(row.command.definition.send_at,null);assert.equal(postRequests(ui)[0].path,'/auth/campaign-create');assert.equal(ui.element('campaign-create').hidden,true);assert.equal(ui.element('campaign-select').value,'1001');
 ui.input('campaign-time',new Date(ui.f.config.now()+86400000).toISOString().slice(0,16));await clickEffect(ui,'save',2);await clickEffect(ui,'validate',1);checked(ui);await clickEffect(ui,'schedule',1);checked(ui);await clickEffect(ui,'cancel',1);assert.equal(ui.f.origin.row().status,'cancelled');assert.equal(ui.f.origin.effects.create,1);assert.equal(postRequests(ui).length,5);assert.ok(ui.locks.names.every(n=>n==='shrigma-campaign-bff:'+ui.session().uiKey+':fish'));assert.equal(JSON.stringify([...ui.storage.values]).includes(ui.person.bearer),false);ui.escape();assert.equal(ui.dialog.open,false);assert.equal(ui.document.activeElement.id,'entry-campaign-open');});
test('lost CREATE ACK after source recovers through reload STATUS before catalogue, no second POST',async t=>{let ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);ui.f.behavior(async({options,dispatch})=>{if(options.method==='POST'){await dispatch();throw Error('SYNTHETIC_ACK_LOST');}return dispatch();});ui.element('campaign-create').click();await until(()=>stored(ui)?.phase==='uncertain'&&!ui.element('campaign-consult').disabled,'uncertain CREATE');const key=stored(ui).attemptKey,start=ui.requests.length;assert.equal(stored(ui).createdId,undefined);assert.equal(ui.element('campaign-new').disabled,true);ui=ui.remount();await ui.controller.open();assert.equal(ui.requests[start].method,'GET');assert.match(ui.requests[start].path,/^\/auth\/campaign-create\?/);assert.equal(stored(ui).attemptKey,key);assert.equal(stored(ui).createdId,1001);assert.equal(postRequests(ui).length,1);assert.equal(ui.element('campaign-select').value,'1001');});
test('lost request/404 survives a refused forged brand switch, close and reload without repeating POST',async t=>{
 let ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);ui.f.behavior(({options,dispatch})=>options.method==='POST'?Promise.reject(Error('Lost before source')):dispatch());
 ui.element('campaign-create').click();await until(()=>stored(ui)?.phase==='uncertain'&&!ui.element('campaign-consult').disabled,'pending404');const a=stored(ui),before=ui.requests.length;
 forgeBrand(ui,'aristo');for(let i=0;i<3;i++)await new Promise(resolve=>setImmediate(resolve));
 assert.equal(ui.requests.length,before,'A forged other-brand selector performs no I/O');assert.equal(ui.element('campaign-brand').value,'fish');assert.equal(stored(ui,'aristo'),null);assert.deepEqual(stored(ui),a);
 assert.equal(ui.element('campaign-name').value,'UI new draft fish');assert.equal(ui.element('campaign-create').disabled,true);assert.equal(ui.element('campaign-save').disabled,true);assert.equal(ui.element('campaign-new').disabled,true);assert.match(ui.element('campaign-state').textContent,/sem ID/);
 ui=ui.remount();const resume=ui.requests.length;await ui.controller.open();assert.match(ui.requests[resume].path,/^\/auth\/campaign-create\?brand=fish/);assert.equal(stored(ui).attemptKey,a.attemptKey);
 ui.element('campaign-consult').click();await until(()=>ui.responses.at(-1)?.request.path.startsWith('/auth/campaign-create?')&&!ui.element('campaign-consult').disabled,'statusagain');assert.equal(postRequests(ui).length,1);assert.equal(ui.f.origin.effects.create,0);
});
test('late CREATE ACK cannot paint a different authenticated brand or actor and the original intent remains recoverable',async t=>{
 let ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);const originalSession=ui.session();let release; t.after(()=>release?.());
 ui.f.behavior(async({options,dispatch})=>{if(options.method==='POST'){await new Promise(r=>{release=r;});}return dispatch();});
 ui.element('campaign-create').click();await until(()=>release!==undefined,'POSTgate');const old=stored(ui),oldJournalKey='shrigma_campaign_bff_v1:'+originalSession.uiKey+':fish',before=ui.requests.length;
 forgeBrand(ui,'aristo');for(let i=0;i<3;i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(ui.requests.length,before);assert.equal(ui.element('campaign-brand').value,'fish');
 const other=await ui.f.manager('other-create-brand@synthetic.invalid',{brand:'aristo'});const otherSession=(await ui.f.get(hosts.growth,'/auth/session',other)).json;
 assert.equal(otherSession.authenticated,true);assert.equal(otherSession.user.brand,'aristo');assert.equal(otherSession.user.brandAccess,'single');assert.notEqual(otherSession.uiKey,originalSession.uiKey);ui.setSession(otherSession);
 const beforeLateState=ui.element('campaign-state').textContent;release();await until(()=>ui.f.origin.effects.create===1&&postRequests(ui).length===1,'lateeffect');for(let i=0;i<10;i++)await new Promise(r=>setImmediate(r));
 assert.equal(ui.element('campaign-select').value,'');assert.equal(ui.element('campaign-state').textContent,beforeLateState);assert.equal(ui.element('campaign-state').textContent.includes('1001'),false);
 assert.equal(JSON.parse(ui.storage.getItem(oldJournalKey)).attemptKey,old.attemptKey);assert.equal(stored(ui),null);assert.equal(stored(ui,'aristo'),null);
 ui.setSession(originalSession);ui=ui.remount();const resume=ui.requests.length;await ui.controller.open();assert.match(ui.requests[resume].path,/^\/auth\/campaign-create\?brand=fish/);assert.equal(stored(ui).attemptKey,old.attemptKey);assert.equal(stored(ui).createdId,1001);assert.equal(postRequests(ui).length,1);assert.equal(ui.element('campaign-select').value,'1001');
});
test('CREATE readback404 keeps confirmed ID private, no fabricated existing editor from list fallback',async t=>{let ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);ui.f.behavior(({payload,dispatch})=>payload.acao==='campanha_obter'?Promise.resolve({status:404,body:{error:'MISSING'}}):dispatch());ui.element('campaign-create').click();await until(()=>stored(ui)?.phase==='uncertain'&&!ui.element('campaign-consult').disabled,'fresh404');assert.equal(stored(ui).createdId,undefined);assert.equal(ui.element('campaign-save').disabled,true);ui=ui.remount();await ui.controller.open();assert.equal(ui.element('campaign-select').value,'');assert.equal(ui.element('campaign-name').value,'UI new draft fish');assert.equal(ui.element('campaign-save').disabled,true);assert.match(ui.element('campaign-state').textContent,/sem ID/);assert.equal(postRequests(ui).length,1);ui.f.behavior(null);ui.element('campaign-consult').click();await until(()=>stored(ui)?.phase==='succeeded'&&!ui.element('campaign-save').disabled,'derivedreadback');assert.equal(stored(ui).createdId,1001);});
test('OFF/read session/missing locks cannot open or POST CREATE',async t=>{for(const opts of [{enabled:false},{writer:false},{locks:undefined}]){const settings=Object.hasOwn(opts,'locks')?{locks:{}}:opts;const ui=await uiFixture(t,settings);const opened=await ui.controller.open();if(opts.enabled===false||opts.writer===false)assert.equal(opened,false);else{assert.equal(opened,true);assert.equal(ui.element('campaign-new').disabled,true);ui.element('campaign-new').click();assert.equal(ui.element('campaign-create').hidden,true);}assert.equal(postRequests(ui).length,0);}});

test('reload cannot persist a stale STATUS journal while another tab holds the mutation lock',async t=>{let ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);let release;ui.f.behavior(async({options,dispatch})=>{if(options.method==='POST')await new Promise(r=>{release=r;});return dispatch();});ui.element('campaign-create').click();await until(()=>release!==undefined,'held POST lock');const start=ui.requests.length,key=stored(ui).attemptKey;ui=ui.remount();await ui.controller.open();assert.equal(ui.requests.slice(start).some(q=>q.path.startsWith('/auth/campaign-create?')),false);assert.equal(stored(ui).attemptKey,key);assert.equal(ui.element('campaign-new').disabled,true);release();await until(()=>stored(ui)?.phase==='succeeded','old tab final receipt');ui.element('campaign-consult').click();await until(()=>ui.responses.at(-1)?.request.path.includes('campanha_obter')&&!ui.element('campaign-save').disabled,'new tab recovery');assert.equal(postRequests(ui).length,1);assert.equal(stored(ui).createdId,1001);});

test('CREATE proved succeeded closes its form before failing the separate fresh UI read, then only same STATUS recovers',async t=>{const ui=await uiFixture(t);await ui.controller.open();fillCreate(ui);let obtains=0;ui.f.behavior(({payload,dispatch})=>payload.acao==='campanha_obter'&&++obtains===2?Promise.resolve({status:404,body:{error:'MISSING'}}):dispatch());ui.element('campaign-create').click();await until(()=>stored(ui)?.phase==='succeeded'&&!ui.element('campaign-consult').disabled&&ui.element('campaign-status').textContent.startsWith('Rascunho criado.'),'secondGET404');assert.equal(stored(ui).createdId,1001);assert.equal(ui.element('campaign-create').hidden,true);assert.equal(ui.element('campaign-new').disabled,true);assert.equal(ui.element('campaign-save').disabled,true);ui.element('campaign-create').click();for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));assert.equal(postRequests(ui).length,1);ui.f.behavior(null);ui.element('campaign-consult').click();await until(()=>ui.responses.at(-1)?.request.path.includes('campanha_obter')&&!ui.element('campaign-save').disabled,'sameattempt recovered');assert.equal(stored(ui).createdId,1001);assert.equal(postRequests(ui).length,1);});
