'use strict';
// Exact compiled browser assets, real parsed DOM; every request is an in-process fake.
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {browserDom,memoryStorage,serialLocks,until}=require('./dashboard-operational-campaign-create-ui-fixture.cjs');
const {definition}=require('./dashboard-operational-campaign-create-fixture.cjs');
const {createCampaignEditor}=require('../services/dashboard-operational/public/campaign-edit.compiled.js');
const {createCampaignBffClient}=require('../services/dashboard-operational/public/campaign-bff-client.js');
const session=letter=>({authenticated:true,features:{campaignSubmitWrite:true},csrf:letter.repeat(43),uiKey:'ui-'+letter.repeat(32),user:{role:'manager',areas:['growth'],permissions:{growth:{read:true,edit:true}}}});
function fixture(options={}){
 let currentSession=session('a'),behavior=null,nextId=1001;const storage=options.storage||memoryStorage(),locks=options.locks||serialLocks(),requests=[],rows=new Map(),attempts=new Map();
 for(const [brand,id]of [['fish',2001],['aristo',2002]])rows.set(id,{id,version:'c'.repeat(32),status:'draft',sent:0,started_at:null,send_at:null,definition:definition(brand)});
 const projection=c=>({id:c.id,version:c.version,status:c.status,sent:c.sent,startedAt:c.started_at,sendAt:c.send_at});
 const request=async q=>{requests.push(structuredClone(q));assert.equal(q.headers['X-CSRF-Token']!==undefined,true);assert.equal(Object.keys(q.headers).some(k=>/authorization|cookie/i.test(k)),false);
  const dispatch=()=>{const url=new URL(q.path,'https://synthetic.invalid');if(q.method==='POST'&&url.pathname==='/auth/campaign-create'){const c={id:nextId++,version:'d'.repeat(32),status:'draft',sent:0,started_at:null,send_at:null,definition:structuredClone(q.body.definition)};rows.set(c.id,c);const result={status:200,body:{schema:'crm-campaign-bff-operation-v1',action:'campanha_criar',attemptKey:q.body.idempotency_key,state:'succeeded',campaign:projection(c),validation:null}};attempts.set(q.body.idempotency_key,result);return structuredClone(result);}
   if(q.method!=='GET')throw Error('SYNTHETIC_UNEXPECTED_POST');if(url.pathname==='/auth/campaign-create')return structuredClone(attempts.get(url.searchParams.get('idempotency_key'))||{status:404,body:{error:'MISSING'}});
   const brand=url.searchParams.get('brand'),action=url.searchParams.get('acao');if(url.pathname!=='/api/campaigns')throw Error('SYNTHETIC_PATH_REFUSED');if(action==='campanha_catalogo')return{status:200,body:{brand,current:true,lists:[{id:brand==='fish'?125:126,brand,available:true}],templates:[{id:1,type:'campaign',available:true}]}};
   if(action==='campanha_listar')return{status:200,body:{campaigns:[...rows.values()].filter(c=>c.definition.brand===brand).map(c=>structuredClone(c))}};if(action==='campanha_obter'){const c=rows.get(Number(url.searchParams.get('id')));return c?.definition.brand===brand?{status:200,body:{campaign:structuredClone(c)}}:{status:404,body:{error:'MISSING'}};}throw Error('SYNTHETIC_ACTION_REFUSED');};return behavior?behavior({q,dispatch}):dispatch();};
 const mount=()=>{const dom=browserDom(),controller=createCampaignEditor({document:dom.document,getSession:()=>currentSession,request,storage,locks,now:()=>Date.parse('2026-10-03T12:00:00.000Z'),uuid:()=>crypto.randomUUID(),createClient:createCampaignBffClient});return{...dom,controller};};
 return{...mount(),mount,requests,storage,locks,rows,behavior:fn=>{behavior=fn;},setSession:s=>{currentSession=s;},session:()=>currentSession,stored(brand='fish',owner=currentSession.uiKey){const text=storage.getItem('shrigma_campaign_bff_v1:'+owner+':'+brand);return text?JSON.parse(text):null;}};
}
function fill(ui){ui.element('campaign-new').click();for(const [id,value]of [['initiative-key','synthetic-create'],['initiative-name','Synthetic'],['utm','synthetic-create'],['name','Independent new draft'],['subject','Independent subject'],['html','<a href="https://fishermans.com.br/products/fixture">Synthetic</a>{{ UnsubscribeURL }}'],['text','https://fishermans.com.br/products/fixture {{ UnsubscribeURL }}']])ui.input('campaign-'+id,value);ui.element('campaign-lists').querySelector('input').checked=true;ui.element('campaign-form').dispatchEvent(new ui.window.Event('input',{bubbles:true}));}
const tick=()=>new Promise(r=>setImmediate(r));
test('shared browser lock contention refuses CREATE before storing intent or POST',async()=>{
 const names=[],ui=fixture({locks:{request:(name,opts,cb)=>{names.push(name);return Promise.resolve(cb(null));}}});await ui.controller.open();fill(ui);ui.element('campaign-create').click();await until(()=>names.length===1&&!ui.element('campaign-create').disabled,'lock refusal');assert.equal(names[0],'shrigma-campaign-bff:'+ui.session().uiKey+':fish');assert.equal(ui.stored(),null);assert.equal(ui.requests.filter(q=>q.method==='POST').length,0);ui.controller.close();
});
test('successful CREATE plus failed UI fresh GET must not leave the unbound CREATE button reusable',async()=>{
 const ui=fixture();await ui.controller.open();fill(ui);ui.behavior(({q,dispatch})=>q.method==='GET'&&q.path.includes('campanha_obter')&&q.path.includes('id=1001')?{status:404,body:{error:'MISSING'}}:dispatch());ui.element('campaign-create').click();await until(()=>ui.stored()?.phase==='succeeded'&&!ui.element('campaign-consult').disabled,'terminal CREATE/readback failure');await tick();
 assert.equal(ui.stored().createdId,1001);assert.equal(ui.element('campaign-save').disabled,true);if(!ui.element('campaign-create').disabled&&!ui.element('campaign-create').hidden){ui.element('campaign-create').click();await until(()=>ui.requests.filter(q=>q.method==='POST').length===2,'unexpected duplicate CREATE');}assert.equal(ui.requests.filter(q=>q.method==='POST').length,1);assert.equal(ui.element('campaign-create').disabled||ui.element('campaign-create').hidden,true);ui.controller.close();
});
test('reload STATUS404 preserves CREATE despite an existing first campaign in the list',async()=>{
 let ui=fixture();await ui.controller.open();fill(ui);ui.behavior(({q,dispatch})=>q.method==='POST'?Promise.reject(Error('SYNTHETIC_ACK_LOST')):dispatch());ui.element('campaign-create').click();await until(()=>ui.stored()?.phase==='uncertain'&&!ui.element('campaign-consult').disabled,'uncertain intent');const key=ui.stored().attemptKey,start=ui.requests.length;ui.controller.close();const fresh=ui.mount();ui={...ui,...fresh};await ui.controller.open();assert.equal(ui.requests[start].method,'GET');assert.match(ui.requests[start].path,/^\/auth\/campaign-create\?/);assert.equal(ui.stored().attemptKey,key);assert.equal(ui.element('campaign-select').value,'');assert.equal(ui.element('campaign-save').disabled,true);assert.equal(ui.element('campaign-create').disabled,true);assert.match(ui.element('campaign-state').textContent,/sem ID/);assert.equal(ui.requests.filter(q=>q.method==='POST').length,1);ui.controller.close();
});
test('actor changes during CREATE retain old scope and never paint its late ID into the new owner',async()=>{
 let ui=fixture(),release;await ui.controller.open();fill(ui);const owner=ui.session().uiKey;ui.behavior(async({q,dispatch})=>{if(q.method==='POST')await new Promise(r=>{release=r;});return dispatch();});ui.element('campaign-create').click();await until(()=>release!==undefined,'inflight POST');const oldKey=ui.stored().attemptKey;ui.controller.close();ui.setSession(session('b'));const fresh=ui.mount();ui={...ui,...fresh};await ui.controller.open();release();for(let i=0;i<8;i++)await tick();assert.equal(ui.stored(),null);assert.equal(ui.stored('fish',owner).attemptKey,oldKey);assert.equal(ui.stored('fish',owner).createdId,undefined);assert.equal(ui.element('campaign-select').value,'2001');assert.equal(ui.element('campaign-state').textContent.includes('1001'),false);assert.equal(ui.requests.filter(q=>q.method==='POST').length,1);ui.controller.close();
});
