'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const P=require('../n8n/growth/email-test-recipient-workflow-patch.cjs');
const code=(name,jsCode)=>({name,type:'n8n-nodes-base.code',parameters:{jsCode}}),pg=name=>({name,type:'n8n-nodes-base.postgres',parameters:{query:'={{ $json.sql }}',options:{queryReplacement:'={{ $json.sqlParameters || [] }}'}},credentials:{postgres:{id:'synthetic'}}});
function workflow(){const http=(name,url)=>({name,type:'n8n-nodes-base.httpRequest',typeVersion:4.2,parameters:{url,options:{timeout:20000,redirect:{redirect:{followRedirects:false}},response:{response:{fullResponse:true,neverError:true}}}},credentials:{httpBasicAuth:{id:'synthetic'}}});return {versionId:'fixture',settings:{saveDataErrorExecution:'none',saveDataSuccessExecution:'none',saveManualExecutions:false,saveExecutionProgress:false},nodes:[code('Autenticação entrada',"const emailTestRoute=['email_teste','email_teste_previa','email_teste_operacao','email_previa','email_capacidades'].includes('');"),code('Prepara','// CRM_EMAIL_NATIVE_PREVIEW_V1\nreturn [];'),{name:'Etapa',type:'n8n-nodes-base.switch',parameters:{rules:{values:[]},options:{fallbackOutput:'extra'}}},pg('CRM Email Test claim'),pg('CRM Email Test snapshot'),http('CRM Email Test transport','https://email.shrigma.com.br/api/tx'),http('CRM Email Native read','https://email.shrigma.com.br/api/templates/1'),http('CRM Email Native render','https://email.shrigma.com.br/api/templates/preview'),code('CRM Email Test claim result','return [{json:$json.result}];'),code('CRM Email Test response','return [{json:$json.result}];'),code('Responde','')],connections:{Etapa:{main:[[]]}}};}
const opts=w=>({expectedVersionId:w.versionId,expectedNodeHashes:Object.fromEntries(P.AFFECTED.map(n=>[n,P.sha(w.nodes.find(x=>x.name===n))]))});
function run(code,globals={}){return vm.runInNewContext('(function(){'+code+'})()',globals);}
test('pure patch preserves credentials/settings and every existing node except exact four; new providers have no retry or redirect',()=>{const w=workflow(),before=JSON.stringify(w),{workflow:r}=P.patchWorkflow(w,opts(w));assert.equal(JSON.stringify(w),before);for(const n of w.nodes)if(!P.AFFECTED.includes(n.name))assert.deepEqual(r.nodes.find(x=>x.name===n.name),n);assert.deepEqual(r.settings,w.settings);for(const n of r.nodes.filter(n=>n.name.startsWith('CRM Email Recipient ')&&n.type==='n8n-nodes-base.httpRequest')){assert.equal(n.retryOnFail,false);assert.equal(n.parameters.options.redirect.redirect.followRedirects,false);assert.deepEqual(n.credentials,w.nodes.find(n=>n.name==='CRM Email Test transport').credentials);}assert.throws(()=>P.patchWorkflow(w,{...opts(w),expectedVersionId:'stale'}));assert.throws(()=>P.patchWorkflow(r,opts(r)));});
test('route authenticates manager, enforces exact method/body, parameterizes email and does not mutate legacy routes',()=>{const base={acao:'email_teste_previa_v2',auth:{who:'panel:fixture',caps:['draft','validate','submit']},method:'POST',b:{acao:'email_teste_previa_v2',draft_id:'d_fixture',expected_version:1,recipient:'test@shrigma.com.br'},q:{},out:(status,body)=>({json:{status,body}})};const r=run(P.ROUTE,base)[0].json;assert.equal(r._step,'crm_email_recipient');assert.doesNotMatch(r.sql,/test@/);assert.equal(JSON.parse(r.sqlParameters[1]).recipient,'test@shrigma.com.br');assert.equal(run(P.ROUTE,{...base,auth:{who:'panel:viewer',caps:[]}})[0].json.status,403);assert.equal(run(P.ROUTE,{...base,method:'GET'})[0].json.status,405);assert.equal(run(P.ROUTE,{...base,b:{...base.b,cc:'other'}})[0].json.status,400);});
test('bundle compiles in n8n sandbox without require; failed render and HTTP uncertainty never become an acceptance',()=>{for(const code of [P.PREPARE,P.RENDERED])assert.doesNotThrow(()=>new vm.Script('(function(){'+code+'})()'));const c={operation_id:'id',claim_token:'token'};for(const response of [{statusCode:500,body:{data:true}},{statusCode:200,body:{data:false}},{error:'timeout'}])assert.equal(run(P.FINISH,{$json:response,$:()=>({first:()=>({json:c})})})[0].json.sqlParameters[2],'outcome_unknown');});
