'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,uuid,GEC}=require('./fixtures/email-test-fixture.cjs');
const GEE=require(process.env.CRM_EMAIL_EXPRESSIONS_MODULE||'../growth-email-expressions.js');
const ENP=require('../n8n/growth/email-native-preview.cjs'),ENTP=require('../n8n/growth/email-native-test-protocol.cjs');
const {digest}=require('../n8n/growth/template-operation-receipt.cjs');
const deps={GEE,GEC,ENP,digest};
async function fixture(){const f=await setup();await f.db.exec("ALTER TABLE subscribers ADD COLUMN name text NOT NULL DEFAULT 'Fixture';ALTER TABLE subscribers ADD COLUMN uuid uuid NOT NULL DEFAULT '20000000-0000-4000-8000-000000000001';");await f.db.exec(fs.readFileSync(path.join(__dirname,'../n8n/growth/email-native-test.sql'),'utf8'));
 const r=(await f.snapshot()).rascunho;r.corpo='<p>{{ .Subscriber.Name }}</p>{{ if .Tx.Data.has_discount }}<p>{{ .Tx.Data.coupon_code }}</p>{{ end }}';r.assunto='Exemplo';const n=GEC.payload(r);
 await f.db.query('UPDATE templates SET subject=$1,body=$2',[n.subject,n.body]);await f.db.query('UPDATE shrigma_template_draft SET rascunho=$1,components=$2',[r,{subject:n.subject,body_html:n.body}]);
 f.nativeSnapshot=async()=> (await f.db.query("SELECT crm_email_native_snapshot_v1('panel:manager','d_fixture',1) s")).rows[0].s;
 f.nativePlan=async()=>{const s=await f.nativeSnapshot(),p=ENTP.prepare(s,{statusCode:200,body:{data:s.snapshot.native}},deps);return ENTP.rendered(p,{statusCode:200,body:'<html><body><p>Fixture</p><p>EXEMPLO</p></body></html>'},deps);};
 f.nativeClaim=async(n,plan=null,p=null)=>{plan||=await f.nativePlan();p||={...f.request(n),preview_token:plan.preview_token||'0'.repeat(64)};return(await f.db.query("SELECT crm_email_native_claim_v1('panel:manager',$1,$2) r",[p,plan])).rows[0].r;};return f;}
test('native preparation is deterministic, preserves source, requires real fixed identity only for test, and never exposes it in public preview',()=>{
 const r={marca:'aristo',canal:'email',nome:'fixture',from_email:'O Aristocrata <contato@oaristocrata.com>',reply_to:'contato@oaristocrata.com',preheader:'Exemplo',assunto:'Exemplo',corpo:'<p>{{ .Subscriber.Name }}</p>{{ range .Tx.Data.items }}<p>{{ .name }}</p>{{ end }}',botoes:[]};
 const p=ENP.prepare(r,deps);assert.equal(p.eligible,true);assert.equal(p.subscriber_context,'synthetic');assert.equal(p.source_hash,ENP.prepare(r,deps).source_hash);assert.equal(p.request.path,'/api/templates/preview');assert.ok(p.request.form.body.includes(GEC.payload(r).body));assert.equal(ENP.prepare(r,deps,{purpose:'test'}).code,'recipient_identity_unavailable');
 const accepted=ENP.accept(p,{statusCode:200,body:'<html><body><p>Synthetic</p></body></html>'},{GEC});assert.equal(accepted.eligible,true);assert.equal(accepted.context,undefined);assert.equal(accepted.request,undefined);
 for(const body of ['<script>alert(1)</script>','<p>#ZgotmplZ</p>','<p>{{ .Tx.Data.foo }}</p>',''])assert.equal(ENP.accept(p,{statusCode:200,body},{GEC}).eligible,false);
 assert.equal(ENP.accept(p,{statusCode:500,body:'<p>error</p>'},{GEC}).eligible,false);
});
test('native test requires exact native read, successful safe render, token; untrusted plan is never publicly eligible',async()=>{const f=await fixture();try{const s=await f.nativeSnapshot();assert.equal(ENTP.prepare(s,{statusCode:200,body:{data:{...s.snapshot.native,subject:'Changed'}}},deps).code,'published_content_mismatch');const p=ENTP.prepare(s,{statusCode:200,body:{data:s.snapshot.native}},deps);assert.equal(p.eligible,true);assert.equal(ENTP.preview(p).eligible,false);const r=ENTP.rendered(p,{statusCode:200,body:'<p>Fixture</p>'},deps);const visible=ENTP.preview(r);assert.equal(visible.eligible,true);assert.equal(visible.preview_token,s.preview_token);assert.equal(visible.snapshot,undefined);assert.equal(visible.context,undefined);assert.equal(visible.recipient,ENTP.RECIPIENT);assert.equal(r.subscriber_mode,'default');assert.equal(r.rendered_subject,'✅ FINAL — Exemplo');assert.throws(()=>ENTP.request({...f.request(1),preview_token:'invalid'}));}finally{await f.db.close();}});
test('additive SQL profile matches pure profile; once/journal and transport outcome reuse CRM05 across paths',async()=>{const f=await fixture();try{for(const b of ['fish','aristo'])assert.deepEqual((await f.db.query('SELECT crm_email_native_data_v1($1) d',[b])).rows[0].d,ENP.profile(b));const p=await f.nativePlan();assert.equal(p.eligible,true);const claim=await f.nativeClaim(1,p);assert.equal(claim.should_send,true);assert.equal(claim.payload.subscriber_mode,'default');assert.equal(claim.payload.subscriber_email,ENTP.RECIPIENT);assert.deepEqual(claim.payload.data,p.data);assert.match(claim.payload.headers[2]['X-SES-MESSAGE-TAGS'],/crm_test=true/);assert.equal((await f.nativeClaim(1,p)).should_send,false);assert.equal((await f.claim(2)).result._body.operation.code,'version_already_attempted');await f.db.query("SELECT crm_email_test_finish_v1($1,$2,'outcome_unknown')",[uuid(1),claim.claim_token]);assert.equal((await f.receipt(1))._body.operation.state,'outcome_unknown');assert.equal((await f.db.query('SELECT count(*)::int n FROM shrigma_email_dispatch')).rows[0].n,1);assert.equal((await f.db.query('SELECT count(*)::int n FROM subscribers')).rows[0].n,1);}finally{await f.db.close();}});
test('identity drift, brand optout, disabled recipient and absent identity refuse durably before dispatch',async()=>{
 for(const [change,expected]of [["UPDATE subscribers SET name='Changed'",'preview_changed'],["UPDATE subscribers SET uuid='30000000-0000-4000-8000-000000000001'",'preview_changed'],["INSERT INTO subscriber_lists VALUES(1,17,'unsubscribed')",'recipient_opted_out'],["UPDATE subscribers SET status='blocklisted'",'recipient_disabled'],['DELETE FROM subscriber_lists;DELETE FROM subscribers','recipient_unavailable']]){const f=await fixture();try{const p=await f.nativePlan();await f.db.exec(change);const c=await f.nativeClaim(1,p);assert.equal(c.should_send,false);assert.equal(c.result._body.operation.code,expected);assert.equal((await f.db.query('SELECT count(*)::int n FROM shrigma_email_dispatch')).rows[0].n,0);assert.equal((await f.nativeClaim(1,p)).result._body.operation.code,expected);}finally{await f.db.close();}}
});
test('native failure and forged arbitrary data are durably rejected; neither may dispatch',async()=>{const f=await fixture();try{const p=await f.nativePlan();const failure={eligible:false,code:'native_preview_unsafe'};assert.equal((await f.nativeClaim(1,failure,{...f.request(1),preview_token:p.preview_token})).result._body.operation.code,'native_preview_unsafe');const forged={...p,data:{coupon_code:'arbitrary'}};assert.equal((await f.nativeClaim(2,forged)).result._body.operation.code,'plan_changed');assert.equal((await f.db.query('SELECT count(*)::int n FROM shrigma_email_dispatch')).rows[0].n,0);}finally{await f.db.close();}});
test('changed preview token rejects before dispatch and a v1 reservation blocks v2 for the same version',async()=>{const f=await fixture();try{
 const p=await f.nativePlan();const changed={...f.request(1),preview_token:p.preview_token==='0'.repeat(64)?'1'.repeat(64):'0'.repeat(64)};
 assert.equal((await f.nativeClaim(1,p,changed)).result._body.operation.code,'preview_changed');assert.equal((await f.db.query('SELECT count(*)::int n FROM shrigma_email_dispatch')).rows[0].n,0);
 const r=(await f.snapshot()).rascunho;r.corpo='<p>Oi {{ .Tx.Data.first_name }}</p>';const native=GEC.payload(r);
 await f.db.query('UPDATE templates SET subject=$1,body=$2',[native.subject,native.body]);await f.db.query('UPDATE shrigma_template_draft SET rascunho=$1,components=$2',[r,{subject:native.subject,body_html:native.body}]);
 const future=await f.nativePlan();assert.equal(future.eligible,true);assert.equal(future.subscriber_mode,'external');assert.equal((await f.claim(2)).should_send,true);
 assert.equal((await f.nativeClaim(3,future)).result._body.operation.code,'version_already_attempted');assert.equal((await f.db.query('SELECT count(*)::int n FROM shrigma_email_dispatch')).rows[0].n,1);
 }finally{await f.db.close();}});
