'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),J=require('../growth-email-test.js');
const id=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0'),policy=J.RECIPIENT_POLICY;
const caps={contract:policy,policy_version:2,enabled:true,brands:['fish','aristo'],recipient_input:true,existing_only:false,limits:{per_revision:5,per_actor_hour:20},preview_ttl_seconds:300,prefix:'[TESTE] '};
function setup({storage,ops=new Map(),previewPatch={},enabled=true}={}){const map=new Map();storage||={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};let seq=0;const calls=[];const fetch=async(url,o)=>{const q=new URL(url).searchParams,p=o.body?JSON.parse(o.body):Object.fromEntries(q);calls.push(p);assert.equal(o.headers.Authorization,'Bearer synthetic-key');assert.equal(q.has('recipient'),false);let body;if(p.acao==='email_teste_capacidades_v2')body={...caps,enabled};else if(p.acao==='email_teste_previa_v2')body={contract:policy,eligible:true,recipient:p.recipient,brand:'fish',draft_id:p.draft_id,version:p.expected_version,preview_token:'b'.repeat(64),source_hash:'c'.repeat(64),body_html:'<p>Example</p>',rendered_subject:'[TESTE] Example',expires_at:new Date(Date.now()+300000).toISOString(),subscriber_context:'external',...previewPatch};else if(p.acao==='email_teste_v2'){assert.equal(JSON.parse(storage.getItem(J.SLOT)).operations.at(-1).phase,'pending');const {acao,...request_payload}=p;ops.set(p.idempotency_key,{idempotency_key:p.idempotency_key,actor:'panel:fixture',state:'accepted',request_payload,request_sha256:'a'.repeat(64),request_hash_schema:'postgres-jsonb-text-sha256-v1',draft_id:p.draft_id,version:p.expected_version,http_accepted:true,ses:{}});throw Error('lost response');}else if(p.acao==='email_teste_operacao_v2')body={contract:policy,operation:ops.get(p.idempotency_key)||{idempotency_key:p.idempotency_key,actor:'panel:fixture',state:'missing',request_payload:null}};else if(['email_teste_testadores_v2','email_teste_testador_v2'].includes(p.acao))body={contract:policy,brand:p.brand,testers:p.recipient?[{recipient:p.recipient,enabled:p.enabled,expires_at:'2099-01-01T00:00:00Z',updated_at:'2026-09-26T00:00:00Z'}]:[]};else throw Error('unknown action');return {status:200,json:async()=>body};};const client=J.create({endpoint:'https://example.invalid/templates',key:'synthetic-key',recipientPolicy:policy,storage,locks:{request:async(k,o,fn)=>fn({})},crypto:{randomUUID:()=>id(++seq)},fetch});return {client,calls,ops,storage};}
const input={draft_id:'d_fixture',expected_version:1,recipient:'TESTER@Fishermans.com.br'};
test('one address parser is exported; selected preview uses body and token binds recipient before one durable POST',async()=>{assert.equal(J.recipient(' A@Shrigma.com.br '),'a@shrigma.com.br');for(const x of ['a@b.com,b@b.com','Name <a@b.com>','a@b.com\r\nX:y'])assert.throws(()=>J.recipient(x),{code:'TEST_RECIPIENT'});const s=setup(),p=await s.client.preview(input);const r=await s.client.run({...input,preview_token:p.preview_token,confirm:'enviar_teste'});assert.equal(r.phase,'confirmed');assert.equal(r.operation.request_payload.recipient,'tester@fishermans.com.br');assert.equal(s.calls.filter(c=>c.acao==='email_teste_v2').length,1);assert.equal(s.client.inspect().operations[0].recipient_policy,policy);await assert.rejects(s.client.run({...input,preview_token:p.preview_token,confirm:'enviar_teste'}),{code:'TEST_ALREADY_ATTEMPTED'});const reload=setup({storage:s.storage,ops:s.ops});assert.equal((await reload.client.reconcile(id(1))).phase,'confirmed');assert.equal(reload.calls.filter(c=>c.acao==='email_teste_v2').length,0);});
test('disabled capability, foreign or expired preview, changed address fail closed before dispatch',async()=>{const off=setup({enabled:false});await assert.rejects(off.client.preview(input),{code:'TEST_POLICY'});for(const patch of [{recipient:'other@shrigma.com.br'},{draft_id:'d_other'},{expires_at:'2000-01-01T00:00:00Z'},{preview_token:'bad'}]){const s=setup({previewPatch:patch});await assert.rejects(s.client.preview(input),{code:'TEST_PREVIEW'});assert.equal(s.calls.some(c=>c.acao==='email_teste_v2'),false);}const s=setup(),p=await s.client.preview(input);await assert.rejects(s.client.run({...input,recipient:'other@shrigma.com.br',preview_token:p.preview_token,confirm:'enviar_teste'}),{code:'TEST_PREVIEW'});assert.equal(s.storage.getItem(J.SLOT),null);});
test('testers management binds brand, normalizes addresses and never creates send journal',async()=>{const s=setup();assert.deepEqual((await s.client.testers({brand:'aristo'})).testers,[]);const r=await s.client.setTester({brand:'aristo',recipient:' X@example.invalid ',enabled:false});assert.equal(r.testers[0].recipient,'x@example.invalid');assert.equal(r.testers[0].enabled,false);assert.equal(s.storage.getItem(J.SLOT),null);assert.equal(s.calls.some(c=>c.acao==='email_teste_v2'),false);});
