'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {parseHTML,DOMParser}=require('linkedom');
const files=['growth-templates-api.js','growth-message-preview.js','growth-control.js'];
function setup({brand='fish',channel='email',templates,capability={},native={},fetcher}={}){
 const {document,window}=parseHTML('<html><body><button id="opener">Abrir</button><div id="control-workflows"></div><div id="control-templates"></div></body></html>');
 const calls=[];let key='synthetic-key';const api={capabilities:{templates:{read_content:true},endpoints:{templates:'https://synthetic.invalid/templates'}},crm_operacao:{email_steps:[{key:brand+':cart',brand,piece:'carrinho-30min',flow_key:brand+':carrinho',template_id:'101',enabled:true,runtime_ready:true,checked_at:new Date().toISOString()}]}};
 const list=templates||[{id:'101',key:'catalog-key',brand,channel,components:channel==='email'?{subject:'Olá {{ .Tx.Data.first_name }}',body_html:'<!doctype html><html><body><p>{{ .Tx.Data.first_name }}</p></body></html>'}:[{type:'BODY',text:'Olá {{1}}',example:{body_text:[['PRIVATE-EXAMPLE']]}}]}];
 const fx=async(url,init={})=>{calls.push({url,init});if(fetcher)return fetcher(url,init);const action=init.body?JSON.parse(init.body).acao:new URL(url).searchParams.get('acao');let body=action==='listar'?{templates:list}:action==='email_capacidades'?{contract:'crm_email_native_preview_v1',policy_version:1,brands:['fish','aristo'],native_email_preview:true,...capability}:{contract:'crm_email_native_preview_v1',eligible:true,brand,subscriber_context:'synthetic',source_hash:'a'.repeat(64),subject:'Olá Exemplo',body_html:'<html><body><p>Exemplo</p><a href="https://synthetic.invalid/track">Link</a><img src="https://synthetic.invalid/pixel"></body></html>',...native};return {status:200,json:async()=>body};};
 const context=vm.createContext({document,window,DOMParser,URL,URLSearchParams,Date,Intl,AbortSignal,fetch:fx,GrowthAccess:{ready:()=>true,current:()=>key}});
 for(const file of files)vm.runInContext(fs.readFileSync(file,'utf8'),context);
 context.ctx={api,marca:brand,canal:channel};vm.runInContext('GC.previewContext=ctx;GC.caps=GTA.caps(ctx.api)',context);
 return {document,calls,api,run:s=>vm.runInContext(s,context),setKey:v=>{key=v;},preview:ref=>{context.ref=ref||{brand,channel,id:'101'};return vm.runInContext('GC.previewTemplate(ref,ctx)',context);}};
}
test('both brand email journeys expose exact template preview independently of period and editing state',()=>{
 for(const brand of ['fish','aristo']){const f=setup({brand});const html=f.run('GC.emailCatalog(ctx)+GC.emailInventory(ctx.api,ctx.marca,ctx.canal)');const {document}=parseHTML('<body>'+html+'</body>');const buttons=[...document.querySelectorAll('[data-template-preview]')];assert.equal(buttons.length,2);assert.ok(buttons.every(b=>b.dataset.previewBrand===brand&&b.dataset.previewId==='101'&&b.dataset.previewChannel==='email'));assert.equal(f.calls.length,0);}
});
test('published WA uses real components with fictitious variables, noninteractive buttons and no provider examples/media',async()=>{
 for(const brand of ['fish','aristo']){const f=setup({brand,channel:'whatsapp',templates:[{id:'101',brand,channel:'whatsapp',components:[{type:'BODY',text:'Olá *{{1}}*. Pedido {{order}}',example:{body_text:[['PRIVATE-NAME']]}},{type:'HEADER',format:'IMAGE',example:{header_handle:['https://synthetic.invalid/private']}},{type:'BUTTONS',buttons:[{type:'URL',text:'Acompanhar',url:'https://synthetic.invalid/token'},{type:'ORDER_DETAILS',text:'Pagar'}]}]}]});await f.preview();const box=f.document.querySelector('#message-preview-dialog');assert.match(box.textContent,/Exemplo 1/);assert.match(box.textContent,/Exemplo order/);assert.match(box.textContent,/Imagem do envio não carregada/);assert.doesNotMatch(box.innerHTML,/PRIVATE-NAME|https:\/\//);assert.equal(box.querySelectorAll('a,img,iframe').length,0);assert.equal(f.calls.length,1);assert.equal(f.calls[0].init.method,undefined);assert.match(f.calls[0].url,/marca=\w+&canal=whatsapp/);}
});
test('email native rendering needs only preview capability, never creates a draft or calls a send endpoint',async()=>{
 for(const brand of ['fish','aristo']){const f=setup({brand});await f.preview();assert.equal(f.calls.length,3);assert.equal(new URL(f.calls[0].url).searchParams.get('canal'),'email');const action=f.calls.map(c=>c.init.body?JSON.parse(c.init.body).acao:new URL(c.url).searchParams.get('acao'));assert.deepEqual(action,['listar','email_capacidades','email_previa']);assert.ok(f.calls.every(c=>c.init.headers.Authorization==='Bearer synthetic-key'));const sent=JSON.parse(f.calls[2].init.body);assert.equal(sent.rascunho.marca,brand);assert.equal(sent.rascunho.id,undefined);assert.equal(sent.rascunho.servidor,undefined);assert.equal(sent.k,undefined);const box=f.document.querySelector('#message-preview-dialog'),frame=box.querySelector('iframe');assert.ok(frame);assert.equal(frame.getAttribute('sandbox'),'');assert.match(frame.getAttribute('srcdoc'),/img-src &#39;none&#39;/);assert.doesNotMatch(frame.getAttribute('srcdoc'),/href=|src="https/);assert.equal(box.querySelector('[data-mp-images]'),null);assert.ok(box.querySelector('[title="Remetente e destinatário não fazem parte desta prévia."]'));}
});
test('static email shows exact source without synthetic shell, POST, external tracking or script',async()=>{
 const f=setup({templates:[{id:'101',brand:'fish',channel:'email',components:{subject:'Publicado',body_html:'<html><body><h1>Conteúdo real</h1><script>bad()</script><a href="https://synthetic.invalid/track" onclick="bad()">Abrir</a><img src="https://synthetic.invalid/pixel"><iframe src="https://synthetic.invalid/"></iframe></body></html>'}}]});await f.preview();assert.equal(f.calls.length,1);const html=f.document.querySelector('iframe').getAttribute('srcdoc');assert.match(html,/Conteúdo real/);assert.doesNotMatch(html,/<script|onclick|src="https|href="https|<iframe/);
});
test('missing/mismatched/ambiguous content and unavailable native capability never fabricate a preview',async()=>{
 for(const options of [{templates:[]},{templates:[{id:'101',brand:'aristo',channel:'email',components:{}}]},{templates:[{id:'101',brand:'fish',channel:'email'},{id:'101',brand:'fish',channel:'email'}]},{capability:{native_email_preview:false}},{native:{brand:'aristo'}},{native:{body_html:'<p>{{ unresolved }}</p>'}}]){const f=setup(options);await f.preview();assert.equal(f.document.querySelector('iframe'),null);assert.match(f.document.querySelector('[role=status]').textContent,/não|indisponível/i);assert.ok(f.calls.every(c=>!c.init.body||JSON.parse(c.init.body).acao==='email_previa'));}
});
test('brand or access changing during lookup discards the old response without POST',async()=>{
 for(const change of ['brand','key']){let resolve;const f=setup({fetcher:()=>new Promise(r=>resolve=r)}),pending=f.preview();if(change==='brand')f.run('GC.previewContext={...ctx,marca:"aristo"}');else f.setKey('rotated');resolve({status:200,json:async()=>({templates:[]})});await pending;assert.equal(f.calls.length,1);assert.equal(f.document.querySelector('iframe'),null);assert.match(f.document.querySelector('[role=status]').textContent,/marca ou o acesso mudou/);}
});
test('closing the read-only modal during lookup ignores a late response',async()=>{
 let resolve;const f=setup({fetcher:()=>new Promise(r=>resolve=r)}),pending=f.preview();f.document.querySelector('[data-mp-close]').click();resolve({status:200,json:async()=>({templates:[]})});await pending;assert.equal(f.document.querySelector('#message-preview-dialog'),null);assert.equal(f.calls.length,1);
});
test('missing capability leaves explicit unavailable guidance and makes zero network calls',async()=>{
 const f=setup();f.api.capabilities.templates.read_content=false;assert.match(f.run('GC.emailCatalog(ctx)'),/Prévia indisponível/);assert.doesNotMatch(f.run('GC.emailCatalog(ctx)'),/data-template-preview/);await f.preview();assert.equal(f.calls.length,0);assert.equal(f.document.querySelector('iframe'),null);
});
test('canvas inspector and fallback list preview the selected draft template without saving, sending or changing pending edits',async()=>{
 for(const visual of [false,true])for(const brand of ['fish','aristo'])for(const channel of ['email','whatsapp']){
  const components=channel==='email'?{subject:'Assunto real',body_html:'<html><body><p>Template selecionado</p></body></html>'}:[{type:'BODY',text:'Template selecionado {{1}}'}];
  const f=setup({brand,channel,templates:[{id:'202',brand,channel,components}]}),root=f.document.createElement('section');root.id='control-fluxos';f.document.body.append(root);
  f.run(fs.readFileSync('growth-builder.js','utf8'));if(visual)f.run(fs.readFileSync('growth-canvas.js','utf8'));
  f.run(`globalThis.slot={key:'step',name:'Mensagem',channel:${JSON.stringify(channel)},template_id:'101',template_name:'Original',wait_min:0,min_wait:0,max_wait:0,enabled:true,variables:[],signature:[]};globalThis.flow={key:${JSON.stringify(brand+':journey')},brand:${JSON.stringify(brand)},name:'Jornada',trigger:'Evento',version:1,published_version:1,runtime_ready:true,enabled:true,available_steps:[slot],draft:{name:'Jornada',steps:[slot]}};GB.ctx=ctx;GB.state={...GB.state,loaded:true,flows:[flow],selected:flow.key,baseVersion:1,dirty:true,pending:{request_payload:{id:'synthetic-pending'}},draft:{name:'Minha edição',steps:[{...slot,template_id:'202',template_name:'Selecionado'}]}};GB.journal=()=>null;${visual?"GBC.flowKey=flow.key;GBC.selected='step:step';GBC.minimap=()=>{};":''}globalThis.before=JSON.stringify({draft:GB.state.draft,pending:GB.state.pending,version:GB.state.baseVersion,dirty:GB.state.dirty});GB.render();`);
  const button=root.querySelector('[data-template-preview]');assert.ok(button);assert.equal(button.dataset.previewId,'202');assert.equal(button.dataset.previewBrand,brand);assert.equal(button.dataset.previewChannel,channel);assert.equal(button.disabled,false);assert.equal(!!button.closest('.flow-inspector'),visual);assert.match(root.textContent,/Seleção em rascunho/);
  await button.onclick();assert.equal(f.calls.length,1);assert.match(f.document.querySelector('#message-preview-dialog').textContent,/Seleção em rascunho/);assert.equal(f.run('JSON.stringify({draft:GB.state.draft,pending:GB.state.pending,version:GB.state.baseVersion,dirty:GB.state.dirty})'),f.run('before'));
 }
});
