const {test}=require('node:test'),assert=require('node:assert/strict'),GA=require('../growth-attribution');
const day='2026-09-15',family='semana-do-cliente-2026',utm={source:'listmonk',medium:'campanha',campaign:'aristo-semana-cliente',content:'cta',term:''};
function fixture(){const row=(grain,dimension,n=1)=>({marca:'aristo',dia:day,model:'last_non_direct',grain,dimension,pedidos:n,receita:n*100,assistidos:0});return {crm_familia_campanha:[{marca:'aristo',utm_campaign:utm.campaign,familia:family}],crm_conversao:[{marca:'aristo',dia:day,canal:'email',receita_ultimo:999}],crm_attribution:{schema_version:2,generated_at:day+'T14:00:00Z',coverage:[{brand:'aristo',day,checked_at:day+'T13:00:00Z'}],quality:[],daily:[row('family',[family]),row('family_channel',[family,'email']),row('total',['crm']),row('channel',['email']),row('piece',['email',utm.medium,utm.campaign,utm.content,'',utm.source])],campaigns:[{marca:'aristo',emissor:'aristo',canal:'email',campanha_id:127,nome:'Semana Cliente Mornos',familia:family,segmentos:['Mornos'],status:'running',enviados:700,utms:[utm],enviado_em:day+'T11:30:00Z'},{marca:'aristo',emissor:'aristo',canal:'email',campanha_id:126,nome:'Semana Cliente Quentes',familia:family,segmentos:['Quentes'],status:'scheduled',enviados:0,utms:[{...utm,content:'hero'}],agendado_em:day+'T21:00:00Z'}]}};}
test('initiative groups sends and scheduled bases while preserving one purchase',()=>{const [v]=GA.campaigns(fixture(),'aristo',day,day);assert.equal(v.members.length,2);assert.equal(v.sent,700);assert.equal(v.scheduled,1);assert.equal(v.pedidos,1);assert.equal(v.receita,100);assert.equal(v.members.find(m=>m.campanha_id===127).result.receita,100);assert.equal(v.members.find(m=>m.campanha_id===126).result,null);});
test('shared full UTM cannot allocate sale to a segment; initiative keeps one credit',()=>{const f=fixture();f.crm_attribution.campaigns.push({...f.crm_attribution.campaigns[0],campanha_id:128,segmentos:['Frios']});const [v]=GA.campaigns(f,'aristo',day,day);assert.equal(v.receita,100);assert.equal(v.shared,2);assert(v.members.filter(m=>!m.future).every(m=>m.result===null));});
test('different medium or source does not claim a purchase',()=>{for(const key of ['source','medium']){const f=fixture();f.crm_attribution.campaigns[0].utms=[{...utm,[key]:'different'}];assert.equal(GA.campaigns(f,'aristo',day,day)[0].members.find(m=>m.campanha_id===127).result.receita,0);}});
test('untagged sends remain visible with unknown revenue',()=>{const f=fixture();f.crm_attribution.campaigns[0].utms=null;const [v]=GA.campaigns(f,'aristo',day,day);assert.equal(v.sent,700);assert.equal(v.untracked,1);assert.equal(v.members.find(m=>m.campanha_id===127).result,null);});
test('purchase period and dispatch period differ explicitly',()=>{const f=fixture();f.crm_attribution.campaigns[0].enviado_em='2026-09-14T11:30:00Z';const [v]=GA.campaigns(f,'aristo',day,day);assert.equal(v.sent,0);assert.equal(v.receita,100);assert.equal(v.members.find(m=>m.campanha_id===127).in_period,false);});
test('cross promotion uses destination store for conversion and retains sender base',()=>{const f=fixture();f.crm_attribution.campaigns[0].emissor='fish';const [v]=GA.campaigns(f,'aristo',day,day);assert.equal(v.receita,100);assert.equal(v.members.find(m=>m.campanha_id===127).emissor,'fish');assert.equal(GA.campaigns(f,'fish',day,day).length,0);});
test('models project without retaining obsolete credit or accumulating on toggle',()=>{const f=fixture();GA.project(f);assert.equal(f.crm_conversao.length,1);assert.equal(f.crm_conversao[0].receita_ultimo,100);GA.project(f,'last_click');assert.equal(f.crm_conversao.length,0);GA.project(f);assert.equal(f.crm_conversao.length,1);assert.equal(GA.conversion(f,'aristo',day,day,'familia')[0].receita,100);});
test('channel filtering and campaign search honor real dimensions',()=>{const f=fixture();assert.equal(GA.campaigns(f,'aristo',day,day,'whatsapp').length,0);assert.equal(GA.campaigns(f,'aristo',day,day,'email','mornos').length,1);assert.equal(GA.campaigns(f,'aristo',day,day,'email','not present').length,0);});
test('coverage is per brand per day; rows absent from one brand cannot imply full coverage',()=>{const f=fixture();assert.equal(GA.coverage(f,'aristo',day,day).complete,true);assert.equal(GA.coverage(f,'todas',day,day).complete,false);assert.equal(GA.coverage(f,'aristo','2026-09-14',day).covered,1);});
test('family and channel credit come from independent order-deduplicated grains',()=>{const f=fixture();f.crm_attribution.daily.find(r=>r.grain==='family').assistidos=1;f.crm_attribution.daily.push({...f.crm_attribution.daily.find(r=>r.grain==='piece'),dimension:['whatsapp','campanha',utm.campaign,'wa','','whatsapp'],pedidos:0,receita:0,assistidos:3});const v=GA.conversion(f,'aristo',day,day,'familia')[0];assert.equal(v.assist,1);assert.equal(v.pedidos,1);});
test('exclusive links keep their revenue when the dispatch also has a shared coupon link',()=>{const f=fixture(),shared={...utm,content:'coupon'};f.crm_attribution.campaigns[0].utms.push(shared);f.crm_attribution.campaigns.push({...f.crm_attribution.campaigns[0],campanha_id:128,utms:[shared]});const [v]=GA.campaigns(f,'aristo',day,day);const m=v.members.find(m=>m.campanha_id===127);assert.equal(m.shared,true);assert.equal(m.result.receita,100);assert.equal(v.members.find(m=>m.campanha_id===128).result,null);});
test('automatic recovery flows remain in conversion data, outside the commercial initiative list',()=>{const f=fixture();f.crm_attribution.daily.push({marca:'aristo',dia:day,model:'last_non_direct',grain:'family',dimension:['workflow_123_carrinho'],pedidos:5,receita:500});assert.equal(GA.campaigns(f,'aristo',day,day).length,1);assert.equal(GA.conversion(f,'aristo',day,day,'familia').length,2);});
