'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const base=require('./fixtures/growth-control.json');
const D=require('../growth-diagnostic.js');
const now=Date.parse('2026-09-08T01:10:00Z');
const opts={brand:'aristo',ini:'2026-09-07',fim:'2026-09-08',now,receivedAt:'2026-09-08T01:10:00Z'};
function fixture(){const op=structuredClone(base);op.workflows.push({...structuredClone(op.workflows[3]),key:'motor',channel:'whatsapp'});return {crm_operacao:op,crm_wa_cobertura:{inicio:'2026-09-01',fim:'2026-09-08'},crm_wa_envios:[]};}
function row(changes={}){return {marca:'aristo',flow:'transacional',piece:'pedido-pago',dia:'2026-09-07',registros:1,aceitos:1,entregues:1,lidos:1,falhas:0,erros_sincronos:0,pendentes_entrega:0,sem_disparo_confirmado:0,conflitos_status:0,...changes};}
function live(p){p.crm_operacao.workflows.find(w=>w.key==='aristo_tx').modes[0].value='real';return p;}
test('sombra de pedido pago é separada de rastreio, estado ativo e entrega',()=>{const p=fixture();p.crm_operacao.workflows[1].modes[1].value='real';p.crm_wa_envios=[row()];const m=D.model(p,opts);assert.equal(m.configuration.state,'blocked');assert.equal(m.configuration.stages.transactional.mode,'sombra');assert.equal(m.history.counts.entregues,1);});
test('modo real, motor e Utility conferidos não garantem envio',()=>{const m=D.model(live(fixture()),opts);assert.equal(m.configuration.state,'configured');assert.match(m.configuration.label,/depende/);assert.equal(m.history.state,'empty');});
test('não usa modo de rastreio quando modo de pagamento falta',()=>{const p=live(fixture());p.crm_operacao.workflows[1].modes=[{key:'modo_rastreio',value:'real'}];assert.equal(D.model(p,opts).configuration.state,'unknown');});
test('configuração inativa, sem publicação e modo interno bloqueiam',()=>{for(const mutate of [w=>w.active=false,w=>w.published=false,w=>w.modes[0].value='interno']){const p=live(fixture());mutate(p.crm_operacao.workflows[1]);assert.equal(D.model(p,opts).configuration.state,'blocked');}});
test('alterações não publicadas não atestam o modo da versão ativa',()=>{const p=live(fixture());p.crm_operacao.workflows[1].has_unpublished_changes=true;const m=D.model(p,opts);assert.equal(m.configuration.state,'unknown');assert.equal(m.configuration.stages.transactional.mode,null);});
test('coleta vencida ou no futuro nunca atesta configuração',()=>{for(const time of [now+16*60000,now-10*60000])assert.equal(D.model(fixture(),{...opts,now:time}).configuration.state,'unknown');});
test('falha da última consulta mantém histórico mas retira certeza da configuração',()=>{const p=live(fixture());p.crm_wa_envios=[row()];const m=D.model(p,{...opts,readFailed:true});assert.equal(m.configuration.state,'unknown');assert.equal(m.read_failed,true);assert.equal(m.history.counts.entregues,1);});
test('coleta parcial R1 preserva configuração explícita sem confiar na execução',()=>{const p=live(fixture()),w=p.crm_operacao.workflows[1];w.config_collection={status:'ok',checked_at:w.checked_at,last_good_at:w.last_good_at};w.execution_collection={status:'error'};w.collection_status='error';w.last_retained_execution={status:'new',started_at:null};assert.equal(D.model(p,opts).configuration.state,'configured');});
test('coleta parcial inválida não usa status geral como atalho',()=>{for(const c of [null,{}, {status:'ok',checked_at:'invalid'}]){const p=live(fixture());p.crm_operacao.workflows[1].config_collection=c;assert.equal(D.model(p,opts).configuration.state,'unknown');}});
test('template rejeitado ou reclassificado não é elegível',()=>{for(const changes of [{status:'REJECTED'},{category:'MARKETING',expected_category:'MARKETING',category_matches_expected:true},{category:'MARKETING',category_matches_expected:false}]){const p=live(fixture());Object.assign(p.crm_operacao.templates[1],changes);assert.equal(D.model(p,opts).configuration.state,'blocked');}});
test('não usa cartão nativo pendente nem outro template como pagamento',()=>{const p=live(fixture());p.crm_operacao.templates[1].usage='native_pending';assert.equal(D.model(p,opts).configuration.state,'unknown');});
test('duplicatas e ausência de motor não são configuração comprovada',()=>{for(const modify of [p=>p.crm_operacao.workflows.push(structuredClone(p.crm_operacao.workflows[1])),p=>p.crm_operacao.workflows.pop(),p=>p.crm_operacao.templates.push(structuredClone(p.crm_operacao.templates[1]))]){const p=live(fixture());modify(p);assert.equal(D.model(p,opts).configuration.state,'unknown');}});
test('histórico isola marca, fluxo, peça e período; não soma leituras a entregas',()=>{const p=fixture();p.crm_wa_envios=[row(),row({marca:'fish'}),row({flow:'teste-motor'}),row({piece:'rastreio'}),row({dia:'2026-09-01'})];const m=D.model(p,opts);assert.equal(m.history.counts.aceitos,1);assert.equal(m.history.counts.entregues,1);assert.equal(m.history.counts.lidos,1);});
test('ausência ou cobertura parcial não vira zero',()=>{for(const c of [undefined,null,[],[{inicio:'2026-09-08',fim:'2026-09-08'}],[{inicio:'2026-09-01',fim:'2026-09-08'},{inicio:'2026-09-01',fim:'2026-09-08'}]]){const p=fixture();p.crm_wa_cobertura=c;assert.equal(D.model(p,opts).history.counts.aceitos,null);}});
test('campo ausente, negativo, decimal ou inválido não vira zero',()=>{for(const value of [undefined,null,'',-1,1.5,'err',true,Infinity]){const p=fixture();p.crm_wa_envios=[row({aceitos:value})];assert.equal(D.model(p,opts).history.counts.aceitos,null);}});
test('linhas malformadas não são descartadas silenciosamente como zero',()=>{for(const bad of [null,{},row({dia:'2026-02-30'})]){const p=fixture();p.crm_wa_envios=[bad];assert.equal(D.model(p,opts).history.counts.aceitos,null);}});
test('falhas têm prioridade e não são escondidas por outras entregas',()=>{const p=fixture();p.crm_wa_envios=[row(),row({aceitos:0,entregues:0,lidos:0,erros_sincronos:1})];const m=D.model(p,opts);assert.equal(m.history.state,'warning');assert.match(m.history.label,/falhas ou rejeições/);});
test('aceite sem entrega não é entregue',()=>{const p=fixture();p.crm_wa_envios=[row({entregues:0,lidos:0,pendentes_entrega:1})];assert.match(D.model(p,opts).history.label,/entrega ainda não confirmada/);});
test('registro sem aceite não vira envio',()=>{const p=fixture();p.crm_wa_envios=[row({aceitos:0,entregues:0,lidos:0,sem_disparo_confirmado:1})];assert.match(D.model(p,opts).history.label,/nenhum aceite/);});
test('contagens impossíveis e conflitos não geram sinal saudável',()=>{for(const changes of [{entregues:2},{lidos:2},{conflitos_status:1}]){const p=fixture();p.crm_wa_envios=[row(changes)];assert.match(D.model(p,opts).history.label,/conflitantes/);}});
test('overflow de soma não vira número confiável',()=>{const p=fixture();p.crm_wa_envios=[row({registros:Number.MAX_SAFE_INTEGER}),row()];assert.equal(D.model(p,opts).history.counts.registros,null);});
test('JSON exportável é whitelist sem chave, cliente, telefone, HTML ou IDs internos',()=>{const p=live(fixture());p.secret='DO_NOT_EXPORT';p.crm_wa_envios=[row({email:'DO_NOT_EXPORT',telefone:'DO_NOT_EXPORT',template_id:'DO_NOT_EXPORT'})];p.crm_operacao.workflows[1].label='<img src=x>';p.crm_operacao.workflows[1].version_id='DO_NOT_EXPORT';const text=JSON.stringify(D.model(p,opts));assert(!text.includes('DO_NOT_EXPORT'));assert(!text.includes('<img'));assert(!text.includes('version_id'));assert(!text.includes('"id"'));});
test('período inválido ou invertido é recusado; horário usa Brasília explicitamente',()=>{for(const o of [{ini:'2026-02-30'},{ini:'x'},{ini:'2026-09-09'}])assert.throws(()=>D.model(fixture(),{...opts,...o}),/invalid_period/);assert.equal(D.model(fixture(),opts).period.time_zone,'America/Sao_Paulo');});
test('não altera payload original e marca desconhecida não injeta conteúdo',()=>{const p=fixture(),before=JSON.stringify(p);const m=D.model(p,{...opts,brand:'<script>'});assert.equal(m.brand,'aristo');assert.equal(JSON.stringify(p),before);});
