'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {parseHTML}=require('linkedom'),Audience=require('../growth-audience.js');
function fixture(){const {document,window}=parseHTML('<main></main>'),element=document.querySelector('main'),ui=Audience.mount({element});return {ui,element,window,summary:()=>element.querySelector('[data-ga-summary]').textContent,result:()=>element.querySelector('[data-ga-result]').textContent};}
const rule={marca:'fish',galho:'ativos',rotulo:'Ativos'};
test('absent identities and measurements alone never claim zero loaded audiences',()=>{for(const api of [{},{crm_base:null,crm_regra_galho:null},{crm_galho:[{marca:'fish',galho:'ativos',dia:'2026-10-06',pessoas:0}]}]){const f=fixture();f.ui.update({api,brand:'fish'});assert.match(f.summary(),/Quantidade de públicos indisponível/);assert.doesNotMatch(f.summary(),/0 de 0/);assert.match(f.result(),/fonte está ausente ou incompleta/);}});
test('explicit empty identity arrays prove loaded empty without inventing people',()=>{for(const api of [{crm_base:[]},{crm_regra_galho:[]},{crm_base:[],crm_regra_galho:[]}]){const f=fixture();assert.deepEqual(f.ui.update({api,brand:'fish'}),{total:0,visible:0,unknown:0});assert.equal(f.summary(),'0 de 0 públicos carregados');assert.doesNotMatch(f.result(),/fonte está ausente/);}});
test('malformed or wholly invalid identities override an otherwise empty array',()=>{for(const api of [{crm_base:{},crm_regra_galho:[]},{crm_base:[],crm_regra_galho:'unavailable'},{crm_regra_galho:[{marca:'unknown',galho:'a'}]},{crm_regra_galho:[{marca:'fish',galho:''}]}]){const f=fixture();f.ui.update({api,brand:'fish'});assert.match(f.summary(),/Quantidade de públicos indisponível/);assert.doesNotMatch(f.summary(),/0 de 0/);}});
test('valid identities stay visible during a partial query and filtering remains explicit',()=>{const f=fixture();f.ui.update({api:{crm_base:{},crm_regra_galho:[rule]},brand:'fish'});assert.match(f.summary(),/Quantidade de públicos indisponível · 1 público exibido · 1 sem contagem/);assert.match(f.result(),/Ativos/);const search=f.element.querySelector('[data-ga-search]');search.value='inexistente';search.dispatchEvent(new f.window.Event('input'));assert.match(f.summary(),/Quantidade de públicos indisponível · 0 públicos exibidos/);assert.match(f.result(),/Nenhum público corresponde à busca/);search.value='';search.dispatchEvent(new f.window.Event('input'));assert.match(f.result(),/Ativos/);});
test('valid records from another brand prove a loaded empty selected-brand cut',()=>{const f=fixture();f.ui.update({api:{crm_regra_galho:[{...rule,marca:'aristo'}]},brand:'fish'});assert.equal(f.summary(),'0 de 0 públicos carregados');assert.equal(f.element.querySelectorAll('[data-ga-row]').length,0);});
test('catalog identities prove emptiness only when a current source declares its lists',()=>{for(const catalogs of [[],[{brand:'fish',current:false,lists:[]}],[{brand:'fish',current:true}],[{brand:'fish',current:true,lists:{}}],[{brand:'fish',current:true,lists:[{brand:'aristo',id:1,available:true}]}]]){const f=fixture();f.ui.update({api:{},catalogs,brand:'fish'});assert.match(f.summary(),/Quantidade de públicos indisponível/);}const f=fixture();f.ui.update({api:{},catalogs:[{brand:'fish',current:true,lists:[]}],brand:'fish'});assert.equal(f.summary(),'0 de 0 públicos carregados');});
test('zero people remains zero and missing people remains unknown for loaded identities',()=>{const f=fixture();f.ui.update({api:{crm_regra_galho:[rule,{...rule,galho:'sem-contagem'}],crm_galho:[{marca:'fish',galho:'ativos',dia:'2026-10-06',pessoas:0}]},brand:'fish'});assert.equal(f.summary(),'2 de 2 públicos carregados · 1 sem contagem');assert.match(f.element.querySelector('tbody tr .ga-count').textContent,/^0$/);assert.match(f.result(),/Sem contagem/);});
