'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{Blob,File}=require('node:buffer'),{parseHTML}=require('linkedom'),M=require('../growth-media.js');
const url='https://cdn.shopify.com/s/files/1/123/files/example.jpg?v=123';
test('public image links permit known HTTPS image hosts and reject credentials, temporary links and executable or unrelated content',()=>{
 assert.equal(M.publicImage(url).host,'Shopify');assert.equal(M.publicImage('https://email.shrigma.com.br/uploads/image.png').host,'Listmonk');
 for(const value of ['http://cdn.shopify.com/s/files/a.jpg','https://cdn.shopify.com.evil.test/s/files/a.jpg','https://secret@cdn.shopify.com/s/files/a.jpg','https://cdn.shopify.com:444/s/files/a.jpg',url+'#secret',url+'&token=secret','https://email.shrigma.com.br/admin/a.jpg','https://email.shrigma.com.br/uploads/a.svg','https://cdn.shopify.com/s/files/a.html','javascript:alert(1)','data:image/png;base64,abc','https://example.test/x.jpg','https://cdn.shopify.com/s/files/a.jpg?X-Amz-Signature=x','https://cdn.shopify.com/s/files/a.jpg\n',null])assert.equal(M.publicImage(value),null,String(value));
 assert.match(M.snippet(url,'" onerror="bad <script>'),/alt="&quot; onerror=&quot;bad &lt;script&gt;"/);assert.doesNotMatch(M.snippet(url,'teste'),/<script|onload=/);
});
function memory(){const values=new Map;return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),values};}
const capabilities={capabilities:{campaigns:{contract_version:'crm-campaign-v1',read:true,brands:['fish','aristo']},endpoints:{campaigns:'https://campaign.example/webhook/campaigns'}}};
function boot(options={}){const {document,window}=parseHTML('<html><body><section id="crm-media"></section></body></html>'),copies=[],store=options.storage||memory(),locks=options.locks||{request:async(_name,_opts,fn)=>fn({})},context=vm.createContext({document,window,URL,URLSearchParams,Blob,File,FormData,AbortSignal,TextEncoder,crypto:globalThis.crypto,confirm:options.confirm||(()=>true),navigator:{locks,clipboard:{writeText:async x=>copies.push(x)}},sessionStorage:store,fetch:options.fetch||(()=>assert.fail('No transport in image preparation'))});vm.runInContext(fs.readFileSync(path.join(__dirname,'../growth-media.js'),'utf8'),context);const api=vm.runInContext('GMedia',context);api.mount({marca:'fish',api:options.api,storage:store,locks,fetch:context.fetch,readKey:()=>options.readKey||'read-key',writeKey:()=>options.writeKey||'edit-key',uuid:()=>options.uuid||'11111111-1111-4111-8111-111111111111',digest:options.digest,createObjectURL:()=>"blob:preview"});return {document,window,api,copies,store,q:s=>document.querySelector(s)};}
test('brand changes preserve local fields separately without attaching a prior image or URL to the new brand',()=>{
 const x=boot(),field=x.q('#crm-media-url');field.value=url;x.q('#crm-media-alt').value='Peixe';field.dispatchEvent(new x.window.Event('input'));assert.equal(x.q('#crm-media-copy-html').disabled,false);x.api.mount({marca:'aristo'});assert.equal(field.value,'');assert.equal(x.q('#crm-media-copy-html').disabled,true);assert.match(x.q('#crm-media-brand').textContent,/O Aristocrata/);
 field.value='https://email.shrigma.com.br/uploads/aristo.png';x.api.mount({marca:'fish'});assert.equal(field.value,url);assert.equal(x.q('#crm-media-alt').value,'Peixe');x.api.mount({marca:'todas'});assert.equal(x.q('#crm-media-fields').disabled,true);assert.equal(field.value,'');assert.equal(x.copies.length,0);
});
test('copy generates escaped HTML and does not upload, save or send any message; preview is opt-in',async()=>{
 const x=boot();x.q('#crm-media-url').value=url;x.q('#crm-media-alt').value='<promoção>';x.q('#crm-media-url').dispatchEvent(new x.window.Event('input'));assert.equal(x.q('img'),null);x.q('#crm-media-copy-html').click();await new Promise(r=>setImmediate(r));assert.equal(x.copies.length,1);assert.match(x.copies[0],/alt="&lt;promoção&gt;"/);assert.equal(x.q('#crm-media-output').value,x.copies[0]);
 x.q('#crm-media-preview').click();const image=x.q('#crm-media-picture img');assert.ok(image);assert.equal(image.referrerPolicy,'no-referrer');assert.equal(image.crossOrigin,undefined,'public Listmonk images do not advertise CORS; a normal image preview must not require it');x.api.mount({marca:'aristo'});image.onload();assert.equal(x.q('#crm-media-status').textContent,'');assert.equal(x.q('img'),null);
 for(const a of x.document.querySelectorAll('a[target="_blank"]'))assert.equal(a.getAttribute('rel'),'noopener noreferrer');assert.match(x.q('#crm-media').textContent,/Links públicos existentes continuam disponíveis/);
});
test('image preparation belongs to Templates and remains available to the CRM manager',()=>{
 const {document}=parseHTML(fs.readFileSync(path.join(__dirname,'../growth.html'),'utf8'));assert.equal(document.querySelector('#crm-media').closest('.sec').id,'sec-templates');assert.equal(document.querySelector('#crm-media').closest('[data-crm-owner-only]'),null);
});

function png(width=2,height=3){const b=Buffer.alloc(45);Buffer.from([137,80,78,71,13,10,26,10]).copy(b);b.writeUInt32BE(13,8);b.write('IHDR',12);b.writeUInt32BE(width,16);b.writeUInt32BE(height,20);b[24]=8;b[25]=2;b.writeUInt32BE(0,33);b.write('IEND',37);return b;}
const media=(filename='crm-fish-11111111-1111-4111-8111-111111111111-'+('a'.repeat(64))+'.png',id=1)=>({id,filename,url:'https://email.shrigma.com.br/uploads/'+filename,thumb_url:null,content_type:'image/png',width:2,height:3,created_at:'2026-09-30T10:00:00Z'});
const tick=()=>new Promise(resolve=>setImmediate(resolve));

test('library is lazy, filters behind service availability and selects a paginated Listmonk image',async()=>{
 const calls=[],second=media('crm-fish-22222222-2222-4222-8222-222222222222-'+('c'.repeat(64))+'.png',2),x=boot({api:capabilities,fetch:async(url,init)=>{calls.push({url,init});const page=Number(new URL(url).searchParams.get('page'));return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[page===1?media():second],total:25,page,per_page:24,next_page:page===1?2:null}),{status:200});}});assert.equal(calls.length,0,'mount does not probe the service');
 x.q('#crm-media-library-load').click();await tick();assert.equal(calls.length,1);assert.match(calls[0].url,/\/media\?brand=fish&page=1&per_page=24$/);assert.equal(calls[0].init.headers.Authorization,'Bearer read-key');assert.equal(x.q('#crm-media-upload-fields').hidden,false);
 const entry=x.q('[data-media-index="0"]');assert.ok(entry);entry.click();assert.equal(x.q('#crm-media-url').value,media().url);assert.equal(x.q('#crm-media-next').hidden,false);
 x.q('#crm-media-next').click();await tick();assert.equal(calls.length,2);assert.match(calls[1].url,/page=2/);assert.equal(x.document.querySelectorAll('[data-media-index]').length,2);assert.equal(x.q('#crm-media-next').hidden,true);
});

test('choosing and uploading a valid file performs one POST, stores identity before transport and yields copyable URL/HTML',async()=>{
 const sha='a'.repeat(64),name='crm-fish-11111111-1111-4111-8111-111111111111-'+sha+'.png',calls=[],store=memory(),x=boot({api:capabilities,storage:store,digest:async()=>sha,fetch:async(url,init)=>{calls.push({url,init,journal:store.getItem('shrigma_media_upload_v1:fish')});if(init.method==='POST')return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',state:'created',operation_id:'11111111-1111-4111-8111-111111111111',filename:name,sha256:sha,media:media(name)}),{status:201});return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[],total:0,page:1,per_page:24,next_page:null}),{status:200});}});
 x.q('#crm-media-library-load').click();await tick();const file=new File([png()],'private-customer-name.png',{type:'image/png'});Object.defineProperty(x.q('#crm-media-file'),'files',{configurable:true,value:[file]});x.q('#crm-media-file').dispatchEvent(new x.window.Event('change'));await tick();assert.match(x.q('#crm-media-library-status').textContent,/Arquivo pronto/);assert.equal(x.q('#crm-media-upload').disabled,false);
 x.q('#crm-media-upload').click();await tick();await tick();const posts=calls.filter(c=>c.init.method==='POST');assert.equal(posts.length,1);assert.ok(posts[0].journal?.includes('"phase":"pending"'));assert.equal(posts[0].init.headers.Authorization,'Bearer edit-key');assert.doesNotMatch(posts[0].journal,/private-customer-name/);assert.equal(x.q('#crm-media-url').value,media(name).url);x.q('#crm-media-copy-html').click();await tick();assert.match(x.copies[0],new RegExp(name));assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'confirmed');
});

test('lost upload response never auto-posts; exact GET marks missing and only explicit warned retry posts again',async()=>{
 const sha='b'.repeat(64),name='crm-fish-11111111-1111-4111-8111-111111111111-'+sha+'.png',calls=[],store=memory(),x=boot({api:capabilities,storage:store,digest:async()=>sha,fetch:async(url,init)=>{calls.push({url,method:init.method});if(init.method==='POST'&&calls.filter(c=>c.method==='POST').length===1)throw Error('lost');if(init.method==='POST')return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',state:'created',operation_id:'11111111-1111-4111-8111-111111111111',filename:name,sha256:sha,media:media(name)}),{status:201});if(url.includes('operation_id='))return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',state:'missing',operation_id:'11111111-1111-4111-8111-111111111111',filename:name,sha256:sha,media:null}),{status:200});return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[],total:0,page:1,per_page:24,next_page:null}),{status:200});}});
 x.q('#crm-media-library-load').click();await tick();const file=new File([png()],'not-exposed.png',{type:'image/png'});Object.defineProperty(x.q('#crm-media-file'),'files',{configurable:true,value:[file]});x.q('#crm-media-file').dispatchEvent(new x.window.Event('change'));await tick();x.q('#crm-media-upload').click();await tick();await tick();assert.equal(calls.filter(c=>c.method==='POST').length,1);assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'uncertain');assert.equal(x.q('#crm-media-recover').hidden,false);
 x.q('#crm-media-recover').click();await tick();assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'missing');assert.equal(calls.filter(c=>c.method==='POST').length,1);assert.equal(x.q('#crm-media-retry').hidden,false);x.q('#crm-media-retry').click();await tick();await tick();assert.equal(calls.filter(c=>c.method==='POST').length,2);assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'confirmed');
});

test('recovery never opens manual retry from a missing response with different operation identity',async()=>{
 const sha='9'.repeat(64),name='crm-fish-11111111-1111-4111-8111-111111111111-'+sha+'.png',store=memory();store.setItem('shrigma_media_upload_v1:fish',JSON.stringify({version:1,brand:'fish',endpoint:'https://campaign.example/webhook/campaigns/media',operation_id:'11111111-1111-4111-8111-111111111111',sha256:sha,filename:name,phase:'uncertain'}));const x=boot({api:capabilities,storage:store,fetch:async()=>new Response(JSON.stringify({contract:'crm-media-v1',brand:'aristo',state:'missing',operation_id:'11111111-1111-4111-8111-111111111111',filename:name,sha256:sha,media:null}),{status:200})});x.q('#crm-media-recover').click();await tick();assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'uncertain');assert.equal(x.q('#crm-media-retry').hidden,true);assert.match(x.q('#crm-media-library-status').textContent,/não confirmou/);
});

test('a late upload result stays with its original brand and never overwrites the newly selected brand',async()=>{
 const sha='d'.repeat(64),name='crm-fish-11111111-1111-4111-8111-111111111111-'+sha+'.png',store=memory();let finish;
 const x=boot({api:capabilities,storage:store,digest:async()=>sha,fetch:async(url,init)=>{if(init.method==='POST')return await new Promise(resolve=>{finish=resolve;});return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[],total:0,page:1,per_page:24,next_page:null}),{status:200});}});
 x.q('#crm-media-library-load').click();await tick();const file=new File([png()],'private.png',{type:'image/png'});Object.defineProperty(x.q('#crm-media-file'),'files',{configurable:true,value:[file]});x.q('#crm-media-file').dispatchEvent(new x.window.Event('change'));await tick();x.q('#crm-media-upload').click();await tick();assert.equal(typeof finish,'function');
 x.api.mount({marca:'aristo'});assert.equal(x.q('#crm-media-url').value,'');finish(new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',state:'created',operation_id:'11111111-1111-4111-8111-111111111111',filename:name,sha256:sha,media:media(name)}),{status:201}));await tick();await tick();assert.equal(x.q('#crm-media-url').value,'');assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'confirmed');
 x.api.mount({marca:'fish'});assert.equal(x.q('#crm-media-library-load').disabled,false,'the original brand does not remain busy after its response');
});

test('switching brands while waiting for the cross-tab lock aborts before journal or POST',async()=>{
 let enter,posts=0;const locks={request:async(_name,_opts,fn)=>new Promise(resolve=>{enter=async()=>resolve(await fn({}));})},store=memory(),x=boot({api:capabilities,storage:store,locks,digest:async()=>('f'.repeat(64)),fetch:async(_url,init)=>{if(init.method==='POST')posts++;return new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[],total:0,page:1,per_page:24,next_page:null}),{status:200});}});x.q('#crm-media-library-load').click();await tick();const file=new File([png()],'private.png',{type:'image/png'});Object.defineProperty(x.q('#crm-media-file'),'files',{configurable:true,value:[file]});x.q('#crm-media-file').dispatchEvent(new x.window.Event('change'));await tick();x.q('#crm-media-upload').click();await tick();assert.equal(typeof enter,'function');x.api.mount({marca:'aristo'});await enter();await tick();assert.equal(posts,0);assert.equal(store.getItem('shrigma_media_upload_v1:fish'),null);assert.equal(store.getItem('shrigma_media_upload_v1:aristo'),null);
});

test('a deterministic pre-upload refusal is recorded as rejected rather than an uncertain native outcome',async()=>{
 const sha='e'.repeat(64),store=memory(),x=boot({api:capabilities,storage:store,digest:async()=>sha,fetch:async(_url,init)=>init.method==='POST'?new Response(JSON.stringify({error:'MEDIA_ACTOR_CHANGED',message:'O acesso mudou.',posted:false}),{status:409}):new Response(JSON.stringify({contract:'crm-media-v1',brand:'fish',items:[],total:0,page:1,per_page:24,next_page:null}),{status:200})});x.q('#crm-media-library-load').click();await tick();const file=new File([png()],'private.png',{type:'image/png'});Object.defineProperty(x.q('#crm-media-file'),'files',{configurable:true,value:[file]});x.q('#crm-media-file').dispatchEvent(new x.window.Event('change'));await tick();x.q('#crm-media-upload').click();await tick();await tick();assert.equal(JSON.parse(store.getItem('shrigma_media_upload_v1:fish')).phase,'rejected');assert.match(x.q('#crm-media-library-status').textContent,/acesso mudou/i);assert.equal(x.q('#crm-media-recover').hidden,true);
});
