'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,id}=require('./journey-graph-source-fixture.cjs'),{createSourceAdapter,mapItems}=require('../n8n/growth/journey-graph-source.cjs'),{patchCollector,makeBatches,graphMoney,patchNormalizer}=require('../n8n/growth/journey-graph-source-workflow.cjs');
const fixture=fn=>async()=>{const x=await setup();try{await fn(x);}finally{await x.db.close();}};
test('captures exact cart event once and maps only real typed material for both brands',fixture(async x=>{
 for(const [brand,n]of [['fish',100],['aristo',101]]){const r=await x.receipt(brand,id(n)),a=await x.api.capture(r),b=await x.api.capture(r);assert.deepEqual(a,b);const p=await x.read(a.source_refs[0],brand);assert.equal(p.subject_id,id(1));assert.equal(p.eligible,true);assert.equal(p.consent,true);assert.equal(p.suppressed,false);assert.equal(p.facts['cart.total'].value,'R$ 24,60');assert.equal(p.facts['cart.items'].value[0].quantity,2);assert.equal(p.facts['purchase.confirmed'],undefined);assert.equal(p.facts['cart.total'].observed_at,x.now);assert.ok(!JSON.stringify(a).includes('Synthetic'));}
 assert.equal((await x.query('SELECT count(*)::int n FROM crm_graph_candidate.source_event_v1')).rows[0].n,2);
}));
test('receipt identity, brand, source change and missing reconciliation fail without partial capture',fixture(async x=>{
 const r=await x.receipt();await assert.rejects(x.api.capture({...r,reconciled:false}),/RECEIPT/);await x.api.capture(r);await assert.rejects(x.api.capture({...r,brand:'aristo'}),/REPLAY/);
 await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,cart_id}','\"changed\"')");await assert.rejects(x.api.capture({...r,receipt_id:id(102)}),/SOURCE_CHANGED/);assert.equal((await x.query('SELECT count(*)::int n FROM crm_graph_candidate.source_batch_v1')).rows[0].n,1);
}));
test('blocklist, brand opt-out, missing membership and superseded cart stop eligibility',fixture(async x=>{
 const ref=await x.capture();await x.query("UPDATE subscribers SET status='blocklisted'");assert.equal((await x.read(ref)).consent,false);await x.query("UPDATE subscribers SET status='enabled'");await x.query("UPDATE subscriber_lists SET status='unsubscribed' WHERE list_id=17");assert.equal((await x.read(ref)).consent,false);assert.equal((await x.read(await x.capture('aristo',id(101)),'aristo')).consent,true);
 await x.query("UPDATE subscriber_lists SET status='confirmed' WHERE list_id=17");await x.query('DELETE FROM subscriber_lists WHERE list_id=22');assert.equal((await x.read(ref)).consent,false);await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,cart_id}','\"next-cart\"')");assert.equal((await x.read(ref)).eligible,false);
}));
test('purchase positive is monotonic evidence; missing malformed and old markers never become No',fixture(async x=>{
 const ref=await x.capture(),before=await x.read(ref);for(const marker of ['', 'malformed',new Date(Date.parse(x.ref)-1).toISOString()]){await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,last_order_at}',$1::jsonb)",[JSON.stringify(marker)]);assert.equal((await x.read(ref)).facts['purchase.confirmed'],undefined);}
 await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,last_order_at}',$1::jsonb)",[JSON.stringify(x.ref)]);const after=await x.read(ref);assert.equal(after.facts['purchase.confirmed'].value,true);assert.equal(after.source_revision,before.source_revision);
}));
test('legacy reservations including uncertain and historical send flags suppress without replay',fixture(async x=>{
 const ref=await x.capture();const key=JSON.stringify(['email',x.ref,1,false]).replaceAll(',',', ');await x.query("INSERT INTO shrigma_email_dispatch VALUES($1,'fish','carrinho','carrinho-30min',$2,false,'outcome_unknown')",[id(200),key]);assert.equal((await x.read(ref)).suppressed,true);
 await x.query('DELETE FROM shrigma_email_dispatch');await x.query("INSERT INTO shrigma_send_log VALUES(1,'fish','carrinho','carrinho-1h','email',1,$1)",[x.ref]);assert.equal((await x.read(ref)).suppressed,true);await x.query('DELETE FROM shrigma_send_log');await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,flows}','{\"cart_t05_at\":\"synthetic\"}')");assert.equal((await x.read(ref)).suppressed,true);
}));
test('current SQL read never freshens stale or changed collector material',fixture(async x=>{
 const ref=await x.capture();await x.query("UPDATE crm_graph_candidate.source_observation_v1 SET observed_at=observed_at-interval '10 minutes'");const p=await x.read(ref);assert.ok(Date.parse(p.observed_at)-Date.parse(p.facts['cart.total'].observed_at)>590000);
 await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,cart_value}','30')");assert.equal((await x.read(ref)).facts['cart.total'],undefined);
}));
test('negative purchase requires exhaustive subject-bound interval proof; positive native dominates',fixture(async x=>{
 const ref=await x.capture();let valid=false;
 const api=createSourceAdapter({query:x.query,purchaseFor:async a=>({...a,version:'journey_purchase_evidence_v1',complete:valid,purchased:false,covered_from:a.occurred_at,covered_through:a.now,observed_at:a.now})});assert.equal((await x.read(ref,'fish',api)).facts['purchase.confirmed'],undefined);valid=true;assert.equal((await x.read(ref,'fish',api)).facts['purchase.confirmed'].value,false);
 await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,last_order_at}',$1::jsonb)",[JSON.stringify(x.ref)]);assert.equal((await x.read(ref,'fish',api)).facts['purchase.confirmed'].value,true);
}));
test('immutable source/replay and install collision are refused; native rows unchanged',fixture(async x=>{
 const ref=await x.capture();await assert.rejects(x.query("UPDATE crm_graph_candidate.source_event_v1 SET brand='aristo' WHERE id=$1",[ref]),/immutable/i);await assert.rejects(x.db.exec(fs.readFileSync(path.join(__dirname,'../n8n/growth/journey-graph-source.sql'),'utf8')),/COLLISION/);await x.db.exec('ROLLBACK');assert.equal((await x.query('SELECT count(*)::int n FROM subscribers')).rows[0].n,1);
}));
test('workflow receipts wait for reconciliation, bind execution/brand, and capture durably via allowlisted handoff',fixture(async x=>{
 const r=await x.receipt(),counts=Object.fromEntries(['compradores_add','leads_removidos','leads_add','carrinho_add','carrinho_removidos','flags_sincronizados'].map(k=>[k,0]));const batches=makeBatches([{graph_source_items:r.items,carrinhos_gravados:1,graph_persisted_at:x.now}],[counts],{brand:'fish',executionId:'123',workflowId:'syntheticFish',observedAt:x.now});assert.equal(batches.length,1);const a=await x.api.captureHandoff(batches[0]);assert.deepEqual(await x.api.captureHandoff(batches[0]),a);await assert.rejects(x.api.captureHandoff({...batches[0],workflow_id:'syntheticOther'}),/HANDOFF/);assert.throws(()=>makeBatches([],[],{brand:'fish',executionId:'123',workflowId:'syntheticFish',observedAt:x.now}),/RECONCILIATION/);
}));
test('pure collector patch preserves connections and transport absence; mapper does not invent fields',()=>{
 const query=fs.readFileSync(path.join(__dirname,'sql/journey-collector-fixture.sql'),'utf8');const w={id:'syntheticFish',versionId:'version',nodes:[{name:'Config',parameters:{assignments:{assignments:[{name:'brand',value:'fish'},{name:'list_base',value:17},{name:'list_carrinho',value:22}]}}},{name:'Upsert Carrinhos (Listmonk PG)',type:'n8n-nodes-base.postgres',parameters:{query}},{name:'Reconciliação 4 Listas (PG)',type:'n8n-nodes-base.postgres',parameters:{query:'SELECT 0 AS flags_sincronizados'}},{name:'Normalizar Carrinhos',type:'n8n-nodes-base.code',parameters:{jsCode:'const preco=Number(e.node.originalUnitPriceSet?.shopMoney?.amount || 0);const total=Number(n.totalPriceSet?.shopMoney?.amount || 0);'}}],connections:{'Upsert Carrinhos (Listmonk PG)':{main:[[{node:'Reconciliação 4 Listas (PG)'}]]},'Reconciliação 4 Listas (PG)':{main:[[{node:'Resumo'}]]}}};const p=patchCollector(w,{expectedVersion:'version',brand:'fish'});assert.equal(p.connections['Reconciliação 4 Listas (PG)'].main[0][0].node,'Resumo');assert.equal(p.nodes.length,w.nodes.length+1);assert.ok(p.nodes[1].parameters.query.includes('graph_source_items'));assert.deepEqual(mapItems([{title:'Only title'}]),[{name:'Only title',title:'Only title'}]);assert.equal(mapItems([{foo:'unknown'}]),null);assert.throws(()=>patchCollector(w,{expectedVersion:'changed',brand:'fish'}),/VERSION/);
});
test('real source adapter drives runtime to unknown wait, then purchase exit without an email intent',fixture(async x=>{
 const {createGraphRuntime}=require('../n8n/growth/journey-graph-runtime.cjs');let at=x.now,seq=400;
 const catalog={version:'journey_graph_v1',brand:'fish',triggers:[{key:'cart.abandoned',brand:'fish',available:true,fields:['purchase.confirmed']}],fields:[{key:'purchase.confirmed',type:'boolean',available:true,max_age_seconds:300}],messages:[{key:'cart.email',brand:'fish',channel:'email',available:true,release:'synthetic-pinned-release',required_fields:[]}]};
 const definition={version:'journey_graph_v1',brand:'fish',name:'Synthetic source integration',nodes:[{id:'start',type:'trigger',event:'cart.abandoned'},{id:'wait',type:'wait',seconds:1},{id:'paid',type:'condition',expression:{field:'purchase.confirmed',op:'eq',value:true},on_unknown:{max_wait_seconds:60,retry_seconds:1}},{id:'email',type:'message',binding:'cart.email'},{id:'end',type:'exit',reason:'finished'}],edges:[{from:'start',to:'wait',port:'next'},{from:'wait',to:'paid',port:'next'},{from:'paid',to:'end',port:'yes'},{from:'paid',to:'email',port:'no'},{from:'email',to:'end',port:'next'}]};
 const api=createGraphRuntime({pool:{connect:async()=>({query:x.query,release(){}})},catalogFor:async()=>catalog,readSource:x.api.readSource,clock:()=>at});const req=p=>({request_id:id(seq++),actor:'synthetic',brand:'fish',...p});
 let j=await api.create(req({definition}));j=await api.publish(req({journey_id:j.journey_id,expected_version:j.version,confirm:'publicar'}));await x.query('UPDATE crm_graph_candidate.control SET enabled=true');j=await api.pause(req({journey_id:j.journey_id,expected_version:j.version,paused:false,confirm:'retomar'}));
 let e=await api.enroll(req({journey_id:j.journey_id,expected_version:j.version,source_ref:await x.capture()}));e=await api.step(req({entry_id:e.entry_id,expected_version:e.version}));at=new Date(Date.parse(at)+1000).toISOString();e=await api.step(req({entry_id:e.entry_id,expected_version:e.version}));e=await api.step(req({entry_id:e.entry_id,expected_version:e.version}));assert.equal(e.kind,'wait_data');assert.equal((await x.query('SELECT count(*)::int n FROM crm_graph_candidate.intent')).rows[0].n,0);
 await x.query("UPDATE subscribers SET attribs=jsonb_set(attribs,'{fish,last_order_at}',$1::jsonb)",[JSON.stringify(x.ref)]);at=new Date(Date.parse(at)+1000).toISOString();e=await api.step(req({entry_id:e.entry_id,expected_version:e.version}));assert.equal(e.kind,'advance');assert.equal(e.node_id,'end');assert.equal((await x.query('SELECT count(*)::int n FROM crm_graph_candidate.intent')).rows[0].n,0);
}));

test('collector does not freshen a newer stored cart when Shopify input contained only an older event',fixture(async x=>{
 await x.db.exec("CREATE SEQUENCE source_fixture_ids START 10;ALTER TABLE subscribers ALTER COLUMN id SET DEFAULT nextval('source_fixture_ids');ALTER TABLE subscribers ADD UNIQUE(email);ALTER TABLE subscribers ADD COLUMN name text;ALTER TABLE subscribers ADD COLUMN created_at timestamptz;ALTER TABLE subscribers ADD COLUMN updated_at timestamptz;ALTER TABLE subscriber_lists ADD COLUMN meta jsonb;ALTER TABLE subscriber_lists ADD COLUMN created_at timestamptz;ALTER TABLE subscriber_lists ADD COLUMN updated_at timestamptz;");
 const query=fs.readFileSync(path.join(__dirname,'sql/journey-collector-fixture.sql'),'utf8'),w={versionId:'v',nodes:[{name:'Config',parameters:{assignments:{assignments:[{name:'brand',value:'fish'},{name:'list_base',value:17},{name:'list_carrinho',value:22}]}}},{name:'Upsert Carrinhos (Listmonk PG)',type:'n8n-nodes-base.postgres',parameters:{query}},{name:'Reconciliação 4 Listas (PG)',type:'n8n-nodes-base.postgres',parameters:{query:'SELECT 0 AS flags_sincronizados'}},{name:'Normalizar Carrinhos',type:'n8n-nodes-base.code',parameters:{jsCode:'const preco=Number(e.node.originalUnitPriceSet?.shopMoney?.amount || 0);const total=Number(n.totalPriceSet?.shopMoney?.amount || 0);'}}],connections:{'Upsert Carrinhos (Listmonk PG)':{main:[[{node:'Reconciliação 4 Listas (PG)'}]]},'Reconciliação 4 Listas (PG)':{main:[[{node:'Resumo'}]]}}};
 const sql=patchCollector(w,{expectedVersion:'v',brand:'fish'}).nodes[1].parameters.query;
 const input={email:'synthetic@example.invalid',name:'Synthetic',first_name:'Synthetic',cart_abandoned_at:new Date(Date.parse(x.ref)-3600000).toISOString(),cart_value:1,cart_url:'https://example.invalid/old',cart_items:[],cart_id:'older-cart',cart_phone:null,mkt_consent:'subscribed'};
 const stale=(await x.query(sql,[JSON.stringify([input]),'fish',17])).rows[0];assert.equal(Number(stale.carrinhos_gravados),1);assert.deepEqual(stale.graph_source_items,[]);
 input.cart_abandoned_at=new Date(Date.parse(x.ref)+1000).toISOString();input.cart_id='next-cart';const next=(await x.query(sql,[JSON.stringify([input]),'fish',17])).rows[0];assert.equal(next.graph_source_items.length,1);assert.equal(next.graph_source_items[0].ref,input.cart_abandoned_at);
}));

test('source identity and exact replay are stable across database session timezones',fixture(async x=>{
 const receipt=await x.receipt(),a=await x.api.capture(receipt);await x.query("SET TIME ZONE 'America/Sao_Paulo'");assert.deepEqual(await x.api.capture(receipt),a);assert.deepEqual((await x.api.capture({...receipt,receipt_id:id(199)})).source_refs,a.source_refs);
}));

test('collector monetary parsing preserves explicit zero and refuses absent or invalid provider amounts',()=>{
 for(const [input,expected]of [['12.30',12.3],['0.00',0],[0,0],[12.3,12.3],[null,null],[undefined,null],['',null],['R$ 12,30',null],['12,30',null],['-1',null],[NaN,null],[true,null]])assert.equal(graphMoney(input),expected);
 const code=patchNormalizer('return [Number(e.node.originalUnitPriceSet?.shopMoney?.amount || 0),Number(n.totalPriceSet?.shopMoney?.amount || 0)];');
 const result=new Function('e','n',code)({node:{originalUnitPriceSet:{shopMoney:{amount:null}}}},{totalPriceSet:{shopMoney:{amount:'0.00'}}});assert.deepEqual(result,[null,0]);assert.throws(()=>patchNormalizer('source changed'),/DRIFT/);assert.deepEqual(mapItems([{title:'Known',variante:''}]),[{name:'Known',title:'Known',variant:''}]);assert.ok(!Object.hasOwn(mapItems([{title:'Absent'}])[0],'variant'));
});
