'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require(process.env.CAMPAIGN_PGLITE_MODULE||'@electric-sql/pglite');
const C=require('../n8n/growth/journey-graph-catalog.cjs'),G=require('../n8n/growth/journey-graph-contract.js');
const sql=fs.readFileSync(path.join(__dirname,'../n8n/growth/journey-graph-catalog.sql'),'utf8');
async function setup(t){const db=new PGlite();t.after(()=>db.close());await db.exec(`CREATE SCHEMA crm_graph_candidate;
 CREATE TABLE shrigma_flow_definition(key text PRIMARY KEY,brand text,runtime_ready boolean,published_version integer,published jsonb);
 CREATE TABLE templates(id integer PRIMARY KEY,name text,type text,subject text,body text,body_source text);
 CREATE TABLE shrigma_template_email_registry(template_id integer,brand text);
 INSERT INTO shrigma_flow_definition VALUES('fish:carrinho','fish',true,6,'{"steps":[]}'),('aristo:carrinho','aristo',true,9,'{"steps":[]}');
 INSERT INTO templates VALUES(11,'Pedido Fish','tx','Sintético','<p>{{ .Tx.Data.first_name }}</p>',NULL),(12,'Carrinho Fish','tx','Exemplo','<p>Não publicar corpo no catálogo</p>',NULL),(21,'Pedido Aristo','tx','Exemplo Aristo','<p>Exemplo</p>',NULL),(22,'__shrigma_journey_tx_v1_fixture','tx','Clone','<p>Clone</p>',NULL),(23,'Wrapper','campaign','Campanha','<p>Wrapper</p>',NULL),(24,'Sem associação','tx','Sem marca','<p>Sem marca</p>',NULL),(25,'Ambíguo','tx','Ambíguo','<p>Marca ambígua</p>',NULL);
 INSERT INTO shrigma_template_email_registry VALUES(11,'fish'),(12,'fish'),(21,'aristo'),(22,'fish'),(23,'fish'),(25,'fish'),(25,'aristo');`);await db.exec(sql);return{db,query:db.query.bind(db)};}
const graph=brand=>({version:G.VERSION,brand,name:'Planejamento sintético',nodes:[{id:'start',type:'trigger',event:'cart.abandoned'},{id:'mail',type:'message',binding:brand==='fish'?'email.template.11':'email.template.21'},{id:'end',type:'exit',reason:'finished'}],edges:[{from:'start',port:'next',to:'mail'},{from:'mail',port:'next',to:'end'}]});
test('real registry snapshots are brand-isolated and stable; metadata is separate and never authorizes execution',async t=>{
 const f=await setup(t);for(const brand of ['fish','aristo']){const opt={brand,query:f.query},c=await C.catalogFor(opt),ui=await C.catalogUIFor(opt);assert.deepEqual(await C.catalogFor(opt),c);assert.deepEqual(ui.catalog,c);assert.equal(G.validateGraph(graph(brand),{catalog:c}).ok,true);assert.equal(ui.readiness.draft_only,true);for(const k of ['publish','runtime','transport','source_complete','immutable_release','template_variables_bound'])assert.equal(ui.readiness[k],false);assert.ok(ui.checked_at);assert.ok(!Object.hasOwn(c,'checked_at'));assert.ok(c.messages.every(m=>m.brand===brand&&m.channel==='email'&&m.release.startsWith('snapshot_')));assert.equal(ui.labels.triggers['cart.abandoned'],'Carrinho abandonado');assert.doesNotMatch(JSON.stringify(ui),/<p>|first_name|Não publicar/);}
 const fcat=await C.catalogFor({brand:'fish',query:f.query}),acat=await C.catalogFor({brand:'aristo',query:f.query});assert.deepEqual(fcat.messages.map(x=>x.key),['email.template.11','email.template.12']);assert.deepEqual(acat.messages.map(x=>x.key),['email.template.21']);assert.equal(G.validateGraph({...graph('fish'),nodes:graph('fish').nodes.map(n=>n.type==='message'?{...n,binding:'email.template.21'}:n)},{catalog:fcat}).ok,false);
});
test('native content changes alter the fingerprint without mutating anything; labels do not alter catalog revision',async t=>{
 const {db,query}=await setup(t),opt={brand:'fish',query},first=await C.catalogFor(opt);await db.exec("UPDATE templates SET name='Nome atualizado' WHERE id=11");assert.deepEqual(await C.catalogFor(opt),first);assert.equal((await C.catalogUIFor(opt)).labels.messages['email.template.11'],'Nome atualizado');await db.exec("UPDATE templates SET body='<p>Nova revisão</p>' WHERE id=11");const second=await C.catalogFor(opt);assert.notEqual(first.messages[0].release,second.messages[0].release);assert.equal(first.messages[1].release,second.messages[1].release);assert.equal((await db.query('SELECT count(*)::int n FROM templates')).rows[0].n,7);
});
test('missing/foreign/unpublished legacy source is unavailable; purchase and permission conditions cannot be invented',async t=>{
 const {db,query}=await setup(t),opt={brand:'fish',query};const c=await C.catalogFor(opt);assert.equal(c.triggers[0].available,true);assert.equal(c.fields.find(f=>f.key==='purchase.confirmed').available,false);assert.throws(()=>G.evaluateCondition({field:'purchase.confirmed',op:'eq',value:false},{catalog:c,trigger:'cart.abandoned',facts:{},now:'2026-09-26T12:00:00.000Z'}),{code:'GRAPH_FIELD'});
 for(const q of ["UPDATE shrigma_flow_definition SET runtime_ready=false WHERE key='fish:carrinho'","UPDATE shrigma_flow_definition SET runtime_ready=true,published_version=NULL WHERE key='fish:carrinho'","UPDATE shrigma_flow_definition SET published_version=6,brand='aristo' WHERE key='fish:carrinho'","DELETE FROM shrigma_flow_definition WHERE key='fish:carrinho'"]){await db.exec(q);const absent=await C.catalogFor(opt);assert.equal(absent.triggers[0].available,false);assert.equal(G.validateGraph(graph('fish'),{catalog:absent}).errors[0].code,'GRAPH_TRIGGER_UNAVAILABLE');}
});
test('catalog limit fails closed rather than silently truncating eligible templates',async t=>{
 const {db,query}=await setup(t);await db.exec("INSERT INTO templates SELECT n,'Fixture '||n,'tx','Fixture','<p>Fixture</p>',NULL FROM generate_series(100,163)n;INSERT INTO shrigma_template_email_registry SELECT n,'fish' FROM generate_series(100,163)n");await assert.rejects(C.catalogFor({brand:'fish',query}),/GRAPH_CATALOG_LIMIT/);
});
test('installation is atomic, private and refuses collisions without changing unrelated functions',async t=>{
 const {db}=await setup(t);await assert.rejects(db.exec(sql),/GRAPH_CATALOG_COLLISION/);assert.equal((await db.query('SELECT 1 ok')).rows[0].ok,1);const rows=(await db.query("SELECT p.proname,p.prosecdef,p.provolatile,EXISTS(SELECT 1 FROM aclexplode(p.proacl) a WHERE a.grantee=0 AND a.privilege_type='EXECUTE') public_execute FROM pg_proc p WHERE p.pronamespace='crm_graph_candidate'::regnamespace")).rows;assert.equal(rows.length,2);assert.ok(rows.every(r=>r.provolatile==='s'&&!r.prosecdef&&!r.public_execute));await assert.rejects(db.query("SELECT crm_graph_candidate.catalog_v1('olivas')"),/GRAPH_CATALOG_BRAND/);
});
test('adapter parameterizes brand and rejects malformed or execution-ready responses',async t=>{
 const {query}=await setup(t);let calls=0;const spy=async(q,args)=>{calls++;assert.match(q,/^SELECT crm_graph_candidate\.catalog(?:_ui)?_v1\(\$1::text\) AS result$/);assert.deepEqual(args,['fish']);return query(q,args);};await C.catalogFor({brand:'fish',query:spy});await C.catalogUIFor({brand:'fish',query:spy});assert.equal(calls,2);await assert.rejects(C.catalogFor({brand:"fish';SELECT 1",query:spy}),/GRAPH_CATALOG_ADAPTER_REQUIRED/);assert.equal(calls,2);
 const good=await C.catalogUIFor({brand:'fish',query});for(const change of [r=>r.readiness.transport=true,r=>r.catalog.brand='aristo',r=>r.labels.fields['cart.abandoned_at']='',r=>r.catalog.messages[0].release='immutable-proof']){const r=JSON.parse(JSON.stringify(good));change(r);await assert.rejects(C.catalogUIFor({brand:'fish',query:async()=>({rows:[{result:r}]})}),/GRAPH_CATALOG_UNCONFIRMED/);}
});
