'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const W=require('../n8n/growth/journey-graph-service-wiring.cjs');
const credential={id:'syntheticHeaderAuth',name:'CRM flows private synthetic'},origin='http://comunicacao_crm-flows:8080',uid=n=>'91000000-0000-4000-8000-'+String(n).padStart(12,'0');
function collector(brand){const base=brand==='fish'?17:16,cart=brand==='fish'?22:21,query=fs.readFileSync(path.join(__dirname,'sql/journey-collector-fixture.sql'),'utf8');return {id:brand==='fish'?'syntheticFish':'syntheticAristo',versionId:'version-'+brand,active:true,settings:{executionOrder:'v1'},nodes:[{name:'Config',type:'n8n-nodes-base.set',position:[0,0],parameters:{assignments:{assignments:[{name:'brand',value:brand},{name:'list_base',value:base},{name:'list_carrinho',value:cart}]}}},{name:'Normalizar Carrinhos',type:'n8n-nodes-base.code',parameters:{jsCode:'const preco=Number(e.node.originalUnitPriceSet?.shopMoney?.amount || 0);const total=Number(n.totalPriceSet?.shopMoney?.amount || 0);'}},{name:'Upsert Carrinhos (Listmonk PG)',type:'n8n-nodes-base.postgres',parameters:{query}},{name:'Reconciliação 4 Listas (PG)',type:'n8n-nodes-base.postgres',position:[100,100],parameters:{query:'SELECT 0 AS flags_sincronizados'}},{name:'Resumo',type:'n8n-nodes-base.code',parameters:{jsCode:'return items;'}}],connections:{'Upsert Carrinhos (Listmonk PG)':{main:[[{node:'Reconciliação 4 Listas (PG)',type:'main',index:0}]]},'Reconciliação 4 Listas (PG)':{main:[[{node:'Resumo',type:'main',index:0}]]}}};}
test('both collectors preserve the natural schedule and reconciliation, then submit once and recover by read only',()=>{
 for(const brand of ['fish','aristo']){const before=collector(brand),after=W.patchCollectorService(before,{expectedVersion:before.versionId,brand,serviceOrigin:origin,credential});assert.equal(after.active,true);assert.deepEqual(after.settings,before.settings);assert.equal(after.nodes.filter(n=>n.name==='Graph source submit').length,1);assert.equal(after.nodes.filter(n=>n.name==='Graph source recover').length,1);for(const name of ['Graph source submit','Graph source recover']){const n=after.nodes.find(x=>x.name===name);assert.equal(n.retryOnFail,false);assert.equal(n.onError,'continueRegularOutput');assert.equal(n.credentials.httpHeaderAuth.id,credential.id);assert.equal(n.parameters.options.redirect.redirect.followRedirects,false);assert.equal(n.parameters.options.response.response.fullResponse,true);assert.equal(n.parameters.options.response.response.neverError,true);}assert.equal(after.connections['Reconciliação 4 Listas (PG)'].main[0][0].node,'Resumo');assert.ok(after.connections['Reconciliação 4 Listas (PG)'].main[0].some(x=>x.node==='Graph source receipts (candidate)'));for(const n of after.nodes.filter(x=>x.type==='n8n-nodes-base.code'))assert.doesNotThrow(()=>new vm.Script('(function(){'+n.parameters.jsCode+'})()'));}
});
test('tick workflow is inactive, bounded to one per brand, and recovery never points to the mutation route',()=>{
 const w=W.buildTickWorkflow({serviceOrigin:origin,credential});assert.equal(w.active,false);assert.match(w.name,/CANDIDATO OFF/);assert.equal(w.nodes.find(n=>n.name==='Graph tick submit').parameters.url,origin+'/internal/tick');assert.equal(w.nodes.find(n=>n.name==='Graph tick recover').parameters.url,origin+'/internal/tick-operation');assert.equal(w.nodes.find(n=>n.name==='Graph tick submit').retryOnFail,false);assert.equal(w.nodes.find(n=>n.name==='Graph tick recover').retryOnFail,false);assert.equal(w.settings.saveDataSuccessExecution,'none');assert.equal(w.settings.saveDataErrorExecution,'none');assert.notEqual(W.tickRequestId('123','fish'),W.tickRequestId('123','aristo'));assert.equal(W.tickRequestId('123','fish'),W.tickRequestId('123','fish'));for(const n of w.nodes.filter(x=>x.type==='n8n-nodes-base.code'))assert.doesNotThrow(()=>new vm.Script('(function(){'+n.parameters.jsCode+'})()'));
});
test('response validators bind the exact operation and reject missing, cross-brand and malformed recovery',()=>{
 const source={brand:'fish',workflow_id:'syntheticFish',execution_id:'123',batch_index:0,items:[{}]},sourceBody={source_refs:[uid(1)],authorizes_enrollment:false,authorizes_send:false},confirmed=W.validateSourceResponse({statusCode:200,body:sourceBody},source);assert.equal(confirmed.operation.workflow_id,'syntheticFish');
 const found={contract:'journey_graph_source_operation_v1',state:'found',...confirmed.operation,receipt_id:uid(2),response:sourceBody,authorizes_enrollment:false,authorizes_send:false};assert.equal(W.validateSourceOperation({statusCode:200,body:found},confirmed.operation).receipt_id,uid(2));assert.throws(()=>W.validateSourceOperation({statusCode:200,body:{...found,state:'missing'}},confirmed.operation),/UNCONFIRMED/);assert.throws(()=>W.validateSourceOperation({statusCode:200,body:{...found,brand:'aristo'}},confirmed.operation),/UNCONFIRMED/);
 const request={brand:'fish',limit:1,request_id:uid(3)},tick={contract:'journey_graph_worker_request_v1',state:'completed',brand:'fish',request_id:uid(3),authorizes_send:false,response:{contract:'journey_graph_worker_v1',brand:'fish'}};assert.equal(W.validateTickResponse({statusCode:200,body:tick},request).state,'completed');assert.throws(()=>W.validateTickOperation({statusCode:200,body:{...tick,state:'in_flight'}},request),/UNCONFIRMED/);
});
test('only an explicit private origin and credential reference are accepted',()=>{for(const bad of ['https://example.com','http://127.0.0.1:8080','http://crm-flows:80','http://crm-flows:8080/path'])assert.throws(()=>W.buildTickWorkflow({serviceOrigin:bad,credential}),/INPUT/);assert.throws(()=>W.buildTickWorkflow({serviceOrigin:origin,credential:{id:'short',name:'x'}}),/INPUT/);});
