'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const W=require('../n8n/growth/journey-graph-workflow.cjs'),{setup,id,read}=require('./fixtures/journey-graph-workflow.cjs');
const req=(definition,n=1)=>({action:'create',brand:definition.brand,request_id:id(n),definition});
test('transport accepts only exact manager header requests and draft methods; local simulation never grants runtime',()=>{const invalid=[{action:'create',brand:'fish',request_id:id(1),definition:{},actor:'panel:other'},{action:'publish',brand:'fish'},{action:'catalog',brand:'olivas'}];for(const p of invalid)assert.equal(W.API.parse({method:'POST',request:{headers:{authorization:'Bearer synshort'},body:p}}).route,'response');for(const headers of [{},{authorization:'Bearer synshort',Authorization:'Bearer synshort'},{authorization:'Bearer synshort',origin:'https://evil.invalid'}])assert.equal(W.API.parse({method:'GET',request:{headers,query:{action:'catalog',brand:'fish'}}}).route,'response');assert.equal(W.API.parse({method:'GET',request:{headers:{authorization:'Bearer synshort'},query:{action:'list',brand:'fish'}}}).request.limit,25);});
test('SQL bridge uses real short-key helper, validates graph, emits immutable draft receipt and preserves exact replay/CAS',async()=>{const x=await setup();try{const p=req(x.fish.graph),created=await x.call(p,'synshort');assert.equal(created.status,201);assert.equal(created.body.actor,'panel:manager');assert.deepEqual(created.body.request_payload,p);assert.equal(created.body.receipt.paused,true);assert.equal(created.body.receipt.published_revision,null);assert.deepEqual(await x.call(p),created);const changed={...p,definition:{...p.definition,name:'Changed'}};assert.equal((await x.call(changed)).body.error,'GRAPH_REPLAY_MISMATCH');assert.equal((await x.call(p,'synthetic-other-key')).status,409);assert.equal((await x.call({...p,request_id:id(2)},'synthetic-reader-key')).status,403);const save={action:'save',brand:'fish',request_id:id(3),journey_id:created.body.receipt.journey_id,expected_version:1,definition:{...p.definition,name:'Revision two'}};assert.equal((await x.call(save)).body.receipt.version,2);assert.equal((await x.call({...save,request_id:id(4)})).body.error,'GRAPH_VERSION_CONFLICT');assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.revision')).rows[0].n,2);assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.intent')).rows[0].n,0);}finally{await x.db.close();}});
test('lost response and historical reconstruction keep original payload, actor, revision and brand; missing stays unconfirmed',async()=>{const x=await setup();try{const p=req(x.fish.graph),e=x.entry(p),prepared=W.API.prepare(e,await x.sqlRead(e));const committed=await x.sqlCommit(e,prepared.proof);assert.equal(W.API.failure(e).response.status,202);const old=committed.body.receipt;await x.call({action:'save',brand:'fish',request_id:id(2),journey_id:old.journey_id,expected_version:1,definition:{...p.definition,name:'New head'}});const readback=await x.call({action:'operation',brand:'fish',request_id:p.request_id});assert.equal(readback.status,200);assert.deepEqual(readback.body.request_payload,p);assert.deepEqual(readback.body.receipt,old);assert.equal(readback.body.actor,'panel:manager');assert.equal((await x.call({action:'operation',brand:'fish',request_id:p.request_id},'synthetic-other-key')).status,404);assert.equal((await x.call({action:'operation',brand:'aristo',request_id:p.request_id})).status,404);const missing=await x.call({action:'operation',brand:'fish',request_id:id(999)});assert.equal(missing.status,202);assert.equal(missing.body.actor,'panel:manager');assert.equal(missing.body.retry_same_request_only,true);assert.deepEqual((await x.call(p)).body.receipt,old);}finally{await x.db.close();}});
test('catalog drift or privilege revocation between preflight and atomic commit refuses all writes',async()=>{const x=await setup();try{const p=req(x.fish.graph),e=x.entry(p),prepared=W.API.prepare(e,await x.sqlRead(e));await x.db.query("UPDATE fixture_catalog SET payload=jsonb_set(payload,'{messages,0,release}','\"changed\"') WHERE brand='fish'");assert.equal((await x.sqlCommit(e,prepared.proof)).body.error,'GRAPH_CATALOG_CHANGED');await x.db.query('UPDATE fixture_catalog SET payload=$1 WHERE brand=\'fish\'',[JSON.stringify(x.fish.catalog)]);await x.db.exec("UPDATE crm_dash_chave SET ativo=false WHERE chave='manager'");assert.equal((await x.sqlCommit(e,prepared.proof)).status,401);assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.journey')).rows[0].n,0);}finally{await x.db.close();}});
test('read catalog/get/list are brand-bound, verify stored content and hide credentials/provider internals',async()=>{const x=await setup();try{const f=await x.call(req(x.fish.graph)),a=await x.call(req(x.aristo.graph,2));for(const brand of ['fish','aristo']){const c=await x.call({action:'catalog',brand});assert.equal(c.body.catalog.brand,brand);assert.equal(c.body.readiness.runtime,false);const l=await x.call({action:'list',brand});assert.equal(l.body.journeys.length,1);assert.equal(l.body.journeys[0].brand,brand);}const got=await x.call({action:'get',brand:'fish',journey_id:f.body.receipt.journey_id});assert.equal(got.status,200);assert.deepEqual(got.body.definition,x.fish.graph);assert.equal((await x.call({action:'get',brand:'aristo',journey_id:f.body.receipt.journey_id})).status,404);assert.equal((await x.call({action:'capabilities',brand:'fish'})).body.features.runtime,false);assert.doesNotMatch(JSON.stringify(got),/synthetic-manager-key|request_hash|stored_catalog|content_hash/);assert.ok(a.body.receipt.journey_id!==f.body.receipt.journey_id);}finally{await x.db.close();}});
test('reapplication changes no data and a graph rejected by the shared contract never reaches commit',async()=>{const x=await setup();try{const graph=JSON.parse(JSON.stringify(x.fish.graph));graph.edges.pop();const bad=await x.call(req(graph));assert.equal(bad.status,422);assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.operation')).rows[0].n,0);const p=req(x.fish.graph,2),created=await x.call(p);await x.db.exec(read('n8n/growth/journey-graph-workflow-store.sql'));assert.deepEqual(await x.call(p),created);}finally{await x.db.close();}});
test('generated workflow has only PG credential references, no transport/schedules, payload retention none and bounded prepared queries',()=>{const w=W.buildWorkflow({webhookPath:'synthetic-graph-drafts',postgresCredential:{id:'synthetic',name:'Fixture PG'}});assert.equal(w.settings.saveDataErrorExecution,'none');assert.equal(w.settings.executionTimeout,45);assert.ok(w.nodes.every(n=>!['n8n-nodes-base.httpRequest','n8n-nodes-base.scheduleTrigger'].includes(n.type)));for(const n of w.nodes){if(n.type==='n8n-nodes-base.code')assert.doesNotThrow(()=>new vm.Script('(function(){'+n.parameters.jsCode+'})()'));if(n.type==='n8n-nodes-base.postgres'){assert.equal(n.retryOnFail,false);assert.match(n.parameters.query,/\$1::text/);assert.equal(n.parameters.options.queryReplacement.includes('JSON.stringify'),true);}}assert.throws(()=>W.buildWorkflow({webhookPath:'synthetic-graph-drafts',postgresCredential:{id:'x',name:'y',password:'not allowed'}}));});
test('HTTP bridge and existing Node API share identical ledger hashes and immutable revisions in both directions',async()=>{const {createDraftApi}=require('../n8n/growth/journey-graph-draft-api.cjs'),x=await setup();try{const api=createDraftApi({pool:x.pool,catalogFor:async({brand})=>brand==='fish'?x.fish.catalog:x.aristo.catalog}),p=req({...x.fish.graph,name:'Revisão — açao'},501);const old=await api.handle({method:'POST',authorization:'Bearer synshort',request:p});assert.equal(old.status,201);const readback=await x.call({action:'operation',brand:'fish',request_id:p.request_id});assert.deepEqual(readback.body.request_payload,p);assert.deepEqual((await x.call(p)).body.receipt,old.body.receipt);const q=req(x.aristo.graph,502),modern=await x.call(q),got=await api.handle({method:'GET',authorization:'Bearer synshort',request:{action:'get',brand:'aristo',journey_id:modern.body.receipt.journey_id}});assert.equal(got.status,200);assert.deepEqual(got.body.definition,q.definition);}finally{await x.db.close();}});
test('malformed permission object cannot impersonate the helper array grants or reserve a draft',async()=>{const x=await setup();try{const p=req(x.fish.graph),e=x.entry(p),proof=W.API.prepare(e,await x.sqlRead(e)).proof;await x.db.query("UPDATE shrigma_panel_permission_v1 SET caps='{\"draft\":true,\"read_content\":true}' WHERE principal_id='manager'");assert.equal((await x.call({action:'catalog',brand:'fish'})).status,401);assert.equal((await x.sqlCommit(e,proof)).status,401);assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.operation')).rows[0].n,0);}finally{await x.db.close();}});

test('embedded bridge executes without require/crypto and does not depend on sandbox module exports',()=>{const input={method:'GET',request:{headers:{authorization:'Bearer synshort'},query:{action:'capabilities',brand:'fish'}}};for(const context of [{},{module:{exports:{}}}]){const out=vm.runInNewContext('(function(){'+W.BUNDLE+'\nreturn GraphHttp.parse('+JSON.stringify(input)+');})()',context);assert.equal(out.route,'read');assert.equal(out.request.action,'capabilities');}});

test('draft save cannot overwrite a published revision, while its earlier receipt remains recoverable',async()=>{
 const x=await setup();try{
  const p=req(x.fish.graph,901),created=await x.call(p),j=created.body.receipt.journey_id;
  await x.db.query('UPDATE crm_graph_candidate.journey SET published_revision=head_revision,paused=true WHERE id=$1',[j]);
  const save={action:'save',brand:'fish',request_id:id(902),journey_id:j,expected_version:1,definition:{...x.fish.graph,name:'Overwrite forbidden'}};
  assert.equal((await x.call(save)).body.error,'GRAPH_PUBLISHED_READ_ONLY');
  assert.deepEqual((await x.call(p)).body.receipt,created.body.receipt);
  const {createDraftApi}=require('../n8n/growth/journey-graph-draft-api.cjs'),api=createDraftApi({pool:x.pool,catalogFor:async()=>x.fish.catalog});
  assert.equal((await api.handle({method:'POST',authorization:'Bearer synshort',request:save})).body.error,'GRAPH_PUBLISHED_READ_ONLY');
  assert.equal((await x.db.query('SELECT count(*)::int n FROM crm_graph_candidate.revision')).rows[0].n,1);
 }finally{await x.db.close();}
});
