'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.CAMPAIGN_PGLITE_MODULE||'@electric-sql/pglite');
const f=require('./maintenance-tx-popup-fixture.cjs'),p=require('../n8n/growth/maintenance-tx-popup-protocol.cjs');
async function setup(t){const db=new PGlite();t.after(()=>db.close());await db.exec(f.fixtureSQL);await db.exec(f.store);await db.exec(f.txSQL);return {db,a:f.txAPI(db)};}
test('TX admission is durable before ACK, same normalized input replays receipt; no implicit expiry',async t=>{
 const {a}=await setup(t),b=f.body(),r=await a.admitTX('fish',b);assert.equal(r.persisted,true);assert.equal(r.authorizes_send,false);assert.equal(r.expires_at,null);assert.deepEqual(await a.admitTX('fish',b),r);assert.equal(p.receiptResponse({receipt:r},'fish').status,200);assert.equal(p.receiptResponse({error:'private SQL detail'},'fish').status,503);assert.equal((await a.claimTX(r.event_id)).reason,'retained');assert.deepEqual(await a.nextTX('fish'),[]);await assert.rejects(a.admitTX('fish',{...b,subject:'Changed'}),/MAINTENANCE_REPLAY_MISMATCH/);
});
test('consumer prepares only a missing subscriber; same claim token is issued once and finish reconciles',async t=>{
 const {a}=await setup(t);const r=await a.admitTX('fish',f.body());await a.control(1,true,'open');const [next]=await a.nextTX('fish');assert.equal(next.subscriber_needed,true);assert.equal(next.event_id,r.event_id);assert.deepEqual(next.body,f.body());assert.equal((await a.claimTX(r.event_id)).reason,'retained_subscriber_pending');assert.deepEqual(await a.nextTX('fish'),[]);await a.subscriber('fish');const c=await a.claimTX(r.event_id);assert.equal(c.should_send,true);assert.deepEqual(c.payload,f.body());assert.deepEqual(c.context,f.body());assert.equal((await a.claimTX(r.event_id)).claim_token,null);const finish=await a.finishTX(c,{statusCode:200,body:{data:true}});assert.equal(finish.transport_state,'accepted');assert.equal((await a.row(r.event_id)).state,'accepted');assert.deepEqual(await a.admitTX('fish',f.body()),r);
});
test('close after selection fences claim and keeps same event; new arrival during closed is retained',async t=>{
 const {a}=await setup(t);await a.control(1,true,'open');await a.subscriber('aristo');const r=await a.admitTX('aristo',f.body('aristo'));assert.equal((await a.nextTX('aristo')).length,1);await a.control(2,true,'closed');assert.equal((await a.claimTX(r.event_id)).should_send,false);const late=await a.admitTX('aristo',f.body('aristo',{order_id:'late'}));assert.equal((await a.row(late.event_id)).state,'queued');await a.control(3,true,'open');assert.equal((await a.claimTX(r.event_id)).should_send,true);
});
test('global and brand opt-outs, wrong-brand membership and ambiguous subscriber fail closed before original claim',async t=>{
 for(const [status,subscription,brand,reason] of [['blocklisted','confirmed','fish','optout'],['disabled','confirmed','fish','optout'],['enabled','unsubscribed','fish','optout'],['enabled','confirmed','aristo','brand_membership_missing']]){
 const {a}=await setup(t);await a.control(1,true,'open');await a.subscriber(brand,'synthetic@example.invalid',status,subscription);const r=await a.admitTX('fish',f.body()),c=await a.claimTX(r.event_id);assert.equal(c.should_send,false);assert.equal(c.claim_token,null);assert.equal((await a.row(r.event_id)).reason,reason);
 }
});
test('rotation passes paused entries, future retries use same identity; original SQL failure blocks only event',async t=>{
 const {db,a}=await setup(t);await a.subscriber('fish');await a.control(1,true,'open');const refs=[];for(let i=0;i<12;i++)refs.push(await a.admitTX('fish',f.body('fish',{order_id:'paused'+i})));await db.exec('UPDATE maintenance_fixture_policy SET paused=true');const ids=[];for(let i=0;i<12;i++){const [n]=await a.nextTX('fish');ids.push(n.event_id);assert.equal((await a.claimTX(n.event_id)).reason,'retained_flow_paused');}assert.equal(new Set(ids).size,12);assert.deepEqual(await a.nextTX('fish'),[]);await db.exec("UPDATE crm_maintenance_candidate.tx_attempt SET last_attempt_at=clock_timestamp()-interval '31 seconds';UPDATE maintenance_fixture_policy SET paused=false,crash=true");const [n]=await a.nextTX('fish');assert.equal((await a.claimTX(n.event_id)).reason,'review_required');assert.equal((await a.row(n.event_id)).reason,'tx_claim_failed');assert.equal((await db.query('SELECT count(*) n FROM shrigma_email_dispatch')).rows[0].n,0);
});
test('accepted, rejected and unknown finish remain terminal, preserving context; reconciliation failure rolls back only SQL',async t=>{
 const {db,a}=await setup(t);await a.control(1,true,'open');await a.subscriber('fish');
 for(const [i,response,state] of [[1,{statusCode:200,body:{data:true}},'accepted'],[2,{statusCode:422},'rejected'],[3,{error:'timeout'},'outcome_unknown']]){const r=await a.admitTX('fish',f.body('fish',{order_id:'finish'+i})),c=await a.claimTX(r.event_id);assert.equal((await a.finishTX(c,response)).transport_state,state);assert.equal((await a.row(r.event_id)).state,state);assert.equal((await a.claimTX(r.event_id)).claim_token,null);assert.deepEqual((await db.query('SELECT context FROM maintenance_finish_log WHERE dispatch_id=$1',[c.dispatch_id])).rows[0].context,c.context);}
 const r=await a.admitTX('fish',f.body('fish',{order_id:'rollback'})),c=await a.claimTX(r.event_id);await db.exec("CREATE FUNCTION reject_reconcile() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.state='accepted' THEN RAISE EXCEPTION 'SYNTHETIC_RECONCILE';END IF;RETURN NEW;END$$;CREATE TRIGGER reject_reconcile BEFORE UPDATE ON crm_maintenance_candidate.event FOR EACH ROW EXECUTE FUNCTION reject_reconcile()");await assert.rejects(a.finishTX(c,{statusCode:200,body:{data:true}}),/SYNTHETIC_RECONCILE/);assert.equal((await a.row(r.event_id)).state,'claimed');assert.equal((await db.query('SELECT transport_state FROM shrigma_email_dispatch WHERE dispatch_id=$1',[c.dispatch_id])).rows[0].transport_state,'in_flight');assert.equal((await a.claimTX(r.event_id)).claim_token,null);
});
test('SQL input excludes secrets, wrong slice and non-TX scope; no grants or subscriber writes',async t=>{
 const {a,db}=await setup(t);for(const b of [{...f.body(),headers:{}},{...f.body(),template_id:23},{...f.body(),items:[{authorization:'not-secret'}]}])await assert.rejects(a.admitTX('fish',b),/MAINTENANCE_TX_/);await assert.rejects(a.admitTX('olivas',f.body()),/MAINTENANCE_TX_/);const popup=await a.admit('fish','popup',f.popup());await assert.rejects(a.claimTX(popup.event_id),/MAINTENANCE_TX_SCOPE/);assert.equal((await db.query('SELECT count(*) n FROM subscribers')).rows[0].n,0);
});
test('SQL refuses header CRLF even when caller skips protocol validation',async t=>{
 const {a}=await setup(t);for(const key of ['name','from_email','reply_to','subject'])await assert.rejects(a.admitTX('fish',f.body('fish',{[key]:key==='from_email'?'Injected\n<orders@fishermans.com.br>':'Synthetic\r\nBcc: synthetic@example.invalid'})),/MAINTENANCE_TX_HEADER/);
});
test('consumer owns only entries admitted by the TX contract, never other generic transactional producers',async t=>{
 const {a,db}=await setup(t);await a.control(1,true,'open');await a.subscriber('fish');const foreign=await a.admit('fish','transactional',f.body('fish',{event_type:'enviado'}));assert.deepEqual(await a.nextTX('fish'),[]);await assert.rejects(a.claimTX(foreign.event_id),/MAINTENANCE_TX_SCOPE/);assert.equal((await a.row(foreign.event_id)).state,'queued');const own=await a.admitTX('fish',f.body());assert.equal((await a.nextTX('fish'))[0].event_id,own.event_id);await assert.rejects(db.query('DELETE FROM crm_maintenance_candidate.tx_inbox WHERE event_id=$1',[own.event_id]),/MAINTENANCE_IMMUTABLE/);
});
test('reviewed native TX claim/selector/finish composition preserves exact payload hash and dispatch identity',async t=>{
 const {db,a}=await setup(t);await db.exec(require('node:fs').readFileSync(require('node:path').join(__dirname,'maintenance-tx-popup-native-fixture.sql'),'utf8'));await a.control(1,true,'open');
 for(const brand of ['fish','aristo']){await a.subscriber(brand);const b=f.body(brand,{order_id:'native-'+brand}),r=await a.admitTX(brand,b),c=await a.claimTX(r.event_id);assert.equal(c.should_send,true);assert.deepEqual(c.context,{...b,template_id:brand==='fish'?5:15});assert.deepEqual(c.payload.data,c.context);assert.equal(c.payload.subscriber_email,b.email);assert.equal(c.payload.template_id,b.template_id);const terminal=await a.finishTX(c,{statusCode:200,body:{data:true}});assert.equal(terminal.transport_state,'accepted');assert.equal((await a.row(r.event_id)).state,'accepted');assert.equal((await a.claimTX(r.event_id)).claim_token,null);}
 assert.equal((await db.query('SELECT count(*) n FROM shrigma_send_log')).rows[0].n,2);
 await db.exec("UPDATE shrigma_flow_definition SET enabled=false WHERE brand='fish'");const held=await a.admitTX('fish',f.body('fish',{order_id:'native-paused'}));assert.equal((await a.claimTX(held.event_id)).reason,'retained_flow_paused');assert.equal((await a.row(held.event_id)).state,'queued');
});
