'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const source=process.env.ORGANICO_INCIDENT_SOURCE||path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(source,'organico.html'),'utf8');
function slice(a,b){const start=html.indexOf(a),end=html.indexOf(b,start);assert(start>=0&&end>start);return html.slice(start,end);}
function boot(open='2026-10-08T02:55:00Z',preset='mes'){
 let clock=Date.parse(open),active=preset;const elements=new Map(),buttons=['semana','semanaant','mes','mesant','30','90'].map(p=>({dataset:{p},classList:{add(){active=p;},remove(){if(active===p)active=null;}}}));
 class Clock extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
 const $=s=>{if(!elements.has(s))elements.set(s,{value:'',innerHTML:'',textContent:'',hidden:false,title:''});return elements.get(s);};
 const document={querySelector:s=>s==='#presets button.ativo'?(active?buttons.find(b=>b.dataset.p===active):null):$(s),querySelectorAll:s=>s==='#presets button'?buttons:[]};
 const calls=[],painted=[],warnings=[];
 const ctx=vm.createContext({Date:Clock,Intl,Number,Array,JSON,$,document,Image:function(){},console,
 pintaMarca(){},pintaKPIs(){const rows=vm.runInContext('posts(PER.ini,PER.fim)',ctx);painted.push(rows);return rows;},pintaGrade(){},pintaPosts(){},pintaStories(){},
 AbortController,setTimeout,clearTimeout,CARGA_ORGANICO:false,ACESSO_ORGANICO:{setBusy(){},show(){},reject(){}},chaveLeitura:()=> 'synthetic-read-only',CX_CACHE_URL:'https://example.invalid/cache',CX_API_URL:'https://example.invalid/live',
 avisoTela:(a,b)=>warnings.push([a,b]),window:{},shrigmaFrescor(){},
 fetch:async(url)=>{calls.push(url);return{ok:true,status:200,json:async()=>vm.runInContext('API',ctx)};}});
 for(const code of [slice('const G={','// Recorta apenas'),slice('function daMarca(x)','// Percentil recalculado'),slice('function render(){','function troca(s)'),slice('// ORGANICO_CACHE_READ_BEGIN','// ORGANICO_CACHE_READ_END'),slice('async function carrega(){',"document.querySelectorAll('#seg-marca button')"),slice("document.querySelectorAll('#presets button')","$('#cmp').onchange")])vm.runInContext(code,ctx);
 const run=s=>vm.runInContext(s,ctx);run(`MARCA='fish'; API={_escopo:'organico',_cache_gerado_em:new Date().toISOString(),cx_post:[{post_id:'synthetic-fish-yesterday',marca:'fishermans',publicado_em:'2026-10-07T21:00:00-03:00',alcance:10},{post_id:'synthetic-fish-new',marca:'fishermans',publicado_em:'2026-10-08T09:00:00-03:00',alcance:10},{post_id:'synthetic-aristo-new',marca:'aristocrata',publicado_em:'2026-10-08T09:00:00-03:00',alcance:10},{post_id:'synthetic-boosted',marca:'fishermans',publicado_em:'2026-10-08T09:00:00-03:00',impulsionado:true}],cx_story:[],cx_organico_receita:[]};`);
 return{ctx,run,calls,painted,elements,buttons,setClock:v=>{clock=Date.parse(v);},active:()=>active};
}
test('successful fresh-cache read after BRT day rollover includes newly published Fish, without live call',async()=>{const b=boot();b.run('render()');assert.equal(b.run('PER.fim'),'2026-10-07');b.setClock('2026-10-09T12:00:00Z');b.run('API._cache_gerado_em=new Date().toISOString()');await b.run('carrega()');assert.equal(b.run('PER.fim'),'2026-10-09');assert.deepEqual(Array.from(b.painted.at(-1),p=>p.post_id),['synthetic-fish-yesterday','synthetic-fish-new']);assert.equal(b.calls.length,1);assert.equal(b.run('ORIGEM_LEITURA'),'cache');assert.equal(b.elements.get('#d-fim').value,'2026-10-09');});
test('preset click in long-lived tab uses current Brasília day, not opening date',()=>{const b=boot();b.setClock('2026-10-09T12:00:00Z');b.buttons.find(x=>x.dataset.p==='30').onclick();assert.equal(b.run('PER.fim'),'2026-10-09');assert.equal(b.run('PER.ini'),'2026-09-10');});
test('manual historical date range survives later read and does not add new posts',async()=>{const b=boot();b.elements.get('#d-ini').value='2026-10-01';b.elements.get('#d-fim').value='2026-10-07';b.run("$('#d-fim').onchange()");assert.equal(b.active(),null);b.setClock('2026-10-09T12:00:00Z');b.run('API._cache_gerado_em=new Date().toISOString()');await b.run('carrega()');assert.equal(b.run('PER.fim'),'2026-10-07');assert.deepEqual(Array.from(b.painted.at(-1),p=>p.post_id),['synthetic-fish-yesterday']);});
test('BRT boundary differs from UTC, and selected presets keep original semantics',()=>{for(const preset of ['semana','semanaant','mes','30','90']){const b=boot('2026-10-08T02:55:00Z',preset);b.setClock('2026-10-09T02:59:00Z');b.run('render()');assert.equal(JSON.stringify(b.run('PER')),JSON.stringify(b.run(`G.preset('${preset}','2026-10-08')`)));b.setClock('2026-10-09T03:00:00Z');b.run('render()');assert.equal(JSON.stringify(b.run('PER')),JSON.stringify(b.run(`G.preset('${preset}','2026-10-09')`)));}});
test('stale cache falls back to live using original request/auth path and renders current period',async()=>{const b=boot();b.setClock('2026-10-09T12:00:00Z');let n=0;b.ctx.fetch=async(url,init)=>{b.calls.push(url);assert.equal(init.cache,'no-store');assert.equal(init.headers.Authorization,'Bearer synthetic-read-only');assert(!url.includes('synthetic'));n++;return{status:200,ok:true,json:async()=>n===1?b.run('API'):b.run('({...API,_cache_gerado_em:undefined})')};};await b.run('carrega()');assert.equal(b.calls.length,2);assert.equal(b.run('ORIGEM_LEITURA'),'vivo');assert.equal(b.run('PER.fim'),'2026-10-09');});
test('rejected cache access preserves data and does not issue live read',async()=>{const b=boot();const before=b.run('API');b.ctx.fetch=async()=>{b.calls.push('cache');return{status:403,ok:false};};await b.run('carrega()');assert.equal(b.calls.length,1);assert.equal(b.run('API'),before);});
test('inline script is admitted by exact CSP hash',()=>{const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>!m[1].includes('src='));assert.equal(scripts.length,1);const hash=crypto.createHash('sha256').update(scripts[0][2]).digest('base64');assert(html.includes("'sha256-"+hash+"'"));});
test('month preset follows month rollover while source rows remain unchanged',()=>{const b=boot('2026-10-31T15:00:00Z');const before=JSON.stringify(b.run('API'));b.setClock('2026-11-01T15:00:00Z');b.run('render()');assert.equal(b.run('PER.ini'),'2026-11-01');assert.equal(b.run('PER.fim'),'2026-11-01');assert.equal(JSON.stringify(b.run('API')),before);});
test('fresh Aristo read follows the same active preset without showing Fish posts',async()=>{const b=boot();b.run("MARCA='aristo'");b.setClock('2026-10-09T12:00:00Z');b.run('API._cache_gerado_em=new Date().toISOString()');await b.run('carrega()');assert.equal(b.run('PER.fim'),'2026-10-09');assert.deepEqual(Array.from(b.painted.at(-1),p=>p.post_id),['synthetic-aristo-new']);});
