'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const API=require('../n8n/growth/segment-campaign-binding-api.cjs'),F=require('./segment-campaign-binding-fixture.cjs'),CF=require('./growth-campaign-audience-fixture.cjs');
const {C}=CF,headers={Authorization:'Bearer synthetic-manager-key'},read={acao:C.ACTIONS.read,brand:'fish',campaign_id:'100'},inspect={acao:C.ACTIONS.inspect,brand:'fish',campaign_id:100,audience_id:CF.audience.id,audience_revision:1};
test('local HTTP boundary enforces exact methods, Bearer authentication, origin, fields and numeric GET IDs',()=>{
 assert.equal(API.ENABLED,false);assert.equal(API.parse({method:'GET',request:{headers,query:read}}).request.campaign_id,100);assert.equal(API.parse({method:'POST',request:{headers,body:inspect}}).route,'execute');
 for(const p of [{method:'GET',request:{headers,query:inspect}},{method:'POST',request:{headers,body:{...inspect,actor:'panel:forged'}}},{method:'POST',request:{headers,body:{...inspect,caps:['draft']}}},{method:'GET',request:{headers:{...headers,authorization:headers.Authorization},query:read}},{method:'GET',request:{headers:{...headers,origin:'https://evil.test'},query:read}},{method:'GET',request:{headers,query:{...read,key:'a-secret'}}},{method:'POST',request:{headers,body:inspect,query:{extra:'value'}}}])assert.equal(API.parse(p).route,'response');
 for(const id of ['01','1e2',' 100','100.0',0,-1])assert.equal(API.parse({method:'GET',request:{headers,query:{...read,campaign_id:id}}}).route,'response');
});
test('malformed provider output or thrown secrets project to static uncertain writes and unavailable reads',async()=>{
 const binding={acao:C.ACTIONS.bind,...CF.intent(),idempotency_key:'operation-0001'},api=API.createCampaignBindingAPI({store:{execute:async()=>{throw Error('private credential');}}});
 const r=await api.handle({method:'POST',request:{headers,body:binding}});assert.equal(r.status,202);assert.deepEqual(r.body,{error:'SEGMENT_BINDING_UNCONFIRMED',state:'unconfirmed',idempotency_key:binding.idempotency_key,automatic_retry:false});assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(api.enabled,false);
 assert.equal((await api.handle({method:'POST',request:{headers,body:inspect}})).status,503);
 const polluted=API.createCampaignBindingAPI({store:{execute:async()=>({_http:201,_body:{binding:{...CF.bound(binding),email:'private@example.test'},transport_supported:false}})}});const out=await polluted.handle({method:'POST',request:{headers,body:binding}});assert.equal(out.status,202);assert.doesNotMatch(JSON.stringify(out),/private|email/);
});
test('browser plus HTTP candidate plus actual durable store recovers lost ACK for both brands without POST replay',async t=>{
 const db=new PGlite();t.after(()=>db.close());const f=await F.setup(db),api=API.createCampaignBindingAPI({store:f.service}),ui=CF.fixture();let lose=false,posts=0;
 const fetch=async(url,init)=>{const p=init.method==='GET'?Object.fromEntries(new URL(url).searchParams):JSON.parse(init.body),r=await api.handle({method:init.method,request:{headers:init.headers,[init.method==='GET'?'query':'body']:p}});if(p.acao===C.ACTIONS.bind){posts++;if(lose)throw Error('lost ACK after durable commit');}return {status:r.status,text:async()=>JSON.stringify(r.body)};};
 for(const [brand,id]of [['fish',100],['aristo',200]]){const a=await f.createAudience(brand,'browser-'+brand),c=ui.create(brand,id,{fetch}),s=await c.read();assert.equal(s.binding,null);const p=await c.inspect(id,{id:a.id,version:a.version});lose=true;await assert.rejects(c.bind(p.inspection.intent),{code:'SEGMENT_BINDING_OPERATION_UNCONFIRMED'});lose=false;const restored=ui.create(brand,id,{fetch}),done=await restored.consult();assert.equal(done.operation.phase,'confirmed');assert.equal(done.binding.audience_id,a.id);assert.equal(done.binding.campaign_version,(await f.current(id)).version);assert.equal(done.binding.authorizes_send,false);assert.equal((await f.bound(id)).binding_version,1);await assert.rejects(f.legacySchedule(id),/SEGMENT_CAMPAIGN_SELECTOR_REQUIRED/);}
 assert.equal(posts,2);assert.equal((await db.query('SELECT count(*)::int n FROM crm_audience_v2.campaign_binding_request')).rows[0].n,2);
 const a=await f.createAudience('fish','wrong-base'),c=ui.create('fish',300,{fetch});await assert.rejects(c.inspect(300,{id:a.id,version:a.version}),e=>e.code==='SEGMENT_BINDING_BASE_REQUIRED'&&e.baseList.id===17&&typeof e.baseList.name==='string');assert.equal((await db.query('SELECT list_id FROM campaign_lists WHERE campaign_id=300')).rows[0].list_id,101);
});
test('leaf archived after inspection yields durable 422; consultation and fresh GET resolve rejection without a second POST',async t=>{
 const db=new PGlite();t.after(()=>db.close());const f=await F.setup(db),api=API.createCampaignBindingAPI({store:f.service}),ui=CF.fixture(),calls=[];
 const fetch=async(url,init)=>{const p=init.method==='GET'?Object.fromEntries(new URL(url).searchParams):JSON.parse(init.body);calls.push(p);const r=await api.handle({method:init.method,request:{headers:init.headers,[init.method==='GET'?'query':'body']:p}});return {status:r.status,text:async()=>JSON.stringify(r.body)};};
 for(const [brand,id,leaf]of [['fish',100,101],['aristo',200,201]]){const a=await f.createAudience(brand,'leaf-'+brand,{op:'in_list',list_id:leaf}),c=ui.create(brand,id,{fetch}),s=await c.inspect(id,{id:a.id,version:a.version});await db.query("UPDATE lists SET status='archived' WHERE id=$1",[leaf]);await assert.rejects(c.bind(s.inspection.intent),{code:'SEGMENT_BINDING_OPERATION_UNCONFIRMED'});assert.equal(c.pending(),true);const done=await c.consult();assert.equal(done.operation.phase,'rejected');assert.deepEqual(done.operation.receipt,{status:422,body:{error:'SEGMENT_LIST_UNAVAILABLE'}});assert.equal(done.binding,null);assert.equal(c.pending(),false);assert.deepEqual(calls.slice(-2).map(p=>p.acao),[C.ACTIONS.operation,C.ACTIONS.read]);}
 assert.equal(calls.filter(p=>p.acao===C.ACTIONS.bind).length,2);assert.equal((await db.query('SELECT count(*)::int n FROM crm_audience_v2.campaign_binding')).rows[0].n,0);
 assert.equal(C.validation.rejected({status:422,body:{error:'SEGMENT_LIST_UNAVAILABLE'}}),true);for(const status of [400,401,403,404,409,503])assert.equal(C.validation.rejected({status,body:{error:'SEGMENT_LIST_UNAVAILABLE'}}),false);
});
