'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const V1=require('../n8n/growth/segment-shopify-sync-patch.cjs'),P=require('../n8n/growth/segment-shopify-product-sync-patch.cjs'),S=require('../n8n/growth/segment-shopify-service-patch.cjs'),Fixture=require('./fixtures/segment-shopify-sync.cjs');
const by=(w,n)=>w.nodes.find(x=>x.name===n),shop=b=>'synthetic-'+b;
function installed(brand){let w=V1.patchWorkflow(Fixture.workflow(brand),{brand,shop:shop(brand),revision:P.OLD_REVISION,expectedVersionId:'fixture-v1-'+brand}).workflow;w.versionId='fixture-products-'+brand;const customer=fs.readFileSync(path.join(__dirname,'../n8n/growth/segment-shopify-customer-bulk.graphql'),'utf8'),mutation='mutation CrmAudienceRunCustomerBulk($query: String!) { bulkOperationRunQuery(query: $query) { bulkOperation { id status } userErrors { field message } } }';by(w,'Bulk Clientes — Start').parameters.jsonBody=`={{ ${JSON.stringify({query:mutation,variables:{query:customer}})} }}`;w=P.patchProductWorkflow(w,{brand,shop:shop(brand),revision:'crm-shopify-product-evidence-20260929-v2',expectedVersionId:w.versionId}).workflow;return w;}
for(const brand of ['fish','aristo'])test(brand+': restores legacy Customer and delegates only after legacy graph',()=>{const before=installed(brand),after=S.transformServiceLayer(before,{brand,serviceUrl:'https://crm-shopify-sync.internal',credential:{id:'cred-1',name:'private sync'},expectedVersionId:before.versionId}).workflow;
 const customer=fs.readFileSync(path.join(__dirname,'../n8n/growth/segment-shopify-customer-bulk.graphql'),'utf8'),start=JSON.parse(by(after,'Bulk Clientes — Start').parameters.jsonBody);assert.equal(start.variables.query,customer);assert.deepEqual(after.connections,before.connections);assert.deepEqual(by(after,'Todo dia 03h'),by(before,'Todo dia 03h'));
 const unchanged=before.nodes.filter(n=>!['Bulk Clientes — Start',P.CRM.evidence,P.CRM.ingest].includes(n.name));for(const node of unchanged)assert.deepEqual(by(after,node.name),node);
 assert.equal(by(after,P.CRM.ingest).type,'n8n-nodes-base.httpRequest');assert.equal(by(after,P.CRM.ingest).retryOnFail,false);assert.equal(by(after,P.CRM.ingest).parameters.options.timeout,5000);assert.equal(by(after,P.CRM.ingest).parameters.jsonBody,'={{ $json }}');
 const rows=new vm.Script('(function(){'+by(after,P.CRM.evidence).parameters.jsCode+'})()').runInNewContext({Date:class extends Date{constructor(){super('2026-09-29T06:00:00Z');}}});assert.deepEqual(JSON.parse(JSON.stringify(rows)),[{json:{brand,idempotency_key:'shopify-products:'+brand+':2026-09-29',scheduled_for:'2026-09-29T00:00:00.000Z'}}]);
});
for(const brand of ['fish','aristo'])test(brand+': pending fallback restores Customer and replaces only V2 evidence/ingest with inert receipts',()=>{const before=installed(brand),result=S.transformPendingLayer(before,{brand,expectedVersionId:before.versionId}),after=result.workflow;
 const customer=fs.readFileSync(path.join(__dirname,'../n8n/growth/segment-shopify-customer-bulk.graphql'),'utf8'),start=JSON.parse(by(after,'Bulk Clientes — Start').parameters.jsonBody);assert.equal(start.variables.query,customer);assert.deepEqual(after.connections,before.connections);assert.deepEqual(after.settings,before.settings);assert.deepEqual(by(after,'Todo dia 03h'),by(before,'Todo dia 03h'));
 const unchanged=before.nodes.filter(n=>!['Bulk Clientes — Start',P.CRM.evidence,P.CRM.ingest].includes(n.name));for(const node of unchanged)assert.deepEqual(by(after,node.name),node);
 for(const [name,stage] of [[P.CRM.evidence,'evidence'],[P.CRM.ingest,'ingest']]){const node=by(after,name);assert.equal(node.type,'n8n-nodes-base.code');assert.equal(node.typeVersion,2);assert.equal(node.credentials,undefined);const rows=new vm.Script('(function(){'+node.parameters.jsCode+'})()').runInNewContext();assert.deepEqual(JSON.parse(JSON.stringify(rows)),[{json:{status:'collector_pending',brand,stage,products_collected:false,database_written:false,delegated:false}}]);assert.doesNotMatch(node.parameters.jsCode,/https?:|postgres|shopify_ingest|secret|credential/i);}
 assert.deepEqual(result.changes,{brand,restored_customer_query:true,collector_pending:true,product_sync_disabled:true,schedule_changed:false,connections_changed:false});
});
test('production wrapper pins exact active versions and layer rejects source or graph drift',()=>{const w=installed('fish');assert.throws(()=>S.patchShopifyServiceWorkflow(w,{brand:'fish',serviceUrl:'https://sync.internal',credential:{id:'x',name:'x'}}),/VERSION_DRIFT/);for(const mutate of [x=>x.nodes.push({...x.nodes[0],id:'extra',name:'extra'}),x=>by(x,'Bulk Clientes — Start').parameters.jsonBody+=' ',x=>by(x,P.CRM.ingest).parameters.query+=' ',x=>x.connections[P.CRM.evidence].main[0][0].node='Auto-Reconciliação (Postgres)']){const x=installed('fish');mutate(x);assert.throws(()=>S.transformServiceLayer(x,{brand:'fish',serviceUrl:'https://sync.internal',credential:{id:'x',name:'x'},expectedVersionId:x.versionId}),/(NODE|SOURCE|SCHEDULE|CONNECTION)_DRIFT/);}});
test('pending production wrapper pins exact versions and rejects source or graph drift',()=>{const w=installed('fish');assert.throws(()=>S.patchShopifyServicePendingWorkflow(w,{brand:'fish'}),/VERSION_DRIFT/);for(const mutate of [x=>x.nodes.push({...x.nodes[0],id:'extra',name:'extra'}),x=>by(x,'Bulk Clientes — Start').parameters.jsonBody+=' ',x=>by(x,P.CRM.ingest).parameters.query+=' ',x=>x.connections[P.CRM.evidence].main[0][0].node='Auto-Reconciliação (Postgres)']){const x=installed('fish');mutate(x);assert.throws(()=>S.transformPendingLayer(x,{brand:'fish',expectedVersionId:x.versionId}),/(NODE|SOURCE|SCHEDULE|CONNECTION)_DRIFT/);}});
function productionPending(brand,versionId){const source=installed(brand);by(source,'Todo dia 03h').parameters={rule:{interval:[{field:'cronExpression',expression:brand==='fish'?'30 3 * * *':'0 3 * * *'}]}};const pending=S.transformPendingLayer(source,{brand,expectedVersionId:source.versionId}).workflow;pending.id=S.PINS[brand].id;pending.versionId=versionId;return {source,pending};}
for(const brand of ['fish','aristo'])test(brand+': exact pending fallback advances to the same delegated workflow',()=>{
 const versionId='pending-current-'+brand,{source,pending}=productionPending(brand,versionId),options={brand,expectedVersionId:versionId,serviceUrl:'https://crm-shopify-sync.internal:8443/',credential:{id:'cred-active',name:'Private sync'}};
 source.id=S.PINS[brand].id;source.versionId=versionId;
 const actual=S.patchShopifyServicePendingToActiveWorkflow(pending,options),expected=S.transformServiceLayer(source,options);
 assert.deepEqual(actual,expected);assert.deepEqual(actual.workflow.settings,pending.settings);assert.deepEqual(by(actual.workflow,'Config'),by(pending,'Config'));
});
test('pending-to-active requires the fresh version and exact pinned pending literals',()=>{
 const versionId='pending-current-fish',make=()=>productionPending('fish',versionId).pending,options={brand:'fish',expectedVersionId:versionId,serviceUrl:'https://sync.internal',credential:{id:'cred-1',name:'Private sync'}};
 assert.throws(()=>S.patchShopifyServicePendingToActiveWorkflow(make(),{...options,expectedVersionId:undefined}),/VERSION_DRIFT/);
 assert.throws(()=>S.patchShopifyServicePendingToActiveWorkflow(make(),{...options,expectedVersionId:'stale-version'}),/VERSION_DRIFT/);
 for(const mutate of [x=>x.id='wrong-workflow',x=>by(x,'Todo dia 03h').parameters={rule:{interval:[{field:'hours',hoursInterval:1}]}},x=>x.connections[P.CRM.evidence].main[0][0].node='Auto-Reconciliação (Postgres)',x=>by(x,'Bulk Clientes — Start').parameters.jsonBody+=' ',x=>by(x,P.CRM.evidence).parameters.jsCode+=' ',x=>by(x,P.CRM.ingest).credentials={postgres:{id:'new',name:'new'}}]){
  const workflow=make();mutate(workflow);assert.throws(()=>S.patchShopifyServicePendingToActiveWorkflow(workflow,options),/(VERSION|SCHEDULE|CONNECTION|SOURCE)_DRIFT/);
 }
 assert.throws(()=>S.patchShopifyServicePendingToActiveWorkflow(make(),{...options,serviceUrl:'http://sync.internal'}),/SERVICE_CONFIG/);
 assert.throws(()=>S.patchShopifyServicePendingToActiveWorkflow(make(),{...options,credential:{id:'cred-1',name:'Private sync',token:'forbidden'}}),/SERVICE_CONFIG/);
});
