'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const M=require('../n8n/growth/segment-audience-allocated.cjs'),F=require('./segment-audience-allocated-fixture.cjs');
async function setup(t){const db=new PGlite();t.after(()=>db.close());return F.setup(db);}
test('both brands review only allocated members with nested AND/OR and mutually exclusive reasons; outside base members are never admitted',async t=>{
 const f=await setup(t);for(const brand of ['fish','aristo']){const [a,b]=brand==='fish'?[101,102]:[201,202];
  for(const op of ['and','or']){const p=F.args(brand,{op,rules:[F.leaf(a),F.leaf(b),F.leaf(a)]}),r=await f.resolve(p);assert.equal(r.source_confirmed,true);assert.equal(r.unknown_reason,null);assert.deepEqual(r.members.filter(m=>m.eligible).map(m=>m.subscriber_id),brand==='fish'?(op==='and'?[1]:[1,2,3]):(op==='and'?[7]:[7,8]));assert.ok(!r.members.some(m=>[13,14].includes(m.subscriber_id)));assert.equal(r.members.length,brand==='fish'?8:2);for(const arm of r.arms){assert.equal(arm.allocated,arm.eligible+arm.excluded);assert.ok(arm.revoked+arm.missing<=arm.excluded);}assert.ok(Object.isFrozen(r.members));}
 }
 const r=await f.resolve(F.args('fish',{op:'and',rules:[F.leaf(101),F.leaf(102)]}));assert.deepEqual(r.members.map(m=>m.reason),['eligible','rule','rule','global_disabled','global_disabled','base_consent','missing','revoked']);assert.deepEqual(r.arms,[{arm:'a',allocated:4,eligible:1,excluded:3,revoked:0,missing:1},{arm:'b',allocated:4,eligible:0,excluded:4,revoked:1,missing:0}]);
 assert.equal(M.ENABLED,false);
});
test('revoked takes precedence over missing/global/consent; subscriber deletion preserves denominator and does not change assignment',async t=>{
 const f=await setup(t),p=F.args(),before=(await f.db.query('SELECT * FROM crm_ab_member_v2 ORDER BY test_id,subscriber_id')).rows;
 await f.db.query('DELETE FROM subscribers WHERE id=1');let r=await f.resolve(p);assert.equal(r.members.find(m=>m.subscriber_id===1).reason,'missing');assert.equal(r.arms.reduce((n,a)=>n+a.allocated,0),8);assert.equal(r.members.find(m=>m.subscriber_id===10).reason,'revoked');
 await f.db.query("UPDATE crm_ab_member_v2 SET revoked_at='2025-02-01T00:00:00Z' WHERE test_id=$1 AND subscriber_id=4",[F.TESTS.fish]);r=await f.resolve(p);assert.equal(r.members.find(m=>m.subscriber_id===4).reason,'revoked');assert.equal(r.arms[1].revoked,2);assert.equal(r.arms[1].missing,0);
 await f.db.exec("UPDATE subscribers SET status='enabled' WHERE id=4;UPDATE subscriber_lists SET status='confirmed' WHERE subscriber_id=4");r=await f.resolve(p);assert.equal(r.members.find(m=>m.subscriber_id===4).eligible,false);assert.equal(r.members.find(m=>m.subscriber_id===4).reason,'revoked');
 const after=(await f.db.query('SELECT * FROM crm_ab_member_v2 ORDER BY test_id,subscriber_id')).rows;assert.deepEqual(after.map(({revoked_at,...x})=>x),before.map(({revoked_at,...x})=>x));
});
test('base opt-in and exact membership evidence recheck consent, while missing leaf membership is an exclusion not an unknown source',async t=>{
 const f=await setup(t),p=F.args('fish',F.leaf(102));let r=await f.resolve(p);assert.equal(r.members.find(m=>m.subscriber_id===2).reason,'rule');await f.db.exec("UPDATE lists SET optin='single' WHERE id=102");r=await f.resolve(p);assert.equal(r.members.find(m=>m.subscriber_id===2).eligible,true);
 await f.db.exec("UPDATE lists SET optin='double' WHERE id=17;UPDATE subscriber_lists SET status='unconfirmed' WHERE list_id=17 AND subscriber_id=2;DELETE FROM subscriber_lists WHERE subscriber_id=1 AND list_id=102");r=await f.resolve(p);assert.equal(r.source_confirmed,true);assert.equal(r.members.find(m=>m.subscriber_id===1).reason,'rule');assert.equal(r.members.find(m=>m.subscriber_id===2).reason,'base_consent');
});
test('native source unavailable, brand mismatch, malformed allocation totals and empty allocation return all unknown without IDs',async t=>{
 const f=await setup(t);for(const sql of ["UPDATE lists SET status='archived' WHERE id=101","UPDATE lists SET status='active',tags=ARRAY['aristo'] WHERE id=101","UPDATE lists SET tags=ARRAY['fish'],optin='invalid' WHERE id=101"]){await f.db.exec(sql);const r=await f.resolve(F.args());assert.equal(r.unknown_reason,'list_source_unavailable');assert.equal(r.members,null);assert.equal(r.arms,null);}
 await f.db.exec("UPDATE lists SET optin='single' WHERE id=101");let r=await f.resolve({...F.args(),testId:F.TESTS.aristo});assert.equal(r.unknown_reason,'allocation_unavailable');assert.equal(r.members,null);
 await f.db.query('UPDATE crm_ab_arm_v2 SET allocated_count=allocated_count+1 WHERE test_id=$1 AND arm=$2',[F.TESTS.fish,'a']);r=await f.resolve(F.args());assert.equal(r.unknown_reason,'allocation_malformed');assert.equal(r.members,null);
 await f.db.query('DELETE FROM crm_ab_member_v2 WHERE test_id=$1',[F.TESTS.fish]);r=await f.resolve(F.args());assert.equal(r.unknown_reason,'allocation_unavailable');assert.equal(r.members,null);assert.equal(r.arms,null);
});
test('malformed persisted revocation and a removed member never silently shrink or restore eligibility',async t=>{
 const f=await setup(t);await f.db.query("UPDATE crm_ab_member_v2 SET revoked_at='infinity'::timestamptz WHERE test_id=$1 AND subscriber_id=10",[F.TESTS.fish]);let r=await f.resolve(F.args());assert.equal(r.unknown_reason,'allocation_malformed');assert.equal(r.members,null);
 await f.db.query('DELETE FROM crm_ab_member_v2 WHERE test_id=$1 AND subscriber_id=10',[F.TESTS.fish]);r=await f.resolve(F.args());assert.equal(r.unknown_reason,'allocation_malformed');assert.equal(r.members,null);
});
test('external leaf even inside a true OR makes the entire review unknown and does not query allocation/base tables',async t=>{
 const f=await setup(t),p=F.args('fish',{op:'or',rules:[F.leaf(101),{op:'condition',field:'purchase.count',operator:'eq',value:0}]});const q=M.compileAllocated(p);assert.doesNotMatch(q.text,/public\.(crm_ab_member_v2|subscribers|subscriber_lists|lists)\b/);const r=await f.resolve(p);assert.deepEqual({...r,checked_at:null},{source_confirmed:false,unknown_reason:'external_source_unavailable',checked_at:null,members:null,arms:null});
});
test('allocation limit applies before member/person locks; 100001 is refused and 100000 retains missing allocations',async t=>{
 const f=await setup(t);await f.db.query('DELETE FROM crm_ab_member_v2 WHERE test_id=$1',[F.TESTS.fish]);await f.db.query("INSERT INTO crm_ab_member_v2(test_id,subscriber_id,arm) SELECT $1::uuid,n,CASE WHEN n%2=1 THEN 'a' ELSE 'b' END FROM generate_series(1,100001)n",[F.TESTS.fish]);await f.db.query('UPDATE crm_ab_arm_v2 a SET allocated_count=(SELECT count(*) FROM crm_ab_member_v2 m WHERE m.test_id=a.test_id AND m.arm=a.arm) WHERE a.test_id=$1',[F.TESTS.fish]);await assert.rejects(f.resolve(F.args()),{code:'AUDIENCE_ALLOCATED_LIMIT'});
 const def=(await f.db.query("SELECT pg_get_functiondef('crm_audience_v2.ab_audience_allocated_source(text,integer[],uuid,integer,jsonb)'::regprocedure) definition")).rows[0].definition;assert.match(def,/member_candidates AS MATERIALIZED[\s\S]*LIMIT 100001/);assert.ok(def.indexOf('(SELECT count(*) FROM member_candidates)>100000')<def.indexOf('FOR SHARE OF m'));assert.ok(def.indexOf('subscriber_lock_barrier.n<=100000')<def.indexOf('FOR SHARE OF sl'));
 await f.db.query('DELETE FROM crm_ab_member_v2 WHERE test_id=$1 AND subscriber_id=100001',[F.TESTS.fish]);await f.db.query("UPDATE crm_ab_arm_v2 SET allocated_count=50000 WHERE test_id=$1",[F.TESTS.fish]);const r=await f.resolve(F.args());assert.equal(r.members.length,100000);assert.equal(r.arms[0].allocated,50000);assert.equal(r.arms[1].allocated,50000);assert.equal(r.members.at(-1).reason,'missing');
});
test('query enforces RC and real timeouts; compiler parameters are bounded and never enumerate an unallocated base',async t=>{
 const f=await setup(t);for(const [setting,value]of [['statement_timeout','0'],['statement_timeout','30001ms'],['lock_timeout','0'],['lock_timeout','501ms']]){await f.db.exec('SET '+setting+"='"+value+"'");await assert.rejects(f.resolve(F.args()),{code:'AUDIENCE_ALLOCATED_BOUNDARY'});await f.db.exec("SET statement_timeout='20s';SET lock_timeout='500ms'");}
 await f.db.transaction(async tx=>{await tx.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await assert.rejects(M.resolveAllocated({...F.args(),query:tx.query.bind(tx)}),{code:'AUDIENCE_ALLOCATED_BOUNDARY'});});
 const p=M.compileAllocated(F.args());assert.match(p.text,/crm_audience_v2\.ab_audience_allocated_source/);assert.doesNotMatch(p.text,/public\.|\bINSERT\b|\bUPDATE\b|\bDELETE\b|\bSET\b/);assert.equal(p.values[2],F.TESTS.fish);assert.equal(p.values[3],17);assert.deepEqual(p.values[4],F.args().definition.rule);assert.throws(()=>M.compileAllocated({...F.args(),testId:'no-uuid'}),{code:'AUDIENCE_ALLOCATED_TEST'});
});
test('private response validates IDs, revocation/reason precedence, sorted arms and exact recomputed counters',async()=>{
 const now=new Date().toISOString(),good={source_confirmed:true,unknown_reason:null,checked_at:now,members:[{subscriber_id:1,arm:'a',revoked_at:null,reason:'eligible',eligible:true},{subscriber_id:2,arm:'b',revoked_at:null,reason:'missing',eligible:false}],arms:[{arm:'a',allocated:1,eligible:1,excluded:0,revoked:0,missing:0},{arm:'b',allocated:1,eligible:0,excluded:1,revoked:0,missing:1}]};
 for(const change of [r=>r.members[1].subscriber_id=1,r=>r.members[0].eligible=false,r=>r.members[1].revoked_at=now,r=>r.members[1].reason='revoked',r=>r.arms[1].missing=0,r=>r.arms.reverse(),r=>r.members[0].email='private@example.test',r=>r.checked_at='2001-01-01',r=>r.members=[],r=>r.source_confirmed=false]){const r=structuredClone(good);change(r);let calls=0;await assert.rejects(M.resolveAllocated({...F.args(),query:async()=>{calls++;return {rows:[r]};}}),{code:'AUDIENCE_ALLOCATED_UNCONFIRMED'});assert.equal(calls,1);}
 const r=await M.resolveAllocated({...F.args(),query:async()=>({rows:[good]})});assert.equal(r.arms[1].missing,1);await assert.rejects(M.resolveAllocated({...F.args(),query:async()=>{throw Error('private transport context');}}),e=>e.code==='AUDIENCE_ALLOCATED_UNCONFIRMED'&&!e.message.includes('private'));
});
test('abort and deadline never retry and cannot accept late success; allocation remains untouched',async()=>{
 for(const external of [false,true]){const controller=new AbortController();let calls=0,seen,finish;const running=M.resolveAllocated({...F.args(),signal:controller.signal,timeoutMs:20,query:(_q,_v,{signal})=>{calls++;seen=signal;return new Promise(resolve=>finish=resolve);}});if(external)setTimeout(()=>controller.abort(),5);await assert.rejects(running,{code:external?'AUDIENCE_ALLOCATED_ABORTED':'AUDIENCE_ALLOCATED_TIMEOUT'});assert.equal(calls,1);assert.equal(seen.aborted,true);finish({rows:[]});await new Promise(r=>setImmediate(r));assert.equal(calls,1);}
 const signal=AbortSignal.abort();await assert.rejects(M.resolveAllocated({...F.args(),signal,query:()=>{throw Error('must not query');}}),{code:'AUDIENCE_ALLOCATED_ABORTED'});
});
