const test=require('node:test'),assert=require('node:assert/strict');const S=require('../growth-ses.js');
const now=Date.parse('2026-09-15T01:00:00Z');
const brand=marca=>({marca,finalizacao_pendente:0,entregue_sem_gravacao:0,resultado_incerto:0,sem_confirmacao_15min:0,falhas_24h:0,reclamacoes_24h:0});
const fixture=()=>({crm_email_ses:{health:{schema_version:1,checked_at:'2026-09-15T00:59:00Z',collector:{last_poll_ok_at:'2026-09-15T00:59:50Z',last_poll_count:0},queue:{checked_at:'2026-09-15T00:59:50Z',visible:0,inflight:0,delayed:0},pending_ingest_15min:0,conflicts:0,brands:[brand('fish'),brand('aristo')]}}});
test('healthy empty poll is evidence of polling, not a delivery guarantee',()=>{const x=S.health(fixture(),'todas',now);assert.equal(x.alerts.length,2);assert.match(x.alerts[0].text,/Consulta à fila/);assert.equal(x.alerts[0].level,'ok');});
test('delivered but unfinalized messages and recent collector errors stay visible',()=>{const a=fixture();a.crm_email_ses.health.brands[1].entregue_sem_gravacao=108;a.crm_email_ses.health.brands[1].finalizacao_pendente=108;a.crm_email_ses.health.collector.last_error_at='2026-09-15T00:58:00Z';const text=S.health(a,'aristo',now).alerts.map(a=>a.text).join(' ');assert.match(text,/108.*registro incompleto/);assert.match(text,/falha no processamento/);assert.doesNotMatch(S.health(a,'fish',now).alerts.map(a=>a.text).join(' '),/108/);});
test('old, absent, future and malformed diagnostics never imply healthy operation',()=>{for(const change of [a=>delete a.crm_email_ses.health,a=>a.crm_email_ses.health.checked_at='2020-01-01',a=>a.crm_email_ses.health.checked_at='2027-01-01']){const a=fixture();change(a);assert.equal(S.health(a,'todas',now).alerts.some(a=>a.level==='ok'),false);}const a=fixture();a.crm_email_ses.health.collector.last_poll_ok_at=null;assert.equal(S.health(a,'todas',now).alerts.some(a=>a.level==='ok'),false);a.crm_email_ses.health.brands[0].falhas_24h='0';assert.match(S.health(a,'fish',now).alerts.map(a=>a.text).join(' '),/diagnóstico.*indisponível/);});
test('collector interruption and conflicts are global; failures and uncertainty are brand scoped',()=>{const a=fixture(),h=a.crm_email_ses.health;h.collector.last_poll_ok_at='2026-09-15T00:50:00Z';h.conflicts=2;h.brands[0].resultado_incerto=1;h.brands[1].falhas_24h=3;assert.match(S.health(a,'fish',now).alerts.map(a=>a.text).join(' '),/cinco minutos.*2 eventos.*1 envios/s);assert.doesNotMatch(S.health(a,'fish',now).alerts.map(a=>a.text).join(' '),/3 falhas/);});

test('queue backlog warns and stale queue counts do not masquerade as zero',()=>{const a=fixture();a.crm_email_ses.health.queue.visible=300;assert.match(S.health(a,'fish',now).alerts.find(x=>x.text.startsWith('Fila SES')).text,/300 eventos/);a.crm_email_ses.health.queue.error_at='2026-09-15T01:00:00Z';assert.match(S.health(a,'fish',now).alerts.map(x=>x.text).join(' '),/Tamanho da fila sem medição/);});
