'use strict';
const fs=require('node:fs'),path=require('node:path');
const esbuild=require('esbuild');
const root=path.resolve(__dirname,'../..');
(async()=>{
 const result=await esbuild.build({entryPoints:[path.join(__dirname,'entry.js')],bundle:true,write:false,
  platform:'browser',format:'iife',globalName:'ShrigmaCampaignRuntime',target:'es2020',minify:true,
  legalComments:'eof',banner:{js:'/* Generated by tools/campaign-runtime-build/build.cjs. Server only. */\nvar URL;'},
  footer:{js:'URL=ShrigmaCampaignRuntime.URL;'},
  plugins:[{name:'no-native-crypto',setup(build){
   build.onResolve({filter:/^node:crypto$/},()=>({path:'native-crypto-unavailable',namespace:'closed'}));
   build.onLoad({filter:/.*/,namespace:'closed'},()=>({contents:'export function createHash(){throw new Error("Native crypto unavailable: use configured runtime hash");}',loader:'js'}));
  }}]});
 const content=result.outputFiles[0].text,dest=path.join(root,'n8n/growth/campaign-runtime.bundle.js');
 if(process.argv.includes('--check')){
  if(!fs.existsSync(dest)||fs.readFileSync(dest,'utf8')!==content)throw Error('Campaign runtime bundle differs from its sources; rebuild.');
  console.log('Campaign runtime bundle matches pinned sources.');
 }else {fs.writeFileSync(dest,content);console.log(`Campaign runtime bundle generated (${Buffer.byteLength(content)} bytes).`);}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
