'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const runtime=process.env.SCHEDULER_STATE_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const modulePath=path.join(runtime,'native-scheduler-state-chat-approval.cjs');
const C=require(fs.existsSync(modulePath)?modulePath:path.resolve(__dirname,'../../services/dashboard-operational/native-scheduler-state-chat-approval.cjs'));
const CID='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222';
const H=x=>crypto.createHash('sha256').update(x).digest('hex'),MAC=(k,x)=>crypto.createHmac('sha256',k).update(x).digest('hex');
function fixture(options={}){
 const f={now:Date.parse('2026-10-09T15:00:00Z'),key:'disposable-test-key',revoked:false,scopes:['crm.read','crm.iam'],brands:['fish','aristo'],callbacks:[],calls:[],mod:{},token:'b'.repeat(43)};
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE crm_native_connections_v1(id TEXT PRIMARY KEY,scopes_json TEXT);CREATE TABLE crm_native_delivery_health_consent_v1(receipt TEXT);CREATE TABLE crm_scheduler_read_consent_v1(receipt TEXT);CREATE TABLE callback_fixture(id TEXT PRIMARY KEY);');db.prepare('INSERT INTO users VALUES(?)').run('private-fixture-owner');for(const id of [CID,OTHER])db.prepare('INSERT INTO crm_native_connections_v1 VALUES(?,?)').run(id,JSON.stringify(f.scopes));db.prepare('INSERT INTO crm_native_delivery_health_consent_v1 VALUES(?)').run('accepted-browser-health');db.prepare('INSERT INTO crm_scheduler_read_consent_v1 VALUES(?)').run('accepted-worker-diagnostic');
 f.context={nativeBearer:f.token,method:'POST'};
 f.snapshot=()=>({ownerId:'private-fixture-owner',ownerRevision:H('owner-revision'),connectionHash:H(CID),crmBindingHash:H('two-original-brands'),profileRevision:MAC(f.key,'real-profile-revision'),credentialBindingHash:H('private-pg-profile-binding'),resourceHash:C.resourceHash,queryHash:C.queryHash,...f.mod});
 const current=(context,id,needs)=>{f.calls.push(needs);assert.deepEqual(needs,C.CURRENT_NEEDS);assert.ok(Object.isFrozen(needs)&&Object.isFrozen(needs.scopes));if(f.revoked||context.nativeBearer!==f.token||id!==CID||!needs.scopes.every(s=>f.scopes.includes(s))||!needs.brands.every(b=>f.brands.includes(b)))throw Error('private-current-denial '+f.token);return f.booleanCurrent?true:f.snapshot();};
 const authorizeBoundApproval=async q=>{f.callbacks.push(q);assert.deepEqual(Object.keys(q).sort(),['approvalId','authority','connectionId','context']);assert.ok(Object.isFrozen(q.authority));assert.deepEqual(q.authority,f.snapshot());assert.equal(db.prepare('SELECT state FROM crm_scheduler_state_chat_intent_v1 WHERE id=?').get(q.approvalId).state,'consumed');
  // A real second SQLite transaction proves the caller committed its consume
  // transaction before calling the purpose store. No nested transaction.
  db.exec('BEGIN IMMEDIATE');db.prepare('INSERT INTO callback_fixture VALUES(?)').run(q.approvalId);db.exec('COMMIT');
  if(f.callback)await f.callback(q);if(f.throwCallback)throw Error('private-callback-secret '+f.token);if(f.answer!==undefined)return f.answer;return {authorized:true,purpose:C.PURPOSE,connectionId:CID,operational:false};};
 f.options={db,current,mac:x=>MAC(f.key,x),authorizeBoundApproval,now:()=>f.now,...options};f.bridge=C.createSchedulerStateChatApproval(f.options);f.db=db;
 f.prepare=()=>f.bridge.prepare({context:f.context,connectionId:CID});f.confirm=(intent,decision='approve')=>f.bridge.confirm({context:f.context,connectionId:CID,approvalId:intent.approvalId,intentHash:intent.intentHash,decision});f.status=intent=>f.bridge.status({context:{...f.context,method:'GET'},connectionId:CID,approvalId:intent.approvalId});f.close=()=>db.close();return f;
}
function safe(dto,f){const s=JSON.stringify(dto);for(const x of [f.token,'private-fixture-owner','private-callback-secret','private-current-denial','password','actor','issuer','SELECT'])assert.ok(!s.includes(x),x);}
test('resource and complete fixed query hash match the original pinned state module',()=>{const source=path.join(runtime,'native-scheduler-state.cjs');assert.ok(fs.existsSync(source),'Provide SCHEDULER_STATE_RUNTIME with the pinned/public runtime');const state=require(source);assert.equal(C.PURPOSE,state.PURPOSE);assert.equal(C.queryHash,state.queryHash);assert.equal(C.resourceHash,state.resourceHash);assert.equal(C.MAX_TTL_MS,600000);});
test('prepare/status neither call callback nor authorize automatically, reuse unchanged live intent',()=>{const f=fixture();try{const i=f.prepare();assert.equal(i.state,'prepared');assert.equal(i.authorized,false);assert.equal(i.operational,false);assert.match(i.intentHash,/^[a-f0-9]{64}$/);assert.equal(Date.parse(i.expiresAt)-Date.parse(i.createdAt),600000);assert.deepEqual(f.prepare(),i);assert.deepEqual(f.status(i),i);assert.equal(f.callbacks.length,0);safe(i,f);}finally{f.close();}});
test('exact approval is single-use, consumed before callback, and survives new bridge instance',async()=>{const f=fixture();try{const i=f.prepare(),r=await f.confirm(i);assert.equal(r.state,'approved');assert.equal(r.authorized,true);assert.equal(f.callbacks.length,1);assert.deepEqual(await f.confirm(i),r);f.bridge=C.createSchedulerStateChatApproval(f.options);assert.deepEqual(await f.confirm(i),r);assert.equal(f.callbacks.length,1);safe(r,f);}finally{f.close();}});
test('deny consumes the exact intent without callback and cannot later become approve',async()=>{const f=fixture();try{const i=f.prepare();assert.equal((await f.confirm(i,'deny')).state,'denied');assert.equal((await f.confirm(i)).state,'denied');assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('wrong hash is refused without consuming or calling callback',async()=>{const f=fixture();try{const i=f.prepare();await assert.rejects(f.confirm({...i,intentHash:H('different-intent')}),{code:'SCHEDULER_CHAT_INTENT_HASH_REFUSED'});assert.equal(f.status(i).state,'prepared');assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('booleans, auto/status decisions, actors, SQL and caller authority cannot confirm',async()=>{const f=fixture();try{const i=f.prepare();for(const decision of [true,false,'auto','status'])await assert.rejects(f.confirm(i,decision),{code:'SCHEDULER_CHAT_ARGUMENTS_REFUSED'});for(const [key,value] of [['actor','caller'],['issuer','caller'],['grant',true],['authority',f.snapshot()],['sql','SELECT 1']])await assert.rejects(f.bridge.confirm({context:f.context,connectionId:CID,approvalId:i.approvalId,intentHash:i.intentHash,decision:'approve',[key]:value}),{code:'SCHEDULER_CHAT_ARGUMENTS_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('boolean CURRENT and fabricated context are not owner/scopes grants',()=>{const f=fixture();try{f.booleanCurrent=true;assert.throws(f.prepare,{code:'SCHEDULER_CHAT_ARGUMENTS_REFUSED'});f.booleanCurrent=false;for(const context of [{method:'POST',admitted:true},{method:'POST',nativeBearer:true},{method:'POST',nativeBearer:'c'.repeat(43)}])assert.throws(()=>f.bridge.prepare({context,connectionId:CID}));assert.equal(f.callbacks.length,0);}finally{f.close();}});
for(const missing of ['crm.read','crm.iam','fish','aristo'])test('CURRENT refuses missing '+missing+' independently',()=>{const f=fixture();try{f.scopes=f.scopes.filter(x=>x!==missing);f.brands=f.brands.filter(x=>x!==missing);assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});
for(const field of C.AUTHORITY_FIELDS)test('changed '+field+' cannot confirm prepared intent',async()=>{const f=fixture();try{const i=f.prepare();f.mod[field]=field==='ownerId'?'other-owner':H('different-'+field);await assert.rejects(f.confirm(i));assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('revocation before confirmation prevents callback',async()=>{const f=fixture();try{const i=f.prepare();f.revoked=true;await assert.rejects(f.confirm(i),{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('revocation after consume but before callback microtask prevents callback and stays consumed',async()=>{const f=fixture();try{const i=f.prepare(),p=f.confirm(i);f.revoked=true;await assert.rejects(p,{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});assert.equal(f.callbacks.length,0);f.revoked=false;assert.equal(f.status(i).state,'uncertain');assert.equal((await f.confirm(i)).state,'uncertain');assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('revocation during callback suppresses approved DTO and never retries',async()=>{const f=fixture();try{const i=f.prepare();f.callback=()=>{f.revoked=true;};await assert.rejects(f.confirm(i),{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});f.revoked=false;assert.equal(f.status(i).state,'uncertain');assert.equal((await f.confirm(i)).state,'uncertain');assert.equal(f.callbacks.length,1);assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CONFIRMATION_UNCERTAIN'});}finally{f.close();}});
test('key rotation and record tampering refuse confirmation',async()=>{const f=fixture();try{const i=f.prepare();f.key='rotated-key';await assert.rejects(f.confirm(i),{code:'SCHEDULER_CHAT_INTEGRITY_REFUSED'});f.key='disposable-test-key';f.db.prepare('UPDATE crm_scheduler_state_chat_intent_v1 SET expires_at=expires_at+1 WHERE id=?').run(i.approvalId);await assert.rejects(f.confirm(i),{code:'SCHEDULER_CHAT_INTEGRITY_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('TTL maximum, expiry boundary and backwards clock are finite; expired intent cannot rearm',async()=>{const f=fixture({ttlMs:10});try{assert.throws(()=>C.createSchedulerStateChatApproval({...f.options,ttlMs:600001}),{code:'SCHEDULER_CHAT_CONFIGURATION_REFUSED'});const i=f.prepare();f.now+=10;assert.equal(f.status(i).state,'expired');assert.equal((await f.confirm(i)).state,'expired');f.now-=5;assert.equal((await f.confirm(i)).state,'expired');assert.equal(f.callbacks.length,0);f.now=Date.parse(i.createdAt)-1;assert.throws(()=>f.status(i),{code:'SCHEDULER_CHAT_CLOCK_REFUSED'});}finally{f.close();}});
test('concurrent confirmations execute only one callback with no nested SQLite transaction',async()=>{const f=fixture();let release,entered;const pending=new Promise(r=>entered=r),hold=new Promise(r=>release=r);try{const i=f.prepare();f.callback=async()=>{entered();await hold;};const first=f.confirm(i);await pending;const second=await f.confirm(i);assert.equal(second.state,'uncertain');assert.equal(f.callbacks.length,1);release();assert.equal((await first).state,'approved');assert.equal(f.callbacks.length,1);}finally{release?.();f.close();}});
for(const kind of ['throw','boolean','unknown','wrong-purpose'])test('callback '+kind+' stays consumed and exposes no raw error or protocol content',async()=>{const f=fixture();try{const i=f.prepare();if(kind==='throw')f.throwCallback=true;else if(kind==='boolean')f.answer=true;else if(kind==='unknown')f.answer={authorized:true,purpose:C.PURPOSE,connectionId:CID,operational:false,password:'secret'};else f.answer={authorized:true,purpose:'crm.delivery-health',connectionId:CID,operational:false};const r=await f.confirm(i);assert.equal(r.state,'uncertain');safe(r,f);assert.equal((await f.confirm(i)).state,'uncertain');f.bridge=C.createSchedulerStateChatApproval(f.options);assert.equal(f.status(i).state,'uncertain');assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CONFIRMATION_UNCERTAIN'});assert.equal(f.callbacks.length,1);}finally{f.close();}});
test('bounded callback timeout cannot be replayed even after late completion',async()=>{const f=fixture({callbackTimeoutMs:5});let release;const hold=new Promise(r=>release=r);try{const i=f.prepare();f.callback=()=>hold;const r=await f.confirm(i);assert.equal(r.state,'uncertain');release();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.status(i).state,'uncertain');assert.equal((await f.confirm(i)).state,'uncertain');assert.equal(f.callbacks.length,1);}finally{release?.();f.close();}});
test('status of a different connection and purpose injection cannot disclose or authorize intent',async()=>{const f=fixture();try{const i=f.prepare();assert.throws(()=>f.bridge.status({context:{...f.context,method:'GET'},connectionId:OTHER,approvalId:i.approvalId}),{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});assert.throws(()=>f.bridge.prepare({context:f.context,connectionId:CID,purpose:'crm.delivery-health'}),{code:'SCHEDULER_CHAT_ARGUMENTS_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('prepare and confirm require POST; status requires GET at the core boundary',async()=>{const f=fixture();try{const i=f.prepare(),get={...f.context,method:'GET'};assert.throws(()=>f.bridge.prepare({context:get,connectionId:CID}),{code:'SCHEDULER_CHAT_METHOD_REFUSED',status:405});await assert.rejects(f.bridge.confirm({context:get,connectionId:CID,approvalId:i.approvalId,intentHash:i.intentHash,decision:'approve'}),{code:'SCHEDULER_CHAT_METHOD_REFUSED',status:405});assert.throws(()=>f.bridge.status({context:f.context,connectionId:CID,approvalId:i.approvalId}),{code:'SCHEDULER_CHAT_METHOD_REFUSED',status:405});assert.equal(f.status(i).state,'prepared');assert.equal(f.callbacks.length,0);}finally{f.close();}});
test('expiry during callback cannot publish an approved outcome or retry',async()=>{const f=fixture();try{const i=f.prepare();f.callback=()=>{f.now+=600000;};const r=await f.confirm(i);assert.equal(r.state,'uncertain');assert.equal((await f.confirm(i)).state,'uncertain');assert.equal(f.callbacks.length,1);}finally{f.close();}});
test('old scopes and accepted health/diagnostic consents are byte unchanged by prepare/confirm',async()=>{const f=fixture();try{const scopes=f.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all(),health=f.db.prepare('SELECT * FROM crm_native_delivery_health_consent_v1').all(),diagnostic=f.db.prepare('SELECT * FROM crm_scheduler_read_consent_v1').all();await f.confirm(f.prepare());assert.deepEqual(f.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all(),scopes);assert.deepEqual(f.db.prepare('SELECT * FROM crm_native_delivery_health_consent_v1').all(),health);assert.deepEqual(f.db.prepare('SELECT * FROM crm_scheduler_read_consent_v1').all(),diagnostic);}finally{f.close();}});

const canonical=x=>JSON.stringify(x,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
// Authenticated historical fixtures use the unchanged public v1 record/intent
// protocol. They are not real grants and never touch PG or original identity.
function previousRecord(f,state,historicalQuery=C.PREVIOUS_QUERY_HASH){
 const authority={...f.snapshot(),queryHash:historicalQuery},r={id:crypto.randomUUID(),owner_id:authority.ownerId,connection_id:CID,purpose:C.PURPOSE,authority_json:canonical(authority),created_at:f.now-1000,expires_at:f.now+599000,state,consumed_at:state==='prepared'?null:f.now-500};
 r.intent_hash=H(canonical({schema:'shrigma-scheduler-state-chat-intent-v1',approvalId:r.id,connectionId:CID,purpose:C.PURPOSE,authority,createdAt:r.created_at,expiresAt:r.expires_at}));
 r.record_mac=MAC(f.key,canonical(['scheduler-state-chat-record-v1',r.id,r.owner_id,r.connection_id,r.purpose,r.authority_json,r.intent_hash,r.created_at,r.expires_at,r.state,r.consumed_at]));
 f.db.prepare('INSERT INTO crm_scheduler_state_chat_intent_v1 VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(r.id,r.owner_id,r.connection_id,r.purpose,r.authority_json,r.intent_hash,r.created_at,r.expires_at,r.state,r.consumed_at,r.record_mac);return {approvalId:r.id,intentHash:r.intent_hash};
}
for(const historicalQuery of [C.PREVIOUS_QUERY_HASH,C.V2_QUERY_HASH,C.V3_QUERY_HASH,C.V4_QUERY_HASH])for(const state of ['prepared','approved','consumed','uncertain'])test((historicalQuery===C.V4_QUERY_HASH?'v5 authenticated v4':historicalQuery===C.V3_QUERY_HASH?'v4 authenticated v3':'authenticated '+(historicalQuery===C.V2_QUERY_HASH?'v2':'v1'))+' '+state+' stays historical and cannot authorize the new fixed SQL',async()=>{
 const f=fixture();try{
  const {createSchedulerStateConsent}=require(runtime+'/native-scheduler-state-consent.cjs'),trusted=new WeakSet();
  const consent=createSchedulerStateConsent({db:f.db,current:(context,id,browser)=>{assert.equal(id,CID);assert.equal(browser,false);assert.equal(context.nativeBearer,f.token);if(f.revoked)throw Error('revoked');return f.snapshot();},mac:x=>MAC(f.key,x),now:()=>f.now,admitNativeApproval:q=>trusted.has(q)});
  const old=previousRecord(f,state,historicalQuery),oldRow=f.db.prepare('SELECT * FROM crm_scheduler_state_chat_intent_v1 WHERE id=?').get(old.approvalId),oldAuthority={...f.snapshot(),queryHash:historicalQuery};
  // The original accepted purpose receipt is validly MACed for the old SQL.
  const prior={id:1,owner_id:oldAuthority.ownerId,connection_id:CID,purpose:C.PURPOSE,authority_hash:MAC(f.key,canonical(['scheduler-state-current-v1',C.PURPOSE,oldAuthority])),happened_at:f.now-900,revoked_at:null};
  const priorMac=MAC(f.key,canonical(['scheduler-state-consent-record-v1',prior.id,prior.owner_id,prior.connection_id,prior.purpose,prior.authority_hash,prior.happened_at,prior.revoked_at]));
  f.db.prepare('INSERT INTO crm_scheduler_state_consent_v1 VALUES(?,?,?,?,?,?,?,?)').run(prior.id,prior.owner_id,prior.connection_id,prior.purpose,prior.authority_hash,prior.happened_at,null,priorMac);
  const originalConsent=f.db.prepare('SELECT * FROM crm_scheduler_state_consent_v1 WHERE id=1').get();
  f.options.authorizeBoundApproval=q=>{f.callbacks.push(q);assert.equal(f.db.prepare('SELECT state FROM crm_scheduler_state_chat_intent_v1 WHERE id=?').get(q.approvalId).state,'consumed');trusted.add(q);try{return consent.authorizeNativeBound(q);}finally{trusted.delete(q);}};f.bridge=C.createSchedulerStateChatApproval(f.options);
  assert.equal(consent.status({context:{...f.context,method:'GET'},connectionId:CID}).consented,false);assert.throws(()=>consent.require({context:{...f.context,method:'GET'},connectionId:CID}),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});
  assert.throws(()=>f.status(old),{code:'SCHEDULER_CHAT_BINDING_CHANGED'});await assert.rejects(f.confirm(old),{code:'SCHEDULER_CHAT_BINDING_CHANGED'});assert.equal(f.callbacks.length,0);
  const next=f.prepare();assert.notEqual(next.approvalId,old.approvalId);assert.equal(next.authorized,false);assert.equal(consent.status({context:{...f.context,method:'GET'},connectionId:CID}).consented,false);
  assert.equal((await f.confirm(next)).authorized,true);assert.equal(f.callbacks.length,1);assert.equal(consent.require({context:{...f.context,method:'GET'},connectionId:CID}).queryHash,C.queryHash);
  assert.deepEqual(f.db.prepare('SELECT * FROM crm_scheduler_state_chat_intent_v1 WHERE id=?').get(old.approvalId),oldRow);assert.deepEqual(f.db.prepare('SELECT * FROM crm_scheduler_state_consent_v1 WHERE id=1').get(),originalConsent);
 }finally{f.close();}
});
test('old query CURRENT and historical MAC tampering remain refused without callbacks',()=>{const f=fixture();try{const old=previousRecord(f,'approved');f.mod.queryHash=C.PREVIOUS_QUERY_HASH;assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CURRENT_REFUSED'});delete f.mod.queryHash;f.db.prepare('UPDATE crm_scheduler_state_chat_intent_v1 SET state=? WHERE id=?').run('uncertain',old.approvalId);assert.throws(f.prepare,{code:'SCHEDULER_CHAT_INTEGRITY_REFUSED'});assert.equal(f.callbacks.length,0);}finally{f.close();}});

for(const state of ['consumed','uncertain'])test('v3 same binding '+state+' remains sticky and cannot prepare or replay callback',async()=>{const f=fixture();try{const old=previousRecord(f,state,C.queryHash);assert.equal(f.status(old).state,'uncertain');assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CONFIRMATION_UNCERTAIN'});assert.equal((await f.confirm(old)).state,'uncertain');f.bridge=C.createSchedulerStateChatApproval(f.options);assert.throws(f.prepare,{code:'SCHEDULER_CHAT_CONFIRMATION_UNCERTAIN'});assert.equal(f.callbacks.length,0);}finally{f.close();}});

for(const state of ['prepared','approved','consumed','uncertain'])test('v4 v3 authenticated '+state+' cannot promote authorization to helper evaluation',async()=>{const f=fixture();try{const old=previousRecord(f,state,C.V3_QUERY_HASH);assert.throws(()=>f.status(old),{code:'SCHEDULER_CHAT_BINDING_CHANGED'});await assert.rejects(f.confirm(old),{code:'SCHEDULER_CHAT_BINDING_CHANGED'});const fresh=f.prepare();assert.notEqual(fresh.approvalId,old.approvalId);assert.equal(f.callbacks.length,0);assert.equal(f.db.prepare('SELECT state FROM crm_scheduler_state_chat_intent_v1 WHERE id=?').get(old.approvalId).state,state);assert.equal((await f.confirm(fresh)).state,'approved');assert.equal(f.callbacks.length,1);}finally{f.close();}});
