'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{AsyncLocalStorage}=require('node:async_hooks');
const MANIFEST_SHA='452cdbec54d59cfb7157a7efaa0ff40fbeb210c780413c3943678ddf52ce0a51',H=/^[a-f0-9]{64}$/,U=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function read(file){const name=path.join(__dirname,file),stat=fs.lstatSync(name);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||fs.realpathSync(name)!==name)throw Error('FOUNDATION_PIN_REFUSED');return fs.readFileSync(name);}
function freeze(x){if(x&&typeof x==='object'){for(const value of Object.values(x))freeze(value);Object.freeze(x);}return x;}
const mb=read('manifest.json');if(sha(mb)!==MANIFEST_SHA)throw Error('FOUNDATION_PIN_REFUSED');const M=freeze(JSON.parse(mb)),body=read(M.sql.path),qb=read(M.queries.path);if(body.length!==M.sql.bytes||sha(body)!==M.sql.sha256||qb.length!==M.queries.bytes||sha(qb)!==M.queries.sha256)throw Error('FOUNDATION_PIN_REFUSED');const Q=require('./sql.cjs'),CAPSULE=Object.freeze(body.toString('utf8').split('\n--@@\n').map(x=>x.trim()));if(CAPSULE.length!==6)throw Error('FOUNDATION_PIN_REFUSED');
const owned=new WeakSet();function fail(code,status=503){const e=Object.assign(new Error(code),{code,status});owned.add(e);return e;}
function copy(x){if(x===null||typeof x==='string'||typeof x==='boolean'||typeof x==='number'&&Number.isFinite(x))return x;if(Array.isArray(x))return x.map(copy);if(!x||typeof x!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(x)))throw fail('FOUNDATION_INPUT_REFUSED',400);const o={};for(const k of Object.keys(x).sort()){const d=Object.getOwnPropertyDescriptor(x,k);if(!Object.hasOwn(d,'value')||['__proto__','constructor','prototype'].includes(k))throw fail('FOUNDATION_INPUT_REFUSED',400);o[k]=copy(d.value);}return o;}
const canon=x=>JSON.stringify(copy(x)),digest=x=>sha(canon(x));function exact(x,keys){if(!x||Array.isArray(x)||Object.keys(x).sort().join(',')!==[...keys].sort().join(','))throw fail('FOUNDATION_INPUT_REFUSED',400);}
const resourceHash=digest(M.resource),fenceScopeHash=digest({resourceHash,namespace:M.namespace,runtimeRole:M.runtimeRole});
const columns=['operation_id:2950:true','capsule_id:25:true','capsule_sha256:25:true','target_sha256:25:true','admission_receipt_sha256:25:true','reservation_receipt_sha256:25:true','state:25:true','applied_at:1184:true'];
const invFields=['database','sessionRole','currentRole','pid','engine','port','ssl','readOnly','installerSuperuser','installerCreateRole','installerDatabaseCreate','schemaPresent','runtimePresent','eventTriggers','unsafeDefaultAcls','publicThirdPartyPrivileges'];
function blockers(v,allowOwn=false){const b=[];if(!v.installerSuperuser)b.push('INSTALLER_SUPERUSER_REQUIRED');if(!v.installerCreateRole||!v.installerDatabaseCreate)b.push('INSTALLER_CREATE_PRIVILEGES_REQUIRED');if(!allowOwn&&v.schemaPresent)b.push('NAMESPACE_PREEXISTS');if(!allowOwn&&v.runtimePresent)b.push('RUNTIME_ROLE_PREEXISTS');if(v.eventTriggers)b.push('DDL_EVENT_TRIGGERS_PRESENT');if(v.unsafeDefaultAcls)b.push('INSTALLER_DEFAULT_ACL_UNSAFE');if(v.publicThirdPartyPrivileges)b.push('PUBLIC_THIRD_PARTY_PRIVILEGES');return b;}
function createOwnFoundation({enabled=false,client,getTransactionState,withFoundationSession,poisonSession,context,admitInspection,admitFoundation,reserveOriginal,getOriginalStatus}={}){
 const ready=enabled===true&&typeof client?.query==='function'&&typeof getTransactionState==='function'&&typeof withFoundationSession==='function'&&typeof poisonSession==='function'&&typeof admitInspection==='function';
 let ctx,targetHash,contextHash;if(ready){ctx=copy(context);exact(ctx,['ownerId','bindingRevision','credentialBindingHash','installerRole','resource','driver']);exact(ctx.driver,['version','packageSha256']);if(typeof ctx.ownerId!=='string'||!ctx.ownerId||!Number.isSafeInteger(ctx.bindingRevision)||ctx.bindingRevision<1||!H.test(ctx.credentialBindingHash||'')||typeof ctx.installerRole!=='string'||!ctx.installerRole||Buffer.byteLength(ctx.installerRole)>63||ctx.installerRole.includes('\0')||[M.namespace,M.runtimeRole].includes(ctx.installerRole)||canon(ctx.resource)!==canon(M.resource)||!/^\d+\.\d+\.\d+$/.test(ctx.driver.version||'')||!H.test(ctx.driver.packageSha256||''))throw fail('FOUNDATION_CONTEXT_REFUSED');targetHash=digest({resource:M.resource,installerRole:ctx.installerRole});contextHash=digest(ctx);}
 const storage=new AsyncLocalStorage();let active=null,closing=false,closed=false,closePromise=null,originalId=null,retiredSession=null,retirementUnconfirmed=false;
 const base=()=>({ownerId:ctx.ownerId,contextHash,targetHash,resourceHash,capsuleHash:M.sql.sha256,fenceScopeHash});
 function bound(p,ms,code){let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(fail(code)),ms);})]).finally(()=>clearTimeout(timer));}
 function check(t){if(active!==t||!t.valid||closed)throw fail('FOUNDATION_LEASE_REFUSED');}
 function retire(t,reason){if(t.retirement)return t.retirement;t.retirement=(async()=>{retirementUnconfirmed=true;retiredSession=t.proof?.physicalSessionHash||null;let result;try{result=copy(await bound(Promise.resolve().then(()=>poisonSession({operationId:originalId,reason,physicalSessionHash:retiredSession})),5000,'FOUNDATION_RETIRE_TIMEOUT'));exact(result,['retired','confirmedClosed']);if(result.retired!==true||result.confirmedClosed!==true)throw fail('FOUNDATION_RETIRE_UNCONFIRMED');retirementUnconfirmed=false;}catch{throw fail('FOUNDATION_RETIRE_UNCONFIRMED');}})();t.retirement.catch(()=>{});return t.retirement;}
 async function query(t,text,params,command,state){const l=storage.getStore();check(t);if(!l?.alive||l.ticket!==t||l.pending)throw fail('FOUNDATION_QUERY_REFUSED');l.pending=true;try{let r;try{r=await bound(Promise.resolve().then(()=>client.query(text,params)),12000,'FOUNDATION_QUERY_TIMEOUT');}catch(e){const known=e?.severity==='ERROR'&&typeof e.code==='string'&&/^[0-9A-Z]{5}$/.test(e.code)&&!e.code.startsWith('08')&&!['57P01','57P02','57P03'].includes(e.code);const f=fail(known?'FOUNDATION_SQL_REFUSED':'FOUNDATION_DATABASE_UNKNOWN');f.knownSql=known;throw f;}check(t);if(getTransactionState()!==state||!r||Array.isArray(r)||r.command!==command||!Array.isArray(r.rows)||(command==='SELECT'||command==='INSERT'?(!Number.isSafeInteger(r.rowCount)||r.rowCount!==r.rows.length):(r.rowCount!==null||r.rows.length!==0)))throw fail('FOUNDATION_ACK_UNKNOWN');return copy(r.rows);}finally{l.pending=false;}}
 async function inventory(t,write){const rows=await query(t,Q.INVENTORY,undefined,'SELECT','T');if(rows.length!==1)throw fail('FOUNDATION_PEER_REFUSED');const v=rows[0];exact(v,invFields);if(v.database!=='listmonk'||v.sessionRole!==ctx.installerRole||v.currentRole!==ctx.installerRole||v.pid!==t.proof.pid||!Number.isInteger(v.engine)||Math.floor(v.engine/10000)!==17||v.port!==5432||v.ssl!==false||v.readOnly!==(write?'off':'on')||!['installerSuperuser','installerCreateRole','installerDatabaseCreate','schemaPresent','runtimePresent'].every(k=>typeof v[k]==='boolean')||!['eventTriggers','unsafeDefaultAcls','publicThirdPartyPrivileges'].every(k=>Number.isSafeInteger(v[k])&&v[k]>=0))throw fail('FOUNDATION_PEER_REFUSED');const {pid,readOnly,...stable}=v;return {value:v,hash:digest(stable)};}
 async function post(t){const rows=await query(t,Q.POST,undefined,'SELECT','T');if(rows.length!==1)throw fail('FOUNDATION_POSTCONDITION_REFUSED');const p=rows[0];exact(p,['schemaOwned','ledgerOwned','runtimeRestricted','runtimeNoMemberships','runtimeNoSettings','runtimeUsageOnly','schemaAclClosed','ledgerAclClosed','ledgerColumns','primaryKeys','checks']);let c;try{c=JSON.parse(p.ledgerColumns);}catch{throw fail('FOUNDATION_POSTCONDITION_REFUSED');}if(!['schemaOwned','ledgerOwned','runtimeRestricted','runtimeNoMemberships','runtimeNoSettings','runtimeUsageOnly','schemaAclClosed','ledgerAclClosed'].every(k=>p[k]===true)||canon(c)!==canon(columns)||p.primaryKeys!==1||p.checks!==6)throw fail('FOUNDATION_POSTCONDITION_REFUSED');}
 async function readAdmission(t){const e={admitted:true,action:t.action,purpose:'own-foundation-read',...base()};let r;try{r=copy(await bound(Promise.resolve().then(()=>admitInspection({...e,admitted:false})),5000,'FOUNDATION_ADMISSION_TIMEOUT'));}catch{throw fail('FOUNDATION_READ_ADMISSION_REFUSED');}check(t);if(canon(r)!==canon(e))throw fail('FOUNDATION_READ_ADMISSION_REFUSED');}
 async function applyAdmission(t,inv){if(typeof admitFoundation!=='function'||typeof reserveOriginal!=='function')throw fail('FOUNDATION_APPLY_ADMISSION_MISSING');const e={admitted:true,action:'bootstrap',purpose:'own-foundation-bootstrap',operationId:t.args.operationId,inventoryHash:inv.hash,...base(),recoveryReady:true,runtimeIsolationReady:true};let r;try{r=copy(await bound(Promise.resolve().then(()=>admitFoundation({...e,admitted:false,recoveryReady:false,runtimeIsolationReady:false,inventory:inv.value})),5000,'FOUNDATION_ADMISSION_TIMEOUT'));}catch{throw fail('FOUNDATION_APPLY_ADMISSION_REFUSED');}check(t);exact(r,[...Object.keys(e),'consentReceiptHash','admissionReceiptHash','isolationReceiptHash','recovery']);const {consentReceiptHash,admissionReceiptHash,isolationReceiptHash,recovery,...answer}=r;if(canon(answer)!==canon(e)||!H.test(consentReceiptHash||'')||!H.test(admissionReceiptHash||'')||!H.test(isolationReceiptHash||''))throw fail('FOUNDATION_APPLY_ADMISSION_REFUSED');exact(recovery,['backupSha256','restoreProofSha256','roleGlobalsSha256','destinationReceiptSha256']);if(!Object.values(recovery).every(v=>typeof v==='string'&&H.test(v)))throw fail('FOUNDATION_RECOVERY_REQUIRED');return {admissionReceiptHash};}
 async function reserve(t,admission,inv){originalId=t.args.operationId;let r;try{r=copy(await bound(Promise.resolve().then(()=>reserveOriginal({purpose:'own-foundation-bootstrap',operationId:originalId,inventoryHash:inv.hash,...base(),admissionReceiptHash:admission.admissionReceiptHash})),5000,'FOUNDATION_RESERVATION_TIMEOUT'));}catch{throw fail('FOUNDATION_RESERVATION_UNKNOWN');}check(t);exact(r,['disposition','durable','operationId','ownerId','targetHash','resourceHash','capsuleHash','fenceScopeHash','admissionReceiptHash','reservationReceiptHash']);if(r.durable!==true||!['new','existing','unknown'].includes(r.disposition)||!U.test(r.operationId||'')||M.historicalOperationIds.includes(r.operationId)||r.ownerId!==ctx.ownerId||r.targetHash!==targetHash||r.resourceHash!==resourceHash||r.capsuleHash!==M.sql.sha256||r.fenceScopeHash!==fenceScopeHash||!H.test(r.admissionReceiptHash||'')||!H.test(r.reservationReceiptHash||''))throw fail('FOUNDATION_RESERVATION_UNKNOWN');if(r.disposition!=='new'){originalId=r.operationId;throw fail('FOUNDATION_ORIGINAL_STATUS_REQUIRED',409);}if(r.operationId!==t.args.operationId||r.admissionReceiptHash!==admission.admissionReceiptHash)throw fail('FOUNDATION_RESERVATION_UNKNOWN');return r;}
 async function original(t){if(typeof getOriginalStatus!=='function')throw fail('FOUNDATION_ORIGINAL_STATUS_UNAVAILABLE');let r;try{r=copy(await bound(Promise.resolve().then(()=>getOriginalStatus({purpose:'own-foundation-original-status',operationId:t.args.operationId,...base()})),5000,'FOUNDATION_ORIGINAL_STATUS_TIMEOUT'));}catch{throw fail('FOUNDATION_ORIGINAL_STATUS_REFUSED');}check(t);exact(r,['state','durable','operationId','ownerId','targetHash','resourceHash','capsuleHash','fenceScopeHash','admissionReceiptHash','reservationReceiptHash']);if(r.durable!==true||!['reserved','unknown'].includes(r.state)||r.operationId!==t.args.operationId||r.ownerId!==ctx.ownerId||r.targetHash!==targetHash||r.resourceHash!==resourceHash||r.capsuleHash!==M.sql.sha256||r.fenceScopeHash!==fenceScopeHash||!H.test(r.admissionReceiptHash||'')||!H.test(r.reservationReceiptHash||''))throw fail('FOUNDATION_ORIGINAL_STATUS_REFUSED');originalId=r.operationId;return r;}
 const flags=Object.freeze({sourceOnly:true,operational:false,productionAdmitted:false,automaticReplay:false});
 async function work(t){await readAdmission(t);let begun=false,commitStarted=false;try{await query(t,t.action==='apply'?Q.BEGIN_WRITE:Q.BEGIN_READ,undefined,'BEGIN','T');begun=true;if(t.action==='apply')await query(t,Q.LOCK,undefined,'SELECT','T');const inv=await inventory(t,t.action==='apply');
  if(['inspect','preview'].includes(t.action)){await query(t,Q.ROLLBACK,undefined,'ROLLBACK','I');begun=false;return Object.freeze({capsuleId:M.capsuleId,capsuleHash:M.sql.sha256,inventoryHash:inv.hash,resource:M.resource,installerRole:ctx.installerRole,namespace:M.namespace,runtimeRole:M.runtimeRole,ledger:M.ledger,inventory:inv.value,catalogEligible:blockers(inv.value).length===0,applyAdmitted:false,recoveryReady:false,blockers:[...blockers(inv.value),'ROOT_APPLY_ADMISSION_AND_RECOVERY_REQUIRED'],plan:[{kind:'create-role',name:M.runtimeRole,login:false},{kind:'create-schema',name:M.namespace,ownerRole:ctx.installerRole},{kind:'grant-own-usage-only',role:M.runtimeRole,namespace:M.namespace},{kind:'create-private-versioned-ledger',name:M.ledger,ownerRole:ctx.installerRole}],...flags});}
  if(t.action==='status'){const r=await original(t);let state='reserved-unresolved';if(inv.value.schemaPresent||inv.value.runtimePresent){if(!inv.value.schemaPresent||!inv.value.runtimePresent)throw fail('FOUNDATION_CURRENT_METADATA_CHANGED');await post(t);const rows=await query(t,Q.STATUS,[r.operationId],'SELECT','T');if(rows.length>1)throw fail('FOUNDATION_LEDGER_REFUSED');if(rows.length===1){const row=rows[0];exact(row,['operationId','capsuleHash','targetHash','admissionReceiptHash','reservationReceiptHash','state']);if(row.operationId!==r.operationId||row.capsuleHash!==M.sql.sha256||row.targetHash!==targetHash||row.admissionReceiptHash!==r.admissionReceiptHash||row.reservationReceiptHash!==r.reservationReceiptHash||row.state!=='applied')throw fail('FOUNDATION_LEDGER_REFUSED');state='applied';}}await query(t,Q.ROLLBACK,undefined,'ROLLBACK','I');begun=false;return Object.freeze({operationId:r.operationId,state,rearmAllowed:false,...flags});}
  if(blockers(inv.value).length)throw fail('FOUNDATION_CATALOG_BLOCKED',409);if(inv.hash!==t.args.expectedInventoryHash)throw fail('FOUNDATION_INVENTORY_CHANGED',409);const admission=await applyAdmission(t,inv),r=await reserve(t,admission,inv);for(let i=0;i<CAPSULE.length;i++)await query(t,CAPSULE[i],undefined,['CREATE','CREATE','REVOKE','GRANT','CREATE','REVOKE'][i],'T');await post(t);const after=await inventory(t,true);if(blockers(after.value,true).length)throw fail('FOUNDATION_POSTCONDITION_REFUSED');const rows=await query(t,Q.INSERT,[r.operationId,M.sql.sha256,targetHash,r.admissionReceiptHash,r.reservationReceiptHash],'INSERT','T');if(rows.length!==1||canon(rows[0])!==canon({operationId:r.operationId,state:'applied'}))throw fail('FOUNDATION_LEDGER_REFUSED');commitStarted=true;await query(t,Q.COMMIT,undefined,'COMMIT','I');begun=false;return Object.freeze({operationId:r.operationId,state:'applied',rearmAllowed:false,...flags});
 }catch(e){const unknown=!owned.has(e)||['FOUNDATION_DATABASE_UNKNOWN','FOUNDATION_ACK_UNKNOWN','FOUNDATION_RESERVATION_UNKNOWN','FOUNDATION_LEASE_REFUSED'].includes(e.code);let rollbackFailed=false;if(begun&&!commitStarted&&!unknown){try{await query(t,Q.ROLLBACK,undefined,'ROLLBACK','I');begun=false;}catch{rollbackFailed=true;}}if(unknown||commitStarted||rollbackFailed||originalId){await retire(t,owned.has(e)?e.code:'FOUNDATION_REFUSED');}throw owned.has(e)?e:fail('FOUNDATION_REFUSED');}}
 async function invoke(action,raw){if(!ready)throw fail('FOUNDATION_OFF');if(closing||closed)throw fail('FOUNDATION_CLOSED');if(retirementUnconfirmed)throw fail('FOUNDATION_RETIRE_UNCONFIRMED');if(active)throw fail('FOUNDATION_BUSY');const a=copy(raw===undefined?{}:raw);exact(a,action==='apply'?['operationId','expectedCapsuleSha256','expectedInventoryHash']:action==='status'?['operationId']:[]);if(['apply','status'].includes(action)&&(!U.test(a.operationId||'')||M.historicalOperationIds.includes(a.operationId)))throw fail('FOUNDATION_OPERATION_REFUSED',400);if(action==='apply'&&(a.expectedCapsuleSha256!==M.sql.sha256||!H.test(a.expectedInventoryHash||'')))throw fail('FOUNDATION_CAPSULE_REFUSED',400);if(originalId&&(action!=='status'||a.operationId!==originalId))throw fail('FOUNDATION_ORIGINAL_STATUS_REQUIRED',409);const t={action,args:a,valid:true,proof:null,done:null,finish:null};t.done=new Promise(r=>t.finish=r);active=t;const run=Promise.resolve().then(()=>withFoundationSession(async proof=>{check(t);if(t.leaseEntered)throw fail('FOUNDATION_LEASE_REFUSED');t.leaseEntered=true;t.proof=copy(proof);exact(t.proof,['exclusive','connected','resourceHash','driverPackageSha256','physicalSessionHash','pid','installerRole']);if(t.proof.exclusive!==true||t.proof.connected!==true||t.proof.resourceHash!==resourceHash||t.proof.driverPackageSha256!==ctx.driver.packageSha256||!H.test(t.proof.physicalSessionHash||'')||!Number.isSafeInteger(t.proof.pid)||t.proof.pid<=0||t.proof.installerRole!==ctx.installerRole||retiredSession===t.proof.physicalSessionHash||getTransactionState()!=='I')throw fail('FOUNDATION_LEASE_REFUSED');const l={ticket:t,alive:true,pending:false};try{return await storage.run(l,()=>work(t));}finally{l.alive=false;if(l.pending||getTransactionState()!=='I')await retire(t,'FOUNDATION_SESSION_NOT_IDLE');}}, {purpose:action==='apply'?'own-foundation-write':action==='status'?'own-foundation-original-status':'own-foundation-read',operationId:a.operationId||null}));try{return await bound(run,45000,'FOUNDATION_OPERATION_TIMEOUT');}catch(e){if(owned.has(e)&&e.code==='FOUNDATION_OPERATION_TIMEOUT'){t.valid=false;await retire(t,e.code);}throw owned.has(e)?e:fail('FOUNDATION_REFUSED');}finally{t.valid=false;active=null;t.finish();}}
 function close(){if(closePromise)return closePromise;closing=true;closePromise=(async()=>{if(active){const t=active;try{await bound(t.done,15000,'FOUNDATION_DRAIN_TIMEOUT');}catch{t.valid=false;await retire(t,'FOUNDATION_DRAIN_TIMEOUT');}}if(retirementUnconfirmed)throw fail('FOUNDATION_RETIRE_UNCONFIRMED');closed=true;return Object.freeze({closed:true,...flags});})();closePromise.catch(()=>{});return closePromise;}
 return Object.freeze({inspect:raw=>invoke('inspect',raw),preview:raw=>invoke('preview',raw),apply:raw=>invoke('apply',raw),status:raw=>invoke('status',raw),close});
}
module.exports=Object.freeze({createOwnFoundation,ENABLED:false,manifestHash:MANIFEST_SHA,capsuleHash:M.sql.sha256});
