'use strict';
const BEGIN_READ='BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY',BEGIN_WRITE='BEGIN ISOLATION LEVEL SERIALIZABLE READ WRITE',ROLLBACK='ROLLBACK',COMMIT='COMMIT';
const LOCK='SELECT pg_catalog.pg_advisory_xact_lock(1987462211,170007)';
const INVENTORY=`SELECT pg_catalog.current_database() AS database,session_user::text AS "sessionRole",current_user::text AS "currentRole",pg_catalog.pg_backend_pid() AS pid,pg_catalog.current_setting('server_version_num')::integer AS engine,pg_catalog.inet_server_port() AS port,(SELECT ssl FROM pg_catalog.pg_stat_ssl WHERE pid=pg_catalog.pg_backend_pid()) AS ssl,pg_catalog.current_setting('transaction_read_only') AS "readOnly",r.rolsuper AS "installerSuperuser",r.rolcreaterole AS "installerCreateRole",pg_catalog.has_database_privilege(current_user,pg_catalog.current_database(),'CREATE') AS "installerDatabaseCreate",EXISTS(SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname='dashboard_crm_controls') AS "schemaPresent",EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='shrigma_app_runtime_v1') AS "runtimePresent",(SELECT count(*)::integer FROM pg_catalog.pg_event_trigger WHERE evtenabled<>'D') AS "eventTriggers",(SELECT count(*)::integer FROM pg_catalog.pg_default_acl d CROSS JOIN LATERAL pg_catalog.aclexplode(d.defaclacl) a WHERE d.defaclrole=r.oid AND d.defaclnamespace=0 AND d.defaclobjtype IN ('r','n') AND a.grantee<>r.oid) AS "unsafeDefaultAcls",(
 (SELECT count(*) FROM pg_catalog.pg_namespace n CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(n.nspacl,pg_catalog.acldefault('n',n.nspowner))) a WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND n.nspname<>'dashboard_crm_controls' AND a.grantee=0)
 +(SELECT count(*) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(c.relacl,pg_catalog.acldefault(CASE WHEN c.relkind='S' THEN 's'::"char" ELSE 'r'::"char" END,c.relowner))) a WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND n.nspname<>'dashboard_crm_controls' AND c.relkind IN ('r','p','v','m','f','S') AND a.grantee=0)
 +(SELECT count(*) FROM pg_catalog.pg_attribute att JOIN pg_catalog.pg_class c ON c.oid=att.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL pg_catalog.aclexplode(att.attacl) a WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND n.nspname<>'dashboard_crm_controls' AND att.attnum>0 AND NOT att.attisdropped AND a.grantee=0)
 +(SELECT count(*) FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(p.proacl,pg_catalog.acldefault('f',p.proowner))) a WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND n.nspname<>'dashboard_crm_controls' AND a.grantee=0)
 +(SELECT count(*) FROM pg_catalog.pg_database d CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(d.datacl,pg_catalog.acldefault('d',d.datdba))) a WHERE d.datname=pg_catalog.current_database() AND a.grantee=0 AND a.privilege_type IN ('CREATE','TEMPORARY'))
 )::integer AS "publicThirdPartyPrivileges" FROM pg_catalog.pg_roles r WHERE r.rolname=session_user`;
const POST=`SELECT n.nspowner=r.oid AS "schemaOwned",c.relowner=r.oid AND c.relkind='r' AND c.relpersistence='p' AS "ledgerOwned",NOT rt.rolcanlogin AND NOT rt.rolsuper AND NOT rt.rolcreatedb AND NOT rt.rolcreaterole AND NOT rt.rolinherit AND NOT rt.rolreplication AND NOT rt.rolbypassrls AS "runtimeRestricted",NOT EXISTS(SELECT 1 FROM pg_catalog.pg_auth_members WHERE member=rt.oid OR roleid=rt.oid) AS "runtimeNoMemberships",NOT EXISTS(SELECT 1 FROM pg_catalog.pg_db_role_setting WHERE setrole=rt.oid) AS "runtimeNoSettings",pg_catalog.has_schema_privilege(rt.oid,n.oid,'USAGE') AND NOT pg_catalog.has_schema_privilege(rt.oid,n.oid,'CREATE') AS "runtimeUsageOnly",NOT EXISTS(SELECT 1 FROM pg_catalog.aclexplode(COALESCE(n.nspacl,pg_catalog.acldefault('n',n.nspowner))) a WHERE a.grantee<>r.oid AND NOT(a.grantee=rt.oid AND a.privilege_type='USAGE' AND NOT a.is_grantable)) AS "schemaAclClosed",NOT EXISTS(SELECT 1 FROM pg_catalog.aclexplode(COALESCE(c.relacl,pg_catalog.acldefault('r',c.relowner))) a WHERE a.grantee<>r.oid) AS "ledgerAclClosed",(SELECT pg_catalog.jsonb_agg(a.attname::text||':'||a.atttypid::text||':'||a.attnotnull::text ORDER BY a.attnum) FROM pg_catalog.pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped)::text AS "ledgerColumns",(SELECT count(*)::integer FROM pg_catalog.pg_constraint WHERE conrelid=c.oid AND contype='p') AS "primaryKeys",(SELECT count(*)::integer FROM pg_catalog.pg_constraint WHERE conrelid=c.oid AND contype='c') AS checks FROM pg_catalog.pg_namespace n JOIN pg_catalog.pg_class c ON c.relnamespace=n.oid AND c.relname='foundation_operation_v1' JOIN pg_catalog.pg_roles r ON r.rolname=session_user JOIN pg_catalog.pg_roles rt ON rt.rolname='shrigma_app_runtime_v1' WHERE n.nspname='dashboard_crm_controls'`;
const INSERT="INSERT INTO dashboard_crm_controls.foundation_operation_v1(operation_id,capsule_id,capsule_sha256,target_sha256,admission_receipt_sha256,reservation_receipt_sha256,state) VALUES($1::uuid,'shrigma-own-foundation-bootstrap-v1',$2,$3,$4,$5,'applied') RETURNING operation_id::text AS \"operationId\",state";
const STATUS='SELECT operation_id::text AS "operationId",capsule_sha256 AS "capsuleHash",target_sha256 AS "targetHash",admission_receipt_sha256 AS "admissionReceiptHash",reservation_receipt_sha256 AS "reservationReceiptHash",state FROM dashboard_crm_controls.foundation_operation_v1 WHERE operation_id=$1::uuid';
module.exports=Object.freeze({BEGIN_READ,BEGIN_WRITE,ROLLBACK,COMMIT,LOCK,INVENTORY,POST,INSERT,STATUS});
