'use strict';
// Explicit synthetic source identities/revisions. These callbacks are NOT Root IAM.
const N=1000,H='a'.repeat(64),E='b'.repeat(64),uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
async function prepared(D){const distribution={schema:'crm-audience-slices-v1',brand:'fish',id:uuid(3),revision:2,key:H,identity_contract:'crm-contact-id-v1',algorithm:'sha256-rejection-bp-v1'},plan={schema:'crm-audience-slices-v1',brand:'fish',distribution_id:uuid(3),distribution_revision:2,key_hash:D.kernel.keyHash(distribution),slices:[{id:uuid(4),name:'Original',from_bp:0,to_bp:10000}]},snapshot={schema:'crm-audience-slice-source-v1',brand:'fish',audience_id:uuid(5),audience_revision:3,definition_hash:H,snapshot_id:uuid(6),source_hash:H,observed_at:new Date(N).toISOString(),expires_at:new Date(N+60000).toISOString(),complete:true,identity_complete:true,members:[uuid(1)]};
 const claims={schema:'crm-audience-slice-claims-v1',brand:'fish',distribution_id:uuid(3),distribution_revision:2,key_hash:plan.key_hash,revision:4,complete:true,claims:[]},selection={plan,distribution,slice_id:uuid(4),snapshot},before=D.kernel.select({...selection,claims,now:N}),campaign={brand:'fish',campaign_id:10,campaign_version:3,content_hash:H,audience_definition_hash:H};
 const policy=D.deliverability.createPolicy({brand:'fish',softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:async e=>e,authorizePolicyChange:async()=>({brand:'fish',actorRef:H}),clock:()=>N});const token=await policy.admitPolicyChange({operationId:uuid(80),softBounceAttempts:2});const state=policy.apply(policy.initialState(),token).state;
 const bodies=[['claims',claims],['capacity',{distributionId:uuid(3),distributionRevision:2,campaignId:10,campaignVersion:3,capacityRevision:5,limit:1,acceptedCount:0,reservedCount:0}],['capping',{subjectId:uuid(1),recipientRef:H,cappingRevision:8,windowStart:N,windowEnd:N+60000,limit:1,acceptedCount:0,reservedCount:0}],['consent',{subjectId:uuid(1),recipientRef:H,consent:'current',consentRevision:9}],['policy',state],['suspension',{suspension:'clear',suspensionRevision:2}]];
 const facts=bodies.map(([kind,body])=>({kind,body,expectedRevision:null,revision:D.F.revision(body)}));
 const contentGuards={brand:'fish',campaign_id:10,campaign_version:3,content_hash:H,definition_hash:H,members_hash:before.members_hash,observed_at:new Date(N).toISOString(),expires_at:new Date(N+60000).toISOString(),content_current:true,consent_current:true,bounce_current:true,frequency_current:true};
 return {facts,request:{brand:'fish',operationId:uuid(7),selection,before,campaign,beforeCampaign:campaign,contentGuards,memberBindings:[{subjectId:uuid(1),recipientRef:H}]}};}
const batch=(facts,extra={})=>({brand:'fish',inputKind:'verified_snapshot',sourceRef:H,eventRef:E,evidenceHash:H,expectedBrandRevision:null,brandRevision:7,observedAt:N,expiresAt:N+60000,facts,bindings:[],...extra});
function registered(D,id=uuid(7),brand='fish'){return D.J.encode(D.J.body({brand,operationId:id,attemptId:id,principalRefHash:H,registrationEvidenceHash:E,revision:1,state:'registered',reservationAttempted:false,outcomeWriteState:'idle',registeredAt:N,updatedAt:N,scope:null,reservation:false,reservedMemberCount:null,reservedMembersHash:null,capacityEvidenceHash:null}));}
function options(D,domain,p){return {enabled:true,client:domain.client,withDomainSession:domain.withDomainSession,poisonSession:domain.poison,journalCodec:D.J,journalSQL:D.JS,factsCodec:D.F,factsSQL:D.FS,kernel:D.kernel,deliverability:D.deliverability,clock:()=>N,loadLiveContext:async i=>({...p.request,operationId:i.operationId,brand:i.brand}),verifyLiveContext:async(i,meta)=>{if(meta?.original?.principalRefHash!==H)throw Error('synthetic authority refused');return {brand:i.brand,operationId:i.operationId,contextHash:D.F.digest(i)};},verifyFacts:async i=>({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,payloadHash:D.F.digest(i),authorityRef:H}),verifyOriginalAttempt:async(i,r)=>({brand:i.brand,sourceRef:i.sourceRef,eventRef:i.eventRef,bindingHash:D.F.digest(i.binding),requirementsHash:D.F.digest(i.requirements),operationReceiptHash:r.receipt_hash})};}
const reserve=(D,id=uuid(7),evaluate=D.decision.createDecision({kernel:D.kernel,deliverability:D.deliverability}))=>({brand:'fish',operationId:id,attemptId:id,expectedOperationRevision:1,evaluate});
module.exports={N,H,E,uuid,prepared,batch,registered,options,reserve};
