'use strict';
// New atomic transaction/rollback model only. Not a persistence fallback/PG proof.
function database(){return {operations:new Map(),brands:new Map(),events:new Map(),heads:new Map(),versions:new Map(),generation:0};}
function client(db,D,S){let state=null,start=0,write=false,changed=false,initialOperations=null,operationWrites=new Set(),factWrites=false;const logs=[],raw={logs,before:null,after:null,ownership:{connect:0,end:0,release:0}};for(const k of Object.keys(raw.ownership))raw[k]=()=>{raw.ownership[k]++;throw Error('Root owns lifecycle');};const key=(brand,kind,key)=>JSON.stringify([brand,kind,key]);
 raw.query=async(sql,p=[])=>{logs.push({sql,params:p});if(raw.before)await raw.before(sql,p);let rows=[],command=sql.split(' ')[0],r;
 if(sql===D.FS.BEGIN_WRITE||sql===D.FS.BEGIN_READ){if(state)throw Error('nested model tx');state=structuredClone(db);start=db.generation;write=sql===D.FS.BEGIN_WRITE;changed=false;initialOperations=structuredClone(db.operations);operationWrites=new Set();factWrites=false;r={command:'BEGIN',rows:[],rowCount:null};}
 else if(sql===D.FS.COMMIT){if(write&&changed&&db.generation!==start&&(factWrites||[...operationWrites].some(k=>JSON.stringify(db.operations.get(k))!==JSON.stringify(initialOperations.get(k)))))throw Object.assign(Error('model serialization'),{code:'40001'});if(write&&changed){if(factWrites){for(const k of ['operations','brands','events','heads','versions'])db[k]=state[k];}else for(const k of operationWrites)db.operations.set(k,state.operations.get(k));db.generation++;}state=null;r={command:'COMMIT',rows:[],rowCount:null};}
 else if(sql===D.FS.ROLLBACK){state=null;r={command:'ROLLBACK',rows:[],rowCount:null};}
 else{if(!state)throw Error('model query outside transaction');
 if(sql===D.JS.READ||sql===D.JS.LOCK){const o=state.operations.get(JSON.stringify(p));if(o)rows=[o];}
 else if(sql===D.JS.INSERT){const id=JSON.stringify(p.slice(0,3));if(!state.operations.has(id)){const o=D.J.encode(D.J.body({brand:p[0],operationId:p[1],attemptId:p[2],principalRefHash:p[3],registrationEvidenceHash:p[4],revision:1,state:'registered',reservationAttempted:false,outcomeWriteState:'idle',registeredAt:Number(p[5]),updatedAt:Number(p[5]),scope:null,reservation:false,reservedMemberCount:null,reservedMembersHash:null,capacityEvidenceHash:null}));state.operations.set(id,o);operationWrites.add(id);rows=[o];changed=true;}}
 else if(sql===D.JS.CONSUME){const id=JSON.stringify(p.slice(0,3)),o=state.operations.get(id);if(o&&o.revision===p[3]&&o.receipt_hash===p[6]&&o.state==='registered'&&!o.reservation_attempted){Object.assign(o,{revision:String(Number(o.revision)+1),reservation_attempted:true,updated_at:p[4],receipt_hash:p[5]});operationWrites.add(id);rows=[o];changed=true;}}
 else if(sql===S.RESERVE){const id=JSON.stringify(p.slice(0,3)),o=state.operations.get(id);if(o&&o.revision===p[3]&&o.receipt_hash===p[4]&&o.state==='registered'&&o.reservation_attempted){Object.assign(o,{state:'reserved',revision:String(Number(o.revision)+1),updated_at:p[5],scope:JSON.parse(p[6]),reservation:true,reserved_member_count:p[7],reserved_members_hash:p[8],capacity_evidence_hash:p[9],receipt_hash:p[10]});operationWrites.add(id);rows=[o];changed=true;}}
 else if(sql===D.FS.ORIGINAL){const o=state.operations.get(JSON.stringify(p));if(o)rows=[Object.fromEntries(['brand','operation_id','attempt_id','state','receipt_hash','scope','reservation','reserved_member_count','reserved_members_hash','capacity_evidence_hash','revision'].map(k=>[k,o[k]]))];}
 else if(sql===D.FS.BRAND||sql===D.FS.LOCK_BRAND){const revision=state.brands.get(p[0]);if(revision!==undefined)rows=[{brand:p[0],revision}];}
 else if(sql===D.FS.HEADS){for(const q of JSON.parse(p[1])){const revision=state.heads.get(key(p[0],q.kind,q.fact_key)),v=state.versions.get(JSON.stringify([p[0],q.kind,q.fact_key,revision]));if(v){const b=state.events.get(JSON.stringify([v.brand,v.source_ref,v.event_ref]));rows.push({...v,batch_payload_hash:b.payload_hash,authority_ref:b.authority_ref,envelope:b.envelope});}}}
 else if(sql===D.FS.EVENT){const b=state.events.get(JSON.stringify(p));if(b)rows=[b];}
 else if(sql===D.FS.INSERT_EVENT){const k=JSON.stringify(p.slice(0,3));if(!state.events.has(k)){state.events.set(k,{brand:p[0],source_ref:p[1],event_ref:p[2],brand_revision:p[3],payload_hash:p[4],authority_ref:p[5],recorded_at:p[6],envelope:JSON.parse(p[7])});rows=[{brand_revision:p[3]}];changed=true;factWrites=true;}}
 else if(sql===D.FS.INSERT_VERSION){state.versions.set(JSON.stringify(p.slice(0,4)),{brand:p[0],kind:p[1],fact_key:p[2],revision:p[3],body:JSON.parse(p[4]),body_hash:p[5],observed_at:p[6],expires_at:p[7],source_ref:p[8],event_ref:p[9],brand_revision:p[10]});rows=[{revision:p[3]}];changed=true;factWrites=true;}
 else if(sql===D.FS.INSERT_HEAD){const k=key(...p.slice(0,3));if(!state.heads.has(k)){state.heads.set(k,p[3]);rows=[{revision:p[3]}];changed=true;factWrites=true;}}
 else if(sql===D.FS.UPDATE_HEAD){const k=key(...p.slice(0,3));if(state.heads.get(k)===p[3]){state.heads.set(k,p[4]);rows=[{revision:p[4]}];changed=true;factWrites=true;}}
 else if(sql===D.FS.INSERT_BRAND){if(!state.brands.has(p[0])){state.brands.set(p[0],p[1]);rows=[{revision:p[1]}];changed=true;factWrites=true;}}
 else if(sql===D.FS.UPDATE_BRAND){if(state.brands.get(p[0])===p[1]){state.brands.set(p[0],p[2]);rows=[{revision:p[2]}];changed=true;factWrites=true;}}
 else throw Error('unmodeled new atomic SQL');r={command,rows:structuredClone(rows),rowCount:rows.length};}
 return raw.after?raw.after(sql,r):r;};return raw;}
module.exports={database,client};
