'use strict';
const fs=require('node:fs'),crypto=require('node:crypto'),http=require('node:http'),a=require('node:assert/strict');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');let stage='release';
async function main(){
 a.equal(process.getuid(),1000);const host='master.synthetic.invalid',origin='https://'+host,token=crypto.randomBytes(24).toString('base64url'),password=crypto.randomBytes(32).toString('base64url');
 Object.assign(process.env,{DASHBOARD_MODE:'synthetic',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_MANAGER_HOST:host,DASHBOARD_AREA_HOSTS:JSON.stringify({growth:'crm.synthetic.invalid',organico:'organic.synthetic.invalid',influs:'affiliate.synthetic.invalid'}),DASHBOARD_EMAIL_DOMAINS:'["synthetic.invalid"]',DASHBOARD_ADMIN_EMAIL:'master@synthetic.invalid',DASHBOARD_BOOTSTRAP_SHA256:sha(token),DASHBOARD_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),DASHBOARD_UPSTREAMS:'{}',DASHBOARD_UPSTREAM_HOSTS:'[]',HOST:'127.0.0.1',PORT:'8080'});
 const bytes=fs.readFileSync('/app/native-backend/manifest.json'),m=JSON.parse(bytes),manifestSha256=sha(bytes),N=require('/app/native-backend/bootstrap.cjs'),P=require('/app/presentation-release/release.cjs');
 a.deepEqual(m.presentationChangedPaths,['assets/panels/growth.js','growth.html']);a.equal(sha(fs.readFileSync('/app/presentation-release/manifest.json')),m.presentationManifestSha256);stage='release-runtime-verification';N.verifyRelease(manifestSha256);stage='release-startup';
 fs.writeFileSync('/dashboard-data/runtime-pack.json',fs.readFileSync('/app/runtime-pack.json'),{flag:'wx',mode:0o600});
 const started=P.startWithPresentation(()=>N.start({manifestSha256}));await new Promise(r=>started.server.listening?r():started.server.once('listening',r));
 const request=(path,{method='GET',body,cookie,csrf,bearer}={})=>new Promise((resolve,reject)=>{const q=http.request({host:'127.0.0.1',port:8080,path,method,agent:false,headers:{Host:host,Origin:origin,Accept:'application/json, text/event-stream',...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(bearer?{Authorization:'Bearer '+bearer}:{})}},res=>{const all=[];res.on('data',b=>all.push(b));res.on('end',()=>{const text=Buffer.concat(all).toString();let value;try{value=JSON.parse(text);}catch{value=text;}resolve({status:res.statusCode,value,cookie:res.headers['set-cookie']?.[0]});});});q.on('error',reject);q.setTimeout(10000,()=>q.destroy(Error('JOURNEY_SMOKE_DEADLINE')));q.end(body===undefined?undefined:JSON.stringify(body));});
 stage='public-composition';a.equal(N.verifyReady({manifestSha256}).runtimeFiles,62);a.equal(P.verifyReady().manifestSha256,m.presentationManifestSha256);
 const deniedHtml=await request('/growth.html');a.equal(deniedHtml.status,401);
 const health=await request('/healthz');a.equal(health.status,200);a.equal(health.value.nativeBackendManifestSha256,manifestSha256);a.equal(health.value.journeyPresentationManifestSha256,m.presentationManifestSha256);a.equal(health.value.journeyPublicFiles.length,3);for(const f of health.value.journeyPublicFiles){const b=fs.readFileSync(f.path==='assets/panels/growth.css'?'/app/native-backend/runtime/crm-presentation.css':'/app/presentation-release/public/'+f.path);a.equal(f.bytes,b.length);a.equal(f.sha256,sha(b));}
 stage='original-master';a.equal((await request('/auth/bootstrap/complete',{method:'POST',body:{email:'master@synthetic.invalid',token,password}})).status,200);
 const login=await request('/auth/login',{method:'POST',body:{email:'master@synthetic.invalid',password}});a.equal(login.status,200);const cookie=login.cookie.split(';')[0],csrf=login.value.csrf;
 for(const path of m.presentationChangedPaths){const r=await request('/'+path,{cookie});a.equal(r.status,200);a.equal(sha(Buffer.from(r.value)),sha(fs.readFileSync('/app/presentation-release/public/'+path)));}
 const html=await request('/growth.html',{cookie});a.match(html.value,/configuredReadOnly:true/);a.doesNotMatch(html.value,/observedOnly:true/);a.match(html.value,/conexões originais/);
 const style=await request('/assets/panels/growth.css',{cookie});a.equal(style.status,200);const styleHash=sha(Buffer.from(style.value));a.equal(styleHash,'cdc4fef0ca423aae8a067ab95a7264bcf7fa903c290be12487954c1507be4ba3');a.ok(html.value.includes('growth.css?v='+styleHash.slice(0,12)));a.ok(style.value.includes('.crm-sidebar'));a.ok(style.value.includes('crm-active-brand'));a.ok(style.value.includes('crm-home'));const headStyle=await request('/assets/panels/growth.css',{method:'HEAD',cookie});a.equal(headStyle.status,200);a.equal(headStyle.value,'');
 const issue=await request('/auth/native-connections',{method:'POST',cookie,csrf,body:{action:'issue',label:'journey isolated READ',brands:['fish'],scopes:['crm.read'],expiresDays:1}});a.equal(issue.status,201);const bearer=issue.value.token;
 const call=(brand)=>request('/api/native/mcp',{method:'POST',bearer,body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'crm_journey_catalog',arguments:{brand}}}});
 stage='native-read';const read=await call('fish');a.equal(read.status,200);const r=read.value.result.structuredContent;a.equal(r.status,200);a.equal(r.body.contract,'shrigma-crm-journey-read-v1');a.equal(r.body.brand,'fish');a.equal(r.body.readOnly,true);a.equal(r.body.authorizesEdit,false);a.equal(r.body.authorizesSend,false);a.equal(r.body.operational,false);for(const x of [bearer,csrf,cookie])a.equal(JSON.stringify(read.value).includes(x),false);
 a.equal((await call('aristo')).value.result.structuredContent.error,'BRAND_DENIED');
 stage='revoke';a.equal((await request('/auth/native-connections',{method:'POST',cookie,csrf,body:{action:'revoke',connectionId:issue.value.connection.id}})).status,200);a.equal((await call('fish')).status,401);
 console.log(JSON.stringify({schema:'shrigma-configured-journey-image-smoke-v1',ok:true,node:process.version,uid:process.getuid(),manifestSha256,presentationManifestSha256:m.presentationManifestSha256,sourceRevision:m.sourceRevision,actualNativeRuntimeFiles:62,presentationPathsUpdated:2,publicAssetsActuallyServed:true,canonicalCrmStylesActuallyServed:true,htmlCssVersionMatched:true,originalPresentationVerifierPreserved:true,originalMasterNativeRead:true,crossBrandDenied:true,revocationDuringReadGuardCovered:true,nativeRevocationDenied:true,noEditorOrSendGrant:true,verifiedRuntimeAndPresentation:true,sqlInstallerEnabled:false,productionIdentityUsed:false,productionDatabaseUsed:false,operational:false}));process.kill(process.pid,'SIGTERM');
}
main().catch(e=>{console.error(JSON.stringify({ok:false,stage,code:/^[A-Z][A-Z0-9_]{1,80}$/.test(e.code||e.message||'')?(e.code||e.message):'JOURNEY_IMAGE_SMOKE_FAILED'}));process.exitCode=1;process.kill(process.pid,'SIGTERM');});
