'use strict';
// New read-only implementation; no historical controller/observer/guard imported.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const PINS_SHA='8789803c62ec8e45aea77185703d6b6e6aa74e5d7294d9bc019ae05c5a987833',pinBytes=fs.readFileSync(path.join(__dirname,'pins.json'));
if(sha(pinBytes)!==PINS_SHA)throw Error('CONTINUITY_PUBLIC_PINS_REFUSED');
const freeze=x=>{if(x&&typeof x==='object'){for(const v of Object.values(x))freeze(v);Object.freeze(x);}return x;};
const P=freeze(JSON.parse(pinBytes)),SOURCE_SHA=sha(fs.readFileSync(__filename)),H=/^[a-f0-9]{64}$/;
const ownedErrors=new WeakSet();function fail(code){const e=Object.assign(new Error(code),{code});ownedErrors.add(e);throw e;}
function exact(x,keys){if(!x||Object.getPrototypeOf(x)!==Object.prototype||Reflect.ownKeys(x).length!==keys.length||keys.some(k=>{const d=Object.getOwnPropertyDescriptor(x,k);return !d?.enumerable||!Object.hasOwn(d,'value');}))fail('CONTINUITY_SHAPE_REFUSED');}
function canon(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(canon).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canon(x[k])).join(',')+'}';}
const equal=(a,b)=>typeof a==='string'&&H.test(a)&&typeof b==='string'&&H.test(b)&&crypto.timingSafeEqual(Buffer.from(a,'hex'),Buffer.from(b,'hex'));
const mac=(key,domain,body)=>crypto.createHmac('sha256',key).update(domain+canon(body)).digest('hex');
function decoded(bytes){return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
function stat(file,mode,dir=false){const s=fs.lstatSync(file);if(path.resolve(file)!==file||fs.realpathSync(file)!==file||s.isSymbolicLink()||(dir?!s.isDirectory():!s.isFile())||s.uid!==P.uid||s.gid!==P.gid||(s.mode&0o777)!==mode||!dir&&s.nlink!==1)fail('CONTINUITY_OWNERSHIP_REFUSED');return s;}
const same=(a,b)=>['dev','ino','size','mtimeMs','ctimeMs','nlink','uid','gid','mode'].every(k=>a[k]===b[k]);
function absent(file){try{fs.lstatSync(file);fail('CONTINUITY_PENDING_OR_WAL_REFUSED');}catch(e){if(e?.code!=='ENOENT')throw e;}}
function read(file,mode,max,tracked){const s=stat(file,mode);if(s.size<=0||s.size>max)fail('CONTINUITY_FILE_REFUSED');let fd;try{fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);if(!same(s,fs.fstatSync(fd)))fail('CONTINUITY_FILE_CHANGED');const b=Buffer.alloc(s.size+1),n=fs.readSync(fd,b,0,b.length,0);if(n!==s.size||!same(s,fs.fstatSync(fd))||!same(s,stat(file,mode)))fail('CONTINUITY_FILE_CHANGED');tracked.push({file,mode,stat:s,hash:sha(b.subarray(0,n))});return Buffer.from(b.subarray(0,n));}finally{if(fd!==undefined)fs.closeSync(fd);}}
function signed(bytes,key,domain){const x=decoded(bytes);exact(x,['body','mac']);if(!equal(x.mac,mac(key,domain,x.body)))fail('CONTINUITY_HMAC_REFUSED');return x.body;}
function unpack(value,key){const p=typeof value==='string'?value.split('.'):[];if(p.length!==4||p[0]!=='v1'||p.slice(1).some(x=>!x))fail('CONTINUITY_KEY_REFUSED');const b=p.slice(1).map(x=>{const b=Buffer.from(x,'base64url');if(b.toString('base64url')!==x)fail('CONTINUITY_KEY_REFUSED');return b;});if(b[0].length!==12||b[1].length!==16||b[2].length>4096)fail('CONTINUITY_KEY_REFUSED');const d=crypto.createDecipheriv('aes-256-gcm',key,b[0]);d.setAuthTag(b[1]);return new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat([d.update(b[2]),d.final()]));}
function pack(bytes,expected){const x=decoded(bytes),key=x.schema==='shrigma_dashboard_operational_pack_v1'?'gzipBase64':x.schema==='shrigma_dashboard_operational_pack_v2'?'brotliBase64':null;if(!key)fail('CONTINUITY_PACK_REFUSED');exact(x,['schema','sha256',key]);if(x.sha256!==expected||typeof x[key]!=='string'||Buffer.from(x[key],'base64').toString('base64')!==x[key])fail('CONTINUITY_PACK_REFUSED');const b=Buffer.from(x[key],'base64');let raw;if(key==='gzipBase64')raw=zlib.gunzipSync(b,{maxOutputLength:16*1024*1024});else{const r=zlib.brotliDecompressSync(b,{maxOutputLength:16*1024*1024,info:true});if(r.engine.bytesWritten!==b.length)fail('CONTINUITY_PACK_REFUSED');raw=r.buffer;}if(sha(raw)!==expected)fail('CONTINUITY_PACK_REFUSED');}
function historical(bytes,key){const plan=P.originalConsumedPlan,proof=signed(bytes['readonly-observation.json'],key,P.domains.proof),fence=signed(bytes['activation-once.json'],key,P.domains.fence),result=signed(bytes['activation-result.json'],key,P.domains.result);
 exact(fence,['schema','plan','proofSha256']);if(fence.schema!=='crm-own-master-startup-fixed-fence-v1'||canon(fence.plan)!==canon(plan))fail('CONTINUITY_ORIGINAL_PLAN_REFUSED');
 exact(proof,['schema','operationId','issuedAt','expiresAt','observerProgramSha256','attestationSha256','imageDigest','nativeAdmissionSha256','sourceOld','sourceNew','master']);
 if(proof.schema!=='crm-own-master-original-runtime-observation-body-v1'||proof.operationId!==plan.operationId||proof.imageDigest!==plan.imageDigest||proof.nativeAdmissionSha256!==plan.nativeAdmissionSha256||proof.observerProgramSha256!==P.historicalPublicDependencies.observerProgramSha256||proof.attestationSha256!==P.historicalPublicDependencies.attestationSha256||!Number.isSafeInteger(proof.issuedAt)||proof.issuedAt<0||!Number.isSafeInteger(proof.expiresAt)||proof.expiresAt!==plan.expiresAt||proof.expiresAt<=proof.issuedAt||proof.expiresAt>proof.issuedAt+300000)fail('CONTINUITY_OBSERVATION_REFUSED');
 exact(proof.sourceOld,['commit','runtimePackSha256']);exact(proof.sourceNew,['commit','runtimePackSha256','ciRuntimeBytes','ciTransportSha256']);const t=P.transitionHistoricalConfig;if(proof.sourceOld.commit!=='710ffb49f6c065072c8c073ef8269f8c33b589b7'||proof.sourceOld.runtimePackSha256!==t.oldPackSha256||proof.sourceNew.commit!==t.sourceRevision||proof.sourceNew.runtimePackSha256!==t.newPackSha256||proof.sourceNew.ciRuntimeBytes!==t.newPackBytes||proof.sourceNew.ciTransportSha256!==t.newPackTransportSha256)fail('CONTINUITY_OBSERVATION_REFUSED');
 const m=proof.master;exact(m,['schema','profile','queryOnly','fileSystemReadOnly','walAuxiliaryWritesMayOccur','state','reason','sqliteReadOnly','originalBindingValid','pendingClear','nativeAttemptAvailable','identityFourCaps','snapshotUnchanged','catalogs','nativeSourcePinsVerified','templateBrandExclusivityProven','businessMutations','iamUsageTelemetryMayUpdate']);if(m.schema!=='crm-own-master-original-runtime-observation-result-v1'||m.profile!=='original-owned-runtime-query-only-v1'||m.state!=='observed-compatible'||m.reason!=='REQUIRES_NATIVE_SOURCE_AND_INSTALLATION_ADMISSION'||['queryOnly','sqliteReadOnly','originalBindingValid','pendingClear','nativeAttemptAvailable','identityFourCaps','snapshotUnchanged','walAuxiliaryWritesMayOccur','iamUsageTelemetryMayUpdate'].some(k=>m[k]!==true)||['fileSystemReadOnly','nativeSourcePinsVerified','templateBrandExclusivityProven','businessMutations'].some(k=>m[k]!==false))fail('CONTINUITY_OBSERVATION_REFUSED');exact(m.catalogs,['fish','aristo']);for(const b of ['fish','aristo']){exact(m.catalogs[b],['compatible']);if(m.catalogs[b].compatible!==true)fail('CONTINUITY_OBSERVATION_REFUSED');}
 const envelope={schema:'crm-own-master-original-runtime-observation-custody-v1',body:proof,bodySha256:sha(canon(proof)),custodyMac:mac(key,P.domains.proof,proof)};if(!equal(fence.proofSha256,sha(canon(envelope))))fail('CONTINUITY_ORIGINAL_PLAN_REFUSED');
 exact(result,['schema','fenceSha256','state','code','markerConsumed','writerVerified','confirmedAt']);if(result.schema!=='crm-own-master-startup-result-v1'||!equal(result.fenceSha256,sha(canon(fence)))||result.state!=='confirmed'||result.code!=='NATIVE_WRITER_CONFIRMED'||result.markerConsumed!==true||result.writerVerified!==true||!Number.isSafeInteger(result.confirmedAt)||result.confirmedAt<proof.issuedAt)fail('CONTINUITY_RESULT_REFUSED');return {confirmedAt:result.confirmedAt};
}
function sourceFingerprint(db){const schema=db.prepare('SELECT type,name,tbl_name,sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type,name').all(),tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all(),h=crypto.createHash('sha256');let size=Buffer.byteLength(JSON.stringify(schema));if(size>32*1024*1024)fail('CONTINUITY_SOURCE_REFUSED');h.update(JSON.stringify(schema));for(const {name}of tables){if(typeof name!=='string'||name.length>200)fail('CONTINUITY_SOURCE_REFUSED');h.update(JSON.stringify(name));if(name==='sessions'||name==='login_limits')continue;const stmt=db.prepare('SELECT * FROM "'+name.replaceAll('"','""')+'"');stmt.setReadBigInts(true);const rows=[];for(const row of stmt.iterate()){const pairs=Object.entries(row).map(([k,v])=>{if(typeof v==='string'&&Buffer.from(v).toString('utf8')!==v)fail('CONTINUITY_SOURCE_REFUSED');if(v instanceof Uint8Array&&v.byteLength>16*1024*1024)fail('CONTINUITY_SOURCE_REFUSED');return [k,typeof v==='bigint'?['integer',v.toString()]:v instanceof Uint8Array?['blob',Buffer.from(v).toString('hex')]:v];});const s=JSON.stringify(pairs);size+=Buffer.byteLength(s);if(size>32*1024*1024)fail('CONTINUITY_SOURCE_REFUSED');rows.push(s);}rows.sort();for(const r of rows){h.update(r);h.update('\n');}}return h.digest('hex');}
function master(db,key){const rows=db.prepare("SELECT id,email,role,state,password_hash,totp_secret FROM users WHERE role='superadmin'").all();if(rows.length!==1)fail('CONTINUITY_MASTER_REFUSED');const m=rows[0];if(m.email!==P.owner||m.role!=='superadmin'||m.state!=='active'||typeof m.id!=='string'||!m.id||m.id.length>64||typeof m.password_hash!=='string'||!m.password_hash)fail('CONTINUITY_MASTER_REFUSED');const g=db.prepare('SELECT area,can_read,can_edit FROM grants WHERE user_id=? ORDER BY area').all(m.id);if(g.length!==3||new Set(g.map(g=>g.area)).size!==3||!['growth','organico','influs'].every(a=>g.some(g=>g.area===a&&g.can_read===1)))fail('CONTINUITY_GRANT_REFUSED');let cipher,expected;const has=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='identity_metadata'").all();if(has.length===1){const r=db.prepare("SELECT encrypted_value FROM identity_metadata WHERE key='encryption_verifier'").all();if(r.length>1)fail('CONTINUITY_KEY_REFUSED');if(r.length){cipher=r[0].encrypted_value;expected='shrigma-identity-v1';}}if(cipher===undefined)cipher=m.totp_secret;const plain=unpack(cipher,key);if(!plain||expected&&plain!==expected)fail('CONTINUITY_KEY_REFUSED');return {m,g};}
function writer(db,key,m,g,now,confirmedAt){const plan=P.originalConsumedPlan,r=db.prepare('SELECT encrypted_value FROM identity_metadata WHERE key=?').all('native_master_campaign_writer_once_v1');if(r.length!==1)fail('CONTINUITY_WRITER_REFUSED');const expected=JSON.stringify({schema:'CRM_NATIVE_OWN_MASTER_SQLITE_WRITER_V1',operationId:plan.operationId,owner:P.owner,action:'install-own-master-campaign-writer',programSha256:plan.programSha256,expiresAt:plan.expiresAt});if(unpack(r[0].encrypted_value,key)!==expected)fail('CONTINUITY_ORIGINAL_PLAN_REFUSED');
 const rows=db.prepare("SELECT a.*,c.key_digest,c.encrypted_key FROM campaign_writer_attestation_v1 a JOIN upstream_credentials c ON c.user_id=a.user_id AND c.slot='growth-campaign' WHERE a.user_id=?").all(m.id),bindings=db.prepare("SELECT binding_mac FROM upstream_brand_bindings_v1 WHERE user_id=? AND slot='growth-campaign'").all(m.id);if(rows.length!==1||bindings.length!==1||!g.some(g=>g.area==='growth'&&g.can_edit===1))fail('CONTINUITY_WRITER_REFUSED');const a=rows[0];if(a.user_id!==m.id||a.owner!==P.owner||!equal(a.credential_mac,a.key_digest)||!Number.isSafeInteger(a.attested_at)||a.attested_at<0||a.attested_at>now||!Number.isSafeInteger(a.expires_at)||a.expires_at<=now||a.expires_at>a.attested_at+14*86400000||typeof a.principal_id!=='string'||!/^master-[a-f0-9]{64}$/.test(a.principal_id))fail('CONTINUITY_WRITER_REFUSED');const brand=v=>crypto.createHmac('sha256',key).update('identity-brand-v1:'+JSON.stringify(v)).digest('hex');if(!equal(a.master_proof_mac,brand(['campaign-master-writer-v1',m.id,m.email,'master','todos',a.principal_id,a.credential_mac,a.expires_at,a.attested_at,['read_content','draft','validate','submit']]))||!equal(bindings[0].binding_mac,brand([m.id,m.email,'growth-campaign','all',null,a.key_digest,sha(a.encrypted_key)]))||db.prepare('SELECT 1 FROM upstream_credentials WHERE key_digest=? AND user_id<>? LIMIT 1').get(a.key_digest,m.id))fail('CONTINUITY_WRITER_REFUSED');let bearer;try{bearer=unpack(a.encrypted_key,key);if(!/^[a-z0-9-]{8,128}$/.test(bearer)||!equal(a.key_digest,crypto.createHmac('sha256',key).update('upstream-key:'+bearer).digest('hex')))fail('CONTINUITY_WRITER_REFUSED');}finally{bearer=undefined;}return a.expires_at;}
function createReadOnlyContinuity({enabled=false,encryptionKey,admitNewSource,clock=Date.now}={}){
 const issued=new WeakMap();let busy=false;
 function time(){const n=clock();if(!Number.isSafeInteger(n)||n<0)fail('CONTINUITY_CLOCK_REFUSED');return n;}
 async function verify(staticOnly){if(enabled!==true||!Buffer.isBuffer(encryptionKey)||encryptionKey.length!==32||typeof admitNewSource!=='function'||typeof clock!=='function')fail('CONTINUITY_OFF');if(busy)fail('CONTINUITY_BUSY');busy=true;let key;const tracked=[],dbs=[];try{
  if(process.platform!=='linux'||process.arch!=='x64'||process.version!=='v22.23.3'||process.getuid?.()!==P.uid||process.getgid?.()!==P.gid||['NODE_OPTIONS','NODE_PATH','NODE_DEBUG','DEBUG','LD_PRELOAD','LD_LIBRARY_PATH'].some(k=>process.env[k]))fail('CONTINUITY_RUNTIME_REFUSED');
  const input={purpose:staticOnly?'verify-preserved-files-only':'verify-existing-continuity-only',moduleSha256:SOURCE_SHA,pinsSha256:PINS_SHA,inputSha256:P.inputSha256,service:P.currentService};const admission=await admitNewSource(Object.freeze(input));exact(admission,['admitted','purpose','moduleSha256','pinsSha256','inputSha256','service','newReleaseRevision','newReleaseImageDigest']);if(admission.admitted!==true||['purpose','moduleSha256','pinsSha256','inputSha256'].some(k=>admission[k]!==input[k])||canon(admission.service)!==canon(input.service)||!/^[a-f0-9]{40}$/.test(admission.newReleaseRevision)||admission.newReleaseRevision===P.originalConsumedPlan.sourceRevision||!H.test(admission.newReleaseImageDigest)||admission.newReleaseImageDigest===P.originalConsumedPlan.imageDigest||admission.newReleaseImageDigest===P.currentImage.split('@sha256:')[1])fail('CONTINUITY_NEW_ADMISSION_REFUSED');
  key=Buffer.from(encryptionKey);const now=time();stat(P.root,0o700,true);stat(P.source,0o700,true);stat(P.state,0o700,true);const mounts=fs.readFileSync('/proc/self/mountinfo','utf8').trim().split('\n').map(l=>l.split(' ')),src=mounts.filter(x=>x[4]===P.source),dst=mounts.filter(x=>x[4]===P.root);if(src.length!==1||dst.length!==1||!src[0][5].split(',').includes('ro')||!dst[0][5].split(',').includes('rw')||src[0][3]===dst[0][3])fail('CONTINUITY_MOUNT_REFUSED');
  const historicalBytes={};for(const p of P.preservedMasterFiles){const b=read(P.state+'/'+p.name,p.mode,8192,tracked);if(b.length!==p.bytes||sha(b)!==p.sha256)fail('CONTINUITY_ORIGINAL_FILES_REFUSED');historicalBytes[p.name]=b;}const past=historical(historicalBytes,key);
  const t=P.transitionHistoricalConfig,sealBytes=read(P.root+'/.efc-prestart-parity-v2.json',0o600,2048,tracked),seal=signed(sealBytes,key,P.domains.parity);exact(seal,['schema','bindingSha256','guardSha256','paritySha256','sourceMasterId']);if(seal.schema!=='crm-efc-prestart-parity-v2'||seal.bindingSha256!==t.originalParityConfig.bindingSha256||seal.guardSha256!==t.originalParityConfig.guardSha256||sha(canon(t.originalParityConfig.binding))!==seal.bindingSha256||!H.test(seal.paritySha256)||typeof seal.sourceMasterId!=='string'||!seal.sourceMasterId||seal.sourceMasterId.length>64||t.originalParityConfig.sourceMode!=='stopped')fail('CONTINUITY_PARITY_REFUSED');
  const current=read(P.root+'/runtime-pack.json',0o600,950000,tracked),old=read(P.root+'/.runtime-pack-'+t.oldPackSha256+'.rollback.json',0o600,950000,tracked);absent(P.root+'/.runtime-pack-'+t.sourceRevision+'.staged');if(current.length!==t.newPackBytes||sha(current)!==t.newPackTransportSha256||t.newPackSha256!==P.oldRuntimePackSha256)fail('CONTINUITY_PACK_REFUSED');pack(current,t.newPackSha256);pack(old,t.oldPackSha256);const transition=signed(read(P.root+'/.runtime-pack-'+t.sourceRevision+'.transition.json',0o600,4096,tracked),key,P.domains.transition),expectedTransition={schema:'crm-owned-runtime-pack-transition-v1',originalSealSha256:sha(sealBytes),originalBindingSha256:t.originalParityConfig.bindingSha256,upgradeGuardSha256:t.upgradeGuardSha256,sourceRevision:t.sourceRevision,oldPackSha256:t.oldPackSha256,oldPackTransportSha256:sha(old),newPackSha256:t.newPackSha256,newPackTransportSha256:t.newPackTransportSha256,newPackBytes:t.newPackBytes};if(canon(transition)!==canon(expectedTransition))fail('CONTINUITY_TRANSITION_REFUSED');
  function stable(){for(const x of tracked){if(!same(x.stat,stat(x.file,x.mode)))fail('CONTINUITY_FILE_CHANGED');if(x.hash!==undefined&&sha(read(x.file,x.mode,x.stat.size,[]))!==x.hash)fail('CONTINUITY_FILE_CHANGED');}}
  if(staticOnly){stable();return Object.freeze({schema:'shrigma-read-only-preserved-files-v1',originalFilesPreserved:true,originalSealAndPackTransitionVerified:true,existingGrantVerified:false,currentWriterVerified:false,environmentProof:false,sqliteOpened:false,historicalAttemptRemainsConsumed:true,moduleSha256:SOURCE_SHA,pinsSha256:PINS_SHA,sourceOnly:true,operational:false,writes:0,oldInvocations:0});}
  // immutable=1 cannot write WAL/SHM. Refuse auxiliary files instead of ignoring
  // committed WAL data or performing a checkpoint/cleanup/snapshot.
  const {DatabaseSync}=require('node:sqlite');function open(dir){const file=dir+'/dashboard.sqlite';for(const s of ['-wal','-shm','-journal'])absent(file+s);const s=stat(file,0o600);if(s.size<=0||s.size>64*1024*1024)fail('CONTINUITY_DATABASE_REFUSED');tracked.push({file,mode:0o600,stat:s});const db=new DatabaseSync('file:'+file+'?immutable=1',{readOnly:true});dbs.push(db);const integrity=db.prepare('PRAGMA integrity_check').all();if(integrity.length!==1||integrity[0].integrity_check!=='ok'||db.prepare('PRAGMA foreign_key_check').all().length)fail('CONTINUITY_DATABASE_REFUSED');return db;}
  const source=open(P.source),target=open(P.root),oldMaster=master(source,key),currentMaster=master(target,key);if(oldMaster.m.id!==seal.sourceMasterId||currentMaster.m.id!==seal.sourceMasterId||sourceFingerprint(source)!==seal.paritySha256)fail('CONTINUITY_PARITY_REFUSED');const expires=writer(target,key,currentMaster.m,currentMaster.g,now,past.confirmedAt);
  stable();for(const dir of [P.root,P.source])for(const s of ['-wal','-shm','-journal'])absent(dir+'/dashboard.sqlite'+s);const end=time();if(end<now||end>=expires)fail('CONTINUITY_WRITER_REFUSED');
  const proof=Object.freeze({schema:'shrigma-read-only-existing-continuity-v1',existingGrantVerified:true,originalFilesPreserved:true,originalParityVerified:true,originalPackTransitionVerified:true,currentWriterVerified:true,historicalAttemptRemainsConsumed:true,issuedAt:end,expiresAt:Math.min(end+P.proofLifetimeMs,expires),moduleSha256:SOURCE_SHA,pinsSha256:PINS_SHA,newReleaseRevision:admission.newReleaseRevision,newReleaseImageDigest:admission.newReleaseImageDigest,sourceOnly:true,operational:false,writes:0,oldInvocations:0});issued.set(proof,{used:false});return proof;
 }catch(e){if(ownedErrors.has(e))throw e;fail('CONTINUITY_REFUSED');}finally{for(const db of dbs)try{db.close();}catch{}key?.fill(0);busy=false;}}
 function environmentForExistingGrant(env,proof){const entry=proof&&issued.get(proof);if(!entry||entry.used||time()<proof.issuedAt||time()>=proof.expiresAt)fail('CONTINUITY_PROOF_REFUSED');entry.used=true;if(!env||Object.getPrototypeOf(env)!==Object.prototype||Reflect.ownKeys(env).some(k=>typeof k!=='string'||!Object.hasOwn(Object.getOwnPropertyDescriptor(env,k),'value')||typeof env[k]!=='string'))fail('CONTINUITY_ENVIRONMENT_REFUSED');let upstreams,hosts,manifest;try{upstreams=JSON.parse(env.DASHBOARD_UPSTREAMS);hosts=JSON.parse(env.DASHBOARD_UPSTREAM_HOSTS);manifest=JSON.parse(env.DASHBOARD_DYNAMIC_ROUTE_MANIFEST||'null');}catch{fail('CONTINUITY_ENVIRONMENT_REFUSED');}
  if(!upstreams||Object.getPrototypeOf(upstreams)!==Object.prototype)fail('CONTINUITY_ENVIRONMENT_REFUSED');const r=P.routes,readOnly=Object.keys(upstreams).sort().join(',')==='crm-read',own=Object.keys(upstreams).sort().join(',')==='campaigns,crm-read';if(!readOnly&&!own||upstreams['crm-read']!==r.read||own&&upstreams.campaigns!==r.campaigns||!Array.isArray(hosts)||hosts.length<1||hosts.length>(hosts.includes(r.host)?8:7)||new Set(hosts).size!==hosts.length||hosts.some(h=>typeof h!=='string'||!h||h.length>253||!/^[a-z0-9.-]+$/.test(h))||!hosts.includes(new URL(r.read).hostname))fail('CONTINUITY_ENVIRONMENT_REFUSED');const expected={schema:r.schema,sourceRevision:r.revision,routes:{campaigns:r.campaigns}};if(readOnly&&manifest!==null||own&&canon(manifest)!==canon(expected))fail('CONTINUITY_ENVIRONMENT_REFUSED');
  return {...env,DASHBOARD_UPSTREAMS:JSON.stringify({'crm-read':r.read,campaigns:r.campaigns}),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify(hosts.includes(r.host)?hosts:[...hosts,r.host]),DASHBOARD_DYNAMIC_ROUTE_MANIFEST:JSON.stringify(expected),DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE:'own-master-production-v1',DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'enabled',DASHBOARD_CRM_CORPORATE_CREATE:'disabled',DASHBOARD_CRM_DRAFT_WRITE:'disabled',DASHBOARD_CRM_AUDIENCE_DRAFT:'disabled',DASHBOARD_CRM_MANAGED_READ:'disabled',DASHBOARD_CRM_MANAGED_READ_UI:'disabled',DASHBOARD_CRM_MANAGED_AUDIENCE_READ:'disabled',DASHBOARD_CRM_MANAGED_TEMPLATE_READ:'disabled',DASHBOARD_CRM_MANAGED_WRITER:'disabled'};
 }
 return Object.freeze({verifyExistingContinuity:()=>verify(false),verifyPreservedFiles:()=>verify(true),environmentForExistingGrant});
}
module.exports=Object.freeze({createReadOnlyContinuity,ENABLED:false,moduleSha256:SOURCE_SHA,pinsSha256:PINS_SHA});
