'use strict';
// Synthetic descriptors/credentials; no real issuer, network, SQL server or workers.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {load,original,root,extra,runtime,inputs}=require('./load.cjs'),S=load('server.cjs'),A=load('auth.cjs'),C=load('crm-individual-coexistence.cjs'),R=load('crm-manager-runtime.cjs'),P=load('proxy.cjs');
const domains=['oaristocrata.com','shrigma.com.br','fishermans.com.br'],hosts={growth:'crm.shrigma.com.br',organico:'organico.shrigma.com.br',influs:'influs.shrigma.com.br'},uuid=n=>String(n).padStart(8,'0')+'-0000-4000-8000-000000000000';
const read={issuerId:uuid(1),namespaceId:uuid(2),provisionerToken:'r'.repeat(43)},writer={mode:'corporate-read-writer-v1',issuerId:uuid(3),namespaceId:uuid(4),provisionerToken:'w'.repeat(43)};
function options(on=true){return {dbPath:':memory:',managerHost:'gerencial.shrigma.com.br',areaHosts:hosts,allowedEmailDomains:domains,bootstrapAdminEmail:'felipebandeira@oaristocrata.com',bootstrapTokenSha256:'a'.repeat(64),encryptionKey:Buffer.alloc(32,1).toString('hex'),crmCampaignWriterProfile:'own-master-production-v1',crmCampaignSubmitWrite:true,...(on?{crmIndividualCoexistence:true,crmManagedRead:{issuerId:read.issuerId,namespaceId:read.namespaceId},crmManagedWriter:{mode:writer.mode,issuerId:writer.issuerId,namespaceId:writer.namespaceId}}:{})};}
function env(on=false){const routes={'crm-read':P.FIXED_DESTINATIONS['crm-read'],campaigns:P.REVIEWED_DYNAMIC.routes.campaigns,segments:P.REVIEWED_DYNAMIC.routes.segments};return {DASHBOARD_PUBLIC_DIR:'/tmp/synthetic-public',DASHBOARD_MODE:'operational',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE:'own-master-production-v1',DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'enabled',DASHBOARD_CRM_MASTER_AUDIENCE_READ:'enabled',DASHBOARD_MANAGER_HOST:'gerencial.shrigma.com.br',DASHBOARD_AREA_HOSTS:JSON.stringify(hosts),DASHBOARD_EMAIL_DOMAINS:JSON.stringify(domains),DASHBOARD_ADMIN_EMAIL:'felipebandeira@oaristocrata.com',DASHBOARD_UPSTREAMS:JSON.stringify(routes),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify([...new Set(Object.values(routes).map(s=>new URL(s).hostname))]),DASHBOARD_DYNAMIC_ROUTE_MANIFEST:JSON.stringify({schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:routes.campaigns,segments:routes.segments}}),...(on?{DASHBOARD_CRM_INDIVIDUAL_COEXISTENCE:'enabled',DASHBOARD_CRM_MANAGED_READ:'enabled',DASHBOARD_CRM_MANAGED_READ_UI:'enabled',DASHBOARD_CRM_MANAGER_ISSUER_ID:read.issuerId,DASHBOARD_CRM_MANAGER_NAMESPACE_ID:read.namespaceId,DASHBOARD_CRM_MANAGER_PROVISIONER_TOKEN:read.provisionerToken,DASHBOARD_CRM_MANAGED_WRITER:'enabled',DASHBOARD_CRM_WRITER_DESCRIPTOR:JSON.stringify({mode:writer.mode,issuerId:writer.issuerId,namespaceId:writer.namespaceId}),DASHBOARD_CRM_WRITER_PROVISIONER_TOKEN:writer.provisionerToken}:{})};}
test('OFF environment matches original settings and old profile still denies managed coexistence',()=>{const old=original('server.cjs');const off=S.settingsFromEnv(env());assert.deepEqual(off,old.settingsFromEnv(env()));assert.equal(off.crmIndividualCoexistence,undefined);assert.equal(C.validate(options(false)),false);assert.throws(()=>A.createAuth({...options(true),crmIndividualCoexistence:false}),/MASTER_WRITER_CONFIG_INVALID/);assert.throws(()=>S.settingsFromEnv({...env(true),DASHBOARD_CRM_INDIVIDUAL_COEXISTENCE:'disabled'}),/Own Master/);const preserved=env();assert.equal(S.environmentForOriginalMasterIndividualCoexistence({},preserved),preserved);});
test('ON explicit concrete descriptors compose Master and individual journals; private identities remain distinct',()=>{const s=S.settingsFromEnv(env(true));assert.equal(s.crmIndividualCoexistence,true);assert.equal(s.crmCampaignWriterProfile,'own-master-production-v1');assert.equal(s.crmManagedWriter.mode,'corporate-read-writer-v1');const opts=S.authOptionsFor({...s,...options(false),crmIndividualCoexistence:true,crmManagedRead:s.crmManagedRead,crmManagedWriter:s.crmManagedWriter});const auth=A.createAuth(opts);try{assert(auth.managedCrmJournal);assert(auth.managedCampaignWriterJournal);assert.equal(typeof auth.ownMasterPublishedJourneyReadBinding,'function');assert.equal(typeof auth.activateOwnMasterCampaignWriter,'function');assert.equal(typeof auth.managedCrmReadAuthorization,'function');}finally{auth.close();}});
test('incomplete/ambiguous descriptors, duplicated issuer namespace or tokens refuse startup',()=>{for(const mutate of [e=>delete e.DASHBOARD_CRM_WRITER_DESCRIPTOR,e=>e.DASHBOARD_CRM_MANAGED_READ='disabled',e=>e.DASHBOARD_CRM_MANAGER_PROVISIONER_TOKEN='short',e=>e.DASHBOARD_CRM_WRITER_PROVISIONER_TOKEN=read.provisionerToken,e=>e.DASHBOARD_CRM_WRITER_DESCRIPTOR=JSON.stringify({...writer,issuerId:read.issuerId}),e=>e.DASHBOARD_CRM_INDIVIDUAL_COEXISTENCE='true']){const e=env(true);mutate(e);assert.throws(()=>S.settingsFromEnv(e));}assert.throws(()=>C.validate({...options(true),crmIndividualCoexistence:'enabled'}));assert.throws(()=>C.validate({...options(false),crmIndividualCoexistence:true}));});
test('last bounded environment projection preserves every original Master property and is OFF identity',()=>{const preserved=env(),before=structuredClone(preserved),request=env(true);request.DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE='corporate-read-writer-v1';request.DASHBOARD_ENCRYPTION_KEY='do-not-copy';const out=S.environmentForOriginalMasterIndividualCoexistence(request,preserved);assert.deepEqual(preserved,before);assert.equal(out.DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE,preserved.DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE);assert.equal(out.DASHBOARD_ENCRYPTION_KEY,undefined);assert.equal(out.DASHBOARD_UPSTREAMS,preserved.DASHBOARD_UPSTREAMS);assert.equal(S.environmentForOriginalMasterIndividualCoexistence({},preserved),preserved);assert.equal(S.environmentForOriginalMasterIndividualCoexistence({DASHBOARD_CRM_INDIVIDUAL_COEXISTENCE:'disabled'},preserved),preserved);});
test('original MAC and binding functions byte identical; own Master descriptor retains priority',()=>{const original=fs.readFileSync(path.join(inputs,'auth.cjs'),'utf8'),candidate=fs.readFileSync(path.join(runtime,'auth.cjs'),'utf8');for(const [start,end]of [[' const masterWriterMac=',' function installMasterCampaignWriter'],[' function upstreamBindingMac',' function recordUpstreamBinding']]){const a=original.slice(original.indexOf(start),original.indexOf(end,original.indexOf(start))),b=candidate.slice(candidate.indexOf(start),candidate.indexOf(end,candidate.indexOf(start)));assert.equal(a,b);}assert.match(candidate,/masterWriter=coexistence\?ownMasterWriter:corporateWriter\|\|ownMasterWriter/);assert.match(fs.readFileSync(path.join(runtime,'server.cjs'),'utf8'),/campaignWriter=coexistence\?ownMasterWriter:corporateWriter\|\|ownMasterWriter/);assert.match(candidate,/const creator=build\(masterWriter\)/);assert.match(candidate,/individual=build\(corporateWriter\)/);});
test('dormant composition coalesces explicit work, preserves failures and closes both exactly once',async()=>{let release,reads=0,writes=0,rc=0,wc=0,fulfill=0;const read={kick(){reads++;return new Promise(r=>release=r);},close(){rc++;return Promise.resolve();}},writer={kick(){writes++;return Promise.resolve();},close(){wc++;return Promise.resolve();}},runtime=C.compose({read,writer,auth:{fulfillManagedCampaignWriterRequests(){fulfill++;},reconcileUserProfileUpdates(){}}});assert.equal(reads,0);const first=runtime.kick();assert.equal(runtime.kick(),first);await new Promise(r=>setImmediate(r));assert.equal(reads,1);const close=runtime.close();assert.equal(runtime.close(),close);release({ready:1});await close;assert.equal(writes,0);assert.equal(fulfill,0);assert.equal(rc,1);assert.equal(wc,1);await runtime.kick();assert.equal(reads,1);});
test('individual issuer failure cannot trigger writer issuance or a Master call',async()=>{let writerCalls=0;const runtime=C.compose({read:{kick:async()=>{throw Error('synthetic issuer down');},close:async()=>{}},writer:{kick:async()=>{writerCalls++;},close:async()=>{}},auth:{fulfillManagedCampaignWriterRequests(){throw Error('must not issue');},reconcileUserProfileUpdates(){}}});const result=await runtime.kick();assert.equal(result[0].status,'rejected');assert.equal(writerCalls,1);await runtime.close();});
test('server ON has no listening provisioner hook; journeys remain Master-only and template bridge separated',()=>{const s=fs.readFileSync(path.join(runtime,'server.cjs'),'utf8');assert.match(s,/if\(!coexistence\)server.once\('listening',kickManagedCrm\)/);assert.match(s,/auth.session\(ctx\).user\?\.role==='superadmin'\|\|\['fluxos_listar','fluxos_capacidade'\]/);assert.match(s,/templateRead:found.user\?\.role==='manager'&&coexistence\?crmManagedTemplateRead&&managedReadReady/);assert.match(s,/crmIndividualAccessUnavailable:!coexistence/);assert.match(s,/operational:false/);});
process.on('exit',()=>{if(process.env.ANALYST_COEXISTENCE_EXTRA_PINS)fs.writeFileSync(process.env.ANALYST_COEXISTENCE_EXTRA_PINS,JSON.stringify([...extra.values()],null,2)+'\n');});

test('same synthetic persisted Master session credential MAC and proof survive opt-in without rotation',()=>{
 const {DatabaseSync}=require('node:sqlite'),os=require('node:os'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'c2-coexist-')),dbPath=path.join(dir,'identity.sqlite'),now=Date.now(),key=Buffer.alloc(32,1),opts={...options(false),dbPath,now:()=>now};
 const old=original('auth.cjs').createAuth(opts);old.close();let db=new DatabaseSync(dbPath);const user=db.prepare("SELECT * FROM users WHERE role='superadmin'").get();
 const token='s'.repeat(43),credential='m'.repeat(64),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),mac=x=>crypto.createHmac('sha256',key).update('identity-brand-v1:'+JSON.stringify(x)).digest('hex');
 const iv=Buffer.alloc(12,2),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(credential),cipher.final()]),encryptedKey=['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.'),digest=crypto.createHmac('sha256',key).update('upstream-key:'+credential).digest('hex'),principal='synthetic-original-master',expires=now+86400000;
 db.prepare("UPDATE users SET state='active',bootstrap_hash=NULL WHERE id=?").run(user.id);db.prepare("UPDATE grants SET can_edit=1 WHERE user_id=? AND area='growth'").run(user.id);
 db.prepare('INSERT INTO sessions(token_hash,user_id,host,ui_key,created_at,expires_at,idle_expires_at) VALUES(?,?,?,?,?,?,?)').run(hash(token),user.id,hosts.growth,'ui-synthetic-fixed',now,expires,expires);
 db.prepare('INSERT INTO upstream_credentials(user_id,slot,encrypted_key,key_digest,updated_at) VALUES(?,?,?,?,?)').run(user.id,'growth-campaign',encryptedKey,digest,now);
 db.prepare('INSERT INTO campaign_writer_attestation_v1(user_id,owner,principal_id,credential_mac,expires_at,attested_at,master_proof_mac) VALUES(?,?,?,?,?,?,?)').run(user.id,user.email,principal,digest,expires,now,mac(['campaign-master-writer-v1',user.id,user.email,'master','todos',principal,digest,expires,now,['read_content','draft','validate','submit']]));
 db.prepare('INSERT INTO upstream_brand_bindings_v1(user_id,slot,binding_mac) VALUES(?,?,?)').run(user.id,'growth-campaign',mac([user.id,user.email,'growth-campaign','all',null,digest,hash(encryptedKey)]));
 const before=db.prepare('SELECT * FROM upstream_credentials').all(),sessions=db.prepare('SELECT token_hash,user_id,host,ui_key FROM sessions').all();db.close();const ctx={method:'GET',host:hosts.growth,origin:'https://'+hosts.growth,csrf:crypto.createHmac('sha256',key).update('csrf:'+token).digest('base64url'),cookieHeader:'__Host-shrigma_sid='+token};
 const legacy=original('auth.cjs').createAuth(opts);assert.equal(legacy.campaignWriterReady(ctx),true);const oldSession=legacy.session(ctx);legacy.close();
 const auth=A.createAuth({...options(true),dbPath,now:()=>now});try{assert.equal(auth.campaignWriterReady(ctx),true);assert.equal(auth.getUpstreamCredential({...ctx,area:'growth',edit:true,slot:'growth-campaign'}),credential);assert.deepEqual(auth.session(ctx),oldSession);db=new DatabaseSync(dbPath);assert.deepEqual(db.prepare('SELECT * FROM upstream_credentials').all(),before);assert.deepEqual(db.prepare('SELECT token_hash,user_id,host,ui_key FROM sessions').all(),sessions);db.close();}finally{auth.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('individual READ uses only individual slot and rechecks lifecycle/generation/credential after awaits',async()=>{
 const T=load('crm-template-read-bridge.cjs'),M=load('crm-master-template-read.cjs'),ctx={method:'GET',host:hosts.growth,brand:'fish'},credential='d'.repeat(64);
 function binding(){return {userId:uuid(9),owner:'synthetic@shrigma.com.br',lifecycleId:uuid(8),lifecycleVersion:1,principalId:'dcrm-'+'b'.repeat(32),generation:1,expiresAt:Date.now()+60000,credentialMac:'c'.repeat(64),slot:'crm-panel-read',caps:['read_content','list_history','submission']};}
 const dto=M.project({templates:[],consultado_em:new Date().toISOString()},'fish');
 for(const mutate of [a=>a.generation++,a=>a.lifecycleVersion++,a=>a.credentialMac='e'.repeat(64),a=>a.expiresAt=Date.now()-1,a=>a.userId=uuid(10),a=>null]){
  let current=binding(),release;const calls=[];
  const auth={managedCrmReadAuthorization(c){if(c.brand!=='fish'||!current)throw Error('synthetic revoked');return {...current,caps:[...current.caps]};},getUpstreamCredential(c){assert.equal(c.slot,'crm-panel-read');return credential;}};
  const bridge=T.createTemplateReadBridge({auth,upstreams:{'template-read':new URL(T.DESTINATIONS['template-read'])},enabled:true},{fetchImpl:(u,o)=>{calls.push({u:String(u),o});return new Promise(r=>release=r);}});
  const pending=bridge.read({context:ctx,route:'templates',method:'GET',query:new URLSearchParams('acao=listar&marca=fish&canal=email'),origin:'https://'+hosts.growth});
  while(!release)await new Promise(r=>setImmediate(r));const changed=mutate(current);if(changed===null)current=null;release(new Response(JSON.stringify(dto),{headers:{'content-type':'application/json'}}));await assert.rejects(pending);assert.equal(calls.length,1);assert.equal(calls[0].o.method,'GET');assert.equal(calls[0].o.headers.Authorization,'Bearer '+credential);assert.notEqual(calls[0].o.headers.Authorization,'Bearer '+'m'.repeat(64));
 }
});
test('individual READ denies wrong brand host purpose and writes before network; Master refuses manager original journeys',async()=>{
 const T=load('crm-template-read-bridge.cjs');let calls=0;const auth={managedCrmReadAuthorization(){throw Error('no synthetic grant');},getUpstreamCredential(){throw Error('no credential');}},bridge=T.createTemplateReadBridge({auth,enabled:true,upstreams:{'template-read':new URL(T.DESTINATIONS['template-read'])}},{fetchImpl:()=>{calls++;throw Error('never');}});
 for(const v of [{method:'POST'},{query:new URLSearchParams('acao=submissao&marca=fish&submission_id=test')},{context:{method:'GET',host:hosts.growth,brand:'aristo'}},{origin:'https://evil.example'}])await assert.rejects(bridge.read({context:{method:'GET',host:hosts.growth,brand:'fish'},route:'templates',method:'GET',query:new URLSearchParams('acao=listar&marca=fish&canal=email'),origin:'https://'+hosts.growth,...v}));assert.equal(calls,0);
 const s=fs.readFileSync(path.join(inputs,'auth.cjs'),'utf8');assert.match(s,/user.role!=='superadmin'.*PUBLISHED_JOURNEY_READ_DENIED/s);
});
test('real creator keeps same uncertain attempt, one POST, and denies renewed writer after awaits',async()=>{
 const {DatabaseSync}=require('node:sqlite'),Create=load('crm-campaign-create.cjs');
 for(const renew of [false,true]){
  const db=new DatabaseSync(':memory:'),stash=new Map();let serial=0,valid=true,post=0;const calls=[],proof={userId:uuid(9),role:'manager',slot:'growth-campaign',canEdit:true,credentialMac:'a'.repeat(64),caps:['read_content','draft','validate','submit']};
  const creator=Create.createCampaignCreator({db,enabled:true,profile:writer.mode,corporateWriter:R.corporateWriterDescriptor(writer,read,domains),allowedEmailDomains:domains,authorize(){if(!valid)throw Error('revoked');return {...proof,caps:[...proof.caps]};},transport:async(ctx,q)=>{calls.push(q);if(q.method==='POST'){post++;if(renew)proof.credentialMac='b'.repeat(64);throw Error('synthetic ACK unknown');}if(q.command.acao==='campanha_catalogo')return {status:200,body:{synthetic:true}};return {status:404,body:{}};},now:Date.now,encrypt:s=>{const c='v1.a.b.'+String(++serial);stash.set(c,s);return c;},decrypt:s=>stash.get(s),preflightDefinition:d=>d,prepareDefinition:d=>({definition:d}),hasOpenDelivery:()=>false});
  const q={acao:'campanha_criar',brand:'fish',definition:{brand:'fish',send_at:null},idempotency_key:'synthetic_attempt_001'},ctx={method:'POST'};
  if(renew){await assert.rejects(creator.submit(ctx,q),e=>e.code==='CAMPAIGN_CREATE_DENIED');assert.equal(db.prepare('SELECT phase FROM crm_campaign_create_v1').get().phase,'uncertain');await assert.rejects(creator.submit(ctx,q));}
  else {assert.equal((await creator.submit(ctx,q)).state,'pending');const row=db.prepare('SELECT * FROM crm_campaign_create_v1').get();assert.equal(row.phase,'uncertain');await creator.submit(ctx,q);await creator.reconcile({method:'GET'},{brand:q.brand,idempotency_key:q.idempotency_key});const checks=calls.filter(c=>c.command.acao==='campanha_operacao');assert(checks.length>=1);assert(checks.every(c=>c.method==='GET'&&c.command.idempotency_key===row.remote_key));assert.equal(db.prepare('SELECT remote_key FROM crm_campaign_create_v1').get().remote_key,row.remote_key);}
  assert.equal(post,1);db.close();
 }
});
test('actual composed server startup stays dormant and close drains without extra issuance',async()=>{
 const settings={...S.settingsFromEnv(env(true)),crmPublishedJourneyRead:true,crmMasterTemplateRead:true},auth=A.createAuth({...S.authOptionsFor(settings),...options(true)});let kicks=0,closes=0;
 const runtime={kick:async()=>{kicks++;},close:async()=>{closes++;}};
 try{const server=S.createServer(settings,{auth,managedCrmRuntime:runtime,fetchImpl:()=>{throw Error('no synthetic network');}});assert.equal(server.listenerCount('listening'),require('node:http').createServer().listenerCount('listening'));server.emit('listening');assert.equal(kicks,0);server.emit('close');await new Promise(r=>setImmediate(r));assert.equal(closes,1);assert.equal(kicks,0);}finally{auth.close();}
});
test('same real server dispatch serves concurrent Master and individual template readers with separate credentials',async()=>{
 const T=load('crm-template-read-bridge.cjs'),M=load('crm-master-template-read.cjs'),EventEmitter=require('node:events');const e=env(true);e.DASHBOARD_CRM_MANAGED_TEMPLATE_READ='enabled';const allowed=JSON.parse(e.DASHBOARD_UPSTREAM_HOSTS);allowed.push(new URL(T.DESTINATIONS['template-read']).hostname);e.DASHBOARD_UPSTREAM_HOSTS=JSON.stringify([...new Set(allowed)]);const settings={...S.settingsFromEnv(e),crmPublishedJourneyRead:true,crmMasterTemplateRead:true};
 const real=A.createAuth(options(true)),who=c=>({id:c.cookieHeader==='master'?uuid(5):uuid(9),role:c.cookieHeader==='master'?'superadmin':'manager',brand:c.cookieHeader==='master'?null:'fish',areas:['growth'],permissions:{growth:{read:true,edit:false}}}),originalCredential='m'.repeat(64),individualCredential='d'.repeat(64),individualExpiry=Date.now()+60000;
 const auth={...real,session:c=>({authenticated:true,user:who(c)}),authorize:c=>who(c),authorizeBrand(c,b){if(who(c).role==='manager'&&b!=='fish')throw Object.assign(Error('BRAND_DENIED'),{status:403,code:'BRAND_DENIED'});return who(c);},managedCrmJournal:{status:()=>({state:'ready'})},managedCrmReadAuthorization(c){if(c.brand!=='fish')throw Error('brand');return {userId:uuid(9),owner:'synthetic@shrigma.com.br',lifecycleId:uuid(8),lifecycleVersion:1,principalId:'dcrm-'+'b'.repeat(32),generation:1,expiresAt:individualExpiry,credentialMac:'c'.repeat(64),slot:'crm-panel-read',caps:['read_content','list_history','submission']};},getUpstreamCredential(c){assert.equal(c.slot,'crm-panel-read');assert.notEqual(c.cookieHeader,'master');return individualCredential;},ownMasterPublishedJourneyReadBinding(c){if(who(c).role!=='superadmin')throw Object.assign(Error('PUBLISHED_JOURNEY_READ_DENIED'),{status:403,code:'PUBLISHED_JOURNEY_READ_DENIED'});return {userId:uuid(5),binding:'original-master',credential:originalCredential};},ownMasterPublishedJourneyReadReady:c=>who(c).role==='superadmin'};
 const upstream={templates:[],consultado_em:new Date().toISOString()},calls=[],server=S.createServer(settings,{auth,managedCrmRuntime:{kick:async()=>{},close:async()=>{}},fetchImpl:async(u,o)=>{calls.push({url:String(u),credential:o.headers.Authorization});await new Promise(r=>setImmediate(r));return new Response(JSON.stringify(String(u).startsWith(M.DESTINATION)?upstream:M.project(upstream,'fish')),{headers:{'content-type':'application/json'}});}});
 const dispatch=(cookie,url)=>new Promise(resolve=>{const res=new EventEmitter();Object.assign(res,{setHeader(){},end(s){this.writableFinished=true;resolve({status:this.statusCode,body:JSON.parse(s)});this.emit('finish');},destroy(){this.destroyed=true;resolve({status:0});}});server.emit('request',{method:'GET',url,headers:{host:hosts.growth,cookie,origin:'https://'+hosts.growth},socket:{remoteAddress:'synthetic'}},res);});
 try{const results=await Promise.all([dispatch('master','/api/templates?acao=listar&marca=fish&canal=email'),dispatch('individual','/api/templates?acao=listar&marca=fish&canal=email')]);assert.deepEqual(results.map(r=>r.status),[200,200]);assert.equal(calls.length,2);assert(calls.some(c=>c.url.startsWith(M.DESTINATION)&&c.credential==='Bearer '+originalCredential));assert(calls.some(c=>c.url.startsWith(T.DESTINATIONS['template-read'])&&c.credential==='Bearer '+individualCredential));const denied=await dispatch('individual','/api/templates?acao=fluxos_capacidade&marca=fish');assert.equal(denied.status,403);assert.equal(calls.length,2);}finally{server.emit('close');real.close();}
});
test('new operation guards reject lifecycle/version change despite unchanged credential MAC and never repeat POST',async()=>{let revision=1,post=0;const snapshot=()=>JSON.stringify({revision,credentialMac:'same'}),transport=C.guardedTransport(async()=>{revision++;return {status:200,body:{private:'late'}};},snapshot);await assert.rejects(transport({}, {method:'GET',command:{brand:'fish'}}),e=>e.code==='CRM_CURRENT_BINDING_CHANGED');const operations=C.guardedOperations({submit:async()=>{post++;revision++;return {state:'pending'};}},snapshot);await assert.rejects(operations.submit({}, {brand:'fish',idempotency_key:'same'}),e=>e.code==='CRM_CURRENT_BINDING_CHANGED');assert.equal(post,1);const master=C.guardedTransport(async()=>{revision++;return 'preserved';},()=>null);assert.equal(await master({}, {command:{brand:'fish'}}),'preserved');});
