'use strict';
// Inert on import/OFF. Providers are trusted application code, never STDIO helpers.
const BOOT='crm-manager-read-private-bootstrap-v1',READY='crm-manager-read-bootstrap-ready-v1',ACK='crm-manager-read-bootstrap-ack-v1',RESULT='crm-manager-read-driver-result-v1',PLAN='crm-manager-read-driver-plan-file-v1',BIND='crm-manager-read-driver-scope-binding-v1';
const MAX_BOOT=16384,MAX_PRIVATE=4096,BOOT_MS=10000;
const freeze=Object.freeze,refuse=()=>{throw Error('READ_STAGE_DRIVER_REFUSED');};
function exact(v,keys){if(!v||Object.getPrototypeOf(v)!==Object.prototype)refuse();const ks=Reflect.ownKeys(v);if(ks.length!==keys.length||ks.some(k=>typeof k!=='string'||!keys.includes(k)))refuse();for(const k of ks){const d=Object.getOwnPropertyDescriptor(v,k);if(!d?.enumerable||!Object.hasOwn(d,'value'))refuse();}}
function wellFormed(v,depth=0){if(depth>40)refuse();if(typeof v==='string'){if(!v.isWellFormed())refuse();return;}if(v===null||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v))return;if(!v||typeof v!=='object')refuse();if(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype)refuse();for(const k of Reflect.ownKeys(v)){if(Array.isArray(v)&&k==='length')continue;const d=Object.getOwnPropertyDescriptor(v,k);if(typeof k!=='string'||!k.isWellFormed()||!d?.enumerable||!Object.hasOwn(d,'value'))refuse();wellFormed(d.value,depth+1);}}
function parse(b){if(b[0]===0xef&&b[1]===0xbb&&b[2]===0xbf)refuse();let value;try{value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(b));}catch{refuse();}wellFormed(value);return value;}
function canonical(v){return Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);}
function result(state,value=null){return freeze({schema:RESULT,state,result:value});}
function readPinned(file,digest,max){
 const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');if(typeof file!=='string'||!path.isAbsolute(file)||path.resolve(file)!==file||typeof digest!=='string'||!/^[a-f0-9]{64}$/.test(digest))refuse();
 const dir=path.dirname(file),ds=fs.lstatSync(dir);if(!ds.isDirectory()||ds.isSymbolicLink()||ds.uid!==process.getuid()||(ds.mode&0o7777)!==0o700||fs.realpathSync(dir)!==dir)refuse();
 const before=fs.lstatSync(file),same=s=>{if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.uid!==process.getuid()||(s.mode&0o7777)!==0o600||s.size<1||s.size>max||s.dev!==before.dev||s.ino!==before.ino||s.mtimeMs!==before.mtimeMs||s.ctimeMs!==before.ctimeMs)refuse();};same(before);const fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let b;
 try{same(fs.fstatSync(fd));b=fs.readFileSync(fd);same(fs.fstatSync(fd));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}same(fs.lstatSync(file));if(b.length!==before.size||crypto.createHash('sha256').update(b).digest('hex')!==digest)refuse();return b;
}
function ttyPolicy(input){if(input?.isTTY!==true||!Number.isSafeInteger(input.fd))refuse();let text;try{text=require('node:child_process').execFileSync('stty',['-a'],{stdio:[input.fd,'pipe','pipe'],timeout:1000,maxBuffer:8192}).toString('utf8');}catch{refuse();}const tokens=text.split(/[;\s]+/);if(!tokens.includes('-echo')||!tokens.includes('-icanon')||tokens.includes('echo')||tokens.includes('icanon'))refuse();return freeze({echoDisabled:true,canonicalDisabled:true});}
function write(output,v){return new Promise((resolve,reject)=>{try{output.write(JSON.stringify(v)+'\n',e=>e?reject(Error('READ_STAGE_DRIVER_REFUSED')):resolve());}catch{reject(Error('READ_STAGE_DRIVER_REFUSED'));}});}
function bootstrap(input,output,plan,mode,verify,timers,signal){return new Promise((resolve,reject)=>{
 let settled=false,chunks=[],bytes=0,timer;const finish=(error,value)=>{if(settled)return;settled=true;input.pause();input.removeListener('data',data);input.removeListener('end',end);input.removeListener('error',end);signal?.removeEventListener('abort',end);timers.clearTimeout(timer);chunks=[];error?reject(Error('READ_STAGE_DRIVER_REFUSED')):resolve(value);},end=()=>finish(true);
 function data(chunk){try{if(typeof chunk==='string')refuse();const b=Buffer.from(chunk);bytes+=b.length;if(bytes>MAX_BOOT)refuse();chunks.push(b);const at=b.indexOf(10);if(at<0)return;if(at!==b.length-1||b.subarray(0,at).includes(10))refuse();const raw=Buffer.concat(chunks,bytes);if(raw.indexOf(10)!==raw.length-1||raw.at(-2)===13)refuse();const q=parse(raw.subarray(0,-1));exact(q,['schema','seq','mode','planSha256','adminPassword','servicePassword','serviceVerifier']);if(q.schema!==BOOT||q.seq!==0||q.mode!==mode||q.planSha256!==plan.planSha256||typeof q.adminPassword!=='string'||q.adminPassword.length<1||q.adminPassword.length>1024||/[\r\n\0\\']/.test(q.adminPassword))refuse();if(mode==='execute'?(typeof q.servicePassword!=='string'||!/^[a-f0-9]{64}$/.test(q.servicePassword)||typeof q.serviceVerifier!=='string'):(q.servicePassword!==null||q.serviceVerifier!==null))refuse();finish(false,q);}catch{finish(true);}}
 try{input.pause();const checked=verify(input);exact(checked,['echoDisabled','canonicalDisabled']);if(checked.echoDisabled!==true||checked.canonicalDisabled!==true||signal?.aborted)refuse();input.on('data',data);input.once('end',end);input.once('error',end);signal?.addEventListener('abort',end,{once:true});timer=timers.setTimeout(end,BOOT_MS);write(output,{schema:READY,seq:0,state:'awaiting-bootstrap',echoDisabled:true,canonicalDisabled:true,planSha256:plan.planSha256}).then(()=>{if(!settled)input.resume();},end);}catch{finish(true);}
 });}
function admitConfig(config){
 exact(config,Object.getOwnPropertyDescriptor(config||{},'enabled')?.value===true?['enabled','mode','stageApproved','readonlyReconcileApproved','planFile','planFileSha256','publicKeyFile','privateKeyFile','custodyDirectory','effectsDirectory','requestDirectory']:['enabled']);if(typeof config.enabled!=='boolean')refuse();if(!config.enabled)return false;
 if(!['execute','reconcile'].includes(config.mode)||typeof config.stageApproved!=='boolean'||typeof config.readonlyReconcileApproved!=='boolean'||(config.mode==='execute'?!config.stageApproved:!config.readonlyReconcileApproved))refuse();return true;
}
async function runUnsafe(config={enabled:false},deps){
 if(!admitConfig(config))return result('disabled');
 const optional=['verifyTty','timers','signal','getRetainedVerifier'].filter(k=>Object.hasOwn(deps||{},k));exact(deps,['input','output','bindScopes','admission','observeStatus',...optional]);for(const n of['bindScopes','admission','observeStatus'])if(typeof deps[n]!=='function')refuse();if(config.mode==='reconcile'&&typeof deps.getRetainedVerifier!=='function')refuse();
 const {input,output}=deps;if(typeof input?.on!=='function'||typeof input?.pause!=='function'||typeof input?.resume!=='function'||typeof input?.removeListener!=='function'||typeof output?.write!=='function')refuse();
 const timers=deps.timers||{setTimeout,clearTimeout};exact(timers,['setTimeout','clearTimeout']);if(typeof timers.setTimeout!=='function'||typeof timers.clearTimeout!=='function'||deps.verifyTty!==undefined&&typeof deps.verifyTty!=='function')refuse();if(deps.signal&&typeof deps.signal.addEventListener!=='function')refuse();
 const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),R=require('./remote-operator.cjs'),O=require('./operator.cjs'),E=require('./easypanel-plan.cjs'),S=require('./stage-runner.cjs');
 const pfile=parse(readPinned(config.planFile,config.planFileSha256,524288));exact(pfile,['schema','stage','reconcile','planSha256']);if(pfile.schema!==PLAN)refuse();exact(pfile.stage,['suffix','sources','intent','domainId',...(Object.hasOwn(pfile.stage||{},'isolatedProject')?['isolatedProject']:[])]);if(Object.hasOwn(pfile.stage,'isolatedProject')&&pfile.stage.isolatedProject!==true)refuse();const stage=R.buildStagePlan(pfile.stage);let plan=stage;if(config.mode==='reconcile'){exact(pfile.reconcile,['suffix','domainId']);plan=R.buildReconcilePlan({...pfile.reconcile,stagePlan:stage});}else if(pfile.reconcile!==null)refuse();if(pfile.planSha256!==plan.planSha256)refuse();
 const privateKey=O.loadPrivateKey(config.privateKeyFile),publicKey=config.mode==='execute'?O.loadPublicKey(config.publicKeyFile):null;if(publicKey&&!crypto.createPublicKey(privateKey).export({type:'spki',format:'der'}).equals(publicKey.export({type:'spki',format:'der'})))refuse();
 for(const d of[config.effectsDirectory,config.requestDirectory]){if(typeof d!=='string'||!path.isAbsolute(d)||path.resolve(d)!==d)refuse();const st=fs.lstatSync(d);if(!st.isDirectory()||st.isSymbolicLink()||st.uid!==process.getuid()||(st.mode&0o7777)!==0o700||fs.realpathSync(d)!==d)refuse();}
 if(typeof config.custodyDirectory!=='string'||!path.isAbsolute(config.custodyDirectory)||path.resolve(config.custodyDirectory)!==config.custodyDirectory)refuse();
 let runner=null,aborted=false,timer=null;const cancellers=new Set(),abort=()=>{aborted=true;for(const cancel of [...cancellers])cancel();void runner?.close().catch(()=>{});};deps.signal?.addEventListener('abort',abort,{once:true});input.once('end',abort);input.once('error',abort);
 function bounded(fn){return new Promise((resolve,reject)=>{let done=false;const end=(error,value)=>{if(done)return;done=true;cancellers.delete(cancel);timers.clearTimeout(timer);timer=null;error?reject(Error('READ_STAGE_DRIVER_REFUSED')):resolve(value);},cancel=()=>end(true);cancellers.add(cancel);timer=timers.setTimeout(cancel,BOOT_MS);Promise.resolve().then(()=>{if(aborted)refuse();return fn();}).then(v=>end(aborted,v),()=>end(true));});}
 try{
  const q=await bootstrap(input,output,plan,config.mode,deps.verifyTty||ttyPolicy,timers,deps.signal);if(aborted||input.readableLength!==undefined&&input.readableLength!==0)refuse();
  let verifier=q.serviceVerifier;if(plan.mode==='reconcile'){const held=O.openExisting({directory:config.custodyDirectory,intent:plan.intent,privateKey});const requested=freeze({schema:'crm-manager-read-driver-retained-verifier-request-v1',planSha256:plan.planSha256,credentialIntentId:plan.intent.credentialIntentId});verifier=await bounded(()=>deps.getRetainedVerifier(requested));if(verifier!==held.verifier)refuse();}
  // Canonical verifier now; existing custody checks the password pair before writing/fencing.
  require('../crm-manager-read-activation-review/activation.cjs').validateVerifier(verifier);
  const ep=E.buildEasypanelInputs({remotePlan:plan}),steps=Object.values(ep).filter(x=>x&&x.procedure),queries=steps.filter(x=>x.executor==='execute_query').map(x=>({procedure:x.procedure,input:x.input})),mutations=steps.filter(x=>x.executor!=='execute_query').map(x=>({procedure:x.procedure,input:x.input}));
  if(plan.parentStage){const prior=E.buildEasypanelInputs({remotePlan:plan.parentStage});for(const k of['inspect','inspectRunning','inspectDomains'])queries.push({procedure:prior[k].procedure,input:prior[k].input});for(const k of['stop','clearEnvironment','deleteTestDomain'])mutations.push({procedure:prior[k].procedure,input:prior[k].input});}
  const flags={READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:plan.mode,READ_ACTIVATION_APPROVED_ACTION:plan.mode==='execute'?'stage':'readonly-reconcile',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:plan.intent.operationId,READ_CREDENTIAL_INTENT_ID:plan.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'},pv=E.privateEnvInput({plan:ep,publicFlags:flags,verifier,adminPassword:q.adminPassword}),privateArgs={procedure:pv.procedure,input:{...pv.input,env:pv.input.env}};
  if(Buffer.byteLength(JSON.stringify({schema:'read-stdio-request-v1',seq:999999,kind:'mcp',visibility:'private',executor:pv.executor,args:privateArgs}))>MAX_PRIVATE)refuse();mutations.push(privateArgs);if(queries.length>16||mutations.length>16)refuse();for(const a of [...queries,...mutations]){freeze(a.input);freeze(a);}freeze(queries);freeze(mutations);
  const scopesSha256=crypto.createHash('sha256').update(canonical({queries,mutations})).digest('hex'),binding=freeze({schema:BIND,planSha256:plan.planSha256,mode:plan.mode,scopesSha256}),request={...binding};Object.defineProperties(request,{allowedQueries:{value:queries,enumerable:false},allowedMutations:{value:mutations,enumerable:false}});freeze(request);
  // The caller must install these exact scopes before invocation, never first-seen admission.
  const receipt=await bounded(()=>deps.bindScopes(request));exact(receipt,['schema','planSha256','mode','scopesSha256']);if(canonical(receipt)!==canonical(binding))refuse();if(aborted||input.readableLength!==undefined&&input.readableLength!==0)refuse();
  let first=true;const bridgeOutput={write(packet,callback){try{if(first){if(aborted||input.readableLength!==undefined&&input.readableLength!==0)refuse();const h=parse(Buffer.from(packet));if(h.schema!=='read-stdio-request-v1'||h.seq!==1||h.kind!=='mcp'||input.listenerCount('data')!==1)refuse();first=false;}const ok=output.write(packet,e=>{if(!e&&!aborted)input.resume();callback?.(e);});return ok;}catch{callback?.(Error('READ_STAGE_DRIVER_REFUSED'));return false;}}};
  runner=S.createStageRunner({enabled:true,stageApproved:config.stageApproved,readonlyReconcileApproved:config.readonlyReconcileApproved},{custody:{directory:config.custodyDirectory,privateKey},effectsDirectory:config.effectsDirectory,requestDirectory:config.requestDirectory,transport:{input,output:bridgeOutput},getAdminPassword:request=>{exact(request,['schema','planSha256','mode']);if(request.schema!=='crm-manager-read-stage-admin-request-v1'||request.planSha256!==plan.planSha256||request.mode!==plan.mode)refuse();return q.adminPassword;},admission:deps.admission,observeStatus:deps.observeStatus});
  await bounded(()=>write(output,{schema:ACK,seq:0,state:'accepted',planSha256:plan.planSha256}));if(aborted||input.readableLength!==undefined&&input.readableLength!==0)refuse();const value=plan.mode==='execute'?await runner.stage({plan,password:q.servicePassword,verifier,publicKey}):await runner.reconcile({plan});return result('completed',value);
 }catch{return result('hold');}finally{timers.clearTimeout(timer);input.pause();deps.signal?.removeEventListener('abort',abort);input.removeListener('end',abort);input.removeListener('error',abort);if(runner)await runner.close();}
}
async function runDriver(config={enabled:false},deps){try{return await runUnsafe(config,deps);}catch{return result('hold');}}
module.exports=freeze({runDriver,BOOT,READY,ACK,RESULT,PLAN,BIND,MAX_BOOT,MAX_PRIVATE,BOOT_MS});
if(require.main===module){
 (async()=>{const args=process.argv.slice(2);if(args.length===0){process.stdout.write(JSON.stringify(await runDriver())+'\n');return;}if(args.length!==5||args[0]!=='--opt-in')refuse();
  const config=parse(readPinned(args[1],args[2],16384));if(!admitConfig(config))refuse();const source=readPinned(args[3],args[4],65536),Module=require('node:module'),provider=new Module(args[3],module);provider.filename=args[3];provider.paths=module.paths;provider._compile(new TextDecoder('utf-8',{fatal:true}).decode(source),args[3]);exact(provider.exports,['createProviders']);if(typeof provider.exports.createProviders!=='function')refuse();
  const supplied=provider.exports.createProviders();exact(supplied,['bindScopes','admission','observeStatus',...(Object.hasOwn(supplied||{},'getRetainedVerifier')?['getRetainedVerifier']:[])]);const value=await runDriver(config,{...supplied,input:process.stdin,output:process.stdout});process.stdout.write(JSON.stringify(value)+'\n');process.exitCode=value.state==='completed'&&value.result?.state==='verified'?0:1;
 })().catch(()=>{process.stderr.write('READ_STAGE_DRIVER_REFUSED\n');process.exitCode=1;});
}
