'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{PassThrough}=require('node:stream'),{spawnSync}=require('node:child_process');
const D=require('./driver.cjs'),R=require('./remote-operator.cjs'),O=require('./operator.cjs'),C=require('../crm-manager-read-activation-review/compose/build-compose.cjs'),B=require('./stdio-bridge.cjs'),{createFunctionsRelay}=require('./functions-relay.js');
const sources=Object.fromEntries(Object.keys(C.PINS).map(n=>[n,fs.readFileSync(path.join(__dirname,'../crm-manager-read-activation-review/runtime',n),'utf8')]));
const pair=crypto.generateKeyPairSync('rsa',{modulusLength:4096,publicExponent:65537}),password='a7'.repeat(32),admin='SYNTHETIC_ADMIN_ONLY',salt=Buffer.from('0123456789abcdef'),salted=crypto.pbkdf2Sync(password,salt,4096,32,'sha256'),client=crypto.createHmac('sha256',salted).update('Client Key').digest(),verifier='SCRAM-SHA-256$4096:'+salt.toString('base64')+'$'+crypto.createHash('sha256').update(client).digest('base64')+':'+crypto.createHmac('sha256',salted).update('Server Key').digest('base64');salted.fill(0);client.fill(0);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(t,{reconcile=false,isolatedProject=false}={}){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'read-driver-synthetic-')));fs.chmodSync(root,0o700);t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const stage={suffix:crypto.randomBytes(6).toString('hex'),sources,intent:{schema:'crm-manager-read-runtime-intent-v1',operationId:crypto.randomUUID(),credentialIntentId:crypto.randomUUID(),action:'stage',fromPhase:'empty'},domainId:crypto.randomUUID(),...(isolatedProject?{isolatedProject:true}:{})},parent=R.buildStagePlan(stage),child=reconcile?{suffix:crypto.randomBytes(6).toString('hex'),domainId:crypto.randomUUID()}:null,plan=child?R.buildReconcilePlan({...child,stagePlan:parent}):parent;
 const pfile=path.join(root,'plan.json'),bytes=Buffer.from(JSON.stringify({schema:D.PLAN,stage,reconcile:child,planSha256:plan.planSha256})+'\n');fs.writeFileSync(pfile,bytes,{mode:0o600});const pub=path.join(root,'public.pem'),priv=path.join(root,'private.pem');fs.writeFileSync(pub,pair.publicKey.export({format:'pem',type:'spki'}),{mode:0o600});fs.writeFileSync(priv,pair.privateKey.export({format:'pem',type:'pkcs8'}),{mode:0o600});const effects=path.join(root,'effects'),requests=path.join(root,'requests'),custody=path.join(root,'capsule');fs.mkdirSync(effects,{mode:0o700});fs.mkdirSync(requests,{mode:0o700});
 const config={enabled:true,mode:plan.mode,stageApproved:!reconcile,readonlyReconcileApproved:reconcile,planFile:pfile,planFileSha256:sha(bytes),publicKeyFile:pub,privateKeyFile:priv,custodyDirectory:custody,effectsDirectory:effects,requestDirectory:requests},packet={schema:D.BOOT,seq:0,mode:plan.mode,planSha256:plan.planSha256,adminPassword:admin,servicePassword:reconcile?null:password,serviceVerifier:reconcile?null:verifier};return{root,plan,config,packet};}
function harness(f,{raw,tty,bind,admission,signal,timers,getRetainedVerifier}={}){const input=new PassThrough(),output=new PassThrough(),packets=[],calls=[],events=[];let relay=null,chain=Promise.resolve();
 const deps={input,output,verifyTty:()=>{events.push('tty');return tty||{echoDisabled:true,canonicalDisabled:true};},bindScopes:async q=>{events.push('bind');assert.equal(input.isPaused(),true);assert.equal(input.listenerCount('data'),0);assert.equal(JSON.stringify(q).includes(admin),false);assert.ok(q.allowedMutations.some(a=>a.procedure==='updateComposeEnv'&&a.input.env.includes(f.packet.adminPassword)));assert.ok(Object.isFrozen(q.allowedMutations));if(bind)return bind(q);relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:q.allowedQueries,allowedMutations:q.allowedMutations,timeoutMs:40000,readPublic:d=>B.readPublicFile(d),retainPrivate:()=>{},tools:{mcp__easypanel__execute_query:async args=>{calls.push(args.procedure);assert.equal(fs.existsSync(path.join(f.config.custodyDirectory,O.FILE)),true);const held=O.openExisting({directory:f.config.custodyDirectory,intent:f.plan.intent,privateKey:pair.privateKey});assert.equal(held.verifier,verifier);return{structuredContent:{procedure:args.procedure,result:[]}};}},writeToNode:line=>input.write(line)});return{schema:q.schema,planSha256:q.planSha256,mode:q.mode,scopesSha256:q.scopesSha256};},admission:admission||(()=>{events.push('admission');throw Error(admin);}),observeStatus:()=>{throw Error('SHOULD_NOT_OBSERVE');},...(signal?{signal}:{}),...(timers?{timers}:{}),...(getRetainedVerifier?{getRetainedVerifier}:{} )};
 output.on('data',chunk=>{const p=JSON.parse(chunk.toString());packets.push(p);if(p.schema===D.READY){assert.equal(input.listenerCount('data'),1);assert.equal(events.at(-1),'tty');events.push('ready');queueMicrotask(()=>{if(raw!==false)input.write(raw||JSON.stringify(f.packet)+'\n');});}else if(p.schema===D.ACK){events.push('ack');assert.equal(input.isPaused(),true);assert.equal(input.listenerCount('data'),0);}else{events.push('frame');assert.ok(relay);assert.equal(p.seq,1);assert.equal(input.listenerCount('data'),1);chain=chain.then(()=>relay.step(chunk.toString()));}});
 return{input,output,deps,packets,calls,events,async settled(){await chain;}};
}
function noEffect(f,h){assert.equal(fs.existsSync(f.config.custodyDirectory),false);assert.deepEqual(fs.readdirSync(f.config.effectsDirectory),[]);assert.deepEqual(fs.readdirSync(f.config.requestDirectory),[]);assert.equal(h.packets.some(p=>p.kind==='mcp'),false);assert.equal(h.packets.some(p=>p.schema===D.ACK),false);}

test('import and OFF never load composed dependencies or inspect provider/streams/files/environment',async()=>{const Module=require('node:module'),old=Module._load;delete require.cache[require.resolve('./driver.cjs')];Module._load=function(id,...r){if(id.includes('operator.cjs')||id.includes('stage-runner.cjs')||id==='node:fs')throw Error('SHOULD_NOT_LOAD');return old.call(this,id,...r);};try{const api=require('./driver.cjs'),deps=new Proxy({}, {get(){throw Error('SHOULD_NOT_TOUCH');},ownKeys(){throw Error('SHOULD_NOT_TOUCH');}});assert.deepEqual(await api.runDriver(undefined,deps),{schema:D.RESULT,state:'disabled',result:null});}finally{Module._load=old;}});
test('real wrappers: parser ready, pause/detach, exact prebound scopes, ACK0 then bridge1; custody precedes query and refusal never POSTs',async t=>{const f=fixture(t),h=harness(f),out=await D.runDriver(f.config,h.deps);await h.settled();assert.equal(out.state,'completed');assert.equal(out.result.state,'not_dispatched');assert.deepEqual(h.events,['tty','ready','bind','ack','frame','admission']);assert.deepEqual(h.calls,['listDomains']);assert.equal(h.input.listenerCount('data'),0);assert.equal(h.input.isPaused(),true);assert.equal(JSON.stringify(h.packets).includes(admin),false);assert.equal(JSON.stringify(out).includes(admin),false);for(const file of fs.readdirSync(f.config.requestDirectory)){const b=fs.readFileSync(path.join(f.config.requestDirectory,file),'utf8');for(const s of[admin,password,verifier])assert.equal(b.includes(s),false);}const ciphertext=fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE));const again=await D.runDriver(f.config,harness(f).deps);assert.equal(again.state,'hold');assert.ok(ciphertext.equals(fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE))));assert.equal(h.calls.length,1);});
test('missing providers or action approval fail before public-ready/key reads, with no default admission',async()=>{const config={enabled:true,mode:'execute',stageApproved:true,readonlyReconcileApproved:false,planFile:'/MISSING',planFileSha256:'a'.repeat(64),publicKeyFile:'/MISSING',privateKeyFile:'/MISSING',custodyDirectory:'/MISSING',effectsDirectory:'/MISSING',requestDirectory:'/MISSING'};for(const deps of[undefined,{input:new PassThrough(),output:new PassThrough(),bindScopes:()=>{},admission:()=>{}}])assert.equal((await D.runDriver(config,deps)).state,'hold');assert.equal((await D.runDriver({...config,stageApproved:false},new Proxy({}, {get(){throw Error('SHOULD_NOT_TOUCH');}}))).state,'hold');});
test('TTY ECHO/canonical refusal happens before parser readiness or secret delivery',async t=>{const f=fixture(t),h=harness(f,{tty:{echoDisabled:false,canonicalDisabled:true},raw:false});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.packets.length,0);assert.equal(h.input.listenerCount('data'),0);noEffect(f,h);});
test('exact seq0/binding/fields and unsafe password JSON are refused before scopes, capsule or frame',async t=>{for(const changed of[{seq:1},{mode:'reconcile'},{planSha256:'f'.repeat(64)},{adminPassword:admin+'\n'},{adminPassword:admin+'\u0000'},{extra:true},{servicePassword:null}]){const f=fixture(t),h=harness(f,{raw:JSON.stringify({...f.packet,...changed})+'\n'});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.events.includes('bind'),false);noEffect(f,h);}});
test('UTF8 fatal, escaped unpaired surrogate, BOM, malformed JSON and a second packet never reach invocation',async t=>{for(const mode of['utf8','surrogate','bom','json','second','trailing','crlf']){const f=fixture(t),line=JSON.stringify(f.packet)+'\n',raw=mode==='utf8'?Buffer.from([0xff,0x0a]):mode==='surrogate'?line.replace(admin,'\\ud800'):mode==='bom'?Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from(line)]):mode==='json'?'{\n':mode==='second'?line+line:mode==='trailing'?line+'x':line.replace(/\n$/,'\r\n'),h=harness(f,{raw});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');noEffect(f,h);}});
test('bootstrap budget is incremental even without newline, before any effects',async t=>{const f=fixture(t),h=harness(f,{raw:Buffer.alloc(D.MAX_BOOT+1,0x61)});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');noEffect(f,h);});
test('well-formed literal Unicode is accepted and private scope UTF8 size is precomputed before effect',async t=>{const f=fixture(t);f.packet.adminPassword='界'.repeat(1024);let called=false;const h=harness(f,{bind:q=>{called=true;const pv=q.allowedMutations.find(a=>a.input.env?.includes('READ_SERVICE_SCRAM'));const frame={schema:B.REQUEST,seq:999999,kind:'mcp',visibility:'private',executor:'execute_destructive',args:pv};assert.ok(Buffer.byteLength(JSON.stringify(frame))<=D.MAX_PRIVATE);throw Error('SYNTHETIC_HOLD');}});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(called,true);noEffect(f,h);});
test('scope receipt is exact before invocation; mismatched digest/extra key/provider error cannot create custody or frame',async t=>{for(const how of['sha','extra','throw']){const f=fixture(t),h=harness(f,{bind:q=>{if(how==='throw')throw Error(admin);return{schema:q.schema,planSha256:q.planSha256,mode:q.mode,scopesSha256:how==='sha'?'a'.repeat(64):q.scopesSha256,...(how==='extra'?{nativeApproved:true}:{})};}});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');noEffect(f,h);}});
test('canonical SCRAM and matching password remain custody gates; mismatched pair never writes or requests',async t=>{for(const v of['bad','pair']){const f=fixture(t);if(v==='bad')f.packet.serviceVerifier='NOT_SCRAM';else f.packet.servicePassword='b8'.repeat(32);const h=harness(f);assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(fs.existsSync(f.config.custodyDirectory),false);assert.deepEqual(fs.readdirSync(f.config.effectsDirectory),[]);assert.equal(h.packets.some(p=>p.kind==='mcp'),false);}});
test('startup EOF/abort/deadline refuse, remove parser and never invoke scopes or create intent',async t=>{for(const mode of['eof','abort','deadline']){const f=fixture(t),controller=new AbortController(),timersList=[],timers={setTimeout:(fn,ms)=>{const item={fn,ms};timersList.push(item);return item;},clearTimeout:()=>{}},h=harness(f,{raw:false,signal:controller.signal,timers});h.output.on('data',b=>{if(JSON.parse(b.toString()).schema===D.READY)queueMicrotask(()=>{if(mode==='eof')h.input.end();else if(mode==='abort')controller.abort();else timersList.at(-1).fn();});});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.ok(timersList.every(x=>x.ms===D.BOOT_MS));assert.equal(h.input.listenerCount('data'),0);noEffect(f,h);}});
test('prebinding callback timeout returns held without waiting or invoking runner; late binding cannot start it',async t=>{const f=fixture(t),timersList=[],timers={setTimeout:(fn,ms)=>{const x={fn,ms};timersList.push(x);return x;},clearTimeout:()=>{}};let release,bound;const begun=new Promise(r=>bound=r),gate=new Promise(r=>release=r),h=harness(f,{timers,bind:async q=>{bound();await gate;return{schema:q.schema,planSha256:q.planSha256,mode:q.mode,scopesSha256:q.scopesSha256};}}),running=D.runDriver(f.config,h.deps);await begun;timersList.at(-1).fn();assert.equal((await running).state,'hold');release();await new Promise(r=>setImmediate(r));noEffect(f,h);});
test('reconcile requires private SCRAM prebinding, never fresh secret; mismatched handoff preserves capsule bytes',async t=>{const f=fixture(t,{reconcile:true});const missing=harness(f);assert.equal((await D.runDriver(f.config,missing.deps)).state,'hold');assert.equal(missing.packets.length,0);O.sealNew({directory:f.config.custodyDirectory,intent:f.plan.intent,password,verifier,publicKey:pair.publicKey});const before=fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE)),h=harness(f,{getRetainedVerifier:q=>{assert.equal(q.planSha256,f.plan.planSha256);return verifier+'x';}});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.events.includes('bind'),false);assert.ok(before.equals(fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE))));assert.deepEqual(fs.readdirSync(f.config.effectsDirectory),[]);assert.equal(h.packets.some(p=>p.kind==='mcp'),false);});
test('public file content digest and rebuilt branded-plan SHA are separate gates',async t=>{for(const mode of['file','rebuilt']){const f=fixture(t);if(mode==='file')f.config.planFileSha256='a'.repeat(64);else{const v=JSON.parse(fs.readFileSync(f.config.planFile,'utf8'));v.planSha256='a'.repeat(64);const b=Buffer.from(JSON.stringify(v)+'\n');fs.writeFileSync(f.config.planFile,b);f.config.planFileSha256=sha(b);}const h=harness(f,{raw:false});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.packets.length,0);noEffect(f,h);}});
test('NOFOLLOW/private modes refuse plan symlink or exposed local key before bootstrap',async t=>{for(const how of['symlink','keymode']){const f=fixture(t);if(how==='symlink'){const target=f.config.planFile+'.target';fs.renameSync(f.config.planFile,target);fs.symlinkSync(target,f.config.planFile);}else fs.chmodSync(f.config.privateKeyFile,0o644);const h=harness(f,{raw:false});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.packets.length,0);noEffect(f,h);}});
test('CLI default OFF exits without providers/TTY; opt-in missing provider is closed generic refusal',()=>{const off=spawnSync(process.execPath,[__dirname+'/driver.cjs'],{env:{PATH:'/usr/bin:/bin'},encoding:'utf8'});assert.equal(off.status,0);assert.deepEqual(JSON.parse(off.stdout),{schema:D.RESULT,state:'disabled',result:null});assert.equal(off.stderr,'');const bad=spawnSync(process.execPath,[__dirname+'/driver.cjs','--opt-in','/MISSING','a'.repeat(64),'/MISSING','a'.repeat(64)],{env:{PATH:'/usr/bin:/bin'},encoding:'utf8'});assert.equal(bad.status,1);assert.equal(bad.stdout,'');assert.equal(bad.stderr,'READ_STAGE_DRIVER_REFUSED\n');});
test('abort during scope binding settles immediately and ignores a late receipt without invoking runner',async t=>{const f=fixture(t),controller=new AbortController();let release,began;const gate=new Promise(r=>release=r),start=new Promise(r=>began=r),h=harness(f,{signal:controller.signal,bind:async q=>{began();await gate;return{schema:q.schema,planSha256:q.planSha256,mode:q.mode,scopesSha256:q.scopesSha256};}}),running=D.runDriver(f.config,h.deps);await start;controller.abort();assert.equal((await running).state,'hold');release();await new Promise(r=>setImmediate(r));noEffect(f,h);});
test('mismatched RSA4096 pair is refused before READY, avoiding an unusable durable capsule',async t=>{const f=fixture(t),other=crypto.generateKeyPairSync('rsa',{modulusLength:4096,publicExponent:65537});fs.writeFileSync(f.config.publicKeyFile,other.publicKey.export({format:'pem',type:'spki'}));const h=harness(f,{raw:false});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.packets.length,0);noEffect(f,h);});
test('CLI validates action approval before loading even a correctly pinned trusted provider',t=>{const f=fixture(t),startup=path.join(f.root,'startup.json'),provider=path.join(f.root,'provider.cjs'),marker=path.join(f.root,'provider-loaded'),cfg=Buffer.from(JSON.stringify({...f.config,stageApproved:false})+'\n'),source=Buffer.from("require('node:fs').writeFileSync("+JSON.stringify(marker)+",'loaded');module.exports={createProviders(){throw Error('SHOULD_NOT_RUN')}};\n");fs.writeFileSync(startup,cfg,{mode:0o600});fs.writeFileSync(provider,source,{mode:0o600});const child=spawnSync(process.execPath,[__dirname+'/driver.cjs','--opt-in',startup,sha(cfg),provider,sha(source)],{env:{PATH:'/usr/bin:/bin'},encoding:'utf8'});assert.equal(child.status,1);assert.equal(child.stdout,'');assert.equal(child.stderr,'READ_STAGE_DRIVER_REFUSED\n');assert.equal(fs.existsSync(marker),false);});
test('late extra seq0 during paused ACK0 drain refuses before capsule/fence/first query',async t=>{const f=fixture(t),h=harness(f);h.output.on('data',b=>{if(JSON.parse(b.toString()).schema===D.ACK)h.input.write(JSON.stringify(f.packet)+'\n');});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(fs.existsSync(f.config.custodyDirectory),false);assert.deepEqual(fs.readdirSync(f.config.effectsDirectory),[]);assert.deepEqual(fs.readdirSync(f.config.requestDirectory),[]);assert.equal(h.packets.some(p=>p.kind==='mcp'),false);assert.deepEqual(h.calls,[]);});
test('JSON expansion of valid bootstrap control characters cannot exceed private4096 after bootstrap16KiB admission',async t=>{const f=fixture(t);f.packet.adminPassword='\u0001'.repeat(1024);const bytes=Buffer.byteLength(JSON.stringify(f.packet)+'\n');assert.ok(bytes<D.MAX_BOOT);const h=harness(f);assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.events.includes('bind'),false);noEffect(f,h);});

test('optional isolatedProject accepts only literal true; false/string/arbitrary project refuse before bootstrap/effects',async t=>{for(const extra of[{isolatedProject:false},{isolatedProject:'true'},{projectName:'arbitrary'}]){const f=fixture(t),v=JSON.parse(fs.readFileSync(f.config.planFile,'utf8'));Object.assign(v.stage,extra);const b=Buffer.from(JSON.stringify(v)+'\n');fs.writeFileSync(f.config.planFile,b);f.config.planFileSha256=sha(b);const h=harness(f,{raw:false});assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(h.packets.length,0);noEffect(f,h);}});

test('isolated project driver rebuild binds only the reviewed new target before query; admission refusal never creates a service',async t=>{
 const f=fixture(t,{isolatedProject:true}),h=harness(f),bind=h.deps.bindScopes;assert.equal(f.plan.descriptor.projectName,C.ISOLATED_PROJECT);
 h.deps.bindScopes=async q=>{for(const a of [...q.allowedQueries,...q.allowedMutations]){if(Object.hasOwn(a.input,'projectName'))assert.equal(a.input.projectName,C.ISOLATED_PROJECT);if(Object.hasOwn(a.input,'service'))assert.ok(a.input.service.startsWith(C.ISOLATED_PROJECT+'_'));if(a.input.serviceDestination)assert.equal(a.input.serviceDestination.projectName,C.ISOLATED_PROJECT);}return bind(q);};
 const out=await D.runDriver(f.config,h.deps);await h.settled();assert.equal(out.state,'completed');assert.equal(out.result.state,'not_dispatched');assert.deepEqual(h.calls,['listDomains']);assert.equal(h.events.includes('bind'),true);assert.equal(h.packets.filter(p=>p.kind==='mcp').length,1);assert.equal(h.packets.some(p=>p.executor!=='execute_query'&&p.kind==='mcp'),false);
});
test('isolated reconcile reconstruction retains original project, private verifier and ciphertext before prebinding refuses',async t=>{
 const f=fixture(t,{reconcile:true,isolatedProject:true});assert.equal(f.plan.parentStage.descriptor.projectName,C.ISOLATED_PROJECT);assert.equal(f.plan.descriptor.projectName,C.ISOLATED_PROJECT);
 O.sealNew({directory:f.config.custodyDirectory,intent:f.plan.intent,password,verifier,publicKey:pair.publicKey});const before=fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE));let bound=false;
 const h=harness(f,{getRetainedVerifier:q=>{assert.equal(q.planSha256,f.plan.planSha256);return verifier;},bind:q=>{bound=true;const names=new Set(q.allowedQueries.filter(a=>Object.hasOwn(a.input,'serviceName')).map(a=>a.input.serviceName));assert.ok(names.has(f.plan.descriptor.serviceName));assert.ok(names.has(f.plan.parentStage.descriptor.serviceName));for(const a of [...q.allowedQueries,...q.allowedMutations])if(Object.hasOwn(a.input,'projectName'))assert.equal(a.input.projectName,C.ISOLATED_PROJECT);throw Error('SYNTHETIC_PREBIND_HOLD');}});
 assert.equal((await D.runDriver(f.config,h.deps)).state,'hold');assert.equal(bound,true);assert.deepEqual(h.calls,[]);assert.equal(h.packets.some(p=>p.kind==='mcp'),false);assert.ok(before.equals(fs.readFileSync(path.join(f.config.custodyDirectory,O.FILE))));assert.deepEqual(fs.readdirSync(f.config.effectsDirectory),[]);
});
