'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),util=require('node:util');
const E=require('./easypanel-plan.cjs'),R=require('./remote-operator.cjs'),P=require('./public-postcondition.cjs'),C=require('../crm-manager-read-activation-review/compose/build-compose.cjs');
const sources=Object.fromEntries(Object.keys(C.PINS).map(n=>[n,fs.readFileSync(path.join(__dirname,'../crm-manager-read-activation-review/runtime',n),'utf8')]));
const intent=()=>({schema:'crm-manager-read-runtime-intent-v1',operationId:crypto.randomUUID(),credentialIntentId:crypto.randomUUID(),action:'stage',fromPhase:'empty'});
const flags=p=>({READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:'execute',READ_ACTIVATION_APPROVED_ACTION:'stage',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:p.intent.operationId,READ_CREDENTIAL_INTENT_ID:p.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'});
const verifier='SCRAM-SHA-256$4096:'+Buffer.alloc(16,1).toString('base64')+'$'+Buffer.alloc(32,2).toString('base64')+':'+Buffer.alloc(32,3).toString('base64'),password='SYNTHETIC_ADMIN_ONLY';
const closed=e=>e instanceof Error&&e.message==='READ_EASYPANEL_PLAN_REFUSED';
function plan(){return E.buildEasypanelInputs({remotePlan:R.buildStagePlan({suffix:crypto.randomBytes(6).toString('hex'),sources,intent:intent(),domainId:crypto.randomUUID()})});}
test('auto-deploy create is only public pinned network-none initialization; subsequent execution has no initializer and uses external volumes',()=>{
 const p=plan(),create=p.createPublicBootstrap.input,bootstrap=JSON.parse(create.source.content),exec=JSON.parse(p.updatePrivateSource.input.content);assert.equal(p.createPublicBootstrap.procedure,'createComposeService');assert.equal(p.createPublicBootstrap.executor,'execute_mutation');assert.equal(create.env,'');assert.deepEqual(create.domains,[]);assert.deepEqual(Object.keys(bootstrap.services),['init-volumes']);const init=bootstrap.services['init-volumes'];assert.equal(init.network_mode,'none');assert.deepEqual(init.environment,{});assert.equal(init.image,C.IMAGE);assert.equal(init.read_only,true);assert.deepEqual(init.cap_drop,['ALL']);assert.deepEqual(init.cap_add,['CHOWN']);assert.equal(init.cpus,0.1);assert.equal(init.mem_limit,67108864);assert.equal(init.memswap_limit,init.mem_limit);assert.equal(init.pids_limit,16);assert.equal(init.command.at(-1),C.buildInitializer(sources));assert.equal(bootstrap.networks,undefined);
 assert.deepEqual(Object.keys(exec.services),['gateway']);assert.equal(exec.services.gateway.depends_on,undefined);assert.equal(exec.volumes.source.external,true);assert.equal(exec.volumes.ledger.external,true);assert.equal(exec.volumes.source.name,p.sourceVolume);assert.equal(exec.volumes.ledger.name,p.ledgerVolume);assert.equal(exec.services.gateway.volumes.find(v=>v.target==='/review').read_only,true);assert.equal(exec.services.gateway.user,'1000:1000');assert.equal(exec.services.gateway.mem_limit,335544320);assert.deepEqual(exec.services.gateway.entrypoint,['timeout','-s','KILL','600']);assert.equal(exec.services.gateway.command.at(-1),'/review/supervisor.cjs');const pub=JSON.parse(p.updatePublicProbe.input.content);assert.equal(pub.services.gateway.command.at(-1),P.buildPublicPostcondition({remotePlan:p.remotePlan}).inline);assert.equal(pub.services.gateway.env_file,undefined);assert.equal(pub.volumes.ledger.external,true);assert.equal(p.unproven.destroyPreservesExternalVolumes,false);assert.equal(p.unproven.allStoppedContainersInspectable,false);
});
test('prepared procedure inputs match the discovered scopes and use destructive executor for replacement/deploy/stop only; no mutation executes',()=>{
 const p=plan();for(const key of ['inspect','updatePrivateSource','deployOnce','stop','clearEnvironment']){const i=p[key].input;assert.equal(i.projectName,p.target.projectName);assert.equal(i.serviceName,p.target.serviceName);if(key==='inspect')assert.equal(p[key].executor,'execute_query');else assert.equal(p[key].executor,'execute_destructive');}
 assert.equal(p.deployOnce.input.forceRebuild,false);assert.equal(p.clearEnvironment.input.env,'');assert.equal(p.clearEnvironment.input.createDotEnv,true);assert.equal(p.destroyIsolatedService,undefined);assert.equal(p.startPublicProbe.executor,'execute_mutation');assert.deepEqual(p.createTestDomain.input,{id:p.domain.id,certificateResolver:'',host:p.domain.host,https:true,path:'/',wildcard:false,middlewares:[],destinationType:'service',serviceDestination:{...p.target,composeService:'gateway',protocol:'http',port:8099,path:'/'}});assert.equal(p.deleteTestDomain.input.id,p.domain.id);assert.equal(p.inspectRunning.procedure,'getDockerContainers');assert.equal(p.inspectRunning.input.service,p.target.projectName+'_'+p.target.serviceName);assert.equal(p.privateDeployApproved,undefined);assert.equal(p.unproven.privateDeployApproved,false);assert.equal(Object.isFrozen(p.createPublicBootstrap.input.source),true);
});
test('private environment lives only in explicit RAM properties; serialization/inspection is public and cannot replace intent or target',()=>{
 const p=plan(),payload=E.privateEnvInput({plan:p,publicFlags:flags(p),verifier,adminPassword:password});assert.equal(payload.procedure,'updateComposeEnv');assert.equal(payload.input.projectName,p.target.projectName);assert.equal(payload.input.serviceName,p.target.serviceName);assert.ok(payload.input.env.includes("PG_ADMIN_PASSWORD='"+password+"'"));assert.ok(payload.input.env.includes("READ_SERVICE_SCRAM='"+verifier+"'"));for(const shown of [JSON.stringify(payload),util.inspect(payload),JSON.stringify(payload.input),util.inspect(payload.input)]){assert.equal(shown.includes(password),false);assert.equal(shown.includes(verifier),false);}assert.equal(Object.keys(payload).includes('input'),false);assert.equal(Object.keys(payload.input).includes('env'),false);
 for(const changed of [{READ_ACTIVATION_OPERATION_ID:crypto.randomUUID()},{READ_CREDENTIAL_INTENT_ID:crypto.randomUUID()},{READ_ACTIVATION_MODE:'reconcile',READ_ACTIVATION_APPROVED_ACTION:'readonly-reconcile'},{EXTRA:'x'}])assert.throws(()=>E.privateEnvInput({plan:p,publicFlags:{...flags(p),...changed},verifier,adminPassword:password}),closed);
});
test('getter/symbol/unbranded input and unsupported dotenv bytes are refused before values are read; no secret escaping is guessed',()=>{
 const p=plan();let reads=0;for(const value of ["contains'quote",'has\\slash','new\nline','zero\0byte'])assert.throws(()=>E.privateEnvInput({plan:p,publicFlags:flags(p),verifier,adminPassword:value}),closed);
 const getter={};Object.defineProperty(getter,'schema',{enumerable:true,get(){reads++;return p.schema;}});assert.throws(()=>E.privateEnvInput({plan:getter,publicFlags:flags(p),verifier,adminPassword:password}),closed);const badFlags=flags(p);Object.defineProperty(badFlags,'READ_ACTIVATION_OPERATION_ID',{enumerable:true,get(){reads++;return p.intent.operationId;}});assert.throws(()=>E.privateEnvInput({plan:p,publicFlags:badFlags,verifier,adminPassword:password}),closed);assert.throws(()=>E.privateEnvInput({plan:JSON.parse(JSON.stringify(p)),publicFlags:flags(p),verifier,adminPassword:password}),closed);assert.throws(()=>E.privateEnvInput({plan:p,publicFlags:flags(p),verifier,adminPassword:password,[Symbol('secret')]:true}),closed);assert.equal(reads,0);
});
