'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),vm=require('node:vm'),{EventEmitter}=require('node:events');
const P=require('./provider-factory.cjs');
const BASE=__dirname;
const R=require(BASE+'/remote-operator.cjs'),E=require(BASE+'/easypanel-plan.cjs');
const {buildSyntheticFixture}=require('./fixture.cjs');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
function fixture(t){
 const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'read-provider-unit-')));fs.chmodSync(dir,0o700);t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const synthetic=buildSyntheticFixture(BASE);assert.equal(synthetic.classification,'SYNTHETIC_TEST_ONLY_NOT_NATIVE_EVIDENCE');
 const pf=synthetic.planFileBytes,plan=synthetic.plan,ep=E.buildEasypanelInputs({remotePlan:plan}),steps=Object.values(ep).filter(x=>x&&x.procedure);
 // Synthetic-only scope material; it remains in test RAM, never an output/fixture file.
 const password='8'.repeat(64),salt=Buffer.alloc(16,9),salted=crypto.pbkdf2Sync(password,salt,4096,32,'sha256'),ck=crypto.createHmac('sha256',salted).update('Client Key').digest(),verifier='SCRAM-SHA-256$4096:'+salt.toString('base64')+'$'+hash(ck)+':'+crypto.createHmac('sha256',salted).update('Server Key').digest('base64');
 // hash(ck) above is hex, so use the canonical base64 stored key instead.
 const validVerifier=verifier.replace(hash(ck),crypto.createHash('sha256').update(ck).digest('base64'));salted.fill(0);ck.fill(0);
 const flags={READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:'execute',READ_ACTIVATION_APPROVED_ACTION:'stage',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:plan.intent.operationId,READ_CREDENTIAL_INTENT_ID:plan.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'};
 const privateStep=E.privateEnvInput({plan:ep,publicFlags:flags,verifier:validVerifier,adminPassword:'SYNTHETIC_UNIT_ONLY'}),queries=steps.filter(x=>x.executor==='execute_query').map(x=>({procedure:x.procedure,input:x.input})),mutations=steps.filter(x=>x.executor!=='execute_query').map(x=>({procedure:x.procedure,input:x.input}));mutations.push({procedure:privateStep.procedure,input:{...privateStep.input,env:privateStep.input.env}});
 const binding={schema:'crm-manager-read-driver-scope-binding-v1',planSha256:plan.planSha256,mode:'execute',scopesSha256:hash(canonical({queries,mutations}))},vectors={queries:queries.map(v=>hash(canonical(v))),mutations:mutations.map(v=>hash(canonical(v)))};
 const evidence=synthetic.evidence,planFile=path.join(dir,'plan.json'),evidenceFile=path.join(dir,'evidence.json');fs.writeFileSync(planFile,pf,{mode:0o600});
 const config={enabled:true,mode:'execute',runtimeDirectory:BASE,planFile,planFileSha256:hash(pf),evidenceFile,evidenceSha256:'',binding,vectors};
 const saveEvidence=()=>{const b=JSON.stringify(evidence)+'\n';fs.writeFileSync(evidenceFile,b,{mode:0o600});config.evidenceSha256=hash(b);};saveEvidence();
 const q={...binding};Object.defineProperties(q,{allowedQueries:{value:queries,enumerable:false},allowedMutations:{value:mutations,enumerable:false}});
 const request={schema:'crm-manager-read-stage-admission-request-v1',planSha256:plan.planSha256,mode:'execute'},now=Date.parse(evidence.receiptValidFromUtc)+2000;
 return{dir,config,evidence,saveEvidence,q,request,now,plan,queries,mutations};
}
test('OFF/import has no provider dependency or filesystem requirement',()=>{const off=P.createProviders();for(const k of ['bindScopes','admission','observeStatus'])assert.throws(()=>off[k]({}),/READ_PINNED_PROVIDER_REFUSED/);assert.throws(()=>P.createProviders({enabled:false,mode:'execute'}),/READ_PINNED_PROVIDER_REFUSED/);});
test('preinstalled fixed binding gives closed V2 receipt, with unobserved volumes',t=>{const f=fixture(t),p=P.createProviders(f.config,{now:()=>f.now});assert.deepEqual(p.bindScopes(f.q),f.config.binding);assert.deepEqual(p.admission(f.request),f.evidence.receipt);assert.throws(()=>p.bindScopes(f.q),/REFUSED/);assert.equal(p.admission(f.request).newVolumesAbsent,false);});
test('no binding refuses admission and observer before any endpoint request',async t=>{const f=fixture(t);let called=0;const p=P.createProviders(f.config,{now:()=>f.now,transport:{request(){called++;throw Error('NO_REQUEST');}}});assert.throws(()=>p.admission(f.request),/REFUSED/);await assert.rejects(p.observeStatus({}),/REFUSED/);assert.equal(called,0);});
test('synthetic receipt refuses the non-fixture clock, and TTL ends exactly at 10s',t=>{const f=fixture(t),p=P.createProviders(f.config,{now:()=>Date.parse(f.evidence.receiptExpiresAtUtc)+1});p.bindScopes(f.q);assert.throws(()=>p.admission(f.request),/REFUSED/);for(const delta of [9999,10000]){const x=P.createProviders(f.config,{now:()=>Date.parse(f.evidence.receiptValidFromUtc)+delta});x.bindScopes(f.q);if(delta===9999)assert.deepEqual(x.admission(f.request),f.evidence.receipt);else assert.throws(()=>x.admission(f.request),/REFUSED/);}});
test('TTL cannot be reset from the newest collection time, future evidence refuses',t=>{const f=fixture(t);f.evidence.receiptExpiresAtUtc=new Date(Date.parse(f.evidence.receiptValidFromUtc)+12000).toISOString();f.saveEvidence();const p=P.createProviders(f.config,{now:()=>f.now});p.bindScopes(f.q);assert.throws(()=>p.admission(f.request),/REFUSED/);f.evidence.receiptExpiresAtUtc=new Date(Date.parse(f.evidence.receiptValidFromUtc)+10000).toISOString();f.saveEvidence();const future=P.createProviders(f.config,{now:()=>f.now-3000});future.bindScopes(f.q);assert.throws(()=>future.admission(f.request),/REFUSED/);});
test('wrong evidence pin, later replacement, loose mode, hardlink and symlink refuse',t=>{const f=fixture(t);const c={...f.config,evidenceSha256:'0'.repeat(64)},p=P.createProviders(c,{now:()=>f.now});p.bindScopes(f.q);assert.throws(()=>p.admission(f.request),/REFUSED/);const exact=P.createProviders(f.config,{now:()=>f.now});exact.bindScopes(f.q);fs.appendFileSync(f.config.evidenceFile,' ');assert.throws(()=>exact.admission(f.request),/REFUSED/);f.saveEvidence();fs.chmodSync(f.config.evidenceFile,0o644);assert.throws(()=>exact.admission(f.request),/REFUSED/);fs.chmodSync(f.config.evidenceFile,0o600);fs.linkSync(f.config.evidenceFile,path.join(f.dir,'hardlink'));assert.throws(()=>exact.admission(f.request),/REFUSED/);fs.unlinkSync(path.join(f.dir,'hardlink'));fs.renameSync(f.config.evidenceFile,path.join(f.dir,'real'));fs.symlinkSync(path.join(f.dir,'real'),f.config.evidenceFile);assert.throws(()=>exact.admission(f.request),/REFUSED/);});
test('wrong plan, wrong mode and a first-seen altered scope are refused',t=>{const f=fixture(t);assert.throws(()=>P.createProviders({...f.config,binding:{...f.config.binding,planSha256:'0'.repeat(64)}}),/REFUSED/);assert.throws(()=>P.createProviders({...f.config,mode:'reconcile'}),/REFUSED/);const p=P.createProviders(f.config,{now:()=>f.now}),wrong={...f.q};Object.defineProperties(wrong,{allowedQueries:{value:f.queries},allowedMutations:{value:[...f.mutations.slice(0,-1),{procedure:'updateComposeEnv',input:{...f.mutations.at(-1).input,env:'UNEXPECTED'}}]}});assert.throws(()=>p.bindScopes(wrong),/REFUSED/);assert.deepEqual(p.bindScopes(f.q),f.config.binding);assert.throws(()=>p.admission({...f.request,planSha256:'0'.repeat(64)}),/REFUSED/);});
test('unexpected envelope fields, capacity failure and fake volume absence do not grant',t=>{for(const change of [e=>{e.credentials={key:'SYNTHETIC_PRIVATE_FIELD'};},e=>{e.observed.capacity.memoryPassed=false;},e=>{e.receipt.newVolumesAbsent=true;},e=>{e.pins.sourceEntries[0].sha256='0'.repeat(64);},e=>{e.authorizeStage=true;}]){const f=fixture(t);change(f.evidence);f.saveEvidence();const p=P.createProviders(f.config,{now:()=>f.now});p.bindScopes(f.q);assert.throws(()=>p.admission(f.request),/REFUSED/);}});
test('this V2 provider refuses legacy V1 volume-absence receipt even if R would admit it',t=>{const f=fixture(t);f.evidence.receipt.schema='crm-manager-read-remote-admission-v1';f.evidence.receipt.newVolumesAbsent=true;delete f.evidence.receipt.volumeExistence;delete f.evidence.receipt.freshVolumeNamespaceVerified;f.saveEvidence();assert.equal(R.assertRemoteAdmission(f.evidence.receipt,f.plan),true);const p=P.createProviders(f.config,{now:()=>f.now});p.bindScopes(f.q);assert.throws(()=>p.admission(f.request),/REFUSED/);});
test('status-reader uses only exact plan GET/TLS and strips raw upstream data',async t=>{const f=fixture(t);let options=null,calls=0;const transport={request(opts,cb){calls++;options=opts;const req=new EventEmitter();req.destroy=()=>{};req.end=()=>{const res=new EventEmitter();res.statusCode=200;res.headers={'content-type':'application/json'};res.complete=true;res.destroy=()=>{};cb(res);queueMicrotask(()=>{res.emit('data',Buffer.from(JSON.stringify({schema:'crm-manager-read-supervisor-v1',action:'stage',state:'pending',childExitConfirmed:false,proofBarrierConfirmed:false,proof:null})));res.emit('end');});};return req;}};const p=P.createProviders(f.config,{now:()=>f.now,transport});p.bindScopes(f.q);const q={schema:'crm-manager-read-public-status-request-v1',planSha256:f.plan.planSha256,url:'https://'+f.plan.descriptor.domain.host+'/status',method:'GET',maxBytes:2048,timeoutMs:35000};assert.equal((await p.observeStatus(q)).state,'pending');assert.equal(options.hostname,f.plan.descriptor.domain.host);assert.equal(options.rejectUnauthorized,true);assert.equal(options.minVersion,'TLSv1.2');assert.equal(options.method,'GET');for(const change of [{url:'https://unrelated.invalid/status'},{method:'POST'},{planSha256:'0'.repeat(64)}])await assert.rejects(p.observeStatus({...q,...change}),/REFUSED/);assert.equal(calls,1);});
test('CLI rendered source has one export, contains public config only, and actual driver refuses bad plan pin',t=>{
 const f=fixture(t),bad={...f.config,planFileSha256:'0'.repeat(64)},source=P.buildCliSource(bad);
 const c={module:{exports:{}},require,process,TextDecoder};vm.runInNewContext(source,c);assert.deepEqual(Object.keys(c.module.exports),['createProviders']);assert.equal(source.includes('SYNTHETIC_UNIT_ONLY'),false);assert.equal(source.includes('PG_ADMIN_PASSWORD='),false);
 const entry=path.join(f.dir,'provider.cjs');fs.writeFileSync(entry,source,{mode:0o600});const config={enabled:true,mode:'execute',stageApproved:true,readonlyReconcileApproved:false,planFile:f.config.planFile,planFileSha256:f.config.planFileSha256,publicKeyFile:path.join(f.dir,'unused-public.pem'),privateKeyFile:path.join(f.dir,'unused-private.pem'),custodyDirectory:path.join(f.dir,'unused-capsule'),effectsDirectory:path.join(f.dir,'unused-effects'),requestDirectory:path.join(f.dir,'unused-requests')};const configFile=path.join(f.dir,'startup.json'),b=JSON.stringify(config)+'\n';fs.writeFileSync(configFile,b,{mode:0o600});
 const child=require('node:child_process').spawnSync(process.execPath,['--require',path.join(__dirname,'unit-guard.cjs'),BASE+'/driver.cjs','--opt-in',configFile,hash(b),entry,hash(source)],{env:{PATH:'/usr/bin:/bin'},encoding:'utf8',timeout:3000});assert.equal(child.status,1);assert.equal(child.stdout,'');assert.equal(child.stderr,'READ_STAGE_DRIVER_REFUSED\n');assert.equal(fs.existsSync(config.custodyDirectory),false);
});
