'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const H=require('./public-postcondition.cjs'),R=require('./remote-operator.cjs'),C=require('../crm-manager-read-activation-review/compose/build-compose.cjs'),A=require('../crm-manager-read-activation-review/runtime/activation.cjs'),RT=require('../crm-manager-read-activation-review/runtime/runtime.cjs');
const runtimeDir=path.join(__dirname,'../crm-manager-read-activation-review/runtime'),sources=Object.fromEntries(Object.keys(C.PINS).map(n=>[n,fs.readFileSync(path.join(runtimeDir,n),'utf8')]));
function plans(){const intent={schema:'crm-manager-read-runtime-intent-v1',operationId:crypto.randomUUID(),credentialIntentId:crypto.randomUUID(),action:'stage',fromPhase:'empty'},stage=R.buildStagePlan({suffix:'0123456789ab',sources,intent,domainId:crypto.randomUUID()});return[stage,R.buildReconcilePlan({suffix:'abcdef012345',stagePlan:stage,domainId:crypto.randomUUID()})];}
function fixture(p){
 const map=new Map(),counters={fsync:0,writes:0,journal:0},fdMap=new Map();let fd=20,handler,listen,stderr='';
 const stat=(kind,uid,gid,mode,size=0)=>({uid,gid,mode,size,nlink:1,dev:kind==='source'?10:11,ino:kind==='source'?12:13,isDirectory:()=>kind==='source'||kind==='dir',isFile:()=>kind==='file',isSymbolicLink:()=>false});
 map.set('/review',{s:stat('source',0,0,0o555),names:Object.keys(C.PINS)});map.set('/runtime-proof',{s:stat('dir',1000,1000,0o700),names:[]});
 for(const [n,b]of Object.entries(sources))map.set('/review/'+n,{s:stat('file',0,0,0o444,Buffer.byteLength(b)),bytes:b});
 map.set('/proc/self/status',{bytes:['NoNewPrivs:\t1',...['CapInh','CapPrm','CapEff','CapBnd','CapAmb'].map(k=>k+':\t0000000000000000')].join('\n')});map.set('/proc/self/mountinfo',{bytes:'1 0 0:1 / / ro - overlay overlay ro\n2 1 0:2 / /review ro - ext4 source ro\n3 1 0:3 / /runtime-proof rw - ext4 ledger rw'});
 if(p.mode==='reconcile'){const dir='/runtime-proof/'+p.intent.operationId;map.get('/runtime-proof').names=[p.intent.operationId];map.set(dir,{s:stat('dir',1000,1000,0o700),names:['00.json']});const bytes=JSON.stringify({schema:'crm-manager-read-runtime-ledger-v1',spec:A.SPEC,sourcePins:A.PINS,intent:p.intent})+'\n';map.set(dir+'/00.json',{s:stat('file',1000,1000,0o600,Buffer.byteLength(bytes)),bytes});}
 const fakeFs={constants:fs.constants,lstatSync:n=>{if(!map.has(n))throw Error('missing');return map.get(n).s;},realpathSync:n=>n,readdirSync:n=>[...map.get(n).names],readFileSync:(n,e)=>{const v=map.get(typeof n==='number'?fdMap.get(n):n)?.bytes;if(v===undefined)throw Error('missing');return e?String(v):Buffer.from(v);},openSync:(n,flags)=>{if(flags&fs.constants.O_WRONLY){counters.writes++;const e=Error();e.code='EROFS';throw e;}if(!map.has(n))throw Error('missing');fdMap.set(++fd,n);return fd;},closeSync:n=>fdMap.delete(n),fstatSync:n=>map.get(fdMap.get(n)).s,fsyncSync:()=>counters.fsync++,mkdirSync:()=>{throw Error('forbidden create');},writeFileSync:()=>{throw Error('forbidden write');}};
 const module={exports:{}},requireJournal=n=>{if(n==='node:fs')return fakeFs;if(n==='node:path')return path;if(n==='./activation.cjs')return A;if(n==='./runtime.cjs')return RT;throw Error('forbidden import');};new vm.Script(sources['journal.cjs']).runInNewContext({require:requireJournal,module,Buffer,Object,JSON,Number,Error});
 const fakeHttp={createServer:fn=>{handler=fn;return{on(){return this;},listen(port,host){listen={port,host};}}}},processFake={getuid:()=>1000,getgid:()=>1000,versions:{node:'22.0.0'},env:{NODE_PATH:'/app/node_modules'},stderr:{write:x=>stderr+=x},exitCode:undefined};
 const run=()=>new vm.Script(H.buildPublicPostcondition({remotePlan:p}).inline).runInNewContext({require:n=>{if(n==='node:fs')return fakeFs;if(n==='node:crypto')return crypto;if(n==='node:http')return fakeHttp;if(n==='/review/journal.cjs'){counters.journal++;return module.exports;}throw Error('forbidden import');},process:processFake,Buffer,Map,Object,JSON,String});
 function request(method='GET',url='/status',host=p.descriptor.domain.host){const out={};assert.ok(handler);handler({method,url,headers:{host}},{writeHead:(code,headers)=>Object.assign(out,{code,headers}),end:body=>out.body=body||''});return out;}
 return{map,counters,processFake,run,request,get listen(){return listen;},get stderr(){return stderr;}};
}
test('both branded plans preserve resources, aliases, mounts and original external volumes with public-only command; forged/cross-mode input refused',()=>{
 for(const p of plans()){const b=H.buildPublicPostcondition({remotePlan:p});assert.equal(Buffer.byteLength(b.inline)<16000,true);assert.equal(b.inline.includes('$'),false);new vm.Script(b.inline);assert.deepEqual(Object.keys(b.compose.services),['gateway']);for(const n of['source','ledger'])assert.deepEqual(b.compose.volumes[n],{external:true,name:p.descriptor.compose.volumes[n].name});const a=structuredClone(b.compose.services.gateway),e=structuredClone(p.descriptor.compose.services.gateway);for(const v of[a,e])for(const k of['entrypoint','command','env_file','depends_on','healthcheck'])delete v[k];assert.deepEqual(a,e);assert.equal(b.compose.services.gateway.env_file,undefined);assert.deepEqual(b.compose.services.gateway.entrypoint,['timeout','-s','KILL','600']);assert.deepEqual(b.command,b.compose.services.gateway.command);assert.equal(b.postconditionExpected.intent,p.intent);assert.throws(()=>H.buildPublicPostcondition({remotePlan:structuredClone(p)}));assert.throws(()=>H.buildPublicPostcondition({remotePlan:p,other:true}));}
});
test('stage observer proves real synthetic fs pins/modes/RO/empty ledger and refuses method, query and wrong Host without private output',()=>{
 const p=plans()[0],f=fixture(p);f.run();assert.deepEqual(f.listen,{port:8099,host:'0.0.0.0'});assert.equal(f.processFake.exitCode,undefined);const r=f.request();assert.equal(r.code,200);const proof=H.acceptPostcondition(r.body,p);assert.equal(proof.ledgerPhase,'empty');assert.equal(proof.postgresConnected,false);assert.equal(f.counters.journal,0);assert.equal(f.counters.fsync,0);assert.doesNotMatch(r.body,/\/review|\/runtime-proof|password|verifier|backend|SELECT|SYNTHETIC_SECRET/);for(const [m,u,h,code]of[['POST','/status',p.descriptor.domain.host,405],['GET','/status?secret=SYNTHETIC_SECRET',p.descriptor.domain.host,404],['GET','/status','arbitrary.invalid',404]]){const out=f.request(m,u,h);assert.equal(out.code,code);assert.equal(out.body,'');}
});
test('startup and every GET recheck source hash/owner/modes/mount and stage empty ledger; runtime environment refuses before listen',()=>{
 const p=plans()[0];const changes=[f=>f.map.get('/review/runtime.cjs').bytes+='corrupt',f=>f.map.get('/review').names.push('extra'),f=>f.map.get('/review/runtime.cjs').s.uid=1000,f=>f.map.get('/review/runtime.cjs').s.gid=1000,f=>f.map.get('/review/runtime.cjs').s.mode=0o444|0o4000,f=>f.map.get('/review/runtime.cjs').s.isSymbolicLink=()=>true,f=>f.map.get('/runtime-proof').names.push('unexpected'),f=>f.map.get('/runtime-proof').s.gid=0,f=>f.map.get('/proc/self/mountinfo').bytes=f.map.get('/proc/self/mountinfo').bytes.replace('/review ro','/review rw'),f=>f.processFake.env.PG_ADMIN_PASSWORD='SYNTHETIC_SECRET',f=>f.processFake.env.READ_ACTIVATION_RUNTIME_OPT_IN='1',f=>f.processFake.getuid=()=>0];
 for(const change of changes){const f=fixture(p);change(f);f.run();assert.equal(f.listen,undefined);assert.equal(f.processFake.exitCode,1);assert.equal(f.stderr,'READ_PUBLIC_POSTCONDITION_REFUSED\n');const after=fixture(p);after.run();change(after);const r=after.request();assert.equal(r.code,503);assert.equal(r.body,'');}
});
test('reconcile reads actual frozen Journal durably with original intent only; no create/append/PG/private events response',()=>{
 const p=plans()[1],f=fixture(p);f.run();const r=f.request();assert.equal(r.code,200);const proof=H.acceptPostcondition(r.body,p);assert.equal(proof.ledgerPhase,'original_intent_held');assert.equal(proof.ledgerEmpty,false);assert.equal(proof.originalIntentHeld,true);assert.ok(f.counters.journal>=2);assert.ok(f.counters.fsync>=6);assert.doesNotMatch(r.body,/backend|pid|events|credentialIntentId|operationId|SELECT|SYNTHETIC_SECRET/);
 const dir='/runtime-proof/'+p.intent.operationId;for(const change of[f=>{const x=JSON.parse(f.map.get(dir+'/00.json').bytes);x.intent.credentialIntentId=crypto.randomUUID();f.map.get(dir+'/00.json').bytes=JSON.stringify(x);},f=>f.map.get('/runtime-proof').names.push(crypto.randomUUID()),f=>f.map.get(dir+'/00.json').s.gid=0,f=>f.map.get(dir+'/00.json').s.nlink=2,f=>f.map.get(dir).s.mode|=0o2000,f=>f.map.get(dir+'/00.json').s.isSymbolicLink=()=>true]){const bad=fixture(p);change(bad);bad.run();assert.equal(bad.listen,undefined);assert.equal(bad.processFake.exitCode,1);}
});
test('public response admission closes unknown fields, phase/plan/capability drift, raw null/oversized/malformed and forged plan',()=>{
 for(const p of plans()){const f=fixture(p);f.run();const raw=f.request().body,base=JSON.parse(raw);assert.ok(Object.isFrozen(H.acceptPostcondition(raw,p)));for(const d of[{...base,unexpected:'SYNTHETIC_SECRET'},{...base,planSha256:'a'.repeat(64)},{...base,ledgerPhase:'active'},{...base,postgresConnected:true},{...base,privateEnvironmentAbsent:false},{...base,mode:p.mode==='execute'?'reconcile':'execute'}])assert.throws(()=>H.acceptPostcondition(JSON.stringify(d),p),/READ_PUBLIC_POSTCONDITION_REFUSED/);for(const raw of[null,'null','{','x'.repeat(4097)])assert.throws(()=>H.acceptPostcondition(raw,p),/READ_PUBLIC_POSTCONDITION_REFUSED/);assert.throws(()=>H.acceptPostcondition(raw,structuredClone(p)));}
});
