'use strict';
// Synthetic RSA, own ciphertext/fence directories, actual public wrappers and
// fake MCP shaped exactly like observed envelopes. No real tools/network/PG.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),util=require('node:util');
const {PassThrough}=require('node:stream'),S=require('./stage-runner.cjs'),B=require('./stdio-bridge.cjs'),{createFunctionsRelay}=require('./functions-relay.js');
const R=require('./remote-operator.cjs'),E=require('./easypanel-plan.cjs'),M=require('./easypanel-adapter.cjs'),F=require('./effect-fence.cjs'),O=require('./operator.cjs'),C=require('../crm-manager-read-activation-review/compose/build-compose.cjs'),P=require('./public-postcondition.cjs');
const sources=Object.fromEntries(Object.keys(C.PINS).map(n=>[n,fs.readFileSync(path.join(__dirname,'../crm-manager-read-activation-review/runtime',n),'utf8')]));
const pair=crypto.generateKeyPairSync('rsa',{modulusLength:4096,publicExponent:65537}),wrong=crypto.generateKeyPairSync('rsa',{modulusLength:4096,publicExponent:65537});
const password='a7'.repeat(32),admin='SYNTHETIC_ADMIN_ONLY',salt=Buffer.from('0123456789abcdef'),salted=crypto.pbkdf2Sync(password,salt,4096,32,'sha256'),client=crypto.createHmac('sha256',salted).update('Client Key').digest();
const verifier='SCRAM-SHA-256$4096:'+salt.toString('base64')+'$'+crypto.createHash('sha256').update(client).digest('base64')+':'+crypto.createHmac('sha256',salted).update('Server Key').digest('base64');salted.fill(0);client.fill(0);
const proof={schema:'crm-manager-read-runtime-result-v1',action:'stage',state:'confirmed',phase:'staged',coreVerified:true,credentialBound:true,commitAck:true};
const verified=()=>({schema:'crm-manager-read-supervisor-v1',action:'stage',state:'verified',childExitConfirmed:true,proofBarrierConfirmed:true,proof:{...proof}});
const pending=()=>({schema:'crm-manager-read-supervisor-v1',action:'stage',state:'pending',childExitConfirmed:false,proofBarrierConfirmed:false,proof:null});
const closed=e=>e instanceof Error&&/^(READ_EASYPANEL_ADAPTER_REFUSED|READ_REMOTE_OPERATOR_REFUSED|READ_EFFECT_FENCE_REFUSED)$/.test(e.message)&&e.cause===undefined;
function fixture(t){const parent=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'read-mcp-stage-synthetic-')));fs.chmodSync(parent,0o700);t.after(()=>fs.rmSync(parent,{force:true,recursive:true}));const directory=path.join(parent,'capsule'),effects=path.join(parent,'effects');fs.mkdirSync(effects,{mode:0o700});const intent={schema:'crm-manager-read-runtime-intent-v1',operationId:crypto.randomUUID(),credentialIntentId:crypto.randomUUID(),action:'stage',fromPhase:'empty'},plan=R.buildStagePlan({suffix:crypto.randomBytes(6).toString('hex'),sources,intent,domainId:crypto.randomUUID()});return{parent,directory,effects,intent,plan,input:{plan,directory,password,verifier,publicKey:pair.publicKey,privateKey:pair.privateKey}};}
function transport(f,options={}){
 const states=new Map(),calls=[],domainRows=[{id:crypto.randomUUID(),host:'existing.invalid',https:true,path:'/',certificateResolver:'',wildcard:false,middlewares:[],destinationType:'service',serviceDestination:{projectName:'existing',serviceName:'existing',composeService:'gateway',protocol:'http',port:8080,path:'/'}}],before=JSON.stringify(domainRows);let adminCalls=0,stageMutations=0,readonly=0;const admittedPlans=new Map(),publicObservations=[];
 const key=i=>i.projectName+'_'+i.serviceName;
 async function execute(args){
  const step=args.procedure,i=args.input,executor=M.PROCEDURES[step],request={executor,private:typeof i.env==='string'&&i.env!==''};assert.ok(executor);assert.equal(fs.existsSync(path.join(f.directory,O.FILE)),true);
  const bound=O.openExisting({directory:f.directory,intent:f.plan.intent,privateKey:pair.privateKey});assert.equal(bound.verifier,verifier);calls.push({procedure:step,executor:request.executor,private:request.private===true,target:i.serviceName||null,sourcePhase:states.has(key(i))?JSON.parse(states.get(key(i)).source.content).services.gateway?.command?.at(-1)==='/review/supervisor.cjs'?'private':'public':null,environmentEmpty:states.has(key(i))?states.get(key(i)).env==='':null});
  let result;switch(step){
   case'createComposeService':if(states.has(key(i)))throw Error('SYNTHETIC_COLLISION');states.set(key(i),{name:i.serviceName,projectName:i.projectName,type:'compose',enabled:true,createDotEnv:true,env:i.env,source:{...i.source},running:0});result={token:admin,env:verifier};break;
   case'inspectComposeService':{const s=states.get(key(i));if(!s)throw Error('SYNTHETIC_ABSENT');const out={...s,source:{...s.source}};out.token=admin;result=out;break;}
   case'getDockerContainers':{const s=states.get(i.service);result=s?.running?[{Id:'a'.repeat(64),State:'running',Labels:{'com.shrigma.read-runtime-plan':s.name.slice(-12)},Names:['synthetic-only'],Image:C.IMAGE}]:[];break;}
   case'listDomains':result=domainRows.filter(r=>i.projectName===undefined||r.serviceDestination.projectName===i.projectName&&r.serviceDestination.serviceName===i.serviceName);break;
   case'updateComposeSourceInline':states.get(key(i)).source={type:'inline',content:i.content};break;
   case'createDomain':domainRows.push(JSON.parse(JSON.stringify(i)));break;
   case'deleteDomain':{const at=domainRows.findIndex(r=>r.id===i.id);assert.ok(at>=1);domainRows.splice(at,1);break;}
   case'updateComposeEnv':states.get(key(i)).env=i.env;break;
   case'deployComposeService':{const s=states.get(key(i)),spec=JSON.parse(s.source.content);s.enabled=true;s.running=1;if(spec.services.gateway?.command?.at(-1)==='/review/supervisor.cjs'){const mode=s.env.match(/^READ_ACTIVATION_MODE=(.+)$/m)[1];if(mode==='execute')stageMutations++;else readonly++;}break;}
   case'startComposeService':states.get(key(i)).enabled=true;states.get(key(i)).running=1;break;
   case'stopComposeService':states.get(key(i)).enabled=false;states.get(key(i)).running=0;break;
   default:throw Error('UNEXPECTED_PROC');
  }
  if(options.lost===step&&calls.filter(c=>c.procedure===step).length===(options.lostOccurrence||1))throw Error('RAW_SECRET '+admin+' '+verifier);
  if(options.modify)result=options.modify({step,input:i,result,states,domainRows});
  return options.textFallback?{content:[{type:'text',text:JSON.stringify({procedure:step,result:result===undefined?null:result})}]}:{structuredContent:{procedure:step,result:result===undefined?null:result}};
 }
 const fence=F.openEffectFence({directory:f.effects});
 function publicResult(p){return JSON.stringify({schema:'crm-manager-read-public-postcondition-v1',mode:p.mode,planSha256:p.planSha256,sourcePinsSha256:crypto.createHash('sha256').update(JSON.stringify(C.PINS)).digest('hex'),nineSourcesPinned:true,sourceReadOnly:true,sourceRootOwned:true,sourceModesVerified:true,ledgerPhase:p.mode==='execute'?'empty':'original_intent_held',ledgerEmpty:p.mode==='execute',originalIntentHeld:p.mode==='reconcile',ledgerPrivateOwned:true,uid1000:true,noNewPrivileges:true,capabilitiesEmpty:true,rootReadOnly:true,privateEnvironmentAbsent:true,postgresConnected:false,runtimeExecuted:false});}
 const dependencies={execute,fence:fence.fence,admitCapacity:async p=>{admittedPlans.set(p.planSha256,p);return{schema:'crm-manager-read-remote-admission-v1',planSha256:p.planSha256,capacityVerified:true,targetAbsent:true,domainAbsent:true,imagePinned:true,nineSourcesPinned:true,newVolumesAbsent:p.mode==='execute',existingSourceVerified:p.mode==='reconcile',existingLedgerVerified:p.mode==='reconcile',priorQuiescent:p.mode==='reconcile',...(options.admission||{})};},getAdminPassword:async()=>{adminCalls++;return admin;},observeStatus:async q=>{
  assert.equal(q.method,'GET');assert.ok(q.url.endsWith('/status'));
  if(q.schema==='crm-manager-read-public-postcondition-request-v1'){assert.equal(q.maxBytes,4096);const p=admittedPlans.get(q.planSha256);assert.ok(p);const s=states.get(p.descriptor.projectName+'_'+p.descriptor.serviceName),spec=JSON.parse(s.source.content);assert.equal(s.env,'');assert.equal(s.enabled,true);assert.equal(s.running,1);assert.equal(spec.services.gateway.command.at(-1),P.buildPublicPostcondition({remotePlan:p}).inline);publicObservations.push(q.planSha256);return options.publicObserver?options.publicObserver(q,publicResult(p),publicObservations.length):publicResult(p);}
  assert.equal(q.schema,'crm-manager-read-public-status-request-v1');assert.equal(q.maxBytes,2048);return options.observer?options.observer(q):verified();},custody:{directory:f.directory,privateKey:pair.privateKey}};
 return{dependencies,states,calls,domainRows,fence,publicObservations,get adminCalls(){return adminCalls},get stageMutations(){return stageMutations},get readonly(){return readonly},assertExisting(){assert.equal(JSON.stringify(domainRows.filter(r=>r.host==='existing.invalid')),before);}};
}function compose(f,n,{plan=f.plan,flags={stageApproved:true,readonlyReconcileApproved:true},timers,admission,secret,observer}={}){
 const requestDir=path.join(f.parent,'requests-'+crypto.randomBytes(4).toString('hex'));fs.mkdirSync(requestDir,{mode:0o700});const input=new PassThrough(),output=new PassThrough(),packets=[],privateRetained=[],jobs=[];let chain=Promise.resolve(),getAdminRequests=0,admissionRequests=0;
 const ep=E.buildEasypanelInputs({remotePlan:plan}),steps=Object.values(ep).filter(x=>x&&x.procedure),queries=steps.filter(x=>x.executor==='execute_query').map(x=>({procedure:x.procedure,input:x.input})),writes=steps.filter(x=>x.executor!=='execute_query').map(x=>({procedure:x.procedure,input:x.input}));
 if(plan.parentStage){const prior=E.buildEasypanelInputs({remotePlan:plan.parentStage});for(const k of['inspect','inspectRunning','inspectDomains'])queries.push({procedure:prior[k].procedure,input:prior[k].input});for(const k of['stop','clearEnvironment','deleteTestDomain'])writes.push({procedure:prior[k].procedure,input:prior[k].input});}
 const publicFlags={READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:plan.mode,READ_ACTIVATION_APPROVED_ACTION:plan.mode==='execute'?'stage':'readonly-reconcile',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:plan.intent.operationId,READ_CREDENTIAL_INTENT_ID:plan.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'},privateStep=E.privateEnvInput({plan:ep,publicFlags,verifier,adminPassword:admin});writes.push({procedure:privateStep.procedure,input:{...privateStep.input,env:privateStep.input.env}});
 const relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:queries,allowedMutations:writes,timeoutMs:40000,readPublic:d=>B.readPublicFile(d),retainPrivate:(_s,v)=>privateRetained.push(v),tools:Object.fromEntries(['execute_query','execute_mutation','execute_destructive'].map(x=>['mcp__easypanel__'+x,args=>{assert.equal(M.PROCEDURES[args.procedure],x);return n.dependencies.execute(args);} ])),writeToNode:async line=>input.write(line)});
 output.on('data',b=>{packets.push(JSON.parse(b.toString()));chain=chain.then(()=>relay.step(b.toString())).then(r=>{if(r.state!=='responded')input.end();});jobs.push(chain);});
 const boundPlans=new Map([[plan.planSha256,plan]]);
 const runner=S.createStageRunner({enabled:true,...flags},{custody:{directory:f.directory,privateKey:pair.privateKey},effectsDirectory:f.effects,requestDirectory:requestDir,transport:{input,output},getAdminPassword:async q=>{getAdminRequests++;assert.deepEqual(q,{schema:'crm-manager-read-stage-admin-request-v1',planSha256:plan.planSha256,mode:plan.mode});return secret?secret(q):admin;},admission:async q=>{admissionRequests++;assert.deepEqual(q,{schema:'crm-manager-read-stage-admission-request-v1',planSha256:plan.planSha256,mode:plan.mode});assert.equal(fs.existsSync(path.join(f.directory,O.FILE)),true);return admission?admission(q):n.dependencies.admitCapacity(boundPlans.get(q.planSha256));},observeStatus:observer||n.dependencies.observeStatus,...(timers?{timers}:{})});
 return{runner,packets,requestDir,privateRetained,async settled(){await chain;},get adminRequests(){return getAdminRequests;},get admissionRequests(){return admissionRequests;}};
}
const inputFor=f=>({plan:f.plan,password,verifier,publicKey:pair.publicKey});
const refused=e=>e?.message==='READ_STAGE_RUNNER_REFUSED'&&e.cause===undefined;
function scanPublic(f){for(const dir of[f.effects,...fs.readdirSync(f.parent).filter(x=>x.startsWith('requests-')).map(x=>path.join(f.parent,x))])for(const file of fs.readdirSync(dir)){const text=fs.readFileSync(path.join(dir,file),'utf8');assert.equal(text.includes(password),false);assert.equal(text.includes(admin),false);assert.equal(text.includes(verifier),false);}}

test('import/OFF does not load composed modules or inspect dependencies, streams, environment or timers',async()=>{const Module=require('node:module'),load=Module._load;delete require.cache[require.resolve('./stage-runner.cjs')];Module._load=function(id,...rest){if(['./remote-operator.cjs','./easypanel-adapter.cjs','./effect-fence.cjs','./stdio-bridge.cjs'].includes(id))throw Error('SHOULD_NOT_IMPORT');return load.call(this,id,...rest);};try{const api=require('./stage-runner.cjs'),deps=new Proxy({}, {get(){throw Error('SHOULD_NOT_TOUCH');}}),runner=api.createStageRunner(undefined,deps);assert.equal((await runner.stage({})).state,'disabled');assert.equal((await runner.reconcile({})).state,'disabled');await runner.close();assert.equal(api.CALLBACK_TIMEOUT_MS,40000);assert.equal(api.NODE_TIMEOUT_MS,45000);assert.equal(api.GET_TIMEOUT_MS,35000);}finally{Module._load=load;}});
test('separate approvals and unbranded plan refuse before capsule or any stream/native dispatch',async t=>{for(const mode of['approval','unbranded']){const f=fixture(t),n=transport(f),h=compose(f,n,{flags:{stageApproved:mode!=='approval',readonlyReconcileApproved:false}});await assert.rejects(h.runner.stage(mode==='unbranded'?{...inputFor(f),plan:JSON.parse(JSON.stringify(f.plan))}:inputFor(f)),refused);assert.equal(fs.existsSync(f.directory),false);assert.equal(h.packets.length,0);assert.equal(n.calls.length,0);await h.runner.close();}});
test('composition stage seals and reopens before every actual bridge/in-memory/mock native request; exact scopes, two public barriers, single private deploy and closed cleanup',async t=>{const f=fixture(t),n=transport(f),h=compose(f,n),out=await h.runner.stage(inputFor(f));await h.settled();assert.equal(out.state,'verified');assert.equal(out.cleanupVerified,true);assert.equal(n.stageMutations,1);assert.equal(n.publicObservations.length,2);assert.equal(h.adminRequests,1);assert.equal(h.admissionRequests,1);assert.deepEqual(n.calls.filter(c=>c.procedure==='startComposeService').map(c=>[c.sourcePhase,c.environmentEmpty]),[['public',true]]);assert.equal(h.packets.every(p=>p.kind==='mcp'),true);assert.equal(h.packets.filter(p=>p.visibility==='private').length,1);assert.equal(h.packets.filter(p=>p.visibility==='private')[0].args.input.env,privateStepEnv(f.plan));assert.ok(h.privateRetained.some(r=>r.kind==='mcp-response'&&JSON.stringify(r.value).includes(admin)));scanPublic(f);n.assertExisting();assert.equal(JSON.stringify(out).includes(admin),false);await assert.rejects(h.runner.stage(inputFor(f)),refused);assert.equal(n.stageMutations,1);await h.runner.close();});
function privateStepEnv(plan){const ep=E.buildEasypanelInputs({remotePlan:plan});return E.privateEnvInput({plan:ep,publicFlags:{READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:plan.mode,READ_ACTIVATION_APPROVED_ACTION:plan.mode==='execute'?'stage':'readonly-reconcile',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:plan.intent.operationId,READ_CREDENTIAL_INTENT_ID:plan.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'},verifier,adminPassword:admin}).input.env;}
test('explicit synthetic V2 admission composes with the derived128-bit namespace without asserting volume absence or changing cleanup',async t=>{const f=fixture(t),n=transport(f),h=compose(f,n,{admission:async()=>({...await n.dependencies.admitCapacity(f.plan),schema:'crm-manager-read-remote-admission-v2',newVolumesAbsent:false,volumeExistence:'unobserved',freshVolumeNamespaceVerified:true})}),out=await h.runner.stage(inputFor(f));assert.equal(out.state,'verified');assert.equal(out.cleanupVerified,true);assert.equal(n.stageMutations,1);assert.equal(n.publicObservations.length,2);assert.match(f.plan.descriptor.compose.volumes.ledger.name,/[a-f0-9]{32}$/);assert.equal(h.packets.some(p=>p.kind!=='mcp'),false);scanPublic(f);n.assertExisting();await h.runner.close();});
test('admission provider refusal/missing evidence flag/wrong SHA never defaults absent or creates; capsule stays held',async t=>{for(const kind of['refused','volume','sha']){const f=fixture(t),n=transport(f),h=compose(f,n,{admission:async()=>{if(kind==='refused')throw Error(admin);const r=await n.dependencies.admitCapacity(f.plan);return{...r,...(kind==='volume'?{newVolumesAbsent:false}:{planSha256:'f'.repeat(64)})};}}),out=await h.runner.stage(inputFor(f));assert.equal(out.state,'not_dispatched');assert.equal(n.calls.every(c=>c.executor==='execute_query'),true);assert.equal(n.calls.filter(c=>c.procedure==='createComposeService').length,0);assert.equal(h.adminRequests,0);assert.equal(fs.existsSync(path.join(f.directory,O.FILE)),true);scanPublic(f);await h.runner.close();}});
test('wrong custody key refuses before first transport request or secret callback',async t=>{const f=fixture(t),n=transport(f),h=compose(f,n);const bad=S.createStageRunner({enabled:true,stageApproved:true,readonlyReconcileApproved:false},{custody:{directory:f.directory,privateKey:wrong.privateKey},effectsDirectory:f.effects,requestDirectory:h.requestDir,transport:{input:new PassThrough(),output:new PassThrough()},getAdminPassword:()=>{throw Error(admin);},admission:()=>{throw Error(admin);},observeStatus:()=>{throw Error(admin);}});await assert.rejects(bad.stage(inputFor(f)),refused);assert.equal(n.calls.length,0);assert.equal(h.packets.length,0);await bad.close();await h.runner.close();});
test('pending supervisor or lost private deploy ACK remains unknown without repeating POST/effect or generating new credential',async t=>{for(const mode of['pending','lost']){const f=fixture(t),n=transport(f,mode==='pending'?{observer:()=>pending()}:{lost:'deployComposeService',lostOccurrence:2}),h=compose(f,n),out=await h.runner.stage(inputFor(f));assert.equal(out.state,'outcome_unknown');assert.equal(out.proof,null);assert.equal(n.stageMutations,1);assert.equal(h.adminRequests,1);assert.equal(n.calls.filter(c=>c.procedure==='deployComposeService').length,2);await assert.rejects(h.runner.stage(inputFor(f)),refused);assert.equal(n.stageMutations,1);scanPublic(f);await h.runner.close();}});
test('reconcile restart keeps ciphertext/IDs/volumes, explicitly admits evidence after prior cleanup, and performs no second execute',async t=>{const f=fixture(t),n=transport(f,{observer:()=>pending()}),first=compose(f,n);await first.runner.stage(inputFor(f));await first.runner.close();const cipher=fs.readFileSync(path.join(f.directory,O.FILE)),plan=R.buildReconcilePlan({suffix:crypto.randomBytes(6).toString('hex'),stagePlan:f.plan,domainId:crypto.randomUUID()});let checked=false;const h=compose(f,n,{plan,flags:{stageApproved:false,readonlyReconcileApproved:true},admission:async()=>{const state=n.states.get(f.plan.descriptor.projectName+'_'+f.plan.descriptor.serviceName);assert.equal(state.enabled,false);assert.equal(state.env,'');assert.equal(state.running,0);checked=true;return n.dependencies.admitCapacity(plan);},observer:q=>q.schema==='crm-manager-read-public-postcondition-request-v1'?JSON.stringify({schema:'crm-manager-read-public-postcondition-v1',mode:plan.mode,planSha256:plan.planSha256,sourcePinsSha256:crypto.createHash('sha256').update(JSON.stringify(C.PINS)).digest('hex'),nineSourcesPinned:true,sourceReadOnly:true,sourceRootOwned:true,sourceModesVerified:true,ledgerPhase:'original_intent_held',ledgerEmpty:false,originalIntentHeld:true,ledgerPrivateOwned:true,uid1000:true,noNewPrivileges:true,capabilitiesEmpty:true,rootReadOnly:true,privateEnvironmentAbsent:true,postgresConnected:false,runtimeExecuted:false}):verified()});const out=await h.runner.reconcile({plan});assert.equal(out.state,'verified');assert.equal(checked,true);assert.ok(cipher.equals(fs.readFileSync(path.join(f.directory,O.FILE))));assert.equal(plan.intent.operationId,f.plan.intent.operationId);assert.equal(plan.intent.credentialIntentId,f.plan.intent.credentialIntentId);assert.equal(plan.descriptor.compose.volumes.ledger.name,f.plan.descriptor.compose.volumes.ledger.name);assert.equal(n.stageMutations,1);assert.equal(n.readonly,1);scanPublic(f);n.assertExisting();await h.runner.close();});
test('callbacks have bounded40s deadline; concurrent call refuses, close cancels pending readonly callback and never starts new native effect',async t=>{const f=fixture(t),n=transport(f);let began,release;const start=new Promise(r=>began=r),gate=new Promise(r=>release=r),seen=[];const h=compose(f,n,{timers:{setTimeout:(fn,ms)=>{seen.push(ms);return{fn};},clearTimeout:()=>{}},admission:async()=>{began();await gate;return n.dependencies.admitCapacity(f.plan);}});const running=h.runner.stage(inputFor(f));await start;await assert.rejects(h.runner.stage(inputFor(f)),refused);await h.runner.close();assert.equal((await running).state,'not_dispatched');assert.ok(seen.every(ms=>ms===40000));assert.equal(n.calls.filter(c=>c.executor!=='execute_query').length,0);release();await new Promise(r=>setImmediate(r));assert.equal(n.calls.filter(c=>c.executor!=='execute_query').length,0);});

test('40s callback deadline fires into held not_dispatched without waiting for provider and ignores its late response',async t=>{const f=fixture(t),n=transport(f);let begun,release;const start=new Promise(r=>begun=r),gate=new Promise(r=>release=r),deadlines=[];const h=compose(f,n,{timers:{setTimeout:(fn,ms)=>{const timer={fn,ms};deadlines.push(timer);return timer;},clearTimeout:()=>{}},admission:async()=>{begun();await gate;return n.dependencies.admitCapacity(f.plan);}});const running=h.runner.stage(inputFor(f));await start;assert.equal(deadlines.at(-1).ms,40000);deadlines.at(-1).fn();assert.equal((await running).state,'not_dispatched');release();await new Promise(r=>setImmediate(r));assert.equal(n.calls.some(c=>c.procedure==='createComposeService'),false);await assert.rejects(h.runner.stage(inputFor(f)),refused);await h.runner.close();});
test('non-string or unsafe admin callback result fails after public barriers before any private request without echo',async t=>{for(const result of[{credentials:{key:admin}},admin+'\nUNSAFE']){const f=fixture(t),n=transport(f),h=compose(f,n,{secret:()=>result}),out=await h.runner.stage(inputFor(f));assert.equal(out.state,'outcome_unknown');assert.equal(n.publicObservations.length,2);assert.equal(n.stageMutations,0);assert.equal(h.packets.some(q=>q.visibility==='private'),false);assert.equal(JSON.stringify(out).includes(admin),false);scanPublic(f);await h.runner.close();}});
