'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{PassThrough}=require('node:stream');
const B=require('./stdio-bridge.cjs'),{createFunctionsRelay}=require('./functions-relay.js');
const SECRET='SYNTHETIC_ONLY_NOT_A_CREDENTIAL';
const query={procedure:'listDomains',input:{projectName:'synthetic-project',serviceName:'synthetic-service'}};
const materialize=q=>({procedure:q.procedure,input:q.input});
function fixture(t,timeoutMs=100){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'read-stdio-synthetic-')));fs.chmodSync(dir,0o700);t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const input=new PassThrough(),output=new PassThrough(),packets=[];output.on('data',b=>packets.push(b.toString()));const bridge=B.createStdioBridge({enabled:true,directory:dir,materialize,input,output,timeoutMs});t.after(()=>bridge.close());return{dir,input,output,packets,bridge};}
const response=(seq,result)=>JSON.stringify({schema:B.RESPONSE,seq,ok:true,result})+'\n';
const refused=e=>e?.code==='READ_STDIO_OUTCOME_UNKNOWN'&&e.message==='READ_STDIO_OUTCOME_UNKNOWN'&&e.cause===undefined;
const next=()=>new Promise(r=>setImmediate(r));
test('OFF neither touches streams/files nor materializes a request',async()=>{let calls=0;const b=B.createStdioBridge({directory:'/nonexistent',materialize:()=>calls++,input:{on:()=>calls++},output:{write:()=>calls++}});await assert.rejects(b.execute({}),refused);assert.equal(calls,0);});
test('large PUBLIC request goes through 600 file/hash readback and only metadata reaches stdout',async t=>{const f=fixture(t),input={projectName:'synthetic-project',serviceName:'synthetic-service',createDotEnv:true,env:'',domains:[],source:{type:'inline',content:'PUBLIC_SOURCE_'.repeat(10000)}},p=f.bridge.execute({executor:'execute_mutation',procedure:'createComposeService',input});const q=JSON.parse(f.packets[0]);assert.equal(q.visibility,'public');assert.equal(q.args,undefined);assert.ok(q.file.bytes>100000);assert.equal(fs.statSync(q.file.path).mode&0o777,0o600);const read=B.readPublicFile(q.file);assert.equal(read.args.input.source.content.length,input.source.content.length);assert.ok(!f.packets[0].includes('PUBLIC_SOURCE_'));f.input.write(response(q.seq,{structuredContent:{procedure:'createComposeService',result:null}}));await p;});
test('PRIVATE classification derives from env payload despite caller flag false; nothing is written to a request file',async t=>{const f=fixture(t),p=f.bridge.execute({private:false,executor:'execute_destructive',procedure:'updateComposeEnv',input:{projectName:'synthetic-project',serviceName:'synthetic-service',createDotEnv:true,env:'PG_ADMIN_PASSWORD='+SECRET}});const q=JSON.parse(f.packets[0]);assert.equal(q.visibility,'private');assert.equal(q.file,undefined);assert.equal(fs.readdirSync(f.dir).length,0);assert.ok(q.args.input.env.includes(SECRET));f.input.write(response(q.seq,{structuredContent:{procedure:'updateComposeEnv',result:null}}));await p;});
test('hash/mode/symlink drift refuses public reader without returning a body',async t=>{for(const mode of['hash','mode','symlink']){const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query}),q=JSON.parse(f.packets[0]);if(mode==='hash')fs.appendFileSync(q.file.path,'x');if(mode==='mode')fs.chmodSync(q.file.path,0o640);if(mode==='symlink'){fs.renameSync(q.file.path,q.file.path+'.old');fs.symlinkSync(q.file.path+'.old',q.file.path);}assert.throws(()=>B.readPublicFile(q.file),refused);f.bridge.abort();await assert.rejects(p,refused);}});
test('timeout, EOF, abort and wrong correlation are terminal unknown, never a second request',async t=>{for(const mode of['timeout','eof','abort','seq']){const f=fixture(t,10),p=f.bridge.execute({executor:'execute_query',...query});const reject=assert.rejects(p,refused);if(mode==='eof')f.input.end();if(mode==='abort')f.bridge.abort();if(mode==='seq')f.input.write(response(2,{}));await reject;await assert.rejects(f.bridge.execute({executor:'execute_query',...query}),refused);assert.equal(f.packets.length,1);}});
test('malformed UTF8 and input above one-line budget fail closed',async t=>{for(const bytes of[Buffer.from([0xff,10]),Buffer.alloc(B.MAX_INPUT+1,120)]){const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query}),r=assert.rejects(p,refused);f.input.write(bytes);await r;assert.equal(f.packets.length,1);}});
test('relay OFF/nativeApproved false/unknown procedure/wrong scope make zero native or private calls',async()=>{for(const mode of['off','unapproved','unknown','scope']){let calls=0;const args={...query,procedure:mode==='unknown'?'deleteEverything':'listDomains'},raw=JSON.stringify({schema:B.REQUEST,seq:1,kind:'mcp',visibility:'private',executor:'execute_query',args});const relay=createFunctionsRelay({enabled:mode!=='off',nativeApproved:mode!=='unapproved',tools:{mcp__easypanel__execute_query:async()=>{calls++;}},allowedQueries:mode==='scope'?[]:[query],retainPrivate:()=>{calls++;},writeToNode:async()=>{calls++;}});const r=await relay.step(raw);assert.equal(r.state,mode==='off'?'disabled':'unknown');assert.equal(calls,0);}});
test('relay exact readonly scope and PUBLIC reader move sensitive MCP reply only to stdin/internal keeper',async t=>{const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query});let calls=0,retained=false;const relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:[query],readPublic:d=>B.readPublicFile(d),retainPrivate:(_seq,v)=>{retained=JSON.stringify(v).includes(SECRET);},tools:{mcp__easypanel__execute_query:async args=>{calls++;assert.deepEqual(args,query);return{structuredContent:{procedure:'listDomains',result:{env:SECRET}}};}},writeToNode:async line=>f.input.write(line)});const result=await relay.step(f.packets[0]);const reply=await p;assert.equal(result.state,'responded');assert.equal(calls,1);assert.ok(retained);assert.ok(reply.structuredContent.result.env===SECRET);assert.ok(!JSON.stringify(result).includes(SECRET));assert.ok(!f.packets.join('').includes(SECRET));});
test('relay rejects mutation outside exact allowed list, and abort during native await never delivers late ACK',async t=>{const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query});let release,calls=0,writes=0;const gate=new Promise(r=>release=r);const relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:[query],readPublic:d=>B.readPublicFile(d),retainPrivate:()=>{},tools:{mcp__easypanel__execute_query:async()=>{calls++;await gate;return{};}},writeToNode:async()=>{writes++;}});const running=relay.step(f.packets[0]);await next();relay.abort();release();assert.equal((await running).state,'unknown');assert.equal(calls,1);assert.equal(writes,0);f.bridge.abort();await assert.rejects(p,refused);});

test('public helper requests reject env/password/token before any output',async t=>{const f=fixture(t);for(const payload of[{env:SECRET},{nested:{password:SECRET}},{PG_ADMIN_PASSWORD:SECRET}])await assert.rejects(f.bridge.request('admission',payload),refused);assert.equal(f.packets.length,0);});
test('abort or step timeout during PUBLIC readback prevents native dispatch after it resolves',async t=>{for(const mode of['abort','timeout']){const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query}),q=JSON.parse(f.packets[0]);let release,calls=0;const gate=new Promise(r=>release=r);const relay=createFunctionsRelay({enabled:true,nativeApproved:true,timeoutMs:10,allowedQueries:[query],readPublic:async()=>{await gate;return B.readPublicFile(q.file);},retainPrivate:()=>{},tools:{mcp__easypanel__execute_query:async()=>{calls++;return{};}},writeToNode:async()=>{}});const task=relay.step(f.packets[0]);if(mode==='abort')relay.abort();else await new Promise(r=>setTimeout(r,15));release();assert.equal((await task).state,'unknown');assert.equal(calls,0);f.bridge.abort();await assert.rejects(p,refused);}});
test('wrong exact target, mutation not allowed, and explicit negative ACK all refuse without a retry',async t=>{for(const mode of['target','mutation']){const f=fixture(t),frame=mode==='target'?{executor:'execute_query',procedure:'listDomains',input:{...query.input,serviceName:'foreign'}}:{executor:'execute_destructive',procedure:'updateComposeEnv',input:{...query.input,createDotEnv:true,env:'PG_ADMIN_PASSWORD='+SECRET}},p=f.bridge.execute(frame);let calls=0;const relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:[query],readPublic:d=>B.readPublicFile(d),retainPrivate:()=>{},tools:{mcp__easypanel__execute_query:async()=>calls++,mcp__easypanel__execute_destructive:async()=>calls++},writeToNode:async()=>{}});assert.equal((await relay.step(f.packets[0])).state,'unknown');assert.equal(calls,0);f.bridge.abort();await assert.rejects(p,refused);}const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query});f.input.write(JSON.stringify({schema:B.RESPONSE,seq:1,ok:false})+'\n');await assert.rejects(p,refused);await assert.rejects(f.bridge.execute({executor:'execute_query',...query}),refused);assert.equal(f.packets.length,1);});

test('unknown PUBLIC input fields and nested credential blobs reject before file/stdout dispatch',async t=>{for(const input of[{...query.input,adminPassword:SECRET},{...query.input,credentials:{key:SECRET}}]){const f=fixture(t);await assert.rejects(f.bridge.execute({executor:'execute_query',procedure:'listDomains',input}),refused);assert.equal(f.packets.length,0);assert.equal(fs.readdirSync(f.dir).length,0);}});

test('PUBLIC identifiers reject typed nested blobs and getter inputs before file/output',async t=>{for(const input of[{projectName:{credentials:{key:SECRET}},serviceName:'synthetic-service'},{projectName:'synthetic-project',serviceName:42},{projectName:'synthetic-project',get serviceName(){throw Error(SECRET);}}]){const f=fixture(t);await assert.rejects(f.bridge.execute({executor:'execute_query',procedure:'listDomains',input}),refused);assert.equal(f.packets.length,0);assert.equal(fs.readdirSync(f.dir).length,0);}});
test('relay deadline resolves unknown while native callback remains pending and prevents late retention/ACK',async t=>{const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query});let release,calls=0,writes=0,retains=0;const gate=new Promise(r=>release=r);const relay=createFunctionsRelay({enabled:true,nativeApproved:true,timeoutMs:10,allowedQueries:[query],readPublic:d=>B.readPublicFile(d),retainPrivate:()=>retains++,tools:{mcp__easypanel__execute_query:async()=>{calls++;await gate;return{};}},writeToNode:async()=>{writes++;}});const running=relay.step(f.packets[0]);assert.equal((await Promise.race([running,new Promise(r=>setTimeout(()=>r({state:'unbounded'}),40))])).state,'unknown');release();await next();assert.equal(calls,1);assert.equal(writes,0);assert.equal(retains,0);f.bridge.abort();await assert.rejects(p,refused);});
test('relay abort during an already started write never reports responded after write settles',async t=>{const f=fixture(t),p=f.bridge.execute({executor:'execute_query',...query});let release,writes=0;const gate=new Promise(r=>release=r);const relay=createFunctionsRelay({enabled:true,nativeApproved:true,allowedQueries:[query],readPublic:d=>B.readPublicFile(d),retainPrivate:()=>{},tools:{mcp__easypanel__execute_query:async()=>({})},writeToNode:async()=>{writes++;await gate;}});const running=relay.step(f.packets[0]);await next();assert.equal(writes,1);assert.equal(relay.abort().state,'unknown');assert.equal((await running).state,'unknown');release();await next();assert.equal(writes,1);f.bridge.abort();await assert.rejects(p,refused);});

test('query demo projects count only from structured or one text MCP result and refuses error/shape',()=>{const {unwrap}=require('./synthetic-demo.cjs');assert.equal(unwrap({structuredContent:{procedure:'listDomains',result:[{env:SECRET}]}}),1);assert.equal(unwrap({content:[{type:'text',text:JSON.stringify({procedure:'listDomains',result:[]})}]}),0);for(const r of[{isError:true,structuredContent:{procedure:'listDomains',result:[]}},{structuredContent:{procedure:'inspectComposeService',result:[]}},{content:[{type:'text',text:SECRET}]}])assert.throws(()=>unwrap(r));});
