'use strict';
const http=require('node:http'),crypto=require('node:crypto');
const problem=(status,error)=>Object.assign(Error(error),{status,body:{error}}),KEY=/^[A-Za-z0-9_.:-]{32,256}$/,IDEM=/^[A-Za-z0-9_.:-]{16,160}$/,BULK=/^gid:\/\/shopify\/BulkOperation\/[1-9][0-9]{0,24}$/;
async function body(req,cap=4096){if(!/^application\/json(?:\s*;\s*charset=utf-8)?$/i.test(req.headers['content-type']||'')||req.headers['content-encoding'])throw problem(415,'CONTENT_TYPE_INVALID');let bytes=0,chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>cap)throw problem(413,'REQUEST_TOO_LARGE');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw problem(422,'REQUEST_INVALID');}}
function authorized(req,key){const values=req.rawHeaders.filter((_,i)=>i%2===0&&req.rawHeaders[i].toLowerCase()==='authorization');if(values.length!==1)return false;const header=req.headers.authorization||'',given=header.startsWith('Bearer ')?header.slice(7):'';if(!KEY.test(given)||given.length!==key.length)return false;return crypto.timingSafeEqual(Buffer.from(given),Buffer.from(key));}
function createServer({runtime,key,revision,enabled=false,maxPending=4}={}){let pending=0,closing=false;const server=http.createServer({requestTimeout:10000,headersTimeout:5000,maxHeaderSize:8192},async(req,res)=>{let admitted=false;const reply=(status,value)=>{if(res.writableEnded)return;const data=Buffer.from(JSON.stringify(value));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':data.length,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-CRM-Shopify-Sync-Revision':revision});res.end(data);};try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/healthz')return reply(closing?503:200,{service:'crm-shopify-sync',enabled,revision,stopping:closing});if(!enabled||closing||pending>=maxPending)throw problem(503,'SYNC_UNAVAILABLE');if(!authorized(req,key))throw problem(401,'UNAUTHORIZED');pending++;admitted=true;
   if(req.method==='GET'&&url.pathname.startsWith('/v1/operations/')){const idempotency_key=decodeURIComponent(url.pathname.slice('/v1/operations/'.length));if(!IDEM.test(idempotency_key)||url.search)throw problem(422,'REQUEST_INVALID');return reply(200,await runtime.inspect(idempotency_key));}
   if(req.method!=='POST'||!['/v1/run','/v1/recover'].includes(url.pathname)||url.search)throw problem(404,'ROUTE_INVALID');const input=await body(req);if(!input||typeof input!=='object'||Array.isArray(input))throw problem(422,'REQUEST_INVALID');const allowed=url.pathname==='/v1/run'?['brand','idempotency_key','scheduled_for']:['brand','idempotency_key','scheduled_for','bulk_operation_id'];if(Object.keys(input).some(k=>!allowed.includes(k))||!['fish','aristo'].includes(input.brand)||!IDEM.test(input.idempotency_key||'')||!/^20[0-9]{2}-[0-9]{2}-[0-9]{2}T[0-9:.]+Z$/.test(input.scheduled_for||'')||url.pathname==='/v1/recover'&&!BULK.test(input.bulk_operation_id||''))throw problem(422,'REQUEST_INVALID');const result=await runtime.request({...input,kind:url.pathname==='/v1/run'?'run':'recover',bulk_operation_id:url.pathname==='/v1/run'?null:input.bulk_operation_id});return reply(202,result);
  }catch(e){reply(e.status||503,e.body||{error:'SYNC_UNAVAILABLE'});}finally{if(admitted)pending--;}});let stopped;const stop=()=>stopped||=(async()=>{closing=true;server.closeIdleConnections();await new Promise(resolve=>server.close(resolve));await runtime.stop();})();return {server,stop,pending:()=>pending};}
module.exports={createServer,authorized};
