'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{pipeline}=require('node:stream/promises'),{Transform}=require('node:stream');
const PRODUCT_QUERY=fs.readFileSync(path.join(__dirname,'../../n8n/growth/segment-shopify-customer-products-bulk.graphql'),'utf8'),STATE_QUERY=fs.readFileSync(path.join(__dirname,'../../n8n/growth/segment-shopify-bulk-state.graphql'),'utf8');
const QUERY_SHA256=crypto.createHash('sha256').update(PRODUCT_QUERY).digest('hex');if(QUERY_SHA256!=='bb89faf525f58f9c5075878888c1be6fcf4992200310a4867cdd2871fb570086')throw Error('CRM_SHOPIFY_QUERY_DRIFT');
const START_QUERY='mutation CrmAudienceRunCustomerBulk($query: String!) { bulkOperationRunQuery(query: $query) { bulkOperation { id status } userErrors { field message } } }';
const RECOVER_QUERY='query CrmAudienceRecentBulks { bulkOperations(first: 10, reverse: true) { edges { node { id status errorCode createdAt completedAt objectCount rootObjectCount fileSize url partialDataUrl query } } } }';
const OPERATION_QUERY='query CrmAudienceBulkStateWithQuery($operation: ID!) { shop { id myshopifyDomain currencyCode ianaTimezone } currentAppInstallation { accessScopes { handle } } node(id: $operation) { ... on BulkOperation { id query status errorCode objectCount rootObjectCount createdAt completedAt fileSize url partialDataUrl } } }';
const uncertain=code=>Object.assign(Error(code),{uncertain:true});
function createShopify({brands,fetchFn=fetch,maxBytes=40*1024*1024,timeoutMs=15000,tokenProvider}={}){
 if(!brands||typeof fetchFn!=='function')throw Error('CRM_SHOPIFY_TRANSPORT_CONFIG');
 const tokens=new Map();async function accessToken(brand){if(tokenProvider)return tokenProvider(brand);const c=brands[brand],cached=tokens.get(brand);if(cached&&cached.until>Date.now()+60000)return cached.value;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetchFn(`https://${c.shop}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'client_credentials'}),redirect:'manual',signal:controller.signal});if(response.status!==200||!/^application\/json\b/i.test(response.headers.get('content-type')||''))throw Error('CRM_SHOPIFY_OAUTH');const value=await response.json(),seconds=Number(value?.expires_in);if(typeof value?.access_token!=='string'||value.access_token.length<20||!Number.isFinite(seconds)||seconds<120||seconds>86400)throw Error('CRM_SHOPIFY_OAUTH');tokens.set(brand,{value:value.access_token,until:Date.now()+seconds*1000});return value.access_token;}catch(e){if(e?.message==='CRM_SHOPIFY_OAUTH')throw e;throw Error('CRM_SHOPIFY_OAUTH');}finally{clearTimeout(timer);controller.abort();}}
 async function graphql(brand,query,variables={}){const c=brands[brand];if(!c)throw Error('CRM_SHOPIFY_BRAND');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);let response;
  try{const token=await accessToken(brand);response=await fetchFn(`https://${c.shop}/admin/api/2026-07/graphql.json`,{method:'POST',headers:{'X-Shopify-Access-Token':token,'Content-Type':'application/json'},body:JSON.stringify({query,variables}),redirect:'manual',signal:controller.signal});if(response.status!==200||!/^application\/json\b/i.test(response.headers.get('content-type')||''))throw uncertain('CRM_SHOPIFY_RESPONSE_UNKNOWN');const announced=Number(response.headers.get('content-length'));if(Number.isFinite(announced)&&announced>1024*1024)throw Error('CRM_SHOPIFY_RESPONSE_LARGE');const text=await response.text();if(Buffer.byteLength(text)>1024*1024)throw Error('CRM_SHOPIFY_RESPONSE_LARGE');let body;try{body=JSON.parse(text);}catch{throw uncertain('CRM_SHOPIFY_RESPONSE_UNKNOWN');}if(body.errors?.length)throw Error('CRM_SHOPIFY_GRAPHQL');return body;}catch(e){if(['CRM_SHOPIFY_OAUTH','CRM_SHOPIFY_RESPONSE_LARGE','CRM_SHOPIFY_GRAPHQL'].includes(e?.message)||e?.uncertain)throw e;throw uncertain('CRM_SHOPIFY_RESPONSE_UNKNOWN');}finally{clearTimeout(timer);controller.abort();}
 }
 return Object.freeze({querySha256:QUERY_SHA256,
  async start(brand){const body=await graphql(brand,START_QUERY,{query:PRODUCT_QUERY}),result=body?.data?.bulkOperationRunQuery;if(result?.userErrors?.length)throw Error('CRM_SHOPIFY_START_REJECTED');if(!result||!/^gid:\/\/shopify\/BulkOperation\/[1-9][0-9]{0,24}$/.test(result.bulkOperation?.id||''))throw uncertain('CRM_SHOPIFY_START_UNKNOWN');return result.bulkOperation.id;},
  async reconcileStart(brand){const body=await graphql(brand,RECOVER_QUERY),nodes=(body?.data?.bulkOperations?.edges||[]).map(x=>x?.node).filter(Boolean),matches=nodes.filter(x=>crypto.createHash('sha256').update(x.query||'').digest('hex')===QUERY_SHA256);return matches;},
  async poll(brand,id){const body=await graphql(brand,OPERATION_QUERY,{operation:id}),node=body?.data?.node;if(!node||node.id!==id||crypto.createHash('sha256').update(node.query||'').digest('hex')!==QUERY_SHA256)throw Error('CRM_SHOPIFY_POLL_INVALID');return {operation:body,node};},
  async download(url,file){let parsed;try{parsed=new URL(url);}catch{throw Error('CRM_SHOPIFY_DOWNLOAD_URL');}if(parsed.protocol!=='https:'||parsed.username||parsed.password)throw Error('CRM_SHOPIFY_DOWNLOAD_URL');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs*4);let response;try{response=await fetchFn(parsed,{redirect:'manual',signal:controller.signal});if(response.status!==200||!response.body)throw Error('CRM_SHOPIFY_DOWNLOAD_RESPONSE');const announced=Number(response.headers.get('content-length'));if(Number.isFinite(announced)&&announced>maxBytes)throw Error('CRM_SHOPIFY_DOWNLOAD_LIMIT');let bytes=0;const hash=crypto.createHash('sha256'),guard=new Transform({transform(chunk,_encoding,callback){bytes+=chunk.length;if(bytes>maxBytes)return callback(Error('CRM_SHOPIFY_DOWNLOAD_LIMIT'));hash.update(chunk);callback(null,chunk);}});await pipeline(response.body,guard,fs.createWriteStream(file,{flags:'wx',mode:0o600}));return {bytes,sha256:hash.digest('hex')};}finally{clearTimeout(timer);controller.abort();}}
 });
}
module.exports={createShopify,PRODUCT_QUERY,QUERY_SHA256,START_QUERY,RECOVER_QUERY,OPERATION_QUERY};
