 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const out=path.resolve(__dirname,'../../n8n/growth'),input=process.env.SHRIGMA_AUDIENCE_CONTEXT_INPUTS||path.resolve(__dirname,'../../../inputs/n8n/growth');
const cache={};function load(name,candidate=true){const key=name+candidate;if(cache[key])return cache[key];const filename=path.join(candidate&&fs.existsSync(path.join(out,name))?out:input,name),m=new Module(filename);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));m.require=n=>n.startsWith('./')?load(n.slice(2),candidate):require(n);cache[key]=m.exports;m._compile(fs.readFileSync(filename,'utf8'),filename);cache[key]=m.exports;return m.exports;}
const S=load('segment-audience-store.cjs'),Original=load('segment-audience-store.cjs',false),A=load('segment-audience-contract.js'),H=load('segment-audience-review.cjs'),C=load('segment-audience-context-review.cjs'),API=load('segment-audience-api.cjs');
const Shopify=load('segment-shopify-facts.cjs');
const clone=v=>JSON.parse(JSON.stringify(v)),id='11111111-1111-4111-8111-111111111111',key='fixture-key-123',time='2026-10-07T12:00:00.000Z';
async function fixture(brand='fish',opts={}){
 const def=A.normalize({schema_version:A.VERSION,brand,name:'Fixture',rule:opts.product?{op:'condition',field:'purchase.product',operator:'purchased',value:'gid://shopify/Product/123'}:{op:'condition',field:'email.opened',operator:'within_last_days',value:7}});
 const source={currency:null,timezone:null,shop_id:null,fields:[{key:'email.opened',available:opts.available!==false,source_hash:'a'.repeat(64)}],products:[],origins:[]};
 if(opts.product){source.currency='BRL';source.timezone='America/Sao_Paulo';source.shop_id='gid://shopify/Shop/12';source.products=[{id:'gid://shopify/Product/123',brand,name:'Native fixture',available:true}];source.fields=[{key:'purchase.product',available:true,source_hash:Shopify.sourceHash(brand,'purchase.product',source)}];}
 const config={brand,enabled:true,base_list_id:1,revision:1,catalog:source,checked_at:time,read_at:time,expires_at:'2026-10-07T12:04:00.000Z'},lists=[{id:1,name:'Fixture list',status:'active',optin:'single'}];
 let calls=[],auth=0,configs=0,gets=0,row;
 async function query(sql,values){calls.push(sql);if(sql===S.SQL.setup)return {rows:[]};if(sql===S.SQL.boundary)return {rows:[{isolation:'read committed',timeout_ms:25000}]};if(sql===S.SQL.auth){auth++;const who=opts.actorAt===auth?'panel:other':'panel:fixture';return {rows:[{operator:{who,caps:opts.denyAt===auth?[]:['read_content']},live_count:opts.revokeAt===auth?0:1,live_actor:who}]};}if(sql===S.SQL.config){configs++;const c=clone(config);if(opts.drift&&configs>1)c.catalog.fields[0].source_hash='c'.repeat(64);return {rows:[c]};}if(sql===S.SQL.shopify)return {rows:[{source:{current:opts.sourceUnavailable!==true,started_at:time,observed_at:time,expires_at:'2026-10-08T14:00:00.000Z',customers:3,mapped:3,unresolved:0}}]};if(sql===S.SQL.lists)return {rows:clone(lists)};if(sql===S.SQL.get){gets++;return {rows:opts.notfound?[]:[clone({...row,...(opts.rowChange&&gets>1?{version:2}:{})})]};}throw Error('Unexpected SQL');}
 const sourceUnavailable=opts.sourceUnavailable;opts.sourceUnavailable=false;const current=await S.readCatalog(query,brand);opts.sourceUnavailable=sourceUnavailable;configs=0;calls=[];const context=S.pins(def,opts.product?current:{...current,catalog:{...current.catalog,fields:[{key:'email.opened',available:true,source_hash:'a'.repeat(64)}]}});if(opts.product&&opts.oldProduct)context.rules[0].source_hash=H.digest({semantics:Shopify.PRODUCT_SEMANTICS_V1,brand,field:'purchase.product',shop_id:source.shop_id,currency:source.currency,timezone:source.timezone});if(opts.divergent)context.rules[0].source_hash='b'.repeat(64);
 row={id,brand,name:def.name,definition:def,definition_hash:H.digest(def),context,context_hash:H.digest(context),version:opts.version||1,archived:!!opts.archived,created_at:time,updated_at:time,updated_by:'panel:fixture'};if(opts.badHash)row.context_hash='d'.repeat(64);if(opts.badContext){row.context.extra='bad';row.context_hash=H.digest(row.context);}
 const initial=clone(row),request={acao:'segmento_contexto_revisao',brand,id,expected_version:1,expected_catalog_hash:opts.badCatalog?'f'.repeat(64):current.catalog.catalog_hash};
 const store=S.createAudienceStore({transaction:fn=>fn({query}),refreshCatalog:()=>{throw Error('refresh forbidden');},countProvider:()=>{throw Error('count forbidden');}});
 const result=await store.execute({key,request});assert.deepEqual(row,initial);assert(calls.every(q=>[S.SQL.setup,S.SQL.boundary,S.SQL.auth,S.SQL.config,S.SQL.lists,S.SQL.get,S.SQL.shopify].includes(q)));return {result,request,def,calls};
}
test('SQL and original source boundaries remain exact',()=>{assert.deepEqual(S.SQL,Original.SQL);for(const n of ['readAuth','readCatalog','pins','sourceConfig','publicSegment','countResult'])assert.equal(String(S[n]),String(Original[n]));const original=fs.readFileSync(path.join(input,'segment-audience-store.cjs'),'utf8'),candidate=fs.readFileSync(path.join(out,'segment-audience-store.cjs'),'utf8'),marker='   if(writing)await query(SQL.lock,[first.actor,p.idempotency_key]);';assert.equal(candidate.slice(candidate.indexOf(marker)),original.slice(original.indexOf(marker)));});
for(const brand of ['fish','aristo'])for(const divergent of [false,true])test(`${brand} factual context ${divergent}`,async()=>{const f=await fixture(brand,{divergent});assert.equal(f.result._http,200);const r=f.result._body.context_review;assert.equal(r.context_current,!divergent);assert.equal(r.changes.length,divergent?1:0);if(divergent)assert.deepEqual(r.changes[0],{path:'rules[0].source_hash',before:'b'.repeat(64),after:'a'.repeat(64)});assert.equal(r.authorizes_refresh,false);assert.equal(r.transport_supported,false);assert(Object.isFrozen(r.changes));assert.equal(f.calls.filter(q=>q===S.SQL.get).length,2);C.validateResponse({status:200,body:f.result._body},f.request,{definition:f.def,secrets:[key]});});
for(const [opts,status,code]of [[{notfound:true},404,'SEGMENT_NOT_FOUND'],[{archived:true},409,'SEGMENT_ARCHIVED'],[{version:2},409,'SEGMENT_VERSION_CONFLICT'],[{badCatalog:true},409,'SEGMENT_CATALOG_CHANGED'],[{drift:true},409,'SEGMENT_CATALOG_CHANGED'],[{badHash:true},503,'SEGMENT_READBACK_UNCONFIRMED'],[{badContext:true},503,'SEGMENT_READBACK_UNCONFIRMED'],[{rowChange:true},409,'SEGMENT_VERSION_CONFLICT'],[{available:false},422,'SEGMENT_LIST_UNAVAILABLE']])test(code+JSON.stringify(opts),async()=>{const f=await fixture('fish',opts);assert.equal(f.result._http,status);assert.equal(f.result._body.error,code);C.validateResponse({status,body:f.result._body},f.request);});
for(const field of ['actorAt','denyAt','revokeAt'])for(const at of [2,3,4,5,6])test(`${field} await ${at}`,async()=>{const f=await fixture('fish',{[field]:at});assert.equal(f.result._http,field==='denyAt'?403:401);});
test('HTTP GET parsing and fixed projection',async()=>{const f=await fixture();const input={method:'GET',request:{headers:{Authorization:'Bearer '+key},query:{...f.request,expected_version:'1'}}};const entry=API.parse(input);assert.equal(entry.route,'execute');assert.equal(entry.request.expected_version,1);assert.equal(API.project(entry,f.result).status,200);assert.equal(API.parse({...input,method:'POST',request:{headers:input.request.headers,body:f.request}}).response.status,405);assert.throws(()=>API.project(entry,{_http:409,_body:{error:'SEGMENT_CATALOG_CHANGED',secret:key}}));assert.throws(()=>API.project(entry,{_http:404,_body:{error:'SEGMENT_ARCHIVED'}}));});
test('DTO rejects extras, secrets, arbitrary paths, mismatched hashes and prototypes',async()=>{const f=await fixture('aristo',{divergent:true});for(const mutate of [b=>b.extra=1,b=>b.context_review.extra=key,b=>b.context_review.changes[0].path='definition.name',b=>b.context_review.changes[0].before=key,b=>b.context_review.definition_hash='f'.repeat(64),b=>b.context_review.context_current=true,b=>b.context_review.changes.push(b.context_review.changes[0])]){const b=clone(f.result._body);mutate(b);assert.throws(()=>C.validateBody(b,f.request,{definition:f.def,secrets:[key]}));}const bad=Object.create({});Object.assign(bad,f.result._body);assert.throws(()=>C.validateBody(bad,f.request));const getter={};Object.defineProperty(getter,'context_review',{enumerable:true,get(){throw Error('never');}});assert.throws(()=>C.validateBody(getter,f.request));const b=clone(f.result._body),safe=C.validateBody(b,f.request);b.context_review.changes[0].before='f'.repeat(64);assert.equal(safe.context_review.changes[0].before,'b'.repeat(64));});

for(const brand of ['fish','aristo'])test(brand+' native Shopify fingerprint v1 versus v2',async()=>{const f=await fixture(brand,{product:true,oldProduct:true});assert.equal(f.result._http,200);const r=f.result._body.context_review;assert.equal(r.context_current,false);assert.equal(r.changes.length,1);assert.equal(r.changes[0].path,'rules[0].source_hash');C.validateResponse({status:200,body:f.result._body},f.request,{definition_hash:H.digest(f.def),secrets:[key]});assert.throws(()=>C.validateResponse({status:200,body:f.result._body},f.request));});
test('bounded requests and closed fixed errors',async()=>{const f=await fixture();for(const change of [{expected_version:0},{expected_version:1000000000},{id:'invalid'},{expected_catalog_hash:'x'},{unexpected:true}])assert.throws(()=>S.request({...f.request,...change}));for(const result of [{status:202,body:{error:'SEGMENT_SERVICE_UNAVAILABLE'}},{status:409,body:{error:'SEGMENT_VERSION_CONFLICT',current_version:1}},{status:503,body:{error:'secret-query'}},{status:503,body:{error:'SEGMENT_SERVICE_UNAVAILABLE',extra:key}}])assert.throws(()=>C.validateResponse(result,f.request));});

test('native Shopify source unavailable retains original refusal',async()=>{const f=await fixture('fish',{product:true,sourceUnavailable:true});assert.equal(f.result._http,409);assert.equal(f.result._body.error,'SEGMENT_CATALOG_CHANGED');});
test('trusted definition hash and frozen Root projection',async()=>{const f=await fixture();const value={status:200,body:f.result._body};assert.throws(()=>C.validateResponse(value,f.request,{definition_hash:'f'.repeat(64)}));const checked=C.validateResponse(value,f.request,{definition:f.def});assert(Object.isFrozen(checked));assert(Object.isFrozen(checked.body.context_review));const raw=clone(value);const safe=C.validateResponse(raw,f.request,{definition:f.def});raw.body.context_review.version=2;assert.equal(safe.body.context_review.version,1);});
