 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const K=require(path.join(process.env.CRM_CONTEXT_DIRECTORY,'domain/audience-slices/kernel.cjs'));
const D=require(path.join(process.env.CRM_CONTEXT_DIRECTORY,'services/dashboard-operational/domain/deliverability/policy.cjs'));
const B=require('../../services/dashboard-operational/domain/crm-mvp-controls/boundary.cjs');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`, h='a'.repeat(64), now=100000;
function fixture(brand='fish'){
 const distribution={schema:K.VERSION,brand,id:id(1),revision:1,key:h,identity_contract:K.IDENTITY,algorithm:K.ALGORITHM};
 const plan={schema:K.VERSION,brand,distribution_id:id(1),distribution_revision:1,key_hash:K.keyHash(distribution),slices:[{id:id(2),name:'all',from_bp:0,to_bp:10000}]};
 const snapshot={schema:'crm-audience-slice-source-v1',brand,audience_id:id(3),audience_revision:1,definition_hash:h,snapshot_id:id(4),source_hash:h,observed_at:new Date(now).toISOString(),expires_at:new Date(now+50000).toISOString(),complete:true,identity_complete:true,members:[id(5)]};
 const claims={schema:'crm-audience-slice-claims-v1',brand,distribution_id:id(1),distribution_revision:1,key_hash:plan.key_hash,revision:1,complete:true,claims:[]};
 const selection={plan,distribution,slice_id:id(2),snapshot,claims},before=K.select({...selection,now});
 const campaign={brand,campaign_id:1,campaign_version:1,content_hash:h,audience_definition_hash:h};
 const guards={brand,campaign_id:1,campaign_version:1,content_hash:h,definition_hash:h,members_hash:before.members_hash,observed_at:snapshot.observed_at,expires_at:snapshot.expires_at,content_current:true,consent_current:true,bounce_current:true,frequency_current:true};
 const policy=D.createPolicy({brand,softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:x=>x,clock:()=>now});
 const evidence={brand,membersHash:before.members_hash,campaignId:1,campaignVersion:1,ledgerRevision:1,revision:1,observedAt:now,expiresAt:now+50000,authority:'admitted',suspension:'clear',members:[{subjectId:id(5),recipientRef:h,consent:'current',capping:'clear',bounce:'current',consentRevision:1,cappingRevision:1,policyState:policy.initialState(),policyRevision:0}]};
 return {selection,before,campaign,beforeCampaign:campaign,guards,evidence,operationId:id(6)};
}
function setup(){
 let live=fixture(), writes=0, unknown=false; const records=new Map(),capacity=new Set();
 const recordKey=i=>`${i.brand}/${i.operationId}`;
 const registrations=new Map(['fish','aristo'].flatMap(brand=>[6,7,8].map(n=>{
  const i={brand,operationId:id(n),attemptId:id(n)};
  return [recordKey(i),{...i,state:'registered',reservationAttempted:false,durable:true,revision:1,receiptHash:h}];
 })));
 const adapter={contractVersion:B.VERSION,async inspectOperation(i){return records.get(recordKey(i))||registrations.get(recordKey(i))||{...i,state:'absent'};},async reserveOperation(i){
  // Synthetic synchronous critical section only; no production durability proof.
  if(records.has(recordKey(i)))return records.get(recordKey(i));
  const registration=registrations.get(recordKey(i));
  if(!registration||registration.reservationAttempted!==false||i.expectedOperationRevision!==registration.revision)return {...i,state:'refused'};
  registration.reservationAttempted=true;
  const capacityKeys=live.selection.snapshot.members.map(member=>`${i.brand}/${member}`);
  if(capacityKeys.some(key=>capacity.has(key)))return {...i,state:'refused'};
  const d=i.evaluate({...live,operationId:i.operationId});if(d.state!=='eligible-for-reservation')return {...i,state:'refused'};
  const r={brand:i.brand,operationId:i.operationId,attemptId:i.attemptId,state:'reserved',revision:2,outcomeWriteState:'idle',scope:d.scope,reservedMemberCount:d.scope.memberCount,reservedMembersHash:d.scope.membersHash,capacityEvidenceHash:d.scope.evidenceHash,atomic:true,idempotent:true,durable:true,reservation:true,receiptHash:h};records.set(recordKey(i),r);capacityKeys.forEach(key=>capacity.add(key));writes++;if(unknown)throw Error('lost ack');return r;
 },async recordOutcome(i){const r=records.get(recordKey(i));if(!r||r.brand!==i.brand||r.revision!==i.expectedOperationRevision||r.outcomeWriteState!=='idle')return null;if(['accepted','rejected_before_send'].includes(r.state)&&r.state!==i.outcome)return null;const next={...r,state:i.outcome==='unknown'?'uncertain':i.outcome,revision:r.revision+1,outcomeWriteState:'idle'};records.set(recordKey(i),next);return next;}};
 const options={enabled:true,kernel:K,deliverability:D,adapter,clock:()=>now};return {live,adapter,options,records,unknown:()=>unknown=true,writes:()=>writes,b:B.create(options),i:{brand:'fish',operationId:id(6),attemptId:id(6)}};
}
test('default off and missing adapter close',async()=>{assert.equal((await B.create().reserve({})).state,'closed');assert.equal((await B.create({enabled:true,kernel:K,deliverability:D,clock:()=>now}).reserve({})).state,'closed');});
test('real pinned kernels compose pure selection and bounce policy',()=>{const s=setup();assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');assert.equal(s.b.decide(s.live).authorizesSend,false);});
test('absent and unknown veto close',()=>{for(const key of ['bounce','capping','consent'])for(const value of [undefined,'unknown']){const s=setup();s.live.evidence.members[0][key]=value;assert.equal(s.b.decide(s.live).state,'closed');}});
test('brand, member, revision, expiry and suspension isolate',()=>{for(const mutate of [x=>x.evidence.brand='aristo',x=>x.evidence.members[0].subjectId=id(9),x=>x.selection.claims.revision++,x=>x.evidence.expiresAt=now,x=>x.evidence.suspension='unknown',x=>x.campaign.campaign_version++,x=>x.evidence.members[0].policyRevision++]){const s=setup();mutate(s.live);assert.equal(s.b.decide(s.live).state,'closed');}});
test('hard bounce veto uses actual policy journal',async()=>{const s=setup(),p=D.createPolicy({brand:'fish',softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:x=>x,clock:()=>now});const token=await p.admitEvent({schema:D.EVENT_VERSION,providerId:'synthetic',brand:'fish',recipientRef:h,eventId:'event',attemptId:'attempt',classification:'hard_bounce',occurredAt:now},{});const m=s.live.evidence.members[0];m.policyState=p.apply(m.policyState,token).state;m.policyRevision=1;assert.equal(s.b.decide(s.live).reason,'bounce_veto');});
test('CAS contention and duplicate original operation write once',async()=>{const s=setup();await Promise.all([s.b.reserve(s.i),s.b.reserve(s.i)]);await s.b.reserve(s.i);assert.equal(s.writes(),1);s.live.selection.claims.revision++;const next={...s.i,operationId:id(7),attemptId:id(7)};assert.equal((await s.b.reserve(next)).state,'closed');assert.equal(s.writes(),1);});
test('unknown ACK retains original reservation across synthetic restart without retry',async()=>{const s=setup();s.unknown();assert.equal((await s.b.reserve(s.i)).state,'closed');const restarted=B.create(s.options);assert.equal((await restarted.consult(s.i)).state,'reserved');await restarted.reserve(s.i);await restarted.recordOutcome(s.i,'unknown');assert.equal((await restarted.consult(s.i)).state,'uncertain');assert.equal(s.writes(),1);assert.equal(s.records.size,1);});
test('revocation at final transaction closes; prior attempt outcome still records',async()=>{const s=setup();await s.b.reserve(s.i);s.live.evidence.members[0].consent='revoked';assert.equal((await s.b.reserve({...s.i,operationId:id(7),attemptId:id(7)})).state,'closed');assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(s.writes(),1);});
test('unproven reservation ACK and failed lookup close',async()=>{const s=setup();s.adapter.inspectOperation=async()=>{throw Error('unknown');};assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);const q=setup();const original=q.adapter.reserveOperation;q.adapter.reserveOperation=async i=>({...await original(i),atomic:false});assert.equal((await q.b.reserve(q.i)).state,'closed');});
test('pure decision has no store or clock dependency',()=>{const P=require('../../services/dashboard-operational/domain/crm-mvp-controls/decision.cjs');const decide=P.createDecision({kernel:K,deliverability:D});assert.equal(decide({...fixture(),now}).state,'eligible-for-reservation');assert.equal(decide({...fixture(),now:NaN}).state,'closed');});
test('missing registration and malformed registration never write',async()=>{for(const change of [r=>({...r,state:'absent'}),r=>({...r,reservationAttempted:true}),r=>({...r,durable:false}),r=>({...r,revision:0}),r=>({...r,receiptHash:null}),r=>({...r,brand:'aristo'})]){const s=setup(),read=s.adapter.inspectOperation;s.adapter.inspectOperation=async i=>change(await read(i));assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);}});
test('lost ACK cannot cause second reservation even if lookup erroneously reports registered',async()=>{const s=setup();let calls=0;const reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>{calls++;return reserve(i);};s.unknown();await s.b.reserve(s.i);s.adapter.inspectOperation=async i=>({...i,state:'registered',reservationAttempted:false,durable:true,revision:1,receiptHash:h});const r=await s.b.reserve(s.i);assert.equal(r.state,'closed');assert.equal(calls,1);assert.equal(s.writes(),1);});
test('lost ACK returns original identity and consult-only instruction',async()=>{const s=setup();s.unknown();const r=await s.b.reserve(s.i);assert.equal(r.operationId,s.i.operationId);assert.equal(r.attemptId,s.i.attemptId);assert.equal(r.action,'consult_original');assert.equal(r.automaticReplay,false);assert.equal(r.newAttemptAllowed,false);});
test('independent operations contend for same members without second reservation',async()=>{const s=setup();const results=await Promise.all([s.b.reserve(s.i),s.b.reserve({...s.i,operationId:id(8),attemptId:id(8)})]);assert.equal(results.filter(r=>r.state==='reserved').length,1);assert.equal(s.writes(),1);assert.equal(s.records.size,1);});
test('revocation between pure review and transactional evaluation closes before write',async()=>{const s=setup();assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');const reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>{s.live.evidence.members[0].consent='revoked';return reserve(i);};assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);});
test('receipt must bind exact final evidence scope and one evaluation',async()=>{for(const change of [r=>({...r,scope:{...r.scope,evidenceHash:'b'.repeat(64)}}),r=>({...r,idempotent:false}),r=>({...r,durable:false}),r=>({...r,reservation:false}),r=>({...r,attemptId:id(9)})]){const s=setup(),reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>change(await reserve(i));assert.equal((await s.b.reserve(s.i)).state,'closed');}const s=setup();s.adapter.reserveOperation=async i=>{i.evaluate(s.live);i.evaluate(s.live);return {...i,state:'reserved'};};assert.equal((await s.b.reserve(s.i)).state,'closed');});
test('journal corruption, missing journal and missing evidence revisions close',()=>{for(const change of [x=>x.evidence.members[0].policyState={...x.evidence.members[0].policyState,historyHash:h},x=>x.evidence.members[0].policyState=null,x=>delete x.evidence.revision,x=>delete x.evidence.members[0].consentRevision,x=>delete x.evidence.members[0].cappingRevision,x=>x.evidence.observedAt=-1,x=>x.evidence.expiresAt=now+60001,x=>x.operationId='invalid']){const s=setup();change(s.live);assert.equal(s.b.decide(s.live).state,'closed');}});
test('brand switch cannot consult or record prior brand operation',async()=>{const s=setup();await s.b.reserve(s.i);const other={...s.i,brand:'aristo'};assert.equal((await s.b.consult(other)).state,'closed');assert.equal((await s.b.recordOutcome(other,'accepted')).state,'closed');assert.equal(s.records.get('fish/'+s.i.operationId).state,'reserved');});
test('terminal outcome cannot regress on synthetic adapter',async()=>{const s=setup();await s.b.reserve(s.i);assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal((await s.b.recordOutcome(s.i,'unknown')).state,'closed');assert.equal((await s.b.consult(s.i)).state,'accepted');assert.equal(s.writes(),1);});
test('original reservation blocks a different operation after synthetic restart',async()=>{const s=setup();s.unknown();await s.b.reserve(s.i);const restarted=B.create(s.options);assert.equal((await restarted.reserve({...s.i,operationId:id(8),attemptId:id(8)})).state,'closed');assert.equal((await restarted.consult(s.i)).state,'reserved');assert.equal(s.writes(),1);});

test('complete empty selection cannot create reservation; incomplete is unavailable',()=>{const s=setup();s.live.selection.snapshot.members=[];s.live.before=K.select({...s.live.selection,now});s.live.guards.members_hash=s.live.before.members_hash;s.live.evidence.membersHash=s.live.before.members_hash;s.live.evidence.members=[];assert.equal(s.b.decide(s.live).reason,'empty_selection');s.live.selection.snapshot.complete=false;s.live.selection.snapshot.members=null;assert.equal(s.b.decide(s.live).state,'closed');});
test('two brands can reserve same operation ID independently through shared adapter',async()=>{const s=setup();assert.equal((await s.b.reserve(s.i)).state,'reserved');Object.assign(s.live,fixture('aristo'));assert.equal((await s.b.reserve({...s.i,brand:'aristo'})).state,'reserved');assert.equal(s.writes(),2);assert.equal(s.records.size,2);assert.equal((await s.b.consult(s.i)).state,'reserved');assert.equal((await s.b.consult({...s.i,brand:'aristo'})).state,'reserved');});
test('consult refuses receipt labels without durable scoped reservation proof',async()=>{for(const change of [r=>({...r,durable:false}),r=>({...r,receiptHash:null}),r=>({...r,reservation:false}),r=>({...r,scope:{...r.scope,brand:'aristo'}})]){const s=setup();await s.b.reserve(s.i);const read=s.adapter.inspectOperation;s.adapter.inspectOperation=async i=>change(await read(i));assert.equal((await s.b.consult(s.i)).state,'closed');assert.equal(s.writes(),1);}});
test('soft bounce threshold counts original attempts and delivered does not reset veto',async()=>{const s=setup(),p=D.createPolicy({brand:'fish',softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:x=>x,clock:()=>now}),m=s.live.evidence.members[0];async function append(eventId,attemptId,classification){const token=await p.admitEvent({schema:D.EVENT_VERSION,providerId:'synthetic',brand:'fish',recipientRef:h,eventId,attemptId,classification,occurredAt:now},{});m.policyState=p.apply(m.policyState,token).state;m.policyRevision=m.policyState.revision;}
await append('e1','a1','soft_bounce');await append('e2','a1','soft_bounce');assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');await append('e3','a2','soft_bounce');assert.equal(s.b.decide(s.live).reason,'bounce_veto');await append('e4','a3','delivered');assert.equal(s.b.decide(s.live).reason,'bounce_veto');});
test('registration CAS conflict cannot claim durable reservation',async()=>{const s=setup(),read=s.adapter.inspectOperation;s.adapter.inspectOperation=async i=>({...await read(i),revision:2});assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);});

test('reservation retains captured identity when caller mutates during async lookup',async()=>{const s=setup(),original={...s.i},read=s.adapter.inspectOperation;let resume;const pause=new Promise(resolve=>resume=resolve);s.adapter.inspectOperation=async i=>{const r=await read(i);await pause;return r;};const pending=s.b.reserve(s.i);s.i.brand='aristo';s.i.operationId=id(9);s.i.attemptId=id(9);resume();const result=await pending;assert.equal(result.state,'reserved');assert.equal(result.operationId,original.operationId);assert.equal(s.records.has('fish/'+original.operationId),true);assert.equal(s.records.has('aristo/'+id(9)),false);});
test('consult failure preserves original operation and recovery instruction',async()=>{const s=setup();s.adapter.inspectOperation=async()=>{throw Error('lookup unavailable');};const r=await s.b.consult(s.i);assert.equal(r.operationId,s.i.operationId);assert.equal(r.attemptId,s.i.attemptId);assert.equal(r.action,'consult_original');assert.equal(r.newAttemptAllowed,false);});

function addMember(s,subjectId=id(7),recipientRef='b'.repeat(64)){
 s.live.selection.snapshot.members.push(subjectId);
 s.live.before=K.select({...s.live.selection,now});
 s.live.guards.members_hash=s.live.before.members_hash;
 s.live.evidence.membersHash=s.live.before.members_hash;
 s.live.evidence.members.push({...s.live.evidence.members[0],subjectId,recipientRef});
}
test('all members reserve as one operation with full member/capacity proof',async()=>{const s=setup();addMember(s);assert.equal((await s.b.reserve(s.i)).state,'reserved');const r=s.records.get('fish/'+s.i.operationId);assert.equal(r.scope.memberCount,2);assert.equal(r.reservedMemberCount,2);assert.equal(r.reservedMembersHash,K.digest([id(5),id(7)]));assert.equal(r.capacityEvidenceHash,r.scope.evidenceHash);assert.equal(s.writes(),1);});
test('one unknown or refused member veto closes the whole multi-member operation',async()=>{for(const key of ['consent','bounce','capping'])for(const value of ['unknown','revoked',undefined]){const s=setup();addMember(s);s.live.evidence.members[1][key]=value;assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);assert.equal(s.records.size,0);}});
test('partial reservation receipt never opens admission or creates another attempt',async()=>{for(const change of [r=>({...r,reservedMemberCount:1}),r=>({...r,reservedMembersHash:'b'.repeat(64)}),r=>({...r,capacityEvidenceHash:null})]){const s=setup();addMember(s);const reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>change(await reserve(i));const r=await s.b.reserve(s.i);assert.equal(r.state,'closed');assert.equal(r.operationId,s.i.operationId);await s.b.reserve(s.i);assert.equal(s.writes(),1);assert.equal(s.records.size,1);}});
test('different selections sharing one contact cannot both reserve it',async()=>{const s=setup();await s.b.reserve(s.i);addMember(s);const next={...s.i,operationId:id(8),attemptId:id(8)};assert.equal((await s.b.reserve(next)).state,'closed');assert.equal(s.writes(),1);});
test('final live gate catches suspension/capping/brand/campaign/source/expiry changes',async()=>{for(const change of [x=>x.evidence.suspension='suspended',x=>x.evidence.members[0].capping='limit_reached',x=>x.selection.plan.brand='aristo',x=>x.campaign.campaign_version++,x=>x.selection.snapshot.audience_revision++,x=>x.evidence.expiresAt=now]){const s=setup();assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');const reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>{change(s.live);return reserve(i);};assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);}});
test('hard bounce arriving after selection closes final live transaction',async()=>{const s=setup();addMember(s);const m=s.live.evidence.members[1],p=D.createPolicy({brand:'fish',softBounceAttempts:2,providers:['synthetic'],verifyClassifiedEvent:x=>x,clock:()=>now}),reserve=s.adapter.reserveOperation;assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');s.adapter.reserveOperation=async i=>{const token=await p.admitEvent({schema:D.EVENT_VERSION,providerId:'synthetic',brand:'fish',recipientRef:m.recipientRef,eventId:'late',attemptId:'original',classification:'hard_bounce',occurredAt:now},{});m.policyState=p.apply(m.policyState,token).state;m.policyRevision=m.policyState.revision;return reserve(i);};assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(s.writes(),0);});
test('caller mutation during outcome ACK cannot change original attempt accounting',async()=>{const s=setup();await s.b.reserve(s.i);const original={...s.i},record=s.adapter.recordOutcome;let resume;const pause=new Promise(resolve=>resume=resolve);s.adapter.recordOutcome=async i=>{const r=await record(i);await pause;return r;};const pending=s.b.recordOutcome(s.i,'accepted');s.i.brand='aristo';s.i.operationId=id(9);s.i.attemptId=id(9);resume();const r=await pending;assert.equal(r.state,'accepted');assert.equal(r.operationId,original.operationId);assert.equal(s.records.get('fish/'+original.operationId).state,'accepted');});
test('caller mutation during consultation retains original scoped identity',async()=>{const s=setup();await s.b.reserve(s.i);const original={...s.i},read=s.adapter.inspectOperation;let resume;const pause=new Promise(resolve=>resume=resolve);s.adapter.inspectOperation=async i=>{const r=await read(i);await pause;return r;};const pending=s.b.consult(s.i);s.i.brand='aristo';s.i.operationId=id(9);s.i.attemptId=id(9);resume();const r=await pending;assert.equal(r.state,'reserved');assert.equal(r.operationId,original.operationId);});
test('identity accessor is refused without executing it or calling adapter',async()=>{const s=setup();let accesses=0,calls=0;s.adapter.inspectOperation=async()=>{calls++;};const input={...s.i};Object.defineProperty(input,'brand',{get(){accesses++;return 'fish';}});assert.equal((await s.b.reserve(input)).state,'closed');assert.equal(accesses,0);assert.equal(calls,0);});
test('adapter receives only frozen identity DTOs; caller extras cannot cross boundary',async()=>{const s=setup();s.i.extraCallback=()=>{throw Error('must not forward');};const read=s.adapter.inspectOperation,record=s.adapter.recordOutcome;s.adapter.inspectOperation=async i=>{assert.equal(Object.isFrozen(i),true);assert.deepEqual(Object.keys(i).sort(),['attemptId','brand','operationId']);return read(i);};s.adapter.recordOutcome=async i=>{assert.equal(Object.isFrozen(i),true);assert.deepEqual(Object.keys(i).sort(),['attemptId','brand','expectedOperationRevision','operationId','outcome']);return record(i);};await s.b.reserve(s.i);assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');});
test('failed outcome ACK retains original identity without another reservation',async()=>{const s=setup();await s.b.reserve(s.i);s.adapter.recordOutcome=async()=>{throw Error('lost outcome ACK');};const r=await s.b.recordOutcome(s.i,'unknown');assert.equal(r.operationId,s.i.operationId);assert.equal(r.attemptId,s.i.attemptId);assert.equal(r.action,'consult_original');assert.equal(r.automaticReplay,false);assert.equal(s.writes(),1);});

test('consult rejects incomplete member/capacity hashes even when labels agree',async()=>{const s=setup();await s.b.reserve(s.i);const r=s.records.get('fish/'+s.i.operationId);delete r.scope; r.scope={brand:'fish',operationId:s.i.operationId,memberCount:1};delete r.reservedMembersHash;delete r.capacityEvidenceHash;assert.equal((await s.b.consult(s.i)).state,'closed');});

test('unknown outcome ACK blocks repeated recordOutcome writes',async()=>{const s=setup();await s.b.reserve(s.i);let calls=0;s.adapter.recordOutcome=async()=>{calls++;throw Error('unknown ACK');};await s.b.recordOutcome(s.i,'accepted');await s.b.recordOutcome(s.i,'accepted');await s.b.recordOutcome(s.i,'unknown');assert.equal(calls,1);assert.equal(s.writes(),1);});
test('outcome without an authoritative original reservation cannot reach adapter write',async()=>{const s=setup();let calls=0;s.adapter.recordOutcome=async()=>{calls++;return null;};const r=await s.b.recordOutcome(s.i,'accepted');assert.equal(r.state,'closed');assert.equal(calls,0);});
test('duplicate confirmed outcome is queried rather than written again',async()=>{const s=setup();await s.b.reserve(s.i);let calls=0;const write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{calls++;return write(i);};assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(calls,1);});
test('concurrent outcome intents cause at most one pending write',async()=>{const s=setup();await s.b.reserve(s.i);let release,calls=0;const pause=new Promise(resolve=>release=resolve),write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{calls++;await pause;return write(i);};const a=s.b.recordOutcome(s.i,'accepted');const b=s.b.recordOutcome(s.i,'rejected_before_send');release();await Promise.all([a,b]);assert.equal(calls,1);assert.equal((await s.b.consult(s.i)).state,'accepted');});
test('restart with durable pending outcome fence queries and never writes again',async()=>{const s=setup();await s.b.reserve(s.i);const r=s.records.get('fish/'+s.i.operationId);r.outcomeWriteState='uncertain';r.revision++;let calls=0;s.adapter.recordOutcome=async()=>{calls++;};const restarted=B.create(s.options);const result=await restarted.recordOutcome(s.i,'accepted');assert.equal(result.state,'closed');assert.equal(result.action,'consult_original');assert.equal(calls,0);assert.equal((await restarted.consult(s.i)).state,'reserved');assert.equal(s.writes(),1);});
test('unknown provider result persisted successfully permits later authoritative final result',async()=>{const s=setup();await s.b.reserve(s.i);let calls=0;const write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{calls++;return write(i);};assert.equal((await s.b.recordOutcome(s.i,'unknown')).state,'uncertain');assert.equal((await s.b.recordOutcome(s.i,'unknown')).state,'uncertain');assert.equal(calls,1);assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(calls,2);assert.equal(s.writes(),1);});
test('lost outcome ACK after commit resolves by query with no repeated write',async()=>{const s=setup();await s.b.reserve(s.i);let calls=0;const write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{calls++;await write(i);throw Error('lost ACK after commit');};assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'closed');assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(calls,1);const restarted=B.create(s.options);assert.equal((await restarted.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(calls,1);});
test('unknown lookup prevents outcome writes and preserves recovery identity',async()=>{const s=setup();await s.b.reserve(s.i);let calls=0;s.adapter.recordOutcome=async()=>{calls++;};s.adapter.inspectOperation=async()=>{throw Error('lookup unknown');};const r=await s.b.recordOutcome(s.i,'accepted');assert.equal(r.state,'closed');assert.equal(r.operationId,s.i.operationId);assert.equal(r.action,'consult_original');assert.equal(calls,0);});
test('missing/corrupt revision or reservation proof blocks outcome write',async()=>{for(const change of [r=>({...r,revision:0}),r=>({...r,revision:null}),r=>({...r,reservation:false}),r=>({...r,durable:false}),r=>({...r,outcomeWriteState:undefined})]){const s=setup();await s.b.reserve(s.i);let calls=0;const read=s.adapter.inspectOperation;s.adapter.inspectOperation=async i=>change(await read(i));s.adapter.recordOutcome=async()=>{calls++;};assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'closed');assert.equal(calls,0);}});
test('wrong outcome receipt CAS/scope/durability retains one-time pending fence',async()=>{for(const change of [r=>({...r,revision:2}),r=>({...r,scope:{...r.scope,campaignVersion:99}}),r=>({...r,durable:false}),r=>({...r,outcomeWriteState:'uncertain'})]){const s=setup();await s.b.reserve(s.i);let calls=0;const write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{calls++;return change(await write(i));};assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'closed');await s.b.recordOutcome(s.i,'accepted');assert.equal(calls,1);}});
test('terminal conflict is refused before invoking persistence adapter',async()=>{const s=setup();await s.b.reserve(s.i);await s.b.recordOutcome(s.i,'rejected_before_send');let calls=0;s.adapter.recordOutcome=async()=>{calls++;};const r=await s.b.recordOutcome(s.i,'accepted');assert.equal(r.reason,'terminal_outcome_conflict');assert.equal(calls,0);assert.equal((await s.b.consult(s.i)).state,'rejected_before_send');});
test('outcome accounting remains available after all present-day gates are revoked',async()=>{const s=setup();await s.b.reserve(s.i);s.live.evidence.authority='refused';s.live.evidence.suspension='suspended';s.live.evidence.members[0].consent='revoked';s.live.evidence.members[0].bounce='unknown';s.live.evidence.members[0].capping='limit_reached';s.live.evidence.expiresAt=now;assert.equal(s.b.decide(s.live).state,'closed');assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');assert.equal(s.writes(),1);});
test('admitted contract version mismatch closes every adapter action',async()=>{const s=setup();s.adapter.contractVersion='unissued-interface';let calls=0;for(const name of ['inspectOperation','reserveOperation','recordOutcome'])s.adapter[name]=async()=>{calls++;};const b=B.create(s.options);assert.equal((await b.reserve(s.i)).state,'closed');assert.equal((await b.consult(s.i)).state,'closed');assert.equal((await b.recordOutcome(s.i,'accepted')).state,'closed');assert.equal(calls,0);});
test('QA B1-V2-SCOPE-PROPERTY-ORDER: equal reordered reservation scope confirms',async()=>{const s=setup(),reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>{const r=await reserve(i);return {...r,scope:Object.fromEntries(Object.entries(r.scope).reverse())};};assert.equal((await s.b.reserve(s.i)).state,'reserved');assert.equal(s.writes(),1);});
test('equal reordered outcome scope confirms without a false unknown ACK',async()=>{const s=setup();await s.b.reserve(s.i);const write=s.adapter.recordOutcome;s.adapter.recordOutcome=async i=>{const r=await write(i);return {...r,scope:Object.fromEntries(Object.entries(r.scope).reverse())};};assert.equal((await s.b.recordOutcome(s.i,'accepted')).state,'accepted');});
test('closed structural scope comparison refuses modified/missing/extra/type-changed fields',async()=>{for(const change of [r=>({...r,scope:{...r.scope,evidenceRevision:99}}),r=>({...r,scope:{...r.scope,extra:'unexpected'}}),r=>{const scope={...r.scope};delete scope.campaignVersion;return {...r,scope};},r=>({...r,scope:{...r.scope,memberCount:String(r.scope.memberCount)}}),r=>({...r,scope:Object.assign(Object.create({}),r.scope)})]){const s=setup(),reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>change(await reserve(i));const result=await s.b.reserve(s.i);assert.equal(result.state,'closed');assert.equal(result.operationId,s.i.operationId);assert.equal(s.writes(),1);}});
test('scope accessors and hidden extra keys are refused without accessor execution',async()=>{for(const mode of ['accessor','hidden','symbol']){const s=setup(),reserve=s.adapter.reserveOperation;let accesses=0;s.adapter.reserveOperation=async i=>{const r=await reserve(i),scope={...r.scope};if(mode==='accessor')Object.defineProperty(scope,'campaignVersion',{enumerable:true,get(){accesses++;return 1;}});if(mode==='hidden')Object.defineProperty(scope,'extra',{value:1});if(mode==='symbol')scope[Symbol('extra')]=1;return {...r,scope};};assert.equal((await s.b.reserve(s.i)).state,'closed');assert.equal(accesses,0);}});
test('consultation accepts a reordered complete historical scope',async()=>{const s=setup();await s.b.reserve(s.i);const read=s.adapter.inspectOperation;s.adapter.inspectOperation=async i=>{const r=await read(i);return {...r,scope:Object.fromEntries(Object.entries(r.scope).reverse())};};assert.equal((await s.b.consult(s.i)).state,'reserved');});

test('unregistered operation is absent and cannot cause reservation or outcome writes',async()=>{const s=setup(),missing={brand:'fish',operationId:id(99),attemptId:id(99)};let reserveCalls=0,outcomeCalls=0;const reserve=s.adapter.reserveOperation;s.adapter.reserveOperation=async i=>{reserveCalls++;return reserve(i);};s.adapter.recordOutcome=async()=>{outcomeCalls++;};assert.equal((await s.b.reserve(missing)).state,'closed');assert.equal((await s.b.recordOutcome(missing,'accepted')).state,'closed');assert.equal(reserveCalls,0);assert.equal(outcomeCalls,0);assert.equal(s.writes(),0);});
test('cross-distribution operations cannot consume the same brand member capacity',async()=>{const s=setup();await s.b.reserve(s.i);s.live.selection.distribution.id=id(10);s.live.selection.plan.distribution_id=id(10);s.live.selection.plan.key_hash=K.keyHash(s.live.selection.distribution);s.live.selection.claims.distribution_id=id(10);s.live.selection.claims.key_hash=s.live.selection.plan.key_hash;s.live.before=K.select({...s.live.selection,now});s.live.guards.members_hash=s.live.before.members_hash;s.live.evidence.membersHash=s.live.before.members_hash;assert.equal(s.b.decide(s.live).state,'eligible-for-reservation');assert.equal((await s.b.reserve({...s.i,operationId:id(8),attemptId:id(8)})).state,'closed');assert.equal(s.writes(),1);});
