"use strict";
const test=require('node:test'),a=require('node:assert/strict'),crypto=require('node:crypto');
const k=require('./source/prepare.cjs'),sha=k.sha;
const candidate={...k.FIXED,newWorkerSha256:'a'.repeat(64),newImageSha256:'b'.repeat(64)};
function historical(){return Array.from({length:34},(_,n)=>({dispatch_id:crypto.randomUUID(),flow:'transacional',transport_state:'in_flight',is_test:false,brand:n<16?'aristo':'fish',started_at:'2026-09-14T17:10:00Z',outcome_at:null,accepted_at:null,send_log_id:null}));}
function snapshot(){return {legacyPendingRows:historical(),allDispatchFingerprint:{count:1,md5:'c'.repeat(32)},privateSynthetic:"$$ $& $'"};}
function request(stage='switch-to-candidate',s=snapshot(),restore={}){const refs={};for(const n of k.REFERENCES)refs[n]={reference:crypto.randomUUID(),sha256:sha(n==='snapshot'?JSON.stringify(s):n==='restore'?JSON.stringify(restore):n==='legacyPending'?JSON.stringify(s.legacyPendingRows):'synthetic-'+n)};return {stage,operationId:crypto.randomUUID(),candidate:{...candidate},privateReferences:refs};}
function callback(plan,s,{extra={},qextra={}}={}){return async()=>({operationId:plan.operationId,stage:plan.stage,purpose:k.PURPOSE,candidate:plan.candidate,actor:'SYNTHETIC_NOT_ORIGINAL_AUTHORITY',checkedAt:new Date(Date.now()-100).toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),...Object.fromEntries(Object.entries(plan.privateReferences).map(([n,r])=>[n+'Sha256',r.sha256])),...k.SOURCE,activeWorkerProcesses:plan.stage.startsWith('verify-')?1:0,measuredWorkerSha256:plan.stage.includes('candidate')?candidate.newWorkerSha256:candidate.oldWorkerSha256,measuredImageSha256:plan.stage.includes('candidate')?candidate.newImageSha256:candidate.oldImageSha256,measuredRuntimeSha256:candidate.runtimeSha256,measuredQuerySha256:candidate.querySha256,compiledKernelSha256:candidate.kernelSha256,currentProcessInstanceId:crypto.randomUUID(),priorLeaseInstanceId:crypto.randomUUID(),identityCommitAcknowledgedAt:new Date().toISOString(),legacyPendingRows:s.legacyPendingRows,quiescence:{checkedAt:new Date(Date.now()-100).toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),allFlowReserved:0,allFlowInFlight:34,newOutcomeUnknownAfterCheckpoint:0,httpActive:0,msgQPending:0,smtpActive:0,legacyIngressCoverage:'all-producers-blocked-and-drained',checkpointDispatchFingerprint:s.allDispatchFingerprint,...qextra},...extra});}
test('new purpose/four distinct inert stages preserve pins and finite timeout',()=>{for(const stage of k.STAGES){const p=k.prepare(request(stage));a.equal(p.plan.admissionPurpose,'crm.fish174.permanent-exclusion-runtime-handoff');a.equal(p.executionAvailable,false);a.equal(p.processingAuthorized,false);a.equal(p.statements.at(-1),'COMMIT;');a.equal(p.plan.statementTimeoutMs,5000);a.equal(p.plan.lockTimeoutMs,500);a.equal(p.plan.source.canonicalOverlaySha256,'fddc286630157005e82a64ba97dbcb100869f56ea6cf2ba7e61cb59232486fee');a.equal(p.statements[6].includes('__SNAPSHOT_SELECT__'),false);}});
test('candidate worker/image must be distinct; old operation schema not accepted',()=>{const r=request();r.candidate.newWorkerSha256=k.FIXED.oldWorkerSha256;a.throws(()=>k.prepare(r),/IDENTITY_REFUSED/);a.throws(()=>k.prepare({stage:'switch-to-candidate',operationId:crypto.randomUUID(),privateReferences:r.privateReferences}),/INPUT_REFUSED/);});
test('execution cannot be enabled by a source hash',()=>a.throws(()=>k.executeOriginal(),/ORIGINAL_EXECUTION_NOT_ADMITTED/));
test('missing/forged prepared object or CURRENT callback refused',async()=>{const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));await a.rejects(k.bindCurrent({prepared:p,snapshot:s}),/CURRENT_CALLBACK_REQUIRED/);await a.rejects(k.bindCurrent({prepared:{...p},snapshot:s,current:callback(p.plan,s)}),/CURRENT_CALLBACK_REQUIRED/);});
test('CURRENT exact source/measurement binding required; prior purpose refused',async()=>{const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));for(const extra of [{purpose:'crm.guarded-runtime-handoff.switch'},{handoffProofSha256:undefined},{canonicalOverlaySha256:'0'.repeat(64)},{measuredWorkerSha256:'d'.repeat(64)},{measuredQuerySha256:'e'.repeat(64)}])await a.rejects(k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s,{extra})}),/CURRENT_(REFUSED|SOURCE_PROOF_REFUSED|MEASUREMENT_REFUSED)/);});
test('unknown legacy ingress or pending work in any flow stays refused',async()=>{const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));for(const qextra of [{legacyIngressCoverage:'unknown'},{httpActive:1},{msgQPending:1},{smtpActive:1},{allFlowReserved:1},{allFlowInFlight:1},{newOutcomeUnknownAfterCheckpoint:1}])await a.rejects(k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s,{qextra})}),/QUIESCENCE_UNPROVED/);});
test('snapshot private bound/drift and own-return checkpoint required',async()=>{const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));await a.rejects(k.bindCurrent({prepared:p,snapshot:{...s,other:1},current:callback(p.plan,s)}),/SNAPSHOT_REFERENCE_REFUSED/);const q=k.prepare(request('return-to-original',s));await a.rejects(k.bindCurrent({prepared:q,snapshot:s,current:callback(q.plan,s)}),/RESTORE_REFERENCE_REFUSED/);const big={...s,large:'x'.repeat(k.MAX_PRIVATE_BYTES)};const bp=k.prepare(request('switch-to-candidate',big));await a.rejects(k.bindCurrent({prepared:bp,snapshot:big,current:callback(bp.plan,big)}),/PRIVATE_BOUND_REFUSED/);});
test('verify requires genuine distinct process/lease identity structure',async()=>{const s=snapshot(),p=k.prepare(request('verify-candidate',s));const id=crypto.randomUUID();await a.rejects(k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s,{extra:{currentProcessInstanceId:id,priorLeaseInstanceId:id}})}),/CURRENT_HEARTBEAT_REQUIRED/);});
test('private literal JSON preserved only in RAM; no authority or send assertion',async()=>{const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));const text=await k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s)});const e=JSON.parse(text);a.deepEqual(e.snapshot,s);a.equal(e.plan.processingAuthorized,false);a.equal(p.originalOperational,false);});
test('historical baseline is content-bound and cannot admit new/recent/regular/reserved work',async()=>{
 const s=snapshot(),p=k.prepare(request('switch-to-candidate',s));
 for(const mutate of [r=>r.push({...r[0],dispatch_id:crypto.randomUUID()}),r=>r[0].flow='campaign',r=>r[0].transport_state='reserved',r=>r[0].started_at=new Date().toISOString(),r=>r[0].accepted_at=new Date().toISOString(),r=>r[0].dispatch_id=r[1].dispatch_id]){
  const rows=structuredClone(s.legacyPendingRows);mutate(rows);
  await a.rejects(k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s,{extra:{legacyPendingRows:rows}})}),/LEGACY_PENDING_(REFUSED|REFERENCE_REFUSED)/);
 }
 const changed=structuredClone(s.legacyPendingRows);changed[0].payload_sha256='f'.repeat(64);
 await a.rejects(k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s,{extra:{legacyPendingRows:changed}})}),/LEGACY_PENDING_REFERENCE_REFUSED/);
 const envelope=JSON.parse(await k.bindCurrent({prepared:p,snapshot:s,current:callback(p.plan,s)}));a.deepEqual(envelope.privateAdmission.legacyPendingRows,s.legacyPendingRows);
});
