SELECT jsonb_build_object(
 'serverVersionNum',current_setting('server_version_num')::integer,
 'sessionUser',session_user,'currentUser',current_user,
 'function',(SELECT to_jsonb(p) FROM pg_catalog.pg_proc p WHERE p.oid=pg_catalog.to_regprocedure('crm_audience_v2.selection_worker_context(integer)')),'queryConstraint',(SELECT jsonb_build_object('name',c.conname,'definition',pg_catalog.pg_get_constraintdef(c.oid,true),'expression',pg_catalog.pg_get_expr(c.conbin,c.conrelid),'validated',c.convalidated,'noinherit',c.connoinherit,'deferrable',c.condeferrable,'deferred',c.condeferred,'keys',to_jsonb(c.conkey)) FROM pg_catalog.pg_constraint c WHERE c.conrelid='crm_audience_v2.regular_worker_deployment'::regclass AND c.contype='c' AND c.conkey=ARRAY[(SELECT attnum FROM pg_catalog.pg_attribute WHERE attrelid='crm_audience_v2.regular_worker_deployment'::regclass AND attname='query_sha256')]::smallint[]),
 'deployment',(SELECT to_jsonb(d) FROM crm_audience_v2.regular_worker_deployment d WHERE singleton),
 'lease',(SELECT to_jsonb(l) FROM crm_audience_v2.regular_worker_lease l WHERE singleton),
 'selectionRuntime',(SELECT to_jsonb(r) FROM crm_audience_v2.selection_runtime r WHERE singleton),
 'preservedFunctionMetadata',(SELECT coalesce(jsonb_object_agg(s.signature,to_jsonb(p) ORDER BY s.signature),'{}'::jsonb) FROM (VALUES ('crm_audience_v2.regular_worker_heartbeat(uuid,text,text)'),('crm_audience_v2.regular_worker_require(uuid,text,text)'),('crm_audience_v2.regular_delivery_claim(integer,integer,uuid,text,text,text,text,text,jsonb)'),('crm_audience_v2.regular_delivery_finish(integer,integer,uuid,uuid,text)')) s(signature) LEFT JOIN pg_catalog.pg_proc p ON p.oid=pg_catalog.to_regprocedure(s.signature)),'relationMetadata',(SELECT jsonb_object_agg(r.name,jsonb_build_object('oid',c.oid,'namespace',c.relnamespace,'owner',c.relowner,'acl',to_jsonb(c.relacl),'options',to_jsonb(c.reloptions),'kind',c.relkind,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity) ORDER BY r.name) FROM (VALUES ('crm_audience_v2.regular_worker_deployment'),('crm_audience_v2.regular_worker_lease'),('crm_audience_v2.selection_runtime'),('crm_audience_v2.regular_delivery_campaign')) r(name) LEFT JOIN pg_catalog.pg_class c ON c.oid=pg_catalog.to_regclass(r.name)),'mutationTriggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('relation',tgrelid,'oid',oid,'enabled',tgenabled,'function',tgfoid) ORDER BY oid),'[]'::jsonb) FROM pg_catalog.pg_trigger WHERE NOT tgisinternal AND tgrelid IN('crm_audience_v2.regular_worker_deployment'::regclass,'crm_audience_v2.regular_delivery_campaign'::regclass)),
 'controls',(SELECT coalesce(jsonb_agg(to_jsonb(c) ORDER BY c.campaign_id),'[]'::jsonb) FROM crm_audience_v2.regular_delivery_campaign c WHERE c.campaign_id IN(SELECT c.campaign_id FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256)),'ownedActiveCampaignIds',(SELECT coalesce(jsonb_agg(c.campaign_id ORDER BY c.campaign_id),'[]'::jsonb) FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256),'ownedRowState',jsonb_build_object(
'campaigns',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text COLLATE "C"),'[]'::jsonb) FROM (SELECT t.* FROM public.campaigns t WHERE t.id IN(SELECT c.campaign_id FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256) ORDER BY to_jsonb(t)::text COLLATE "C" LIMIT 4097) t),
'bindings',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text COLLATE "C"),'[]'::jsonb) FROM (SELECT t.* FROM crm_audience_v2.campaign_binding t WHERE t.campaign_id IN(SELECT c.campaign_id FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256) ORDER BY to_jsonb(t)::text COLLATE "C" LIMIT 4097) t),
'bindingHistory',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text COLLATE "C"),'[]'::jsonb) FROM (SELECT t.* FROM crm_audience_v2.campaign_binding_revision t WHERE t.campaign_id IN(SELECT c.campaign_id FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256) ORDER BY to_jsonb(t)::text COLLATE "C" LIMIT 4097) t),
'dispatch',(SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.dispatch_id),'[]'::jsonb) FROM (SELECT x.* FROM public.shrigma_email_dispatch x WHERE x.flow='campaign' AND x.piece IN(SELECT 'audience-regular-v1:'||owned.campaign_id::text FROM (SELECT c.campaign_id FROM crm_audience_v2.regular_delivery_campaign c JOIN public.campaigns p ON p.id=c.campaign_id CROSS JOIN crm_audience_v2.regular_worker_deployment d WHERE d.singleton AND c.enabled AND p.type::text='regular' AND p.messenger='email' AND p.attribs#>>'{crm,policy}'='crm-campaign-v1' AND p.attribs#>>'{crm,brand}' IN('fish','aristo') AND p.status::text IN('scheduled','running','paused') AND c.worker_sha256=d.worker_sha256 AND c.runtime_sha256=d.runtime_sha256) owned) ORDER BY x.dispatch_id LIMIT 4097) x))
) AS private_transition_snapshot;
