'use strict';
// New GET integration only, using pinned original 03a dependencies and a synthetic
// transaction/query boundary. No DB, HTTP transport, credential or production proof.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const base=path.resolve(__dirname,'../../n8n/growth'),packaged=path.resolve(__dirname,'../../../inputs/n8n/growth'),deps=process.env.SHRIGMA_AUDIENCE_03A_INPUTS||packaged;
const nativeBlobs={"segment-audience-contract.js":"c3ab4b1cba35a1e044c43edc2e72c8c250f7edb3","segment-audience-review.cjs":"4c761b7d16229557bcaece4131f98027f4d3de0b","segment-shopify-facts.cjs":"440b7ffa33e4d9726ef8b030bcad6ce50bc92bd5","segment-recorded-origin.cjs":"dbde8921b402f53f138c706e20b4c2967ffdb878","segment-audience-store.cjs":"ebfc2c721bf100da6a08e72c11db9f2c4004ce99","segment-audience-api.cjs":"d4b0279e7492d25d371a974b2dd0aee5d9a7b5f6"};
for(const [file,expected]of Object.entries(nativeBlobs)){const bytes=fs.readFileSync(deps+'/'+file);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes])).digest('hex'),expected,'Original 03a input pin required: '+file);}
const H=require(deps+'/segment-audience-review.cjs'),A=require(deps+'/segment-audience-contract.js'),BaseStore=require(deps+'/segment-audience-store.cjs'),BaseAPI=require(deps+'/segment-audience-api.cjs');
function load(file,store){const m={exports:{}};vm.runInThisContext('(function(require,module,exports){'+fs.readFileSync(base+'/'+file,'utf8')+'\n})')(name=>name==='./segment-audience-store.cjs'&&store?store:require(name.startsWith('./')?deps+'/'+name.slice(2):name),m,m.exports);return m.exports;}
const Store=load('segment-audience-store.cjs'),API=load('segment-audience-api.cjs',Store),key='synthetic-key-01',actor='panel:synthetic-key-01',operationKey='synthetic-operation-01',id='00000000-0000-4000-8000-000000000001',hash='a'.repeat(64),clone=x=>JSON.parse(JSON.stringify(x));
const definition=brand=>({schema_version:A.VERSION,brand,name:'Público sintético',rule:{op:'in_list',list_id:11}});
function request(action='segmento_salvar',brand='fish'){return {acao:action,brand,idempotency_key:operationKey,...(action==='segmento_criar'?{definition:definition(brand),expected_catalog_hash:hash}:action==='segmento_salvar'?{id,expected_version:4,definition:definition(brand),expected_catalog_hash:hash}:{id,expected_version:4})};}
function journal(action='segmento_salvar',brand='fish',error){const payload=request(action,brand),segment={id,brand,name:definition(brand).name,definition:definition(brand),version:action==='segmento_criar'?1:5,archived:action==='segmento_arquivar',created_at:'2026-10-01T12:00:00.000Z',updated_at:'2026-10-07T12:00:00.000Z',updated_by:actor,semantic_context:{currency:null,timezone:null,current:false}};const response=error?{_http:error.status,_body:{error:error.code,...(error.code==='SEGMENT_VERSION_CONFLICT'?{current_version:6}:{})}}:{_http:action==='segmento_criar'?201:200,_body:{segment,transport_supported:false}};return {brand,payload,payload_hash:H.digest(payload),response};}
function boot({row=journal(),rows,auth=()=>({who:actor,caps:['draft','read_content']}),live=()=>({live_count:1,live_actor:actor}),refresh=true}={}){
 const calls=[],transactions=[],state={authCalls:0,refreshCalls:0,row,rows};
 const transaction=async(fn,options)=>{transactions.push(options);return fn({query:async(sql,values=[])=>{calls.push({sql,values:clone(values)});if(sql===Store.SQL.setup)return {rows:[]};if(sql===Store.SQL.boundary)return {rows:[{isolation:'read committed',timeout_ms:5000}]};if(sql===Store.SQL.auth){const n=++state.authCalls;return {rows:[{operator:auth(n),...live(n)}]};}if(sql===Store.SQL.operation)return {rows:state.rows??(state.row?[clone(state.row)]:[])};throw Error('Unexpected SQL at new GET boundary');}});};
 const store=Store.createAudienceStore({transaction,...(refresh?{refreshCatalog:async()=>{state.refreshCalls++;throw Error('Catalog refresh forbidden for new GET');}}:{})}),api=API.createAudienceAPI({store});
 const handle=(action,brand='fish',extra={})=>api.handle({method:'GET',request:{headers:{Authorization:'Bearer '+key},query:{acao:action,brand,...(action==='segmento_operacao_v2'?{idempotency_key:operationKey}:{}),...extra}}});
 return {state,calls,transactions,store,api,handle};
}
function noWrites(x){assert.equal(x.state.refreshCalls,0);assert(x.calls.every(c=>[Store.SQL.setup,Store.SQL.boundary,Store.SQL.auth,Store.SQL.operation].includes(c.sql)));assert(x.calls.every(c=>!/^\s*(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|GRANT|REVOKE|TRUNCATE)\b/i.test(c.sql)));assert(!x.calls.some(c=>c.sql===Store.SQL.lock||c.sql===Store.SQL.create||c.sql===Store.SQL.save||c.sql===Store.SQL.archive||c.sql===Store.SQL.receipt||c.sql===Store.SQL.revision));}
function safeError(r,status,code){assert.equal(r.status,status);assert.deepEqual(r.body,{error:code});const s=JSON.stringify(r);for(const forbidden of [actor,key,operationKey,'payload','definition','operator'])assert(!s.includes(forbidden));}
test('Fish/Aristo scope uses original draft authentication + before/after reauth, exact canonical actor hash and no journal/catalog/write',async()=>{for(const brand of ['fish','aristo']){const x=boot({auth:()=>({who:actor,caps:['draft']})}),r=await x.handle('segmento_contexto_v2',brand);assert.equal(r.status,200);assert.deepEqual(r.body,{scope:{schema:'crm-audience-writer-scope-v2',brand,actor_sha256:H.digest(actor)}});assert.notEqual(r.body.scope.actor_sha256,crypto.createHash('sha256').update(actor).digest('hex'));assert.equal(x.state.authCalls,3);assert(!JSON.stringify(r).includes(actor));assert(!x.calls.some(c=>c.sql===Store.SQL.operation));assert(x.calls.filter(c=>c.sql===Store.SQL.auth).every(c=>c.values[0]===key));noWrites(x);}});
test('scope denies missing draft and live-clock revoked/changed actor before and after construction without leaking identity',async()=>{const read=boot({auth:()=>({who:actor,caps:['read_content']})});safeError(await read.handle('segmento_contexto_v2'),403,'SEGMENT_ACCESS_DENIED');for(const at of [1,2,3])for(const kind of ['revoked','cap','actor']){const x=boot({auth:n=>({who:n===at&&kind==='actor'?'panel:other-actor':actor,caps:n===at&&kind==='cap'?['read_content']:['draft','read_content']}),live:n=>({live_count:n===at&&kind==='revoked'?0:1,live_actor:n===at&&kind==='actor'?'panel:other-actor':actor})});safeError(await x.handle('segmento_contexto_v2'),kind==='cap'?403:401,kind==='cap'?'SEGMENT_ACCESS_DENIED':'SEGMENT_UNAUTHORIZED');noWrites(x);}});
test('existing create/save/archive original journal exposed as exact V2 wrapper; inner receipt/definition/version unchanged; read_content alone sufficient',async()=>{for(const brand of ['fish','aristo'])for(const action of ['segmento_criar','segmento_salvar','segmento_arquivar']){const row=journal(action,brand),before=clone(row),x=boot({row,auth:()=>({who:actor,caps:['read_content']})}),r=await x.handle('segmento_operacao_v2',brand);assert.equal(r.status,200);assert.deepEqual(r.body,{operation:{schema:'crm-audience-operation-v2',idempotency_key:operationKey,brand,action,actor_sha256:H.digest(actor),payload_sha256:row.payload_hash,receipt:{status:row.response._http,body:row.response._body}}});assert.deepEqual(row,before);assert.equal(x.state.authCalls,4);assert.deepEqual(x.calls.find(c=>c.sql===Store.SQL.operation).values,[actor,operationKey]);const meta={...r.body.operation};delete meta.receipt;assert(!JSON.stringify(meta).includes(actor));assert(!Object.hasOwn(meta,'payload'));noWrites(x);}});
test('receipt read denies revoked/access/actor at every original authentication point and emits no original payload',async()=>{for(const at of [1,2,3,4])for(const kind of ['revoked','cap','actor']){const x=boot({auth:n=>({who:n===at&&kind==='actor'?'panel:other-actor':actor,caps:n===at&&kind==='cap'?['draft']:['read_content']}),live:n=>({live_count:n===at&&kind==='revoked'?0:1,live_actor:n===at&&kind==='actor'?'panel:other-actor':actor})});safeError(await x.handle('segmento_operacao_v2'),kind==='cap'?403:401,kind==='cap'?'SEGMENT_ACCESS_DENIED':'SEGMENT_UNAUTHORIZED');noWrites(x);}});
test('missing/cross-brand/duplicated original operation is fixed refusal with reauth after journal lookup',async()=>{for(const [options,status,code]of [[{row:null},404,'SEGMENT_OPERATION_UNCONFIRMED'],[{row:journal('segmento_salvar','aristo')},409,'SEGMENT_OPERATION_MISMATCH'],[{rows:[journal(),journal()]},503,'SEGMENT_SERVICE_UNAVAILABLE']]){const x=boot(options);safeError(await x.handle('segmento_operacao_v2'),status,code);assert.equal(x.state.authCalls,3);assert.equal(x.calls.filter(c=>c.sql===Store.SQL.operation).length,1);noWrites(x);}});
test('payload/action/brand/key/hash tamper or malformed original receipt rejected, without mutation/replay',async()=>{const changes=[r=>r.payload_hash=hash,r=>r.payload.idempotency_key='other-operation-key',r=>r.payload.brand='aristo',r=>r.payload.acao='segmento_contar',r=>r.payload.extra='caller-actor',r=>{r.payload.id=r.payload.id.toUpperCase();r.payload.id='BAD';r.payload_hash=H.digest(r.payload);},r=>r.response.extra='private',r=>r.response._body.segment.updated_by='panel:other-actor',r=>r.response._body.segment.version=99,r=>r.response._body.segment.brand='aristo',r=>r.response._body.segment.definition.brand='aristo',r=>r.response._body.segment.definition.name='Changed',r=>r.response._body.segment.semantic_context.extra='private',r=>r.response._body.segment.updated_at='bad',r=>r.response._body.segment.extra='private',r=>r.response._body.transport_supported=true,r=>r.response._http=201];for(const change of changes){const row=journal();change(row);const x=boot({row});safeError(await x.handle('segmento_operacao_v2'),503,'SEGMENT_SERVICE_UNAVAILABLE');noWrites(x);}});
test('durable original rejection statuses/bodies preserved; invalid status/action-specific errors/current version tamper refused',async()=>{const errors=[['SEGMENT_SHAPE',422],['SEGMENT_BRAND_MISMATCH',422],['SEGMENT_LIST_UNAVAILABLE',422],['SEGMENT_UNAVAILABLE',503],['SEGMENT_NOT_FOUND',404],['SEGMENT_VERSION_CONFLICT',409],['SEGMENT_ARCHIVED',409],['SEGMENT_CATALOG_CHANGED',409]];for(const [code,status]of errors){const row=journal('segmento_salvar','fish',{code,status}),x=boot({row}),r=await x.handle('segmento_operacao_v2');assert.equal(r.status,200);assert.deepEqual(r.body.operation.receipt,{status,body:row.response._body});noWrites(x);}for(const row of [journal('segmento_criar','fish',{code:'SEGMENT_VERSION_CONFLICT',status:409}),journal('segmento_arquivar','fish',{code:'SEGMENT_SHAPE',status:422}),journal('segmento_salvar','fish',{code:'SEGMENT_VERSION_CONFLICT',status:503}),journal('segmento_salvar','fish',{code:'SEGMENT_UNAUTHORIZED',status:401})])safeError(await boot({row}).handle('segmento_operacao_v2'),503,'SEGMENT_SERVICE_UNAVAILABLE');const row=journal('segmento_salvar','fish',{code:'SEGMENT_VERSION_CONFLICT',status:409});row.response._body.current_version=4;safeError(await boot({row}).handle('segmento_operacao_v2'),503,'SEGMENT_SERVICE_UNAVAILABLE');});
test('API new boundary rejects malformed scope/hash/actor/raw extras, receipt identity/types, and error details',async()=>{const requests={scope:{method:'GET',request:{headers:{Authorization:'Bearer '+key},query:{acao:'segmento_contexto_v2',brand:'fish'}}},op:{method:'GET',request:{headers:{Authorization:'Bearer '+key},query:{acao:'segmento_operacao_v2',brand:'fish',idempotency_key:operationKey}}}};const goodScope={_http:200,_body:{scope:{schema:'crm-audience-writer-scope-v2',brand:'fish',actor_sha256:H.digest(actor)}}},x=boot(),goodOp=await x.store.execute({key,request:{acao:'segmento_operacao_v2',brand:'fish',idempotency_key:operationKey}});for(const [type,good,changes]of [['scope',goodScope,[r=>r._body.scope.brand='aristo',r=>r._body.scope.actor_sha256='raw-actor',r=>r._body.scope.actor=actor,r=>r._body.extra='private']],['op',goodOp,[r=>r._body.operation.brand='aristo',r=>r._body.operation.idempotency_key='other-operation-key',r=>r._body.operation.payload_sha256='BAD',r=>r._body.operation.actor_sha256=actor,r=>r._body.operation.payload=request(),r=>r._body.operation.receipt.body.segment.extra='private',r=>r._body.operation.receipt.body.segment.definition.brand='aristo',r=>r._body.operation.receipt.body.segment.version=1,r=>r._body.operation.receipt.body.transport_supported=true]]])for(const change of changes){const value=clone(good);change(value);const api=API.createAudienceAPI({store:{execute:async()=>value}});safeError(await api.handle(requests[type]),503,'SEGMENT_SERVICE_UNAVAILABLE');}const api=API.createAudienceAPI({store:{execute:async()=>({_http:403,_body:{error:'SEGMENT_ACCESS_DENIED',current_version:7}})}});safeError(await api.handle(requests.op),503,'SEGMENT_SERVICE_UNAVAILABLE');});
test('new GETs reject POST/caller identity/extra fields and wrong scope/key at existing request boundary before querying',async()=>{for(const action of ['segmento_contexto_v2','segmento_operacao_v2']){const x=boot();const q={acao:action,brand:'fish',...(action==='segmento_operacao_v2'?{idempotency_key:operationKey}:{})};const r=await x.api.handle({method:'POST',request:{headers:{Authorization:'Bearer '+key},body:q}});safeError(r,405,'SEGMENT_METHOD_NOT_ALLOWED');assert.equal(x.calls.length,0);const extra=await x.handle(action,'fish',{actor_sha256:hash});safeError(extra,400,'SEGMENT_FIELDS');assert.equal(x.calls.length,0);const wrong=await x.handle(action,'other-brand');safeError(wrong,400,'SEGMENT_REQUEST_INVALID');assert.equal(x.calls.length,0);}const x=boot();const r=await x.handle('segmento_operacao_v2','fish',{idempotency_key:'bad'});safeError(r,400,'SEGMENT_OPERATION_ID_REQUIRED');assert.equal(x.calls.length,0);});
test('unchanged legacy SQL/auth/catalog/source exports and API parse/failure prove no SQL/corporate/RFM transplant',()=>{assert.deepEqual(Store.SQL,BaseStore.SQL);for(const k of ['readAuth','readCatalog','sourceConfig','pins','publicSegment','readDefinition','countResult'])assert.equal(Store[k].toString(),BaseStore[k].toString(),k);assert.equal(API.parse.toString(),BaseAPI.parse.toString());assert.equal(API.failure.toString(),BaseAPI.failure.toString());const source=fs.readFileSync(base+'/segment-audience-store.cjs','utf8');assert(!source.includes('corporateWriter'));assert(!source.includes('corporateAuth'));assert(!source.includes("require('./segment-shopify-rfm.cjs')"));const marker='if(writing)await query(SQL.lock,[first.actor,p.idempotency_key]);';assert.equal(Store.createAudienceStore.toString().split(marker)[1],BaseStore.createAudienceStore.toString().split(marker)[1]);assert.equal(Store.request.toString(),BaseStore.request.toString());});
