'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const sourceRoot=process.env.DELIVERY_HEALTH_PROTOCOL_SOURCE||(fs.existsSync(path.join(__dirname,'sealed-protocol-inputs/INPUT-PINS.json'))?path.join(__dirname,'sealed-protocol-inputs'):path.resolve(__dirname,'../../../inputs/tests/delivery-health-read-native/sealed-protocol-inputs'));
const runtime=process.env.DELIVERY_HEALTH_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
if(!process.env.DELIVERY_HEALTH_RUNTIME)process.env.DELIVERY_HEALTH_RUNTIME=runtime;
const fixtureFile=fs.existsSync(path.join(__dirname,'fixture.cjs'))?path.join(__dirname,'fixture.cjs'):path.join(sourceRoot,'inputs/tests/delivery-health-read-native/fixture.cjs');
const {D,fixture,inspect,baseEvidence,accelerated}=require(fixtureFile);
const sourceFile=path.join(sourceRoot,'inputs/services/dashboard-operational/native-delivery-health.cjs'),original=require(sourceFile);
const schema='shrigma-email-health-protocol-refusal-v1';
const fields=['payload','rows','schema_version','checked_at','collector','collector.last_poll_ok_at','collector.last_poll_count','collector.last_error_at','collector.last_error_code','queue','queue.checked_at','queue.visible','queue.inflight','queue.delayed','queue.error_at','pending_ingest_15min','conflicts','brands','brands.marca','brands.finalizacao_pendente','brands.entregue_sem_gravacao','brands.resultado_incerto','brands.sem_confirmacao_15min','brands.falhas_24h','brands.reclamacoes_24h'];
const reasons=['object','keys','schema-version','timestamp','count','error-code','array','brand-set','size','row-count','unknown'];
const types=['null','array','object','string','number','boolean','undefined','other'];
function assertDiagnostic(error,expected){assert.equal(error.code,'HEALTH_PROTOCOL_REFUSED');assert.equal(error.status,503);const d=D.protocolDiagnostic(error);assert(Object.isFrozen(d));const hasBrandSet=d.field==='brands'&&d.reason==='brand-set'&&d.actualType==='array';assert.deepEqual(Object.keys(d),['schema','field','reason','actualType',...(hasBrandSet?['brandSet']:[])]);if(hasBrandSet){assert(Object.isFrozen(d.brandSet));assert.deepEqual(Object.keys(d.brandSet),['length','inspection','fish','aristo','other','malformed']);}assert.equal(d.schema,schema);assert(fields.includes(d.field));assert(reasons.includes(d.reason));assert(types.includes(d.actualType));if(expected){const {brandSet,...base}=d;assert.deepEqual(base,{schema,...expected});}assert.equal(D.protocolDiagnostic(error),d);return d;}
function failPayload(raw,expected,brand='aristo'){let e;assert.throws(()=>D.validatePayload(raw,brand),error=>{e=error;assertDiagnostic(error,expected);return true;});return e;}
test('four sealed inputs verified independently (not historical14 pin assertion)',()=>{const m=JSON.parse(fs.readFileSync(path.join(sourceRoot,'INPUT-PINS.json')));assert.equal(m.files.length,4);for(const f of m.files){const b=fs.readFileSync(path.join(sourceRoot,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex'),f.githubBlobSha1);}});
test('SQL/constants/queryHash and entire session core byte preserved except row diagnostic',()=>{for(const name of ['READ_SQL','queryHash','PURPOSE','RESOURCE','PEER','BEGIN','ROLLBACK'])assert.deepEqual(D[name],original[name]);const before=fs.readFileSync(sourceFile,'utf8'),after=fs.readFileSync(path.join(runtime,'native-delivery-health.cjs'),'utf8');const a='function createDeliveryHealthRead';const end='module.exports=';const expected=before.slice(before.indexOf(a),before.indexOf(end)).replace("if(evidenceRows.length!==1)throw error('HEALTH_PROTOCOL_REFUSED');","if(evidenceRows.length!==1)throw protocolRefused('rows','row-count',evidenceRows);");assert.equal(after.slice(after.indexOf(a),after.indexOf(end)),expected);const helper='const own=';const iso='function iso(';assert.equal(before.slice(before.indexOf(helper),before.indexOf(iso)),after.slice(after.indexOf(helper),after.indexOf(iso)));});
test('ordinary valid schema/date/nullable/brand cases exactly equivalent to sealed validator',()=>{for(const brand of ['fish','aristo'])for(const modify of [v=>v,v=>{v.brands.reverse();return v;},v=>{v.queue.visible=0;v.queue.inflight=Number.MAX_SAFE_INTEGER;v.collector.last_poll_count=0;return v;},v=>{v.collector.last_error_code='UNCLASSIFIED_RUNTIME_ERROR';v.collector.last_poll_ok_at=v.checked_at;return v;},v=>{Object.setPrototypeOf(v,null);Object.setPrototypeOf(v.collector,null);return v;}]){const v=modify(baseEvidence());assert.deepEqual(D.validatePayload(v,brand),original.validatePayload(v,brand));}});
const cases=[
 ['payload null',()=>null,'payload','object','null'],['payload array',()=>[],'payload','object','array'],['payload string',()=>'<html>private</html>','payload','object','string'],
 ['payload keys',v=>({...v,privateCustomerName:'secret'}),'payload','keys','object'],['schema',v=>({...v,schema_version:2}),'schema_version','schema-version','number'],['timestamp',v=>({...v,checked_at:'2026-02-30T12:00:00Z'}),'checked_at','timestamp','string'],
 ['collector null',v=>({...v,collector:null}),'collector','object','null'],['collector keys',v=>({...v,collector:{...v.collector,privatePassword:'secret'}}),'collector','keys','object'],
 ['poll date',v=>({...v,collector:{...v.collector,last_poll_ok_at:false}}),'collector.last_poll_ok_at','timestamp','boolean'],['poll count',v=>({...v,collector:{...v.collector,last_poll_count:-1}}),'collector.last_poll_count','count','number'],['error date',v=>({...v,collector:{...v.collector,last_error_at:'PRIVATE'}}),'collector.last_error_at','timestamp','string'],['error code',v=>({...v,collector:{...v.collector,last_error_code:'SQL password private@example.invalid'}}),'collector.last_error_code','error-code','string'],
 ['queue null',v=>({...v,queue:null}),'queue','object','null'],['queue keys',v=>({...v,queue:{...v.queue,privateQueueName:'secret'}}),'queue','keys','object'],['queue date',v=>({...v,queue:{...v.queue,checked_at:0}}),'queue.checked_at','timestamp','number'],['queue error',v=>({...v,queue:{...v.queue,error_at:'bad'}}),'queue.error_at','timestamp','string'],
 ['visible',v=>({...v,queue:{...v.queue,visible:'0'}}),'queue.visible','count','string'],['inflight',v=>({...v,queue:{...v.queue,inflight:NaN}}),'queue.inflight','count','number'],['delayed',v=>({...v,queue:{...v.queue,delayed:undefined}}),'queue.delayed','count','undefined'],
 ['pending',v=>({...v,pending_ingest_15min:null}),'pending_ingest_15min','count','null'],['conflicts',v=>({...v,conflicts:Infinity}),'conflicts','count','number'],
 ['brands array',v=>({...v,brands:{}}),'brands','array','object'],['brands missing',v=>({...v,brands:[]}),'brands','brand-set','array'],['brands duplicate',v=>({...v,brands:[v.brands[0],v.brands[0]]}),'brands.marca','brand-set','string'],['foreign marca',v=>({...v,brands:[v.brands[0],{...v.brands[1],marca:'PRIVATE_UNKNOWN_BRAND'}]}),'brands.marca','brand-set','string'],['brand keys',v=>({...v,brands:[v.brands[0],{...v.brands[1],email:'private@example.invalid'}]}),'brands','keys','object']
];
for(const [name,modify,field,reason,actualType] of cases)test('typed refusal '+name+' keeps acceptance unchanged',()=>{const v=modify(baseEvidence());assert.throws(()=>original.validatePayload(v,'aristo'),{code:'HEALTH_PROTOCOL_REFUSED',status:503});const e=failPayload(v,{field,reason,actualType});const text=JSON.stringify(D.protocolDiagnostic(e));assert.doesNotMatch(text,/privateCustomer|privatePassword|privateQueue|PRIVATE|password|private@|<html>/);});
for(const metric of ['finalizacao_pendente','entregue_sem_gravacao','resultado_incerto','sem_confirmacao_15min','falhas_24h','reclamacoes_24h'])test('metric canonical field '+metric,()=>{const v=baseEvidence();v.brands[1][metric]=null;assert.throws(()=>original.validatePayload(v,'aristo'));failPayload(v,{field:'brands.'+metric,reason:'count',actualType:'null'});});
for(const [value,actualType] of [[null,'null'],[[],'array'],[{},'object'],['private','string'],[2,'number'],[true,'boolean'],[undefined,'undefined'],[Symbol('PRIVATE'),'other'],[1n,'other'],[()=>{},'other']])test('finite type only '+actualType+' '+typeof value,()=>{failPayload({...baseEvidence(),schema_version:value},{field:'schema_version',reason:'schema-version',actualType});});
test('getters/toJSON/prototype/symbol/hidden properties refuse without evaluation or names',()=>{
 let calls=0;const getter=()=>{calls++;throw Error('PRIVATE');};
 const variations=[v=>{Object.defineProperty(v,'checked_at',{get:getter,enumerable:true});return [v,'payload','keys'];},v=>{Object.defineProperty(v.collector,'last_poll_count',{get:getter,enumerable:true});return [v,'collector','keys'];},v=>{Object.defineProperty(v,'toJSON',{get:getter,enumerable:true});return [v,'payload','keys'];},v=>{Object.setPrototypeOf(v,{toJSON:getter});return [v,'payload','object'];},v=>{v[Symbol('private')]='SECRET';return [v,'payload','keys'];},v=>{Object.defineProperty(v.queue,'private',{value:'SECRET'});return [v,'queue','keys'];},v=>{Object.defineProperty(v.brands,'0',{get:getter});return [v,'brands','array'];},v=>{v.brands.toJSON=getter;return [v,'brands','array'];},v=>{Object.setPrototypeOf(v.brands,{});return [v,'brands','array'];}];
 for(const modify of variations){const [v,field,reason]=modify(baseEvidence());const e=failPayload(v,{field,reason,actualType:field==='brands'&&reason==='array'?'array':'object'});assert.doesNotMatch(JSON.stringify(D.protocolDiagnostic(e)),/PRIVATE|SECRET|private/);}assert.equal(calls,0);
});
test('dangerous/revoked proxies never execute any trap',()=>{let calls=0;const trap=()=>{calls++;throw Error('SECRET');};const handler={get:trap,getPrototypeOf:trap,ownKeys:trap,getOwnPropertyDescriptor:trap};const p=new Proxy(baseEvidence(),handler);failPayload(p,{field:'payload',reason:'object',actualType:'other'});const v=baseEvidence();v.collector=new Proxy(v.collector,handler);failPayload(v,{field:'collector',reason:'object',actualType:'other'});const w=baseEvidence();w.brands=new Proxy(w.brands,handler);failPayload(w,{field:'brands',reason:'array',actualType:'other'});const revoked=Proxy.revocable({},handler);revoked.revoke();failPayload(revoked.proxy,{field:'payload',reason:'object',actualType:'other'});assert.equal(calls,0);});
test('first failure deterministic and diagnostic unavailable for forged/arbitrary errors',()=>{const v={...baseEvidence(),schema_version:9,checked_at:'PRIVATE',conflicts:-1};for(let i=0;i<3;i++)failPayload(v,{field:'schema_version',reason:'schema-version',actualType:'number'});for(const e of [null,undefined,0,'HEALTH_PROTOCOL_REFUSED',new Error('HEALTH_PROTOCOL_REFUSED'),{code:'HEALTH_PROTOCOL_REFUSED',status:503},{schema,field:'payload',reason:'object',actualType:'null'},new Proxy({}, {get(){assert.fail('trap');}})])assert.equal(D.protocolDiagnostic(e),null);});
for(const count of [0,2])test('read rows '+count+' yields bounded row-count diagnostic once and closes',async()=>{const f=fixture({result:(sql,r)=>sql===D.READ_SQL?{...r,rows:Array.from({length:count},()=>r.rows[0]),rowCount:count}:r});await assert.rejects(inspect(f),e=>{assertDiagnostic(e,{field:'rows',reason:'row-count',actualType:'array'});return true;});assert.equal(f.calls.filter(q=>q===D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);});
test('payload read refusal same diagnostic once and closes without retry',async()=>{const f=fixture({evidence:{conflicts:'PRIVATE_SQL'}});await assert.rejects(inspect(f),e=>{assertDiagnostic(e,{field:'conflicts',reason:'count',actualType:'string'});return true;});assert.equal(f.calls.filter(q=>q===D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);});
for(const opts of [{deny:'read'},{wrongAck:D.READ_SQL},{doubleAck:D.BEGIN},{queryThrow:D.READ_SQL},{peer:{engine:160000}}])test('nonprotocol error has no payload diagnostic '+Object.keys(opts),async()=>{const f=fixture(opts);await assert.rejects(inspect(f),e=>{assert.notEqual(e.code,'HEALTH_PROTOCOL_REFUSED');assert.equal(D.protocolDiagnostic(e),null);return true;});assert(f.clients.every(c=>c.ends===1));});
for(const opt of ['endThrow','noEndEvent','endHang'])test('closure '+opt+' supersedes payload diagnostic, refuses next read',async()=>{const X=accelerated(),f=fixture({D:X.D,evidence:{conflicts:'PRIVATE'},[opt]:true});await assert.rejects(inspect(f),e=>{assert.notEqual(e.code,'HEALTH_PROTOCOL_REFUSED');assert.equal(X.D.protocolDiagnostic(e),null);return true;});assert.equal(f.calls.filter(q=>q===X.D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);await assert.rejects(inspect(f),e=>{assert.equal(X.D.protocolDiagnostic(e),null);return true;});});

test('diagnostic is module-private, cannot transplant original-module or cloned errors',()=>{let originalError;assert.throws(()=>original.validatePayload(null,'aristo'),e=>{originalError=e;return true;});assert.equal(D.protocolDiagnostic(originalError),null);const e=failPayload(null,{field:'payload',reason:'object',actualType:'null'});assert.equal(D.protocolDiagnostic({...e}),null);assert.equal(D.protocolDiagnostic(Object.create(e)),null);});
test('successful original read remains unchanged, no attached protocol diagnostic',async()=>{const f=fixture(),v=await inspect(f);assert.equal(D.protocolDiagnostic(v),null);assert.equal(v.brand,'aristo');assert.equal(v.operational,false);assert.equal(f.calls.filter(q=>q===D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);assert.deepEqual(f.trace,['gate:connect','construct','connect','peer','gate:read','begin','read','rollback','end','gate:release']);});
