'use strict';
// Explicit Linux CI only. No env/client/tests/sockets start when imported.
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const A=require('./activation.cjs'),R=require('./runtime.cjs'),{createJournal}=require('./journal.cjs'),S=require('./supervisor.cjs'),{guard}=require('./oci-guard.cjs');
const F=require('../../crm-manager-install-review/native-fixture.cjs');
const CONNECT=Object.freeze({host:'comunicacao_postgres',port:5432,database:'listmonk',user:'postgres',ssl:false,application_name:'shrigma-read-runtime-native-oci-only',connectionTimeoutMillis:5000,query_timeout:6000});
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
function prepare(){return {schema:'crm-manager-provision-request-v1',issuerId:A.SPEC.issuerId,namespaceId:A.SPEC.namespaceId,action:'prepare_read',operationId:crypto.randomUUID(),userId:crypto.randomUUID(),lifecycleId:crypto.randomUUID(),owner:'synthetic-pilot@oaristocrata.com',principalId:'dcrm-'+crypto.randomBytes(16).toString('hex'),keySha256:sha(crypto.randomBytes(32)),generation:1,expectedGeneration:0,area:'growth',slot:'crm-panel-read',role:'manager',caps:['read_content','list_history','submission'],candidateTtlMs:600000,lifetimeMs:1209600000};}
function revoke(q){return {schema:q.schema,issuerId:q.issuerId,namespaceId:q.namespaceId,action:'revoke_read',operationId:crypto.randomUUID(),userId:q.userId,lifecycleId:q.lifecycleId,owner:q.owner};}
function credential(){const password=crypto.randomBytes(32).toString('base64url'),salt=crypto.randomBytes(16),salted=crypto.pbkdf2Sync(password,salt,4096,32,'sha256'),client=crypto.createHmac('sha256',salted).update('Client Key').digest(),stored=crypto.createHash('sha256').update(client).digest(),server=crypto.createHmac('sha256',salted).update('Server Key').digest();return {password,verifier:'SCRAM-SHA-256$4096:'+salt.toString('base64')+'$'+stored.toString('base64')+':'+server.toString('base64')};}
const makeIntent=action=>({schema:'crm-manager-read-runtime-intent-v1',operationId:crypto.randomUUID(),credentialIntentId:crypto.randomUUID(),action,fromPhase:action==='stage'?'empty':action==='activate'?'staged':'active'});
async function checked(t,name,fn){let failed=false;await t.test(name,async()=>{try{await fn();}catch{failed=true;throw Error('READ_RUNTIME_NATIVE_OCI_PROOF_FAILED');}});if(failed)throw Error('READ_RUNTIME_NATIVE_OCI_PROOF_FAILED');}
async function prove(t){
 guard();assert.equal(require('pg/package.json').version,'8.13.1');const pg=require('pg');
 let password=process.env.PG_ADMIN_PASSWORD;delete process.env.PG_ADMIN_PASSWORD;assert.equal(typeof password,'string');assert.ok(password.length>=40);
 const ownCluster=process.env.READ_RUNTIME_CLUSTER;const secrets=credential();let baseline,db,writes=0,firstBudget=false,logSeen=false;
 class QuietClient extends pg.Client{constructor(c){super(c);this.on('error',()=>{});}}
 async function client(user='postgres',pw=password){const c=new QuietClient({...CONNECT,user,password:pw});await c.connect();const p=c.connectionParameters;assert.deepEqual({host:p.host,port:p.port,database:p.database,user:p.user,ssl:p.ssl},{host:CONNECT.host,port:5432,database:'listmonk',user,ssl:false});const row=(await c.query("SELECT current_database() AS database,current_user AS actor,session_user AS session_role,current_setting('server_version_num') AS version,inet_server_port() AS port,current_setting('cluster_name') AS cluster,current_setting('ssl') AS ssl,coalesce((SELECT ssl FROM pg_stat_ssl WHERE pid=pg_backend_pid()),true) AS session_ssl")).rows[0];assert.deepEqual(row,{database:'listmonk',actor:user,session_role:user,version:'170010',port:5432,cluster:ownCluster,ssl:'off',session_ssl:false});return c;}
 async function connect({dropAck=false}={}){const c=await client();return {async query(text,args){const out=await c.query(text,args);if(text===R.SESSION_SQL)firstBudget=out.rows[0].budget_ok===true;if(text.startsWith('BEGIN'))assert.equal(firstBudget,true);if(text.startsWith("SET LOCAL log_statement='none'"))logSeen=true;if(text.includes("set_config('shrigma.read.scram'"))assert.equal(logSeen,true);if(text.includes('/* MUTATION START */'))writes++;if(text==='COMMIT;'&&dropAck)throw Error('SYNTHETIC_ACK_DROPPED_AFTER_REAL_COMMIT');return out;},end:()=>c.end()};}
 async function snapshot(){return {keys:(await db.query('SELECT * FROM public.crm_dash_chave ORDER BY chave')).rows,permissions:(await db.query('SELECT * FROM public.shrigma_panel_permission_v1 ORDER BY principal_id,area')).rows,cache:(await db.query('SELECT * FROM public.dash_payload_cache ORDER BY painel')).rows,functions:(await db.query("SELECT oid,prosrc,proacl,proconfig FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname NOT LIKE 'shrigma_crm_manager_%' ORDER BY oid")).rows,defaults:(await db.query('SELECT * FROM pg_default_acl ORDER BY oid')).rows};}
 async function rpc(name,q){assert.ok(['prepare','revoke','status'].includes(name));const c=await client(A.SPEC.loginRole,secrets.password);try{return (await c.query('SELECT public.shrigma_crm_manager_'+name+'_v1($1::jsonb) AS body',[canonical(q)])).rows[0].body;}finally{await c.end();}}
 async function observe(action,mode,q){
  // Actual frozen CLI child + separate durable reader + real local GET/status.
  const env={READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:mode,READ_ACTIVATION_APPROVED_ACTION:mode==='execute'?action:'readonly-reconcile',READ_ACTIVATION_ACTION:action,READ_ACTIVATION_OPERATION_ID:q.operationId,READ_CREDENTIAL_INTENT_ID:q.credentialIntentId,READ_ACTIVATION_FROM_PHASE:q.fromPhase,PG_ADMIN_PASSWORD:password};if(action!=='disable')env.READ_SERVICE_SCRAM=secrets.verifier;
  const server=S.startCli(env);assert.ok(server);assert.equal(env.PG_ADMIN_PASSWORD,undefined);assert.equal(env.READ_SERVICE_SCRAM,undefined);
  function get(){return new Promise((resolve,reject)=>{let raw='',bytes=0;const req=http.get({host:'127.0.0.1',port:8099,path:'/status',timeout:1500},res=>{res.on('data',b=>{bytes+=b.length;if(bytes>2048)req.destroy();else raw+=b.toString('utf8');});res.on('end',()=>{try{assert.equal(res.statusCode,200);resolve(JSON.parse(raw));}catch{reject(Error('PROOF_REFUSED'));}});res.on('error',()=>reject(Error('PROOF_REFUSED')));});req.on('timeout',()=>req.destroy());req.on('error',()=>reject(Error('PROOF_REFUSED')));});}
  try{let status;for(let n=0;n<150;n++){try{status=await get();if(status.state!=='pending')break;}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(status&&status.state!=='pending');assert.deepEqual(Object.keys(status),['schema','action','state','childExitConfirmed','proofBarrierConfirmed','proof']);assert.equal(JSON.stringify(status).includes(password),false);assert.equal(JSON.stringify(status).includes(secrets.verifier),false);
   await new Promise((resolve,reject)=>require('node:child_process').execFile(process.execPath,['--max-old-space-size=16',path.join(__dirname,'health.cjs')],{env:{PATH:'/usr/local/bin:/usr/bin:/bin',NODE_PATH:'/app/node_modules'},timeout:2500,maxBuffer:2048},e=>e?reject(Error('HEALTH_REFUSED')):resolve()));return status;
  }finally{await new Promise(r=>server.close(r));}
 }
 try{
  db=await client();
  await checked(t,'OCI fixed real SCRAM PG17.10 transport/empty guard before canonical SQL',async()=>{
   const initial=(await db.query("SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND c.relkind IN ('r','p','v','m','S','f')) AS relations,(SELECT count(*)::int FROM pg_roles WHERE rolname IN ('central_leitor','crm_manager_function_owner_v1','crm_manager_provisioner')) AS fixture_roles,(SELECT count(*)::int FROM pg_default_acl) AS default_acls,(SELECT count(*)::int FROM pg_proc WHERE pronamespace='public'::regnamespace) AS public_functions,(SELECT count(*)::int FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname NOT IN ('public','information_schema')) AS extra_schemas")).rows[0];assert.deepEqual(initial,{relations:0,fixture_roles:0,default_acls:0,public_functions:0,extra_schemas:0});
   await db.query("REVOKE CREATE ON SCHEMA public FROM PUBLIC;CREATE ROLE central_leitor NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;CREATE TABLE public.crm_dash_chave(chave text PRIMARY KEY,painel text NOT NULL CHECK(painel IN ('cx','growth','influs','organico','todos')),dono text NOT NULL,ativo boolean NOT NULL DEFAULT true,revogada_em timestamptz,ultimo_uso timestamptz,usos integer NOT NULL DEFAULT 0,chave_hash text,chave_hash_curta text,expira_em timestamptz,criado_em timestamptz NOT NULL DEFAULT now());CREATE UNIQUE INDEX crm_dash_chave_curta_uq ON public.crm_dash_chave(chave_hash_curta) WHERE chave_hash_curta IS NOT NULL;CREATE TABLE public.shrigma_template_key_v2(active boolean,key_hash text,actor text,capabilities jsonb);CREATE TABLE public.dash_payload_cache(painel text PRIMARY KEY,payload jsonb,gerado_em timestamptz);REVOKE ALL ON public.crm_dash_chave,public.shrigma_template_key_v2,public.dash_payload_cache FROM PUBLIC;");
   for(const name of ['auth.sql','operator.sql','short.sql','read.sql'])await db.query(F.source(name));
   await db.query('INSERT INTO public.crm_dash_chave(chave,painel,dono,chave_hash,chave_hash_curta) VALUES($1,$2,$3,$4,$5)',['synthetic-legacy-admin','todos','legacy-admin@example.test',sha('synthetic-legacy-only'),sha('synthetic-legacy-short')]);
   await db.query(`INSERT INTO public.shrigma_panel_permission_v1 VALUES('synthetic-legacy-admin','growth','["crm_campaign_write","crm_send"]'),('synthetic-legacy-admin','influs','["all"]');INSERT INTO public.dash_payload_cache VALUES('growth','{"synthetic":true}',now());GRANT USAGE ON SCHEMA public TO central_leitor;GRANT SELECT ON public.crm_dash_chave,public.shrigma_panel_permission_v1,public.dash_payload_cache TO central_leitor;ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO central_leitor;CREATE EXTENSION pgcrypto VERSION '1.3';`);
   baseline=await snapshot();await db.query(F.source('installer.sql'));
  });
  const journal=createJournal('/runtime-proof'),stage=makeIntent('stage');
  await checked(t,'OCI actual runtime one COMMIT dropped; wrong verifier holds; fresh read-only same-intent confirms',async()=>{
   const r=R.createRuntime({journal,connect:()=>connect({dropAck:true})});assert.equal((await r.execute(stage,{verifier:secrets.verifier})).state,'outcome_unknown');assert.equal(writes,1);assert.equal(firstBudget,true);
   const resumed=R.createRuntime({journal,connect:()=>connect()});assert.equal((await resumed.reconcile(stage,{verifier:credential().verifier})).state,'outcome_unknown');const out=await resumed.reconcile(stage,{verifier:secrets.verifier});assert.equal(out.state,'confirmed');assert.equal(out.commitAck,false);assert.equal(writes,1);await assert.rejects(resumed.execute(stage,{verifier:secrets.verifier}));
  });
  await checked(t,'OCI frozen supervisor child0 + pinned secretless reader + GET closed proof + health',async()=>{const status=await observe('stage','reconcile',stage);assert.equal(status.state,'verified');assert.equal(status.childExitConfirmed,true);assert.equal(status.proofBarrierConfirmed,true);assert.equal(status.proof.commitAck,false);});
  const status={schema:'crm-manager-provision-request-v1',issuerId:A.SPEC.issuerId,namespaceId:A.SPEC.namespaceId,action:'status',operationId:crypto.randomUUID(),expectedRequestSha256:'0'.repeat(64)};
  await checked(t,'OCI stage inactive rejects RPC; activate CLI+GET verifies no PREP/statusfalse and exact SCRAM',async()=>{
   const wrong=new QuietClient({...CONNECT,user:A.SPEC.loginRole,password:secrets.password+'wrong'});try{await assert.rejects(wrong.connect(),e=>e?.code==='28P01');}finally{try{await wrong.end();}catch{}}
   assert.equal((await rpc('status',status)).code,'ISSUER_DENIED');assert.equal((await observe('activate','execute',makeIntent('activate'))).state,'verified');assert.equal((await rpc('status',status)).found,false);assert.equal((await db.query('SELECT count(*)::int AS n FROM public.shrigma_crm_manager_operation_v1')).rows[0].n,0);
  });
  const q=prepare();
  await checked(t,'OCI READ3 live candidate refuses disable; observer is healthy but outcome unknown',async()=>{assert.equal((await rpc('prepare',q)).state,'prepared');assert.deepEqual((await db.query('SELECT caps FROM public.shrigma_panel_permission_v1 WHERE principal_id=$1',[q.principalId])).rows,[{caps:['read_content','list_history','submission']}]);const out=await observe('disable','execute',makeIntent('disable'));assert.equal(out.state,'outcome_unknown');assert.equal(out.childExitConfirmed,false);assert.equal(out.proof,null);});
  await checked(t,'OCI revoke then disable CLI confirms; receipts/legacy rows preserved, NOLOGIN enforced',async()=>{
   assert.equal((await rpc('revoke',revoke(q))).state,'revoked');const receipts=(await db.query('SELECT operation_id,request_sha256,response FROM public.shrigma_crm_manager_operation_v1 ORDER BY operation_id')).rows;
   const out=await observe('disable','execute',makeIntent('disable'));assert.equal(out.state,'verified');assert.equal(out.proof.phase,'disabled');assert.equal(out.proof.credentialBound,false);assert.deepEqual((await db.query('SELECT operation_id,request_sha256,response FROM public.shrigma_crm_manager_operation_v1 ORDER BY operation_id')).rows,receipts);
   const saved=await snapshot();saved.keys=saved.keys.filter(k=>k.chave!==q.principalId);saved.permissions=saved.permissions.filter(p=>p.principal_id!==q.principalId);assert.deepEqual(saved,baseline);
   const denied=new QuietClient({...CONNECT,user:A.SPEC.loginRole,password:secrets.password});try{await assert.rejects(denied.connect(),e=>e?.code==='28000');}finally{try{await denied.end();}catch{}}
  });
 }finally{password='';secrets.password='';secrets.verifier='';try{await db?.end();}catch{}}
}
if(require.main===module)test('READ runtime in a NEW isolated native PG17 OCI fixture',{timeout:120000},async t=>{try{await prove(t);}catch{throw Error('READ_RUNTIME_NATIVE_OCI_PROOF_FAILED');}});
module.exports=Object.freeze({prove,CONNECT});
