'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const crypto=require('node:crypto'),vm=require('node:vm');
const CONTEXT_MANIFEST_PIN={"bytes": 9485, "sha256": "1cad0f6aa9845368c99ce5fdc2bd2ac91096beca10212157dcca96383f7c11f6", "gitBlobSha1": "a3457494855cbf1d0bf488e102bbc4a96c16662e"};
const CONTEXT_ENTRY_COUNT=35;
function publicContext(root){try{
 if(typeof root!=='string'||!path.isAbsolute(root)||path.resolve(root)!==root||root.split(path.sep).includes('.private'))throw Error();
 function physical(file){let current=path.parse(file).root;for(const part of file.split(path.sep).filter(Boolean)){current=path.join(current,part);const s=fs.lstatSync(current);if(s.isSymbolicLink()||(current===file?(!s.isFile()||s.nlink!==1):!s.isDirectory()))throw Error();}if(fs.realpathSync(file)!==file)throw Error();}
 function read(relative,pin){if(path.isAbsolute(relative)||relative.split('/').some(x=>!x||x==='.'||x==='..'||x==='.private'))throw Error();const f=path.join(root,relative);physical(f);const b=fs.readFileSync(f);if(b.length!==pin.bytes||crypto.createHash('sha256').update(b).digest('hex')!==pin.sha256||crypto.createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex')!==pin.gitBlobSha1)throw Error();return b;}
 const manifest=JSON.parse(read('MANIFEST.json',CONTEXT_MANIFEST_PIN));if(!Array.isArray(manifest.files)||manifest.files.length!==CONTEXT_ENTRY_COUNT||new Set(manifest.files.map(e=>e.path)).size!==CONTEXT_ENTRY_COUNT)throw Error();
 for(const entry of manifest.files)read(entry.path,entry);
 const result=manifest.files.find(e=>e.path==='context/node-postgres-8.13.1/result.js');if(!result||result.bytes!==2713||result.sha256!=='4eb2296d33c87377e4326e3dda80a204dba86bac60851070558c5845252a0dae')throw Error();
 return read(result.path,result).toString('utf8');
 }catch{throw Object.assign(new Error('BORROWED_PUBLIC_CONTEXT_REFUSED'),{code:'BORROWED_PUBLIC_CONTEXT_REFUSED'});}}
// Mandatory before interpreting primary driver reference; no fallback or optional skip.
const publicRoot=process.env.B1_BORROWED_PROTOCOL_CONTEXT;
const primaryResult=publicContext(publicRoot);
const {run}=require('./borrowed-pg17-protocol.cjs');
function client(pid){const calls={query:0,connect:0,end:0,release:0};return {calls,c:{processID:pid,_connected:true,_queryable:true,_ending:false,connection:{},query:async()=>{calls.query++;throw Error('PRIVATE_DETAIL actor secret path');},...Object.fromEntries(['connect','end','release'].map(method=>[method,()=>{calls[method]++;throw Error('PRIVATE_DETAIL ownership');}]))}};}
const assertNoCalls=pair=>pair.forEach(x=>assert.deepEqual(x.calls,{query:0,connect:0,end:0,release:0}));
function closed(result,code){assert.equal(result.code,code);assert.equal(result.executed,false);assert.equal(result.sourceOnly,true);assert.equal(result.operational,false);assert.equal(result.completeReservation,false);assert.equal(result.nativeNetworkAckProof,false);assert.equal(result.productionDurabilityProved,false);assert(!JSON.stringify(result).includes('PRIVATE_DETAIL'));assert(!('cause' in result));assert(!('stack' in result));assert(Object.isFrozen(result));}
test('borrowed protocol: import/default OFF never queries or claims PG execution',async()=>{const pair=[client(101),client(102)];closed(await run(),'BORROWED_PG17_PROOF_DISABLED');closed(await run({clients:pair.map(x=>x.c),admitTest:async()=>{throw Error('PRIVATE_DETAIL');}}),'BORROWED_PG17_PROOF_DISABLED');assertNoCalls(pair);});
test('borrowed protocol: incomplete/distinct/connected/client/admission requirements refuse before SQL',async()=>{closed(await run(null),'BORROWED_PG17_PROOF_REFUSED');closed(await run(Object.defineProperty({},'enabled',{enumerable:true,get(){throw Error('PRIVATE_DETAIL getter must not run');}})),'BORROWED_PG17_PROOF_REFUSED');for(const mutate of [o=>delete o.clients,o=>o.clients.pop(),o=>o.clients[1]=o.clients[0],o=>delete o.admitTest,o=>delete o.sourceDirectory,o=>o.scenario='invented',o=>o.clients[0]._connected=false,o=>o.clients[0]._ending=true,o=>o.clients[0].totalCount=2,o=>delete o.clients[0].processID]){const pair=[client(101),client(102)],o={enabled:true,clients:pair.map(x=>x.c),sourceDirectory:'/public/source',scenario:'registration-race',admitTest:async()=>{throw Error('PRIVATE_DETAIL');}};mutate(o);closed(await run(o),'BORROWED_PG17_PROOF_REFUSED');assertNoCalls(pair);}});
test('borrowed protocol: caller flags cannot admit custody; private admission errors are closed and ownership preserved',async()=>{for(const admission of [async()=>{throw Error('PRIVATE_DETAIL');},async()=>true,async()=>({enabled:true,isolated:true}),async()=>({isolated:true,noExternalTransaction:true,reservedRowsReady:true,schemaInstalled:true,extra:'PRIVATE_DETAIL'}),async()=>({isolated:true,noExternalTransaction:false,reservedRowsReady:true,schemaInstalled:true})]){const pair=[client(101),client(102)],original=pair.map(x=>x.c);closed(await run({enabled:true,clients:original,sourceDirectory:'/public/source',scenario:'ack-hook',admitTest:admission}),'BORROWED_PG17_PROOF_REFUSED');assertNoCalls(pair);assert.equal(original[0],pair[0].c);assert.equal(original[1],pair[1].c);}});
test('borrowed protocol: missing/relative/incomplete public source refuses without imports or SQL after test admission',async()=>{const temp=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'borrowed-pg-negative-'));try{for(const sourceDirectory of ['relative',path.join(temp,'missing'),temp]){const pair=[client(101),client(102)],before=Object.keys(require.cache);closed(await run({enabled:true,clients:pair.map(x=>x.c),sourceDirectory,scenario:'pending-hook',admitTest:async()=>({isolated:true,noExternalTransaction:true,reservedRowsReady:true,schemaInstalled:true})}),'BORROWED_PG17_PROOF_REFUSED');assertNoCalls(pair);assert.deepEqual(Object.keys(require.cache),before);}}finally{fs.rmSync(temp,{recursive:true,force:true});}});
test('borrowed patch: own enumerable data slots required before custody; getters never run',async()=>{for(const make of [(a)=>{const p=[a];p.length=2;return p;},(a,b)=>{const p=[a];p.length=2;const proto=Object.create(Array.prototype);Object.defineProperty(proto,'1',{value:b,enumerable:true});Object.setPrototypeOf(p,proto);return p;},(a,b)=>{const p=[a,b];Object.defineProperty(p,'1',{value:b,enumerable:false});return p;},(a,b)=>{const p=[a,b];Object.defineProperty(p,'0',{enumerable:true,get(){throw Error('getter must never run');}});return p;}]){const pair=[client(101),client(102)];let admissions=0;const before=Object.keys(require.cache);closed(await run({enabled:true,clients:make(pair[0].c,pair[1].c),sourceDirectory:'/public/source-unused',scenario:'registration-race',admitTest:async()=>{admissions++;throw Error('unexpected custody');}}),'BORROWED_PG17_PROOF_REFUSED');assert.equal(admissions,0);assertNoCalls(pair);assert.deepEqual(Object.keys(require.cache),before);}});
test('borrowed patch: pinned primary Result SHOW null accepted and SELECT retains count/type/session guards',async()=>{let typeCalls=0;const slot={exports:{}};vm.runInNewContext(primaryResult,{module:slot,require(name){assert.equal(name,'pg-types');return {getTypeParser(){typeCalls++;throw Error('unused parser');}};}},{filename:'public-pg-result-pure.js'});const Result=slot.exports;
 const line=fs.readFileSync(path.join(__dirname,'borrowed-pg17-protocol.cjs'),'utf8').split('\n').find(x=>x.startsWith('async function metadata(c)'));assert(line);const pure={VERSION:'SHOW server_version_num',SESSION:'SELECT current_database() AS database_name, pg_backend_pid() AS backend_pid',reject(){throw Error('BORROWED_METADATA_PURE_REFUSED');}};vm.runInNewContext('function expect(v){if(!v)reject();}\n'+line+'\nthis.metadata=metadata;',pure);
 const show=()=>{const r=new Result();r.addRow({server_version_num:'170005'});r.addCommandComplete({text:'SHOW'});return r;},select=()=>{const r=new Result();r.addRow({database_name:'synthetic_parser_only',backend_pid:101});r.addCommandComplete({text:'SELECT 1'});return r;};let calls=0;const value=await pure.metadata({processID:101,query:async sql=>{calls++;return sql===pure.VERSION?show():select();}});assert.equal(value.version,170005);assert.equal(value.pid,101);assert.equal(calls,2);assert.equal(show().rowCount,null);assert.equal(select().rowCount,1);
 for(const change of [(s)=>s.rowCount=1,(s)=>s.rows[0].server_version_num=170005,(s,t)=>t.rowCount=null,(s,t)=>t.rows[0].backend_pid=102,(s,t)=>t.rows[0].backend_pid='101']){const s=show(),t=select();change(s,t);await assert.rejects(pure.metadata({processID:101,query:async sql=>sql===pure.VERSION?s:t}),/BORROWED_METADATA_PURE_REFUSED/);}assert.equal(typeCalls,0);
});
test('borrowed patch: missing or mutated public context fails before reference interpretation with no fallback',()=>{assert.throws(()=>publicContext(undefined),e=>e.code==='BORROWED_PUBLIC_CONTEXT_REFUSED'&&e.message===e.code&&!e.cause);const {spawnSync}=require('node:child_process'),env={...process.env};delete env.B1_BORROWED_PROTOCOL_CONTEXT;delete env.NODE_TEST_CONTEXT;const absent=spawnSync(process.execPath,[__filename],{env,encoding:'utf8'});assert.equal(absent.status,1);assert((absent.stdout+absent.stderr).includes('BORROWED_PUBLIC_CONTEXT_REFUSED'));
 for(const relative of ['MANIFEST.json','CONTRATO-CORRECAO-PG17-v5.json','context/node-postgres-8.13.1/result.js']){const dir=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'borrowed-context-patch-'));try{fs.cpSync(publicRoot,dir,{recursive:true,dereference:false});const file=path.join(dir,relative);fs.chmodSync(file,0o644);fs.appendFileSync(file,'\nADULTERATED');const before=Object.keys(require.cache);assert.throws(()=>publicContext(dir),e=>e.code==='BORROWED_PUBLIC_CONTEXT_REFUSED'&&e.message===e.code&&!e.cause);assert.deepEqual(Object.keys(require.cache),before);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
});
