'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const G=require('../../tools/dashboard-crm-mvp-controls-borrowed-pg17/source-gate.cjs'),M=require('../../tools/dashboard-crm-mvp-controls-borrowed-pg17/materialize-v3-context.cjs'),CI=require('../../tools/dashboard-crm-mvp-controls-borrowed-pg17/root-ci-fixture.cjs');
const root=path.resolve(__dirname,'../..'),raw=fs.readFileSync(path.join(root,'tools/dashboard-crm-mvp-controls-borrowed-pg17/original-v3-snapshot.json'));
const sourceManifest=JSON.parse(fs.readFileSync(path.join(root,'tools/dashboard-crm-mvp-controls-borrowed-pg17/source-manifest.json'))),paths=[...sourceManifest.files.map(e=>e.repoPath),'tools/dashboard-crm-mvp-controls-borrowed-pg17/source-manifest.json','.github/workflows/dashboard-crm-mvp-controls-borrowed-pg17-source-20261006.yml'];
function syntheticTree(){const baseTree=new Map(Array.from({length:1917},(_,n)=>['old/'+n,{mode:'100644',type:'blob',sha:'a'.repeat(40)}])),headTree=new Map(baseTree),disk=new Map(),gitBlobs=new Map();for(const p of paths){const b=fs.readFileSync(path.join(root,p));disk.set(p,b);gitBlobs.set(p,Buffer.from(b));headTree.set(p,{mode:'100644',type:'blob',sha:G.digest(b).gitBlobSha1});}return {head:'b'.repeat(40),expectedHead:'b'.repeat(40),ancestor:true,baseTree,headTree,disk,gitBlobs,dirty:false};}
function closed(fn,code){assert.throws(fn,e=>e.code===code&&e.message===code&&!e.cause);}
test('pure borrowed CI: new10A gate refuses base/head/extra/mutation/mode/dirty source',()=>{assert.equal(G.validateSource(syntheticTree()).preserved,1917);for(const mutate of [s=>s.expectedHead='c'.repeat(40),s=>s.ancestor=false,s=>s.baseTree.delete('old/1'),s=>s.headTree.delete('old/1'),s=>s.headTree.set('extra',{mode:'100644',type:'blob',sha:'c'.repeat(40)}),s=>s.headTree.get(paths[0]).mode='100755',s=>s.disk.set(paths[0],Buffer.from('bad')),s=>s.dirty=true]){const s=syntheticTree();mutate(s);closed(()=>G.validateSource(s),'BORROWED_CI_SOURCE_REFUSED');}});
test('pure borrowed CI: snapshot malformed/repinned/alias records refuse before mkdir/import',()=>{for(const mutate of [c=>c.records.pop(),c=>c.records[1]=c.records[0],c=>c.records[0].path='../escape',c=>c.records[0].data+='\n',c=>{const r=c.records[0],b=Buffer.from('repinned');Object.assign(r,G.digest(b),{data:b.toString('base64')});}]){const c=JSON.parse(raw);mutate(c);closed(()=>G.snapshot(Buffer.from(JSON.stringify(c))),'BORROWED_CI_SOURCE_REFUSED');}const dir=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'borrowed-materialize-negative-'));try{const source=path.join(dir,'borrowed-source-test'),reference=path.join(dir,'borrowed-reference-test');closed(()=>M.materialize({raw:Buffer.from('{}'),runnerTemp:dir,source,reference}),'BORROWED_MATERIALIZATION_REFUSED');assert(!fs.existsSync(source)&&!fs.existsSync(reference));const result=M.materialize({raw,runnerTemp:dir,source,reference});assert.equal(result.sourceFiles,14);assert.equal(result.referenceFiles,17);closed(()=>M.materialize({raw,runnerTemp:dir,source,reference}),'BORROWED_MATERIALIZATION_REFUSED');const target=path.join(source,'tests/crm-mvp-controls-persistence/fixtures.cjs'),alias=target+'.alias';fs.linkSync(target,alias);closed(()=>G.verifyDirectory(source,'source'),'BORROWED_CI_SOURCE_REFUSED');assert(!Object.keys(require.cache).some(p=>p.startsWith(source)));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('pure borrowed CI: fixture absent CI admission refuses before clients/setup/deps',async()=>{const previous=process.env.BORROWED_PG17_CI;try{delete process.env.BORROWED_PG17_CI;const r=await CI.executeScenario('registration-race');assert.equal(r.code,'BORROWED_CI_FIXTURE_REFUSED');assert.equal(r.executed,false);assert.deepEqual(r.cleanup,{created:0,endCalls:0,closed:0});assert.equal(r.operational,false);}finally{if(previous!==undefined)process.env.BORROWED_PG17_CI=previous;}});
test('native borrowed CI: default OFF and incomplete pair have zeroSQL/custody/lifecycle',async()=>{assert.equal(process.env.BORROWED_PG17_CI,'1');CI.authenticatedSources();const runner=require('./borrowed-pg17-protocol.cjs');assert.equal((await runner.run()).code,'BORROWED_PG17_PROOF_DISABLED');let sql=0,admissions=0;const pair=[{query(){sql++;throw Error('never');}}];pair.length=2;const r=await runner.run({enabled:true,clients:pair,scenario:'registration-race',sourceDirectory:process.env.BORROWED_SOURCE_DIRECTORY,admitTest:async()=>{admissions++;throw Error('never');}});assert.equal(r.code,'BORROWED_PG17_PROOF_REFUSED');assert.equal(sql,0);assert.equal(admissions,0);});
for(const scenario of ['registration-race','consume-cas','brand-isolation','pending-hook','ack-hook'])test('native borrowed CI: '+scenario,async()=>{assert.equal(process.env.BORROWED_PG17_CI,'1');const r=await CI.executeScenario(scenario);assert.equal(r.code,'BORROWED_PG17_SCENARIO_PASSED');assert.equal(r.executed,true);assert.equal(Math.floor(r.engineVersionNum/10000),17);assert.equal(r.twoDistinctStableSessions,true);assert.deepEqual(r.cleanup,{created:2,endCalls:2,closed:2});assert.equal(r.scenarioResults.every(x=>x.status==='passed'),true);assert.equal(r.syntheticFaultHooks,scenario==='pending-hook'||scenario==='ack-hook');assert.equal(r.nativeNetworkAckProof,false);assert.equal(r.productionDurabilityProved,false);assert.equal(r.operational,false);console.log(JSON.stringify({code:'BORROWED_SCENARIO_CLOSED',scenario,engineVersionNum:r.engineVersionNum,runtimeVersion:process.version,cleanup:r.cleanup,syntheticFaultHooks:r.syntheticFaultHooks,sourceOnly:true,operational:false,nativeNetworkAckProof:false,productionDurabilityProved:false}));});
