'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module');
const {verifyContext}=require('./verify-context.cjs');
const original=process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY;
function env(value,work){const previous=process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY;try{if(value===undefined)delete process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY;else process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY=value;return work();}finally{if(previous===undefined)delete process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY;else process.env.CRM_PERSISTENCE_CONTEXT_DIRECTORY=previous;}}
function closed(value){const load=Module._load;let imports=0;Module._load=function(request,...args){if(typeof request==='string'&&path.isAbsolute(request))imports++;return load.call(this,request,...args);};try{env(value,()=>assert.throws(verifyContext,e=>e.code==='CRM_CONTEXT_REFUSED'&&e.message==='CRM_CONTEXT_REFUSED'&&!('cause' in e)&&Object.keys(e).join(',')==='code'));assert.equal(imports,0);}finally{Module._load=load;}}
function fixture(work){assert(original&&path.isAbsolute(original),'explicit public context required for test fixture');const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'crm-context-pins-'));try{fs.cpSync(original,root,{recursive:true,dereference:false});return work(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
function mutate(root,relative){const file=path.join(root,relative);fs.chmodSync(file,0o644);fs.appendFileSync(file,'\nADULTERATED');}
test('context pins: missing variable and relative/traversal/private paths refuse without imports',()=>{closed(undefined);for(const value of ['relative/context',original+'/../reference-context-v1',original+'/.private'])closed(value);});
test('context pins: wrong manifest and contract refuse before imports',()=>{for(const relative of ['CONTEXT-MANIFEST.json','CONTRATO-PERSISTENCIA-v1.json'])fixture(root=>{mutate(root,relative);closed(root);});});
test('context pins: modified frozen boundary/kernel/identity and missing source refuse before imports',()=>{for(const relative of ['context/source/services/dashboard-operational/domain/crm-mvp-controls/boundary.cjs','context/source/domain/audience-slices/kernel.cjs','context/reference/identity/identity-pg/worker.cjs'])fixture(root=>{mutate(root,relative);closed(root);});fixture(root=>{fs.unlinkSync(path.join(root,'context/source/audience-slice-contract.js'));closed(root);});});
test('context pins: symlink root/file/parent and hardlink aliases refuse before imports',()=>{fixture(root=>{const alias=root+'-alias';try{fs.symlinkSync(root,alias);closed(alias);}finally{fs.unlinkSync(alias);}});for(const kind of ['symlink','hardlink'])fixture(root=>{const file=path.join(root,'context/source/audience-slice-contract.js'),backup=file+'.original';fs.renameSync(file,backup);if(kind==='symlink')fs.symlinkSync(backup,file);else fs.linkSync(backup,file);closed(root);});fixture(root=>{const folder=path.join(root,'context/source/domain'),backup=folder+'-original';fs.renameSync(folder,backup);fs.symlinkSync(backup,folder);closed(root);});});
test('context pins: exact public context verifies all fourteen and contract without loading any source',()=>{const before=new Set(Object.keys(require.cache));const result=env(original,verifyContext);assert.equal(result.verifiedFileCount,14);assert.equal(result.manifestSha256,'2d05b7bcf711b9244b96441ed9c422d4ea19cf52ffefd0bfcf7097dbccd866a5');assert.equal(result.contractSha256,'d82231e3fecaa0fe0ccad51a8e3c54fecdfb38793d1e0fc82864b9d1e9dec9e2');assert(Object.isFrozen(result));assert.deepEqual(Object.keys(require.cache).filter(k=>!before.has(k)),[]);});
