'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const G=require('../../tools/dashboard-crm-mvp-controls-persistence/source-gate.cjs'),M=require('../../tools/dashboard-crm-mvp-controls-persistence/materialize-context.cjs');
const root=path.resolve(__dirname,'../..'),corpus=fs.readFileSync(path.join(root,'tools/dashboard-crm-mvp-controls-persistence/public-context.json'));
const paths=['.github/workflows/dashboard-crm-mvp-controls-persistence-source-20261006.yml',...['source-gate.cjs','public-context.json','materialize-context.cjs'].map(p=>'tools/dashboard-crm-mvp-controls-persistence/'+p),...['codec.cjs','schema-v1.sql','sql.cjs','store.cjs'].map(p=>'services/dashboard-operational/domain/crm-mvp-controls-persistence/'+p),...['context-pins.test.cjs','fixtures.cjs','pg17.test.cjs','store.test.cjs','verify-context.cjs','source-ci-gate.test.cjs'].map(p=>'tests/crm-mvp-controls-persistence/'+p)];
function snapshot(){const baseTree=new Map([['legacy.txt',{mode:'100644',type:'blob',sha:'a'.repeat(40)}]]),headTree=new Map(baseTree),disk=new Map(),gitBlobs=new Map();for(const p of paths){const b=fs.readFileSync(path.join(root,p));disk.set(p,b);gitBlobs.set(p,Buffer.from(b));headTree.set(p,{mode:'100644',type:'blob',sha:G.digest(b).gitBlobSha1});}return {head:'b'.repeat(40),expectedHead:'b'.repeat(40),parents:['bc5efd57f40ba798a981c67a5937be084e441eaf'],baseTree,headTree,disk,gitBlobs,dirty:false};}
const closed=(fn,code)=>assert.throws(fn,e=>e.code===code&&e.message===code&&Object.keys(e).join(',')==='code'&&!('cause' in e));
function temp(work){const dir=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'crm-source-ci-'));try{return work(dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
function altered(work){const c=JSON.parse(corpus);work(c);return Buffer.from(JSON.stringify(c));}
test('source CI: exact synthetic tree and literal seventeen public pins accepted without domain imports',()=>{const before=Object.keys(require.cache);assert.equal(G.validateCorpus(corpus).size,17);assert.deepEqual(G.validateSource(snapshot()),{added:14,preserved:1,carryForward:9,corpusRecords:17,sourceOnly:true,operational:false});assert.deepEqual(Object.keys(require.cache),before);});
test('source CI: wrong head/parent, extra/deleted/base mutation, modes/disk and dirty tree refuse',()=>{for(const mutate of [s=>s.expectedHead='c'.repeat(40),s=>s.parents=['c'.repeat(40)],s=>s.parents.push('c'.repeat(40)),s=>s.headTree.set('extra.txt',{mode:'100644',type:'blob',sha:'c'.repeat(40)}),s=>s.headTree.delete(paths[0]),s=>s.headTree.delete('legacy.txt'),s=>s.headTree.set('legacy.txt',{mode:'100644',type:'blob',sha:'c'.repeat(40)}),s=>s.headTree.get(paths[0]).mode='100755',s=>s.disk.set(paths[0],Buffer.from('bad')),s=>s.dirty=true]){const s=snapshot();mutate(s);closed(()=>G.validateSource(s),'CRM_SOURCE_GATE_REFUSED');}const s=snapshot(),p=paths.find(p=>p.endsWith('/store.cjs'));s.disk.set(p,Buffer.from('repinned runtime'));s.headTree.get(p).sha=G.digest(s.disk.get(p)).gitBlobSha1;closed(()=>G.validateSource(s),'CRM_SOURCE_GATE_REFUSED');});
test('source CI: corpus missing/duplicate/extra/escape/private/noncanonical/base64/autorepin refuse',()=>{for(const mutate of [c=>c.records.pop(),c=>c.records[1]=c.records[0],c=>c.extra=true,c=>c.records[0].path='../escape',c=>c.records[0].path='/absolute',c=>c.records[0].path='.private/input',c=>c.records[0].data+='\n',c=>c.records[0].data='!!!!',c=>{const r=c.records[0],b=Buffer.from('self-repinned');Object.assign(r,G.digest(b),{data:b.toString('base64')});},c=>c.records[16].data=Buffer.from('last record adulterated').toString('base64')])closed(()=>G.validateCorpus(altered(mutate)),'CRM_SOURCE_GATE_REFUSED');closed(()=>G.validateCorpus(undefined),'CRM_SOURCE_GATE_REFUSED');});
test('source CI: all pins precede writes; missing runner, preexisting output and alias paths refuse',()=>temp(dir=>{const output=path.join(dir,'crm-public-context-test');closed(()=>M.materialize({corpus:altered(c=>c.records[16].data='AAAA'),runnerTemp:dir,output}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');assert.equal(fs.existsSync(output),false);closed(()=>M.materialize({corpus,output}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');closed(()=>M.materialize({corpus,runnerTemp:dir,output:path.join(dir,'../escape')}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');fs.mkdirSync(output);closed(()=>M.materialize({corpus,runnerTemp:dir,output}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');const alias=path.join(dir,'runner-alias');fs.symlinkSync(dir,alias);closed(()=>M.materialize({corpus,runnerTemp:alias,output:path.join(alias,'crm-public-context-alias')}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');}));
test('source CI: physical file symlink/hardlink/missing refused; exclusive materialization preserves all pins',()=>temp(dir=>{const output=path.join(dir,'crm-public-context-good');assert.equal(M.materialize({corpus,runnerTemp:dir,output}).records,17);for(const [p,b] of G.validateCorpus(corpus)){const target=path.join(output,p);G.physical(target);assert(fs.readFileSync(target).equals(b));}const file=path.join(dir,'original');fs.writeFileSync(file,'public');const hard=path.join(dir,'hard'),sym=path.join(dir,'sym');fs.linkSync(file,hard);fs.symlinkSync(file,sym);for(const p of [hard,sym,path.join(dir,'missing')])assert.throws(()=>G.physical(p));closed(()=>M.materialize({corpus,runnerTemp:dir,output}),'CRM_CONTEXT_MATERIALIZATION_REFUSED');}));
