'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const B=require('../../services/dashboard-operational/domain/crm-mvp-controls-persistence/store.cjs');
const F=require('./fixtures.cjs'),{C,SQL}=F;
const count=(c,sql)=>c.logs.filter(x=>x.sql===sql).length;
function setup(seed){const db=F.database();if(seed)F.seed(db,seed);const client=F.client(db),options=F.options(client);return {db,client,options,store:B.create(options),i:F.identity()};}
const outcome=(i,outcome='accepted',revision=2)=>({...i,outcome,expectedOperationRevision:revision});
const refused=(promise,code)=>assert.rejects(promise,e=>e.code===code&&!e.message.includes('private synthetic detail'));

test('synthetic: default OFF and every missing dependency cause no SQL',async()=>{for(const missing of ['enabled','client','clock','verifyRegistration','verifyOutcome']){const s=setup(),options={...s.options};delete options[missing];const b=B.create(options);await refused(b.registerOriginal(F.registration(s.i)),'CRM_CONTROLS_OFF');await refused(b.inspectOperation(s.i),'CRM_CONTROLS_OFF');await refused(b.consumeReservationAttempt({...s.i,expectedOperationRevision:1}),'CRM_CONTROLS_OFF');await refused(b.recordOutcome(outcome(s.i)),'CRM_CONTROLS_OFF');assert.equal(s.client.logs.length,0);}assert.equal(B.ENABLED,false);assert.equal(B.operational,false);});
test('synthetic: closed DTOs reject getters/hidden/symbol/extra/prototype/type/UUID/attempt before SQL',async()=>{for(const mutate of [i=>i.extra=true,i=>i[Symbol('extra')]=1,i=>Object.defineProperty(i,'extra',{value:1}),i=>Object.setPrototypeOf(i,{foreign:true}),i=>i.brand='olivas',i=>i.operationId=i.operationId.toUpperCase().replace('0','A'),i=>i.attemptId=F.uuid(2),i=>i.operationId=42,i=>Object.defineProperty(i,'brand',{enumerable:true,get(){throw Error('getter must not run');}})]){const s=setup(),i=F.registration(s.i);mutate(i);await refused(s.store.registerOriginal(i),'CRM_CONTROLS_DTO_REFUSED');assert.equal(s.client.logs.length,0);}});
test('synthetic: capture before verifier await preserves original identity and immutable data',async()=>{const s=setup(),i=F.registration(s.i);let release,seen;const wait=new Promise(resolve=>release=resolve);s.options.verifyRegistration=async frozen=>{seen=frozen;assert(Object.isFrozen(frozen));await wait;return frozen;};const b=B.create(s.options),pending=b.registerOriginal(i);i.brand='aristo';i.operationId=i.attemptId=F.uuid(2);i.principalRefHash=F.E;release();const r=await pending;assert.equal(r.brand,'fish');assert.equal(r.operationId,s.i.operationId);assert.equal(r.principalRefHash,F.H);assert.equal(seen.operationId,s.i.operationId);});
test('synthetic: verification mismatch/throw/verified flag refuses without any SQL',async()=>{for(const verify of [async()=>{throw Error('private synthetic detail');},async i=>({...i,brand:'aristo'}),async i=>({...i,verified:true}),async()=>null]){const s=setup(),b=B.create({...s.options,verifyRegistration:verify});await refused(b.registerOriginal(F.registration(s.i)),'CRM_CONTROLS_VERIFICATION_REFUSED');assert.equal(s.client.logs.length,0);}});
test('synthetic: registration and exact duplicates preserve immutable original without INSERT/UPDATE',async()=>{const s=setup(),first=await s.store.registerOriginal(F.registration(s.i)),again=await s.store.registerOriginal(F.registration(s.i));assert.equal(first.revision,1);assert.equal(first.state,'registered');assert.equal(first.reservation,false);assert.equal(first.scope,null);assert.equal(first.durable,true);assert.deepEqual(again,first);assert.equal(count(s.client,SQL.INSERT),1);assert.equal(s.client.logs.some(x=>x.sql.startsWith('UPDATE')),false);await refused(s.store.registerOriginal({...F.registration(s.i),principalRefHash:F.E}),'CRM_CONTROLS_VERIFICATION_REFUSED');assert.equal(count(s.client,SQL.INSERT),1);});
test('synthetic: same UUID in two brands isolates registration and lookup',async()=>{const s=setup(),aristo=F.identity('aristo');await s.store.registerOriginal(F.registration(s.i));await s.store.registerOriginal({...F.registration(aristo),principalRefHash:F.E});assert.equal((await s.store.inspectOperation(s.i)).principalRefHash,F.H);assert.equal((await s.store.inspectOperation(aristo)).principalRefHash,F.E);assert.equal(s.db.operations.size,2);});
test('synthetic: absent follows successful read and exact ROLLBACK, query failure stays unknown',async()=>{const s=setup(),r=await s.store.inspectOperation(s.i);assert.equal(r.state,'absent');assert.equal(r.durable,false);assert.equal(count(s.client,SQL.BEGIN_READ),1);assert.equal(count(s.client,SQL.ROLLBACK),1);s.client.before=async sql=>{if(sql===SQL.READ)throw Object.assign(Error('private synthetic detail'),{code:'42P01'});};await refused(s.store.inspectOperation(s.i),'CRM_CONTROLS_LOOKUP_UNKNOWN');});
test('synthetic: corrupt/partial/hash-mismatched rows never become absent or confirmed',async()=>{for(const mutate of [row=>row.receipt_hash=F.E,row=>row.revision='9007199254740992',row=>row.revision=2,row=>row.reserved_member_count=null,row=>row.scope={...row.scope,extra:true}]){const s=setup(F.reserved());mutate(s.db.operations.get(F.key(s.i)));await refused(s.store.inspectOperation(s.i),'CRM_CONTROLS_LOOKUP_UNKNOWN');await assert.rejects(s.store.recordOutcome(outcome(s.i)));assert.equal(count(s.client,SQL.INSERT_INTENT),0);}});
test('codec: BIGINT strings only; no precision loss, fractional/nonfinite/type drift',()=>{assert.equal(C.integer('9007199254740991'),Number.MAX_SAFE_INTEGER);for(const n of ['9007199254740992','1.5','-1','01','NaN','Infinity',2,2n,NaN])assert.throws(()=>C.integer(n));assert.equal(C.integer('0',true),0);assert.throws(()=>C.integer('0'));});
test('synthetic: irreversible consume CAS and duplicate do not rearm or increment',async()=>{const s=setup();await s.store.registerOriginal(F.registration(s.i));const dto={...s.i,expectedOperationRevision:1},r=await s.store.consumeReservationAttempt(dto);assert.equal(r.state,'registered');assert.equal(r.revision,2);assert.equal(r.reservationAttempted,true);assert.equal(r.reservation,false);assert.equal(r.scope,null);assert.deepEqual(await s.store.consumeReservationAttempt(dto),r);assert.equal(count(s.client,SQL.CONSUME),1);await refused(s.store.consumeReservationAttempt({...s.i,expectedOperationRevision:2}),'CRM_CONTROLS_CAS_REFUSED');assert.equal(count(s.client,SQL.CONSUME),1);});
test('synthetic: stale/invalid CAS revisions cannot consume',async()=>{for(const revision of [0,-1,1.1,'1',Infinity,NaN,Number.MAX_SAFE_INTEGER+1]){const s=setup();await refused(s.store.consumeReservationAttempt({...s.i,expectedOperationRevision:revision}),'CRM_CONTROLS_DTO_REFUSED');assert.equal(s.client.logs.length,0);}const s=setup();await s.store.registerOriginal(F.registration(s.i));await refused(s.store.consumeReservationAttempt({...s.i,expectedOperationRevision:3}),'CRM_CONTROLS_CAS_REFUSED');assert.equal(count(s.client,SQL.CONSUME),0);});
test('synthetic: complete reservation unavailable even when otherwise enabled; evaluate and SQL untouched',async()=>{const s=setup();let invoked=0;const r=await s.store.reserveOperation({...s.i,expectedOperationRevision:1,evaluate(){invoked++;}});assert.equal(r.reason,'complete_reservation_contract_unavailable');assert.equal(r.operationId,s.i.operationId);assert.equal(r.authorizesSend,false);assert.equal(invoked,0);assert.equal(s.client.logs.length,0);assert.equal(s.store.capabilities.completeReservation,false);assert.notEqual(s.store.contractVersion,'crm-mvp-controls-proposed-v4');});
test('synthetic: actual outcome requires historical complete reservation and matching verifier',async()=>{const empty=setup();await empty.store.registerOriginal(F.registration(empty.i));await refused(empty.store.recordOutcome(outcome(empty.i,'accepted',1)),'CRM_CONTROLS_RECEIPT_REFUSED');assert.equal(count(empty.client,SQL.INSERT_INTENT),0);for(const verifier of [async()=>{throw Error('private synthetic detail');},async i=>({brand:'aristo',operationId:i.operationId,attemptId:i.attemptId,outcome:i.outcome,evidenceHash:F.H}),async i=>({...i,evidenceHash:F.H}),async i=>({brand:i.brand,operationId:i.operationId,attemptId:i.attemptId,outcome:'unknown',evidenceHash:F.H})]){const s=setup(F.reserved()),b=B.create({...s.options,verifyOutcome:verifier});await refused(b.recordOutcome(outcome(s.i)),'CRM_CONTROLS_VERIFICATION_REFUSED');assert.equal(count(s.client,SQL.INSERT_INTENT),0);}});
test('synthetic: two outcome transactions preserve expired historical scope/proof and revision+1',async()=>{const s=setup(F.reserved()),prior=await s.store.inspectOperation(s.i),r=await s.store.recordOutcome(outcome(s.i));assert.equal(r.state,'accepted');assert.equal(r.revision,3);assert.equal(r.outcomeWriteState,'idle');assert.deepEqual(r.scope,prior.scope);assert.equal(r.reservedMembersHash,prior.reservedMembersHash);assert.equal(r.capacityEvidenceHash,prior.capacityEvidenceHash);assert.equal(r.registeredAt,prior.registeredAt);assert.equal(count(s.client,SQL.COMMIT),2);assert.equal([...s.db.intents.values()][0].phase,'finished');const duplicate=await s.store.recordOutcome(outcome(s.i,'accepted',2));assert.deepEqual(duplicate,r);assert.equal(count(s.client,SQL.FINISH),1);await refused(s.store.recordOutcome(outcome(s.i,'unknown',3)),'CRM_CONTROLS_OUTCOME_CONFLICT');});
test('synthetic: known provider unknown may become final only after a matching new private verification',async()=>{const s=setup(F.reserved());let verified=0;const b=B.create({...s.options,verifyOutcome:async i=>{verified++;return {brand:i.brand,operationId:i.operationId,attemptId:i.attemptId,outcome:i.outcome,evidenceHash:verified===1?F.H:F.E};}});assert.equal((await b.recordOutcome(outcome(s.i,'unknown'))).state,'uncertain');assert.equal((await b.recordOutcome(outcome(s.i,'accepted',3))).state,'accepted');assert.equal(verified,2);assert.equal(s.db.intents.size,2);});
test('synthetic: failure between transactions leaves pending intent across an explicit new client/store',async()=>{const s=setup(F.reserved());let began=0;s.client.before=async sql=>{if(sql===SQL.BEGIN_WRITE&&++began===2)throw Object.assign(Error('private synthetic detail'),{code:'57014'});};await assert.rejects(s.store.recordOutcome(outcome(s.i)));const freshClient=F.client(s.db),fresh=B.create(F.options(freshClient)),r=await fresh.inspectOperation(s.i);assert.equal(r.state,'reserved');assert.equal(r.outcomeWriteState,'pending');assert.equal(r.revision,2);assert.equal([...s.db.intents.values()][0].phase,'pending');await refused(fresh.recordOutcome(outcome(s.i)),'CRM_CONTROLS_PENDING_CONSULT_ONLY');assert.equal(count(freshClient,SQL.FINISH),0);});
test('synthetic: second transaction failure rolls back terminal row and retains durable pending fence',async()=>{const s=setup(F.reserved());s.client.before=async sql=>{if(sql===SQL.FINISH_INTENT)throw Object.assign(Error('private synthetic detail'),{code:'23514'});};await assert.rejects(s.store.recordOutcome(outcome(s.i)));const r=C.decode(s.db.operations.get(F.key(s.i)));assert.equal(r.outcomeWriteState,'pending');assert.equal(r.state,'reserved');assert.equal(r.revision,2);assert.equal([...s.db.intents.values()][0].phase,'pending');});
test('synthetic: lost first fence COMMIT ACK poisons and never starts finalisation',async()=>{const s=setup(F.reserved());s.client.after=async(sql,r)=>{if(sql===SQL.COMMIT)throw Object.assign(Error('private synthetic detail'),{code:'ECONNRESET'});return r;};await refused(s.store.recordOutcome(outcome(s.i)),'CRM_CONTROLS_ACK_UNKNOWN');assert.equal(count(s.client,SQL.BEGIN_WRITE),1);assert.equal(count(s.client,SQL.FINISH),0);const writes=s.client.logs.length;await refused(B.create(s.options).inspectOperation(s.i),'CRM_CONTROLS_SESSION_UNAVAILABLE');assert.equal(s.client.logs.length,writes);const fresh=B.create(F.options(F.client(s.db)));assert.equal((await fresh.inspectOperation(s.i)).outcomeWriteState,'pending');});
test('synthetic: lost terminal COMMIT ACK is consultable from new explicit client without another writer',async()=>{const s=setup(F.reserved());let commits=0;s.client.after=async(sql,r)=>{if(sql===SQL.COMMIT&&++commits===2)return {};return r;};await refused(s.store.recordOutcome(outcome(s.i)),'CRM_CONTROLS_ACK_UNKNOWN');const c=F.client(s.db),fresh=B.create(F.options(c));assert.equal((await fresh.inspectOperation(s.i)).state,'accepted');assert.equal((await fresh.recordOutcome(outcome(s.i))).state,'accepted');assert.equal(count(c,SQL.INSERT_INTENT),0);assert.equal(count(c,SQL.FINISH),0);});
test('synthetic: SQLSTATE40001/57014/disconnect poison without retry/reconnect or error leakage',async()=>{for(const code of ['40001','57014','08006','ECONNRESET']){const s=setup();s.client.before=async sql=>{if(sql===SQL.READ)throw Object.assign(Error('private synthetic detail'),{code,sqlstate:'private synthetic detail'});};await assert.rejects(s.store.inspectOperation(s.i),e=>e.code==='CRM_CONTROLS_LOOKUP_UNKNOWN'&&!JSON.stringify(e).includes('private synthetic detail')&&e.message==='CRM_CONTROLS_LOOKUP_UNKNOWN');const length=s.client.logs.length;await refused(B.create(s.options).inspectOperation(s.i),'CRM_CONTROLS_SESSION_UNAVAILABLE');assert.equal(s.client.logs.length,length);assert.deepEqual(s.client.owned,{connect:0,end:0,release:0});}});
test('synthetic: ROLLBACK finish failure and malformed BEGIN/COMMIT never produce a durable ACK',async()=>{for(const sql of [SQL.BEGIN_WRITE,SQL.COMMIT]){const s=setup();s.client.after=async(q,r)=>q===sql?{command:'not-an-ack'}:r;await refused(s.store.registerOriginal(F.registration(s.i)),'CRM_CONTROLS_ACK_UNKNOWN');await refused(s.store.inspectOperation(s.i),'CRM_CONTROLS_SESSION_UNAVAILABLE');}const s=setup();s.client.after=async(q,r)=>q===SQL.ROLLBACK?{}:r;await refused(s.store.inspectOperation(s.i),'CRM_CONTROLS_LOOKUP_UNKNOWN');await refused(s.store.inspectOperation(s.i),'CRM_CONTROLS_SESSION_UNAVAILABLE');});
test('synthetic: one borrowed client shared across stores refuses concurrent/reentrant transactions',async()=>{const s=setup();let release,entered;const latch=new Promise(resolve=>entered=resolve),wait=new Promise(resolve=>release=resolve);s.options.verifyRegistration=async i=>{entered();await wait;return i;};const a=B.create(s.options),b=B.create(s.options),pending=a.registerOriginal(F.registration(s.i));await latch;await refused(b.inspectOperation(s.i),'CRM_CONTROLS_CLIENT_BUSY');assert.equal(s.client.logs.length,0);release();await pending;assert.equal(count(s.client,SQL.BEGIN_WRITE),1);});
test('synthetic: borrowed Root client and original Auth lease remain untouched',async()=>{const s=setup(),lease=s.client.authLease;await s.store.registerOriginal(F.registration(s.i));await s.store.inspectOperation(s.i);await s.store.consumeReservationAttempt({...s.i,expectedOperationRevision:1});assert.equal(s.client.authLease,lease);assert.deepEqual(s.client.owned,{connect:0,end:0,release:0});});
test('source: schema text is exact, fixed/qualified SQL only, foundation cannot activate frozen v6 boundary',async()=>{const ddl=fs.readFileSync(path.resolve(__dirname,'../../services/dashboard-operational/domain/crm-mvp-controls-persistence/schema-v1.sql'),'utf8');assert.equal(ddl,SQL.SCHEMA_SQL);assert(!/CREATE DATABASE|CREATE ROLE|GRANT |CREATE EXTENSION/i.test(ddl));for(const name of ['READ','LOCK','INSERT','CONSUME','PENDING','FINISH','INSERT_INTENT','LOCK_INTENT','FINISH_INTENT'])assert(SQL[name].includes('dashboard_crm_controls.'));const context=require('./verify-context.cjs').verifyContext();{const root=context.source,old=require(path.join(root,'services/dashboard-operational/domain/crm-mvp-controls/boundary.cjs')),kernel=require(path.join(root,'domain/audience-slices/kernel.cjs')),deliverability=require(path.join(root,'services/dashboard-operational/domain/deliverability/policy.cjs'));const s=setup(),boundary=old.create({enabled:true,kernel,deliverability,adapter:s.store,clock:()=>F.NOW});assert.equal((await boundary.reserve(s.i)).state,'closed');assert.equal(s.client.logs.length,0);}});

test('synthetic: reordered scope preserves hash; uncertain write fence stays consult-only',async()=>{const original=F.reserved(),body={...original,scope:Object.fromEntries(Object.entries(original.scope).reverse())};const s=setup(body);assert.equal((await s.store.inspectOperation(s.i)).receiptHash,C.receiptHash(body));const blocked=setup({...F.reserved(),outcomeWriteState:'uncertain'});await refused(blocked.store.recordOutcome(outcome(blocked.i)),'CRM_CONTROLS_PENDING_CONSULT_ONLY');assert.equal(count(blocked.client,SQL.INSERT_INTENT),0);});
test('synthetic: stale/max outcome revision and invalid clock cannot write an intent',async()=>{for(const revision of [1,Number.MAX_SAFE_INTEGER]){const s=setup(F.reserved());await refused(s.store.recordOutcome(outcome(s.i,'accepted',revision)),'CRM_CONTROLS_CAS_REFUSED');assert.equal(count(s.client,SQL.INSERT_INTENT),0);}for(const clock of [()=>NaN,()=>0,()=>{throw Error('private synthetic detail');}]){const s=setup(F.reserved()),b=B.create({...s.options,clock});await refused(b.recordOutcome(outcome(s.i)),'CRM_CONTROLS_CLOCK_REFUSED');assert.equal(count(s.client,SQL.INSERT_INTENT),0);}});
test('synthetic: outcome DTO mutation during private verifier await cannot redirect the write',async()=>{const s=setup(F.reserved()),dto=outcome(s.i);let release,entered;const latch=new Promise(r=>entered=r),wait=new Promise(r=>release=r);const b=B.create({...s.options,verifyOutcome:async(i,prior)=>{assert(Object.isFrozen(i));assert(Object.isFrozen(prior.scope));entered();await wait;return {brand:i.brand,operationId:i.operationId,attemptId:i.attemptId,outcome:i.outcome,evidenceHash:F.H};}});const pending=b.recordOutcome(dto);await latch;dto.brand='aristo';dto.operationId=dto.attemptId=F.uuid(99);dto.outcome='unknown';release();const result=await pending;assert.equal(result.operationId,s.i.operationId);assert.equal(result.brand,'fish');assert.equal(result.state,'accepted');});
