'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),GF=require('../../growth-flows.js');
const {flow,api,now}=require('./fixtures.cjs');
const read=p=>GF.lista(p,{marca:'fish',now,configuredReadOnly:true});
test('configured read is opt-in, one frozen projection preserves only declared links and ambiguous initial entry',()=>{const f=flow(),m=read(api([f]));assert.equal(m.configuredReadOnly,true);assert.equal(m.definidos.length,1);assert.equal(m.deliveryConfirmed,false);const g=m.definidos[0].graph;assert.deepEqual(g.links.map(l=>[l.fromKey,l.toKey,l.status]),[['send','check','resolved'],['check','end','resolved'],['check','missing','missing']]);assert.equal(g.entry,'not-declared');assert.equal(g.fidelity,'declared-links-only');assert.deepEqual(g.nodes.map(n=>n.key),['send','check','end']);assert.equal(g.nodes[0].ordem,2);assert.equal(g.nodes[1].ordem,1);assert.equal(g.nodes[2].ordem,null);assert(Object.isFrozen(g.links));assert.throws(()=>{g.links.push({});},TypeError);});
test('missing/ambiguous targets and undeclared conditional destination retained instead of selecting first duplicate key',()=>{const f=flow();f.etapas.push({key:'end',tipo:'fim'});f.etapas[1].condicoes.push({se:'outro caso'});const g=read(api([f])).definidos[0].graph;assert.equal(g.links[1].status,'ambiguous');assert.equal(g.links[1].toId,null);assert.equal(g.links[2].status,'missing');assert.equal(g.links[3].status,'undeclared');assert(g.problemas.some(p=>p.kind==='duplicate-stage-key'));assert.equal(g.links.length,4);});
test('no transitions means standalone declared stages, never guessed sequence from order/name or alphabet',()=>{const f=flow();f.etapas=[{key:'z',tipo:'espera',espera_seg:60,ordem:1},{key:'a',tipo:'fim',ordem:2}];const g=read(api([f])).definidos[0].graph;assert.deepEqual(g.nodes.map(n=>n.key),['z','a']);assert.equal(g.links.length,0);assert.equal(g.connectionState,'not-declared');const rows=GF.configuredRowsCsv(read(api([f])));assert.equal(rows[0].transicoes,'');assert.equal(rows[1].transicoes,'');});
test('explicit cycle/self-loop are preserved without adding start/end or execution claims',()=>{const f=flow();f.etapas=[{key:'loop',tipo:'espera',espera_seg:1,saida_para:'loop'}];const m=read(api([f]));assert.equal(m.definidos[0].graph.links[0].fromId,m.definidos[0].graph.links[0].toId);assert.equal(m.executionConfirmed,false);});
test('absent,error,unsupported,invalid,valid-empty and partial remain distinct; no missing source count becomes zero',()=>{assert.equal(read({}).source.state,'absent');assert.equal(read({crm_fluxo_def:{error:'private error',fluxos:[]}}).source.state,'error');assert.equal(read({error:'fail',...api([])}).source.state,'error');assert.equal(read({crm_fluxo_def:{schema_version:2,fluxos:[]}}).source.state,'unsupported-schema');assert.equal(read(api([])).source.state,'empty');const invalid=flow();invalid.versao.numero=true;assert.equal(read(api([invalid])).source.state,'invalid');const partial=read(api([flow(),{...invalid,key:'different'}]));assert.equal(partial.source.state,'partial');assert.equal(partial.invalidosDef,1);assert.equal(partial.definidos.length,1);});
test('configured validation rejects inferred keys,boolean/string numeric coercion,bad wait/template and invalid conditions',()=>{for(const change of [f=>delete f.etapas[0].key,f=>f.versao.numero='3',f=>f.etapas[0].ordem=false,f=>f.etapas[0].canal='javascript',f=>delete f.etapas[0].template_ref,f=>f.etapas[1].condicoes=[{entao:'end'}],f=>f.etapas[2]={key:'w',tipo:'espera',espera_seg:'60'}]){const f=flow();change(f);const m=read(api([f]));assert.equal(m.definidos.length,0);assert.equal(m.source.state,'invalid');}});
test('duplicate same-brand flow keys reject all candidates; same key across brands never joins',()=>{const fish=flow(),aristo=flow('aristo');const m=read(api([fish,aristo]));assert.equal(m.definidos.length,1);assert.equal(m.definidos[0].marca,'fish');assert(!JSON.stringify(m).includes('Jornada aristo'));const duplicates=read(api([fish,{...flow(),versao:{...fish.versao,id:'other-revision'}}]));assert.equal(duplicates.definidos.length,0);assert.equal(duplicates.invalidosDef,2);assert.equal(GF.configuredRead(api([fish,aristo]),{marca:'todas'}).source.state,'scope-required');});
test('history without definition never creates nodes,links,versions or current trigger; CSV stays explicitly historical',()=>{const m=read({crm_fluxo:[{marca:'fish',flow:'historic',piece:'z-first',canal:'email',dia:'2026-10-07',enviados:1},{marca:'fish',flow:'historic',piece:'a-second',canal:'email',dia:'2026-10-07',enviados:2},{marca:'aristo',flow:'private-other',piece:'x',canal:'email',enviados:1}],crm_operacao:{workflows:[],templates:[]}});assert.equal(m.source.state,'absent');assert.equal(m.definidos.length,0);assert.equal(m.observados.length,1);assert.equal(m.observados[0].gatilho,null);assert.equal(m.observados[0].graph,undefined);const rows=GF.configuredRowsCsv(m);assert(rows.every(r=>r.origem==='historico-observado'&&r.ordem===null&&r.transicoes===null));assert(!JSON.stringify(rows).includes('private-other'));});
test('revision and declared freshness displayed as source metadata; active/real never means delivery or execution',()=>{const m=read(api([flow()]));assert.equal(m.source.revision,'r6-source');assert.equal(m.source.freshness,'validity-not-declared');assert.equal(m.definidos[0].versao.ativa,true);assert.equal(m.mutateAllowed,false);const p=api([flow()]);p.crm_fluxo_def.expires_at='2026-10-07T11:30:00Z';assert.equal(read(p).source.freshness,'expired');p.crm_fluxo_def.expires_at='2026-10-07T13:00:00Z';assert.equal(read(p).source.freshness,'within-declared-validity');p.crm_fluxo_def.generated_at='future';assert.equal(read(p).source.freshness,'invalid-metadata');});
test('shared model filters feed exact same list/diagram projection and CSV step keys/explicit transition problems',()=>{const first=flow(),second=flow('fish','other');second.nome='Outro caminho';const model=read(api([first,second])),visible=GF.configuredFilter(model,{q:'Jornada fish',origem:'definidos'});assert.equal(visible.definidos.length,1);const rows=GF.configuredRowsCsv(visible);assert.deepEqual(rows.map(r=>r.key),visible.definidos[0].graph.nodes.map(n=>n.key));assert(rows[1].problemas.includes('missing'));assert(rows[1].transicoes.includes('sem compra'));assert.equal(rows[0].modo,'real');});
test('XSS is data only; CSV formula/newline/quote escapes and object getters/limit/prototype payloads refuse',()=>{const f=flow();f.nome='=HYPERLINK("bad")';f.etapas[0].nome='<img src=x onerror=evil()>\n"quoted"';const model=read(api([f])),csv=GF.configuredCsv(model);assert(csv.includes("'=HYPERLINK"));assert(csv.includes('""quoted""'));let ran=false;const p={};Object.defineProperty(p,'crm_fluxo_def',{enumerable:true,get(){ran=true;return api([f]).crm_fluxo_def;}});assert.equal(read(p).source.state,'invalid-input');assert.equal(ran,false);assert.equal(read({crm_fluxo_def:JSON.parse('{"__proto__":{},"schema_version":1,"fluxos":[]}')}).source.state,'invalid-input');assert.equal(read(api(Array.from({length:101},()=>flow()))).source.state,'invalid');});

test('explicit historical export refuses current definition projection and impossible timestamp never appears fresh',()=>{const historical=api([flow()]);historical._historical_export=true;const m=read(historical);assert.equal(m.source.state,'historical-not-current');assert.equal(m.definidos.length,0);const raw=api([flow()]);raw.crm_fluxo_def.historical=true;assert.equal(read(raw).definidos.length,0);const invalid=api([flow()]);invalid.crm_fluxo_def.generated_at='2026-02-30T10:00:00Z';assert.equal(read(invalid).source.freshness,'invalid-metadata');});
test('legacy CSV entry dispatches configured model to its same declared projection instead of observed assumptions',()=>{const m=read(api([flow()]));assert.deepEqual(GF.linhasCsv(m),GF.configuredRowsCsv(m));});

test('same workflow key across brands never leaks foreign label or cache freshness through template/history join',()=>{const p={crm_fluxo:[{marca:'fish',flow:'f',piece:'piece',canal:'whatsapp'}],crm_operacao:{templates:[{brand:'fish',name:'fish-template',mapped_in:[{workflow_key:'shared',piece:'piece',mode_key:'send'}]}],workflows:[{key:'shared',brand:'aristo',label:'private-aristo-workflow',active:true,modes:[{key:'send',value:'real'}]},{key:'shared',brand:'fish',label:'fish-workflow',active:true,modes:[{key:'send',value:'sombra'}]}]}};const m=GF.configuredRead(p,{marca:'fish',workflowsModel:[{key:'shared',brand:'aristo',fieldsValid:true,collection:{current:true}}]});assert(!JSON.stringify(m).includes('private-aristo-workflow'));assert.equal(m.observados[0].etapas[0].workflows[0].label,'fish-workflow');assert.equal(m.observados[0].etapas[0].workflows[0].atual,null);assert(!GF.configuredCsv(m).includes('private-aristo-workflow'));});
