'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{flow,api,now}=require('./fixtures.cjs'),GF=require('../../growth-flows.js');
function ui(){const path=require.resolve('../../growth-flows-ui.js');delete require.cache[path];const UI=require(path),downloads=[],traps=[];class Element{constructor(){this.value='';this.selectionStart=0;this.focused=false;}focus(){this.focused=true;}setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b;}addEventListener(type,handler){this['on'+type]=handler;}}
 const root={nodes:new Map(),html:'',querySelector(selector){return this.nodes.get(selector)||null;},get innerHTML(){return this.html;},set innerHTML(value){this.html=String(value);this.nodes=new Map();for(const match of this.html.matchAll(/\bid="([^"]+)"/g)){const node=new Element();this.nodes.set('#'+match[1],node);}}};global.document={querySelector:s=>s==='#control-fluxos'?root:null};global.GT={captura:()=>null,restaura:()=>{},busca:rows=>rows,baixar:(name,csv)=>downloads.push({name,csv})};global.GB={render:()=>{traps.push('editor');throw Error('MUTATION_UNAUTHORIZED');}};global.GJGApi={create:()=>{traps.push('graph-client');throw Error('MUTATION_UNAUTHORIZED');}};global.fetch=()=>{traps.push('network');throw Error('NETWORK_UNAUTHORIZED');};return {UI,root,downloads,traps,render:(p,marca='fish',extra={})=>UI.render({api:p,marca,now,configuredReadOnly:true,...extra})};}
test('configuredReadOnly wins observedOnly, hostile editor capability never delegates or mutates/network-calls',()=>{const f=ui(),p=api([flow()]);p.capabilities={workflows:{editor:true}};f.render(p,'fish',{observedOnly:true});assert(f.root.html.includes('Jornada fish'));assert(f.root.html.includes('<svg '));assert(f.root.html.includes('Somente leitura'));assert.equal(f.UI.readModel.definidos.length,1);assert.deepEqual(f.traps,[]);assert(!/Salvar|Publicar|Ativar|Criar jornada/.test(f.root.html));});
test('legacy observedOnly still excludes valid definitions and does not delegate editor',()=>{const f=ui(),p=api([flow()]);p.capabilities={workflows:{editor:true}};p.crm_fluxo=[{marca:'fish',flow:'historico',piece:'a',canal:'email',dia:'2026-10-07',enviados:1}];f.UI.render({api:p,marca:'fish',observedOnly:true});assert(f.root.html.includes('historico'));assert(!f.root.html.includes('Jornada fish'));assert(!f.root.html.includes('<svg '));assert.deepEqual(f.traps,[]);});
test('diagram emits only two resolved declared edges; missing condition shown textually and initial entry not inferred',()=>{const f=ui();f.render(api([flow()]));assert.equal([...f.root.html.matchAll(/data-journey-edge=/g)].length,2);assert(f.root.html.includes('destino ausente na definição'));assert(f.root.html.includes('missing'));assert(f.root.html.includes('Etapa inicial não declarada'));assert(f.root.html.includes('A posição é apenas visual'));assert(f.root.html.includes('aria-labelledby='));assert(f.root.html.includes('tabindex="0"'));});
test('same scoped model survives diagram/list and exports exact visible CSV; keyboard focus remains on view button',()=>{const f=ui();f.render(api([flow(),flow('aristo')]));const graph=f.UI.readModel.definidos[0].graph;f.root.querySelector('#gjr-list').onclick();assert.equal(f.UI.readState.view,'list');assert(!f.root.html.includes('<svg '));assert.equal(f.root.querySelector('#gjr-list').focused,true);assert.deepEqual(f.UI.readModel.definidos[0].graph,graph);f.root.querySelector('#gjr-export').onclick();assert.equal(f.downloads.length,1);assert.equal(f.downloads[0].csv,GF.configuredCsv(f.UI.readModel));assert(!f.downloads[0].csv.includes('aristo'));assert.equal(f.downloads[0].name,'jornadas-leitura-fish.csv');});
test('brand switch resets filters and stale export/search/view callbacks cannot act on next brand',()=>{const f=ui();f.render(api([flow(),flow('aristo')]));const staleExport=f.root.querySelector('#gjr-export').onclick,staleView=f.root.querySelector('#gjr-list').onclick;f.UI.readState.q='fish';f.render(api([flow(),flow('aristo')]),'aristo');assert.equal(f.UI.readState.q,'');assert(f.root.html.includes('Jornada aristo'));assert(!f.root.html.includes('Jornada fish'));staleExport();staleView();assert.equal(f.downloads.length,0);assert.equal(f.UI.readState.view,'diagram');f.root.querySelector('#gjr-export').onclick();assert(!f.downloads[0].csv.includes('Jornada fish'));});
test('definition absent/error never becomes empty success; history never renders SVG or invented connections',()=>{const f=ui();f.render({crm_fluxo:[{marca:'fish',flow:'historic',piece:'z-1',canal:'email',enviados:3}]});assert(f.root.html.includes('Definição não fornecida'));assert(f.root.html.includes('Contagem de definições indisponível'));assert(!f.root.html.includes('<svg '));assert(f.root.html.includes('ordem alfabética não é sequência'));f.render({crm_fluxo_def:{error:'secret-error',fluxos:[]}});assert(f.root.html.includes('Falha na leitura'));assert(!f.root.html.includes('secret-error'));f.render(api([]));assert(f.root.html.includes('Nenhuma definição desta marca'));assert(!f.root.html.includes('Contagem de definições indisponível'));});
test('no-edge valid definition shows stages without claiming faithful execution graph; ambiguous destinations draw no guessed edge',()=>{const f=ui(),p=flow();p.etapas=[{key:'one',tipo:'espera',espera_seg:1},{key:'two',tipo:'fim'}];f.render(api([p]));assert(f.root.html.includes('não declarou conexões'));assert(f.root.html.includes('Não é possível afirmar a fidelidade'));assert.equal([...f.root.html.matchAll(/data-journey-edge=/g)].length,0);const ambiguous=flow();ambiguous.etapas.push({key:'end',tipo:'fim'});f.render(api([ambiguous]));assert(f.root.html.includes('destino ambíguo'));assert.equal([...f.root.html.matchAll(/data-journey-edge=/g)].length,1);});
test('API text is escaped in HTML/SVG/attributes and CSV formula-safe; no markup preview delegation',()=>{const f=ui(),p=flow();p.nome='<img src=x onerror=attack()> "bad"';p.key='\"><script>attack()</script>';p.etapas[0].nome='<svg onload=attack()>';p.etapas[1].condicoes[0].se='"><script>condition()</script>';f.render(api([p]));assert(!f.root.html.includes('<img'));assert(!f.root.html.includes('<script'));assert(!f.root.html.includes('<svg onload'));assert(f.root.html.includes('&lt;img'));assert(f.root.html.includes('&lt;script&gt;'));assert(f.root.html.includes('&quot;'));assert.deepEqual(f.traps,[]);});
test('active/real and stale metadata remain declarative warnings, never green delivery confirmation',()=>{const f=ui(),p=api([flow()]);p.crm_fluxo_def.expires_at='2026-10-07T11:30:00Z';f.render(p);assert(f.root.html.includes('Validade declarada expirada'));assert(f.root.html.includes('marcada ativa'));assert(f.root.html.includes('modo declarado real'));assert(f.root.html.includes('não comprova execução nem entrega'));assert(!f.root.html.includes('control-verified'));});
test('search/export uses visible subset,origin toggle is local read only and restores search cursor',()=>{const f=ui(),first=flow(),second=flow('fish','second');second.nome='Segunda';f.render(api([first,second]));const search=f.root.querySelector('#gjr-search');search.value='Segunda';search.selectionStart=3;search.oninput();assert.equal(f.root.querySelector('#gjr-search').focused,true);assert.equal(f.root.querySelector('#gjr-search').selectionStart,3);assert.equal(f.UI.readModel.definidos.length,1);f.root.querySelector('#gjr-export').onclick();assert(!f.downloads[0].csv.includes('Jornada fish'));const origin=f.root.querySelector('#gjr-origin');origin.value='observados';origin.onchange();assert.equal(f.UI.readModel.definidos.length,0);assert.deepEqual(f.traps,[]);});

test('raw browser-style scripts work without module/require using original same-realm JSON; no browser/network used',()=>{const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),f=ui(),sandbox={document:global.document,TextEncoder,GT:global.GT,GB:global.GB,GJGApi:global.GJGApi,fetch:global.fetch,input:JSON.stringify(api([flow()])),now};vm.createContext(sandbox);const product=path.resolve(__dirname,'../..');vm.runInContext(fs.readFileSync(product+'/growth-flows.js','utf8')+'\n'+fs.readFileSync(product+'/growth-flows-ui.js','utf8')+'\nGFU.render({api:JSON.parse(input),marca:"fish",now,configuredReadOnly:true});',sandbox);assert(f.root.html.includes('Jornada fish'));assert.equal([...f.root.html.matchAll(/data-journey-edge=/g)].length,2);assert.deepEqual(f.traps,[]);});
