'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=process.env.PUBLISHED_JOURNEY_SOURCE?path.resolve(process.env.PUBLISHED_JOURNEY_SOURCE):path.resolve(__dirname,'../..'),C=require(path.join(root,'growth-canvas.js')),P=require(path.join(root,'growth-published-flows.js'));
const output=fs.readFileSync(path.join(root,'growth-published-flows.js'),'utf8');
function body(){const steps=[{key:'mail',name:'Mensagem',channel:'email',wait_min:30,enabled:true,template_name:'Publicado'}];return {checked_at:'2026-10-08T12:00:00Z',flows:[{key:'fish:test',brand:'fish',name:'Teste',trigger:'Evento',version:2,published_version:1,published:{steps,layout:{nodes:{trigger:{x:1000,y:-90},'step:mail':{x:-100,y:300}}}},draft:{steps:[]},available_steps:steps,enabled:false,runtime_ready:true,journey_kind:null}]};}
const model=()=>P.normalize(body(),'fish',C),origin='https://crm.example',context=brand=>({api:null,marca:brand,section:'regua',tab:'fluxos'}),reply=b=>new Response(JSON.stringify(b)),proof=brand=>({brand,contract:P.VERSION,endpoint:origin+'/api/templates',read:true,readOnly:true,scope:'master-brand-scoped',write:false});
test('transport and admission remain byte identical; canonical inputs immutable',()=>{const crypto=require('node:crypto'),start=output.indexOf(' function admission'),end=output.indexOf(' let browser=');assert.equal(crypto.createHash('sha256').update(output.slice(start,end)).digest('hex'),'25fa1b8d6ee2fcbfbe2dbf17a1fb6a7876931abb7f801b62028845a4109791a9');assert.equal(P.VERSION,'crm-published-journey-read-v1');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'growth-canvas.js'))).digest('hex'),'16e985aa20c913394f94d0df8aed32c9a887369ece9aecf4922c1e02a6e51e66');});
test('canonical graph, positions, ports, path and icon presentation preserved',()=>{const b=body(),before=structuredClone(b),m=P.normalize(b,'fish',C),g=m.flows[0].graph;assert.equal(m.state,'loaded');assert.deepEqual(g,C.graph(b.flows[0],b.flows[0].published));assert.deepEqual(b,before);assert.equal(g.nodes[0].x,1000);assert.equal(m.flows[0].edgeMarkup,C.edgesHtml(g).replaceAll('url(#flow-arrow)','url(#jpr-flow-arrow)'));for(const edge of g.edges){const a=g.nodes.find(n=>n.id===edge.from),z=g.nodes.find(n=>n.id===edge.to);assert(m.flows[0].edgeMarkup.includes(C.edgePath(a,z)));assert(Number.isFinite(C.ports(a,z).x));}for(const n of g.nodes){const h=P.nodeHtml(n,null);assert(h.includes('left:'+n.x+'px;top:'+n.y+'px'));assert(h.includes('flow-node-'+n.type));assert.match(h,/Somente leitura/);assert.doesNotMatch(h,/data-flow-node|Arraste para mover|configurar/);}});
test('one selected journey and readonly inspector, no draft/editor actions',()=>{const b=body();b.flows.push({...structuredClone(b.flows[0]),key:'fish:second',name:'Segundo'});const m=P.normalize(b,'fish',C),v=P.createView(C);v.sync(m);let h=P.html(m,v);assert.equal((h.match(/flow-viewport /g)||[]).length,1);assert.match(h,/data-jpr-picker/);assert.doesNotMatch(h,/<input|<textarea|data-flow-|Salvar|Publicar|Adicionar/);v.select('fish:second');v.inspect('step:mail');h=P.html(m,v);assert.match(h,/Detalhes publicados|Template publicado/);assert.match(h,/<dd>Publicado<\/dd>/);assert.equal(v.flow().key,'fish:second');});
test('view pan zoom fit minimap change only viewport and preserve canonical globals',()=>{const m=model(),before=JSON.stringify(m),editor={views:C.views,selected:C.selected,model:C.model},v=P.createView(C);v.sync(m);v.pan(25,-10);assert.equal(v.state().x,85);const expected=C.zoomAt(v.state(),1.2,100,80);v.zoom(1.2,100,80);assert.equal(v.state().x,expected.x);assert.equal(v.state().y,expected.y);v.fit(900,650);assert(v.state().z>=.15&&v.state().z<=1);assert.match(v.map(900,650).html,/map-window/);v.mapTo(100,65,900,650);assert(Number.isFinite(v.state().x));assert.equal(JSON.stringify(m),before);assert.deepEqual({views:C.views,selected:C.selected,model:C.model},editor);});
test('timer rerender and reselection preserve view; new read, brand invalidation and clear reset',()=>{const b=body();b.flows.push({...structuredClone(b.flows[0]),key:'fish:second'});const m=P.normalize(b,'fish',C),v=P.createView(C);v.sync(m);v.pan(50,10);v.inspect('trigger');v.state().expanded=true;v.sync(m);assert.equal(v.state().x,110);v.select('fish:second');assert.equal(v.state().x,60);v.select('fish:test');assert.equal(v.state().x,110);assert.equal(v.state().node,'trigger');v.sync({state:'unavailable',flows:[]});assert.equal(v.state(),undefined);v.sync(model());assert.equal(v.state().x,60);assert.equal(v.state().node,null);assert.equal(v.state().expanded,false);});
test('XSS escaped and absent publication never treated as zero or draft',()=>{const b=body();b.flows[0].name='<script>x</script>';b.flows[0].published.steps[0].template_name='<img onerror=x>';const m=P.normalize(b,'fish',C),v=P.createView(C);v.sync(m);v.inspect('step:mail');const h=P.html(m,v);assert.doesNotMatch(h,/<script|<img/);assert.match(h,/&lt;img/);b.flows[0].published=null;b.flows[0].published_version=null;assert.doesNotMatch(P.html(P.normalize(b,'fish',C)),/flow-node|marker-end/);assert.match(P.html(P.normalize({checked_at:b.checked_at,flows:[]},'fish',C)),/não comprova ausência/);});
test('CURRENT two GETs, revoked capability and read failure discard visible definitions',async()=>{let revoked=false,fail=false;const calls=[],c=P.create({canvas:C,origin,fetchImpl:async(u,o)=>{calls.push(u);assert.equal(o.method,'GET');assert.equal(o.body,undefined);return u.includes('fluxos_capacidade')?(revoked?new Response('{}',{status:403}):reply(proof('fish'))):(fail?new Response('{}',{status:503}):reply(body()));}});c.sync(context('fish'));assert.equal(await c.refresh(),true);assert.equal(calls.length,2);revoked=true;assert.equal(await c.refresh(),false);assert.equal(c.state().model.state,'unavailable');assert.equal(calls.length,3);revoked=false;fail=true;assert.equal(await c.refresh(),false);assert.equal(c.state().model.state,'unavailable');c.dispose();});
test('late read after brand change or dispose cannot repopulate model',async()=>{for(const dispose of [false,true]){let resolve;const c=P.create({canvas:C,origin,fetchImpl:async u=>u.includes('fluxos_capacidade')?reply(proof('fish')):await new Promise(r=>resolve=r)});c.sync(context('fish'));const pending=c.refresh();while(!resolve)await new Promise(r=>setImmediate(r));if(dispose)c.dispose();else c.sync(context('aristo'));resolve(reply(body()));assert.equal(await pending,false);assert.equal(c.state().model.state,'unavailable');}});
test('actual readonly DOM bindings dispatch pointer wheel minimap keyboard and inspector without editor hooks',()=>{
 const vm=require('node:vm'),box={module:{exports:{}},document:{getElementById:()=>null}};
 vm.runInNewContext(output.replace('VERSION,normalize,html,createView,nodeHtml,admission','bind,setTestView:v=>{view=v;},VERSION,normalize,html,createView,nodeHtml,admission'),box);
 const v=P.createView(C);v.sync(model());box.module.exports.setTestView(v);
 const element=dataset=>({dataset,style:{},listeners:{},addEventListener(n,f){this.listeners[n]=f;},getBoundingClientRect(){return {left:0,top:0,width:800,height:620};},setPointerCapture(){},innerHTML:''});
 const vp=element({}),world=element({}),map=element({}),node=element({jprNode:'step:mail'}),fit=element({jprAction:'fit'}),expand=element({jprAction:'expand'}),reset=element({jprAction:'reset'});
 const root={querySelector:s=>({'[data-jpr-viewport]':vp,'[data-jpr-world]':world,'[data-jpr-minimap]':map,'[data-jpr-action="reset"]':reset}[s]||null),querySelectorAll:s=>s==='[data-jpr-node]'?[node]:s==='[data-jpr-action]'?[fit,expand,reset]:[]};
 box.module.exports.bind(root);const event={button:0,pointerId:1,clientX:20,clientY:30,target:vp,preventDefault(){}};
 vp.listeners.pointerdown(event);vp.listeners.pointermove({...event,clientX:50,clientY:60});assert.equal(v.state().x,90);vp.listeners.pointerup(event);
 vp.listeners.wheel({...event,deltaY:-20,deltaX:0,ctrlKey:true});assert(v.state().z>.8);assert.match(world.style.transform,/scale/);assert.match(map.innerHTML,/map-window/);
 node.listeners.click();assert.equal(v.state().node,'step:mail');expand.listeners.click();assert.equal(v.state().expanded,true);vp.listeners.keydown({...event,key:'Escape'});assert.equal(v.state().expanded,false);assert.equal(v.state().node,null);
 fit.listeners.click();assert(v.state().z<=1);map.listeners.click({...event,clientX:400,clientY:310});assert(Number.isFinite(v.state().x));
 const before=v.state().x;vp.listeners.pointermove({...event,clientX:900});assert.equal(v.state().x,before);
});

test('missing or throwing canonical edge renderer closes normalization',()=>{assert.equal(P.normalize(body(),'fish',{graph:C.graph}).state,'unavailable');assert.equal(P.normalize(body(),'fish',{graph:C.graph,edgesHtml(){throw Error('unavailable');}}).state,'unavailable');});
