'use strict';
// Isolated source/runtime fixtures only. No production identity or network.
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const runtime=process.env.PUBLISHED_JOURNEY_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const {createAuth}=require(path.join(runtime,'auth.cjs'));
const {createServer,settingsFromEnv,environmentForOriginalMasterPublishedJourneyRead}=require(path.join(runtime,'server.cjs'));
const {ENDPOINT}=require(path.join(runtime,'crm-native-mcp.cjs'));
const P=require(path.join(runtime,'proxy.cjs'));
const host='gerencial.shrigma.com.br',origin='https://'+host,email='felipebandeira@oaristocrata.com',sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function originalResponse(value,url){const r=new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});Object.defineProperty(r,'url',{value:String(url)});return r;}
function catalog(brand){return {segments:[],limit:50,offset:0,catalog:{brand,current:true,currency:'BRL',timezone:'America/Sao_Paulo',shop_id:'gid://shopify/Shop/42',fields:[],products:[],origins:[],lists:[{id:1,brand,name:'ISOLATED fixture',available:true}],coverage:'unconfirmed',checked_at:'2026-10-07T22:00:00Z',catalog_hash:'a'.repeat(64)},capabilities:{draft:true,count:true,send:false}};}
async function fixture(t){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'master-audience-isolated-')),dbPath=path.join(dir,'identity.sqlite'),key='isolated-central-master-'+crypto.randomBytes(12).toString('hex');
 const env={DASHBOARD_CRM_PUBLISHED_JOURNEY_READ:'enabled',DASHBOARD_MODE:'operational',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_MANAGER_HOST:host,DASHBOARD_AREA_HOSTS:JSON.stringify({growth:'crm.shrigma.com.br',organico:'organico.shrigma.com.br',influs:'influs.shrigma.com.br'}),DASHBOARD_EMAIL_DOMAINS:'["oaristocrata.com","shrigma.com.br","fishermans.com.br"]',DASHBOARD_ADMIN_EMAIL:email,DASHBOARD_BOOTSTRAP_SHA256:sha('isolated-bootstrap'),DASHBOARD_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE:'own-master-production-v1',DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'enabled',DASHBOARD_CRM_MASTER_AUDIENCE_READ:'enabled',DASHBOARD_NATIVE_MCP:'enabled',DASHBOARD_UPSTREAMS:JSON.stringify({'crm-read':P.FIXED_DESTINATIONS['crm-read'],campaigns:P.REVIEWED_DYNAMIC.routes.campaigns,segments:P.REVIEWED_DYNAMIC.routes.segments}),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify(['comunicacao-crm-panel-read.tazdb8.easypanel.host','n8n-n8n.tazdb8.easypanel.host','comunicacao-crm-audience.tazdb8.easypanel.host']),DASHBOARD_DYNAMIC_ROUTE_MANIFEST:JSON.stringify({schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:P.REVIEWED_DYNAMIC.routes.campaigns,segments:P.REVIEWED_DYNAMIC.routes.segments}}),DASHBOARD_DB_PATH:dbPath,DASHBOARD_PUBLIC_DIR:dir};
 const settings=settingsFromEnv(env),auth=createAuth({...settings,crmNativeEnabled:true});
 t.after(()=>{auth.close();fs.rmSync(dir,{recursive:true,force:true});});
 await auth.completeBootstrap({email,token:'isolated-bootstrap',password:'Isolated-Test-Password-2026!',host,origin});
 const login=await auth.login({email,password:'Isolated-Test-Password-2026!',host,origin}),ctx={cookieHeader:login.cookie.split(';')[0],host,origin,method:'POST',csrf:login.csrf},user=auth.session(ctx).user;
 auth.setUpstreamCredential({context:ctx,userId:user.id,slot:'growth-read',bearer:key});
 await auth.activateOwnMasterCampaignWriter({context:ctx,fetchImpl:async(url,opts)=>{a.equal(opts.headers.Authorization,'Bearer '+key);return originalResponse({schema:'shrigma_access_identity_v1',role:'master',panel:'todos',owner:email,allowedPanels:['cx','growth','organico','influs'],permissions:{growth:{who:'panel:isolated-principal-2026',label:email,caps:['read_content','draft','validate','submit']},influs:null}},url);}});
 const issued=auth.nativeConnections.issue({context:ctx,brands:['fish'],scopes:['crm.read'],expiresDays:1}),native=auth.nativeConnections.context(issued.token);
 let override=null;const calls=[];
 const server=createServer(settings,{auth,fetchImpl:async(url,options)=>{
  const u=new URL(url);calls.push({url:u.href,method:options.method});a.equal(options.headers.Origin,undefined);a.equal(options.headers.Cookie,undefined);a.equal(options.headers.Authorization,'Bearer '+key);
  if(u.pathname==='/webhook/crm-template-api-242c0db6ddb8'){if(override)return override(u,options);return originalResponse({flows:[],checked_at:'2026-10-08T15:00:00Z'},u);}
  if(u.pathname==='/segments'){if(override)return override(u,options);return originalResponse(catalog(u.searchParams.get('brand')),u);}
  if(u.searchParams.get('acao')==='campanha_catalogo')return originalResponse({brand:u.searchParams.get('brand'),lists:[],templates:[],capabilities:{}},u);
  return originalResponse({_painel:'todos',_escopo:'growth',capabilities:{},data:{}},u);
 }});
 t.after(()=>server.close());
 const rpc=async(brand='fish')=>{
  const {Readable,Writable}=require('node:stream'),req=Readable.from([Buffer.from(JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'crm_journey_catalog',arguments:{brand}}}))]);req.method='POST';req.url=ENDPOINT;req.headers={host,origin,authorization:'Bearer '+issued.token,'content-type':'application/json',accept:'application/json, text/event-stream'};req.socket={remoteAddress:'isolated-native-test'};
  const chunks=[],res=new Writable({write(c,e,cb){chunks.push(Buffer.from(c));cb();}});res.statusCode=200;res.setHeader=()=>{};res.getHeader=()=>undefined;const done=new Promise(resolve=>res.once('finish',resolve));server.emit('request',req,res);await done;return {status:res.statusCode,value:JSON.parse(Buffer.concat(chunks).toString())};
 };
 const browser=async(method,p,body)=>{
  const {Readable,Writable}=require('node:stream'),req=Readable.from(body===undefined?[]:[Buffer.from(JSON.stringify(body))]);req.method=method;req.url=p;req.headers={host,cookie:ctx.cookieHeader,accept:'application/json',...(method==='POST'?{origin,'x-csrf-token':ctx.csrf}:{}),...(body?{'content-type':'application/json'}:{})};req.socket={remoteAddress:'isolated-browser-test'};
  const chunks=[],res=new Writable({write(c,e,cb){chunks.push(Buffer.from(c));cb();}});res.statusCode=200;res.setHeader=()=>{};res.getHeader=()=>undefined;const done=new Promise(resolve=>res.once('finish',resolve));server.emit('request',req,res);await done;return {status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString())};
 };
 return {env,settings,auth,ctx,key,user,issued,calls,rpc,browser,override:fn=>{override=fn;},dbPath};
}

test('same gateway and native delegation read published brand-scoped catalog using CURRENT original Master',async t=>{const f=await fixture(t),r=await f.rpc();a.equal(r.status,200);const v=r.value.result.structuredContent;a.equal(v.status,200);a.equal(v.body.contract,'crm-published-journey-read-v1');a.equal(v.body.source,'original-published-definitions');a.equal(v.body.configuredCount,0);a.equal(f.calls.length,1);a.match(f.calls[0].url,/marca=fish$/);for(const secret of [f.key,f.issued.token,f.ctx.cookieHeader,f.ctx.csrf])a.equal(JSON.stringify(r).includes(secret),false);const aristo=await f.browser('GET','/api/templates?acao=fluxos_listar&marca=aristo');a.equal(aristo.status,200);});
test('native brand scope, manager gate, missing brand and all write attempts refuse before transport',async t=>{const f=await fixture(t);a.equal((await f.rpc('aristo')).value.result.structuredContent.error,'BRAND_DENIED');for(const [method,p]of [['POST','/api/templates'],['GET','/api/templates?acao=publicar&marca=fish'],['GET','/api/templates?acao=fluxos_listar'],['GET','/api/templates?acao=fluxos_listar&marca=todas']])a.notEqual((await f.browser(method,p,method==='POST'?{}:undefined)).status,200);a.equal(f.calls.length,0);});
test('current owner credential tamper and native revocation during original READ suppress response',async t=>{for(const what of ['key','native']){const f=await fixture(t);f.override(async(u)=>{if(what==='key'){const db=new DatabaseSync(f.dbPath);db.prepare("UPDATE upstream_credentials SET key_digest=? WHERE user_id=? AND slot='growth-campaign'").run('a'.repeat(64),f.user.id);db.close();}else f.auth.nativeConnections.revoke({context:f.ctx,connectionId:f.issued.connection.id});return originalResponse({flows:[],checked_at:'2026-10-08T15:00:00Z'},u);});const r=await f.rpc();a.notEqual(r.value.result?.structuredContent?.status,200);a.equal(f.calls.length,1);}});
test('post-verifier purpose projection is separate, immutable and rejects incompatible profiles',async t=>{const f=await fixture(t),requested={DASHBOARD_CRM_PUBLISHED_JOURNEY_READ:'enabled'},preserved={...f.env};delete preserved.DASHBOARD_CRM_PUBLISHED_JOURNEY_READ;const before=JSON.stringify(preserved),next=environmentForOriginalMasterPublishedJourneyRead(requested,preserved);a.equal(JSON.stringify(preserved),before);a.equal(next.DASHBOARD_ENCRYPTION_KEY,preserved.DASHBOARD_ENCRYPTION_KEY);a.equal(settingsFromEnv(next).crmPublishedJourneyRead,true);a.equal(next.DASHBOARD_UPSTREAMS,preserved.DASHBOARD_UPSTREAMS);a.throws(()=>environmentForOriginalMasterPublishedJourneyRead(requested,{...preserved,DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE:undefined}));});

test('browser published READ needs cookie and Accept only; cross-host and missing original attestation fail before transport',async t=>{const f=await fixture(t);const result=await f.browser('GET','/api/templates?acao=fluxos_listar&marca=fish');a.equal(result.status,200);const db=new DatabaseSync(f.dbPath);db.prepare('UPDATE campaign_writer_attestation_v1 SET expires_at=1 WHERE user_id=?').run(f.user.id);db.close();a.equal((await f.browser('GET','/api/templates?acao=fluxos_listar&marca=fish')).status,403);a.equal(f.calls.length,1);});
