'use strict';
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(sourceRoot,{cacheFails=true,patchedHtml,patchedBundle,patchedRenderer,guardSource,transportOverride}={}){
 const fixtures=path.join(__dirname,'fixtures');
 const html=patchedHtml||fs.readFileSync(path.join(fixtures,'ea/growth.html'),'utf8');
 let bundle=patchedBundle||fs.readFileSync(path.join(fixtures,'ea/growth.js'),'utf8');
 const all=[],ids=new Map(),events={},requests=[],errors=[],intervals=[];
 class Element{
  constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.id=attrs.id||'';this.dataset={};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.classes=new Set((attrs.class||'').split(' ').filter(Boolean));this.classList={contains:c=>this.classes.has(c),add:c=>this.classes.add(c),remove:c=>this.classes.delete(c),toggle:(c,b)=>{if(b===undefined)b=!this.classes.has(c);b?this.classes.add(c):this.classes.delete(c);return b;}};this.style={removeProperty(){},setProperty(){}};this.hidden=Object.hasOwn(attrs,'hidden');this.disabled=Object.hasOwn(attrs,'disabled');this.value=attrs.value||'';this.checked=Object.hasOwn(attrs,'checked');this.children=[];this.listeners={};this.isConnected=true;this.textContent='';this._html='';all.push(this);if(this.id)ids.set(this.id,this);}
  set innerHTML(s){this._html=s;for(const c of this.children)c.remove();this.children=[];parse(s,this);}get innerHTML(){return this._html;}
  get options(){return this.children.filter(x=>x.tagName==='OPTION');}get selectedOptions(){return this.options.filter(x=>x.value===this.value);}
  insertAdjacentElement(_where,c){return this.parentElement?this.parentElement.appendChild(c):this.appendChild(c);}appendChild(c){this.children.push(c);c.parentElement=this;if(c.id)ids.set(c.id,c);return c;}append(c){return this.appendChild(c);}replaceChildren(){for(const c of this.children)c.remove();this.children=[];this._html='';this.textContent='';}
  remove(){this.isConnected=false;if(ids.get(this.id)===this)ids.delete(this.id);if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this);for(const c of [...this.children])c.remove();}
  setAttribute(k,v){this.attrs[k]=String(v);if(k==='id'){this.id=String(v);ids.set(this.id,this);}if(k==='hidden')this.hidden=true;}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];if(k==='hidden')this.hidden=false;}
  addEventListener(n,f){(this.listeners[n]??=[]).push(f);}removeEventListener(){}dispatchEvent(e){this['on'+e.type]?.(e);for(const f of this.listeners[e.type]||[])f(e);return true;}click(){if(this.disabled)return;this.dispatchEvent({type:'click',target:this,preventDefault(){}});}focus(){document.activeElement=this;}setSelectionRange(){}closest(sel){for(let p=this;p;p=p.parentElement)if(matches(p,sel))return p;return null;}querySelectorAll(sel){return query(sel,this);}querySelector(sel){return query(sel,this)[0]||null;}getBoundingClientRect(){return {x:0,y:0,width:800,height:500,left:0,top:0};}get clientWidth(){return 800;}get offsetWidth(){return 800;}
 }
 function matches(e,sel){const tag=sel.match(/^[a-z][\w-]*/i)?.[0];if(tag&&e.tagName!==tag.toUpperCase())return false;for(const m of sel.matchAll(/#([\w-]+)/g))if(e.id!==m[1])return false;for(const m of sel.matchAll(/\.([\w-]+)/g))if(!e.classes.has(m[1]))return false;for(const m of sel.matchAll(/\[([^=\]]+)(?:=['"]?([^'"\]]+)['"]?)?\]/g))if(!Object.hasOwn(e.attrs,m[1])||m[2]!==undefined&&e.attrs[m[1]]!==m[2])return false;return true;}
 function query(sel,root){const out=[];for(const part of sel.split(',')){const bits=part.trim().split(/\s*>\s*|\s+/),last=bits.pop();for(const e of all){if(!e.isConnected||!matches(e,last))continue;if(root){let p=e.parentElement;while(p&&p!==root)p=p.parentElement;if(!p)continue;}if(bits.length){let p=e.parentElement,okay=true;for(const bit of bits.reverse()){while(p&&!matches(p,bit))p=p.parentElement;if(!p){okay=false;break;}p=p.parentElement;}if(!okay)continue;}if(!out.includes(e))out.push(e);}}return out;}
 function parse(s,parent){const stack=[parent];for(const m of s.matchAll(/<\/?([a-z][\w:-]*)([^>]*)>/gi)){const tag=m[1].toLowerCase();if(m[0].startsWith('</')){for(let i=stack.length-1;i>0;i--)if(stack[i].tagName===tag.toUpperCase()){stack.length=i;break;}continue;}const attrs={};for(const a of m[2].matchAll(/([\w:-]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g))attrs[a[1]]=a[2]??a[3]??a[4]??'';const e=new Element(tag,attrs);stack.at(-1)?.appendChild(e);if(!['meta','link','input','img','br','hr','source'].includes(tag))stack.push(e);}}
 const document={querySelectorAll:s=>query(s),querySelector:s=>query(s)[0]||null,getElementById:id=>ids.get(id)||null,createElement:t=>new Element(t),addEventListener:(n,f)=>(events[n]??=[]).push(f),hidden:false,visibilityState:'visible',readyState:'complete',activeElement:null};parse(html,null);document.head=query('head')[0];document.body=query('body')[0];document.documentElement=query('html')[0];
 const storage=new Map(),location={origin:'https://gerencial.shrigma.com.br',href:'https://gerencial.shrigma.com.br/growth.html',hash:'',pathname:'/growth.html',search:''};
 const addEventListener=(n,f)=>(events[n]??=[]).push(f);
 const ctx={__loadErrors:errors,document,location,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},console,URL,URLSearchParams,Headers,Request,TextDecoder,TextEncoder,Uint8Array,AbortController,Response,Date,Intl,crypto:require('node:crypto').webcrypto,navigator:{language:'pt-BR'},history:{replaceState(_s,_t,u){location.hash=String(u).includes('#')?String(u).slice(String(u).indexOf('#')):'';}},addEventListener,removeEventListener(){},setTimeout,clearTimeout,setInterval:(f,n)=>{intervals.push({f,n});return intervals.length;},clearInterval(){},requestAnimationFrame:f=>{f();return 1;},cancelAnimationFrame(){},Image:class{},MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},Event:class{constructor(type){this.type=type;}},CustomEvent:class{constructor(type,x){this.type=type;this.detail=x?.detail;}},getComputedStyle:()=>({getPropertyValue:()=>''}),fetch:async(url,options)=>{requests.push({url:String(url),options});if(transportOverride){const custom=await transportOverride(String(url),options);if(custom!==undefined)return custom;}if(String(url).includes('fluxos_capacidade'))return new Response(JSON.stringify({contract:'crm-published-journey-read-v1',brand:new URL(String(url),location.origin).searchParams.get('marca'),read:true,endpoint:location.origin+'/api/templates',scope:'master-brand-scoped',readOnly:true,write:false}));if(String(url).includes('/auth/session'))return new Response(JSON.stringify({authenticated:true,user:{role:'superadmin',brandAccess:'all',brand:null,brands:['fish','aristo'],permissions:{growth:{read:true,edit:true}}},csrf:'fixture-session',uiKey:'fixture-ui',features:{publishedJourneyRead:true}}));if(String(url).includes('fluxos_listar'))return new Response(JSON.stringify({flows:[],checked_at:'2026-10-08T16:00:00Z'}));return cacheFails?new Response(JSON.stringify({error:'unavailable'}),{status:503}):new Response(JSON.stringify({_escopo:'growth',_painel:'todos',_cache_gerado_em:new Date().toISOString(),crm_campanha:[],crm_fluxo:[],crm_conversao:[],capabilities:{workflows:{published_read:true,published_read_contract:'crm-published-journey-read-v1',published_read_scope:'master-brand-scoped'},endpoints:{templates:location.origin+'/api/templates'}}}));}};
 const rawFetch=ctx.fetch;ctx.fetch=async(...args)=>{const r=await rawFetch(...args);r.json=async()=>vm.runInContext('JSON.parse('+JSON.stringify(await r.text())+')',ctx);return r;};ctx.window=ctx;ctx.parent=ctx;ctx.globalThis=ctx;ctx.window.dispatchEvent=e=>{for(const f of events[e.type]||[])f(e);};vm.createContext(ctx);
 if(patchedRenderer){const start=bundle.indexOf('const GPR='),end=bundle.indexOf('typeof module<"u"&&module.exports&&(module.exports=GPR)',start);if(start<0||end<0)throw Error('BUNDLE_RENDERER_BOUNDARY');bundle=bundle.slice(0,start)+patchedRenderer+'\n;'+bundle.slice(end+'typeof module<"u"&&module.exports&&(module.exports=GPR)'.length).replace(/^,/, ';');}
 if(guardSource)vm.runInContext(guardSource,ctx,{filename:'installed-guard.js'});vm.runInContext(bundle,ctx,{filename:'installed-growth.js',timeout:5000});vm.runInContext("shrigmaGuardaChave('growth','ui-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')",ctx);for(const s of html.matchAll(/<script\s*>([\s\S]*?)<\/script>/g))vm.runInContext(s[1].replace("}catch(e){\n    $('#load-state').hidden=true;","}catch(e){\n    __loadErrors.push({name:e.name,message:e.message,stack:e.stack});$('#load-state').hidden=true;"),ctx,{filename:'installed-growth.html',timeout:5000});
 return {ctx,document,requests,errors,intervals,html,bundle,run:s=>vm.runInContext(s,ctx),async settle(){for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));}};
}
module.exports={harness};
if(require.main===module){process.on('unhandledRejection',e=>console.log('UNHANDLED',e.stack));const h=harness(path.resolve(process.argv[2]));h.settle().then(()=>{console.log('INIT',h.run('({SEC,MARCA,api:!!API,tab:GC.activeTab})'));h.document.querySelector('#secoes button[data-s="regua"]').click();console.log('CLICK',h.run('({SEC,MARCA,api:!!API,tab:GC.activeTab})'));console.log('ROOT',h.document.getElementById('control-fluxos').innerHTML.slice(-1000));});}
