'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {harness}=require('./load-harness.cjs');
const fixtures=path.join(__dirname,'fixtures'),source=null;
const inputRoot=process.env.PUBLISHED_JOURNEY_SOURCE?path.resolve(process.env.PUBLISHED_JOURNEY_SOURCE):path.resolve(__dirname,'../..');
const build=require(path.join(inputRoot,'services/dashboard-operational/build.cjs'));
const actualHtml=build.transform(fs.readFileSync(path.join(inputRoot,'growth.html'),'utf8'),'growth.html');
const actualBundle=build.transform(fs.readFileSync(path.join(inputRoot,'assets/panels/growth.js'),'utf8'),'assets/panels/growth.js');
const guard=fs.readFileSync(path.join(fixtures,'ea/guard.js'),'utf8');
const patch={guardSource:guard,patchedHtml:actualHtml,patchedBundle:actualBundle};
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function open(h){h.document.querySelector('#seg-marca button[data-marca="fish"]').click();h.document.querySelector('#secoes button[data-s="regua"]').click();h.document.getElementById('control-tab-fluxos').click();}
function read(h){const button=h.document.getElementById('jpr-published')?.querySelector('[data-jpr-read]');assert(button&&!button.disabled);button.click();}
const result=h=>h.document.getElementById('jpr-published')?.innerHTML||'';
const journeyCalls=h=>h.requests.filter(x=>x.url.includes('fluxos_'));
test('composed final HTML equals sealed correction and full final bundle is exercised',()=>{const sealed=fs.readFileSync(path.join(fixtures,'fixed/growth.html'),'utf8');
const withoutCompilerVersion=h=>h.replace(/(assets\/panels\/growth\.js\?v=)[a-f0-9]{12}/g,'$1<compiler-version>');
assert.equal(withoutCompilerVersion(actualHtml),withoutCompilerVersion(sealed));
assert(actualHtml.includes('assets/panels/growth.js?v='+sha(fs.readFileSync(path.join(inputRoot,'assets/panels/growth.js'))).slice(0,12)));const h=harness(source,{...patch,cacheFails:false});assert.equal(h.html,actualHtml);assert.equal(h.bundle,actualBundle);assert.notEqual(sha(h.bundle),'d1525967509377eb25e0b7f80ac3dd31ba035a442bc36afb438e3b24763fad22');});
test('unmodified transformed inputs equal installed EA HTML and bundle receipt',()=>{const h=harness(source,{cacheFails:false,guardSource:guard});assert.equal(sha(h.html),'2a6d3e8e5e94c1fe1db73a49f59a73ba7c11c6ea6e23508370bd22cb12e91607');assert.equal(sha(h.bundle),'d1525967509377eb25e0b7f80ac3dd31ba035a442bc36afb438e3b24763fad22');});
test('faithful original init + failed first cache + actual section/tab clicks stays blank and refresh throws',async()=>{const h=harness(source,{cacheFails:true,guardSource:guard});await h.settle();assert.equal(h.run('API'),null);open(h);assert.equal(h.document.getElementById('control-fluxos').innerHTML,'');await assert.rejects(h.run('carregar()'),e=>e.name==='TypeError'&&e.message.includes('crm_operacao'));assert.equal(journeyCalls(h).length,0);});
for(const cacheFails of [true,false])test('guarded init/cache '+(cacheFails?'503':'200')+' and real click perform CURRENT proof then one READ',async()=>{const h=harness(source,{...patch,cacheFails});await h.settle();if(!cacheFails)assert.equal(h.errors.length,0);open(h);assert.equal(h.document.getElementById('control-fluxos').hidden,false);assert.equal(journeyCalls(h).length,0);read(h);await h.settle();assert.match(result(h),/Nenhuma jornada publicada retornada/);const calls=journeyCalls(h);assert.equal(calls.length,2);assert.match(calls[0].url,/acao=fluxos_capacidade&marca=fish$/);assert.match(calls[1].url,/acao=fluxos_listar&marca=fish$/);for(const c of calls){assert.equal(c.options.method,'GET');assert.equal(c.options.credentials,'same-origin');assert.equal(c.options.redirect,'error');assert.equal(c.options.headers.get('Authorization'),null);assert.equal(c.options.body,undefined);}assert.equal(h.requests.filter(x=>x.url.includes('/auth/session')).length,1);});
test('original 60s timer demonstrably destroys a confirmed published result',async()=>{const h=harness(source,{cacheFails:false,guardSource:guard});await h.settle();open(h);read(h);await h.settle();assert.match(result(h),/Nenhuma jornada publicada retornada/);h.intervals.find(x=>x.n===60000).f();await h.settle();assert.doesNotMatch(result(h),/Nenhuma jornada publicada retornada/);});
test('patched original 30s and 60s timers preserve current evidence; manual reload explicitly clears',async()=>{const h=harness(source,{...patch,cacheFails:false});await h.settle();open(h);read(h);await h.settle();const before=result(h),count=h.requests.length;h.intervals.find(x=>x.n===30000).f();h.intervals.find(x=>x.n===60000).f();await h.settle();assert.equal(result(h),before);assert.equal(h.requests.length,count);h.document.getElementById('btn-atualizar').click();assert.doesNotMatch(result(h),/Nenhuma jornada publicada retornada/);await h.settle();assert.equal(journeyCalls(h).length,2);});
for(const mode of ['denied','wrong-brand','write','foreign-endpoint','extra'])test('CURRENT proof '+mode+' closes READ through inherited guard',async()=>{const h=harness(source,{...patch,transportOverride:url=>{if(!url.includes('fluxos_capacidade'))return;if(mode==='denied')return new Response('{}',{status:403});const dto={contract:'crm-published-journey-read-v1',brand:'fish',read:true,endpoint:'https://gerencial.shrigma.com.br/api/templates',scope:'master-brand-scoped',readOnly:true,write:false};if(mode==='wrong-brand')dto.brand='aristo';if(mode==='write')dto.write=true;if(mode==='foreign-endpoint')dto.endpoint='https://foreign.invalid/api/templates';if(mode==='extra')dto.actor='unadmitted';return new Response(JSON.stringify(dto));}});await h.settle();open(h);read(h);await h.settle();assert.equal(journeyCalls(h).length,1);assert.match(result(h),/indisponível/);assert.doesNotMatch(result(h),/Nenhuma jornada publicada retornada/);});
test('brand change during CURRENT proof prevents old-brand READ and late display',async()=>{let resolve;const h=harness(source,{...patch,transportOverride:url=>url.includes('fluxos_capacidade')?new Promise(r=>resolve=r):undefined});await h.settle();open(h);read(h);await h.settle();h.document.querySelector('#seg-marca button[data-marca="aristo"]').click();resolve(new Response(JSON.stringify({contract:'crm-published-journey-read-v1',brand:'fish',read:true,endpoint:'https://gerencial.shrigma.com.br/api/templates',scope:'master-brand-scoped',readOnly:true,write:false})));await h.settle();assert.equal(journeyCalls(h).length,1);assert.doesNotMatch(result(h),/Nenhuma jornada publicada retornada/);assert.equal(h.run('MARCA'),'aristo');});
test('context switch/pagehide invalidate a late published READ',async()=>{for(const action of ['brand','pagehide']){let resolve;const h=harness(source,{...patch,transportOverride:url=>url.includes('fluxos_listar')?new Promise(r=>resolve=r):undefined});await h.settle();open(h);read(h);await h.settle();if(action==='brand')h.document.querySelector('#seg-marca button[data-marca="aristo"]').click();else h.ctx.dispatchEvent({type:'pagehide'});resolve(new Response(JSON.stringify({flows:[],checked_at:'2026-10-08T16:00:00Z'})));await h.settle();assert.doesNotMatch(result(h),/Nenhuma jornada publicada retornada/);}});
test('general reload failure while Journeys is open is handled without null dereference',async()=>{const h=harness(source,{...patch,cacheFails:true});await h.settle();open(h);await h.run('carregar()');assert.equal(h.run('LOADING'),false);assert(h.document.getElementById('jpr-published'));assert.equal(h.errors.filter(x=>x.name==='TypeError').length,0);});
