 'use strict';
const test=require('node:test'),a=require('node:assert/strict'),path=require('node:path'),crypto=require('node:crypto');
const root=process.env.SHRIGMA_UI_SOURCE_DIR||path.resolve(__dirname,'../..'),Client=require(path.join(root,'growth-segment-client.js')),A=require(path.join(root,'n8n/growth/segment-audience-contract.js'));
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v),hash=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
function fixture({unavailable=false}={}){
 const definition=A.normalize({schema_version:A.VERSION,brand:'fish',name:'Existing fixture audience',rule:unavailable?{op:'confirmed',rule:{op:'condition',field:'purchase.count',operator:'eq',value:0}}:{op:'in_list',list_id:1}}),record={id,brand:'fish',name:definition.name,definition,version:2,archived:false,created_at:'2026-10-07T21:00:00Z',updated_at:'2026-10-07T22:00:00Z',updated_by:'fixture-original',semantic_context:{currency:'BRL',timezone:'America/Sao_Paulo',current:false}};
 const api={capabilities:{segments:{contract_version:A.VERSION,read:true,save:true,operation:true,count:true,context_review:true,context_review_contract:'crm-audience-context-review-v2',brands:['fish','aristo']},endpoints:{segments:'https://gerencial.shrigma.com.br/api/segments'}}};
 const catalog={brand:'fish',current:true,currency:'BRL',timezone:'America/Sao_Paulo',shop_id:'gid://shopify/Shop/42',fields:unavailable?[{key:'purchase.count',available:false,source_hash:'d'.repeat(64)}]:[],...(unavailable?{shopify_snapshot:{current:false,started_at:'2020-01-01T00:00:00.000Z',observed_at:'2020-01-01T01:00:00.000Z',expires_at:'2020-01-02T02:00:00.000Z'}}:{}),products:[],origins:[],lists:[{id:1,brand:'fish',name:'Fixture list',available:true}],coverage:'unconfirmed',checked_at:new Date().toISOString(),catalog_hash:'a'.repeat(64)};
 const store=new Map(),calls=[],storage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},locks={request:async(k,o,fn)=>fn({})};let mutate=null,key='synthetic-context-actor';
 const fetch=async(url,init)=>{a.equal(init.method,'GET');const q=new URL(url).searchParams;calls.push(q.get('acao'));let body;
 if(q.get('acao')==='segmentos_listar')body={segments:[record],limit:Number(q.get('limit')),offset:Number(q.get('offset')),catalog,capabilities:{draft:true,count:true,send:false}};
 else if(q.get('acao')==='segmento_obter')body={segment:record};
 else{a.equal(q.get('acao'),'segmento_contexto_revisao');a.equal(q.get('id'),id);a.equal(q.get('expected_version'),'2');body={context_review:{schema:'crm-audience-context-review-v2',brand:'fish',id,version:2,definition_hash:hash(definition),stored_context_hash:'b'.repeat(64),current_context_hash:'c'.repeat(64),catalog_hash:catalog.catalog_hash,checked_at:new Date().toISOString(),context_current:false,changes:[{path:'base.optin',before:'single',after:'double'}],authorizes_refresh:false,transport_supported:false,source_ready:!unavailable,unavailable_fields:unavailable?['purchase.count']:[]}};mutate?.(body);}
 return new Response(JSON.stringify(body),{status:200});};
 return {api,record,store,calls,storage,locks,fetch,key:()=>key,setKey:x=>{key=x;},set mutate(x){mutate=x;}};
}
async function ready(f){const c=Client.create({api:f.api,brand:'fish',key:f.key,storage:f.storage,locks:f.locks,fetch:f.fetch});await c.list();await c.open(id);return c;}
test('client reads factual saved-context differences while retaining exact local journals',async()=>{const f=fixture(),c=await ready(f),before=JSON.stringify([...f.store]);const r=await c.reviewContext({id,version:2});a.equal(r.changes[0].path,'base.optin');a.equal(r.authorizes_refresh,false);a.equal(JSON.stringify([...f.store]),before);a.deepEqual(f.calls,['segmentos_listar','segmento_obter','segmento_contexto_revisao']);});
test('client refuses unbound definition, duplicated/arbitrary paths and outdated context metadata',async()=>{for(const mutate of [b=>b.context_review.definition_hash='f'.repeat(64),b=>b.context_review.changes.push(b.context_review.changes[0]),b=>b.context_review.changes[0].path='rules[0].source_hash',b=>b.context_review.checked_at='2000-01-01T00:00:00.000Z']){const f=fixture(),c=await ready(f),before=JSON.stringify([...f.store]);f.mutate=mutate;await a.rejects(c.reviewContext({id,version:2}),{code:'SEGMENT_CONTEXT_REVIEW_UNCONFIRMED'});a.equal(JSON.stringify([...f.store]),before);}});
test('client feature and actor withdrawal close the read without altering journals',async()=>{const f=fixture(),c=await ready(f),before=JSON.stringify([...f.store]);f.mutate=()=>f.setKey('changed-synthetic-actor');await a.rejects(c.reviewContext({id,version:2}),{code:'SEGMENT_ACCESS_CHANGED'});a.equal(JSON.stringify([...f.store]),before);const g=fixture(),d=await ready(g);const revoked=structuredClone(g.api);revoked.capabilities.segments.context_review=false;d.update(revoked);await a.rejects(d.reviewContext({id,version:2}),{code:'SEGMENT_CAPABILITY_UNAVAILABLE'});a.equal(g.calls.length,2);});
test('portal detail shows confirmed before/after and keeps stale save/count disabled',async()=>{
 const {parseHTML}=require('linkedom'),UI=require(path.join(root,'growth-segment-ui.js')),f=fixture(),{document,window}=parseHTML('<html><body><section id="segments"></section></body></html>'),element=document.querySelector('#segments');
 const ui=UI.create({element,document,key:f.key,storage:f.storage,fetch:f.fetch,locks:f.locks});await ui.sync({api:f.api,brand:'fish'});
 const idle=async()=>{for(let n=0;n<100;n++){if(!ui.contextStatus().busy)return;await new Promise(r=>setTimeout(r,2));}a.fail('context UI busy');};
 element.querySelector('[data-gs="open"]').click();await idle();const before=JSON.stringify([...f.store]);a.equal(element.querySelector('[data-gs="save"]').disabled,true);a.equal(element.querySelector('[data-gs="count"]').disabled,true);const button=element.querySelector('[data-gs="context-review"]');a.equal(button.disabled,false);button.click();await idle();a.match(element.querySelector('[data-gs-context-review]').textContent,/single → double/);a.match(element.textContent,/1 diferença/);a.equal(JSON.stringify([...f.store]),before);a.equal(element.querySelector('[data-gs="save"]').disabled,true);a.equal(element.querySelector('[data-gs="count"]').disabled,true);a.equal(f.calls.includes('segmento_criar'),false);
});

test('portal explains unavailable purchase condition and actual snapshot expiry without allowing save/count',async()=>{
 const {parseHTML}=require('linkedom'),UI=require(path.join(root,'growth-segment-ui.js')),f=fixture({unavailable:true}),{document}=parseHTML('<html><body><section id="segments"></section></body></html>'),element=document.querySelector('#segments'),ui=UI.create({element,document,key:f.key,storage:f.storage,fetch:f.fetch,locks:f.locks});await ui.sync({api:f.api,brand:'fish'});
 const idle=async()=>{for(let n=0;n<100;n++){if(!ui.contextStatus().busy)return;await new Promise(r=>setTimeout(r,2));}a.fail('context UI busy');};element.querySelector('[data-gs="open"]').click();await idle();const before=JSON.stringify([...f.store]);element.querySelector('[data-gs="context-review"]').click();await idle();a.match(element.textContent,/Condições indisponíveis/);a.match(element.querySelector('[data-gs-shopify-snapshot]').textContent,/Os dados venceram em/);a.equal(element.querySelector('[data-gs="save"]').disabled,true);a.equal(element.querySelector('[data-gs="count"]').disabled,true);a.equal(JSON.stringify([...f.store]),before);
});
