 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const out=path.resolve(__dirname,'../../n8n/growth'),input=process.env.SHRIGMA_AUDIENCE_CONTEXT_INPUTS||path.resolve(__dirname,'../../../inputs/n8n/growth');
const cache={};function load(name,candidate=true){const key=name+candidate;if(cache[key])return cache[key];const filename=path.join(candidate&&fs.existsSync(path.join(out,name))?out:input,name),m=new Module(filename);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));m.require=n=>n.startsWith('./')?load(n.slice(2),candidate):require(n);m._compile(fs.readFileSync(filename,'utf8'),filename);cache[key]=m.exports;return m.exports;}
const S=load('segment-audience-store.cjs'),Original=load('segment-audience-store.cjs',false),A=load('segment-audience-contract.js'),H=load('segment-audience-review.cjs'),C=load('segment-audience-context-review.cjs'),API=load('segment-audience-api.cjs'),Shopify=load('segment-shopify-facts.cjs');
const clone=v=>JSON.parse(JSON.stringify(v)),id='22222222-2222-4222-8222-222222222222',key='fixture-key-456',time='2026-10-07T12:00:00.000Z';
async function fixture(brand='aristo',opts={}){
 const rules=opts.list?[{op:'in_list',list_id:2}]:opts.product?[{op:'condition',field:'purchase.product',operator:'purchased',value:'gid://shopify/Product/321'}]:[{op:'condition',field:'purchase.count',operator:'gte',value:2}];
 if(opts.multi)rules.push({op:'condition',field:'email.opened',operator:'within_last_days',value:7},{op:'condition',field:'purchase.count',operator:'lt',value:20});
 const def=A.normalize({schema_version:A.VERSION,brand,name:'Fixture availability',rule:rules.length===1?rules[0]:{op:'and',rules}});
 const selected=[...new Set(A.leaves(def).filter(x=>x.rule.op!=='in_list').map(x=>x.rule.field))];
 const source={currency:'BRL',timezone:'America/Sao_Paulo',shop_id:'gid://shopify/Shop/34',fields:[],products:[{id:'gid://shopify/Product/321',brand,name:'Fixture product',available:true}],origins:[]};
 source.fields=selected.map(field=>({key:field,available:true,source_hash:Shopify.FIELDS.includes(field)?Shopify.sourceHash(brand,field,source):'a'.repeat(64)}));
 const config={brand,enabled:true,base_list_id:1,revision:1,catalog:source,checked_at:time,read_at:time,expires_at:'2026-10-07T12:04:00.000Z'},lists=[{id:1,name:'Fixture base',status:'active',optin:'single'},{id:2,name:'Fixture secondary',status:'active',optin:'double'}];
 let calls=[],auth=0,configs=0,gets=0,row,snapshotCurrent=true;
 async function query(sql,values){calls.push(sql);if(sql===S.SQL.setup)return {rows:[]};if(sql===S.SQL.boundary)return {rows:[{isolation:'read committed',timeout_ms:25000}]};if(sql===S.SQL.auth){auth++;const who=opts.actorAt===auth?'panel:changed':'panel:fixture';return {rows:[{operator:{who,caps:opts.denyAt===auth?[]:['read_content']},live_count:opts.revokeAt===auth?0:1,live_actor:who}]};}if(sql===S.SQL.config){configs++;const c=clone(config);if(opts.drift&&configs>1)c.catalog.fields[0].source_hash='f'.repeat(64);if(opts.availabilityDrift&&configs>1)c.catalog.fields.find(f=>f.key==='email.opened').available=!c.catalog.fields.find(f=>f.key==='email.opened').available;return {rows:[c]};}if(sql===S.SQL.lists)return {rows:clone(lists)};if(sql===S.SQL.shopify)return {rows:[{source:{current:snapshotCurrent,started_at:snapshotCurrent?time:'2026-10-06T08:00:00.000Z',observed_at:snapshotCurrent?time:'2026-10-06T08:01:00.000Z',expires_at:snapshotCurrent?'2026-10-08T14:00:00.000Z':'2026-10-07T10:00:00.000Z',customers:4,mapped:4,unresolved:0}}]};if(sql===S.SQL.get){gets++;return {rows:[clone(row)]};}throw Error('Unexpected SQL');}
 const historical=await S.readCatalog(query,brand),context=S.pins(def,historical);if(opts.changed)context.rules.find(r=>r.source_hash).source_hash='b'.repeat(64);
 row={id,brand,name:def.name,definition:def,definition_hash:H.digest(def),context,context_hash:H.digest(context),version:1,archived:false,created_at:time,updated_at:time,updated_by:'panel:fixture'};
 snapshotCurrent=!opts.expired;if(opts.multiUnavailable)source.fields.find(f=>f.key==='email.opened').available=false;
 if(opts.noField)source.fields=[];if(opts.noHash){source.fields[0].source_hash=null;source.fields[0].available=false;}if(opts.badHash)source.fields[0].source_hash='invalid';if(opts.productUnavailable)source.products[0].available=false;if(opts.productMissing)source.products=[];if(opts.baseUnavailable)lists[0].status='inactive';if(opts.listUnavailable)lists[1].status='inactive';if(opts.noShop)source.shop_id=null;
 configs=0;const current=await S.readCatalog(query,brand);configs=0;calls=[];
 const initial=clone(row),request={acao:'segmento_contexto_revisao',brand,id,expected_version:1,expected_catalog_hash:current.catalog.catalog_hash};
 const store=S.createAudienceStore({transaction:fn=>fn({query}),refreshCatalog:()=>{throw Error('refresh forbidden');},countProvider:()=>{throw Error('count forbidden');}});
 const result=await store.execute({key,request});assert.deepEqual(row,initial);assert(calls.every(q=>[S.SQL.setup,S.SQL.boundary,S.SQL.auth,S.SQL.config,S.SQL.lists,S.SQL.shopify,S.SQL.get].includes(q)));return {result,request,def,current,calls};
}
test('seven input pins exact; original SQL/helpers/count-save tail preserved',()=>{const manifest=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../../SOURCE-INPUTS.json')));const crypto=require('node:crypto');for(const f of manifest.inputs){const b=fs.readFileSync(path.resolve(input,'../../..','inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex'),f.gitBlobSha1);}assert.deepEqual(S.SQL,Original.SQL);for(const n of ['readAuth','readCatalog','pins','sourceConfig','publicSegment','countResult'])assert.equal(String(S[n]),String(Original[n]));const original=fs.readFileSync(path.join(input,'segment-audience-store.cjs'),'utf8'),candidate=fs.readFileSync(path.join(out,'segment-audience-store.cjs'),'utf8'),marker='   if(writing)await query(SQL.lock,[first.actor,p.idempotency_key]);';assert.equal(candidate.slice(candidate.indexOf(marker)),original.slice(original.indexOf(marker)));});
for(const brand of ['fish','aristo'])for(const changed of [false,true])test(`${brand} expired native source with ${changed?'changed':'same'} context pins`,async()=>{const f=await fixture(brand,{expired:true,changed});assert.equal(f.result._http,200);const r=f.result._body.context_review;assert.equal(r.schema,'crm-audience-context-review-v2');assert.equal(r.context_current,!changed);assert.equal(r.source_ready,false);assert.deepEqual(r.unavailable_fields,['purchase.count']);assert.equal(r.authorizes_refresh,false);assert.equal(r.transport_supported,false);assert.equal(r.changes.length,changed?1:0);assert.equal(f.current.catalog.current,true);assert.equal(f.current.catalog.shopify_snapshot.current,false);assert.equal(A.checkCatalog(f.def,f.current.catalog).ok,false);assert.throws(()=>S.pins(f.def,f.current),{code:'SEGMENT_LIST_UNAVAILABLE'});assert.throws(()=>Original.pins(f.def,f.current),{code:'SEGMENT_LIST_UNAVAILABLE'});C.validateResponse({status:200,body:f.result._body},f.request,{definition:f.def,secrets:[key]});});
test('ready source and separate hash mismatch remain factual',async()=>{const f=await fixture('fish',{changed:true});const r=f.result._body.context_review;assert.equal(f.result._http,200);assert.equal(r.source_ready,true);assert.equal(r.context_current,false);assert.deepEqual(r.unavailable_fields,[]);});
test('typed unavailable fields unique and ordered despite repeated leaves',async()=>{const f=await fixture('aristo',{expired:true,multi:true,multiUnavailable:true});assert.equal(f.result._http,200);assert.deepEqual(f.result._body.context_review.unavailable_fields,['email.opened','purchase.count']);});
for(const opts of [{noField:true},{noHash:true},{badHash:true},{expired:true,product:true,productUnavailable:true},{expired:true,product:true,productMissing:true},{expired:true,noShop:true},{list:true,listUnavailable:true}])test('missing pin or reference closes '+JSON.stringify(opts),async()=>{const f=await fixture('aristo',opts);assert.equal(f.result._http,opts.badHash?503:422);assert.equal(f.result._body.error,opts.badHash?'SEGMENT_UNAVAILABLE':'SEGMENT_LIST_UNAVAILABLE');});
test('unavailable base remains fixed refusal',async()=>{const f=await fixture('aristo',{expired:true,baseUnavailable:true});assert.equal(f.result._http,503);assert.equal(f.result._body.error,'SEGMENT_UNAVAILABLE');});
test('expired product source still requires available selected product',async()=>{const f=await fixture('aristo',{expired:true,product:true});assert.equal(f.result._http,200);assert.deepEqual(f.result._body.context_review.unavailable_fields,['purchase.product']);});
for(const opts of [{drift:true},{multi:true,availabilityDrift:true}])test('availability metadata drift across await '+JSON.stringify(opts),async()=>{const f=await fixture('aristo',{expired:true,...opts});assert.equal(f.result._http,409);assert.equal(f.result._body.error,'SEGMENT_CATALOG_CHANGED');});
for(const field of ['actorAt','denyAt','revokeAt'])for(const at of [4,6])test('unavailable READ auth boundary '+field+at,async()=>{const f=await fixture('aristo',{expired:true,[field]:at});assert.equal(f.result._http,field==='denyAt'?403:401);});
test('v2 availability projection closes unknown, duplicates, foreign fields and wrong truth table',async()=>{const f=await fixture('aristo',{expired:true,multi:true,multiUnavailable:true});for(const mutate of [b=>b.context_review.extra=1,b=>b.context_review.unavailable_fields=['purchase.count','purchase.count'],b=>b.context_review.unavailable_fields=['purchase.count','email.opened'],b=>b.context_review.unavailable_fields=['purchase.amount'],b=>b.context_review.unavailable_fields=['unknown'],b=>b.context_review.unavailable_fields=[null],b=>b.context_review.source_ready=true,b=>b.context_review.unavailable_fields.push(key)]){const b=clone(f.result._body);mutate(b);assert.throws(()=>C.validateResponse({status:200,body:b},f.request,{definition:f.def,secrets:[key]}),{code:'SEGMENT_READBACK_UNCONFIRMED'});}assert.throws(()=>C.validateResponse({status:200,body:f.result._body},f.request,{definition_hash:H.digest(f.def)}));assert.throws(()=>C.validateBody(clone(f.result._body),f.request));const safe=C.validateResponse({status:200,body:f.result._body},f.request,{definition:f.def});assert(Object.isFrozen(safe.body.context_review.unavailable_fields));});
test('HTTP source-produced body keeps private definition custody; serialized clone requires trusted definition',async()=>{const f=await fixture('aristo',{expired:true});const entry=API.parse({method:'GET',request:{headers:{Authorization:'Bearer '+key},query:{...f.request,expected_version:'1'}}});assert.equal(API.project(entry,f.result).body.context_review.source_ready,false);assert.throws(()=>API.project(entry,clone(f.result)));const api=API.createAudienceAPI({store:{execute:async()=>f.result}});assert.equal((await api.handle({method:'GET',request:{headers:{Authorization:'Bearer '+key},query:f.request}})).status,200);});

test('availability array cannot carry prototypes, getters, extras or secret echoes',async()=>{const f=await fixture('aristo',{expired:true});for(const kind of ['prototype','getter','extra','sparse','secret']){const b=clone(f.result._body),a=b.context_review.unavailable_fields;if(kind==='prototype')Object.setPrototypeOf(a,{injected:true});if(kind==='getter')Object.defineProperty(a,'0',{enumerable:true,get(){throw Error('must not read');}});if(kind==='extra')a.extra=key;if(kind==='sparse')delete a[0];if(kind==='secret')a[0]=key;assert.throws(()=>C.validateResponse({status:200,body:b},f.request,{definition:f.def,secrets:[key]}),{code:'SEGMENT_READBACK_UNCONFIRMED'});}});
test('error projection remains fixed despite new availability metadata',async()=>{const f=await fixture('aristo',{expired:true,noHash:true});const safe=C.validateResponse({status:f.result._http,body:f.result._body},f.request);assert.equal(safe.status,422);assert.deepEqual(safe.body,{error:'SEGMENT_LIST_UNAVAILABLE'});assert.throws(()=>C.validateResponse({status:422,body:{error:'SEGMENT_LIST_UNAVAILABLE',unavailable_fields:['purchase.count']}},f.request));});
