'use strict';
// Inert import; actual native execution requires a NEW labelled CI cluster.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const IMAGE='ghcr.io/bandssz/shrigma-dash-operational-canary@sha256:5ca20e4ea134b7a1a139b80c74a65573a4386d9584fcac40aeedaeb9cf8fe815';
const PG_IMAGE='postgres:17.10@sha256:7958605b474b3d264a969cb3a123d6aa00ad1e1fe9da8a69984dabb704d93317';
const CONNECT=Object.freeze({host:'comunicacao_postgres',port:5432,database:'listmonk',ssl:false,application_name:'shrigma-writer-broker-native-only',connectionTimeoutMillis:3000,query_timeout:8000,options:'-c search_path=pg_catalog -c statement_timeout=6000 -c lock_timeout=500 -c idle_in_transaction_session_timeout=6000'});
const PINS=Object.freeze({"services/crm-manager-writer/server.cjs":"29aa506d959afa8915e279ea106f0a011f194c2bbaf7c197c01dd957c2e2b3a0","services/crm-manager-writer/wire.cjs":"279fc4e59cd7cdabd61f467cb9b0681fedf262c14609730f6b80a27643b2d57f","services/crm-manager-writer/admission.cjs":"46b0e2a3c75f723e91b9ad3de097517fadc203db0d0241d5389c4241a4413425","services/dashboard-operational/crm-manager-writer-client.cjs":"d8a082c9e7527b87620e84d5a17580103fd95333dc2f7a9832cf2ebc60771f67","services/dashboard-operational/crm-manager-writer-policy.cjs":"fbfcc642c43243cb53b081bf018782f3191317d976ecc73111e9583562e83703","services/dashboard-operational/crm-manager-provisioning.cjs":"723bca94435efe08bea98fdd3ceec450264b7e7001d57c42f7a427384ec087a5","tools/crm-manager-writer-review/writer-policy.cjs":"fbfcc642c43243cb53b081bf018782f3191317d976ecc73111e9583562e83703","tools/crm-manager-writer-review/writer-provision-v1.sql":"0db3c19b63537a7fdda8987675f8fe157effe38be103681d258aa3775554ba04","tools/crm-manager-writer-review/writer-empty-rollback-v1.sql":"19a3714bb989047a8ad304ef05d88a916ef841705d69b003b2cc828571164ecd","tools/crm-manager-writer-review/writer-provision.test.cjs":"bd124b8e9994bc3b829c196538f9b04bf0e97f77b99ab636820e571adda0c189","tests/crm-manager-provision-postgres.test.cjs":"49520781a50c1488a2a3d37d18ae3a3d435d35d408dd133c59a32c5e1316c2e2","n8n/access/crm-manager-provision-v1.sql":"be6d670b90cd30977bc0ad2ffd8e7bd2e1d67d58727ef9fa616c2d07c2b813b4","n8n/access/panel-operator.sql":"7b1ab4bb657c6109337355c9a615c0fe5ff6a9837e69ef181ab1806d307446e8"});
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
function fail(){throw Error('WRITER_BROKER_NATIVE_REFUSED');}
function checkedSources(root){
 if(typeof root!=='string'||!path.isAbsolute(root))fail();
 for(const [file,pin]of Object.entries(PINS)){const p=path.join(root,file),s=fs.lstatSync(p);if(!s.isFile()||s.isSymbolicLink()||sha(fs.readFileSync(p))!==pin)fail();}
 return true;
}
function guard({proc=process,f=fs}={}){
 if(proc.platform!=='linux'||proc.getuid()!==1000||proc.getgid()!==1000||proc.versions.node.split('.')[0]!=='22'||proc.env.CRM_WRITER_BROKER_NATIVE_PROOF!=='1'||!/^shrigma-writer-broker-[a-f0-9]{16}$/.test(proc.env.CRM_WRITER_BROKER_CLUSTER||''))fail();
 const status=f.readFileSync('/proc/self/status','utf8');for(const k of ['CapEff','CapPrm','CapBnd'])if(!new RegExp('^'+k+':\\s*0+$','m').test(status))fail();if(!/^NoNewPrivs:\s*1$/m.test(status))fail();
 const integer=v=>{if(!/^[1-9][0-9]*$/.test(v.trim()))fail();return BigInt(v.trim());};
 if(integer(f.readFileSync('/sys/fs/cgroup/memory.max','utf8'))>335544320n||integer(f.readFileSync('/sys/fs/cgroup/pids.max','utf8'))>64n)fail();
 const cpu=f.readFileSync('/sys/fs/cgroup/cpu.max','utf8').trim().split(/\s+/);if(cpu.length!==2||integer(cpu[0])*100n>integer(cpu[1])*35n)fail();
 const mounts=f.readFileSync('/proc/self/mountinfo','utf8').split('\n').filter(Boolean).map(s=>s.split(' '));
 for(const point of ['/','/proof']){const m=mounts.filter(p=>p[4]===point);if(m.length!==1||!m[0][5].split(',').includes('ro'))fail();}
 if(mounts.some(p=>/docker\.sock|\.ssh|\.aws|dashboard-data/.test(p[4])))fail();
 for(const name of Object.keys(proc.env))if(name.startsWith('PG')&&name!=='PG_ADMIN_PASSWORD')fail();
 return true;
}
async function checked(t,name,fn){let failed=false;await t.test(name,async()=>{try{await fn();}catch{failed=true;throw Error('WRITER_BROKER_NATIVE_FAILED');}});if(failed)throw Error('WRITER_BROKER_NATIVE_FAILED');}
async function prove(t){
 guard();const root=path.resolve(__dirname,'../../..');checkedSources(root);
 const pg=require('pg');assert.equal(require('pg/package.json').version,'8.13.1');
 const S=require(path.join(root,'services/crm-manager-writer/server.cjs')),C=require(path.join(root,'services/dashboard-operational/crm-manager-writer-client.cjs'));
 const R=require(path.join(root,'tests/crm-manager-provision-postgres.test.cjs')),F=require(path.join(root,'tools/crm-manager-writer-review/writer-provision.test.cjs'));
 let adminPassword=process.env.PG_ADMIN_PASSWORD;delete process.env.PG_ADMIN_PASSWORD;if(typeof adminPassword!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(adminPassword))fail();
 const cluster=process.env.CRM_WRITER_BROKER_CLUSTER,issuerId=crypto.randomUUID(),namespaceId=crypto.randomUUID();
 const servicePassword=crypto.randomBytes(32).toString('base64url'),token=crypto.randomBytes(32).toString('base64url'),salt=crypto.randomBytes(16),salted=crypto.pbkdf2Sync(servicePassword,salt,4096,32,'sha256');
 const stored=crypto.createHash('sha256').update(crypto.createHmac('sha256',salted).update('Client Key').digest()).digest(),serverKey=crypto.createHmac('sha256',salted).update('Server Key').digest();
 const verifier='SCRAM-SHA-256$4096:'+salt.toString('base64')+'$'+stored.toString('base64')+':'+serverKey.toString('base64');
 class QuietClient extends pg.Client{constructor(c){super(c);this.on('error',()=>{});}}
 async function identity(c,user){const p=c.connectionParameters;assert.deepEqual({host:p.host,port:p.port,database:p.database,user:p.user,ssl:p.ssl},{host:CONNECT.host,port:5432,database:'listmonk',user,ssl:false});const row=(await c.query("SELECT current_database() AS db,current_user AS actor,session_user AS session_role,current_setting('server_version_num') AS version,inet_server_port() AS port,current_setting('cluster_name') AS cluster,current_setting('ssl') AS ssl,coalesce((SELECT ssl FROM pg_stat_ssl WHERE pid=pg_backend_pid()),true) AS session_ssl")).rows[0];assert.deepEqual(row,{db:'listmonk',actor:user,session_role:user,version:'170010',port:5432,cluster,ssl:'off',session_ssl:false});}
 async function connect(user='postgres',password=adminPassword){const c=new QuietClient({...CONNECT,user,password});try{await c.connect();await identity(c,user);return c;}catch{try{await c.end();}catch{}throw Error('WRITER_BROKER_NATIVE_FAILED');}}
 let db,f,pool,app,port;const rpcCalls=[],wrapped=new WeakSet();
 class NativeEngine{constructor(){this.client=null;this.waitReady=connect().then(async c=>{this.client=c;const q=(await c.query("SELECT (SELECT count(*)::int FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND c.relkind IN ('r','p','v','m','S','f')) AS relations,(SELECT count(*)::int FROM pg_roles WHERE rolname IN ('central_leitor','crm_manager_fixture_a','crm_manager_fixture_b','crm_manager_writer_owner_v1','crm_manager_writer_service_v1')) AS fixture_roles,(SELECT count(*)::int FROM pg_default_acl) AS default_acls,(SELECT count(*)::int FROM pg_proc WHERE pronamespace='public'::regnamespace) AS public_functions,(SELECT count(*)::int FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname NOT IN ('public','information_schema')) AS extra_schemas")).rows[0];assert.deepEqual(q,{relations:0,fixture_roles:0,default_acls:0,public_functions:0,extra_schemas:0});});}exec(s){return this.client.query(s);}query(s,a){return this.client.query(s,a);}close(){return this.client?.end();}}
 const args=()=>({operationId:crypto.randomUUID(),userId:crypto.randomUUID(),lifecycleId:crypto.randomUUID(),owner:'synthetic-writer@oaristocrata.com',brand:'fish',principalId:'dcrmw-'+crypto.randomBytes(16).toString('hex'),keySha256:sha(crypto.randomBytes(32))});
 async function http(method,url,body,headers={}){return new Promise((resolve,reject)=>{const bytes=body?Buffer.from(S.canonical(body)):null;const req=require('node:http').request({host:'127.0.0.1',port,path:url,method,timeout:5000,headers:{host:S.HOST,...(body?{authorization:'CRM-Writer-Provisioner '+token,'content-type':'application/json; charset=utf-8','content-length':bytes.length}:{}),...headers}},res=>{let size=0;const chunks=[];res.on('data',b=>{size+=b.length;if(size>8192)req.destroy();else chunks.push(b);});res.on('end',()=>{try{const raw=new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks));assert.equal(S.containsSecret(JSON.parse(raw),[adminPassword,servicePassword,token,verifier]),false);resolve({status:res.statusCode,body:JSON.parse(raw)});}catch{reject(Error('WRITER_BROKER_NATIVE_FAILED'));}});res.on('error',()=>reject(Error('WRITER_BROKER_NATIVE_FAILED')));});req.on('error',()=>reject(Error('WRITER_BROKER_NATIVE_FAILED')));req.on('timeout',()=>req.destroy());req.end(bytes);});}
 function client(dropOperation){return C.createWriterClient({issuerId,namespaceId,allowedEmailDomains:['oaristocrata.com','shrigma.com.br','fishermans.com.br'],now:Date.now,invoke:async q=>{const command=JSON.parse(q.parameters[0]),route=Object.entries(S.ROUTES).find(([,a])=>a.includes(command.action))[0],reply=await http('POST',route,command);assert.equal(reply.status,200);if(command.operationId===dropOperation&&command.action==='prepare_writer')throw Error('SYNTHETIC_LOST_ACK_AFTER_REAL_HTTP_REPLY');return reply.body;}});}
 try{
  await checked(t,'own PG17.10 SCRAM/listmonk empty guard before unchanged public fixture SQL',async()=>{f=await F.createWriterFixture({after:()=>{}},{Engine:NativeEngine,readFixture:R.createFixture,register:false});db=f.db;assert.equal(await f.profile(),S.PROFILE);await f.unchanged();});
  await checked(t,'synthetic own LOGIN SCRAM and actual service metadata; inactive issuer cannot PREP',async()=>{
   await db.query("SET log_statement='none';SET log_min_error_statement='panic';SET log_parameter_max_length=0;SET log_parameter_max_length_on_error=0;SET log_min_duration_statement=-1;SET log_min_duration_sample=-1;SET log_transaction_sample_rate=0;");
   assert.deepEqual((await db.query("SELECT current_setting('log_statement')='none' AND current_setting('log_min_error_statement')='panic' AND current_setting('log_parameter_max_length')='0' AND current_setting('log_parameter_max_length_on_error')='0' AS safe")).rows,[{safe:true}]);
   await db.query("SELECT set_config('shrigma.synthetic.writer.scram',$1,false)",[verifier]);await db.query("DO $$BEGIN EXECUTE format('ALTER ROLE crm_manager_writer_service_v1 LOGIN PASSWORD %L',current_setting('shrigma.synthetic.writer.scram'));END$$;RESET shrigma.synthetic.writer.scram;");
   await db.query('INSERT INTO public.crm_manager_writer_issuer_v1(issuer_id,namespace_id,login_role,allowed_email_domains,active) VALUES($1,$2,$3,$4::text[],false)',[issuerId,namespaceId,S.ROLE,['oaristocrata.com','shrigma.com.br','fishermans.com.br']]);
   const wrong=new QuietClient({...CONNECT,user:S.ROLE,password:servicePassword+'wrong'});try{await assert.rejects(wrong.connect(),e=>e?.code==='28P01');}finally{try{await wrong.end();}catch{}}
   const c=await connect(S.ROLE,servicePassword);try{const meta=(await c.query(S.admissionSql(false))).rows[0];assert.deepEqual(meta,Object.fromEntries(S.ADMISSION_KEYS.map(k=>[k,true])));const q={schema:S.REQUEST,issuerId,namespaceId,action:'writer_status',operationId:crypto.randomUUID(),expectedRequestSha256:'0'.repeat(64)};assert.equal((await c.query(S.QUERIES.writer_status,[S.canonical(q)])).rows[0].body.code,'ISSUER_DENIED');for(const table of ['crm_manager_writer_issuer_v1','crm_dash_chave','shrigma_panel_permission_v1'])await assert.rejects(c.query('SELECT * FROM public.'+table),e=>e?.code==='42501');}finally{await c.end();}assert.equal(await f.profile(),S.PROFILE);
  });
  const env={CRM_WRITER_ENABLED:'true',CRM_WRITER_REVISION:'24d4a7de26b52ae4479a364f50c91cb6a853d17d',CRM_WRITER_ISSUER_ID:issuerId,CRM_WRITER_NAMESPACE_ID:namespaceId,CRM_WRITER_PROVISIONER_TOKEN:token,CRM_WRITER_PG_TLS:'false',PGHOST:CONNECT.host,PGPORT:'5432',PGDATABASE:'listmonk',PGUSER:'crm_manager_writer_service_v1',PGPASSWORD:servicePassword};
  await checked(t,'real pool/HTTP health stays closed before issuer active, admits only private fixed routes after',async()=>{
   const cfg=S.config(env);pool=new pg.Pool(cfg.pg);pool.on('error',()=>{});const realConnect=pool.connect.bind(pool);pool.connect=async()=>{const c=await realConnect();if(!wrapped.has(c)){wrapped.add(c);const realQuery=c.query.bind(c);c.query=async(sql,p)=>{if(Object.values(S.QUERIES).includes(sql))rpcCalls.push({sql,operationId:JSON.parse(p[0]).operationId});return realQuery(sql,p);};}return c;};
   const {pg:unused,port:unusedPort,...opts}=cfg;app=S.createServer({...opts,pool});await new Promise((resolve,reject)=>{app.server.once('error',()=>reject(Error('WRITER_BROKER_NATIVE_FAILED')));app.server.listen(0,'127.0.0.1',resolve);});port=app.server.address().port;
   assert.equal((await http('GET','/healthz')).status,503);assert.equal((await db.query('SELECT count(*)::int AS n FROM public.crm_manager_writer_operation_v1')).rows[0].n,0);
   await db.query('UPDATE public.crm_manager_writer_issuer_v1 SET active=true WHERE issuer_id=$1',[issuerId]);const h=await http('GET','/healthz');assert.equal(h.status,200);assert.equal(h.body.ready,true);assert.equal(h.body.policy.writerCaps4,true);
   const before=rpcCalls.length,q=client().command('prepare_writer',args());assert.equal((await http('POST','/internal/v1/crm-writers/prepare',q,{origin:'https://browser.invalid'})).status,403);assert.equal((await http('POST','/internal/v1/crm-writers/prepare',q,{host:'elsewhere.invalid'})).status,403);assert.equal(rpcCalls.length,before);
  });
  let q,p,committed;
  await checked(t,'real BFF client→HTTP→actual PG role prepare/commit exact caps4; no READ/admin changes',async()=>{
   const c=client();q=c.command('prepare_writer',args());p=await c.prepare(q);assert.equal((await f.key(q)).ativo,false);assert.deepEqual(await f.permissions(q),[{area:'growth',caps:['read_content','draft','validate','submit']}]);const cq=c.command('commit_writer',{...args(),userId:q.userId,lifecycleId:q.lifecycleId,owner:q.owner,principalId:q.principalId,keySha256:q.keySha256,prepareOperationId:q.operationId,generation:1,expectedGeneration:0,issuedAt:p.issuedAt,candidateExpiresAt:p.candidateExpiresAt,expiresAt:p.expiresAt});committed=await c.commit({operationId:cq.operationId,proof:p,expectedRequest:cq});assert.equal(committed.expiresAt,p.expiresAt);assert.equal(committed.expiresAt-committed.issuedAt,1209600000);assert.equal((await f.key(q)).ativo,true);assert.deepEqual((await c.status(cq)).receipt,committed);await f.unchanged();
  });
  await checked(t,'lost ACK STATUS same operation and expired historical receipt never cause another PREP',async()=>{
   const op=crypto.randomUUID(),c=client(op),lost=c.command('prepare_writer',{...args(),operationId:op});await assert.rejects(c.prepare(lost),e=>e?.message==='SYNTHETIC_LOST_ACK_AFTER_REAL_HTTP_REPLY');const historical=await c.status(lost,{requireFound:true}),before=rpcCalls.filter(r=>r.sql===S.QUERIES.prepare_writer&&r.operationId===op).length;assert.equal(before,1);await f.age(lost);assert.deepEqual((await c.status(lost)).receipt,historical.receipt);assert.equal(rpcCalls.filter(r=>r.sql===S.QUERIES.prepare_writer&&r.operationId===op).length,1);assert.equal((await f.key(lost)).ativo,false);const rv=c.command('revoke_writer',{operationId:crypto.randomUUID(),userId:lost.userId,lifecycleId:lost.lifecycleId,owner:lost.owner});assert.equal((await c.revoke(rv)).allGenerationsRevoked,true);await f.unchanged();
  });
  await checked(t,'renew prepare and lifecycle revoke preserve TTL, history and READ/legacy; no direct service DML',async()=>{const c=client(),renew=c.command('renew_writer',{...args(),userId:q.userId,lifecycleId:q.lifecycleId,owner:q.owner,generation:2,expectedGeneration:1});assert.equal((await c.prepare(renew)).state,'prepared');assert.equal((await f.key(q)).ativo,true);assert.equal((await f.key(renew)).ativo,false);const rv=c.command('revoke_writer',{operationId:crypto.randomUUID(),userId:q.userId,lifecycleId:q.lifecycleId,owner:q.owner});assert.equal((await c.revoke(rv)).allGenerationsRevoked,true);assert.equal((await f.key(q)).ativo,false);assert.equal((await f.key(renew)).ativo,false);await f.unchanged();});
  await checked(t,'catalog drift refuses before mutation; disabled issuer/NOLOGIN retains receipts',async()=>{
   const before=rpcCalls.length;await db.query('ALTER FUNCTION public.crm_manager_writer_prepare_v1(jsonb) IMMUTABLE');assert.equal((await http('GET','/healthz')).status,503);assert.equal(rpcCalls.length,before);await db.query('ALTER FUNCTION public.crm_manager_writer_prepare_v1(jsonb) VOLATILE');assert.equal(await f.profile(),S.PROFILE);const receipts=(await db.query('SELECT operation_id,request_sha256,response FROM public.crm_manager_writer_operation_v1 ORDER BY operation_id')).rows;
   await app.stop();await pool.end();app=null;pool=null;await db.query('UPDATE public.crm_manager_writer_issuer_v1 SET active=false WHERE issuer_id=$1',[issuerId]);await db.query('ALTER ROLE crm_manager_writer_service_v1 NOLOGIN');assert.deepEqual((await db.query('SELECT operation_id,request_sha256,response FROM public.crm_manager_writer_operation_v1 ORDER BY operation_id')).rows,receipts);assert.equal((await db.query("SELECT rolcanlogin FROM pg_roles WHERE rolname='crm_manager_writer_service_v1'")).rows[0].rolcanlogin,false);await f.unchanged();
  });
  t.diagnostic(JSON.stringify({schema:'shrigma-crm-writer-broker-native-v1',actualPg1710:true,actualSCRAM:true,actualServiceAdmission:true,privateHttpFlow:true,coreVerified:true,caps4Only:true,lostAckStatusOnly:true,readLegacyPreserved:true,productionConnected:false}));
 }finally{try{await app?.stop();}catch{}try{await pool?.end();}catch{}try{await db?.close();}catch{}adminPassword='';}
}
if(require.main===module){const test=require('node:test');if(process.argv.includes('--pure')){
 test('native entry rejects missing opt-in before any pg load',()=>assert.throws(()=>guard({proc:{platform:'linux',getuid:()=>1000,getgid:()=>1000,versions:{node:'22.23.3'},env:{}},f:{readFileSync(){throw Error('NO_FILES_BEFORE_OPTIN');}}}),/WRITER_BROKER_NATIVE_REFUSED/));
 test('native artifact and public SQL/broker/client pins resolve without PG',()=>assert.equal(checkedSources(process.env.CRM_WRITER_BROKER_SOURCE_ROOT||path.resolve(__dirname,'../../..')),true));
 test('native plan fixes separate listmonk alias/SCRAM digest; it does not reuse old NOLOGIN fixture',()=>{assert.equal(CONNECT.host,'comunicacao_postgres');assert.equal(CONNECT.database,'listmonk');assert.equal(CONNECT.port,5432);assert.ok(PG_IMAGE.endsWith('@sha256:7958605b474b3d264a969cb3a123d6aa00ad1e1fe9da8a69984dabb704d93317'));assert.ok(IMAGE.endsWith('@sha256:5ca20e4ea134b7a1a139b80c74a65573a4386d9584fcac40aeedaeb9cf8fe815'));});
 }else test('new isolated WRITER broker native proof',{timeout:120000},async t=>{try{await prove(t);}catch{throw Error('WRITER_BROKER_NATIVE_FAILED');}});}
module.exports=Object.freeze({prove,guard,checkedSources,CONNECT,PINS,IMAGE,PG_IMAGE});
