'use strict';
// ROOT ISOLATED CI ONLY. No connector/network/environment/DB creation here.
// This checks capsule SQL inside a transaction that is ALWAYS rolled back.
// It intentionally does not manufacture or exercise real APPLY authority.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const product=path.resolve(__dirname,'../../services/dashboard-operational/own-foundation'),F=require(product+'/foundation.cjs'),Q=require(product+'/sql.cjs'),M=JSON.parse(fs.readFileSync(product+'/manifest.json'));
const bytes=fs.readFileSync(product+'/bootstrap-v1.sql');if(crypto.createHash('sha256').update(bytes).digest('hex')!==F.capsuleHash)throw Error('ISOLATED_CAPSULE_PIN_REFUSED');const capsule=bytes.toString('utf8').split('\n--@@\n').map(x=>x.trim());
const BASELINE=`SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.jsonb_build_object(
 'schemas',(SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(n.oid,n.nspname,n.nspowner,n.nspacl) ORDER BY n.oid) FROM pg_catalog.pg_namespace n WHERE n.nspname NOT LIKE 'pg_%'),
 'relations',(SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(c.oid,c.relnamespace,c.relname,c.relkind,c.relowner,c.relacl,c.relrowsecurity,c.relforcerowsecurity,c.relchecks) ORDER BY c.oid) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname NOT LIKE 'pg_%'),
 'columns',(SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(a.attrelid,a.attnum,a.attname,a.atttypid,a.attnotnull,a.atthasdef,a.attacl) ORDER BY a.attrelid,a.attnum) FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname NOT LIKE 'pg_%' AND a.attnum>0),
 'constraints',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(c) ORDER BY c.oid) FROM pg_catalog.pg_constraint c),
 'routines',(SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(p.oid,p.pronamespace,p.proname,p.proowner,p.proacl,p.proargtypes,p.prorettype,p.prosecdef,p.provolatile,pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(p.prosrc,'UTF8')),'hex'),pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(COALESCE(p.proconfig::text,''),'UTF8')),'hex')) ORDER BY p.oid) FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname NOT LIKE 'pg_%'),
 'roles',(SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(r.oid,r.rolname,r.rolcanlogin,r.rolsuper,r.rolcreatedb,r.rolcreaterole,r.rolinherit,r.rolreplication,r.rolbypassrls,pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(COALESCE(r.rolconfig::text,''),'UTF8')),'hex')) ORDER BY r.oid) FROM pg_catalog.pg_roles r),
 'memberships',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(m) ORDER BY m.roleid,m.member,m.grantor) FROM pg_catalog.pg_auth_members m),
 'defaultAcls',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) ORDER BY d.oid) FROM pg_catalog.pg_default_acl d)
 )::text,'UTF8')),'hex') AS fingerprint`;
async function runIsolatedCapsuleRollback({attestation,client,getTransactionState}={}){if(!attestation||attestation.isolated!==true||attestation.production!==false||attestation.existingDatabase!=='listmonk'||attestation.pgMajor!==17||attestation.allowTransactionRolledBackCapsule!==true||typeof client?.query!=='function'||typeof getTransactionState!=='function')throw Error('ISOLATED_FOUNDATION_HARNESS_OFF');
 const query=async(sql,params,command,state)=>{const r=await client.query(sql,params);if(!r||r.command!==command||!Array.isArray(r.rows)||getTransactionState()!==state)throw Error('ISOLATED_FOUNDATION_PROTOCOL_REFUSED');return r.rows;};let begun=false;
 try{if(getTransactionState()!=='I')throw Error('ISOLATED_FOUNDATION_NOT_IDLE');const before=(await query(BASELINE,undefined,'SELECT','I'))[0]?.fingerprint;if(!/^[a-f0-9]{64}$/.test(before||''))throw Error('ISOLATED_FOUNDATION_BASELINE_REFUSED');await query(Q.BEGIN_WRITE,undefined,'BEGIN','T');begun=true;const inv=(await query(Q.INVENTORY,undefined,'SELECT','T'))[0];if(!inv||inv.database!=='listmonk'||Math.floor(inv.engine/10000)!==17||inv.currentRole!==inv.sessionRole||!inv.installerSuperuser||!inv.installerCreateRole||inv.schemaPresent||inv.runtimePresent||inv.eventTriggers||inv.unsafeDefaultAcls)throw Error('ISOLATED_FOUNDATION_PREFLIGHT_REFUSED');
 for(let i=0;i<capsule.length;i++)await query(capsule[i],undefined,['CREATE','CREATE','REVOKE','GRANT','CREATE','REVOKE'][i],'T');const post=(await query(Q.POST,undefined,'SELECT','T'))[0];if(!post||!['schemaOwned','ledgerOwned','runtimeRestricted','runtimeNoMemberships','runtimeNoSettings','runtimeUsageOnly','schemaAclClosed','ledgerAclClosed'].every(k=>post[k]===true)||post.primaryKeys!==1||post.checks!==6||JSON.parse(post.ledgerColumns).length!==8)throw Error('ISOLATED_FOUNDATION_POST_REFUSED');
 const operationId='10000000-0000-4000-8000-000000000001',hash='a'.repeat(64);await query(Q.INSERT,[operationId,F.capsuleHash,hash,hash,hash],'INSERT','T');const row=(await query(Q.STATUS,[operationId],'SELECT','T'))[0];if(row?.operationId!==operationId||row.state!=='applied'||row.capsuleHash!==F.capsuleHash)throw Error('ISOLATED_FOUNDATION_LEDGER_REFUSED');await query(Q.ROLLBACK,undefined,'ROLLBACK','I');begun=false;const after=(await query(BASELINE,undefined,'SELECT','I'))[0]?.fingerprint;if(after!==before)throw Error('ISOLATED_FOUNDATION_LEGACY_CATALOG_CHANGED');
 return Object.freeze({test:'isolated-capsule-rollback-only',pgMajor:17,createdAndRolledBack:true,legacyCatalogFingerprintUnchanged:true,publicExposureCount:inv.publicThirdPartyPrivileges,fullApplyGuardWouldBlock:inv.publicThirdPartyPrivileges>0,realApplyAuthorityTested:false,recoveryReady:false,production:false});
 }catch{if(begun&&['T','E'].includes(getTransactionState())){try{await query(Q.ROLLBACK,undefined,'ROLLBACK','I');}catch{throw Error('ISOLATED_FOUNDATION_ROLLBACK_UNCONFIRMED');}}throw Error('ISOLATED_FOUNDATION_HARNESS_FAILED');}
}
module.exports=Object.freeze({runIsolatedCapsuleRollback,BASELINE});
