'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const B=require('./build-preflight.cjs'),O=require('./observe.cjs');
const runtimeRoot=process.argv[2]?path.resolve(process.argv[2]):path.resolve(__dirname,'../runtime');
const plan=B.buildPreflight({suffix:'012345abcdef',runtimeRoot}),meta={...plan};delete meta.json;
function row(role='installer'){const init=role==='prepare_volume';return{id:'1'.repeat(64),project:meta.composeProjectName,service:role,image:O.IMAGE,state:init?'exited':'running',exitCode:0,oomKilled:false,health:init?'none':'healthy',memory:init?67108864:268435456,memorySwap:init?67108864:268435456,nanoCpus:init?100000000:250000000,pidsLimit:init?16:32,readOnly:true,capDrop:['ALL'],capAdd:init?['CHOWN']:null,securityOpt:['no-new-privileges'],networkMode:'none',user:init?'0:0':'1000:1000',init:true,proofVolume:meta.volumeName,portBindingsCount:0,mountCount:init?1:2};}
test('normalized Compose and closed Docker evidence prove only resources and health',()=>{const c=JSON.parse(plan.json);c.name=meta.composeProjectName;assert.equal(O.verifyConfig(c,meta,JSON.parse(plan.json)),true);assert.equal(O.inspect(row(),meta,'installer'),'ready');assert.equal(O.inspect(row('prepare_volume'),meta,'prepare_volume'),'ready');assert.equal(O.verifyVolume({name:meta.volumeName,purpose:'crm-manager-native-preflight',exclusive:meta.composeProjectName,project:meta.composeProjectName},meta),true);});
test('closed observer rejects secrets/extra fields, wrong ownership and any resource weakening',()=>{for(const change of [v=>v.env='RAW_CANARY',v=>v.id='x',v=>v.project='foreign',v=>v.memory=536870912,v=>v.memorySwap=-1,v=>v.pidsLimit=0,v=>v.capAdd=['DAC_OVERRIDE'],v=>v.networkMode='bridge',v=>v.proofVolume='foreign',v=>v.mountCount=3]){const r=row();change(r);assert.throws(()=>O.inspect(r,meta,'installer'),e=>e.message==='NATIVE_PREFLIGHT_OBSERVATION_REFUSED');}const c=JSON.parse(plan.json);c.name=meta.composeProjectName;c.services.installer.environment.PGPASSWORD='RAW_CANARY';assert.throws(()=>O.verifyConfig(c,meta,JSON.parse(plan.json)));});
test('failed or incomplete runtime cannot become positive proof; parsing stays bounded and generic',()=>{for(const r of [{...row(),state:'exited'},{...row(),oomKilled:true},{...row(),health:'unhealthy'}])assert.equal(O.inspect(r,meta,'installer'),'failed');assert.equal(O.inspect({...row(),health:'starting'},meta,'installer'),'waiting');assert.throws(()=>O.parse('x'.repeat(524289)),e=>e.message==='NATIVE_PREFLIGHT_OBSERVATION_REFUSED');assert.throws(()=>O.parse('{"password":"RAW_CANARY"'),e=>!e.message.includes('CANARY'));});
