'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {D,fixture,inspect,refused,baseEvidence,deferred,accelerated,raw,context,password,sha,inputRoot}=require('./fixture.cjs');
test('14 source pins exact bytes SHA256 Git SHA1',()=>{const m=JSON.parse(fs.readFileSync(path.join(inputRoot,'INPUT-PINS.json')));assert.equal(m.files.length,14);for(const f of m.files){const b=fs.readFileSync(path.join(inputRoot,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);if(f.githubBlobSha1)assert.equal(require('node:crypto').createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex'),f.githubBlobSha1);}});
test('fixed single original SELECT with no params/callerSQL and own purpose',()=>{assert.equal(D.READ_SQL,"SELECT payload FROM public.shrigma_growth_email_ses_health_v1 WHERE pg_catalog.current_database()='listmonk'");assert.equal(D.PURPOSE,'read-only-original-email-health');assert.equal(D.queryHash,sha(D.READ_SQL));assert.equal(D.BEGIN,'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');});
test('OFF / wrong driver no credentials or connection',async()=>{const f=fixture();await assert.rejects(D.createDeliveryHealthRead({...f.args,enabled:false}).inspect(raw,context),{code:'HEALTH_OFF'});await assert.rejects(inspect(fixture({version:'8.22.0'})),{code:'HEALTH_OFF'});assert.equal(f.clients.length,0);});
test('one brand only, null preserved vs zero, shared metadata and no PII',async()=>{const f=fixture(),v=await inspect(f);assert.equal(v.brand,'aristo');assert.equal(v.brandMetrics.finalizacao_pendente,0);assert.equal(v.queue.visible,null);assert.equal(v.collector.last_poll_count,null);assert.equal(v.operational,false);assert.equal(v.sharedQueue,true);assert.equal(v.authorizesSend,false);assert(!JSON.stringify(v).includes('73'));assert(!JSON.stringify(v).includes(password));assert(!('resource' in v));assert(!('healthy' in v));assert.deepEqual(f.trace,['gate:connect','construct','connect','peer','gate:read','begin','read','rollback','end','gate:release']);assert.equal(f.calls.filter(x=>x===D.READ_SQL).length,1);assert(Object.isFrozen(v.brandMetrics));const c=f.clients[0].config;assert.equal(c.ssl,false);assert.equal(c.pipeline,false);assert(c.options.includes('default_transaction_read_only=on'));assert(c.options.includes('search_path=pg_catalog'));assert.equal(c.statement_timeout,8000);assert(f.gates.every(g=>!JSON.stringify(g).includes(password)));});
test('select Fish DTO only while retaining shared NULL',async()=>{const f=fixture(),v=await f.service.inspect({brand:'fish'},context);assert.equal(v.brandMetrics.finalizacao_pendente,73);assert.equal(v.queue.visible,null);});
for(const [name,change] of [
 ['null payload',()=>null],['schema',v=>({...v,schema_version:2})],['extra',v=>({...v,email:'hidden@example.invalid'})],['date',v=>({...v,checked_at:'2026-02-30T10:00:00Z'})],['brand duplicate',v=>({...v,brands:[v.brands[0],v.brands[0]]})],['brand missing',v=>({...v,brands:[v.brands[0]]})],['brand foreign',v=>({...v,brands:[v.brands[0],{...v.brands[1],marca:'other'}]})],['brand PII',v=>({...v,brands:[v.brands[0],{...v.brands[1],customerId:3}]})],['brand null',v=>({...v,brands:[v.brands[0],{...v.brands[1],falhas_24h:null}]})],['negative',v=>({...v,conflicts:-1})],['unsafe',v=>({...v,pending_ingest_15min:Number.MAX_SAFE_INTEGER+1})],['string',v=>({...v,queue:{...v.queue,visible:'0'}})],['error code',v=>({...v,collector:{...v.collector,last_error_code:password}})],['collector extra',v=>({...v,collector:{...v.collector,customer:'x'}})]
])test('payload refuses '+name,async()=>{const f=fixture({result:(sql,r)=>sql===D.READ_SQL?{...r,rows:[{payload:change(baseEvidence())}]}:r});await refused(f,'HEALTH_PROTOCOL_REFUSED');});
for(const phase of ['connect','read','release'])test('CURRENT refuses '+phase+' and no partial result',async()=>{const f=fixture({deny:phase});await refused(f,'HEALTH_ADMISSION_REFUSED');assert.equal(f.clients.length,phase==='connect'?0:1);});
for(const point of ['connect','query','rollback','end'])test('credential epoch changed during '+point+' suppresses result',async()=>{const f=fixture();if(point==='connect')f.opts.connectHook=()=>f.changeRevision();if(point==='query'||point==='rollback')f.opts.queryHook=q=>{if(q===(point==='query'?D.READ_SQL:D.ROLLBACK))f.changeRevision();};if(point==='end')f.opts.endHook=()=>f.changeRevision();await refused(f,'HEALTH_ADMISSION_REFUSED');});
for(const p of [{read_only:'off'},{database:'other'},{sessionRole:'other'},{currentRole:'other'},{pid:5},{port:5433},{engine:160010},{ssl:true}])test('peer refuses '+JSON.stringify(p),async()=>refused(fixture({peer:p}),'HEALTH_PEER_REFUSED'));
for(const q of ['connect',D.PEER,D.BEGIN,D.READ_SQL,D.ROLLBACK])test('ambiguous duplicate ACK refuses '+q.slice(0,15),async()=>refused(fixture({doubleAck:q})));
test('missing ACK timeout closes',async()=>{const X=accelerated();await refused(fixture({D:X.D,missingAck:X.D.READ_SQL}),'HEALTH_TIMEOUT');});
test('query timeout closes single SELECT',async()=>{const X=accelerated(),f=fixture({D:X.D,hang:X.D.READ_SQL});await refused(f,'HEALTH_QUERY_FAILED');assert.equal(f.calls.filter(x=>x===X.D.READ_SQL).length,1);});
for(const opt of ['endThrow','noEndEvent','endHang'])test('uncertain closure blocks next admission '+opt,async()=>{const X=accelerated(),f=fixture({D:X.D,[opt]:true});await refused(f);await assert.rejects(inspect(f),{code:'HEALTH_UNAVAILABLE'});await assert.rejects(f.service.close(),{code:'HEALTH_CLOSE_UNCONFIRMED'});});
test('serialization close drain idempotent no new admission',async()=>{const holdRead=deferred(),entered=deferred(),f=fixture({holdRead,entered}),pending=inspect(f);await entered.promise;await assert.rejects(inspect(f),{code:'HEALTH_BUSY'});const closing=f.service.close();assert.equal(closing,f.service.close());await assert.rejects(inspect(f),{code:'HEALTH_UNAVAILABLE'});holdRead.resolve();await pending;await closing;assert.equal(f.clients[0].ends,1);});
test('exact input/context rejects SQL owner destination and getters',async()=>{const f=fixture();for(const v of [{...raw,sql:'SELECT 1'},{...raw,url:'other'},{...raw,brand:'other'},{get brand(){assert.fail('getter');}}])await assert.rejects(f.service.inspect(v,context));await assert.rejects(f.service.inspect(raw,{...context,actor:'other'}));assert.equal(f.clients.length,0);});
test('private provider errors sanitized and wrong purpose rejected',async()=>{for(const opts of [{queryThrow:D.READ_SQL},{credentialThrow:true},{connectThrow:true},{badGate:'connect'}])await refused(fixture(opts));});
test('row extra/multiple/command/clock fail closed',async()=>{await refused(fixture({rowExtra:{password}}));for(const result of [(sql,r)=>sql===D.READ_SQL?{...r,rows:[...r.rows,...r.rows],rowCount:2}:r,(sql,r)=>sql===D.READ_SQL?{...r,command:'UPDATE'}:r])await refused(fixture({result}));await refused(fixture({clock:NaN}),'HEALTH_CLOCK_REFUSED');});

test('strict payload descriptors/array/accessors no toJSON side effects',()=>{for(const alter of [v=>Object.defineProperty(v.brands,'0',{get(){assert.fail('getter must not execute');}}),v=>v.brands.extra='PII',v=>v.brands[Symbol('private')]='PII',v=>Object.defineProperty(v.collector,'last_error_code',{get(){assert.fail('getter must not execute');},enumerable:true}),v=>v.brands[0].customerId='PII']){const v=baseEvidence();alter(v);assert.throws(()=>D.validatePayload(v,'aristo'),{code:'HEALTH_PROTOCOL_REFUSED'});}});
test('source valid nullable timestamp/count/error; largest safe count retained',async()=>{const f=fixture({evidence:{collector:{last_poll_ok_at:'2026-10-08T19:00:00Z',last_poll_count:0,last_error_at:null,last_error_code:'UNCLASSIFIED_RUNTIME_ERROR'},queue:{checked_at:'2026-10-08T19:00:00Z',visible:0,inflight:Number.MAX_SAFE_INTEGER,delayed:null,error_at:null}}}),v=await inspect(f);assert.equal(v.collector.last_poll_count,0);assert.equal(v.queue.inflight,Number.MAX_SAFE_INTEGER);assert.equal(v.queue.delayed,null);});
for(const q of [D.PEER,D.BEGIN,D.READ_SQL,D.ROLLBACK])test('wrong transaction ACK closes '+q.slice(0,15),async()=>refused(fixture({wrongAck:q})));
for(const change of [{password:''},{revision:0},{ownerId:'foreign'},{transport:{mode:'public'}},{resource:{...D.RESOURCE,database:'other'}}])test('credential exact refuses '+Object.keys(change),async()=>refused(fixture({credential:change}),'HEALTH_CREDENTIAL_REFUSED'));
test('admission exact rejects extra principal/hash/query purpose mismatch',async()=>{for(const delta of [{password},{queryHash:'f'.repeat(64)},{credentialBindingHash:'f'.repeat(64)},{ownerId:'other'}])await refused(fixture({gateResult:(input,expected)=>({...expected,...delta})}));});
