 'use strict';
const fs=require('node:fs'),path=require('node:path'),{test}=require('node:test'),a=require('node:assert/strict'),crypto=require('node:crypto');
const P=fs.realpathSync(process.env.COHERENT_TRANSITION_PACKAGE),D=path.join(P,'files/tools/listmonk-regular-build/coherent-transition');
const B=require(path.join(D,'builder.cjs')),T=require(path.join(D,'templates.cjs')),{PGlite}=require(process.env.PGLITE_MODULE_PATH||path.resolve('.private/test-tools/node_modules/@electric-sql/pglite'));
const index=JSON.parse(fs.readFileSync(path.join(P,'INPUTS.json'))),hash=(b,alg='sha256')=>crypto.createHash(alg).update(b).digest('hex');
function request(mode='forward'){const purposes={admission:mode==='forward'?'coherent-original-worker-transition':'coherent-original-worker-rollback',restore:'coherent-original-worker-restore',snapshot:mode==='forward'?'original-transition-preflight':'original-rollback-preflight',quiescence:'original-worker-quiesced'};return {sourceInputs:index.sourcePins.map(p=>({path:p.path,bytes:p.bytes,sha256:p.sha256,content:fs.readFileSync(path.join(P,p.localPath),'utf8')})),candidate:{querySha256:'a'.repeat(64),kernelSha256:'1'.repeat(64),workerSha256:'b'.repeat(64),runtimeSha256:'c'.repeat(64),imageDigest:'4'.repeat(64)},privateReferences:Object.fromEntries(Object.entries(purposes).map(([k,purpose],i)=>[k,{reference:'root-private:synthetic-'+k,sha256:hash('synthetic-'+mode+'-'+k),purpose}])),operationId:'00000000-0000-4000-8000-000000000111',sendTargets:[171,174].map(campaignId=>({campaignId,admission:{reference:'root-private:synthetic-send-'+campaignId,sha256:hash('synthetic-send-'+campaignId),purpose:'existing-campaign-send-admission'}})),mode};}
function privateAdmission(plan){return {purpose:plan.admissionPurpose,operationId:plan.operationId,candidate:plan.candidate,sendTargets:plan.sendTargets,admissionSha256:plan.privateReferences.admission.sha256,restoreSha256:plan.privateReferences.restore.sha256,snapshotSha256:plan.privateReferences.snapshot.sha256,quiescenceSha256:plan.privateReferences.quiescence.sha256,actor:'synthetic-root-private-test',checkedAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+240000).toISOString(),approvedAt:new Date(Date.now()-1000).toISOString(),topologySha256:'f'.repeat(64)};}
async function dbFixture(){const db=new PGlite();await db.exec('CREATE SCHEMA crm_audience_v2; CREATE ROLE synthetic_reader;');await db.exec(`CREATE TABLE public.campaigns(id integer PRIMARY KEY,status text,send_at timestamptz,sent integer,to_send integer,max_subscriber_id integer,last_subscriber_id integer,started_at timestamptz,updated_at timestamptz,body text,type text DEFAULT 'regular',messenger text DEFAULT 'email',attribs jsonb DEFAULT '{"crm":{"policy":"crm-campaign-v1","brand":"fish"}}');
CREATE TABLE public.campaign_lists(campaign_id integer,list_id integer,details jsonb);
CREATE TABLE public.campaign_media(campaign_id integer,media_id integer,details jsonb);
CREATE TABLE public.templates(id integer,body text); CREATE TABLE public.media(id integer,details jsonb); CREATE TABLE public.lists(id integer,details jsonb);
CREATE TABLE crm_audience_v2.campaign_binding(campaign_id integer,binding_version integer,binding_hash text,brand text,details jsonb);
CREATE TABLE crm_audience_v2.campaign_binding_revision(campaign_id integer,binding_version integer,details jsonb);
CREATE TABLE crm_audience_v2.regular_delivery_recovery(dispatch_id uuid,details jsonb);
CREATE TABLE public.shrigma_email_dispatch(dispatch_id uuid,flow text,piece text,transport_state text,details jsonb);
CREATE TABLE public.crm_ab_arm_v2(campaign_id integer,details jsonb);CREATE TABLE public.crm_ab_member_v2(test_id uuid,subscriber_id integer,details jsonb);CREATE TABLE crm_audience_v2.ab_regular_pair(test_id uuid,campaign_a integer,campaign_b integer,details jsonb);
CREATE TABLE crm_audience_v2.selection_runtime(singleton boolean PRIMARY KEY,enabled boolean,candidate_query_sha256 text,verified_at timestamptz);
INSERT INTO public.campaigns(id,status,send_at,sent,to_send,max_subscriber_id,last_subscriber_id,started_at,updated_at,body) SELECT n,'scheduled','2030-01-01Z',0,0,8,0,NULL,'2026-01-01Z','synthetic material '||n FROM unnest(ARRAY[171,172,173,174,175,880,881,999]) n;`);
const lease=request().sourceInputs[4].content,delivery=request().sourceInputs[3].content;
for(const [source,name]of [[lease,'regular_worker_deployment'],[lease,'regular_worker_lease'],[delivery,'regular_delivery_campaign']]){const re=new RegExp('CREATE TABLE crm_audience_v2\\.'+name+' \\([\\s\\S]*?\\n\\);'),match=source.match(re);a(match);await db.exec(match[0]);}
await db.exec("UPDATE public.campaigns SET status='finished' WHERE id=881;");
await db.exec('CREATE TABLE public.subscribers(id integer,email text,status text,attribs jsonb);');
const body=request().sourceInputs[6].content.split('CREATE OR REPLACE FUNCTION crm_audience_v2.selection_worker_context(cid integer) RETURNS jsonb\n LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path=pg_catalog AS $fn$')[1].split('$fn$')[0];
await db.query('CREATE FUNCTION crm_audience_v2.selection_worker_context(cid integer) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path=pg_catalog AS '+"'"+body.replaceAll("'","''")+"'");await db.exec('REVOKE ALL ON FUNCTION crm_audience_v2.selection_worker_context(integer) FROM PUBLIC; GRANT EXECUTE ON FUNCTION crm_audience_v2.selection_worker_context(integer) TO synthetic_reader;');
for(const [source,name]of [[lease,'regular_worker_heartbeat'],[lease,'regular_worker_require'],[delivery,'regular_delivery_claim'],[delivery,'regular_delivery_finish']]){const re=new RegExp('CREATE FUNCTION crm_audience_v2\\.'+name+'\\([\\s\\S]*?\\n\\$fn\\$;'),match=source.match(re);a(match,name);await db.exec(match[0]);}
await db.query(`INSERT INTO crm_audience_v2.regular_worker_deployment VALUES(true,true,$1,$2,$3,'postgres','2026-01-01Z','synthetic-old-authority',$4)`,['d'.repeat(64),'e'.repeat(64),B.LEGACY,'f'.repeat(64)]);
await db.query(`INSERT INTO crm_audience_v2.regular_worker_lease VALUES(true,'00000000-0000-4000-8000-000000000222',$1,$2,'postgres','2026-01-01Z','2026-01-01Z',false,NULL)`,['d'.repeat(64),'e'.repeat(64)]);
await db.query(`INSERT INTO crm_audience_v2.selection_runtime VALUES(true,true,$1,'2026-01-01Z')`,[B.LEGACY]);
for(const id of [171,172,173,174,175,880,881,999])await db.query(`INSERT INTO crm_audience_v2.regular_delivery_campaign(campaign_id,binding_version,binding_hash,material,worker_sha256,runtime_sha256,envelope_from,account_id,region,configuration_set,enabled,suspended,created_at) VALUES($1,1,$2,$3,$4,$5,'synthetic@example.invalid','000000000000','synthetic-region','synthetic-config',$6,$7,'2026-01-01Z')`,[id,'f'.repeat(64),{synthetic:id},(id===999?'2':'d').repeat(64),(id===999?'3':'e').repeat(64),id!==880,id===881]);
for(const relation of []){if(['public.campaigns'].includes(relation))continue;/* Empty protected history is supplemented below. */}
await db.exec(`INSERT INTO public.campaign_lists VALUES(171,17,'{"scope":"synthetic"}');INSERT INTO public.campaign_media VALUES(171,1,'{}');INSERT INTO public.templates VALUES(1,'Synthetic body');INSERT INTO public.media VALUES(1,'{}');INSERT INTO public.lists VALUES(17,'{}');INSERT INTO crm_audience_v2.campaign_binding VALUES(171,1,'${'f'.repeat(64)}','fish','{}');INSERT INTO crm_audience_v2.campaign_binding_revision VALUES(171,1,'{"history":true}');INSERT INTO public.shrigma_email_dispatch VALUES('00000000-0000-4000-8000-000000000333','campaign','audience-regular-v1:880','accepted','{"history":true}');INSERT INTO crm_audience_v2.regular_delivery_recovery VALUES('00000000-0000-4000-8000-000000000333','{"history":true}');INSERT INTO public.crm_ab_arm_v2 VALUES(171,'{"arm":"A"}');INSERT INTO public.crm_ab_member_v2 VALUES('00000000-0000-4000-8000-000000000444',1,'{}');INSERT INTO crm_audience_v2.ab_regular_pair VALUES('00000000-0000-4000-8000-000000000444',171,174,'{}');`);return db;}
async function snapshot(db){return (await db.query(B.preflightRead)).rows[0].private_transition_snapshot;}
function envelope(prepared,snap,originalSnapshot){return {plan:prepared.plan,snapshot:snap,ownedCampaignIds:snap.ownedActiveCampaignIds,privateAdmission:privateAdmission(prepared.plan),...(originalSnapshot?{originalSnapshot}:{})};}
// Test-only in-memory execution of semantic core. The native guard remains required
// in the sealed transaction recipe; RAM17.5 positive cases never prove PG17.10 admission.
async function coreTx(db,prepared,env,{nativeGuard=false}={}){await db.exec(prepared.transactionStatements[0]);try{await db.exec(prepared.transactionStatements[1]);if(nativeGuard)await db.exec(prepared.transactionStatements[2]);await db.query(prepared.transactionStatements[3],[env]);await db.exec(prepared.transactionStatements[4]);let after=await snapshot(db);await db.exec(prepared.transactionStatements[6]);await db.exec(prepared.transactionStatements[7]);return after;}catch(e){await db.exec('ROLLBACK;');throw e;}}

async function currentFixture(){const db=await dbFixture();await db.exec('DELETE FROM crm_audience_v2.regular_delivery_campaign WHERE campaign_id=173; UPDATE crm_audience_v2.regular_delivery_campaign SET enabled=false WHERE campaign_id=175; INSERT INTO crm_audience_v2.campaign_binding_revision VALUES(173,1,\'{"synthetic":"released historical"}\');');return db;}
test('bounded SOURCE contains only two table boundaries and scoped row probes; no protected full-table hash/equality',()=>{const p=B.prepare(request()),s=p.transactionStatements[4];a.equal((s.match(/LOCK TABLE/g)||[]).length,2);for(const r of ['public.campaigns','public.templates','public.media','public.lists','public.shrigma_email_dispatch','public.crm_ab_arm_v2','crm_audience_v2.campaign_binding_revision'])a.equal(s.includes('LOCK TABLE '+r),false);a.equal(/string_agg|sha256\(convert_to/.test(s),false);a.equal(B.preflightRead.includes("'preserved',"),false);a(s.includes('OWNED_SET_BOUND_EXCEEDED'));a(s.includes('ORDER BY p.id FOR SHARE'));a.equal(p.authorizesExecution,false);});
test('interleaving third-party/173/template/AB/history updates survive forward and same-op rollback',async()=>{const db=await currentFixture();try{const before=await snapshot(db),p=B.prepare(request());await db.exec("UPDATE public.campaigns SET body='live analyst change' WHERE id=999; UPDATE public.templates SET body='live template'; UPDATE public.crm_ab_arm_v2 SET details='{\"live\":true}'; UPDATE crm_audience_v2.campaign_binding_revision SET details='{\"released\":true}' WHERE campaign_id=173; UPDATE public.shrigma_email_dispatch SET details='{\"thirdparty\":true}' WHERE piece='audience-regular-v1:880';");const third=(await db.query('SELECT body FROM public.campaigns WHERE id=999')).rows,legacy=(await db.query('SELECT * FROM crm_audience_v2.campaign_binding_revision WHERE campaign_id=173')).rows;const after=await coreTx(db,p,envelope(p,before));a.deepEqual(after.ownedActiveCampaignIds,[171,172,174]);a.equal((await db.query('SELECT count(*)::int n FROM crm_audience_v2.regular_delivery_campaign WHERE campaign_id=173')).rows[0].n,0);const r=B.prepare(request('rollback'));await coreTx(db,r,envelope(r,after,before));a.deepEqual((await db.query('SELECT body FROM public.campaigns WHERE id=999')).rows,third);a.deepEqual((await db.query('SELECT * FROM crm_audience_v2.campaign_binding_revision WHERE campaign_id=173')).rows,legacy);a.equal((await db.query('SELECT body FROM public.templates')).rows[0].body,'live template');}finally{await db.close();}});
for(const [name,change]of [['enabled phantom',db=>db.exec('UPDATE crm_audience_v2.regular_delivery_campaign SET enabled=true WHERE campaign_id=175')],['status phantom',db=>db.exec("UPDATE public.campaigns SET status='scheduled' WHERE id=881")],['owned progress',db=>db.exec('UPDATE public.campaigns SET sent=1 WHERE id=171')],['owned tuple drift',db=>db.exec("UPDATE crm_audience_v2.regular_delivery_campaign SET worker_sha256='"+'6'.repeat(64)+"' WHERE campaign_id=171")]])test('preflight/core interleaving rejects '+name+' without writing transition',async()=>{const db=await currentFixture();try{const before=await snapshot(db),p=B.prepare(request());await change(db);const current=await snapshot(db);await a.rejects(coreTx(db,p,envelope(p,before)),/SNAPSHOT_DRIFT/);a.deepEqual(await snapshot(db),current);}finally{await db.close();}});
test('unadmitted control mutation trigger refuses before changes',async()=>{const db=await currentFixture();try{await db.exec('CREATE FUNCTION public.synthetic_trigger() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RETURN NEW; END$$;CREATE TRIGGER synthetic_trigger BEFORE UPDATE ON crm_audience_v2.regular_delivery_campaign FOR EACH ROW EXECUTE FUNCTION public.synthetic_trigger();');const s=await snapshot(db),p=B.prepare(request());await a.rejects(coreTx(db,p,envelope(p,s)),/UNADMITTED_MUTATION_TRIGGER/);a.deepEqual(await snapshot(db),s);}finally{await db.close();}});
for(const [name,change]of [['owned counter',db=>db.exec('UPDATE public.campaigns SET sent=1 WHERE id=171')],['lease renewal',db=>db.exec("UPDATE crm_audience_v2.regular_worker_lease SET expires_at=clock_timestamp()+interval '1 minute'")],['unknown claim',db=>db.exec("INSERT INTO public.shrigma_email_dispatch VALUES('00000000-0000-4000-8000-000000000555','campaign','audience-regular-v1:171','outcome_unknown','{}')")]])test('bounded rollback refuses '+name+' and preserves current outcome',async()=>{const db=await currentFixture();try{const original=await snapshot(db),p=B.prepare(request());await coreTx(db,p,envelope(p,original));await change(db);const current=await snapshot(db),r=B.prepare(request('rollback'));await a.rejects(coreTx(db,r,envelope(r,current,original)));a.deepEqual(await snapshot(db),current);}finally{await db.close();}});
for(const [name,change]of [['expired',e=>e.privateAdmission.expiresAt='2026-01-01Z'],['wrong own restore',e=>e.privateAdmission.restoreSha256='0'.repeat(64)]])test('bounded authority gate refuses '+name,async()=>{const db=await currentFixture();try{const s=await snapshot(db),p=B.prepare(request()),e=envelope(p,s);change(e);await a.rejects(coreTx(db,p,e),/PRIVATE_ADMISSION_MISMATCH/);a.deepEqual(await snapshot(db),s);}finally{await db.close();}});
test('full native recipe remains refused on RAM17.5',async()=>{const db=await currentFixture();try{const s=await snapshot(db),p=B.prepare(request());await a.rejects(coreTx(db,p,envelope(p,s),{nativeGuard:true}),/NATIVE_BOUNDARY_REQUIRED/);a.deepEqual(await snapshot(db),s);}finally{await db.close();}});

test('owned history cap refuses overflow without truncation acceptance or mutation',async()=>{const db=await currentFixture();try{await db.exec("INSERT INTO public.shrigma_email_dispatch SELECT gen_random_uuid(),'campaign','audience-regular-v1:171','accepted','{}' FROM generate_series(1,4097)");const s=await snapshot(db),p=B.prepare(request());a.equal(s.ownedRowState.dispatch.length,4097);await a.rejects(coreTx(db,p,envelope(p,s)),/OWNED_ROW_BOUND_EXCEEDED/);a.deepEqual(await snapshot(db),s);}finally{await db.close();}});
