 'use strict';
// Offline portability/new boundary only: no database, pg client or old semantic suites.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{test}=require('node:test'),a=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const root=fs.realpathSync(path.resolve(__dirname,'../..')),sub='tools/listmonk-regular-build/coherent-transition',bundle=require(path.join(root,sub,'source-bundle.json'));
function relocated(){const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'portable-transition-'))),repo=path.join(temp,'repo');fs.mkdirSync(repo);for(const rel of [...bundle.inputs.map(i=>i.repoPath),...['builder.cjs','templates.cjs','source-pins.json','source-bundle.json','source-bundle.cjs','native-boundary.sql'].map(n=>sub+'/'+n),...['bounded-fixtures.cjs','bounded-native-concurrency.test.cjs'].map(n=>'tests/coherent-transition/'+n)]){const dest=path.join(repo,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,rel),dest);}return {repo,temp,loader:require(path.join(repo,sub,'source-bundle.cjs')),close(){fs.rmSync(temp,{recursive:true,force:true});}};}
function exercise(fn){const c=relocated();try{return fn(c);}finally{c.close();}}
test('eight exact source bytes load and pure fixture prepares from relocated canonical repository',()=>exercise(c=>{const inputs=c.loader.load();a.equal(inputs.length,8);const F=require(path.join(c.repo,'tests/coherent-transition/bounded-fixtures.cjs')),p=F.B.prepare(F.request());a.equal(p.sourceBodySha256,'c794db19bf9e8e030284651947510ae5c00a12647fed3ab81f8eeec50b4eb582');a.equal(p.authorizesExecution,false);a.equal(p.operational,false);a(p.transactionStatements[4].includes('RETURN crm_audience_v2.ab_regular_context(cid,ctx);'));}));
test('logical old metadata paths do not require an exclusive package or private folder',()=>exercise(c=>{a.equal(fs.existsSync(path.join(c.repo,'deliverables')),false);a.equal(fs.existsSync(path.join(c.repo,'.private')),false);a.equal(c.loader.load().length,8);const s=fs.readFileSync(path.join(c.repo,'tests/coherent-transition/bounded-fixtures.cjs'),'utf8');for(const bad of ['COHERENT_TRANSITION_PACKAGE','PGLITE_MODULE_PATH','.private/','INPUTS.json'])a.equal(s.includes(bad),false);a.equal(s.includes('new PGlite'),false);}));
for(const [name,action]of [['changed byte',(c,e)=>fs.appendFileSync(path.join(c.repo,e.repoPath),'\n')],['missing byte source',(c,e)=>fs.unlinkSync(path.join(c.repo,e.repoPath))],['symlink byte source',(c,e)=>{const f=path.join(c.repo,e.repoPath),external=path.join(c.temp,'external');fs.renameSync(f,external);fs.symlinkSync(external,f);} ]])test('portable strict pins refuse '+name,()=>exercise(c=>{action(c,bundle.inputs[7]);a.throws(()=>c.loader.load());}));
for(const [name,action]of [['wrong purpose',m=>m.purpose='original-authority'],['path traversal',m=>m.inputs[0].repoPath='../outside'],['wrong pin',m=>m.inputs[0].sha256='a'.repeat(64)],['wrong count',m=>m.inputs.pop()]])test('portable manifest refuses '+name,()=>exercise(c=>{const f=path.join(c.repo,sub,'source-bundle.json'),m=JSON.parse(fs.readFileSync(f));action(m);fs.writeFileSync(f,JSON.stringify(m));a.throws(()=>c.loader.load());}));
test('fixture initializer refuses default connection before any SQL',async()=>{const F=require(path.join(root,'tests/coherent-transition/bounded-fixtures.cjs'));await a.rejects(F.initialize(),/EXISTING_DISPOSABLE_FIXTURE_CONNECTION_REQUIRED/);});
test('native test without explicit opt-in refuses instead of skipping or requiring pg/database',()=>exercise(c=>{const env={PATH:process.env.PATH},receipt=path.join(c.temp,'receipt.json');env.BOUNDED_NATIVE_TEST_RECEIPT=receipt;const r=spawnSync(process.execPath,['--test',path.join(c.repo,'tests/coherent-transition/bounded-native-concurrency.test.cjs')],{env,encoding:'utf8'});a.equal(r.status,1);a((r.stdout+r.stderr).includes('Explicit disposable native fixture opt-in required'));a.equal(fs.existsSync(receipt),false);}));
test('fixed fixture/runtime boundaries precede pg clients; cleanup and pending-end receipt stay strict',()=>{const s=fs.readFileSync(path.join(root,'tests/coherent-transition/bounded-native-concurrency.test.cjs'),'utf8');a(s.indexOf("process.version,'v22.23.3'")<s.indexOf("const {Client}=require('pg')"));a(s.includes("u.pathname,'/bounded_transition_fixture'"));a(s.includes("u.port!=='5432'"));a(s.includes('Promise.allSettled([right.end(),left.end()])'));a(s.includes("left.query('ROLLBACK')"));a(s.includes('accepted:false'));a(s.includes('fixtureServerEnded:false'));a(s.includes('legacyBefore'));a(s.includes('OWNED')||s.includes('ownedRowState'));});
test('canonical SOURCE syntax parses offline',()=>{for(const n of ['source-bundle.cjs',...[]])a.equal(spawnSync(process.execPath,['--check',path.join(root,sub,n)]).status,0);for(const n of ['bounded-fixtures.cjs','bounded-native-concurrency.test.cjs'])a.equal(spawnSync(process.execPath,['--check',path.join(root,'tests/coherent-transition',n)]).status,0);});

test('minimal workflow requires exact fixture/runtime and only accepts after own server ends',()=>{const s=fs.readFileSync(path.join(root,'.github/workflows/coherent-transition-native-proof.yml'),'utf8');for(const required of ['contents: read','postgres:17.10',"'127.0.0.1:55432:5432'","node-version: '22.23.3'",'pg@8.23.1',"sudo -u '#1000'",'BOUNDED_NATIVE_FIXTURE_ISOLATED=1','clients-receipt.json','docker stop --time 5','steps.native.outcome','steps.stop.outcome','fixtureServerEnded=True'])a(s.includes(required),required);for(const forbidden of ['docker push','gh pr','secrets.','image.py','native_proof.py','deploy:'])a.equal(s.includes(forbidden),false);a(s.indexOf('Stop own fixture service')<s.indexOf('Final synthetic receipt'));});
