 'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{test}=require('node:test'),a=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const root=fs.realpathSync(path.resolve(process.env.SOURCE_SPLIT_TEST_ROOT||path.join(__dirname,'../../..')));
const base=fs.existsSync(path.join(root,'files'))?path.join(root,'files'):root,context=fs.existsSync(path.join(root,'context'))?path.join(root,'context'):root,code=path.join(base,'tools/listmonk-regular-build');
const Profile=require(path.join(code,'native_batch_profile.cjs')),Mat=require(path.join(context,'tools/listmonk-regular-build/materialize_batch_profile.cjs'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),draft=path.join(context,'crm-scheduler-batch-profile.json');
function sample(change=()=>{},env='1'){const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'source-proof-split-')));const f=Mat.materialize({profile:draft,profileSha256:sha(fs.readFileSync(draft)),out:path.join(temp,'profile')});let m=JSON.parse(fs.readFileSync(f.profile));const base=Profile.load(f.profile,f.profileSha256);m.buildReceipt={binarySha256:sha(Buffer.from('synthetic-test-only-no-go-binary')),querySha256:m.querySha256,kernelSha256:m.kernelSha256,composerSha256:m.sources.composer.sha256,workerTransactionSha256:base.workerTransactionSha256};change(m);fs.writeFileSync(f.profile,JSON.stringify(m));let previous=process.env.REGULAR_NATIVE_PROOF_ISOLATED;if(env===undefined)delete process.env.REGULAR_NATIVE_PROOF_ISOLATED;else process.env.REGULAR_NATIVE_PROOF_ISOLATED=env;return {...f,temp,sha:sha(fs.readFileSync(f.profile)),close(){if(previous===undefined)delete process.env.REGULAR_NATIVE_PROOF_ISOLATED;else process.env.REGULAR_NATIVE_PROOF_ISOLATED=previous;fs.rmSync(temp,{recursive:true,force:true});}};}
function exercise(fn,change,env){const f=sample(change,env);try{fn(f);}finally{f.close();}}
test('explicit functional loader accepts bound synthetic schema fixture without original/private receipt',()=>exercise(f=>{const p=Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:true});a.equal(p.report.proofPurpose,'isolated-source-functional');a.equal(p.report.isolatedProofAuthorized,false);a.equal(p.report.isolatedProofAuthorization,null);a.equal(p.report.isolatedSourceProofAuthorized,true);for(const k of ['originalPerformanceAccepted','originalOperational','originalDispatchProved','fullRecipientAccepted','performanceAccepted','operational'])a.equal(p.report[k],false);const selected=JSON.parse(fs.readFileSync(draft));a.equal(p.querySha256,sha(fs.readFileSync(path.join(context,selected.sources.candidateQuery.path))));}));
test('same bound profile still refuses default full proof without original authorization',()=>exercise(f=>a.throws(()=>Profile.load(f.profile,f.sha,{forRun:true}))));
test('offline default remains closed but inspectable',()=>exercise(f=>a.equal(Profile.load(f.profile,f.sha).report.isolatedSourceProofAuthorized,false)));
for(const [name,change]of [['unmeasured binary',m=>m.buildReceipt=null],['query mismatch',m=>m.buildReceipt.querySha256='a'.repeat(64)],['kernel mismatch',m=>m.buildReceipt.kernelSha256='a'.repeat(64)],['composer mismatch',m=>m.buildReceipt.composerSha256='a'.repeat(64)],['transaction mismatch',m=>m.buildReceipt.workerTransactionSha256='a'.repeat(64)],['missing JIT identity',m=>delete m.buildReceipt.workerTransactionSha256],['count-only purpose',m=>m.kind='ephemeral-batch-count'],['production acceptance',m=>m.nativeAcceptance={}],['missing original SQL',m=>m.additionalSqlSources.pop()],['wrong original order',m=>m.additionalSqlSources.reverse()]])test(name+' refused in functional opt-in',()=>exercise(f=>a.throws(()=>Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:true})),change));
for(const env of ['0','', 'true'])test('isolated environment '+JSON.stringify(env)+' refused',()=>exercise(f=>a.throws(()=>Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:true})),undefined,env));
test('source-only inspection cannot be promoted by flag',()=>exercise(f=>a.throws(()=>Profile.load(f.profile,f.sha,{forRun:false,isolatedSourceProof:true}))));
test('nonboolean purpose refused',()=>exercise(f=>a.throws(()=>Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:'1'}))));
test('CLI explicit option and default refusal distinct',()=>exercise(f=>{let r=spawnSync(process.execPath,[path.join(code,'native_batch_profile.cjs'),'--isolated-source-proof',f.profile,f.sha],{env:process.env,encoding:'utf8'});a.equal(r.status,0,r.stderr);a.equal(JSON.parse(r.stdout).proofPurpose,'isolated-source-functional');r=spawnSync(process.execPath,[path.join(code,'native_batch_profile.cjs'),f.profile,f.sha],{env:process.env});a.equal(r.status,1);}));
test('pinned original SQL is re-read and refuses byte drift even after successful load',()=>exercise(f=>{let p=Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:true}),dep=p.report.additionalSqlSources[6];fs.appendFileSync(dep.file.path,'\n');a.throws(()=>p.pinnedAdditionalSQL(dep.sourceName));}));
test('functional run requires authorization receipt absent; no private source added',()=>exercise(f=>{let m=JSON.parse(fs.readFileSync(f.profile));const receipt=path.join(path.dirname(f.profile),'bad-original.json');fs.writeFileSync(receipt,'{}');m.isolatedProofAuthorization={path:'bad-original.json',bytes:2,sha256:sha('{}')};fs.writeFileSync(f.profile,JSON.stringify(m));a.throws(()=>Profile.load(f.profile,sha(fs.readFileSync(f.profile)),{forRun:true,isolatedSourceProof:true}));}));
test('JS sources parse without starting fixture',()=>{for(const rel of ['tools/listmonk-regular-build/native_batch_profile.cjs','tests/segment-regular-native-fixture.cjs'])a.equal(spawnSync(process.execPath,['--check',path.join(base,rel)]).status,0);});

test('old original authorization parser preserved byte-for-byte',()=>{const old=fs.readFileSync(path.join(context,'tools/listmonk-regular-build/native_batch_profile.cjs'),'utf8'),now=fs.readFileSync(path.join(code,'native_batch_profile.cjs'),'utf8'),start=" if(m.isolatedProofAuthorization!==null){",stop=" if(forRun&&",newStop=" if(isolatedSourceProof&&";if(old!==now)a.equal(now.slice(now.indexOf(start),now.indexOf(newStop)),old.slice(old.indexOf(start),old.indexOf(stop)));});
test('missing isolated environment refused',()=>exercise(f=>{delete process.env.REGULAR_NATIVE_PROOF_ISOLATED;a.throws(()=>Profile.load(f.profile,f.sha,{forRun:true,isolatedSourceProof:true}));}));
