'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {DatabaseSync}=require('node:sqlite');
const crypto=require('node:crypto');
const vm=require('node:vm');
const runtime=process.env.SCHEDULER_STATE_RUNTIME||require('node:path').resolve(__dirname,'../../services/dashboard-operational');
const core=require(runtime+'/native-scheduler-state.cjs');
const {createSchedulerStateConsent}=require(runtime+'/native-scheduler-state-consent.cjs');
const {createSchedulerStateController}=require(runtime+'/native-scheduler-state-controller.cjs');
const {renderSchedulerStateOperator,SCHEDULER_STATE_JS}=require(runtime+'/native-scheduler-state-operator.cjs');
const CID='11111111-1111-4111-8111-111111111111',CID2='22222222-2222-4222-8222-222222222222',OWNER='fixture-original-owner';
const H=s=>crypto.createHash('sha256').update(s).digest('hex');
const mac=(key,value)=>crypto.createHmac('sha256',key).update(value).digest('hex');
const NOW=Date.parse('2026-10-09T13:25:00.000Z');
const clone=x=>JSON.parse(JSON.stringify(x));
function storedIdentity(){return {instanceId:CID,workerSha256:H('stored-worker-original'),runtimeSha256:H('stored-runtime-original'),heartbeatAt:'2026-10-09T13:23:00.000Z',expiresAt:'2026-10-09T13:24:00.000Z'};}
function payload(){return {checkedAt:'2026-10-09T13:25:00.000Z',storedIdentity:storedIdentity(),deployment:{present:true,enabled:true,approvalPresent:true,approvalTiming:'effective',queryExpected:true},lease:{present:true,live:false,suspended:false,reason:null},deploymentLeaseMatch:{worker:true,runtime:true,databaseRole:true},selection:{present:true,enabled:false,queryExpected:true,verifiedAt:'2026-10-09T13:24:00.000Z'}};}
function catalog(){return Object.entries(core.COLUMN_TYPES).map(([relation,types])=>({relation,kind:'r',readable:true,columns:Object.entries(types).map(([name,oid])=>({name,oid,typmod:-1}))}));}
function dependencies(){return {workerRoleKnown:true,relations:Object.entries(core.SCANNER_COLUMNS).map(([name,cols])=>({name,present:true,kind:'table',rowSecurity:false,forcedRowSecurity:false,allCampaignColumnsSelect:name==='campaigns'?true:null,columns:Object.keys(cols).map(name2=>({name:name2,present:true,typeCompatible:true,readerSelect:true,workerSelect:true,workerUpdate:name==='campaigns'&&['sent','to_send','status','max_subscriber_id','started_at'].includes(name2)?true:null}))})),functions:core.SCANNER_FUNCTIONS.map(name=>({name,present:true,signatureCompatible:true,workerExecute:true,volatility:'stable',securityDefiner:false})),activityCapability:{readable:true,visible:false}};}
function shapes(){return {observedCount:2,truncated:false,runningCount:0,dueCount:2,attribsTopLevelIncompatible:0,headersIncompatible:0,headersUnknown:0,tagsIncompatible:0,scalarNullIncompatible:0,timestampIncompatible:0,targets:[171,174].map(id=>({id,observed:true,attribsTopLevelCompatible:true,headersCompatible:true,tagsCompatible:true,nonNullableScalarsCompatible:true,finiteTimestampsCompatible:true}))};}
function activity(){return {connectionCount:2,activeCount:1,scannerPrefixMatchCount:1,scannerPrefixWaitingCount:1,maxPrefixAgeSeconds:10,ageCapped:false,states:[{name:'active',count:1},{name:'idle',count:1}],waits:[{name:'Lock',count:1},{name:'Client',count:1}]};}
function selectorFence(){return {sameRole:false,helpers:core.SELECTOR_FUNCTIONS.map(f=>({name:f.name,present:true,purePin:true,executable:true})),relations:core.SELECTOR_RELATIONS.map(r=>({name:r.name,present:true,compatible:true,readable:true})),updateGuard:{present:true,variant:'operation',contractMatches:true,triggerPresent:true,triggerEnabled:true,triggerMatches:true}};}
function selectorPayload(){return {checkedAt:'2026-10-09T13:25:00.000Z',targets:[171,174].map(id=>({id,eligible:true,contextReady:true,bound:false,templateCompatible:true,mediaCompatible:true,countPresent:true,countWithinInt32:true,eligibleCount:2,cursorCompatible:true}))};}
function contextGates(){return {checkedAt:'2026-10-09T13:25:00.000Z',targets:[171,174].map(id=>({id,bindingPresent:false,boundEffective:false,...Object.fromEntries(core.CONTEXT_FLAGS.map(k=>[k,null]))}))};}
function fixture(){
 const env={calls:[],clients:[],options:[],time:NOW,revoked:false,key:'disposable-fixture-key',mod:{},browser:[],bearer:'disposable-fixture-bearer'};
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE crm_native_connections_v1(id TEXT PRIMARY KEY,scopes_json TEXT);CREATE TABLE crm_native_delivery_health_consent_v1(purpose TEXT,receipt TEXT);CREATE TABLE crm_scheduler_read_consent_v1(purpose TEXT,receipt TEXT);');db.prepare('INSERT INTO users VALUES(?)').run(OWNER);for(const id of [CID,CID2])db.prepare('INSERT INTO crm_native_connections_v1 VALUES(?,?)').run(id,JSON.stringify(['crm.read','crm.delivery-health']));db.prepare('INSERT INTO crm_native_delivery_health_consent_v1 VALUES(?,?)').run('crm.delivery-health','accepted-health');db.prepare('INSERT INTO crm_scheduler_read_consent_v1 VALUES(?,?)').run('crm.scheduler-diagnostic','accepted-diagnostic');
 env.credential={schema:'shrigma-private-database-credential-v1',revision:1,ownerId:OWNER,username:'disposable_fixture_reader',password:'secret-never-in-output',resource:{...core.RESOURCE},transport:{mode:'admitted-private-network'}};
 env.context={nativeBearer:env.bearer,method:'GET'};env.browserContext={method:'POST',session:'valid-fixture-session',csrf:'valid-fixture-csrf'};
 const current=(context,id,browser)=>{env.browser.push(browser);assert.ok([CID,CID2].includes(id));if(env.revoked||env.vaultRevoked)throw Error('secret-current-denied');if(browser){assert.equal(context.session,'valid-fixture-session');assert.equal(context.csrf,'valid-fixture-csrf');assert.equal(context.method,'POST');}else assert.ok(context.nativeBearer===env.bearer||context.session==='valid-fixture-session');return {ownerId:OWNER,ownerRevision:H('owner-live'),connectionHash:H(id+'connection'),crmBindingHash:H('original-two-brand-bindings'),profileRevision:mac('real-fixture-mac','auth-profile-revision'),credentialBindingHash:core.credentialBinding(env.credential),resourceHash:core.resourceHash,queryHash:core.queryHash,...env.mod};};
 env.consent=createSchedulerStateConsent({db,current,mac:v=>mac(env.key,v),now:()=>env.time});
 class Client extends EventEmitter{
  constructor(options){super();env.options.push(options);env.clients.push(this);this.connection=new EventEmitter();this.connection.stream={encrypted:false};this.processID=41;}
  async connect(){env.calls.push('connect');if(env.connectError)throw Error('private-connect-error');this.connection.emit('readyForQuery',{status:'I'});}
  async query(sql){env.calls.push(sql);if(env.onQuery)await env.onQuery(sql);if(env.throwSQL===sql)throw Error('private-sql-error '+env.credential.password);let command='SELECT',status='I',rows=[];
   if(sql===core.PEER)rows=[{database:'listmonk',sessionRole:env.credential.username,currentRole:env.credential.username,pid:41,port:5432,engine:170005,ssl:false,read_only:'on',...env.peer}];
   else if(sql===core.BEGIN){command='BEGIN';status='T';}
   else if(sql===core.CATALOG_SQL){status='T';rows=env.catalog||catalog();}
   else if(sql===core.READ_SQL){status='T';rows=env.rows||[{payload:env.payload||payload()}];}
   else if(sql===core.DEPENDENCY_SQL){status='T';rows=env.dependencyRows||[{payload:env.dependencies||dependencies()}];}
   else if(sql===core.SHAPES_SQL){status='T';rows=env.shapeRows||[{payload:env.shapes||shapes()}];}
   else if(sql===core.ACTIVITY_SQL){status='T';rows=env.activityRows||[{payload:env.activity||activity()}];}
   else if(sql===core.SELECTOR_FENCE_SQL){status='T';rows=env.fenceRows||[{payload:env.fence||selectorFence()}];}
   else if(sql===core.CONTEXT_GATES_SQL){status='T';rows=[{payload:env.contextGates||contextGates()}];}
   else if(sql===core.SELECTOR_SQL){status='T';if(env.sqlstate){if(!env.missingErrorACK){if(env.lateErrorACK)setImmediate(()=>this.connection.emit('readyForQuery',{status:'E'}));else this.connection.emit('readyForQuery',{status:env.errorACK||'E'});}if(env.doubleErrorACK)this.connection.emit('readyForQuery',{status:'E'});throw Object.assign(Error('private-error-query-body '+env.credential.password),{code:env.sqlstate});}rows=env.selectorRows||[{payload:env.selectorPayload||selectorPayload()}];}
   else if(sql===core.ROLLBACK)command='ROLLBACK';
   else throw Error('arbitrary query refused in test fixture');
   this.connection.emit('readyForQuery',{status:env.badStatusSQL===sql?'E':status});if(env.doubleACKSQL===sql)this.connection.emit('readyForQuery',{status});
   return {command:env.badCommandSQL===sql?'UPDATE':command,rows,rowCount:command==='SELECT'?rows.length:null};
  }
  async end(){env.calls.push('end');if(env.onEnd)await env.onEnd();if(env.endError)throw Error('private-close-error '+env.credential.password);if(!env.missingEnd)this.emit('end');}
 }
 env.driver={Client,version:'8.23.1',packageSha256:H('disposable-pg-package')};
 env.auth={nativeSchedulerStateConsent:env.consent,nativeDatabaseVault:{getPrivateCredential:({ownerId})=>{assert.equal(ownerId,OWNER);if(env.vaultRevoked)throw Error('private-db-credential-revoked');return {...env.credential};}},nativeConnections:{authenticate:(token,needs)=>{assert.equal(needs.scope,'crm.read');if(token!==env.bearer||env.connectionRevoked)throw Error('private-native-token');return {id:CID};}}};
 env.controller=createSchedulerStateController({enabled:true,driver:env.driver,auth:env.auth,now:()=>env.time});
 env.authorize=(id=CID)=>env.consent.authorize({context:env.browserContext,connectionId:id,consent:true});
 env.read=()=>env.controller.nativeReadReceipt({context:env.context});env.finish=async()=>{try{await env.controller.close();}catch{}db.close();};env.db=db;return env;
}
function assertNoSecrets(value){const s=JSON.stringify(value);for(const word of ['secret-never-in-output','disposable_fixture_reader','approved_by','instance_id','private-sql-error','private-close-error','comunicacao_postgres'])assert.ok(!s.includes(word),word);}
test('dedicated consent refuses a boolean grant and prior purposes before PG',async()=>{const e=fixture();try{await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);assert.throws(()=>e.consent.authorize({context:e.browserContext,connectionId:CID,consent:false}),{code:'SCHEDULER_STATE_BROWSER_CONSENT_REQUIRED'});assert.throws(()=>e.consent.authorize({context:e.context,connectionId:CID,consent:true}),{code:'SCHEDULER_STATE_BROWSER_CONSENT_REQUIRED'});assert.equal(e.consent.status({context:e.context,connectionId:CID}).consented,false);assert.ok(e.browser.every(x=>typeof x==='boolean'));}finally{await e.finish();}});
test('authorize and invalidate alone request browser CURRENT; scopes and old consents stay byte equal',async()=>{const e=fixture();try{const before=e.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all();assert.equal(e.authorize().authorized,true);assert.equal(e.consent.status({context:e.context,connectionId:CID}).consented,true);const proof=e.consent.require({context:e.context,connectionId:CID});assert.match(proof.profileRevision,/^[a-f0-9]{64}$/);assert.equal(Object.keys(proof).length,8);assert.ok(Object.isFrozen(proof));assert.deepEqual(e.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all(),before);assert.equal(e.db.prepare('SELECT receipt FROM crm_native_delivery_health_consent_v1').get().receipt,'accepted-health');assert.equal(e.db.prepare('SELECT receipt FROM crm_scheduler_read_consent_v1').get().receipt,'accepted-diagnostic');e.consent.invalidate({context:e.browserContext,connectionId:CID});assert.throws(()=>e.consent.require({context:e.context,connectionId:CID}),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.throws(()=>e.authorize(),{code:'SCHEDULER_STATE_CONSENT_REVOKED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
for(const field of ['ownerRevision','connectionHash','crmBindingHash','profileRevision','credentialBindingHash','resourceHash','queryHash'])test('CURRENT '+field+' change refuses saved consent before PG',async()=>{const e=fixture();try{e.authorize();e.mod[field]=H('changed-'+field);await assert.rejects(e.read());assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('CURRENT owner change refuses before PG',async()=>{const e=fixture();try{e.authorize();e.mod.ownerId='other-owner';await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('profile revision uses HMAC64 and rejects incompatible numeric fixture without PG',async()=>{const e=fixture();try{e.mod.profileRevision=1;assert.throws(()=>e.authorize(),{code:'SCHEDULER_STATE_CURRENT_REFUSED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('MAC key rotation and tampering cannot authorize old state consent',async()=>{const e=fixture();try{e.authorize();e.key='rotated-fixture-key';await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONSENT_INTEGRITY'});e.key='disposable-fixture-key';e.db.prepare('UPDATE crm_scheduler_state_consent_v1 SET purpose=?').run('crm.delivery-health');await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONSENT_INTEGRITY'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('fixed READONLY protocol confirms I-T-I, closure and returns stored-state-only DTO',async()=>{const e=fixture();try{e.authorize();const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.schema,'shrigma-original-scheduler-stored-state-v4');assert.deepEqual(r.body.storedIdentity,storedIdentity());assert.ok(Object.isFrozen(r.body.storedIdentity));assert.equal(r.body.storedStateOnly,true);assert.equal(r.body.runtimeMeasured,false);assert.equal(r.body.causeEstablished,false);assert.equal(r.body.authorizesSend,false);assert.deepEqual(e.calls,['connect',core.PEER,core.BEGIN,core.CATALOG_SQL,core.READ_SQL,core.DEPENDENCY_SQL,core.SHAPES_SQL,core.SELECTOR_FENCE_SQL,core.ROLLBACK,'end']);assert.match(e.options[0].options,/default_transaction_read_only=on/);assert.equal(e.options[0].pipeline,false);assert.equal(e.options[0].statement_timeout,10000);assertNoSecrets(r);assert.ok(Object.isFrozen(r.body.lease));assert.equal(core.queryHash,H([core.PEER,core.BEGIN,core.CATALOG_SQL,core.READ_SQL,core.DEPENDENCY_SQL,core.SHAPES_SQL,core.ACTIVITY_SQL,core.SELECTOR_FENCE_SQL,core.CONTEXT_GATES_SQL,core.SELECTOR_SQL,core.canonical(core.SELECTOR_PROTOCOL),core.ROLLBACK].join('\n')));for(const sql of [core.CATALOG_SQL,core.READ_SQL])assert.doesNotMatch(sql,/\b(?:INSERT|UPDATE|DELETE|CREATE|GRANT|LOCK|FOR\s+SHARE|heartbeat\s*\(|claim\s*\(|refresh\w*\s*\(|regular_worker_require\s*\()/i);}finally{await e.finish();}});
test('v4 diagnostic receipt is terminal after TTL; same native invocation reads once',async()=>{const e=fixture();try{e.authorize();const r=await e.read();e.payload={...payload(),checkedAt:'2026-10-09T13:40:00.000Z'};assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);e.time+=600001;const fresh=await e.read();assert.equal(fresh.status,200);assert.strictEqual(fresh,r);assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('native receipt concurrent invocation never creates a second SELECT or client',async()=>{const e=fixture();let release,entered;const waiting=new Promise(resolve=>entered=resolve),hold=new Promise(resolve=>release=resolve);try{e.authorize();e.onQuery=async sql=>{if(sql===core.READ_SQL){entered();await hold;}};const first=e.read();await waiting;assert.deepEqual(await e.read(),{status:409,body:{error:'SCHEDULER_STATE_BUSY'}});release();assert.equal((await first).status,200);assert.equal(e.clients.length,1);assert.equal(e.calls.filter(x=>x===core.READ_SQL).length,1);}finally{release?.();await e.finish();}});
for(const reason of ['missing','acl','type'])test('catalog '+reason+' stops before state SELECT with rollback and no DDL',async()=>{const e=fixture();try{e.authorize();e.catalog=catalog();if(reason==='missing')e.catalog[0].kind=null;else if(reason==='acl')e.catalog[0].readable=false;else e.catalog[0].columns[0].oid=25;const r=await e.read();assert.equal(r.status,503);assert.equal(r.body.error,({missing:'SCHEDULER_STATE_DEPENDENCY_MISSING',acl:'SCHEDULER_STATE_ACL_REFUSED',type:'SCHEDULER_STATE_SCHEMA_REFUSED'})[reason]);assert.equal(e.calls.includes(core.READ_SQL),false);assert.ok(e.calls.includes(core.ROLLBACK));e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);assertNoSecrets(r);}finally{await e.finish();}});
test('unknown payload fields and unbounded reason are refused without leaking values',async()=>{const e=fixture();try{e.authorize();e.payload=payload();e.payload.lease.reason='private-arbitrary-error';e.payload.unknown='secret-never-in-output';const r=await e.read();assert.equal(r.status,503);assert.equal(r.body.error,'SCHEDULER_STATE_PROTOCOL_REFUSED');assertNoSecrets(r);assert.ok(e.calls.includes(core.ROLLBACK));}finally{await e.finish();}});
test('validator accepts missing rows as missing state, preserves mismatches and future approval without cause claims',()=>{const p=payload();p.deployment.approvalTiming='future';p.lease.suspended=true;p.lease.reason='deployment_off';p.deploymentLeaseMatch={worker:false,runtime:false,databaseRole:false};const r=core.validateState(p);assert.equal(r.deployment.approvalTiming,'future');assert.equal(r.deploymentLeaseMatch.databaseRole,false);assert.equal(r.causeEstablished,false);const empty={checkedAt:p.checkedAt,storedIdentity:null,deployment:{present:false,enabled:null,approvalPresent:false,approvalTiming:'missing',queryExpected:null},lease:{present:false,live:null,suspended:null,reason:null},deploymentLeaseMatch:{worker:null,runtime:null,databaseRole:null},selection:{present:false,enabled:null,queryExpected:null,verifiedAt:null}};assert.equal(core.validateState(empty).deployment.present,false);});
for(const phase of [core.BEGIN,core.CATALOG_SQL,core.READ_SQL,'end'])test('revocation during '+(phase==='end'?'end':phase===core.READ_SQL?'state':phase===core.CATALOG_SQL?'catalog':'begin')+' suppresses the completed result',async()=>{const e=fixture();try{e.authorize();if(phase==='end')e.onEnd=()=>{e.revoked=true;};else e.onQuery=sql=>{if(sql===phase)e.revoked=true;};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});e.revoked=false;const cached=await e.read();assert.equal(cached.status,409);assertNoSecrets(cached);assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('revocation before read and after cached success denies without an additional SQL',async()=>{const e=fixture();try{e.authorize();e.revoked=true;await assert.rejects(e.read());assert.deepEqual(e.calls,[]);e.revoked=false;await e.read();const n=e.calls.length;e.connectionRevoked=true;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONNECTION_REFUSED'});assert.equal(e.calls.length,n);}finally{await e.finish();}});
for(const kind of ['command','status','double','end-missing','end-failed','query'])test('uncertain '+kind+' is finite, consumes attempt and cannot retry even after TTL',async()=>{const e=fixture();try{e.authorize();if(kind==='command')e.badCommandSQL=core.READ_SQL;else if(kind==='status')e.badStatusSQL=core.READ_SQL;else if(kind==='double')e.doubleACKSQL=core.READ_SQL;else if(kind==='end-missing')e.missingEnd=true;else if(kind==='end-failed')e.endError=true;else e.throwSQL=core.READ_SQL;const r=await e.read();assert.equal(r.status,503);assert.match(r.body.error,/^SCHEDULER_STATE_[A-Z_]+$/);assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);await assert.rejects(e.controller.inspect({context:e.context}));assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('peer identity and default READONLY mismatch are refused before BEGIN',async()=>{const e=fixture();try{e.authorize();e.peer={read_only:'off'};const r=await e.read();assert.equal(r.body.error,'SCHEDULER_STATE_PEER_REFUSED');assert.equal(e.calls.includes(core.BEGIN),false);assert.equal(e.calls.includes(core.READ_SQL),false);}finally{await e.finish();}});
test('credential revision or vault revocation before cached return invalidates binding',async()=>{const e=fixture();try{e.authorize();await e.read();e.credential.revision=2;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('boolean CURRENT response cannot stand in for owner proof',async()=>{const e=fixture();try{const c=createSchedulerStateConsent({db:e.db,current:()=>true,mac:v=>mac('fixture',v)});assert.throws(()=>c.authorize({context:e.browserContext,connectionId:CID,consent:true}),{code:'SCHEDULER_STATE_ARGUMENTS_REFUSED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('catalog selects only the required columns of each relation',()=>{for(const [name,fields] of Object.entries(core.COLUMN_TYPES)){const match=core.CATALOG_SQL.match(new RegExp("e\\.relation='"+name+"' AND a\\.attname IN \\(([^)]+)\\)"));assert.ok(match,name);assert.deepEqual(match[1].replace(/'/g,'').split(',').sort(),Object.keys(fields).sort());}assert.ok(core.READ_SQL.includes('d.topology_receipt_sha256'));assert.equal(core.COLUMN_TYPES.selection.expires_at,undefined);});
for(const field of ['profileRevision','credentialBindingHash','crmBindingHash'])test('CURRENT '+field+' changed during state read suppresses result and prevents replay',async()=>{const e=fixture();try{e.authorize();e.onQuery=sql=>{if(sql===core.READ_SQL)e.mod[field]=H('changed-during-read');};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});delete e.mod[field];const n=e.calls.length;const cached=await e.read();assert.equal(cached.status,409);assert.equal(e.calls.length,n);}finally{await e.finish();}});
test('explicit state-consent invalidation during close suppresses DTO',async()=>{const e=fixture();try{e.authorize();e.onEnd=()=>e.consent.invalidate({context:e.browserContext,connectionId:CID});await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});assert.equal(e.clients.length,1);await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});}finally{await e.finish();}});
test('CURRENT private PG vault revocation suppresses cached200 without reconnect',async()=>{const e=fixture();try{e.authorize();await e.read();e.vaultRevoked=true;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CURRENT_REFUSED'});assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('core requires typed private admission, not a boolean, before creating a PG client',async()=>{const e=fixture();const reader=core.createSchedulerStateRead({enabled:true,driver:e.driver,getPrivateCredential:()=>e.credential,admitState:()=>true});try{await assert.rejects(reader.inspect({}, {ownerId:OWNER}),{code:'SCHEDULER_STATE_ADMISSION_REFUSED'});assert.deepEqual(e.calls,[]);assert.deepEqual(e.clients,[]);}finally{await reader.close();await e.finish();}});
test('consent for another connection cannot authorize the native token current connection',async()=>{const e=fixture();try{e.authorize(CID2);await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('operator uses protected connection-list POST and one explicit authorization, without state read',async()=>{
 const html=renderSchedulerStateOperator({csrf:'</script><script>bad</script>',connections:[{id:CID,label:'secret-not-rendered'}]});
 assert.ok(!html.includes('</script><script>bad'));assert.ok(!html.includes('secret-not-rendered'));assert.ok(html.includes('/auth/scheduler-state.js'));assert.equal((html.match(/<button/g)||[]).length,1);
 const calls=[],elements={'scheduler-state-authorization':{addEventListener:(event,f)=>{elements.submit=f;}},authorize:{disabled:false},result:{textContent:''},'scheduler-state-data':{textContent:JSON.stringify({csrf:'fixture-csrf'})},connection:{value:CID,replaceChildren(){this.value='';},append(option){if(!this.value)this.value=option.value;}}};
 vm.runInNewContext(SCHEDULER_STATE_JS,{document:{getElementById:id=>elements[id],createElement:()=>({})},fetch:async(path,options)=>{calls.push({path,options});return {status:200,json:async()=>({connections:[{id:CID,revoked:false,scopes:['crm.read'],brands:['fish','aristo']}]})};}});
 await new Promise(setImmediate);assert.equal(calls.length,1);assert.equal(calls[0].path,'/auth/native-connections');assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].options.headers['X-CSRF-Token'],'fixture-csrf');assert.deepEqual(JSON.parse(calls[0].options.body),{action:'list'});assert.equal(elements.authorize.disabled,false);
 await elements.submit({preventDefault(){}});await elements.submit({preventDefault(){}});assert.equal(calls.length,2);assert.equal(calls[1].path,'/auth/scheduler-state-settings');assert.equal(calls[1].options.method,'POST');assert.deepEqual(JSON.parse(calls[1].options.body),{action:'authorize',connectionId:CID,consent:true});assert.doesNotMatch(SCHEDULER_STATE_JS,/scheduler-state-receipt|api\/scheduler-state|setInterval|setTimeout/);
});

test('v2 stored identity is bounded and frozen while all operational claims remain false',async()=>{const e=fixture();try{e.authorize();const r=await e.read();assert.equal(r.status,200);assert.deepEqual(r.body.storedIdentity,storedIdentity());assert.equal(r.body.schema,'shrigma-original-scheduler-stored-state-v4');assert.ok(Object.isFrozen(r.body.storedIdentity));assert.deepEqual(Object.keys(r.body.storedIdentity).sort(),['expiresAt','heartbeatAt','instanceId','runtimeSha256','workerSha256']);for(const key of ['runtimeMeasured','causeEstablished','authorizesSend','authorizesRecovery','operational'])assert.equal(r.body[key],false);assertNoSecrets(r);}finally{await e.finish();}});
test('absent lease requires null stored identity and can return other stored state without identity claims',async()=>{const e=fixture();try{e.authorize();e.payload=payload();e.payload.lease={present:false,live:null,suspended:null,reason:null};e.payload.deploymentLeaseMatch={worker:null,runtime:null,databaseRole:null};e.payload.storedIdentity=null;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.storedIdentity,null);assert.equal(r.body.deployment.present,true);assert.equal(r.body.runtimeMeasured,false);}finally{await e.finish();}});
for(const [name,change] of [
 ['missing identity',p=>{delete p.storedIdentity;}],['null present identity',p=>{p.storedIdentity=null;}],
 ['unknown identity field',p=>{p.storedIdentity.role='private-role';}],['missing identity field',p=>{delete p.storedIdentity.expiresAt;}],
 ['short worker hash',p=>{p.storedIdentity.workerSha256='a'.repeat(63);}],['uppercase runtime hash',p=>{p.storedIdentity.runtimeSha256='A'.repeat(64);}],
 ['wrong hash type',p=>{p.storedIdentity.workerSha256=true;}],['nil UUID',p=>{p.storedIdentity.instanceId='00000000-0000-0000-0000-000000000000';}],
 ['malformed UUID',p=>{p.storedIdentity.instanceId='private-caller-instance';}],['uppercase UUID',p=>{p.storedIdentity.instanceId='A1111111-1111-4111-8111-111111111111';}],
 ['invalid calendar timestamp',p=>{p.storedIdentity.heartbeatAt='2026-02-30T13:23:00Z';}],['invalid negative offset',p=>{p.storedIdentity.expiresAt='2026-10-09T13:24:00-99:00';}],
 ['non ISO timestamp',p=>{p.storedIdentity.heartbeatAt='Oct 09 2026';}],['expires before heartbeat',p=>{p.storedIdentity.expiresAt='2026-10-09T13:22:00Z';}],
 ['live disagrees with expired identity',p=>{p.lease.live=true;}],['identity for absent lease',p=>{p.lease={present:false,live:null,suspended:null,reason:null};p.deploymentLeaseMatch={worker:null,runtime:null,databaseRole:null};}]
])test('stored identity '+name+' is refused, closed and never retried',async()=>{const e=fixture();try{e.authorize();e.payload=payload();change(e.payload);const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});assert.ok(e.calls.includes(core.ROLLBACK));assert.equal(e.calls.at(-1),'end');assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('stored lease liveness respects microseconds and equivalent timezone offsets at exact boundaries',()=>{
 const p=payload();p.checkedAt='2026-10-09T13:25:00.000001Z';p.storedIdentity.heartbeatAt='2026-10-09T12:25:00.000000-01:00';p.storedIdentity.expiresAt='2026-10-09T13:25:00.000002Z';p.lease.live=true;assert.equal(core.validateState(p).lease.live,true);
 p.storedIdentity.expiresAt='2026-10-09T13:25:00.000001+00:00';assert.throws(()=>core.validateState(p),{code:'SCHEDULER_STATE_PROTOCOL_REFUSED'});p.lease.live=false;assert.equal(core.validateState(p).lease.live,false);
 p.storedIdentity.heartbeatAt='2026-10-09T13:25:00.000002Z';assert.throws(()=>core.validateState(p),{code:'SCHEDULER_STATE_PROTOCOL_REFUSED'});
 // Original CHECK permits a zero-length stored lease; its live predicate is false.
 p.storedIdentity.heartbeatAt=p.checkedAt;p.storedIdentity.expiresAt=p.checkedAt;p.lease.live=false;assert.equal(core.validateState(p).lease.live,false);p.lease.live=true;assert.throws(()=>core.validateState(p),{code:'SCHEDULER_STATE_PROTOCOL_REFUSED'});
});
for(const n of [0,2])test('state row cardinality '+n+' is refused before any identity projection',async()=>{const e=fixture();try{e.authorize();e.rows=Array.from({length:n},()=>({payload:payload()}));const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});assert.ok(e.calls.includes(core.ROLLBACK));assert.equal(e.calls.at(-1),'end');assert.equal(e.clients.length,1);}finally{await e.finish();}});


test('v3 dependency READ retains sanitized metadata and shapes without helpers or activity privilege',async()=>{const e=fixture();try{e.authorize();const r=await e.read(),d=r.body.scannerDependencies;assert.equal(r.status,200);assert.equal(r.body.schema,'shrigma-original-scheduler-stored-state-v4');assert.equal(d.workerRoleKnown,true);assert.equal(d.rowShapes.observedCount,2);assert.equal(d.rowShapes.helperContextEvaluated,false);assert.equal(d.nextCampaignsExecuted,false);assert.deepEqual(d.activity,{status:'unavailable',reason:'not-visible'});assert.equal(e.calls.includes(core.ACTIVITY_SQL),false);assertNoSecrets(r);assert.ok(Object.isFrozen(d.relations[0].columns[0]));assert.ok(Object.isFrozen(d.rowShapes.targets));for(const sql of [core.DEPENDENCY_SQL,core.SHAPES_SQL,core.ACTIVITY_SQL])assert.doesNotMatch(sql,/\b(?:UPDATE|INSERT|DELETE|EXPLAIN|SET\s+ROLE)\s+(?!')/i);}finally{await e.finish();}});
for(const gate of ['relation-missing','schema-incompatible','row-security','not-readable'])test('v3 '+gate+' yields bounded dependency result and never shapes SELECT',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();const c=e.dependencies.relations.find(r=>r.name==='campaigns');if(gate==='relation-missing'){c.present=false;c.kind='absent';c.rowSecurity=null;c.forcedRowSecurity=null;c.allCampaignColumnsSelect=false;for(const v of c.columns){v.present=false;v.typeCompatible=false;v.readerSelect=false;v.workerSelect=false;if(v.workerUpdate!==null)v.workerUpdate=false;}}else if(gate==='schema-incompatible')c.columns.find(v=>v.name==='headers').typeCompatible=false;else if(gate==='row-security')c.rowSecurity=true;else c.columns.find(v=>v.name==='headers').readerSelect=false;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.scannerDependencies.rowShapes.status,gate);assert.equal(e.calls.includes(core.SHAPES_SQL),false);assert.equal(r.body.causeEstablished,false);assertNoSecrets(r);}finally{await e.finish();}});
test('v3 worker ACL denial and missing function remain explicit, never impersonate worker',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();e.dependencies.relations.find(r=>r.name==='subscriber_lists').columns[0].workerSelect=false;const fn=e.dependencies.functions[0];Object.assign(fn,{present:false,signatureCompatible:false,workerExecute:false,volatility:null,securityDefiner:null});const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.scannerDependencies.functions[0].present,false);assert.equal(r.body.scannerDependencies.relations.find(r=>r.name==='subscriber_lists').columns[0].workerSelect,false);assert.equal(r.body.causeEstablished,false);}finally{await e.finish();}});
test('v3 optional activity reports only bounded counts enums and age, never query pid role',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();e.dependencies.activityCapability.visible=true;const r=await e.read();assert.equal(r.status,200);const a=r.body.scannerDependencies.activity;assert.equal(a.status,'observed');assert.equal(a.scannerPrefixMatchCount,1);assert.equal(a.match,'fixed-prefix-only');assert.equal(a.maxPrefixAgeSeconds,10);assert.equal(e.calls.filter(x=>x===core.ACTIVITY_SQL).length,1);assert.ok(Object.isFrozen(a.states[0]));assertNoSecrets(r);assert.doesNotMatch(JSON.stringify(a),/query|pid|role/i);}finally{await e.finish();}});
test('v3 activity SELECT privilege absence explicitly skips the optional view',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();e.dependencies.activityCapability.readable=false;e.dependencies.activityCapability.visible=true;const r=await e.read();assert.deepEqual(r.body.scannerDependencies.activity,{status:'unavailable',reason:'not-readable'});assert.equal(e.calls.includes(core.ACTIVITY_SQL),false);}finally{await e.finish();}});
for(const [name,change] of [['unknown column',d=>{d.relations[0].columns[0].sql='secret-never-in-output';}],['unknown function',d=>{d.functions[0].name='untrusted';}],['bad volatility',d=>{d.functions[0].volatility='private-error';}],['duplicate relation',d=>{d.relations[1]=d.relations[0];}],['unknown role with privilege claim',d=>{d.workerRoleKnown=false;}],['malformed boolean',d=>{d.relations[0].columns[0].readerSelect='true';}]])test('v3 malformed '+name+' closes and consumes without replay',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();change(e.dependencies);const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});assert.equal(e.calls.at(-1),'end');assert.ok(e.calls.includes(core.ROLLBACK));e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);assertNoSecrets(r);}finally{await e.finish();}});
for(const sqlName of ['DEPENDENCY_SQL','SHAPES_SQL','ACTIVITY_SQL'])test('v3 revocation during '+sqlName+' suppresses DTO and prevents retry',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();e.dependencies.activityCapability.visible=true;e.onQuery=sql=>{if(sql===core[sqlName])e.mod.profileRevision=H('late-profile-change');};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});delete e.mod.profileRevision;const n=e.calls.length;assert.equal((await e.read()).status,409);assert.equal(e.calls.length,n);}finally{await e.finish();}});
for(const [name,change] of [['count beyond limit',s=>{s.observedCount=1001;}],['targets duplicated',s=>{s.targets[1]=s.targets[0];}],['aggregate mismatch',s=>{s.dueCount=0;}],['unknown payload',s=>{s.headers='private-content';}],['unobserved target claims shape',s=>{s.targets[0].observed=false;}],['target incompatible count contradiction',s=>{s.targets[0].headersCompatible=false;}],['target unknown count contradiction',s=>{s.targets[0].headersCompatible=null;}]])test('v3 invalid shape '+name+' refused without values',async()=>{const e=fixture();try{e.authorize();e.shapes=shapes();change(e.shapes);const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});assertNoSecrets(r);}finally{await e.finish();}});
test('v3 truncated shapes and unknown headers remain inconclusive',async()=>{const e=fixture();try{e.authorize();e.shapes=shapes();Object.assign(e.shapes,{observedCount:1000,dueCount:1000,truncated:true,headersUnknown:1});e.shapes.targets[1].headersCompatible=null;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.scannerDependencies.rowShapes.truncated,true);assert.equal(r.body.scannerDependencies.rowShapes.headersUnknown,1);assert.equal(r.body.causeEstablished,false);}finally{await e.finish();}});
for(const [name,change] of [['unknown event',a=>{a.waits[0].name='secret-event';}],['count mismatch',a=>{a.connectionCount=1;}],['age infinite',a=>{a.maxPrefixAgeSeconds=Infinity;}],['unknown field',a=>{a.query='private-query';}],['state count contradiction',a=>{a.states[0].name='unknown';}]])test('v3 invalid activity '+name+' refused and sticky',async()=>{const e=fixture();try{e.authorize();e.dependencies=dependencies();e.dependencies.activityCapability.visible=true;e.activity=activity();change(e.activity);const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});e.time+=600001;assert.strictEqual(await e.read(),r);assertNoSecrets(r);}finally{await e.finish();}});
for(const n of [0,2])test('v3 metadata row cardinality '+n+' is refused and rolled back',async()=>{const e=fixture();try{e.authorize();e.dependencyRows=Array.from({length:n},()=>({payload:dependencies()}));const r=await e.read();assert.deepEqual(r,{status:503,body:{error:'SCHEDULER_STATE_PROTOCOL_REFUSED'}});assert.ok(e.calls.includes(core.ROLLBACK));}finally{await e.finish();}});

for(const fault of ['ack','query','end'])test('v3 '+fault+' failure during dependency attempt is closed and never retried',async()=>{const e=fixture();try{e.authorize();if(fault==='ack')e.badStatusSQL=core.DEPENDENCY_SQL;else if(fault==='query')e.throwSQL=core.DEPENDENCY_SQL;else e.endError=true;const r=await e.read();assert.equal(r.status,503);assertNoSecrets(r);const n=e.calls.length;e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.calls.length,n);assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('v3 concurrent dependency READ is single-flight with no extra SELECT or client',async()=>{const e=fixture();let release,entered;const hold=new Promise(resolve=>release=resolve),waiting=new Promise(resolve=>entered=resolve);try{e.authorize();e.onQuery=async sql=>{if(sql===core.DEPENDENCY_SQL){entered();await hold;}};const first=e.read();await waiting;assert.deepEqual(await e.read(),{status:409,body:{error:'SCHEDULER_STATE_BUSY'}});release();assert.equal((await first).status,200);assert.equal(e.calls.filter(x=>x===core.DEPENDENCY_SQL).length,1);assert.equal(e.clients.length,1);}finally{release?.();await e.finish();}});

// New v4 behaviour only: no original SQL, worker or customer is exercised.
test('v4 same actual role is mandatory; reader ACL booleans never impersonate worker',async()=>{const e=fixture();try{e.authorize();const r=await e.read();assert.equal(r.body.selectorDiagnostic.reason,'same-role-required');assert.equal(r.body.selectorDiagnostic.executed,false);assert.equal(e.calls.includes(core.SELECTOR_SQL),false);assert.equal(r.body.selectorDiagnostic.rollbackConfirmed,true);assert.equal(r.body.selectorDiagnostic.endConfirmed,true);assertNoSecrets(r);}finally{await e.finish();}});
test('v4 pure fixed SELECT executes once and projects only aggregate flags under original budgets',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.selectorDiagnostic.status,'observed');assert.equal(r.body.selectorDiagnostic.phase,'select');assert.equal(r.body.selectorDiagnostic.sqlstate,null);assert.equal(r.body.selectorDiagnostic.targets.length,2);assert.equal(r.body.causeEstablished,false);assert.equal(r.body.selectorDiagnostic.originalScannerError,false);assert.deepEqual(e.calls.slice(-3),[core.SELECTOR_SQL,core.ROLLBACK,'end']);assert.equal(e.options[0].statement_timeout,10000);assert.equal(e.options[0].lock_timeout,500);assert.equal(e.options[0].query_timeout,12000);assert.match(core.BEGIN,/READ COMMITTED READ ONLY/);assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.calls.filter(x=>x===core.SELECTOR_SQL).length,1);}finally{await e.finish();}});
for(const [field,reason] of [['present','helper-missing'],['purePin','helper-pin-mismatch'],['executable','helper-acl']])test('v4 helper '+field+' refusal precedes any helper evaluation',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.fence.helpers[0][field]=false;if(field==='present'){e.fence.helpers[0].purePin=false;e.fence.helpers[0].executable=false;}const r=await e.read();assert.equal(r.body.selectorDiagnostic.reason,reason);assert.equal(e.calls.includes(core.SELECTOR_SQL),false);assertNoSecrets(r);}finally{await e.finish();}});
for(const [field,reason] of [['present','relation-missing'],['compatible','relation-incompatible'],['readable','relation-acl']])test('v4 transitive relation '+field+' refusal precedes selector',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.fence.relations[0][field]=false;if(field==='present'){e.fence.relations[0].compatible=false;e.fence.relations[0].readable=false;}const r=await e.read();assert.equal(r.body.selectorDiagnostic.reason,reason);assert.equal(e.calls.includes(core.SELECTOR_SQL),false);}finally{await e.finish();}});
for(const state of ['55000','57014','42501','55P03','42703'])test('v4 known SQLSTATE '+state+' confirms E→ROLLBACK I→end and consumes attempt',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.sqlstate=state;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.selectorDiagnostic.status,'postgres-error');assert.equal(r.body.selectorDiagnostic.sqlstate,state);assert.equal(r.body.selectorDiagnostic.targets,null);assert.equal(r.body.selectorDiagnostic.rollbackConfirmed,true);assert.equal(r.body.selectorDiagnostic.endConfirmed,true);assert.deepEqual(e.calls.slice(-3),[core.SELECTOR_SQL,core.ROLLBACK,'end']);assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);}finally{await e.finish();}});
for(const fault of ['unknown-state','wrong-ACK','double-ACK','query-throw','rollback-ACK','end-fail'])test('v4 uncertain '+fault+' suppresses diagnostic and remains consumed',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.sqlstate='55000';if(fault==='unknown-state')e.sqlstate='ABCDE';if(fault==='wrong-ACK')e.errorACK='T';if(fault==='double-ACK')e.doubleErrorACK=true;if(fault==='query-throw'){delete e.sqlstate;e.throwSQL=core.SELECTOR_SQL;}if(fault==='rollback-ACK')e.badStatusSQL=core.ROLLBACK;if(fault==='end-fail')e.endError=true;const r=await e.read();assert.equal(r.status,503);assert.equal(r.body.selectorDiagnostic,undefined);assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);}finally{await e.finish();}});
for(const field of ['profileRevision','credentialBindingHash','crmBindingHash'])test('v4 CURRENT '+field+' changes during selector suppress result and prohibit replay',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.onQuery=sql=>{if(sql===core.SELECTOR_SQL)e.mod[field]=H('late-change');};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});delete e.mod[field];assert.equal((await e.read()).status,409);assert.equal(e.calls.filter(x=>x===core.SELECTOR_SQL).length,1);}finally{await e.finish();}});
test('v4 revocation during end suppresses known SQLSTATE',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.sqlstate='57014';e.onEnd=()=>{e.revoked=true;};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});e.revoked=false;assert.equal((await e.read()).status,409);}finally{await e.finish();}});
test('v4 selector is single-flight even while a known negative read is pending',async()=>{const e=fixture();let release,entered;const hold=new Promise(r=>release=r),pending=new Promise(r=>entered=r);try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.onQuery=async sql=>{if(sql===core.SELECTOR_SQL){entered();await hold;}};const first=e.read();await pending;assert.equal((await e.read()).status,409);release();assert.equal((await first).status,200);assert.equal(e.calls.filter(x=>x===core.SELECTOR_SQL).length,1);}finally{release?.();await e.finish();}});
for(const variant of ['draft-only','operation','unknown'])test('v4 UPDATE guard '+variant+' is metadata only and not a claim of cause',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.fence.updateGuard.variant=variant;const r=await e.read();assert.equal(r.body.selectorDiagnostic.updateGuard.variant,variant);assert.equal(r.body.selectorDiagnostic.status,'observed');assert.equal(r.body.causeEstablished,false);assertNoSecrets(r);}finally{await e.finish();}});
for(const change of [v=>v.targets[0].eligibleCount=2147483648,v=>v.targets[1]=v.targets[0],v=>v.targets[0].body='private-content',v=>v.targets[0].bound=null])test('v4 malformed aggregate projection is refused and rolled back',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.selectorPayload=selectorPayload();change(e.selectorPayload);const r=await e.read();assert.equal(r.status,503);assert.ok(e.calls.includes(core.ROLLBACK));assertNoSecrets(r);}finally{await e.finish();}});
test('v4 absent targets and absent native count retain nulls rather than invented zero',()=>{const v=selectorPayload();v.targets[0]={id:171,eligible:false,contextReady:null,bound:null,templateCompatible:null,mediaCompatible:null,countPresent:null,countWithinInt32:null,eligibleCount:null,cursorCompatible:null};v.targets[1].countPresent=false;v.targets[1].countWithinInt32=null;v.targets[1].eligibleCount=null;v.targets[1].cursorCompatible=null;assert.equal(core.validateSelector(v).targets[0].eligible,false);});

test('v4 55000 retains direct bounded gates without claiming the false gate caused the scanner error',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.contextGates=contextGates();Object.assign(e.contextGates.targets[0],{bindingPresent:true,boundEffective:true,...Object.fromEntries(core.CONTEXT_FLAGS.map(k=>[k,true])),configFresh:false});e.sqlstate='55000';const r=await e.read();assert.equal(r.body.selectorDiagnostic.sqlstate,'55000');assert.equal(r.body.selectorDiagnostic.contextGates.targets[0].configFresh,false);assert.equal(r.body.selectorDiagnostic.contextGates.targets[0].selectionFresh,true);assert.equal(r.body.causeEstablished,false);assertNoSecrets(r);}finally{await e.finish();}});

test('v4 asynchronous PostgreSQL error ACK is confirmed before rollback and release',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;e.sqlstate='55000';e.lateErrorACK=true;const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.selectorDiagnostic.sqlstate,'55000');assert.equal(r.body.selectorDiagnostic.rollbackConfirmed,true);}finally{await e.finish();}});
for(const missing of ['query-never-settles','known-error-without-ACK'])test('v4 12s context bounds '+missing+' without inventing rollback confirmation',async t=>{const e=fixture();let entered;const waiting=new Promise(r=>entered=r);try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;if(missing==='known-error-without-ACK'){e.sqlstate='55000';e.missingErrorACK=true;}e.onQuery=sql=>{if(sql===core.SELECTOR_SQL){entered();if(missing==='query-never-settles')return new Promise(()=>{});}};t.mock.timers.enable({apis:['setTimeout']});const first=e.read();await waiting;await new Promise(setImmediate);t.mock.timers.tick(12001);const r=await first;assert.equal(r.status,503);assert.equal(r.body.selectorDiagnostic,undefined);assert.equal(e.calls.includes(core.ROLLBACK),false);assert.equal(e.calls.at(-1),'end');e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);}finally{t.mock.timers.reset();await e.finish();}});
test('v4 fence DTO identifies the exact pinned helper and transitive relation mismatch',async()=>{const e=fixture();try{e.authorize();e.fence=selectorFence();e.fence.sameRole=true;const f=e.fence.helpers.find(f=>f.name==='selection_lists_valid');f.purePin=false;e.fence.relations.find(r=>r.name==='config').compatible=false;const r=await e.read();assert.equal(r.body.selectorDiagnostic.fence.helpers.find(f=>f.name==='selection_lists_valid').purePin,false);assert.equal(r.body.selectorDiagnostic.fence.relations.find(r=>r.name==='config').compatible,false);assert.equal(e.calls.includes(core.SELECTOR_SQL),false);assert.equal(e.calls.includes(core.CONTEXT_GATES_SQL),false);assertNoSecrets(r);}finally{await e.finish();}});
