'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {DatabaseSync}=require('node:sqlite');
const crypto=require('node:crypto');
const vm=require('node:vm');
const runtime=process.env.SCHEDULER_STATE_RUNTIME||require('node:path').resolve(__dirname,'../../services/dashboard-operational');
const core=require(runtime+'/native-scheduler-state.cjs');
const {createSchedulerStateConsent}=require(runtime+'/native-scheduler-state-consent.cjs');
const {createSchedulerStateController}=require(runtime+'/native-scheduler-state-controller.cjs');
const {renderSchedulerStateOperator,SCHEDULER_STATE_JS}=require(runtime+'/native-scheduler-state-operator.cjs');
const CID='11111111-1111-4111-8111-111111111111',CID2='22222222-2222-4222-8222-222222222222',OWNER='fixture-original-owner';
const H=s=>crypto.createHash('sha256').update(s).digest('hex');
const mac=(key,value)=>crypto.createHmac('sha256',key).update(value).digest('hex');
const NOW=Date.parse('2026-10-09T13:25:00.000Z');
const clone=x=>JSON.parse(JSON.stringify(x));
function payload(){return {checkedAt:'2026-10-09T13:25:00.000Z',deployment:{present:true,enabled:true,approvalPresent:true,approvalTiming:'effective',queryExpected:true},lease:{present:true,live:false,suspended:false,reason:null},deploymentLeaseMatch:{worker:true,runtime:true,databaseRole:true},selection:{present:true,enabled:false,queryExpected:true,verifiedAt:'2026-10-09T13:24:00.000Z'}};}
function catalog(){return Object.entries(core.COLUMN_TYPES).map(([relation,types])=>({relation,kind:'r',readable:true,columns:Object.entries(types).map(([name,oid])=>({name,oid,typmod:-1}))}));}
function fixture(){
 const env={calls:[],clients:[],options:[],time:NOW,revoked:false,key:'disposable-fixture-key',mod:{},browser:[],bearer:'disposable-fixture-bearer'};
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE crm_native_connections_v1(id TEXT PRIMARY KEY,scopes_json TEXT);CREATE TABLE crm_native_delivery_health_consent_v1(purpose TEXT,receipt TEXT);CREATE TABLE crm_scheduler_read_consent_v1(purpose TEXT,receipt TEXT);');db.prepare('INSERT INTO users VALUES(?)').run(OWNER);for(const id of [CID,CID2])db.prepare('INSERT INTO crm_native_connections_v1 VALUES(?,?)').run(id,JSON.stringify(['crm.read','crm.delivery-health']));db.prepare('INSERT INTO crm_native_delivery_health_consent_v1 VALUES(?,?)').run('crm.delivery-health','accepted-health');db.prepare('INSERT INTO crm_scheduler_read_consent_v1 VALUES(?,?)').run('crm.scheduler-diagnostic','accepted-diagnostic');
 env.credential={schema:'shrigma-private-database-credential-v1',revision:1,ownerId:OWNER,username:'disposable_fixture_reader',password:'secret-never-in-output',resource:{...core.RESOURCE},transport:{mode:'admitted-private-network'}};
 env.context={nativeBearer:env.bearer,method:'GET'};env.browserContext={method:'POST',session:'valid-fixture-session',csrf:'valid-fixture-csrf'};
 const current=(context,id,browser)=>{env.browser.push(browser);assert.ok([CID,CID2].includes(id));if(env.revoked||env.vaultRevoked)throw Error('secret-current-denied');if(browser){assert.equal(context.session,'valid-fixture-session');assert.equal(context.csrf,'valid-fixture-csrf');assert.equal(context.method,'POST');}else assert.ok(context.nativeBearer===env.bearer||context.session==='valid-fixture-session');return {ownerId:OWNER,ownerRevision:H('owner-live'),connectionHash:H(id+'connection'),crmBindingHash:H('original-two-brand-bindings'),profileRevision:mac('real-fixture-mac','auth-profile-revision'),credentialBindingHash:core.credentialBinding(env.credential),resourceHash:core.resourceHash,queryHash:core.queryHash,...env.mod};};
 env.consent=createSchedulerStateConsent({db,current,mac:v=>mac(env.key,v),now:()=>env.time});
 class Client extends EventEmitter{
  constructor(options){super();env.options.push(options);env.clients.push(this);this.connection=new EventEmitter();this.connection.stream={encrypted:false};this.processID=41;}
  async connect(){env.calls.push('connect');if(env.connectError)throw Error('private-connect-error');this.connection.emit('readyForQuery',{status:'I'});}
  async query(sql){env.calls.push(sql);if(env.onQuery)await env.onQuery(sql);if(env.throwSQL===sql)throw Error('private-sql-error '+env.credential.password);let command='SELECT',status='I',rows=[];
   if(sql===core.PEER)rows=[{database:'listmonk',sessionRole:env.credential.username,currentRole:env.credential.username,pid:41,port:5432,engine:170005,ssl:false,read_only:'on',...env.peer}];
   else if(sql===core.BEGIN){command='BEGIN';status='T';}
   else if(sql===core.CATALOG_SQL){status='T';rows=env.catalog||catalog();}
   else if(sql===core.READ_SQL){status='T';rows=env.rows||[{payload:env.payload||payload()}];}
   else if(sql===core.ROLLBACK)command='ROLLBACK';
   else throw Error('arbitrary query refused in test fixture');
   this.connection.emit('readyForQuery',{status:env.badStatusSQL===sql?'E':status});if(env.doubleACKSQL===sql)this.connection.emit('readyForQuery',{status});
   return {command:env.badCommandSQL===sql?'UPDATE':command,rows,rowCount:command==='SELECT'?rows.length:null};
  }
  async end(){env.calls.push('end');if(env.onEnd)await env.onEnd();if(env.endError)throw Error('private-close-error '+env.credential.password);if(!env.missingEnd)this.emit('end');}
 }
 env.driver={Client,version:'8.23.1',packageSha256:H('disposable-pg-package')};
 env.auth={nativeSchedulerStateConsent:env.consent,nativeDatabaseVault:{getPrivateCredential:({ownerId})=>{assert.equal(ownerId,OWNER);if(env.vaultRevoked)throw Error('private-db-credential-revoked');return {...env.credential};}},nativeConnections:{authenticate:(token,needs)=>{assert.equal(needs.scope,'crm.read');if(token!==env.bearer||env.connectionRevoked)throw Error('private-native-token');return {id:CID};}}};
 env.controller=createSchedulerStateController({enabled:true,driver:env.driver,auth:env.auth,now:()=>env.time});
 env.authorize=(id=CID)=>env.consent.authorize({context:env.browserContext,connectionId:id,consent:true});
 env.read=()=>env.controller.nativeReadReceipt({context:env.context});env.finish=async()=>{try{await env.controller.close();}catch{}db.close();};env.db=db;return env;
}
function assertNoSecrets(value){const s=JSON.stringify(value);for(const word of ['secret-never-in-output','disposable_fixture_reader','approved_by','instance_id','private-sql-error','private-close-error','comunicacao_postgres'])assert.ok(!s.includes(word),word);}
test('dedicated consent refuses a boolean grant and prior purposes before PG',async()=>{const e=fixture();try{await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);assert.throws(()=>e.consent.authorize({context:e.browserContext,connectionId:CID,consent:false}),{code:'SCHEDULER_STATE_BROWSER_CONSENT_REQUIRED'});assert.throws(()=>e.consent.authorize({context:e.context,connectionId:CID,consent:true}),{code:'SCHEDULER_STATE_BROWSER_CONSENT_REQUIRED'});assert.equal(e.consent.status({context:e.context,connectionId:CID}).consented,false);assert.ok(e.browser.every(x=>typeof x==='boolean'));}finally{await e.finish();}});
test('authorize and invalidate alone request browser CURRENT; scopes and old consents stay byte equal',async()=>{const e=fixture();try{const before=e.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all();assert.equal(e.authorize().authorized,true);assert.equal(e.consent.status({context:e.context,connectionId:CID}).consented,true);const proof=e.consent.require({context:e.context,connectionId:CID});assert.match(proof.profileRevision,/^[a-f0-9]{64}$/);assert.equal(Object.keys(proof).length,8);assert.ok(Object.isFrozen(proof));assert.deepEqual(e.db.prepare('SELECT * FROM crm_native_connections_v1 ORDER BY id').all(),before);assert.equal(e.db.prepare('SELECT receipt FROM crm_native_delivery_health_consent_v1').get().receipt,'accepted-health');assert.equal(e.db.prepare('SELECT receipt FROM crm_scheduler_read_consent_v1').get().receipt,'accepted-diagnostic');e.consent.invalidate({context:e.browserContext,connectionId:CID});assert.throws(()=>e.consent.require({context:e.context,connectionId:CID}),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.throws(()=>e.authorize(),{code:'SCHEDULER_STATE_CONSENT_REVOKED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
for(const field of ['ownerRevision','connectionHash','crmBindingHash','profileRevision','credentialBindingHash','resourceHash','queryHash'])test('CURRENT '+field+' change refuses saved consent before PG',async()=>{const e=fixture();try{e.authorize();e.mod[field]=H('changed-'+field);await assert.rejects(e.read());assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('CURRENT owner change refuses before PG',async()=>{const e=fixture();try{e.authorize();e.mod.ownerId='other-owner';await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('profile revision uses HMAC64 and rejects incompatible numeric fixture without PG',async()=>{const e=fixture();try{e.mod.profileRevision=1;assert.throws(()=>e.authorize(),{code:'SCHEDULER_STATE_CURRENT_REFUSED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('MAC key rotation and tampering cannot authorize old state consent',async()=>{const e=fixture();try{e.authorize();e.key='rotated-fixture-key';await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONSENT_INTEGRITY'});e.key='disposable-fixture-key';e.db.prepare('UPDATE crm_scheduler_state_consent_v1 SET purpose=?').run('crm.delivery-health');await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONSENT_INTEGRITY'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('fixed READONLY protocol confirms I-T-I, closure and returns stored-state-only DTO',async()=>{const e=fixture();try{e.authorize();const r=await e.read();assert.equal(r.status,200);assert.equal(r.body.storedStateOnly,true);assert.equal(r.body.runtimeMeasured,false);assert.equal(r.body.causeEstablished,false);assert.equal(r.body.authorizesSend,false);assert.deepEqual(e.calls,['connect',core.PEER,core.BEGIN,core.CATALOG_SQL,core.READ_SQL,core.ROLLBACK,'end']);assert.match(e.options[0].options,/default_transaction_read_only=on/);assert.equal(e.options[0].pipeline,false);assert.equal(e.options[0].statement_timeout,8000);assertNoSecrets(r);assert.ok(Object.isFrozen(r.body.lease));assert.equal(core.queryHash,H([core.PEER,core.BEGIN,core.CATALOG_SQL,core.READ_SQL,core.ROLLBACK].join('\n')));for(const sql of [core.CATALOG_SQL,core.READ_SQL])assert.doesNotMatch(sql,/\b(?:INSERT|UPDATE|DELETE|CREATE|GRANT|LOCK|FOR\s+SHARE|heartbeat\s*\(|claim\s*\(|refresh\w*\s*\(|regular_worker_require\s*\()/i);}finally{await e.finish();}});
test('only closed200 may refresh after TTL; same native invocation reads once',async()=>{const e=fixture();try{e.authorize();const r=await e.read();e.payload={...payload(),checkedAt:'2026-10-09T13:40:00.000Z'};assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);e.time+=600001;const fresh=await e.read();assert.equal(fresh.status,200);assert.notEqual(fresh.body.checkedAt,r.body.checkedAt);assert.equal(e.clients.length,2);}finally{await e.finish();}});
test('native receipt concurrent invocation never creates a second SELECT or client',async()=>{const e=fixture();let release,entered;const waiting=new Promise(resolve=>entered=resolve),hold=new Promise(resolve=>release=resolve);try{e.authorize();e.onQuery=async sql=>{if(sql===core.READ_SQL){entered();await hold;}};const first=e.read();await waiting;assert.deepEqual(await e.read(),{status:409,body:{error:'SCHEDULER_STATE_BUSY'}});release();assert.equal((await first).status,200);assert.equal(e.clients.length,1);assert.equal(e.calls.filter(x=>x===core.READ_SQL).length,1);}finally{release?.();await e.finish();}});
for(const reason of ['missing','acl','type'])test('catalog '+reason+' stops before state SELECT with rollback and no DDL',async()=>{const e=fixture();try{e.authorize();e.catalog=catalog();if(reason==='missing')e.catalog[0].kind=null;else if(reason==='acl')e.catalog[0].readable=false;else e.catalog[0].columns[0].oid=25;const r=await e.read();assert.equal(r.status,503);assert.equal(r.body.error,({missing:'SCHEDULER_STATE_DEPENDENCY_MISSING',acl:'SCHEDULER_STATE_ACL_REFUSED',type:'SCHEDULER_STATE_SCHEMA_REFUSED'})[reason]);assert.equal(e.calls.includes(core.READ_SQL),false);assert.ok(e.calls.includes(core.ROLLBACK));e.time+=600001;assert.strictEqual(await e.read(),r);assert.equal(e.clients.length,1);assertNoSecrets(r);}finally{await e.finish();}});
test('unknown payload fields and unbounded reason are refused without leaking values',async()=>{const e=fixture();try{e.authorize();e.payload=payload();e.payload.lease.reason='private-arbitrary-error';e.payload.unknown='secret-never-in-output';const r=await e.read();assert.equal(r.status,503);assert.equal(r.body.error,'SCHEDULER_STATE_PROTOCOL_REFUSED');assertNoSecrets(r);assert.ok(e.calls.includes(core.ROLLBACK));}finally{await e.finish();}});
test('validator accepts missing rows as missing state, preserves mismatches and future approval without cause claims',()=>{const p=payload();p.deployment.approvalTiming='future';p.lease.suspended=true;p.lease.reason='deployment_off';p.deploymentLeaseMatch={worker:false,runtime:false,databaseRole:false};const r=core.validateState(p);assert.equal(r.deployment.approvalTiming,'future');assert.equal(r.deploymentLeaseMatch.databaseRole,false);assert.equal(r.causeEstablished,false);const empty={checkedAt:p.checkedAt,deployment:{present:false,enabled:null,approvalPresent:false,approvalTiming:'missing',queryExpected:null},lease:{present:false,live:null,suspended:null,reason:null},deploymentLeaseMatch:{worker:null,runtime:null,databaseRole:null},selection:{present:false,enabled:null,queryExpected:null,verifiedAt:null}};assert.equal(core.validateState(empty).deployment.present,false);});
for(const phase of [core.BEGIN,core.CATALOG_SQL,core.READ_SQL,'end'])test('revocation during '+(phase==='end'?'end':phase===core.READ_SQL?'state':phase===core.CATALOG_SQL?'catalog':'begin')+' suppresses the completed result',async()=>{const e=fixture();try{e.authorize();if(phase==='end')e.onEnd=()=>{e.revoked=true;};else e.onQuery=sql=>{if(sql===phase)e.revoked=true;};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});e.revoked=false;const cached=await e.read();assert.equal(cached.status,409);assertNoSecrets(cached);assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('revocation before read and after cached success denies without an additional SQL',async()=>{const e=fixture();try{e.authorize();e.revoked=true;await assert.rejects(e.read());assert.deepEqual(e.calls,[]);e.revoked=false;await e.read();const n=e.calls.length;e.connectionRevoked=true;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CONNECTION_REFUSED'});assert.equal(e.calls.length,n);}finally{await e.finish();}});
for(const kind of ['command','status','double','end-missing','end-failed','query'])test('uncertain '+kind+' is finite, consumes attempt and cannot retry even after TTL',async()=>{const e=fixture();try{e.authorize();if(kind==='command')e.badCommandSQL=core.READ_SQL;else if(kind==='status')e.badStatusSQL=core.READ_SQL;else if(kind==='double')e.doubleACKSQL=core.READ_SQL;else if(kind==='end-missing')e.missingEnd=true;else if(kind==='end-failed')e.endError=true;else e.throwSQL=core.READ_SQL;const r=await e.read();assert.equal(r.status,503);assert.match(r.body.error,/^SCHEDULER_STATE_[A-Z_]+$/);assertNoSecrets(r);e.time+=600001;assert.strictEqual(await e.read(),r);await assert.rejects(e.controller.inspect({context:e.context}));assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('peer identity and default READONLY mismatch are refused before BEGIN',async()=>{const e=fixture();try{e.authorize();e.peer={read_only:'off'};const r=await e.read();assert.equal(r.body.error,'SCHEDULER_STATE_PEER_REFUSED');assert.equal(e.calls.includes(core.BEGIN),false);assert.equal(e.calls.includes(core.READ_SQL),false);}finally{await e.finish();}});
test('credential revision or vault revocation before cached return invalidates binding',async()=>{const e=fixture();try{e.authorize();await e.read();e.credential.revision=2;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('boolean CURRENT response cannot stand in for owner proof',async()=>{const e=fixture();try{const c=createSchedulerStateConsent({db:e.db,current:()=>true,mac:v=>mac('fixture',v)});assert.throws(()=>c.authorize({context:e.browserContext,connectionId:CID,consent:true}),{code:'SCHEDULER_STATE_ARGUMENTS_REFUSED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('catalog selects only the required columns of each relation',()=>{for(const [name,fields] of Object.entries(core.COLUMN_TYPES)){const match=core.CATALOG_SQL.match(new RegExp("e\\.relation='"+name+"' AND a\\.attname IN \\(([^)]+)\\)"));assert.ok(match,name);assert.deepEqual(match[1].replace(/'/g,'').split(',').sort(),Object.keys(fields).sort());}assert.ok(core.READ_SQL.includes('d.topology_receipt_sha256'));assert.equal(core.COLUMN_TYPES.selection.expires_at,undefined);});
for(const field of ['profileRevision','credentialBindingHash','crmBindingHash'])test('CURRENT '+field+' changed during state read suppresses result and prevents replay',async()=>{const e=fixture();try{e.authorize();e.onQuery=sql=>{if(sql===core.READ_SQL)e.mod[field]=H('changed-during-read');};await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});delete e.mod[field];const n=e.calls.length;const cached=await e.read();assert.equal(cached.status,409);assert.equal(e.calls.length,n);}finally{await e.finish();}});
test('explicit state-consent invalidation during close suppresses DTO',async()=>{const e=fixture();try{e.authorize();e.onEnd=()=>e.consent.invalidate({context:e.browserContext,connectionId:CID});await assert.rejects(e.read(),{code:'SCHEDULER_STATE_BINDING_CHANGED'});assert.equal(e.clients.length,1);await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});}finally{await e.finish();}});
test('CURRENT private PG vault revocation suppresses cached200 without reconnect',async()=>{const e=fixture();try{e.authorize();await e.read();e.vaultRevoked=true;await assert.rejects(e.read(),{code:'SCHEDULER_STATE_CURRENT_REFUSED'});assert.equal(e.clients.length,1);}finally{await e.finish();}});
test('core requires typed private admission, not a boolean, before creating a PG client',async()=>{const e=fixture();const reader=core.createSchedulerStateRead({enabled:true,driver:e.driver,getPrivateCredential:()=>e.credential,admitState:()=>true});try{await assert.rejects(reader.inspect({}, {ownerId:OWNER}),{code:'SCHEDULER_STATE_ADMISSION_REFUSED'});assert.deepEqual(e.calls,[]);assert.deepEqual(e.clients,[]);}finally{await reader.close();await e.finish();}});
test('consent for another connection cannot authorize the native token current connection',async()=>{const e=fixture();try{e.authorize(CID2);await assert.rejects(e.read(),{code:'SCHEDULER_STATE_SEPARATE_CONSENT_REQUIRED'});assert.deepEqual(e.calls,[]);}finally{await e.finish();}});
test('operator uses protected connection-list POST and one explicit authorization, without state read',async()=>{
 const html=renderSchedulerStateOperator({csrf:'</script><script>bad</script>',connections:[{id:CID,label:'secret-not-rendered'}]});
 assert.ok(!html.includes('</script><script>bad'));assert.ok(!html.includes('secret-not-rendered'));assert.ok(html.includes('/auth/scheduler-state.js'));assert.equal((html.match(/<button/g)||[]).length,1);
 const calls=[],elements={'scheduler-state-authorization':{addEventListener:(event,f)=>{elements.submit=f;}},authorize:{disabled:false},result:{textContent:''},'scheduler-state-data':{textContent:JSON.stringify({csrf:'fixture-csrf'})},connection:{value:CID,replaceChildren(){this.value='';},append(option){if(!this.value)this.value=option.value;}}};
 vm.runInNewContext(SCHEDULER_STATE_JS,{document:{getElementById:id=>elements[id],createElement:()=>({})},fetch:async(path,options)=>{calls.push({path,options});return {status:200,json:async()=>({connections:[{id:CID,revoked:false,scopes:['crm.read'],brands:['fish','aristo']}]})};}});
 await new Promise(setImmediate);assert.equal(calls.length,1);assert.equal(calls[0].path,'/auth/native-connections');assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].options.headers['X-CSRF-Token'],'fixture-csrf');assert.deepEqual(JSON.parse(calls[0].options.body),{action:'list'});assert.equal(elements.authorize.disabled,false);
 await elements.submit({preventDefault(){}});await elements.submit({preventDefault(){}});assert.equal(calls.length,2);assert.equal(calls[1].path,'/auth/scheduler-state-settings');assert.equal(calls[1].options.method,'POST');assert.deepEqual(JSON.parse(calls[1].options.body),{action:'authorize',connectionId:CID,consent:true});assert.doesNotMatch(SCHEDULER_STATE_JS,/scheduler-state-receipt|api\/scheduler-state|setInterval|setTimeout/);
});
