'use strict';
const fs=require('node:fs'),path=require('node:path'),G=require('./gate.cjs'),pins=require('./pins.json');
const flags={sourceOnly:true,productionInstalled:false,operational:false,nativeNetworkAckProof:false,productionDurabilityProved:false};
const refuse=()=>{throw Error('ORGANIC_LINKS_PG17_REFUSED');};
async function metadata(c){const v=await c.query('SHOW server_version_num');if(v?.command!=='SHOW'||v.rowCount!==null||v.rows?.length!==1||typeof v.rows[0].server_version_num!=='string'||!/^17[0-9]{4}$/.test(v.rows[0].server_version_num))refuse();const r=await c.query('SELECT current_database() AS database_name, pg_backend_pid() AS backend_pid');if(r?.command!=='SELECT'||r.rowCount!==1||r.rows?.length!==1||r.rows[0].database_name!=='crm_borrowed_source_test'||!Number.isSafeInteger(r.rows[0].backend_pid)||r.rows[0].backend_pid!==c.processID)refuse();return {engine:v.rows[0].server_version_num,pid:r.rows[0].backend_pid};}
function resultsOK(results){if(!Array.isArray(results)||results.length!==21)refuse();const seen=new Set();for(const r of results){if(!r||r.ok!==true||typeof r.name!=='string'||!pins.expectedResults.includes(r.name)||seen.has(r.name)||Object.keys(r).some(k=>!['name','ok'].includes(k)))refuse();seen.add(r.name);}return true;}
// This injectable lifecycle surface NEVER emits native proof. Only this file's
// CLI, with fixed verified real driver/config and complete cleanup, may attest it.
async function runOwned({makeClient,schema,loadRunner}){const clients=[],idle=new WeakMap();let engine=null,pids=[],created=0,endCalls=0,closed=0,executed=false,code='ORGANIC_LINKS_PG17_REFUSED',errored=false,held=false;try{
 for(let n=0;n<2;n++){const c=makeClient();if(clients.includes(c))refuse();clients.push(c);created++;c.connection.on('readyForQuery',m=>idle.set(c,m.status));c.on('error',()=>{errored=true;});}
 const connected=await Promise.allSettled(clients.map(c=>c.connect()));if(connected.some(r=>r.status!=='fulfilled'))refuse();const original=await Promise.all(clients.map(metadata));if(original[0].engine!==original[1].engine||original[0].pid===original[1].pid||errored||clients.some(c=>idle.get(c)!=='I'))refuse();engine=original[0].engine;pids=original.map(r=>r.pid);
 // Own both raw dedicated clients exclusively for the full runner invocation.
 // No query proxy/pool/lease substitution. Original runner retains test hooks.
 held=true;await clients[0].query('CREATE SCHEMA dashboard_crm_controls');await clients[0].query(schema);if(errored||clients.some(c=>idle.get(c)!=='I'))refuse();
 const {runAll,normalizer}=loadRunner();if(typeof runAll!=='function'||normalizer?.version!=='1.0.2-proposed')refuse();const result=await runAll({clientA:clients[0],clientB:clients[1],normalizer});resultsOK(result);if(!held||errored||clients.some(c=>idle.get(c)!=='I'))refuse();const final=await Promise.all(clients.map(metadata));if(final.some((r,n)=>r.engine!==original[n].engine||r.pid!==original[n].pid)||errored)refuse();executed=true;code='ORGANIC_LINKS_PG17_SCENARIOS_PASSED';
 }catch{executed=false;}
 finally{held=false;for(const c of clients){endCalls++;try{await c.end();closed++;}catch{executed=false;code='ORGANIC_LINKS_PG17_CLEANUP_REFUSED';}}if(errored){executed=false;code='ORGANIC_LINKS_PG17_REFUSED';}}
 return Object.freeze({code,executed,engine,pids,scenarios:executed?21:0,runtime:process.version,created,endCalls,closed,fixtureScope:'injected-lifecycle-only',nativePG17Proof:false,...flags});}
async function execute(){let observed;try{
 if(process.env.ORGANIC_LINKS_PG17_CI!=='1'||process.env.GITHUB_ACTIONS!=='true'||process.version!=='v22.23.3')refuse();const root=process.cwd();G.verify({sourceRoot:root,requireOverlay:true});const runnerTemp=process.env.RUNNER_TEMP,modulePath=process.env.BORROWED_PG_MODULE;G.physical(runnerTemp);G.physical(modulePath);if(!modulePath.startsWith(runnerTemp+path.sep)||!modulePath.endsWith('/node_modules/pg'))refuse();const packagePath=path.join(modulePath,'package.json');G.physical(packagePath,true);if(JSON.parse(fs.readFileSync(packagePath,'utf8')).version!=='8.13.1')refuse();const pg=require(modulePath);if(typeof pg.Client!=='function')refuse();const schema=G.check(root,pins.files.find(p=>p.repoPath.endsWith('/schema-v1.sql'))).toString('utf8');
 const result=observed=await runOwned({makeClient:()=>new pg.Client({host:'127.0.0.1',port:5432,user:'crm_test',password:'crm_test_only',database:'crm_borrowed_source_test',connectionTimeoutMillis:5000,query_timeout:5000,statement_timeout:5000}),schema,loadRunner:()=>{G.verify({sourceRoot:root,requireOverlay:true});const normalizer=require(path.join(root,pins.normalizer.repoPath)),{runAll}=require(path.join(root,'tests/organic-links-persistence/pg17-runner.cjs'));return {runAll,normalizer};}});G.verify({sourceRoot:root,requireOverlay:true});return result;
 }catch{return Object.freeze({code:'ORGANIC_LINKS_PG17_REFUSED',executed:false,engine:null,scenarios:0,runtime:process.version,created:observed?.created||0,endCalls:observed?.endCalls||0,closed:observed?.closed||0,nativePG17Proof:false,...flags});}}
module.exports=Object.freeze({execute,runOwned,resultsOK});
if(require.main===module)execute().then(r=>{const proof=r.executed===true&&r.created===2&&r.endCalls===2&&r.closed===2&&/^17[0-9]{4}$/.test(r.engine)&&r.pids.length===2&&r.pids[0]!==r.pids[1];console.log(JSON.stringify({...r,fixtureScope:'Root-isolated-raw-PG17',nativePG17Proof:proof}));if(!proof)process.exitCode=1;},()=>{console.error('ORGANIC_LINKS_PG17_REFUSED');process.exitCode=1;});
