'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const A=require('./activation.cjs');
const path=require('node:path');
const BASE=path.resolve(__dirname,'../..');
const F=require(BASE+'/tests/crm-manager-provision-postgres.test.cjs');
// PGlite is loaded only by author lab tests, not by the native hook.
function verifier(){const salt=Buffer.alloc(16,7),key=crypto.pbkdf2Sync('synthetic-activation-password-only',salt,4096,32,'sha256'),client=crypto.createHmac('sha256',key).update('Client Key').digest(),stored=crypto.createHash('sha256').update(client).digest(),server=crypto.createHmac('sha256',key).update('Server Key').digest();return `SCRAM-SHA-256$4096:${salt.toString('base64')}$${stored.toString('base64')}:${server.toString('base64')}`;}
function model(phase){return{profileSha256:A.PROFILE,objects:{context_verified:true,...A.COUNTS,...(phase==='empty'?{}:{no_login_roles:phase==='disabled'?2:1,restricted_roles:phase==='disabled'?2:1,passworded_roles:1})},state:{issuerRows:phase==='empty'?0:1,issuerMatches:phase!=='empty',issuerActive:phase==='active',subjects:0,operations:0,generations:0,liveKeys:0,serviceScram:phase!=='empty',ownerPasswordAbsent:true,serviceSessions:0,serviceLogin:['staged','active'].includes(phase),ownerNoLogin:true,serviceRestricted:true,ownerRestricted:true}};}
const refused=e=>e.message==='READ_ACTIVATION_REVIEW_REFUSED'&&!e.cause;
function component(p){const [_,rest]=p.mutating.text.split('/* MUTATION START */'),[body]=rest.split('/* MUTATION END */');return `DO $synthetic_component$ DECLARE observed jsonb;secret text;changed integer; BEGIN observed:=current_setting('synthetic.observed')::jsonb; ${body} END $synthetic_component$;`;}
async function lab(t){const {PGlite}=require('@electric-sql/pglite');const f=await F.createFixture(t,{PGlite});await f.db.exec("DELETE FROM public.shrigma_crm_manager_issuer_v1; CREATE ROLE crm_manager_function_owner_v1 NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS; CREATE ROLE crm_manager_provisioner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 2;");return f;}
async function scope(db){await db.query(A.buildPlan('stage').scopeQuery.text,[A.SPEC.issuerId,A.SPEC.namespaceId]);}
async function state(db){return(await db.query(A.STATE_SQL)).rows[0].state;}
async function componentRun(db,p){await db.query("SELECT set_config('synthetic.observed',$1,true)",[JSON.stringify(await state(db))]);try{await db.exec(component(p));}catch{throw Error('SYNTHETIC_COMPONENT_REFUSED');}}
// Future native invocation only: caller provides the *already guarded* fixture
// from tools/crm-manager-install-review/native-fixture.cjs. No env/socket here.
async function proveNativeActivation(t,{db,fixture}){
 try{
  const baseline=await fixture.legacySnapshot(db);
  await db.exec(fixture.source('installer.sql'));await fixture.assertInstalled(db);
  async function inspect(phase){const p=A.buildPlan('stage');await db.query(p.commands[0].text);assert.equal((await db.query("SELECT current_setting('transaction_timeout') AS timeout")).rows[0].timeout,'500ms');await db.exec(p.readOnlyBegin.text);try{await db.query(p.scopeQuery.text,p.scopeQuery.values);const results=await db.exec(p.readback.text),rows=fixture.flattenRows(results);assert.equal(rows.length,3);return A.admitSnapshot({profileSha256:rows[0].profile_sha256,objects:rows[1],state:rows[2].state},phase);}finally{await db.exec('ROLLBACK');}}
  async function execute(p){for(const q of p.commands)await db.query(q.text,q.values);if(p.requiresSecret){const q=p.passwordQuery(verifier());assert.deepEqual((await db.query(q.text,q.values)).rows,[{accepted:true}]);}await db.exec(p.mutating.text);await db.exec(p.commit.text);return inspect(p.after);}
  await t.test('native17 exact installed4f preflight; stage inactive issuer and own SCRAM in budget500',async()=>{assert.equal((await inspect('empty')).phase,'empty');assert.equal((await execute(A.buildPlan('stage'))).phase,'staged');});
  await t.test('native17 exact activate; STATUS through restricted role writes no keys',async()=>{
   assert.equal((await execute(A.buildPlan('activate'))).phase,'active');await db.exec('SET SESSION AUTHORIZATION crm_manager_provisioner');
   try{const request={schema:'crm-manager-provision-request-v1',issuerId:A.SPEC.issuerId,namespaceId:A.SPEC.namespaceId,action:'status',operationId:'33333333-1234-4234-8234-123456789abc',expectedRequestSha256:'0'.repeat(64)},body=(await db.query('SELECT public.shrigma_crm_manager_status_v1($1::jsonb) AS body',[F.canonical(request)])).rows[0].body;assert.equal(body.found,false);assert.equal(body.schema,'crm-manager-provision-status-v1');await assert.rejects(db.query('SELECT * FROM public.shrigma_crm_manager_issuer_v1'),e=>e.code==='42501');}finally{await db.exec('SET SESSION AUTHORIZATION postgres');}
  });
  await t.test('native17 exact disable preserves issuer and catalog; owner neverLOGIN; no DROP',async()=>{assert.equal((await execute(A.buildPlan('disable',{fromPhase:'active'}))).phase,'disabled');assert.deepEqual(await fixture.legacySnapshot(db),baseline);assert.equal((await db.query('SELECT count(*)::int AS n FROM public.shrigma_crm_manager_issuer_v1')).rows[0].n,1);});
 }catch{try{await db.exec('ROLLBACK');}catch{}throw Error('NATIVE_READ_ACTIVATION_PROOF_FAILED');}
}

if(require.main===module){
 test('public source pins are fixed, changed body refused before a plan',()=>{assert.doesNotThrow(()=>A.validateSources());const s={...require('./sources.cjs'),profile:require('./sources.cjs').profile+' '};assert.throws(()=>A.buildPlan('stage',{sources:s}),refused);});
 test('closed phase/options cannot retarget role/issuer/domain or activate implicitly',()=>{for(const [verb,opt]of [['writer',{}],['stage',{issuerId:'other'}],['stage',{fromPhase:'active'}],['disable',{}],['disable',{fromPhase:'disabled'}]])assert.throws(()=>A.buildPlan(verb,opt),refused);assert.equal(A.buildPlan('stage').after,'staged');assert.equal(A.buildPlan('activate').requiresSecret,false);assert.deepEqual(A.SPEC.allowedEmailDomain,'oaristocrata.com');});
 test('SCRAM binding is canonical and descriptors/proofs never enumerate verifier',()=>{const v=verifier(),q=A.passwordQuery(v);assert.deepEqual(q.values,[v]);assert.equal(JSON.stringify(q).includes(v),false);assert.equal(JSON.stringify(A.buildPlan('stage')).includes(v),false);assert.ok(!q.text.includes(v));for(const bad of ['plaintext',v.replace('4096','1'),v+' ',v.replace('==','='),v.replace('SCRAM-SHA-256','md5')])assert.throws(()=>A.passwordQuery(bad),refused);});
 test('same-transaction context/core/empty/ACL/membership/log guards precede the sole mutation',()=>{const p=A.buildPlan('stage'),text=p.commands.map(q=>q.text).join('\n');assert.match(text,/transaction_timeout='500ms'/);assert.match(text,/SERIALIZABLE/);assert.match(text,/SHARE ROW EXCLUSIVE MODE NOWAIT/);assert.match(text,/pg_try_advisory_xact_lock/);assert.match(text,/4f5b8bdec729/);assert.match(text,/membership_edges/);assert.match(text,/issuerRows.*'0'/s);assert.match(text,/log_error_verbosity.*terse/s);assert.match(p.mutating.text,/ALTER ROLE crm_manager_provisioner LOGIN PASSWORD %L/);assert.doesNotMatch(text,/ALTER ROLE/);assert.doesNotMatch(p.mutating.text,/GRANT |REVOKE |DROP |ALTER SYSTEM|pg_hba|edit_content/);});
 test('admission accepts four distinct closed states; active is issuer admission, not user ready',()=>{for(const phase of ['empty','staged','active','disabled']){const p=A.admitSnapshot(model(phase),phase);assert.equal(p.phase,phase);assert.equal(p.publicResidueAccepted,false);assert.ok(Object.isFrozen(p.counts));assert.equal(Object.hasOwn(p,'ready'),false);}});
 test('admission refuses changed core, context/counts and rows before activation',()=>{for(const mutate of [x=>x.profileSha256='0'.repeat(64),x=>x.objects.context_verified=false,x=>x.objects.functions=8,x=>x.objects.membership_edges=1,x=>x.objects.passworded_roles=1,x=>x.state.subjects=1,x=>x.state.issuerRows=1,x=>x.state.ownerPasswordAbsent=false,x=>x.secret='CANARY_NOT_OUTPUT']){const x=model('empty');mutate(x);assert.throws(()=>A.admitSnapshot(x,'empty'),refused);}});
 test('LOGIN aggregate counts cannot hide service privilege drift or ownerLOGIN',()=>{for(const field of ['ownerNoLogin','ownerRestricted','serviceRestricted']){const x=model('active');x.state[field]=false;assert.throws(()=>A.admitSnapshot(x,'active'),refused);}const x=model('active');x.state.serviceLogin=false;assert.throws(()=>A.admitSnapshot(x,'active'),refused);});
 test('disabled admission preserves historical counts but refuses live controlled keys/sessions',()=>{const x=model('disabled');Object.assign(x.state,{subjects:1,operations:5,generations:2});assert.equal(A.admitSnapshot(x,'disabled').counts.operations,5);for(const field of ['liveKeys','serviceSessions']){const y=structuredClone(x);y.state[field]=1;assert.throws(()=>A.admitSnapshot(y,'disabled'),refused);}});
 test('policy observation is closed categories and vector does not silently become allowed',()=>{const q=A.POLICY_QUERY.text;assert.match(q,/'vectorPresent'/);assert.match(q,/'auditPresent'/);assert.match(q,/'unknownExtensionsPresent'/);assert.match(q,/'extensionPolicySupported'/);assert.doesNotMatch(q,/jsonb_agg|rolpassword|'extversion'|'version'/);assert.match(A.buildPlan('stage').commands.at(-1).text,/extname='pgcrypto' AND extversion='1.3'/);});
 test('policy parser reports precise refusal without raw settings or extension rows',()=>{const v={schema:'crm-manager-read-activation-policy-v1',loggingVerified:true,preloadAbsent:true,pgcryptoPresent:false,pgcryptoVersionSupported:true,vectorPresent:false,auditPresent:false,unknownExtensionsPresent:false,extensionPolicySupported:true};assert.equal(A.admitPolicy(v).phase,'supported');assert.equal(A.admitPolicy({...v,pgcryptoPresent:true}).phase,'supported');assert.equal(A.admitPolicy({...v,pgcryptoPresent:true,pgcryptoVersionSupported:false,extensionPolicySupported:false}).phase,'refused_extension_review');for(const [change,phase] of [[{loggingVerified:false},'refused_logging'],[{preloadAbsent:false},'refused_observer'],[{auditPresent:true},'refused_observer'],[{vectorPresent:true,extensionPolicySupported:false},'refused_extension_review'],[{unknownExtensionsPresent:true},'refused_extension_review']])assert.equal(A.admitPolicy({...v,...change}).phase,phase);assert.throws(()=>A.admitPolicy({...v,password:'NOT_OUTPUT'}),refused);});
 test('PGlite full production guard rejects divergent context before secret binding or mutation',async t=>{const f=await lab(t),p=A.buildPlan('stage');await f.db.exec('BEGIN');try{await scope(f.db);await assert.rejects(f.db.exec(p.commands.at(-1).text));}finally{await f.db.exec('ROLLBACK');}assert.equal((await f.db.query('SELECT count(*)::int AS n FROM public.shrigma_crm_manager_issuer_v1')).rows[0].n,0);assert.equal((await f.db.query("SELECT rolcanlogin AS login FROM pg_roles WHERE rolname='crm_manager_provisioner'")).rows[0].login,false);await f.unchanged();});
 test('PGlite parses exact catalog readback and refuses its divergent profile/context',async t=>{const f=await lab(t),p=A.buildPlan('stage');await f.db.exec('BEGIN');try{await scope(f.db);const r=await f.db.exec(p.readback.text),rows=r.flatMap(x=>x.rows||[]);assert.equal(rows.length,3);assert.match(rows[0].profile_sha256,/^[a-f0-9]{64}$/);assert.equal(rows[1].context_verified,false);assert.throws(()=>A.admitSnapshot({profileSha256:rows[0].profile_sha256,objects:rows[1],state:rows[2].state},'empty'),refused);const fragment=p.commands.at(-1).text.slice(p.commands.at(-1).text.indexOf('SELECT profile_sha256 INTO core'));await f.db.exec('SAVEPOINT catalog_guard');await assert.rejects(f.db.exec('DO $read_activation$ DECLARE core text;objects jsonb;observed jsonb; BEGIN '+fragment));await f.db.exec('ROLLBACK TO SAVEPOINT catalog_guard');assert.equal((await state(f.db)).issuerRows,0);await f.unchanged();}finally{await f.db.exec('ROLLBACK');}});
 test('PGlite isolated mutation SQL: stage inactive, explicit activate, restricted STATUS, preserved admin',async t=>{const f=await lab(t);await f.db.exec('BEGIN');try{await scope(f.db);const p=A.buildPlan('stage'),q=p.passwordQuery(verifier());await f.db.query(q.text,q.values);await componentRun(f.db,p);let s=await state(f.db);assert.equal(s.issuerActive,false);assert.equal(s.serviceLogin,true);assert.equal(s.serviceScram,true);assert.equal(s.ownerNoLogin,true);await componentRun(f.db,A.buildPlan('activate'));s=await state(f.db);assert.equal(s.issuerActive,true);await f.db.exec("GRANT EXECUTE ON FUNCTION public.shrigma_crm_manager_status_v1(jsonb) TO crm_manager_provisioner; SET SESSION AUTHORIZATION crm_manager_provisioner");try{const req={schema:'crm-manager-provision-request-v1',issuerId:A.SPEC.issuerId,namespaceId:A.SPEC.namespaceId,action:'status',operationId:'33333333-1234-4234-8234-123456789abc',expectedRequestSha256:'0'.repeat(64)},body=(await f.db.query('SELECT public.shrigma_crm_manager_status_v1($1::jsonb) AS body',[F.canonical(req)])).rows[0].body;assert.equal(body.found,false);}finally{await f.db.exec('SET SESSION AUTHORIZATION postgres');}await f.unchanged();}finally{await f.db.exec('ROLLBACK');}});
 test('PGlite disable component refuses unreconciled live key and preserves historic receipts',async t=>{const f=await lab(t);await f.db.exec('BEGIN');try{await scope(f.db);const q=A.passwordQuery(verifier());await f.db.query(q.text,q.values);await componentRun(f.db,A.buildPlan('stage'));await componentRun(f.db,A.buildPlan('activate'));await f.db.exec('GRANT EXECUTE ON FUNCTION public.shrigma_crm_manager_prepare_v1(jsonb),public.shrigma_crm_manager_revoke_v1(jsonb) TO crm_manager_provisioner');const req=F.createPrepare({issuerId:A.SPEC.issuerId,namespaceId:A.SPEC.namespaceId,owner:'pilot@oaristocrata.com'});async function rpc(name,input){await f.db.exec('SET SESSION AUTHORIZATION crm_manager_provisioner');try{return(await f.db.query('SELECT public.shrigma_crm_manager_'+name+'_v1($1::jsonb) AS body',[F.canonical(input)])).rows[0].body;}finally{await f.db.exec('SET SESSION AUTHORIZATION postgres');}}assert.equal((await rpc('prepare',req)).state,'prepared');assert.equal((await state(f.db)).liveKeys,1);await f.db.exec('SAVEPOINT before_disable');await assert.rejects(componentRun(f.db,A.buildPlan('disable',{fromPhase:'active'})),e=>e.message==='SYNTHETIC_COMPONENT_REFUSED');await f.db.exec('ROLLBACK TO SAVEPOINT before_disable');assert.equal((await state(f.db)).issuerActive,true);assert.equal((await state(f.db)).serviceLogin,true);assert.equal((await f.key(req)).ativo,true);assert.equal((await rpc('revoke',F.createRevoke(req))).state,'revoked');assert.equal((await state(f.db)).liveKeys,0);const before=(await f.db.query('SELECT * FROM public.shrigma_crm_manager_operation_v1')).rows;await componentRun(f.db,A.buildPlan('disable',{fromPhase:'active'}));const s=await state(f.db);assert.equal(s.serviceLogin,false);assert.equal(s.issuerActive,false);assert.equal(s.ownerNoLogin,true);assert.deepEqual((await f.db.query('SELECT * FROM public.shrigma_crm_manager_operation_v1')).rows,before);await f.unchanged();}finally{await f.db.exec('ROLLBACK');}});
}
module.exports=Object.freeze({proveNativeActivation});
