 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path'),fs=require('node:fs'),vm=require('node:vm'),{DatabaseSync}=require('node:sqlite'),{Readable}=require('node:stream');
const runtime=process.env.SOURCE_SYNC_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational'),D=require(path.join(runtime,'native-source-sync.cjs')),O=require(path.join(runtime,'native-source-operator.cjs'));
const id='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444',third='55555555-5555-4555-8555-555555555555',key='SyntheticOnly.SourceKey.1234567890123456',time=Date.parse('2026-10-07T15:00:00.000Z'),ctx={csrf:'fixture',original:true};
function fixture(opts={}){
 const db=opts.db||new DatabaseSync(':memory:');if(!opts.db)db.exec("PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);INSERT INTO users VALUES('master'),('other');");
 const enc=Buffer.alloc(32,7),mac=x=>crypto.createHmac('sha256',enc).update(x).digest('hex');
 const encrypt=x=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',enc,iv),b=Buffer.concat([c.update(x,'utf8'),c.final()]);return ['v1',iv.toString('base64url'),c.getAuthTag().toString('base64url'),b.toString('base64url')].join('.');};
 const decrypt=x=>{const[v,i,t,b]=x.split('.');assert.equal(v,'v1');const c=crypto.createDecipheriv('aes-256-gcm',enc,Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([c.update(Buffer.from(b,'base64url')),c.final()]).toString('utf8');};
 const state=opts.state||{revision:'a'.repeat(64),binding:'b'.repeat(64),active:true,scope:true,brands:['fish','aristo']},calls=opts.calls||[],operations=opts.operations||new Map();let source;
 function identity(owner){return {role:'superadmin',active:state.active,revision:state.revision};}
 function consent(c){if(!c?.original||c.csrf!=='fixture'||c.nativeBearer!==undefined)throw Error('denied secret');return {userId:'master',sessionHash:'c'.repeat(64)};}
 function authorize(c,{brand,write}){if(!state.scope||!state.brands.includes(brand)||c?.owner==='other')throw Error('unauthorized secret');return {ownerId:'master',ownerRevision:state.revision,binding:state.binding};}
 const response=(status,b)=>({status,revision:D.REVISION,body:b});
 function original(x,full=false){const value={operation_id:'66666666-6666-4666-8666-666666666666',idempotency_key:x.idempotency_key,brand:x.brand,state:'claimed',query_sha256:D.QUERY,bulk_operation_id:null,next_chunk:0,chunks:null,error_code:null};return full?{...value,kind:'run',scheduled_for:x.scheduled_for,source_sha256:null,last_chunk:null,last_chunk_sha256:null,last_receipt:null}:value;}
 async function transport(q){calls.push(q);assert(Object.keys(q).every(k=>['method','path','body','bearer'].includes(k)));assert(q.path==='/healthz'||q.path==='/v1/run'||q.path.startsWith('/v1/operations/'));if(opts.hook)await opts.hook(q,source,state);if(opts.fail)throw Error(key);if(q.path==='/healthz')return response(200,{service:'crm-shopify-sync',enabled:true,revision:opts.healthRevision||D.REVISION,product_semantics:'v2',stopping:false});assert.equal(typeof q.bearer,'string');if(opts.unauthorized||q.bearer!==(state.serviceKey||key))return response(401,{error:'UNAUTHORIZED'});if(q.method==='POST'){const x=q.body;operations.set(x.idempotency_key,x);if(opts.lost)throw Error(key);const b=original(x);if(opts.postBad)b.brand='aristo'===x.brand?'fish':'aristo';return response(opts.http503?503:202,opts.http503?{error:'SYNC_UNAVAILABLE'}:b);}const x=operations.get(q.path.slice('/v1/operations/'.length));if(!x)return response(503,{error:'SYNC_UNAVAILABLE'});const b=original(x,true);if(opts.completed){b.state='completed';b.bulk_operation_id='gid://shopify/BulkOperation/123';b.chunks=1;b.next_chunk=1;b.source_sha256='d'.repeat(64);b.last_receipt={status:'ready',customers:key};}if(opts.getBad)b.scheduled_for='2026-10-07T14:00:00.000Z';if(opts.large)return {...response(200,b),body:{oversized:'x'.repeat(32769)}};if(opts.redirect)return {...response(200,b),status:302,headers:{'X-CRM-Shopify-Sync-Revision':D.REVISION,Location:'https://invalid'}};return response(200,b);}
 const args={enabled:true,db,consent,identity,authorize,encrypt,decrypt,mac,transport,now:()=>time,uuid:()=>crypto.randomUUID(),timeoutMs:opts.timeoutMs||1000,permitDelegation:(c,connectionId)=>{consent(c);return {connection:{id:connectionId,scopes:['crm.source-sync']}};}};
 source=D.createSourceSync(args);if(!opts.db)source.bind({context:ctx,bearer:key,brands:opts.bindBrands||['fish','aristo'],privateNetwork:true});return {source,args,db,state,calls,operations,response,opts};
}

const correctedKey='SyntheticOnly.CorrectedServiceKey.1234567890';
const postCount=f=>f.calls.filter(q=>q.method==='POST').length;
const data=f=>JSON.parse(f.db.prepare('SELECT data FROM crm_native_source_attempt_v1 WHERE request_id=?').get(id).data);
function rebind(f,brand='fish',bearer=key){f.source.bind({context:ctx,bearer,brands:[brand],privateNetwork:true});}
test('uncertain survives credential epoch; new intent denied and original duplicate GET only',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});const before=data(f);rebind(f);await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});f.opts.lost=false;const r=await f.source.run({context:ctx,brand:'fish',requestId:id});assert.equal(r.attempt,'confirmed');assert.equal(postCount(f),1);const after=data(f);for(const k of ['ownerId','brand','ownerRevision','binding','credentialRevision','credentialSeal','privatePayload','createdAt'])assert.equal(after[k],before[k]);assert.equal(f.source.list(ctx).attempts[0].requestId,id);});
test('actual key change reads original payload with current key; uncertainty still blocks',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});const original=f.calls.find(q=>q.method==='POST').body;rebind(f,'fish',correctedKey);f.state.serviceKey=correctedKey;await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});await f.source.inspect({context:ctx,brand:'fish',requestId:id});const get=f.calls.filter(q=>q.path.startsWith('/v1/operations/')).at(-1);assert.equal(get.bearer,correctedKey);assert.equal(get.path,'/v1/operations/'+original.idempotency_key);assert.equal(postCount(f),1);});
test('reauthorization epoch never erases pending owner-brand history',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'aristo',requestId:id});f.state.binding='e'.repeat(64);await assert.rejects(f.source.run({context:ctx,brand:'aristo',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(f.source.list(ctx).attempts.length,1);await f.source.inspect({context:ctx,brand:'aristo',requestId:id});assert.equal(postCount(f),1);});
test('new owner revision and fresh consent retain old custody without using old grants',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});const before=data(f);f.state.revision='e'.repeat(64);await assert.rejects(f.source.inspect({context:ctx,brand:'fish',requestId:id}));rebind(f);assert.equal(f.source.list(ctx).attempts.length,1);await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});await f.source.inspect({context:ctx,brand:'fish',requestId:id});assert.equal(data(f).ownerRevision,before.ownerRevision);});
test('revoke without current live link refuses historical GET/list before transport',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});f.source.revoke(ctx);const n=f.calls.length;await assert.rejects(f.source.inspect({context:ctx,brand:'fish',requestId:id}));assert.throws(()=>f.source.list(ctx));assert.equal(f.calls.length,n);});
test('historical custody cannot cross owner or brand',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});rebind(f);const n=f.calls.length;await assert.rejects(f.source.inspect({context:ctx,brand:'aristo',requestId:id}));const otherOwner=D.createSourceSync({...f.args,consent:()=>({userId:'other',sessionHash:'c'.repeat(64)}),authorize:()=>({ownerId:'other',ownerRevision:f.state.revision,binding:f.state.binding})});otherOwner.bind({context:ctx,bearer:key,brands:['fish'],privateNetwork:true});await assert.rejects(otherOwner.inspect({context:ctx,brand:'fish',requestId:id}),{code:'SOURCE_ATTEMPT_DENIED'});assert.equal(otherOwner.list(ctx).attempts.length,0);assert.equal(f.calls.length,n);});
test('original completed persists across key epoch and later GET401; terminal may permit new',async()=>{const f=fixture({completed:true});await f.source.run({context:ctx,brand:'fish',requestId:id});await f.source.inspect({context:ctx,brand:'fish',requestId:id});rebind(f,'fish',correctedKey);f.state.serviceKey=correctedKey;f.opts.unauthorized=true;await f.source.inspect({context:ctx,brand:'fish',requestId:id});assert.equal(data(f).result.state,'completed');assert.equal(data(f).postRefusal,null);f.opts.unauthorized=false;await f.source.run({context:ctx,brand:'fish',requestId:other});assert.equal(postCount(f),2);});
test('only attested original POST401 seals preclaim refusal; actual corrected key permits new explicit intent',async()=>{const f=fixture();f.state.serviceKey=correctedKey;const r=await f.source.run({context:ctx,brand:'fish',requestId:id});assert.equal(r.attempt,'key_refused');assert.equal(data(f).postRefusal.schema,'crm-original-source-post401-v1');assert(!JSON.stringify(r).includes('credentialMac'));rebind(f,'fish',correctedKey);assert(f.source.status(ctx).newIntentBrands.includes('fish'));assert.equal(f.source.list(ctx).attempts[0].requestId,id);await f.source.run({context:ctx,brand:'fish',requestId:other});assert.equal(postCount(f),2);});
test('grant epoch or same key re-encryption cannot reinterpret POST refusal as key correction',async()=>{const f=fixture();f.state.serviceKey=correctedKey;await f.source.run({context:ctx,brand:'fish',requestId:id});f.state.binding='e'.repeat(64);rebind(f);assert.deepEqual(f.source.status(ctx).newIntentBrands,[]);await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(postCount(f),1);});
test('GET401 without operation result is not a definitive POST rejection',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});f.opts.unauthorized=true;await f.source.inspect({context:ctx,brand:'fish',requestId:id});assert.equal(data(f).phase,'key_refused');assert.equal(data(f).result,null);assert.equal(data(f).postRefusal,null);rebind(f,'fish',correctedKey);f.state.serviceKey=correctedKey;f.opts.unauthorized=false;await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(postCount(f),1);});
test('legacy v1 key_refused row without marker remains pending after correction',async()=>{const f=fixture({unauthorized:true});await f.source.run({context:ctx,brand:'fish',requestId:id});const a=data(f);delete a.postRefusal;const dataText=D.canonical(a),seal=f.args.mac('attempt:'+dataText);f.db.prepare('UPDATE crm_native_source_attempt_v1 SET data=?,seal=? WHERE request_id=?').run(dataText,seal,id);rebind(f,'fish',correctedKey);await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(f.source.list(ctx).attempts.length,1);});
for(const change of ['revoke','binding','identity'])test('current reauth after rebound GET '+change+' rejects emission',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});rebind(f);f.opts.hook=async(q,source,state)=>{if(q.path.startsWith('/v1/operations/')){if(change==='revoke')source.revoke(ctx);if(change==='binding')state.binding='e'.repeat(64);if(change==='identity')state.revision='e'.repeat(64);}};await assert.rejects(f.source.inspect({context:ctx,brand:'fish',requestId:id}));assert.equal(postCount(f),1);});
test('different original operationId after rebind never overwrites custody',async()=>{const f=fixture();await f.source.run({context:ctx,brand:'fish',requestId:id});const original=data(f).result.operationId,transport=f.args.transport;rebind(f);const source=D.createSourceSync({...f.args,transport:async q=>{const r=await transport(q);if(q.path.startsWith('/v1/operations/'))r.body.operation_id=other;return r;}});assert.equal((await source.inspect({context:ctx,brand:'fish',requestId:id})).attempt,'uncertain');assert.equal(data(f).result.operationId,original);});
test('journal tampering and fabricated marker rejected under new binding',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});rebind(f);f.db.prepare("UPDATE crm_native_source_attempt_v1 SET data=replace(data,'null','true')").run();await assert.rejects(f.source.inspect({context:ctx,brand:'fish',requestId:id}),{code:'SOURCE_INTEGRITY'});await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_INTEGRITY'});assert.equal(postCount(f),1);});
function ui(latest=[],runResponse,eligibility=['fish']){const elements={};function e(id){return elements[id]||=( {id,disabled:['run','inspect','revoke'].includes(id),value:id==='brand'?'fish':'',textContent:'',options:[],append(x){this.options.push(x);},replaceChildren(){this.options=[];},querySelector(){return this.button||=(e(id+'-button'));},elements:{}} );}const bind=e('bind'),scope=e('scope');for(const k of ['key','fish','aristo','privateNetwork'])bind.elements[k]={value:'',checked:true};scope.elements.connectionId=e('select');scope.elements.connectionId.value=id;scope.elements.agree={checked:true};const calls=[],handlers={},document={getElementById:e,createElement:()=>({}),querySelectorAll:()=>Object.values(elements)};const context={document,window:{addEventListener:(k,fn)=>handlers[k]=fn},crypto:{randomUUID:()=>{calls.push({uuid:true});return other;}},fetch:async(url,options)=>{if(url==='/auth/session')return {json:async()=>({authenticated:true,user:{role:'superadmin'},csrf:'fixture'})};const b=JSON.parse(options.body);calls.push(b);if(b.action==='run'&&runResponse==='lost')throw Error();return {ok:true,json:async()=>b.action==='status'?{source:{linked:true,brands:['fish'],readBrands:['fish'],writeBrands:['fish'],newIntentBrands:eligibility},connections:[{id,label:'Fixture',scopes:[]}]}:b.action==='latest'?{attempts:latest}:b.action==='run'||b.action==='inspect'?{brand:'fish',requestId:id,attempt:b.action==='inspect'?'confirmed':'uncertain',operation:b.action==='inspect'?{state:'completed'}:null}:{}};}};vm.runInNewContext(O.JS,context);return {elements,calls,handlers,bind,scope};}
const flush=()=>new Promise(r=>setImmediate(r));

test('UI pending epoch remains blocked; corrected-key eligibility permits only explicit new intention',async()=>{const pending=ui([{brand:'fish',requestId:id,attempt:'uncertain',operation:null}],undefined,[]);await flush();assert.equal(pending.elements.run.disabled,true);assert.equal(pending.calls.filter(c=>c.action==='run').length,0);const corrected=ui([{brand:'fish',requestId:id,attempt:'key_refused',operation:null}],undefined,['fish']);await flush();assert.equal(corrected.elements.run.disabled,false);assert(corrected.elements.attempt.textContent.includes('usada nesta tentativa'));await corrected.elements.run.onclick();assert.equal(corrected.calls.find(c=>c.action==='run').requestId,other);assert.equal(corrected.calls.filter(c=>c.action==='run').length,1);});
test('GET-only old intent survives a reopened same journal under current credential',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});rebind(f,'fish',correctedKey);f.state.serviceKey=correctedKey;const restarted=D.createSourceSync(f.args);assert.equal(restarted.list(ctx).attempts[0].requestId,id);await restarted.run({context:ctx,brand:'fish',requestId:id});await assert.rejects(restarted.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(postCount(f),1);});
test('key-refusal marker shape is closed even with a test-generated valid seal',async()=>{const f=fixture({lost:true});await f.source.run({context:ctx,brand:'fish',requestId:id});const a=data(f);a.postRefusal={schema:'crm-original-source-post401-v1',revision:'f'.repeat(40),credentialMac:'e'.repeat(64)};const dataText=D.canonical(a);f.db.prepare('UPDATE crm_native_source_attempt_v1 SET data=?,seal=? WHERE request_id=?').run(dataText,f.args.mac('attempt:'+dataText),id);await assert.rejects(f.source.inspect({context:ctx,brand:'fish',requestId:id}),{code:'SOURCE_INTEGRITY'});});


test('unattested POST401 cannot produce the preclaim marker',async()=>{const f=fixture({unauthorized:true}),original=f.args.transport,source=D.createSourceSync({...f.args,transport:async q=>{const r=await original(q);if(q.method==='POST')r.revision='f'.repeat(40);return r;}});await source.run({context:ctx,brand:'fish',requestId:id});assert.equal(data(f).postRefusal,null);rebind(f,'fish',correctedKey);await assert.rejects(source.run({context:ctx,brand:'fish',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});});
test('first corrected-key intent reserves before awaits and blocks another concurrent requestId',async()=>{let release,entered;const started=new Promise(r=>entered=r),hold=new Promise(r=>release=r),f=fixture();f.state.serviceKey=correctedKey;await f.source.run({context:ctx,brand:'fish',requestId:id});rebind(f,'fish',correctedKey);f.opts.hook=async q=>{if(q.method==='POST'){entered();await hold;}};const second=f.source.run({context:ctx,brand:'fish',requestId:other});await started;await assert.rejects(f.source.run({context:ctx,brand:'fish',requestId:third}),{code:'SOURCE_ATTEMPT_PENDING'});release();await second;assert.equal(postCount(f),2);});

test('runtime module pins match epoch, progress and operator UI delivery bytes',()=>{const pins={'native-source-sync.cjs': '043cc6723e081e37f2e5593e004739a28c37ac413ce14b5c759813afb9fc2b49', 'native-source-operator.cjs': '1d7f2f705cd753491c8542890556754c8b6f0dbf3fb6adf773143f14cf76f06f'};for(const [name,hash]of Object.entries(pins))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(runtime,name))).digest('hex'),hash);});
