'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path');
const runtime=process.env.SOURCE_PROGRESS_UI_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational'),O=require(path.join(runtime,'native-source-operator.cjs'));
const id='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444';
const evidence=(op={},attempt='confirmed',brand='aristo')=>({brand,requestId:id,attempt,operation:{operationId:'66666666-6666-4666-8666-666666666666',sourceAuthenticated:true,state:'chunk_uncertain',nextChunk:34,totalChunks:35,lastChunk:34,checkedAt:Date.parse('2026-10-08T18:00:00Z'),...op}});
const flush=()=>new Promise(r=>setImmediate(r));
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{resolve,reject,promise};}
function ui(opts={}){
 const elements={},calls=[],handlers={};let uuids=0;
 function e(id){return elements[id]||=( {id,disabled:['run','inspect','revoke'].includes(id),value:id==='brand'?'aristo':'',textContent:'',options:[],append(x){this.options.push(x);},replaceChildren(){this.options=[];},querySelector(){return this.button||=(e(id+'-button'));},elements:{}} );}
 const bind=e('bind'),scope=e('scope');for(const k of ['key','fish','aristo','privateNetwork'])bind.elements[k]={value:'',checked:true};scope.elements.connectionId=e('select');scope.elements.connectionId.value=id;scope.elements.agree={checked:true};
 const document={getElementById:e,createElement:()=>({}),querySelectorAll:()=>Object.values(elements)};
 const context={document,window:{addEventListener:(name,fn)=>handlers[name]=fn},crypto:{randomUUID:()=>{uuids++;return other;}},setInterval:()=>assert.fail('polling forbidden'),setTimeout:()=>assert.fail('timer forbidden'),fetch:async(url,options)=>{
  if(url==='/auth/session'){calls.push({url,options});return{json:async()=>({authenticated:true,user:{role:'superadmin'},csrf:'fixture-csrf'})};}
  assert.equal(url,O.API);assert.equal(options.method,'POST');assert.equal(options.credentials,'same-origin');assert.equal(options.headers['X-CSRF-Token'],'fixture-csrf');assert.equal(options.redirect,'error');const b=JSON.parse(options.body);calls.push({url,options,...b});
  let value;
  if(b.action==='status')value={source:{linked:true,brands:['fish','aristo'],readBrands:['fish','aristo'],writeBrands:['fish','aristo'],newIntentBrands:opts.eligibility||[]},connections:[{id,label:'Fixture',scopes:['crm.source-sync']}]};
  else if(b.action==='latest')value=opts.latest?await opts.latest(b):{attempts:opts.value?[opts.value]:[]};
  else if(b.action==='inspect')value=opts.inspect?await opts.inspect(b):opts.value;
  else if(b.action==='run')value=opts.run?await opts.run(b):{brand:b.brand,requestId:b.requestId,attempt:'uncertain',operation:null};
  else if(['bind','revoke','authorize-source'].includes(b.action))value={};else assert.fail('new endpoint/action');
  return{ok:true,json:async()=>value};
 }};
 vm.runInNewContext(O.JS,context,{filename:'native-source.js'});
 return{elements,calls,handlers,opts,uuids:()=>uuids,text:()=>['attempt','progress','progress-reading','message'].map(k=>e(k).textContent).join('\n')};
}
async function ready(opts){const f=ui(opts);await flush();return f;}
const inspections=f=>f.calls.filter(c=>c.action==='inspect');
test('HTML includes accessible numeric progress and reading provenance',()=>{assert(O.HTML.includes('id="progress" role="status"'));assert(O.HTML.includes('id="progress-reading"'));new vm.Script(O.JS);});
test('34/35 confirmed, zero-based last attempt35 uncertain and new update stays blocked',async()=>{const f=await ready({value:evidence()});assert(f.elements.progress.textContent.includes('34 de 35 lotes confirmados'));assert(f.elements.progress.textContent.includes('lote 35 incerta'));assert(f.text().includes('exige diagnóstico'));assert(f.text().includes('última leitura confirmada'));assert.equal(f.elements.run.disabled,true);assert.equal(f.elements.inspect.disabled,false);assert(!f.text().includes('conclusão'));assert(!f.text().includes('%'));});
test('equal counts never imply completed',async()=>{const f=await ready({value:evidence({nextChunk:35,totalChunks:35})});assert(f.text().includes('35 de 35'));assert(f.text().includes('incerto'));assert(!f.text().includes('confirmou a conclusão'));assert(f.elements.run.disabled);});
test('only original completed state displays conclusion; no numeric percent shortcut',async()=>{const f=await ready({value:evidence({state:'completed',nextChunk:35}),eligibility:['aristo']});assert(f.text().includes('A fonte confirmou a conclusão'));assert(f.text().includes('35 de 35'));assert(!f.text().includes('%'));assert.equal(f.elements.run.disabled,false);});
for(const op of [null,{state:'claimed',sourceAuthenticated:true},{state:'claimed',sourceAuthenticated:true,nextChunk:null,totalChunks:null,lastChunk:null}])test('legacy/null/absent numeric fields stay unavailable '+JSON.stringify(op),async()=>{const v=evidence();v.operation=op;const f=await ready({value:v});assert.equal(f.elements.progress.textContent,'Progresso indisponível.');assert(!f.text().includes('0 lotes'));assert(!f.text().includes('0 de'));});
test('known count with unknown total remains confirmed count without fabricated denominator',async()=>{const f=await ready({value:evidence({nextChunk:7,totalChunks:null,lastChunk:6,state:'ingesting'})});assert(f.text().includes('7 lotes confirmados; total ainda desconhecido'));assert(f.text().includes('lote 7'));assert(!f.text().includes('de 0'));});
test('confirmed zero from authenticated GET is shown as zero',async()=>{const f=await ready({value:evidence({nextChunk:0,totalChunks:null,lastChunk:null,state:'claimed'})});assert(f.text().includes('0 lotes confirmados'));});
for(const delta of [{nextChunk:-1},{nextChunk:51},{nextChunk:34.5},{nextChunk:'34'},{totalChunks:0},{totalChunks:51},{totalChunks:'35'},{nextChunk:36},{lastChunk:-1},{lastChunk:50},{lastChunk:'34'},{lastChunk:35},{nextChunk:1,lastChunk:2},{sourceAuthenticated:false}])test('invalid numeric/coherence evidence unavailable '+JSON.stringify(delta),async()=>{const f=await ready({value:evidence(delta)});assert.equal(f.elements.progress.textContent,'Progresso indisponível.');assert(!f.text().includes('lotes confirmados'));assert(f.elements.run.disabled);});
test('uncertain response preserves older evidence with explicit provenance',async()=>{const f=await ready({value:evidence({},'uncertain')});assert(f.text().includes('34 de 35'));assert(f.text().includes('não são uma nova confirmação'));assert(f.text().includes('2026-10-08T18:00:00.000Z'));assert(f.elements.run.disabled);});
test('failed inspect preserves prior progress and identifies unconfirmed consultation',async()=>{const f=await ready({value:evidence(),inspect:async()=>{throw Error('raw-secret-error');}});await f.elements.inspect.onclick();assert(f.text().includes('34 de 35'));assert(f.text().includes('Consulta não confirmada'));assert(f.text().includes('não são uma nova confirmação'));assert(!f.text().includes('raw-secret'));assert.equal(inspections(f).length,1);assert(f.elements.run.disabled);});
test('key refused consult preserves prior evidence and cannot be presented as new confirmation',async()=>{const f=await ready({value:evidence({},'key_refused')});assert(f.text().includes('recusou a chave'));assert(f.text().includes('34 de 35'));assert(f.text().includes('não são uma nova confirmação'));assert(f.elements.run.disabled);});
test('confirmed inspect uses same request brand/id and clears failed-reading provenance',async()=>{const f=await ready({value:evidence(),inspect:async()=>{throw Error();}});await f.elements.inspect.onclick();f.opts.inspect=async()=>evidence({nextChunk:35,state:'completed'});await f.elements.inspect.onclick();assert(f.text().includes('confirmou a conclusão'));assert(!f.text().includes('não são uma nova confirmação'));assert.equal(f.elements.message.textContent,'');for(const c of inspections(f))assert.deepEqual({action:c.action,brand:c.brand,requestId:c.requestId},{action:'inspect',brand:'aristo',requestId:id});assert.equal(f.uuids(),0);});
test('brand change clears previous attempt/progress immediately before latest settles',async()=>{const hold=deferred(),f=await ready({value:evidence()});f.opts.latest=b=>b.brand==='fish'?hold.promise:{attempts:[evidence()]};f.elements.brand.value='fish';f.elements.brand.onchange();assert.equal(f.elements.progress.textContent,'');assert.equal(f.elements['progress-reading'].textContent,'');assert(!f.text().includes('34 de 35'));hold.resolve({attempts:[]});await flush();assert.equal(f.elements.progress.textContent,'');});
test('late inspect from prior brand cannot restore old progress',async()=>{const hold=deferred(),f=await ready({value:evidence(),inspect:()=>hold.promise});const pending=f.elements.inspect.onclick();f.elements.brand.value='fish';f.elements.brand.onchange();assert.equal(f.elements.progress.textContent,'');hold.resolve(evidence({nextChunk:35,state:'completed'}));await pending;assert.equal(f.elements.progress.textContent,'');assert(!f.text().includes('conclusão'));assert(f.elements.run.disabled);assert.equal(inspections(f).length,1);});
test('late latest from prior brand ignored even after newer brand response',async()=>{const hold=deferred(),f=await ready({latest:b=>b.brand==='aristo'?hold.promise:Promise.resolve({attempts:[]})});f.elements.brand.value='fish';f.elements.brand.onchange();await flush();hold.resolve({attempts:[evidence()]});await flush();assert.equal(f.elements.progress.textContent,'');assert(!f.text().includes('34 de 35'));});
test('different attempt response cannot overwrite current evidence',async()=>{const f=await ready({value:evidence(),inspect:async()=>({...evidence({nextChunk:35,state:'completed'}),requestId:other})});await f.elements.inspect.onclick();assert(f.text().includes('34 de 35'));assert(!f.text().includes('confirmou a conclusão'));assert(f.text().includes('Consulta não confirmada'));assert.equal(f.uuids(),0);});
test('pagehide clears key/progress/evidence and rejects delayed result',async()=>{const hold=deferred(),f=await ready({value:evidence(),inspect:()=>hold.promise});f.elements.bind.elements.key.value='synthetic-private-input';const pending=f.elements.inspect.onclick();f.handlers.pagehide();assert.equal(f.elements.bind.elements.key.value,'');assert.equal(f.text().trim(),'');hold.resolve(evidence({nextChunk:35,state:'completed'}));await pending;assert.equal(f.text().trim(),'');assert(f.elements.run.disabled);assert(f.elements.inspect.disabled);});
test('no polling, replay, source endpoint or new intent during pending consultations',async()=>{const hold=deferred(),f=await ready({value:evidence(),inspect:()=>hold.promise});const n=f.calls.length;await flush();assert.equal(f.calls.length,n);await f.elements.run.onclick();assert.equal(f.uuids(),0);const pending=f.elements.inspect.onclick();await f.elements.inspect.onclick();assert.equal(inspections(f).length,1);hold.resolve(evidence());await pending;assert(f.calls.every(c=>c.url==='/auth/session'||c.url===O.API));assert(!f.calls.some(c=>['run','recover','restart'].includes(c.action)));});
test('explicit new run clears previous numeric evidence and reserves one intent without replay',async()=>{const hold=deferred(),f=await ready({value:evidence({state:'completed',nextChunk:35}),eligibility:['aristo'],run:()=>hold.promise});const pending=f.elements.run.onclick();assert.equal(f.elements.progress.textContent,'Progresso indisponível.');assert(!f.text().includes('34 de 35'));await f.elements.run.onclick();assert.equal(f.uuids(),1);assert.equal(f.calls.filter(c=>c.action==='run').length,1);hold.reject(Error('uncertain'));await pending;assert(f.text().includes('Resposta incerta'));assert(f.elements.run.disabled);f.opts.inspect=async b=>({brand:b.brand,requestId:b.requestId,attempt:'uncertain',operation:null});await f.elements.inspect.onclick();assert.equal(inspections(f).at(-1).requestId,other);assert.equal(f.uuids(),1);assert.equal(f.calls.filter(c=>c.action==='run').length,1);});
test('progress projection ignores raw private extras and errors without HTML insertion',async()=>{const f=await ready({value:evidence({last_receipt:{customers:'private customers'},idempotency_key:'private-key',bulk_operation_id:'private-bulk',error_code:'PRIVATE_ERROR',source_sha256:'private-hash',raw:'<script>secret</script>'})});for(const secret of ['private','PRIVATE_ERROR','secret','<script>'])assert(!f.text().includes(secret));assert(f.text().includes('34 de 35'));});
