'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path'),{DatabaseSync}=require('node:sqlite');
const runtime=process.env.SOURCE_PROGRESS_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational'),D=require(path.join(runtime,'native-source-sync.cjs'));
// Private fixture mechanics reused from sealed epoch input; no old suite runs.
const id='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444',third='55555555-5555-4555-8555-555555555555',key='SyntheticOnly.SourceKey.1234567890123456',time=Date.parse('2026-10-07T15:00:00.000Z'),ctx={csrf:'fixture',original:true};
function fixture(opts={}){
 const db=opts.db||new DatabaseSync(':memory:');if(!opts.db)db.exec("PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);INSERT INTO users VALUES('master'),('other');");
 const enc=Buffer.alloc(32,7),mac=x=>crypto.createHmac('sha256',enc).update(x).digest('hex');
 const encrypt=x=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',enc,iv),b=Buffer.concat([c.update(x,'utf8'),c.final()]);return ['v1',iv.toString('base64url'),c.getAuthTag().toString('base64url'),b.toString('base64url')].join('.');};
 const decrypt=x=>{const[v,i,t,b]=x.split('.');assert.equal(v,'v1');const c=crypto.createDecipheriv('aes-256-gcm',enc,Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([c.update(Buffer.from(b,'base64url')),c.final()]).toString('utf8');};
 const state=opts.state||{revision:'a'.repeat(64),binding:'b'.repeat(64),active:true,scope:true,brands:['fish','aristo']},calls=opts.calls||[],operations=opts.operations||new Map();let source;
 function identity(owner){return {role:'superadmin',active:state.active,revision:state.revision};}
 function consent(c){if(!c?.original||c.csrf!=='fixture'||c.nativeBearer!==undefined)throw Error('denied secret');return {userId:'master',sessionHash:'c'.repeat(64)};}
 function authorize(c,{brand,write}){if(!state.scope||!state.brands.includes(brand)||c?.owner==='other')throw Error('unauthorized secret');return {ownerId:'master',ownerRevision:state.revision,binding:state.binding};}
 const response=(status,b)=>({status,revision:D.REVISION,body:b});
 function original(x,full=false){const value={operation_id:'66666666-6666-4666-8666-666666666666',idempotency_key:x.idempotency_key,brand:x.brand,state:'claimed',query_sha256:D.QUERY,bulk_operation_id:null,next_chunk:0,chunks:null,error_code:null};return full?{...value,kind:'run',scheduled_for:x.scheduled_for,source_sha256:null,last_chunk:null,last_chunk_sha256:null,last_receipt:null}:value;}
 async function transport(q){calls.push(q);assert(Object.keys(q).every(k=>['method','path','body','bearer'].includes(k)));assert(q.path==='/healthz'||q.path==='/v1/run'||q.path.startsWith('/v1/operations/'));if(opts.hook)await opts.hook(q,source,state);if(opts.fail)throw Error(key);if(q.path==='/healthz')return response(200,{service:'crm-shopify-sync',enabled:true,revision:opts.healthRevision||D.REVISION,product_semantics:'v2',stopping:false});assert.equal(typeof q.bearer,'string');if(opts.unauthorized||q.bearer!==(state.serviceKey||key))return response(401,{error:'UNAUTHORIZED'});if(q.method==='POST'){const x=q.body;operations.set(x.idempotency_key,x);if(opts.lost)throw Error(key);const b=original(x);if(opts.postBad)b.brand='aristo'===x.brand?'fish':'aristo';return response(opts.http503?503:202,opts.http503?{error:'SYNC_UNAVAILABLE'}:b);}const x=operations.get(q.path.slice('/v1/operations/'.length));if(!x)return response(503,{error:'SYNC_UNAVAILABLE'});const b=original(x,true);if(opts.completed){b.state='completed';b.bulk_operation_id='gid://shopify/BulkOperation/123';b.chunks=1;b.next_chunk=1;b.source_sha256='d'.repeat(64);b.last_receipt={status:'ready',customers:key};}if(opts.getBad)b.scheduled_for='2026-10-07T14:00:00.000Z';if(opts.large)return {...response(200,b),body:{oversized:'x'.repeat(32769)}};if(opts.redirect)return {...response(200,b),status:302,headers:{'X-CRM-Shopify-Sync-Revision':D.REVISION,Location:'https://invalid'}};if(opts.getPatch)Object.assign(b,opts.getPatch);return response(200,b);}
 const args={enabled:true,db,consent,identity,authorize,encrypt,decrypt,mac,transport,now:()=>time,uuid:()=>crypto.randomUUID(),timeoutMs:opts.timeoutMs||1000,permitDelegation:(c,connectionId)=>{consent(c);return {connection:{id:connectionId,scopes:['crm.source-sync']}};}};
 source=D.createSourceSync(args);if(!opts.db)source.bind({context:ctx,bearer:key,brands:opts.bindBrands||['fish','aristo'],privateNetwork:true});return {source,args,db,state,calls,operations,response,opts};
}

const correctedKey='SyntheticOnly.CorrectedServiceKey.1234567890';
const posts=f=>f.calls.filter(q=>q.method==='POST').length;
const data=f=>JSON.parse(f.db.prepare('SELECT data FROM crm_native_source_attempt_v1 WHERE request_id=?').get(id).data);
const progress={state:'chunk_uncertain',bulk_operation_id:'gid://shopify/BulkOperation/123',next_chunk:7,chunks:11,last_chunk:6};
const run=f=>f.source.run({context:ctx,brand:'aristo',requestId:id});
const inspect=f=>f.source.inspect({context:ctx,brand:'aristo',requestId:id});
const reseal=(f,a)=>{const text=D.canonical(a);f.db.prepare('UPDATE crm_native_source_attempt_v1 SET data=?,seal=? WHERE request_id=?').run(text,f.args.mac('attempt:'+text),id);};
const projected=r=>[r.operation.nextChunk,r.operation.totalChunks,r.operation.lastChunk];
async function prepared(opts={}){const f=fixture(opts);await run(f);return f;}
test('historical four-field result remains readable; missing progress is null, not zero',async()=>{const f=await prepared();try{assert.equal(Object.keys(data(f).result).length,4);const source=D.createSourceSync(f.args),r=source.list(ctx).attempts[0];assert.deepEqual(projected(r),[null,null,null]);assert.equal(r.operation.state,'claimed');assert.equal(posts(f),1);}finally{f.db.close();}});
test('authenticated original GET adds bounded numeric progress of same intention',async()=>{const f=await prepared({getPatch:progress});try{const initial=data(f),payload=f.calls.find(q=>q.method==='POST').body;f.calls.length=0;const r=await inspect(f);assert.deepEqual(projected(r),[7,11,6]);assert.equal(r.operation.state,'chunk_uncertain');assert.equal(r.authorizesAudienceRefresh,false);assert(f.calls.every(q=>q.method==='GET'));assert.deepEqual(f.calls.map(q=>q.path),['/healthz','/v1/operations/'+payload.idempotency_key]);assert.equal(f.calls.at(-1).bearer,key);const saved=data(f);for(const k of ['ownerId','brand','ownerRevision','binding','credentialRevision','credentialSeal','privatePayload','createdAt'])assert.equal(saved[k],initial[k]);assert.deepEqual(projected(D.createSourceSync(f.args).list(ctx).attempts[0]),[7,11,6]);}finally{f.db.close();}});
test('unknown total/last from original GET stay null; confirmed next zero stays zero',async()=>{const f=await prepared();try{assert.deepEqual(projected(await inspect(f)),[0,null,null]);}finally{f.db.close();}});
test('maximum next/total 50 and last 49 are retained',async()=>{const f=await prepared({getPatch:{...progress,next_chunk:50,chunks:50,last_chunk:49}});try{assert.deepEqual(projected(await inspect(f)),[50,50,49]);}finally{f.db.close();}});
test('equal next/total does not turn chunk_uncertain into completed or unblock new intent',async()=>{const f=await prepared({getPatch:{...progress,next_chunk:11,chunks:11,last_chunk:10}});try{const r=await inspect(f);assert.equal(r.operation.state,'chunk_uncertain');assert(!f.source.status(ctx).newIntentBrands.includes('aristo'));await assert.rejects(f.source.run({context:ctx,brand:'aristo',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(posts(f),1);}finally{f.db.close();}});
test('completed requires original state and existing completion contract',async()=>{const f=await prepared({getPatch:{...progress,state:'completed',next_chunk:11,last_chunk:10}});try{const r=await inspect(f);assert.equal(r.operation.state,'completed');assert.deepEqual(projected(r),[11,11,10]);assert(f.source.status(ctx).newIntentBrands.includes('aristo'));assert.equal(posts(f),1);}finally{f.db.close();}});
for(const patch of [{next_chunk:-1},{next_chunk:51},{next_chunk:1.5},{next_chunk:'7'},{chunks:0},{chunks:51},{chunks:'11'},{next_chunk:12,chunks:11},{last_chunk:-1},{last_chunk:50},{last_chunk:'6'},{state:'completed',next_chunk:7,chunks:11},{state:'completed',bulk_operation_id:null},{state:'completed',chunks:null}])test('invalid GET '+JSON.stringify(patch)+' retains previous confirmed progress',async()=>{const f=await prepared({getPatch:{...progress}});try{const before=await inspect(f),saved=data(f).result;f.opts.getPatch={...progress,...patch};const r=await inspect(f);assert.equal(r.attempt,'uncertain');assert.deepEqual(r.operation,before.operation);assert.deepEqual(data(f).result,saved);assert.equal(posts(f),1);}finally{f.db.close();}});
test('GET404/unconfirmed retains last evidence and never reissues POST',async()=>{const f=await prepared({getPatch:progress});try{const prior=await inspect(f);const t=f.args.transport;const source=D.createSourceSync({...f.args,transport:async q=>q.path.startsWith('/v1/operations/')?(f.calls.push(q),f.response(404,{error:'NOT_FOUND'})):t(q)});const r=await source.inspect({context:ctx,brand:'aristo',requestId:id});assert.deepEqual(r.operation,prior.operation);assert.equal(r.attempt,'uncertain');assert.equal(posts(f),1);}finally{f.db.close();}});
test('historical progress survives actual key change, current GET uses same original private key and pending remains blocked',async()=>{const f=await prepared({getPatch:progress});try{const before=await inspect(f),saved=data(f),payload=f.calls.find(q=>q.method==='POST').body;f.source.bind({context:ctx,bearer:correctedKey,brands:['aristo'],privateNetwork:true});f.state.serviceKey=correctedKey;assert.deepEqual(f.source.list(ctx).attempts[0].operation,before.operation);await inspect(f);assert.equal(f.calls.at(-1).bearer,correctedKey);assert.equal(f.calls.at(-1).path,'/v1/operations/'+payload.idempotency_key);assert.equal(data(f).privatePayload,saved.privatePayload);await assert.rejects(f.source.run({context:ctx,brand:'aristo',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(posts(f),1);}finally{f.db.close();}});
for(const change of ['revoke','scope','binding'])test('CURRENT '+change+' during GET await suppresses progress emission and persistence',async()=>{const f=await prepared({getPatch:progress});try{const before=data(f).result;f.opts.hook=async(q,s,state)=>{if(q.path.startsWith('/v1/operations/')){await Promise.resolve();if(change==='revoke')s.revoke(ctx);if(change==='scope')state.scope=false;if(change==='binding')state.binding='e'.repeat(64);}};await assert.rejects(inspect(f));assert.deepEqual(data(f).result,before);assert.equal(posts(f),1);}finally{f.db.close();}});
test('public progress exposes no secrets, private identifiers, hashes, receipts or original error text',async()=>{const f=await prepared({getPatch:{...progress,error_code:'PRIVATE_CAUSE',source_sha256:'d'.repeat(64),last_chunk_sha256:'e'.repeat(64),last_receipt:{customers:key,error:'private customer text'}}});try{const r=await inspect(f),text=JSON.stringify(r);assert.deepEqual(Object.keys(r.operation).sort(),['checkedAt','lastChunk','nextChunk','operationId','sourceAuthenticated','state','totalChunks']);for(const secret of [key,'PRIVATE_CAUSE','private customer text','gid://shopify',f.calls.find(q=>q.method==='POST').body.idempotency_key,'query_sha256','source_sha256','last_receipt','idempotency_key'])assert(!text.includes(secret));assert(Object.isFrozen(r.operation));}finally{f.db.close();}});
for(const resultPatch of [{nextChunk:7},{nextChunk:51,totalChunks:11,lastChunk:6},{nextChunk:7,totalChunks:11,lastChunk:50},{nextChunk:7,totalChunks:11,lastChunk:6,secret:'no'}])test('sealed malformed persisted optional progress rejected '+JSON.stringify(resultPatch),async()=>{const f=await prepared();try{const a=data(f);a.result={...a.result,...resultPatch};reseal(f,a);assert.throws(()=>f.source.list(ctx),{code:'SOURCE_INTEGRITY'});}finally{f.db.close();}});
test('HMAC tampering of progress fails closed before GET transport',async()=>{const f=await prepared({getPatch:progress});try{await inspect(f);f.db.prepare("UPDATE crm_native_source_attempt_v1 SET data=replace(data,'\"nextChunk\":7','\"nextChunk\":8')").run();const n=f.calls.length;await assert.rejects(inspect(f),{code:'SOURCE_INTEGRITY'});assert.equal(f.calls.length,n);}finally{f.db.close();}});
test('GET401 after key epoch retains progress, does not become POST refusal or release new intention',async()=>{const f=await prepared({getPatch:progress});try{const prior=await inspect(f);f.source.bind({context:ctx,bearer:correctedKey,brands:['aristo'],privateNetwork:true});f.opts.unauthorized=true;const r=await inspect(f);assert.equal(r.attempt,'key_refused');assert.deepEqual(r.operation,prior.operation);assert.equal(data(f).postRefusal,null);assert(!f.source.status(ctx).newIntentBrands.includes('aristo'));await assert.rejects(f.source.run({context:ctx,brand:'aristo',requestId:other}),{code:'SOURCE_ATTEMPT_PENDING'});assert.equal(posts(f),1);}finally{f.db.close();}});
test('lost current scope forbids persisted historical progress before any transport',async()=>{const f=await prepared({getPatch:progress});try{await inspect(f);f.state.scope=false;const n=f.calls.length;assert.throws(()=>f.source.list(ctx),{code:'SOURCE_SPECIFIC_AUTHORIZATION_REQUIRED'});await assert.rejects(inspect(f));assert.equal(f.calls.length,n);}finally{f.db.close();}});
