'use strict';
// Original auth and gateway in a disposable source fixture; no production
// identity, database, grant, source service or network participates.
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {Readable,Writable}=require('node:stream');
const runtime=process.env.SOURCE_SYNC_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const {createAuth}=require(runtime+'/auth.cjs'),{settingsFromEnv,createServer}=require(runtime+'/server.cjs'),P=require(runtime+'/proxy.cjs');
const host='gerencial.shrigma.com.br',origin='https://'+host,email='felipebandeira@oaristocrata.com',sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const requestId='cccccccc-cccc-4ccc-8ccc-cccccccccccc',sourceBearer='isolated-source-service-key-000000000000',revision='79861de6f9c3628885e7840858011180b5af9899',query='bb89faf525f58f9c5075878888c1be6fcf4992200310a4867cdd2871fb570086';
const originalResponse=(value,url)=>{const r=new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});Object.defineProperty(r,'url',{value:String(url)});return r;};
async function fixture(t,{enabled=true}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'isolated-native-source-auth-')),dbPath=path.join(dir,'identity.sqlite'),masterKey='isolated-central-master-'+crypto.randomBytes(12).toString('hex');
 const env={DASHBOARD_MODE:'operational',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_MANAGER_HOST:host,DASHBOARD_AREA_HOSTS:JSON.stringify({growth:'crm.shrigma.com.br',organico:'organico.shrigma.com.br',influs:'influs.shrigma.com.br'}),DASHBOARD_EMAIL_DOMAINS:'["oaristocrata.com","shrigma.com.br","fishermans.com.br"]',DASHBOARD_ADMIN_EMAIL:email,DASHBOARD_BOOTSTRAP_SHA256:sha('isolated-bootstrap'),DASHBOARD_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),DASHBOARD_CRM_CAMPAIGN_WRITER_PROFILE:'own-master-production-v1',DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'enabled',DASHBOARD_CRM_MASTER_AUDIENCE_READ:'enabled',DASHBOARD_CRM_MASTER_AUDIENCE_WRITE:'enabled',DASHBOARD_NATIVE_MCP:'enabled',...(enabled?{DASHBOARD_NATIVE_SHOPIFY_SOURCE:'enabled'}:{}),DASHBOARD_UPSTREAMS:JSON.stringify({'crm-read':P.FIXED_DESTINATIONS['crm-read'],campaigns:P.REVIEWED_DYNAMIC.routes.campaigns,segments:P.REVIEWED_DYNAMIC.routes.segments}),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify(['comunicacao-crm-panel-read.tazdb8.easypanel.host','n8n-n8n.tazdb8.easypanel.host','comunicacao-crm-audience.tazdb8.easypanel.host']),DASHBOARD_DYNAMIC_ROUTE_MANIFEST:JSON.stringify({schema:P.DYNAMIC_MANIFEST_SCHEMA,sourceRevision:P.REVIEWED_DYNAMIC.sourceRevision,routes:{campaigns:P.REVIEWED_DYNAMIC.routes.campaigns,segments:P.REVIEWED_DYNAMIC.routes.segments}}),DASHBOARD_DB_PATH:dbPath,DASHBOARD_PUBLIC_DIR:dir};
 const calls=[];let started;
 const sourceTransport=async input=>{calls.push(input);if(input.path==='/healthz')return {status:200,revision,body:{service:'crm-shopify-sync',enabled:true,revision,product_semantics:'v2',stopping:false}};a.equal(input.bearer,sourceBearer);if(input.method==='POST'){started={...input.body};return {status:202,revision,body:{operation_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',idempotency_key:started.idempotency_key,brand:started.brand,state:'claimed',query_sha256:query,bulk_operation_id:null,next_chunk:0,chunks:null,error_code:null}};}return {status:200,revision,body:{operation_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',idempotency_key:started.idempotency_key,brand:started.brand,kind:'run',scheduled_for:started.scheduled_for,state:'claimed',query_sha256:query,bulk_operation_id:null,source_sha256:null,next_chunk:0,chunks:null,last_chunk:null,last_chunk_sha256:null,last_receipt:null,error_code:null}};};
 const settings=settingsFromEnv(env),auth=createAuth({...settings,crmNativeSourceTransport:sourceTransport});t.after(()=>{auth.close();fs.rmSync(dir,{recursive:true,force:true});});
 await auth.completeBootstrap({email,token:'isolated-bootstrap',password:'Isolated-Test-Password-2026!',host,origin});const login=await auth.login({email,password:'Isolated-Test-Password-2026!',host,origin}),ctx={cookieHeader:login.cookie.split(';')[0],host,origin,method:'POST',csrf:login.csrf},user=auth.session(ctx).user;
 auth.setUpstreamCredential({context:ctx,userId:user.id,slot:'growth-read',bearer:masterKey});await auth.activateOwnMasterCampaignWriter({context:ctx,fetchImpl:async url=>originalResponse({schema:'shrigma_access_identity_v1',role:'master',panel:'todos',owner:email,allowedPanels:['cx','growth','organico','influs'],permissions:{growth:{who:'panel:isolated-source-master',label:email,caps:['read_content','draft','validate','submit']},influs:null}},url)});
 const issued=auth.nativeConnections.issue({context:ctx,brands:['fish'],scopes:['crm.read','crm.draft'],expiresDays:1}),server=createServer(settings,{auth,sourcePeerTransport:sourceTransport});t.after(()=>server.close());
 async function request(method,url,body,native=false){const req=Readable.from(body===undefined?[]:[Buffer.from(JSON.stringify(body))]);req.method=method;req.url=url;req.headers={host,origin,...(native?{authorization:'Bearer '+issued.token,accept:'application/json, text/event-stream'}:{cookie:ctx.cookieHeader,'x-csrf-token':ctx.csrf}),...(body===undefined?{}:{'content-type':'application/json'})};req.socket={remoteAddress:'isolated-source-fixture'};const chunks=[],res=new Writable({write(c,_e,cb){chunks.push(Buffer.from(c));cb();}});res.statusCode=200;res.setHeader=()=>{};res.getHeader=()=>undefined;const done=new Promise(r=>res.once('finish',r));server.emit('request',req,res);await done;return {status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString())};}
 const rpc=(name,args)=>request('POST','/api/native/mcp',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}},true);
 return {env,settings,auth,ctx,issued,calls,request,rpc};
}
test('actual original Master consent adds source scope and one native run remains inspectable in the same browser portal',async t=>{
 const f=await fixture(t);
 const peer=await f.rpc('crm_status',{});a.equal(peer.body.result.structuredContent.body.sourcePeer.body.reachable,true);a.equal(peer.body.result.structuredContent.body.sourcePeer.body.keyAuthenticationProven,false);a.equal(f.calls.filter(x=>x.method==='POST').length,0);
 await f.auth.nativeSourceSync.bind({context:f.ctx,bearer:sourceBearer,brands:['fish'],privateNetwork:true});
 const denied=await f.rpc('crm_source_sync_run',{brand:'fish',requestId});a.equal(denied.body.result?.structuredContent?.error,'NATIVE_SCOPE_DENIED');a.equal(f.calls.filter(x=>x.method==='POST').length,0);
 f.auth.nativeConnections.permitSourceSync({context:f.ctx,connectionId:f.issued.connection.id});
 const result=await f.rpc('crm_source_sync_run',{brand:'fish',requestId});a.equal(result.body.result?.structuredContent?.status,200,JSON.stringify(result));a.equal(f.calls.filter(x=>x.method==='POST').length,1);
 const read=await f.request('GET','/api/source-sync?action=inspect&brand=fish&requestId='+requestId);a.equal(read.status,200,JSON.stringify(read));a.equal(f.calls.filter(x=>x.method==='POST').length,1);a.equal(JSON.stringify(read.body).includes(sourceBearer),false);
 const before=f.calls.length,cross=await f.request('GET','/api/source-sync?action=inspect&brand=aristo&requestId='+requestId);a.equal(cross.status,403);a.equal(f.calls.length,before);
 f.auth.nativeConnections.revoke({context:f.ctx,connectionId:f.issued.connection.id});const revoked=await f.rpc('crm_source_sync_inspect',{brand:'fish',requestId});a.equal(revoked.status,401);a.equal(f.calls.length,before);
});
test('source stays absent by default and private binding rejects a wrong original browser CSRF',async t=>{
 const off=await fixture(t,{enabled:false});a.equal(off.auth.nativeSourceSync,undefined);a.equal((await off.request('POST','/api/source-sync',{action:'run',brand:'fish',requestId})).status,503);a.equal(off.calls.length,0);
 const on=await fixture(t);await a.rejects(async()=>on.auth.nativeSourceSync.bind({context:{...on.ctx,csrf:'wrong'},bearer:sourceBearer,brands:['fish'],privateNetwork:true}),e=>e.code==='SOURCE_SPECIFIC_AUTHORIZATION_REQUIRED'&&e.status===403);a.equal(on.calls.length,0);a.equal(on.auth.nativeSourceSync.status(on.ctx).linked,false);
 a.throws(()=>settingsFromEnv({...on.env,DASHBOARD_NATIVE_MCP:'disabled'}),/source connection configuration invalid/);
});
