'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path'),fs=require('node:fs'),{DatabaseSync}=require('node:sqlite');
const {fixture,deferred,canonical,sha,D,inputRoot}=require('./fixture.cjs');
const runtime=process.env.DELIVERY_HEALTH_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const {createDelegationStore,SCOPES}=require(path.join(runtime,'crm-native-delegation.cjs'));
const {createDeliveryHealthController}=require(path.join(runtime,'native-delivery-health-controller.cjs'));
const context={method:'POST',host:'manager.original.invalid',session:'fixture-session',csrf:'fixture-csrf'},ownerId='original-master';
function harness(options={}){
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY)');db.prepare('INSERT INTO users VALUES(?)').run(ownerId);
 let owner={role:'superadmin',active:true,revision:'1'.repeat(64),canEditGrowth:false},time=Date.now(),crm={fish:'2'.repeat(64),aristo:'3'.repeat(64)},profileRevision=1;
 const mac=x=>crypto.createHmac('sha256','synthetic-only-secret').update(x).digest('hex');
 const consent=ctx=>{if(ctx?.nativeBearer!==undefined||ctx?.method!=='POST'||ctx?.session!==context.session||ctx?.csrf!==context.csrf)throw Error('ORIGINAL_BROWSER_CSRF_REQUIRED');return {userId:ownerId,sessionHash:sha(ctx.session)};};
 const store=createDelegationStore({db,managerHost:context.host,consent,identity:id=>id===ownerId?owner:null,mac,now:()=>time});
 const issued=store.issue({context,brands:options.brands||['fish','aristo'],scopes:options.scopes||['crm.read']});
 const f=fixture(options.protocol||{});const profile=()=>({schema:'shrigma-private-database-credential-v1',revision:profileRevision,ownerId,username:'fixture_reader',password:'SYNTHETIC_DB_SECRET',resource:{...D.RESOURCE},transport:{mode:'admitted-private-network'}});
 const calls=[];const auth={nativeConnections:store,nativeDatabaseVault:{getPrivateCredential:({ownerId:id})=>{assert.equal(id,ownerId);return profile();},status:ctx=>{consent(ctx);return {linked:true};}},ownMasterPublishedJourneyReadBinding:(ctx,{brand})=>{calls.push({ctx,brand});assert.equal(ctx.method,'GET');if(!crm[brand])throw Error('CRM_READ_DENIED');return {userId:ownerId,binding:crm[brand],credential:'SYNTHETIC_MASTER_SECRET'};}};
 const controller=createDeliveryHealthController({enabled:true,driver:f.args.driver,auth});
 const q={context,connectionId:issued.connection.id,brand:'aristo'};
 return {db,store,issued,f,auth,controller,q,mac,calls,profile,changeOwner:delta=>owner={...owner,...delta},changeProfile:()=>profileRevision++,changeCRM:brand=>crm[brand]='9'.repeat(64),denyCRM:brand=>crm[brand]=null,expire:()=>time+=31*86400000,cleanup:async()=>{await controller.close().catch(()=>{});db.close();}};
}
async function admitted(h){return h.controller.authorize({...h.q,consent:true});}
test('legacy binding function byte identical, source preserved and distinct scope',()=>{const original=fs.readFileSync(path.join(inputRoot,'inputs/services/dashboard-operational/crm-native-delegation.cjs'),'utf8'),updated=fs.readFileSync(path.join(runtime,'crm-native-delegation.cjs'),'utf8');assert.equal(updated.match(/ const bind=r=>[^\n]+/)[0],original.match(/ const bind=r=>[^\n]+/)[0]);assert(SCOPES.includes('crm.delivery-health'));for(const scope of ['crm.read','crm.draft','crm.iam','db.inspect','db.install','crm.source-sync','crm.source-diagnostics'])assert(SCOPES.includes(scope));});
test('same SQLite preserves old token & exact legacy MAC, additive consent only',async()=>{const h=harness();try{const before=h.db.prepare('SELECT * FROM crm_native_connections_v1').get();assert.equal(before.binding_mac,h.mac(JSON.stringify([before.id,before.token_hash,before.user_id,before.host,before.label,before.brands_json,before.scopes_json,before.auth_revision,before.source_session_hash,before.created_at,before.expires_at,before.revoked_at])));assert.throws(()=>h.store.authenticate(h.issued.token,{scope:'crm.delivery-health'}));await admitted(h);const after=h.db.prepare('SELECT * FROM crm_native_connections_v1').get();assert.equal(after.token_hash,before.token_hash);assert.equal(after.source_session_hash,before.source_session_hash);assert.deepEqual(JSON.parse(after.scopes_json),['crm.delivery-health','crm.read']);assert.equal(h.store.authenticate(h.issued.token,{scope:'crm.delivery-health',brand:'aristo'}).userId,ownerId);assert.equal(h.db.prepare('SELECT count(*) n FROM crm_native_delivery_health_consent_v1').get().n,1);const b=h.store.deliveryHealthConsent({...h.q});assert.equal(b.ownerId,ownerId);assert.equal(b.queryHash,D.queryHash);assert(!JSON.stringify(b).includes('SECRET'));assert.deepEqual(h.calls.slice(0,2).map(q=>q.brand),['fish','aristo']);assert.equal((await h.controller.inspect(h.q)).operational,false);}finally{await h.cleanup();}});
test('legacy issue read works; diagnostic and health require own consent; legacy write guards unchanged',async()=>{const h=harness();try{for(const scope of ['crm.delivery-health','crm.source-diagnostics','crm.draft','crm.source-sync'])assert.throws(()=>h.store.issue({context,brands:['fish','aristo'],scopes:[scope]}));h.store.permitInspection({context,connectionId:h.q.connectionId});assert(h.store.authenticate(h.issued.token,{scope:'db.inspect'}));assert.throws(()=>h.store.permitSourceSync({context,connectionId:h.q.connectionId}));assert.throws(()=>h.store.deliveryHealthConsent(h.q));}finally{await h.cleanup();}});
for(const changes of [{brands:['fish']},{scopes:['db.inspect']}])test('shared global counters require crm.read and both brands '+JSON.stringify(changes),async()=>{const h=harness(changes);try{assert.throws(()=>h.controller.authorize({...h.q,consent:true}));assert.equal(h.f.clients.length,0);}finally{await h.cleanup();}});
test('native resolves key and rejects caller connection/owner; cannot consent itself',async()=>{const h=harness();try{await admitted(h);const native=h.store.context(h.issued.token,{scope:'crm.delivery-health',brand:'aristo'});assert.equal((await h.controller.inspect({context:native,brand:'aristo'})).brand,'aristo');await assert.rejects(h.controller.inspect({context:native,brand:'aristo',connectionId:h.q.connectionId}));assert.throws(()=>h.controller.authorize({context:native,connectionId:h.q.connectionId,brand:'aristo',consent:true}));assert.throws(()=>h.store.permitDeliveryHealth({context:native,connectionId:h.q.connectionId,binding:h.store.deliveryHealthConsent(h.q)}));}finally{await h.cleanup();}});
test('consent is per brand; exact browser context/CSRF required',async()=>{const h=harness();try{for(const ctx of [{...context,csrf:'wrong'},{...context,method:'GET'}])assert.throws(()=>h.controller.authorize({...h.q,context:ctx,consent:true}));assert.throws(()=>h.controller.authorize({...h.q,consent:false}));await admitted(h);await assert.rejects(h.controller.inspect({...h.q,brand:'fish'}));h.controller.authorize({...h.q,brand:'fish',consent:true});assert.equal((await h.controller.inspect({...h.q,brand:'fish'})).brand,'fish');}finally{await h.cleanup();}});
const mutations={
 revoke:h=>h.store.revoke({context,connectionId:h.q.connectionId}),
 owner:h=>h.changeOwner({active:false}),revision:h=>h.changeOwner({revision:'7'.repeat(64)}),role:h=>h.changeOwner({role:'analyst'}),expiry:h=>h.expire(),
 crmFish:h=>h.changeCRM('fish'),crmAristo:h=>h.changeCRM('aristo'),crmDenied:h=>h.denyCRM('fish'),vault:h=>h.changeProfile(),
 rowMAC:h=>h.db.prepare("UPDATE crm_native_connections_v1 SET binding_mac=?").run('0'.repeat(64)),
 consentMAC:h=>h.db.prepare("UPDATE crm_native_delivery_health_consent_v1 SET binding_mac=?").run('0'.repeat(64)),
 key:h=>{const r=h.db.prepare('SELECT * FROM crm_native_connections_v1').get();r.token_hash=sha('rotated');const seal=h.mac(JSON.stringify([r.id,r.token_hash,r.user_id,r.host,r.label,r.brands_json,r.scopes_json,r.auth_revision,r.source_session_hash,r.created_at,r.expires_at,r.revoked_at]));h.db.prepare('UPDATE crm_native_connections_v1 SET token_hash=?,binding_mac=?').run(r.token_hash,seal);}
};
for(const [name,mutate] of Object.entries(mutations))test('CURRENT '+name+' prevents read after consent',async()=>{const h=harness();try{await admitted(h);mutate(h);await assert.rejects(h.controller.inspect(h.q));assert.equal(h.f.clients.length,0);}finally{await h.cleanup();}});
for(const point of ['connect','read','rollback','end'])for(const [name,mutate] of Object.entries(mutations).filter(([k])=>['revoke','crmFish','vault','key','revision','consentMAC'].includes(k)))test('suppress stale '+name+' during '+point,async()=>{const hold=deferred(),entered=deferred(),protocol=point==='connect'?{connectWait:hold,connectEntered:entered}:point==='read'?{holdRead:hold,entered}:{},h=harness({protocol});try{await admitted(h);if(point==='rollback')h.f.opts.queryHook=async q=>{if(q===D.ROLLBACK){entered.resolve();await hold.promise;}};if(point==='end')h.f.opts.endHook=async()=>{entered.resolve();await hold.promise;};const pending=h.controller.inspect(h.q),refusal=assert.rejects(pending);await entered.promise;mutate(h);hold.resolve();await refusal;assert.equal(h.f.clients[0].ends,1);}finally{await h.cleanup();}});
test('controller OFF without original CURRENT read dependency; no source-sync needed',async()=>{const h=harness();try{const auth={...h.auth,ownMasterPublishedJourneyReadBinding:undefined};const c=createDeliveryHealthController({enabled:true,driver:h.f.args.driver,auth});assert.equal(c.enabled,false);await assert.rejects(c.inspect(h.q));assert.equal(h.controller.enabled,true);assert.equal(h.auth.nativeSourceSync,undefined);}finally{await h.cleanup();}});
test('controller concurrency and close suppress pending result after drain',async()=>{const holdRead=deferred(),entered=deferred(),h=harness({protocol:{holdRead,entered}});try{await admitted(h);const pending=h.controller.inspect(h.q),refusal=assert.rejects(pending);await entered.promise;await assert.rejects(h.controller.inspect(h.q),{code:'DELIVERY_HEALTH_BUSY'});const closing=h.controller.close();holdRead.resolve();await refusal;await closing;await assert.rejects(h.controller.inspect(h.q));}finally{await h.cleanup();}});

test('historical source purpose methods preserved byte for byte',()=>{const original=fs.readFileSync(path.join(inputRoot,'inputs/services/dashboard-operational/crm-native-delegation.cjs'),'utf8'),updated=fs.readFileSync(path.join(runtime,'crm-native-delegation.cjs'),'utf8');for(const [start,end] of [[' function permitInspection(', ' function permitSourceSync('],[' function permitSourceSync(', ' function diagnosticBinding('],[' function diagnosticBinding(', ' const diagnosticSeal='],[' const diagnosticSeal=', ' function permitSourceDiagnostics('],[' function permitSourceDiagnostics(', ' function sourceDiagnosticsConsent(']])assert.equal(updated.slice(updated.indexOf(start),updated.indexOf(end)),original.slice(original.indexOf(start),original.indexOf(end)));const start=' function sourceDiagnosticsConsent(';assert.equal(updated.slice(updated.indexOf(start),updated.indexOf(' // Own health purpose:')),original.slice(original.indexOf(start),original.indexOf(' return Object.freeze({issue,authenticate,context,list,revoke,')));});
test('consent bound connection/brand/body HMAC cannot be transplanted',async()=>{const h=harness();try{await admitted(h);h.db.prepare("UPDATE crm_native_delivery_health_consent_v1 SET brand='fish'").run();assert.throws(()=>h.store.deliveryHealthConsent({...h.q,brand:'fish'}));await assert.rejects(h.controller.inspect(h.q));}finally{await h.cleanup();}});
test('same token scopes fail shared read even with valid legacy row MAC',async()=>{const h=harness();try{await admitted(h);const r=h.db.prepare('SELECT * FROM crm_native_connections_v1').get();r.scopes_json='["crm.delivery-health"]';const seal=h.mac(JSON.stringify([r.id,r.token_hash,r.user_id,r.host,r.label,r.brands_json,r.scopes_json,r.auth_revision,r.source_session_hash,r.created_at,r.expires_at,r.revoked_at]));h.db.prepare('UPDATE crm_native_connections_v1 SET scopes_json=?,binding_mac=?').run(r.scopes_json,seal);assert.throws(()=>h.store.authenticate(h.issued.token,{scope:'crm.delivery-health',brand:'aristo'}),{code:'NATIVE_HEALTH_SHARED_READ_REQUIRED'});}finally{await h.cleanup();}});
