'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const packageRoot=process.env.DELIVERY_HEALTH_SCOPE_SOURCE||path.resolve(__dirname,'../../..');
const sourceRoot=process.env.DELIVERY_HEALTH_BRAND_SET_SOURCE||path.join(packageRoot,'inputs/tests/delivery-health-read-native/sealed-brand-set-inputs');
const runtime=process.env.DELIVERY_HEALTH_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
if(!process.env.DELIVERY_HEALTH_RUNTIME)process.env.DELIVERY_HEALTH_RUNTIME=runtime;
const fixturePath=fs.existsSync(path.join(__dirname,'fixture.cjs'))?path.join(__dirname,'fixture.cjs'):path.join(sourceRoot,'inputs/tests/delivery-health-read-native/fixture.cjs');
const {D,fixture,inspect,baseEvidence,accelerated,canonical,sha,password}=require(fixturePath),O=require(path.join(sourceRoot,'inputs/services/dashboard-operational/native-delivery-health.cjs'));
const metrics=['finalizacao_pendente','entregue_sem_gravacao','resultado_incerto','sem_confirmacao_15min','falhas_24h','reclamacoes_24h'];
const entry=marca=>({marca,...Object.fromEntries(metrics.map(k=>[k,0]))});
const expectedKeys=['length','inspection','fish','aristo','other','malformed'];
function diagnosis(brands,extra={}){const raw={...baseEvidence(),...extra,brands};let error;assert.throws(()=>D.validatePayload(raw,'fish'),e=>{error=e;assert.equal(e.code,'HEALTH_PROTOCOL_REFUSED');assert.equal(e.status,503);return true;});return {error,d:D.protocolDiagnostic(error)};}
function assertSet(d,length,counts=null){assert.equal(d.schema,'shrigma-email-health-protocol-refusal-v1');assert.equal(d.field,'brands');assert.equal(d.reason,'brand-set');assert.equal(d.actualType,'array');assert.deepEqual(Object.keys(d),['schema','field','reason','actualType','brandSet']);assert(Object.isFrozen(d));assert(Object.isFrozen(d.brandSet));assert.deepEqual(Object.keys(d.brandSet),expectedKeys);assert.equal(d.brandSet.length,length);assert(Number.isSafeInteger(d.brandSet.length));assert.equal(d.brandSet.inspection,counts?'complete':'unavailable');for(const k of expectedKeys.slice(2))if(counts){assert(Number.isSafeInteger(d.brandSet[k]));assert(d.brandSet[k]>=0&&d.brandSet[k]<=64);}else assert.equal(d.brandSet[k],null);if(counts){assert.deepEqual(expectedKeys.slice(2).map(k=>d.brandSet[k]),counts);assert.equal(counts.reduce((a,b)=>a+b,0),length);}return d.brandSet;}
test('ten current input pins and original sealed four pins match without edits',()=>{const m=JSON.parse(fs.readFileSync(path.join(sourceRoot,'INPUT-PINS.json')));assert.equal(m.files.length,10);for(const f of m.files){const b=fs.readFileSync(path.join(sourceRoot,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);}const nested=path.join(sourceRoot,'inputs/tests/delivery-health-read-native/sealed-protocol-inputs'),old=JSON.parse(fs.readFileSync(path.join(nested,'INPUT-PINS.json')));assert.equal(old.files.length,4);for(const f of old.files){const b=fs.readFileSync(path.join(nested,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex'),f.githubBlobSha1);}});
test('validator/first failure/session/SQL/purpose/driver/closure byte preserved',()=>{for(const k of ['READ_SQL','PURPOSE','RESOURCE','queryHash','PEER','BEGIN','ROLLBACK'])assert.deepEqual(D[k],O[k]);const original=fs.readFileSync(path.join(sourceRoot,'inputs/services/dashboard-operational/native-delivery-health.cjs'),'utf8'),updated=fs.readFileSync(path.join(runtime,'native-delivery-health.cjs'),'utf8');const stripped=(updated.split('// BEGIN PRIVATE FIXED SOURCE SCOPE PROJECTION')[0]+updated.split('// END PRIVATE FIXED SOURCE SCOPE PROJECTION\n')[1]).replace('const payload=validatePrivateSource(row.payload,input.brand);','const payload=validatePayload(row.payload,input.brand);');assert.equal(stripped.slice(stripped.indexOf('function protocolDiagnostic')),original.slice(original.indexOf('function protocolDiagnostic')));assert.equal(updated.slice(0,updated.indexOf('function rejectedBrandSet')),original.slice(0,original.indexOf('function protocolRefused')));});
for(const [name,brands,counts] of [
 ['empty',[],[0,0,0,0]],['fish only',[entry('fish')],[1,0,0,0]],['aristo only',[entry('aristo')],[0,1,0,0]],['three mixed',[entry('fish'),entry('aristo'),entry('fish')],[2,1,0,0]],['other strings',[entry('PRIVATE_UNKNOWN_EMAIL@example.invalid'),entry('fish'),entry('other-private')],[1,0,2,0]],['duplicate fish',[entry('fish'),entry('fish'),entry('fish')],[3,0,0,0]],['64 mixed',Array.from({length:64},(_,i)=>entry(i%2?'fish':'aristo')),[32,32,0,0]],['64 fish',Array.from({length:64},()=>entry('fish')),[64,0,0,0]]
])test('bounded complete coverage '+name+' remains503',()=>{const {d}=diagnosis(brands);assertSet(d,brands.length,counts);assert(!('healthy' in d));assert(!('operational' in d));assert.doesNotMatch(JSON.stringify(d),/PRIVATE_UNKNOWN|@|other-private/);});
test('65 / huge length unavailable with null counts and no entry inspections',()=>{const value=Array.from({length:65},()=>entry('fish'));Object.defineProperty(value,'0',{enumerable:true,get(){assert.fail('entry getter');}});assertSet(diagnosis(value).d,65);const huge=[];huge.length=4294967295;assertSet(diagnosis(huge).d,4294967295);});
test('malformed elements/brand types and foreign keys count without leaking content',()=>{for(const row of [null,0,'PRIVATE',[],()=>{},Object.create({marca:'fish'}),{marca:'fish'},entry(null),entry(1),entry(new String('fish')),{...entry('fish'),privateCustomerName:'PRIVATE'},Object.assign(entry('fish'),{[Symbol('PRIVATE')]:0})]){const {d}=diagnosis([row]);assertSet(d,1,[0,0,0,1]);assert.doesNotMatch(JSON.stringify(d),/PRIVATE|privateCustomer/);}});
test('null-prototype/frozen safe rows accepted for counting, metrics not inspected',()=>{const a=Object.assign(Object.create(null),entry('fish'));let calls=0;const getter=()=>{calls++;throw Error('PRIVATE');};const b=entry('aristo');for(const k of metrics)b[k]=new Proxy({}, {get:getter,ownKeys:getter,getPrototypeOf:getter});const c=entry('fish');for(const k of metrics)c[k]='PRIVATE_METRIC';const list=Object.freeze([Object.freeze(a),Object.freeze(b),Object.freeze(c)]);assertSet(diagnosis(list).d,3,[2,1,0,0]);assert.equal(calls,0);assert.doesNotMatch(JSON.stringify(diagnosis(list).d),/PRIVATE_METRIC/);});
for(const [name,modify] of [['sparse',a=>{delete a[0];return a;}],['own extra',a=>{a.private=1;return a;}],['symbol',a=>{a[Symbol('private')]=1;return a;}],['hidden entry',a=>Object.defineProperty(a,'0',{value:a[0],enumerable:false})],['entry accessor',a=>Object.defineProperty(a,'0',{enumerable:true,get(){assert.fail('array getter');}})],['hidden extra',a=>Object.defineProperty(a,'private',{value:1})],['toJSON',a=>{a.toJSON=()=>assert.fail('array toJSON');return a;}],['prototype',a=>{Object.setPrototypeOf(a,{});return a;}],['null proto',a=>{Object.setPrototypeOf(a,null);return a;}]])test('unsafe array '+name+' unavailable without evaluating extras',()=>assertSet(diagnosis(modify([entry('fish')])).d,1));
test('row marca/metric accessor and hidden descriptor unavailable, no getter invoked',()=>{let calls=0;const getter=()=>{calls++;throw Error('PRIVATE');};for(const key of ['marca',...metrics]){const r=entry('fish');Object.defineProperty(r,key,{get:getter,enumerable:true});assertSet(diagnosis([r]).d,1);}const hidden=entry('fish');Object.defineProperty(hidden,'falhas_24h',{enumerable:false,value:0});assertSet(diagnosis([hidden]).d,1);assert.equal(calls,0);});
test('row own toJSON/unknown keys are malformed, no toJSON/getter call',()=>{let calls=0;const r=entry('fish');Object.defineProperty(r,'toJSON',{enumerable:true,get(){calls++;throw Error('PRIVATE');}});assertSet(diagnosis([r]).d,1,[0,0,0,1]);assert.equal(calls,0);});
test('element proxies/revoked proxies unavailable, array proxy has no brandSet/traps',()=>{let calls=0;const trap=()=>{calls++;throw Error('PRIVATE');};const proxy=new Proxy(entry('fish'),{get:trap,ownKeys:trap,getPrototypeOf:trap,getOwnPropertyDescriptor:trap});assertSet(diagnosis([proxy]).d,1);const r=Proxy.revocable({},{});r.revoke();assertSet(diagnosis([r.proxy]).d,1);const a=new Proxy([entry('fish')],{get:trap,getOwnPropertyDescriptor:trap,getPrototypeOf:trap,ownKeys:trap});const d=diagnosis(a).d;assert.equal(d.reason,'array');assert.equal(d.actualType,'other');assert.deepEqual(Object.keys(d),['schema','field','reason','actualType']);assert.equal(calls,0);});
test('own length primitive never coerced; prototype length/iterator/value hooks unused',()=>{let calls=0;const a=[entry('fish')],proto=Object.create(Array.prototype);Object.defineProperty(proto,'length',{get(){calls++;throw Error('PRIVATE');}});proto[Symbol.iterator]=()=>{calls++;throw Error('PRIVATE');};Object.setPrototypeOf(a,proto);assertSet(diagnosis(a).d,1);const frozen=Object.freeze([entry('fish')]);assertSet(diagnosis(frozen).d,1,[1,0,0,0]);assert.equal(calls,0);});
test('earlier failure not supplanted and all non-cardinality errors keep exact4 fields',()=>{for(const raw of [{...baseEvidence(),schema_version:2,brands:[]},{...baseEvidence(),collector:null,brands:[]},{...baseEvidence(),brands:[entry('fish'),entry('fish')]},{...baseEvidence(),brands:[entry('fish'),{...entry('aristo'),falhas_24h:-1}]}]){let e;assert.throws(()=>D.validatePayload(raw,'fish'),x=>{e=x;return true;});const d=D.protocolDiagnostic(e);assert.deepEqual(Object.keys(d),['schema','field','reason','actualType']);assert.equal(d.brandSet,undefined);}assert.equal(diagnosis([], {schema_version:2}).d.field,'schema_version');});
test('two validated brands success equivalent, rejected length stays503 regardless metric values',()=>{for(const brand of ['fish','aristo'])assert.deepEqual(D.validatePayload(baseEvidence(),brand),O.validatePayload(baseEvidence(),brand));const d=diagnosis([entry('fish'),entry('aristo'),{...entry('other'),falhas_24h:-1}]).d;assertSet(d,3,[1,1,1,0]);});
test('authentic WeakMap snapshot immutable, mutated source and copied/forged errors unavailable',()=>{const a=[entry('fish')],{error,d}=diagnosis(a);a[0].marca='aristo';a.push(entry('aristo'));assertSet(d,1,[1,0,0,0]);assert.equal(D.protocolDiagnostic(error),d);assert.equal(D.protocolDiagnostic({...error}),null);assert.equal(D.protocolDiagnostic(new Error('HEALTH_PROTOCOL_REFUSED')),null);assert.equal(D.protocolDiagnostic({code:'HEALTH_PROTOCOL_REFUSED',diagnostic:d}),null);});
test('synthetic core read fails once, closes and returns only frozen safe diagnosis',async()=>{const f=fixture({evidence:{brands:[entry('fish')]}});await assert.rejects(inspect(f),e=>{assertSet(D.protocolDiagnostic(e),1,[1,0,0,0]);return true;});assert.equal(f.calls.filter(q=>q===D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);await f.service.close();});
for(const opt of ['endThrow','noEndEvent','endHang'])test('close '+opt+' vetoes brandSet publication and blocks another read',async()=>{const X=accelerated(),f=fixture({D:X.D,evidence:{brands:[]},[opt]:true});await assert.rejects(inspect(f),e=>{assert.notEqual(e.code,'HEALTH_PROTOCOL_REFUSED');assert.equal(X.D.protocolDiagnostic(e),null);return true;});assert.equal(f.calls.filter(q=>q===X.D.READ_SQL).length,1);assert.equal(f.clients[0].ends,1);await assert.rejects(inspect(f));await f.service.close().catch(()=>{});});
function controllerFixture(options={}){
 const mod={exports:{}};new Function('require','module','exports',fs.readFileSync(path.join(sourceRoot,'inputs/services/dashboard-operational/native-delivery-health-controller.cjs'),'utf8'))(name=>name==='./native-delivery-health.cjs'?D:require(name),mod,mod.exports);
 const f=fixture({evidence:{brands:[]},...options}),connectionId='11111111-1111-4111-8111-111111111111',ownerId='original-master',consents=new Map();
 const profile={schema:'shrigma-private-database-credential-v1',revision:1,ownerId,username:'fixture_reader',password,resource:{...D.RESOURCE},transport:{mode:'admitted-private-network'}};
 const store={deliveryHealthOwner:()=>({ownerId,ownerRevision:'1'.repeat(64)}),permitDeliveryHealth:({binding})=>consents.set(binding.brand,binding),deliveryHealthConsent:({brand})=>{if(!consents.has(brand))throw Error('CONSENT_REQUIRED');return consents.get(brand);},authenticate:()=>({id:connectionId,brands:['fish','aristo']}),list:()=>[]};
 const auth={nativeConnections:store,nativeDatabaseVault:{getPrivateCredential:()=>profile},ownMasterPublishedJourneyReadBinding:(context,{brand})=>{assert.equal(context.method,'GET');return {userId:ownerId,binding:(brand==='fish'?'2':'3').repeat(64),credential:'SYNTHETIC_CRM_SECRET'};}};
 const controller=mod.exports.createDeliveryHealthController({enabled:true,driver:f.args.driver,auth});controller.authorize({context:{method:'POST'},connectionId,brand:'fish',consent:true});
 return {controller,f,context:{nativeBearer:'synthetic-native',method:'GET'}};
}
test('current sealed controller forwards authentic503 brandSet receipt, repeat receipt is no SQL retry',async()=>{const h=controllerFixture(),r=await h.controller.nativeReadReceipt({context:h.context,brand:'fish'});assert.equal(r.status,503);assert.equal(r.body.error,'HEALTH_PROTOCOL_REFUSED');assertSet(r.body.diagnostic,0,[0,0,0,0]);assert.equal(await h.controller.nativeReadReceipt({context:h.context,brand:'fish'}),r);assert.equal(h.f.calls.filter(q=>q===D.READ_SQL).length,1);assert.equal(h.f.clients[0].ends,1);assert(!JSON.stringify(r).includes('SYNTHETIC'));await h.controller.close();});
test('controller close fault never publishes brandSet receipt or retries',async()=>{const h=controllerFixture({endThrow:true}),r=await h.controller.nativeReadReceipt({context:h.context,brand:'fish'});assert.equal(r.status,503);assert.equal(r.body.error,'HEALTH_CLOSE_FAILED');assert.equal(r.body.diagnostic,undefined);await h.controller.nativeReadReceipt({context:h.context,brand:'fish'});assert.equal(h.f.calls.filter(q=>q===D.READ_SQL).length,1);await h.controller.close().catch(()=>{});});

test('64 fully closed counters mix known/other/malformed; malformed marca proxies never coerced',()=>{let calls=0;const proxy=new Proxy({}, {get(){calls++;assert.fail('marca proxy');},getPrototypeOf(){calls++;assert.fail('marca prototype');}});const values=Array.from({length:64},(_,i)=>entry(['fish','aristo','UNKNOWN_PRIVATE',proxy][i%4]));assertSet(diagnosis(values).d,64,[16,16,16,16]);assert.equal(calls,0);assert(!JSON.stringify(diagnosis(values).d).includes('UNKNOWN_PRIVATE'));});
test('late unsafe descriptor suppresses already-counted prefix, never partial counts',()=>{const last=entry('aristo');Object.defineProperty(last,'marca',{get(){assert.fail('getter');},enumerable:true});assertSet(diagnosis([entry('fish'),entry('fish'),last]).d,3);});
test('source array iterator/valueOf hooks do not run; extras yield unavailable',()=>{let calls=0;const values=[entry('fish')];values[Symbol.iterator]=()=>{calls++;throw Error('PRIVATE');};values.valueOf=()=>{calls++;throw Error('PRIVATE');};assertSet(diagnosis(values).d,1);assert.equal(calls,0);const source=fs.readFileSync(path.join(runtime,'native-delivery-health.cjs'),'utf8');const helper=source.slice(source.indexOf('function rejectedBrandSet'),source.indexOf('function protocolRefused'));assert.doesNotMatch(helper,/for\s*\([^)]*\sof\s|JSON\.stringify|\.marca\b|Number\(length|String\(length/);});
