'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const source=process.env.DELIVERY_HEALTH_REFUSAL_SOURCE||path.resolve(__dirname,'sealed-refusal-inputs');
const runtime=process.env.DELIVERY_HEALTH_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const original=fs.readFileSync(path.join(source,'inputs/services/dashboard-operational/native-delivery-health-operator.cjs'),'utf8'),updated=fs.readFileSync(path.join(runtime,'native-delivery-health-operator.cjs'),'utf8');
function js(text){const a=text.indexOf(',JS=')+4,b=text.indexOf(';\nconst fail=',a);return JSON.parse(text.slice(a,b));}
const before=js(original),after=js(updated);
function section(text,start,end){return text.slice(text.indexOf(start),text.indexOf(end,text.indexOf(start)));}
test('five sealed inputs still match exact bytes and SHA256',()=>{const m=JSON.parse(fs.readFileSync(path.join(source,'inputs/INPUT-PINS.json')));assert.equal(m.files.length,5);for(const f of m.files){const b=fs.readFileSync(path.join(source,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);}});
test('server handler/API/HTML and complete strict status/DTO/render byte preserved',()=>{assert.equal(original.slice(0,original.indexOf(',JS=')),updated.slice(0,updated.indexOf(',JS=')));assert.equal(original.slice(original.indexOf('\nconst fail=')),updated.slice(updated.indexOf('\nconst fail=')));for(const [start,end] of [['function validDTO(', 'const value='],['function render(', 'async function action(']])assert.equal(section(before,start,end),section(after,start,end));assert.equal(before.slice(before.indexOf('connection.onchange=')),after.slice(after.indexOf('connection.onchange=')));});
test('request payloads/scopes/no retry and deadline preserved',()=>{for(const literal of ["{action:'authorize',...q,consent:true}:{action:'inspect',...q}","scope!=='crm.delivery-health'","credentials:'same-origin',cache:'no-store',redirect:'error'","'X-CSRF-Token':csrf","bytes>32768","disposed||e!==epoch||key(selected())!==k"])assert(after.includes(literal));assert.match(after,/setTimeout\(\(\)=>stop\('UI_REQUEST_TIMEOUT'\),70000\)/);assert.doesNotMatch(after,/setInterval|randomUUID|innerHTML|RegExp\(/);assert.match(after,/const allowedBackendCodes=new Set\(\[/);});

test('existing consent availability keeps all original DTO/render and explicit-read safeguards',()=>{assert.match(after,/authorizedBrands/);assert.match(after,/consented===key\(q\)/);assert.match(after,/case contraire|caso contrário/);assert.doesNotMatch(after,/request\([^;]+action:'authorize'[^;]+refresh/);});
