'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {HTML,JS}=require('./load-operator.cjs');
const {baseEvidence}=require('./fixture.cjs');
const id='11111111-1111-1111-1111-111111111111';
const status=()=>({schema:'shrigma-delivery-health-status-v1',enabled:true,databaseLinked:true,connections:[{id,label:'Minha conexão',brands:['fish','aristo'],authorizedBrands:[]}],operational:false});
const consent=()=>({authorized:true,scope:'crm.delivery-health',brand:'aristo',operational:false});
const dto=()=>{const v=baseEvidence(),{marca,...brandMetrics}=v.brands[1];return {schema:'shrigma-original-email-health-read-v1',brand:'aristo',checkedAt:'2026-10-08T20:00:00Z',sourceCheckedAt:v.checked_at,collector:v.collector,queue:v.queue,brandMetrics,pendingIngest15min:0,conflicts:0,sharedQueue:true,authorizesSend:false,authorizesRecovery:false,operational:false};};
function harness(handler){const nodes={},events={},calls=[],timers=new Map();let seq=0;
 class E{constructor(){this.value='';this.checked=false;this.disabled=false;this.children=[];this._text='';}set textContent(v){this._text=v;this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('\n');}append(x){this.children.push(x);if(!this.value)this.value=x.value;}replaceChildren(){this.children=[];this.value='';}}
 for(const match of HTML.matchAll(/id="([^"]+)"/g))nodes[match[1]]=new E();
 const response=(v,code=200)=>({ok:code===200,status:code,headers:{get:()=>null},body:{getReader(){let done=false;return {async read(){if(done)return {done:true};done=true;return {done:false,value:new TextEncoder().encode(JSON.stringify(v))};},async cancel(){}};}}});
 const context={document:{getElementById:id=>nodes[id],createElement:()=>new E()},window:{addEventListener:(n,f)=>events[n]=f},AbortController,TextDecoder,Date,JSON,Number,Set,Error,Promise,setTimeout:(f,n)=>{const id=++seq;timers.set(id,{f,n});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,options)=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,options,body});const custom=handler?.(body,url,response);if(custom!==undefined)return custom;return response(body?.action==='status'?status():body?.action==='authorize'?consent():body?.action==='inspect'?dto():{authenticated:true,user:{role:'superadmin'},csrf:'session-csrf'});}};
 nodes['health-brand'].value='aristo';vm.runInNewContext(JS,context);return {nodes,events,calls,timers,response,async settle(){await new Promise(resolve=>setImmediate(resolve));},async authorize(){await this.settle();nodes['health-agree'].checked=true;nodes['health-agree'].onchange();await nodes['health-authorize'].onclick();await this.settle();}};
}

test('standalone original page no secrets and aggregate caveat',()=>{assert.match(HTML,/Leitura agregada; execução e entrega por fluxo ainda exigem evidência própria/);assert.match(HTML,/WhatsApp/);assert.doesNotMatch(HTML,/password|textarea|name="key"/);new vm.Script(JS);assert.doesNotMatch(JS,/innerHTML|setInterval|randomUUID/);});
test('automatic session/status only, own consent CSRF and redirect refusal',async()=>{const h=harness();await h.settle();assert.deepEqual(h.calls.map(x=>x.body?.action||'session'),['session','status']);assert.equal(h.nodes['health-read'].disabled,true);await h.authorize();assert.equal(h.nodes['health-read'].disabled,false);assert.deepEqual(h.calls.at(-1).body,{action:'authorize',connectionId:id,brand:'aristo',consent:true});for(const c of h.calls){assert.equal(c.options.redirect,'error');assert.equal(c.options.cache,'no-store');assert.equal(c.options.credentials,'same-origin');}assert.equal(h.calls.at(-1).options.headers['X-CSRF-Token'],'session-csrf');});
test('one explicit query displays unknown and zero distinctly',async()=>{const h=harness();await h.authorize();await h.nodes['health-read'].onclick();assert.deepEqual(h.calls.at(-1).body,{action:'inspect',connectionId:id,brand:'aristo'});const text=h.nodes['health-result'].textContent;assert.match(text,/desconhecido/);assert.match(text,/Finalização pendente: 0/);assert.match(text,/compartilhada/);assert.match(text,/evidência própria/);assert.equal(h.calls.filter(x=>x.body?.action==='inspect').length,1);});
for(const trigger of ['brand','connection','reload','pagehide'])test(trigger+' cancels and suppresses pending result',async()=>{let resolve;const h=harness((b,u,r)=>{if(b?.action==='inspect')return new Promise(res=>resolve=()=>res(r(dto())));});await h.authorize();const pending=h.nodes['health-read'].onclick();await h.settle();const signal=h.calls.at(-1).options.signal;if(trigger==='brand')h.nodes['health-brand'].onchange();if(trigger==='connection')h.nodes['health-connection'].onchange();if(trigger==='reload')await h.nodes['health-reload'].onclick();if(trigger==='pagehide')h.events.pagehide();assert.equal(signal.aborted,true);resolve();await pending;await h.settle();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
for(const [name,mutate] of [['other brand',v=>v.brand='fish'],['extra PII',v=>v.email='private'],['unknown count',v=>v.brandMetrics.falhas_24h=null],['queue string',v=>v.queue.visible='0'],['authorizes send',v=>v.authorizesSend=true]])test('UI refuses '+name,async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const v=dto();mutate(v);return r(v);}});await h.authorize();await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-authorize'].disabled,true);});
test('revocation 403 clears confirmed evidence and consent',async()=>{let revoke=false;const h=harness((b,u,r)=>b?.action==='inspect'&&revoke?r({},403):undefined);await h.authorize();await h.nodes['health-read'].onclick();assert.notEqual(h.nodes['health-result'].textContent,'');revoke=true;await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
test('bounded deadline aborts no retry; reload available',async()=>{const h=harness(b=>b?.action==='inspect'?new Promise(()=>{}):undefined);await h.authorize();const pending=h.nodes['health-read'].onclick();await h.settle();const timer=[...h.timers.values()][0];assert.equal(timer.n,70000);timer.f();await pending;assert.equal(h.calls.filter(x=>x.body?.action==='inspect').length,1);assert.equal(h.nodes['health-reload'].disabled,false);assert.equal(h.calls.at(-1).options.signal.aborted,true);});
test('oversized stream rejected; labels text only',async()=>{const h=harness((b,u,r)=>{if(b?.action==='status'){const v=status();v.connections[0].label='<img onerror=alert(1)>';return r(v);}if(b?.action==='inspect'){const v=r(dto());v.body.getReader=()=>({read:async()=>({done:false,value:new Uint8Array(32769)}),cancel:async()=>{}});return v;}});await h.authorize();assert.equal(h.nodes['health-connection'].children[0].textContent,'<img onerror=alert(1)>');await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');});
test('missing database no actions and reload clears confirmed data',async()=>{const h=harness();await h.authorize();await h.nodes['health-read'].onclick();await h.nodes['health-reload'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);const unlinked=harness((b,u,r)=>{if(b?.action==='status')return r({...status(),databaseLinked:false});});await unlinked.settle();unlinked.nodes['health-agree'].checked=true;unlinked.nodes['health-agree'].onchange();assert.equal(unlinked.nodes['health-authorize'].disabled,true);});

for(const [name,mutate] of [['invalid source calendar',v=>v.sourceCheckedAt='2026-02-30T12:00:00Z'],['error code array',v=>v.collector.last_error_code=['ERROR']],['collector extra',v=>v.collector.customerId='PII']])test('strict UI '+name,async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const v=dto();mutate(v);return r(v);}});await h.authorize();await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});

function nonJson(response,http,text){const r=response({},http);r.body.getReader=()=>{let done=false;return {async read(){if(done)return {done:true};done=true;return {done:false,value:new TextEncoder().encode(text)};},async cancel(){}};};return r;}
for(const action of ['authorize','inspect'])for(const [http,code] of [[409,'DELIVERY_HEALTH_BINDING_CHANGED'],[503,'HEALTH_ADMISSION_REFUSED'],[403,'NATIVE_HEALTH_CONSENT_REQUIRED']])test(action+' safely identifies '+http+' '+code,async()=>{const h=harness((b,u,r)=>b?.action===action?r({error:code,message:'RAW SQL password private@example.invalid'},http):undefined);if(action==='inspect')await h.authorize();else{await h.settle();h.nodes['health-agree'].checked=true;h.nodes['health-agree'].onchange();}await h.nodes[action==='authorize'?'health-authorize':'health-read'].onclick();const text=h.nodes['health-message'].textContent;assert.match(text,new RegExp(action==='authorize'?'Falha ao autorizar':'Falha ao consultar'));assert.match(text,new RegExp('HTTP '+http));assert.match(text,new RegExp('Código do servidor: '+code));assert.doesNotMatch(text,/RAW SQL|password|private@/);assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-authorize'].disabled,true);assert.equal(h.calls.filter(x=>x.body?.action===action).length,1);if(http===403)assert.match(h.nodes['health-status'].textContent,/Sessão/);});
for(const [name,body] of [['unknown',{error:'HEALTH_ARBITRARY_PRIVATE_VALUE'}],['raw',{error:'SELECT password FROM private_table'}],['nested',{error:{code:'HEALTH_OFF',private:'secret'}}],['array',[{error:'HEALTH_OFF'}]],['missing',{message:'<html>password</html>'}],['null',null]])test('HTTP unknown/malformed '+name+' yields only fixed local fallback',async()=>{const h=harness((b,u,r)=>b?.action==='inspect'?r(body,502):undefined);await h.authorize();await h.nodes['health-read'].onclick();const text=h.nodes['health-message'].textContent;assert.match(text,/HTTP 502/);assert.match(text,/Código local: UI_HTTP_REFUSED/);assert.doesNotMatch(text,/PRIVATE_VALUE|SELECT|private_table|password|<html>|secret|HEALTH_OFF/);assert.equal(h.nodes['health-result'].textContent,'');});
test('HTTP HTML body and HTTP403 malformed preserve local fallback and lock',async()=>{for(const http of [500,403]){const h=harness((b,u,r)=>b?.action==='inspect'?nonJson(r,http,'<html>SQL private key</html>'):undefined);await h.authorize();await h.nodes['health-read'].onclick();assert.match(h.nodes['health-message'].textContent,new RegExp('HTTP '+http+'. Código local: UI_HTTP_REFUSED'));assert.doesNotMatch(h.nodes['health-message'].textContent,/SQL|private|<html>/);assert.equal(h.nodes['health-read'].disabled,true);if(http===403)assert.match(h.nodes['health-status'].textContent,/Sessão/);}});
for(const declared of [false,true])test('non2xx oversized '+(declared?'header':'stream')+' bounded and safe',async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const x=nonJson(r,503,'x'.repeat(32769));if(declared)x.headers.get=()=>32769;return x;}});await h.authorize();await h.nodes['health-read'].onclick();assert.match(h.nodes['health-message'].textContent,/HTTP 503. Código local: UI_RESPONSE_TOO_LARGE/);assert.equal(h.nodes['health-result'].textContent,'');});
test('200 malformed JSON and invalid DTO have HTTP200 local code, never backend refusal',async()=>{for(const bad of ['json','dto']){const h=harness((b,u,r)=>b?.action==='inspect'?(bad==='json'?nonJson(r,200,'{'):r({error:'HEALTH_OFF'},200)):undefined);await h.authorize();await h.nodes['health-read'].onclick();assert.match(h.nodes['health-message'].textContent,/HTTP 200. Código local: UI_RESPONSE_INVALID/);assert.doesNotMatch(h.nodes['health-message'].textContent,/Código do servidor|HEALTH_OFF/);assert.equal(h.nodes['health-result'].textContent,'');}});
test('200 invalid authorization cannot enable read or claim consent',async()=>{const h=harness((b,u,r)=>b?.action==='authorize'?r({authorized:true,scope:'wrong',brand:'aristo',operational:false}):undefined);await h.authorize();assert.match(h.nodes['health-message'].textContent,/Falha ao autorizar — consentimento não confirmado. HTTP 200. Código local: UI_RESPONSE_INVALID/);assert.equal(h.nodes['health-read'].disabled,true);});
for(const action of ['authorize','inspect'])test(action+' local timeout is distinct from backend HEALTH_TIMEOUT, no retry',async()=>{const h=harness(b=>b?.action===action?new Promise(()=>{}):undefined);if(action==='inspect')await h.authorize();else{await h.settle();h.nodes['health-agree'].checked=true;h.nodes['health-agree'].onchange();}const pending=h.nodes[action==='authorize'?'health-authorize':'health-read'].onclick();await h.settle();[...h.timers.values()][0].f();await pending;assert.match(h.nodes['health-message'].textContent,/Código local: UI_REQUEST_TIMEOUT/);assert.match(h.nodes['health-message'].textContent,/HTTP indisponível/);assert.equal(h.calls.filter(x=>x.body?.action===action).length,1);assert.equal(h.nodes['health-read'].disabled,true);const returned=harness((b,u,r)=>b?.action==='inspect'?r({error:'HEALTH_TIMEOUT'},503):undefined);await returned.authorize();await returned.nodes['health-read'].onclick();assert.match(returned.nodes['health-message'].textContent,/Código do servidor: HEALTH_TIMEOUT/);});
for(const trigger of ['brand','connection','reload','pagehide'])test('late refused403 suppressed after '+trigger,async()=>{let resolve;const h=harness((b,u,r)=>b?.action==='inspect'?new Promise(res=>resolve=()=>res(r({error:'NATIVE_AUTH_REQUIRED'},403))):undefined);await h.authorize();const pending=h.nodes['health-read'].onclick();await h.settle();if(trigger==='brand')h.nodes['health-brand'].onchange();if(trigger==='connection')h.nodes['health-connection'].onchange();if(trigger==='reload')await h.nodes['health-reload'].onclick();if(trigger==='pagehide')h.events.pagehide();resolve();await pending;await h.settle();assert.equal(h.nodes['health-message'].textContent,'');assert.equal(h.nodes['health-result'].textContent,'');assert.doesNotMatch(h.nodes['health-status'].textContent,/Sessão/);assert.equal(h.calls.filter(x=>x.body?.action==='inspect').length,1);});
test('late authorization refusal cancelled on brand change never marks consent',async()=>{let resolve;const h=harness((b,u,r)=>b?.action==='authorize'?new Promise(res=>resolve=()=>res(r({error:'DELIVERY_HEALTH_BINDING_CHANGED'},409))):undefined);await h.settle();h.nodes['health-agree'].checked=true;h.nodes['health-agree'].onchange();const pending=h.nodes['health-authorize'].onclick();await h.settle();h.nodes['health-brand'].onchange();resolve();await pending;assert.equal(h.nodes['health-message'].textContent,'');assert.equal(h.nodes['health-read'].disabled,true);});
test('transport raw error text never displayed',async()=>{const h=harness(b=>{if(b?.action==='inspect')throw Error('password SQL https://private.invalid');});await h.authorize();await h.nodes['health-read'].onclick();assert.match(h.nodes['health-message'].textContent,/Código local: UI_TRANSPORT_FAILED/);assert.doesNotMatch(h.nodes['health-message'].textContent,/password|SQL|https:/);});

test('invalid successful response reports actual received HTTP201 rather than guessed200',async()=>{const h=harness((b,u,r)=>{if(b?.action==='inspect'){const x=r({},201);x.ok=true;return x;}});await h.authorize();await h.nodes['health-read'].onclick();assert.match(h.nodes['health-message'].textContent,/HTTP 201. Código local: UI_RESPONSE_INVALID/);});


test('reload uses only CURRENT existing brand consent; no consent POST or health query on load',async()=>{const h=harness((b,u,r)=>b?.action==='status'?r({...status(),connections:[{...status().connections[0],authorizedBrands:['aristo']}]}):undefined);await h.settle();assert.equal(h.nodes['health-read'].disabled,false);assert.deepEqual(h.calls.map(c=>c.body?.action||'session'),['session','status']);await h.nodes['health-read'].onclick();assert.equal(h.calls.filter(c=>c.body?.action==='inspect').length,1);assert.equal(h.calls.filter(c=>c.body?.action==='authorize').length,0);h.nodes['health-brand'].value='fish';h.nodes['health-brand'].onchange();assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-result'].textContent,'');});
test('availability with no prior consent cannot enable health read',async()=>{const h=harness();await h.settle();assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.calls.filter(c=>c.body?.action==='authorize'||c.body?.action==='inspect').length,0);});
for(const authorizedBrands of [['other'],['aristo','aristo'],'aristo',null])test('invalid existing-consent indicator fails closed '+JSON.stringify(authorizedBrands),async()=>{const h=harness((b,u,r)=>b?.action==='status'?r({...status(),connections:[{...status().connections[0],authorizedBrands}]}):undefined);await h.settle();assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-authorize'].disabled,true);});
test('CURRENT revoked consent after reload refuses explicit read and never authorizes again',async()=>{const h=harness((b,u,r)=>b?.action==='status'?r({...status(),connections:[{...status().connections[0],authorizedBrands:['aristo']}]}):b?.action==='inspect'?r({error:'NATIVE_HEALTH_CONSENT_REQUIRED'},403):undefined);await h.settle();await h.nodes['health-read'].onclick();assert.equal(h.nodes['health-read'].disabled,true);assert.equal(h.nodes['health-result'].textContent,'');assert.equal(h.calls.filter(c=>c.body?.action==='authorize').length,0);assert.equal(h.calls.filter(c=>c.body?.action==='inspect').length,1);assert.match(h.nodes['health-message'].textContent,/NATIVE_HEALTH_CONSENT_REQUIRED/);});
