 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {HTML,JS}=require('../../services/dashboard-operational/native-source-diagnostics-ui.cjs');
const id='11111111-1111-1111-1111-111111111111',opid='22222222-2222-2222-2222-222222222222';
const status=()=>({schema:'shrigma-source-diagnostics-status-v1',enabled:true,sourceLinked:true,databaseLinked:true,connections:[{id:'connection',label:'Minha conexão',brands:['aristo'],diagnosticsAuthorized:true}],attempts:[{brand:'aristo',requestId:id,operationId:opid,state:'chunk_uncertain'}],operational:false});
const consent=()=>({authorized:true,scope:'crm.source-diagnostics',brand:'aristo',requestId:id,operationId:opid,operational:false});
const dto=()=>({schema:'shrigma-source-commit-diagnostics-v1',resource:{project:'comunicacao',service:'postgres',host:'comunicacao_postgres',port:5432,database:'listmonk',network:'easypanel'},operation:{operationFound:true,operationId:opid,brand:'aristo',originalState:'chunk_uncertain',nextChunk:35,totalChunks:35,lastAttemptIndex:34,storedChunks:35,storedPrefixChunks:35,lastAttemptStored:true,lastAttemptHashMatches:true,productBatchReady:true,originalErrorCode:null,originalUpdatedAt:'2026-10-08T12:00:00.123456Z',completedByOriginal:false},checkedAt:'2026-10-08T12:01:00.000Z',authorizesRecovery:false,authorizesAudienceRefresh:false,operational:false});
function harness(handler){const nodes={},events={},calls=[],timers=new Map();let seq=0;
 class E{constructor(){this.value='';this.checked=false;this.disabled=false;this.children=[];this._text='';}set textContent(v){this._text=v;this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('\n');}append(x){this.children.push(x);if(!this.value)this.value=x.value;}replaceChildren(){this.children=[];this.value='';}}
 for(const match of HTML.matchAll(/id="([^"]+)"/g))nodes[match[1]]=new E();
 const response=(v,code=200)=>({ok:code===200,status:code,headers:{get:()=>null},body:{getReader(){let done=false;return {async read(){if(done)return {done:true};done=true;return {done:false,value:new TextEncoder().encode(JSON.stringify(v))};},async cancel(){}};}}});
 const context={document:{getElementById:id=>nodes[id],createElement:()=>new E()},window:{addEventListener:(n,f)=>events[n]=f},AbortController,TextDecoder,Date,JSON,Number,Set,Error,Promise,setTimeout:(f,n)=>{const id=++seq;timers.set(id,{f,n});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,options)=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,options,body});const custom=handler?.(body,url,response);if(custom!==undefined)return custom;return response(body?.action==='diagnostics-status'?status():body?.action==='authorize-diagnostics'?consent():body?.action==='diagnose'?dto():{authenticated:true,user:{role:'superadmin'},csrf:'session-csrf'});}};
 vm.runInNewContext(JS,context);return {nodes,events,calls,timers,response,async settle(){await new Promise(resolve=>setImmediate(resolve));},async authorize(){await this.settle();nodes['diag-agree'].checked=true;nodes['diag-agree'].onchange();await nodes['diag-authorize'].onclick();await this.settle();}};
}
test('HTML usable independent section and no secret/editor fields',()=>{assert.match(HTML,/section/);assert.match(HTML,/READ/);assert.doesNotMatch(HTML,/password|name="key"|canvas|textarea/);assert.equal(new Set([...HTML.matchAll(/id="([^"]+)"/g)].map(x=>x[1])).size,[...HTML.matchAll(/id="/g)].length);new vm.Script(JS);});
test('only status automatic; existing authorization never bypasses separate consent',async()=>{const h=harness();await h.settle();assert.deepEqual(h.calls.map(x=>x.body?.action||'session'),['session','diagnostics-status']);assert.equal(h.nodes['diag-read'].disabled,true);await h.authorize();assert.equal(h.nodes['diag-read'].disabled,false);const c=h.calls.at(-1);assert.deepEqual(c.body,{action:'authorize-diagnostics',connectionId:'connection',brand:'aristo',requestId:id,consent:true});assert.equal(c.options.headers['X-CSRF-Token'],'session-csrf');});
test('READ exact request and original uncertainty never completed by counts/hash/ready',async()=>{const h=harness();await h.authorize();await h.nodes['diag-read'].onclick();assert.deepEqual(h.calls.at(-1).body,{action:'diagnose',connectionId:'connection',brand:'aristo',requestId:id});const text=h.nodes['diag-result'].textContent;assert.match(text,/Prefixo confirmado: 35/);assert.match(text,/presente/);assert.match(text,/compatíveis/);assert.match(text,/Conclusão não confirmada/);assert.doesNotMatch(text,/listmonk|postgres|22222222|chunk_uncertain/);});
for(const [name,mutate,expected] of [['absent',d=>{d.operation.lastAttemptStored=false;d.operation.lastAttemptHashMatches=null;},'ausente'],['mismatch',d=>d.operation.lastAttemptHashMatches=false,'incompatíveis'],['unknown',d=>{d.operation.lastAttemptIndex=null;d.operation.lastAttemptStored=false;d.operation.lastAttemptHashMatches=null;},'desconhecido'],['completed',d=>{d.operation.originalState='completed';d.operation.completedByOriginal=true;},'Conclusão confirmada exclusivamente']])test(name+' evidence render',async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnose'){const d=dto();mutate(d);return r(d);}});await h.authorize();await h.nodes['diag-read'].onclick();assert.match(h.nodes['diag-result'].textContent,new RegExp(expected));});
for(const [name,mutate] of [['wrong operation',d=>d.operation.operationId=id],['forged completion',d=>d.operation.completedByOriginal=true],['invalid count',d=>d.operation.storedPrefixChunks=51],['effects',d=>d.authorizesRecovery=true],['extra',d=>d.secret='hidden'],['operation extra',d=>d.operation.schema='shrigma-original-last-chunk-read-v1']])test('reject '+name,async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnose'){const d=dto();mutate(d);return r(d);}});await h.authorize();await h.nodes['diag-read'].onclick();assert.equal(h.nodes['diag-result'].textContent,'');assert.equal(h.nodes['diag-read'].disabled,true);assert.match(h.nodes['diag-message'].textContent,/incerta/);});
test('not found is unknown rather than absence/completion',async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnose'){const d=dto();for(const k of Object.keys(d.operation))d.operation[k]=null;d.operation.operationFound=false;d.operation.completedByOriginal=false;return r(d);}});await h.authorize();await h.nodes['diag-read'].onclick();assert.match(h.nodes['diag-result'].textContent,/desconhecidos/);});
for(const trigger of ['selection','reload','pagehide'])test(trigger+' invalidates pending result',async()=>{let resolve;const h=harness((b,u,r)=>{if(b?.action==='diagnose')return new Promise(res=>resolve=()=>res(r(dto())));});await h.authorize();const pending=h.nodes['diag-read'].onclick();await h.settle();if(trigger==='selection')h.nodes['diag-attempt'].onchange();if(trigger==='reload')await h.nodes['diag-reload'].onclick();if(trigger==='pagehide')h.events.pagehide();resolve();await pending;await h.settle();assert.equal(h.nodes['diag-result'].textContent,'');assert.equal(h.nodes['diag-read'].disabled,true);});
test('session failure clears evidence and disables action',async()=>{let deny=false;const h=harness((b,u,r)=>{if(b?.action==='diagnose'&&deny)return r({},403);});await h.authorize();await h.nodes['diag-read'].onclick();deny=true;await h.nodes['diag-read'].onclick();assert.equal(h.nodes['diag-result'].textContent,'');assert.equal(h.nodes['diag-read'].disabled,true);assert.match(h.nodes['diag-status'].textContent,/Sessão/);});
test('deadline releases busy without retry or new UUID',async()=>{const h=harness((b)=>{if(b?.action==='diagnose')return new Promise(()=>{});});await h.authorize();const pending=h.nodes['diag-read'].onclick();await h.settle();assert.equal(h.nodes['diag-read'].disabled,true);const timers=[...h.timers.values()];assert.equal(timers[0].n,70000);timers[0].f();await pending;assert.equal(h.nodes['diag-reload'].disabled,false);assert.equal(h.calls.filter(x=>x.body?.action==='diagnose').length,1);assert.match(h.nodes['diag-message'].textContent,/mesma tentativa/);assert.doesNotMatch(JS,/randomUUID|action:'run'|action:'inspect'|action:'recover'|setInterval/);});
test('oversized streamed response rejected',async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnose'){const x=r(dto());x.body.getReader=()=>({read:async()=>({done:false,value:new Uint8Array(32769)}),cancel:async()=>{}});return x;}});await h.authorize();await h.nodes['diag-read'].onclick();assert.equal(h.nodes['diag-result'].textContent,'');});
for(const prop of ['enabled','sourceLinked','databaseLinked'])test('missing '+prop+' blocks consent/read',async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnostics-status'){const s=status();s[prop]=false;return r(s);}});await h.settle();h.nodes['diag-agree'].checked=true;h.nodes['diag-agree'].onchange();assert.equal(h.nodes['diag-authorize'].disabled,true);assert.equal(h.nodes['diag-read'].disabled,true);});
test('labels rendered as text; user display avoids infrastructure IDs',async()=>{const h=harness((b,u,r)=>{if(b?.action==='diagnostics-status'){const s=status();s.connections[0].label='<img onerror=alert(1)>';return r(s);}});await h.settle();assert.equal(h.nodes['diag-connection'].children[0].textContent,'<img onerror=alert(1)>');assert.doesNotMatch(JS,/innerHTML/);});

test('reload discards previously confirmed evidence and consent',async()=>{const h=harness();await h.authorize();await h.nodes['diag-read'].onclick();assert.notEqual(h.nodes['diag-result'].textContent,'');await h.nodes['diag-reload'].onclick();assert.equal(h.nodes['diag-result'].textContent,'');assert.equal(h.nodes['diag-read'].disabled,true);});
