'use strict';
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),{EventEmitter}=require('node:events');
const base=path.resolve(__dirname,'../../../..'),kernelDir=process.env.PG_PROVIDER_SOURCE_MODE==='candidate'?path.resolve(process.env.PG_PROVIDER_SOURCE_ROOT,'services/dashboard-operational/native-installer'):path.join(base,'c2-installer/v2/files/services/dashboard-operational/native-installer'),productDir=path.resolve(__dirname,'../../services/dashboard-operational/native-installer');
// Public fixed V2 source/model input only; no historical test suite execution.
const modelPath=process.env.PG_PROVIDER_SOURCE_MODE==='candidate'?path.resolve(process.env.PG_PROVIDER_SOURCE_ROOT,'tests/native-installer/model.cjs'):path.join(base,'c2-installer/v2/files/tests/native-installer/model.cjs');if(require('node:crypto').createHash('sha256').update(fs.readFileSync(modelPath)).digest('hex')!=='3a8167bb4eab251cd92c4385bd70fc9c9cc05669e6f4260caaca65eff6460cc9')throw Error('MODEL_INPUT_REFUSED');const M=require(modelPath);
const peer="SELECT current_database() AS database,session_user::text AS session_role,current_user::text AS current_role,pg_backend_pid() AS pid,inet_server_port() AS port,current_setting('server_version_num')::integer AS engine,(SELECT ssl FROM pg_stat_ssl WHERE pid=pg_backend_pid()) AS ssl";
const P=JSON.parse(fs.readFileSync(productDir+'/provider-pins.json','utf8')),files=new Set(P.files.map(x=>x.path));
function moduleFor(){const f=productDir+'/pg-session-provider.cjs',m=new Module(f,module);m.filename=f;m.paths=Module._nodeModulePaths(productDir);const map=p=>typeof p==='string'&&p.startsWith(productDir+'/')&&files.has(p.slice(productDir.length+1))?kernelDir+'/'+p.slice(productDir.length+1):p;
 const readFS={readFileSync:(...a)=>fs.readFileSync(map(a[0]),...a.slice(1)),lstatSync:(...a)=>fs.lstatSync(map(a[0]),...a.slice(1)),realpathSync:p=>map(p)!==p?p:fs.realpathSync(p)};
 m.require=name=>{if(name==='node:fs')return readFS;if(['./installer.cjs','./sql.cjs','./catalog.cjs'].includes(name))return require(kernelDir+'/'+name.slice(2));if(['node:path','node:crypto','node:async_hooks'].includes(name))return require(name);throw Error('UNADMITTED_IMPORT');};m._compile(fs.readFileSync(f,'utf8'),f);return m.exports;
}
function fixture({queryHook,connectHook,endHook,peerChange}={}){const db=M.database(),clients=[],requests=[];let profile={schema:'shrigma-private-pg-installer-profile-v1',profileRef:'a'.repeat(64),revision:1,resource:P.resource,target:M.target,password:'synthetic-not-production',transport:{mode:'admitted-private-network'},driver:{version:'8.13.1',packageSha256:'b'.repeat(64)},mode:'installer-exclusive',originalOperationId:null};let revoked=false;
 class Client extends EventEmitter{constructor(config){super();this.config=config;this.connection=new EventEmitter();this.connection.stream={encrypted:!!config.ssl,authorized:!!config.ssl};this.processID=100+clients.length;this.model=M.client(db);this.queryCalls=[];this.connectCalls=0;this.endCalls=0;this.status='I';clients.push(this);}async connect(){this.connectCalls++;if(connectHook)await connectHook(this);this.connection.emit('readyForQuery',{status:'I'});}async end(){this.endCalls++;if(endHook)await endHook(this);this.emit('end');}async query(text,params){this.queryCalls.push({text,params});try{if(queryHook){const h=await queryHook(this,text,params);if(h!==undefined)return h;}let r;if(text===peer){const v={database:'listmonk',session_role:M.target.installerRole,current_role:M.target.installerRole,pid:this.processID,port:5432,engine:170011,ssl:!!this.config.ssl};if(peerChange)peerChange(v,this);r=M.result('SELECT',[v]);}else r=await this.model.withInstallerSession(()=>this.model.raw.query(text,params));if(text===M.S.BEGIN_READ||text===M.S.BEGIN_WRITE)this.status='T';if(text==='COMMIT'||text==='ROLLBACK')this.status='I';this.connection.emit('readyForQuery',{status:this.status});return r;}catch(e){this.status='E';this.connection.emit('readyForQuery',{status:'E'});if(/^[0-9A-Z]{5}$/.test(e?.code||''))e.severity='ERROR';throw e;}}}
 const driver={Client,version:'8.13.1',packageSha256:'b'.repeat(64)},getPrivateProfile=async()=>profile,getRealAdmission=async i=>{requests.push(i);if(revoked)throw Error('synthetic-secret');if(i.phase==='migration'){const proof=await M.admission(i.kernel);const {kernel,pid,...r}=i;return {...r,admitted:true,kernelProof:proof};}const {previousOperationId,...r}=i;return {...r,admitted:true};};const Provider=moduleFor();const create=extra=>Provider.createPGSessionProvider({enabled:true,driver,getPrivateProfile,getRealAdmission,...extra});
 return {M,P,db,clients,requests,driver,Provider,create,getPrivateProfile,getRealAdmission,get profile(){return profile;},setProfile:p=>profile=p,revoke:()=>revoked=true};}
module.exports={fixture,M,peer};
