'use strict';
// Local preparation or explicit manual observer. No actions on import/default.
const H=require('./recovery.cjs');
const ERROR='READ_MANUAL_ENTRY_REFUSED';
function refuse(){throw Error(ERROR);}
function exact(q,ks){if(!q||Object.getPrototypeOf(q)!==Object.prototype||Reflect.ownKeys(q).length!==ks.length)refuse();for(const k of ks){const d=Object.getOwnPropertyDescriptor(q,k);if(!d?.enumerable||!Object.hasOwn(d,'value'))refuse();}}
function tty(){if(process.stdin.isTTY!==true)refuse();const text=require('node:child_process').execFileSync('stty',['-a'],{stdio:[process.stdin.fd,'pipe','pipe'],timeout:1000,maxBuffer:8192}).toString().split(/[;\s]+/);if(!text.includes('-echo')||!text.includes('-icanon')||text.includes('echo')||text.includes('icanon'))refuse();}
function write(q){process.stdout.write(JSON.stringify(q)+'\n');}
function bootstrap(plan){
 tty();return new Promise((resolve,reject)=>{let chunks=[],size=0,done=false;const end=(error,v)=>{if(done)return;done=true;clearTimeout(timer);process.stdin.pause();process.stdin.removeListener('data',data);process.stdin.removeListener('end',stop);process.stdin.removeListener('error',stop);chunks=[];error?reject(Error(ERROR)):resolve(v);},stop=()=>end(true),data=b=>{try{if(typeof b==='string')refuse();size+=b.length;if(size>16384)refuse();chunks.push(b);if(!b.includes(10))return;const q=Buffer.concat(chunks,size);if(q.indexOf(10)!==q.length-1||q.at(-2)===13)refuse();const v=H.json(q.subarray(0,-1));exact(v,['schema','seq','mode','planSha256','adminPassword','servicePassword','serviceVerifier']);if(v.schema!=='crm-manager-read-private-bootstrap-v1'||v.seq!==0||v.mode!=='reconcile'||v.planSha256!==plan.planSha256||v.servicePassword!==null||v.serviceVerifier!==null||typeof v.adminPassword!=='string'||v.adminPassword.length<1||v.adminPassword.length>1024||/[\r\n\0\\']/.test(v.adminPassword))refuse();end(false,v);}catch{end(true);}};
  process.stdin.pause();process.stdin.on('data',data);process.stdin.once('end',stop);process.stdin.once('error',stop);const timer=setTimeout(stop,10000);write({schema:'crm-manager-read-manual-private-ready-v1',seq:0,planSha256:plan.planSha256,echoDisabled:true,canonicalDisabled:true});process.stdin.resume();
 });
}
function common(c){exact(c,['schema','plan','directory','custodyDirectory','publicKeyFile','privateKeyFile']);if(c.schema!=='crm-manager-read-manual-input-v1')refuse();const x=H.plans(c.plan),fs=require('node:fs'),path=require('node:path');const s=fs.lstatSync(c.directory);if(!s.isDirectory()||s.isSymbolicLink()||s.uid!==process.getuid()||(s.mode&0o7777)!==0o700||fs.realpathSync(c.directory)!==c.directory||path.resolve(c.directory)!==c.directory)refuse();return x;}
function preparePublic(c){
 const x=common(c),fs=require('node:fs'),path=require('node:path');if(fs.readdirSync(c.directory).length)refuse();
 for(const p of['observer','observer/effects','observer/requests','target','target/effects','target/requests','target/postconditions'])fs.mkdirSync(path.join(c.directory,p),{mode:0o700});
 const observerScopes=H.observerScopes(x),reconcileFile={schema:'crm-manager-read-driver-plan-file-v1',stage:x.original.stage,reconcile:{suffix:c.plan.reconcileSuffix,domainId:c.plan.reconcileDomainId},planSha256:x.reconcile.planSha256};
 const saved={input:H.retain(path.join(c.directory,'input.json'),c),plan:H.retain(path.join(c.directory,'target/plan.json'),reconcileFile,524288),observerBootstrap:H.retain(path.join(c.directory,'observer-bootstrap.compose.json'),JSON.parse(observerScopes.observer.createPublicBootstrap.input.source.content)),observerProbe:H.retain(path.join(c.directory,'observer-probe.compose.json'),JSON.parse(observerScopes.observer.updatePublicProbe.input.content)),reconcileExecution:H.retain(path.join(c.directory,'reconcile-execution.compose.json'),JSON.parse(x.E.buildEasypanelInputs({remotePlan:x.reconcile}).updatePrivateSource.input.content)),observerScopes:H.retain(path.join(c.directory,'observer-scopes.json'),{queries:observerScopes.queries,mutations:observerScopes.mutations})};
 return{schema:'crm-manager-read-manual-preparation-v1',sourceOnly:true,observerPlanSha256:x.observer.planSha256,reconcilePlanSha256:x.reconcile.planSha256,intent:x.stage.intent,sourceVolume:x.stage.descriptor.compose.volumes.source.name,ledgerVolume:x.stage.descriptor.compose.volumes.ledger.name,observer:{projectName:x.observer.descriptor.projectName,serviceName:x.observer.descriptor.serviceName,host:x.observer.descriptor.domain.host,domainId:x.observer.descriptor.domain.id},reconcile:{projectName:x.reconcile.descriptor.projectName,serviceName:x.reconcile.descriptor.serviceName,host:x.reconcile.descriptor.domain.host,domainId:x.reconcile.descriptor.domain.id},saved};
}
async function observe(c){
 exact(c,['enabled','approved','inputFile','inputSha256','snapshotFile','snapshotSha256']);if(c.enabled!==true)return{schema:'crm-manager-read-manual-observation-result-v1',state:'disabled',postgresConnected:false};if(c.approved!==true)refuse();tty();const input=H.json(H.readPinned(c.inputFile,c.inputSha256,16384)),x=common(input),path=require('node:path');let bridge;
 const app=H.createObserver({enabled:true,approved:true,plan:input.plan,directory:path.join(input.directory,'observer'),custodyDirectory:input.custodyDirectory,privateKeyFile:input.privateKeyFile,snapshotFile:c.snapshotFile,snapshotSha256:c.snapshotSha256},{execute:f=>bridge.execute(f),observeStatus:q=>reader.observe(q)}),reader=x.S.createStatusReader({enabled:true,plan:x.observer});
 bridge=x.B.createStdioBridge({enabled:true,directory:path.join(input.directory,'observer/requests'),materialize:app.materialize,input:process.stdin,output:process.stdout,timeoutMs:45000});
 write({schema:'crm-manager-read-manual-observer-ready-v1',planSha256:x.observer.planSha256,echoDisabled:true,canonicalDisabled:true});
 try{return await app.run();}finally{bridge.close();process.stdin.pause();}
}
async function materializePrivate(c){
 exact(c,['enabled','readonlyApproved','inputFile','inputSha256','observationFile','observationSha256','snapshotFile','snapshotSha256']);if(c.enabled!==true||c.readonlyApproved!==true)refuse();
 const input=H.json(H.readPinned(c.inputFile,c.inputSha256,16384)),x=common(input),path=require('node:path'),fs=require('node:fs'),packet=await bootstrap(x.reconcile);
 const key=x.O.loadPrivateKey(input.privateKeyFile),held=x.O.openExisting({directory:input.custodyDirectory,intent:x.stage.intent,privateKey:key}),ep=x.E.buildEasypanelInputs({remotePlan:x.reconcile}),prior=x.E.buildEasypanelInputs({remotePlan:x.stage}),steps=Object.values(ep).filter(s=>s&&s.procedure),queries=steps.filter(s=>s.executor==='execute_query').map(s=>({procedure:s.procedure,input:s.input})),mutations=steps.filter(s=>s.executor!=='execute_query').map(s=>({procedure:s.procedure,input:s.input}));
 for(const k of['inspect','inspectRunning','inspectDomains'])queries.push({procedure:prior[k].procedure,input:prior[k].input});for(const k of['stop','clearEnvironment','deleteTestDomain'])mutations.push({procedure:prior[k].procedure,input:prior[k].input});
 const flags={READ_ACTIVATION_RUNTIME_OPT_IN:'1',READ_ACTIVATION_MODE:'reconcile',READ_ACTIVATION_APPROVED_ACTION:'readonly-reconcile',READ_ACTIVATION_ACTION:'stage',READ_ACTIVATION_OPERATION_ID:x.stage.intent.operationId,READ_CREDENTIAL_INTENT_ID:x.stage.intent.credentialIntentId,READ_ACTIVATION_FROM_PHASE:'empty'},pv=x.E.privateEnvInput({plan:ep,publicFlags:flags,verifier:held.verifier,adminPassword:packet.adminPassword}),privateArgs={procedure:pv.procedure,input:{...pv.input,env:pv.input.env}};if(!packet.adminPassword.isWellFormed()||Buffer.byteLength(JSON.stringify({schema:'read-stdio-request-v1',seq:999999,kind:'mcp',visibility:'private',executor:pv.executor,args:privateArgs}))>4096)refuse();mutations.push(privateArgs);if(queries.length!==7||mutations.length!==13)refuse();
 const binding={schema:'crm-manager-read-driver-scope-binding-v1',planSha256:x.reconcile.planSha256,mode:'reconcile',scopesSha256:H.hash(H.canonical({queries,mutations}))},vectors={queries:queries.map(q=>H.hash(H.canonical(q))),mutations:mutations.map(q=>H.hash(H.canonical(q)))};
 const originalObservation=H.json(H.readPinned(c.observationFile,c.observationSha256,16384)),snapshot=H.json(H.readPinned(c.snapshotFile,c.snapshotSha256,16384));H.admission(originalObservation,snapshot,x,Date.now());
 const target=path.join(input.directory,'target'),planFile=path.join(target,'plan.json'),planSha256=H.hash(fs.readFileSync(planFile)),startup={enabled:true,mode:'reconcile',stageApproved:false,readonlyReconcileApproved:true,planFile,planFileSha256:planSha256,publicKeyFile:input.publicKeyFile,privateKeyFile:input.privateKeyFile,custodyDirectory:input.custodyDirectory,effectsDirectory:path.join(target,'effects'),requestDirectory:path.join(target,'requests')};
 const config={enabled:true,readonlyApproved:true,coreFile:path.join(__dirname,'recovery.cjs'),coreSha256:H.hash(fs.readFileSync(path.join(__dirname,'recovery.cjs'))),plan:input.plan,observationFile:c.observationFile,observationSha256:c.observationSha256,snapshotFile:c.snapshotFile,snapshotSha256:c.snapshotSha256,custodyDirectory:input.custodyDirectory,privateKeyFile:input.privateKeyFile,binding,vectors,postconditionsDirectory:path.join(target,'postconditions')};
 const provider=require('./provider-template.cjs'),providerSource=provider.buildSource(config);provider.createProviders(config);
 const files={startup:H.retain(path.join(target,'startup.json'),startup)};
 const file=path.join(target,'provider.cjs'),bytes=Buffer.from(providerSource),fd=fs.openSync(file,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}const dfd=fs.openSync(target,fs.constants.O_RDONLY|fs.constants.O_DIRECTORY);try{fs.fsyncSync(dfd);}finally{fs.closeSync(dfd);}H.readPinned(file,H.hash(bytes),65536);files.provider={file,sha256:H.hash(bytes)};
 packet.adminPassword=null;
 // PRIVATE nested stdout capture only: includes env in exact scopes. Never text,
 // notify, log or write this return to an operator/public evidence file.
 return{schema:'crm-manager-read-manual-private-preparation-v1',files,binding,vectors,queries,mutations,planSha256:x.reconcile.planSha256};
}
async function main(){const a=process.argv.slice(2);if(a.length===0){write({schema:'crm-manager-read-manual-entry-v1',state:'disabled',postgresConnected:false});return;}if(a.length!==3||!['--prepare-public','--observe','--materialize-private'].includes(a[0]))refuse();const c=H.json(H.readPinned(a[1],a[2],16384)),result=a[0]==='--prepare-public'?preparePublic(c):a[0]==='--observe'?await observe(c):await materializePrivate(c);write(result);if(a[0]==='--observe')process.exitCode=result.state==='observed'?0:1;process.stdin.pause();}
if(require.main===module)main().catch(()=>{process.stderr.write(ERROR+'\n');process.exitCode=1;});
module.exports=Object.freeze({preparePublic,observe,materializePrivate});
