'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../../tools/organic-links-pg17-source/fixture.cjs'),{strict26,strictFocal}=require('../../tools/organic-links-pg17-source/tap.cjs'),G=require('../../tools/organic-links-pg17-source/gate.cjs'),pins=require('../../tools/organic-links-pg17-source/pins.json');
const good=()=>pins.expectedResults.map(name=>({name,ok:true}));
function setup(fault){const calls=[],clients=[];let n=0;const options={schema:'C2_SCHEMA',makeClient:()=>{const i=n++;if(fault==='constructor'&&i===1)throw Error('PRIVATE');let ready,error;const c={processID:i+1,connection:{on(_,fn){ready=fn;}},on(_,fn){error=fn;},async connect(){calls.push('connect'+i);if(fault==='partial-connect'&&i===1)throw Error('PRIVATE');ready({status:'I'});},async end(){calls.push('end'+i);if(fault==='cleanup'&&i===0)throw Error('PRIVATE');},async query(sql){calls.push(sql);if(sql==='SHOW server_version_num')return {command:'SHOW',rowCount:null,rows:[{server_version_num:fault==='major'&&i===1?'160015':'170011'}]};if(sql.startsWith('SELECT current_database'))return {command:'SELECT',rowCount:1,rows:[{database_name:fault==='database'?'production':'crm_borrowed_source_test',backend_pid:fault==='pid'?1:c.processID}]};if(fault==='ddl'&&sql==='C2_SCHEMA')throw Error('PRIVATE');return {command:'CREATE',rows:[],rowCount:null};},emitError(){error(Error('PRIVATE'));},setIdle(v){ready({status:v});}};clients.push(c);return c;},loadRunner:()=>{if(fault==='import')throw Error('PRIVATE');return {normalizer:{version:'1.0.2-proposed'},runAll:async args=>{assert.equal(args.clientA,clients[0]);assert.equal(args.clientB,clients[1]);calls.push('runner');if(fault==='runner')throw Error('PRIVATE');if(fault==='event')clients[0].emitError();if(fault==='idle')clients[0].setIdle('T');const r=good();if(fault==='partial-result')r.pop();if(fault==='duplicate')r[1]=r[0];if(fault==='not-ok')r[0].ok=false;return r;}};}};return {options,calls,clients};}
test('organic CI synthetic: constructor/connect/metadata/import/DDL/runner/partial result/cleanup failures always end constructed clients once',async()=>{for(const fault of [undefined,'constructor','partial-connect','major','database','pid','ddl','import','runner','event','idle','partial-result','duplicate','not-ok','cleanup']){const s=setup(fault),r=await R.runOwned(s.options);assert.equal(r.executed,fault===undefined);assert.equal(r.created,fault==='constructor'?1:2);assert.equal(r.endCalls,r.created);assert.equal(r.closed,r.created-(fault==='cleanup'?1:0));assert.equal(r.nativePG17Proof,false);assert.equal(r.fixtureScope,'injected-lifecycle-only');assert.equal(r.nativeNetworkAckProof,false);assert(!JSON.stringify(r).includes('PRIVATE'));for(let i=0;i<r.created;i++)assert.equal(s.calls.filter(c=>c==='end'+i).length,1);if(['major','database','pid','partial-connect','constructor'].includes(fault))assert(!s.calls.includes('C2_SCHEMA'));}});
test('organic CI source: exactly21 distinct original results are required',()=>{assert.equal(R.resultsOK(good()),true);for(const mutate of [r=>r.pop(),r=>r.push({name:'invented',ok:true}),r=>r[0].name='invented',r=>r[0].error='ignored failure',r=>r[0].ok=false,r=>r[1]=r[0]]){const r=good();mutate(r);assert.throws(()=>R.resultsOK(r));}});
const tap=()=>['TAP version 13',...Array.from({length:26},(_,i)=>'ok '+(i+1)+' - fixture '+i),'1..26','# tests 26','# pass 26','# fail 0','# cancelled 0','# skipped 0','# todo 0',''].join('\n');
test('organic CI TAP:26 pass/0fail/0skip strict; zero todo summary is allowed but directives/partial/duplicates fail',()=>{assert.equal(strict26(tap()).passed,26);const focal=['TAP version 13','ok 1 - first','ok 2 - second','ok 3 - third','1..3','# tests 3','# pass 3','# fail 0','# cancelled 0','# skipped 0','# todo 0'].join('\n');assert.equal(strictFocal(focal,3).passed,3);assert.throws(()=>strictFocal(focal,1));for(const mutate of [s=>s.replace('ok 1 -','not ok 1 -'),s=>s.replace('# pass 26','# pass 25'),s=>s.replace('# skipped 0','# skipped 1'),s=>s.replace('fixture 0','fixture 0 # SKIP'),s=>s.replace('fixture 0','fixture 0 # TODO'),s=>s.replace('ok 2 -','ok 1 -'),s=>s.replace('1..26','1..25'),s=>s.replace('# todo 0','')])assert.throws(()=>strict26(mutate(tap())));});
test('organic CI default OFF: injected and imported execution cannot emit native proof',async()=>{const before=process.env.ORGANIC_LINKS_PG17_CI;delete process.env.ORGANIC_LINKS_PG17_CI;try{assert.equal((await R.execute()).nativePG17Proof,false);assert.equal((await R.runOwned(setup().options)).nativePG17Proof,false);}finally{if(before!==undefined)process.env.ORGANIC_LINKS_PG17_CI=before;}});
test('organic CI physical gate: symlink and hardlink refuse before import',()=>{const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'organic-ci-links-')));try{const f=path.join(root,'original'),link=path.join(root,'symlink'),hard=path.join(root,'hardlink');fs.writeFileSync(f,'tampered');fs.symlinkSync(f,link);fs.linkSync(f,hard);assert.throws(()=>G.physical(link,true));assert.throws(()=>G.physical(hard,true));assert.throws(()=>G.check(root,{...pins.normalizer,repoPath:'original'}));}finally{fs.rmSync(root,{recursive:true,force:true});}});
