-- Metadata only; no legacy row/password/bearer is selected.
WITH t AS (SELECT c.* FROM pg_class c WHERE c.oid IN ('public.crm_dash_chave'::regclass,'public.shrigma_panel_permission_v1'::regclass)),records(k,n,v) AS (
SELECT 'table',c.relname,jsonb_build_object('owner',pg_get_userbyid(c.relowner),'kind',c.relkind,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'partition',c.relispartition,'options',c.reloptions,'columns',(SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid,true)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),'constraints',(SELECT jsonb_agg(jsonb_build_object('name',x.conname,'definition',pg_get_constraintdef(x.oid,true)) ORDER BY x.conname) FROM pg_constraint x WHERE x.conrelid=c.oid),'indexes',(SELECT jsonb_agg(pg_get_indexdef(i.indexrelid) ORDER BY pg_get_indexdef(i.indexrelid)) FROM pg_index i WHERE i.indrelid=c.oid)) FROM t c
UNION ALL SELECT 'table_acl',c.relname,jsonb_agg(jsonb_build_object('grantee',pg_get_userbyid(a.grantee),'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY a.grantee,a.privilege_type) FROM t c CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a WHERE pg_get_userbyid(a.grantee) NOT IN ('crm_manager_writer_owner_v1','crm_manager_writer_service_v1') GROUP BY c.relname
UNION ALL SELECT 'column_acl',c.relname||':'||b.attname,jsonb_agg(jsonb_build_object('grantee',pg_get_userbyid(a.grantee),'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY a.grantee,a.privilege_type) FROM t c JOIN pg_attribute b ON b.attrelid=c.oid CROSS JOIN LATERAL aclexplode(b.attacl) a WHERE pg_get_userbyid(a.grantee) NOT IN ('crm_manager_writer_owner_v1','crm_manager_writer_service_v1') GROUP BY c.relname,b.attname
UNION ALL SELECT 'trigger',c.relname,jsonb_agg(jsonb_build_object('constraint',x.conname,'internal',g.tgisinternal,'enabled',g.tgenabled,'type',g.tgtype,'deferrable',g.tgdeferrable,'deferred',g.tginitdeferred,'function',g.tgfoid::regprocedure::text) ORDER BY x.conname,g.tgtype) FROM t c JOIN pg_trigger g ON g.tgrelid=c.oid LEFT JOIN pg_constraint x ON x.oid=g.tgconstraint WHERE NOT coalesce(x.conrelid=to_regclass('public.crm_manager_writer_generation_v1') AND x.conname='crm_manager_writer_generation_v1_principal_id_fkey',false) GROUP BY c.relname
UNION ALL SELECT 'auth',p.oid::regprocedure::text,jsonb_build_object('owner',pg_get_userbyid(p.proowner),'body',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex'),'acl',p.proacl::text,'path',p.proconfig,'definer',p.prosecdef,'volatile',p.provolatile,'args',p.proargnames) FROM pg_proc p WHERE p.oid IN ('public.shrigma_panel_auth_v1(text,text,text)'::regprocedure,'public.shrigma_panel_operator_v1(text,text)'::regprocedure,'public.shrigma_crm_read_fast_v1(text,text,jsonb)'::regprocedure)
UNION ALL SELECT 'schema_acl',n.nspname,jsonb_agg(jsonb_build_object('grantee',pg_get_userbyid(a.grantee),'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY a.grantee,a.privilege_type) FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a WHERE n.nspname='public' AND pg_get_userbyid(a.grantee) NOT IN ('crm_manager_writer_owner_v1','crm_manager_writer_service_v1') GROUP BY n.nspname
UNION ALL SELECT 'default_acl',d.defaclobjtype::text,jsonb_agg(jsonb_build_object('role',d.defaclrole::regrole::text,'namespace',d.defaclnamespace::regnamespace::text,'acl',d.defaclacl::text) ORDER BY d.defaclrole,d.defaclnamespace) FROM pg_default_acl d GROUP BY d.defaclobjtype
) SELECT encode(sha256(convert_to(jsonb_agg(jsonb_build_object('kind',k,'name',n,'value',v) ORDER BY k,n)::text,'UTF8')),'hex') AS legacy_sha256 FROM records;
