'use strict';
// V2 CI-only smoke: real default policy/startup with a synthetic isolated identity. Run in
// the daughter image as UID:GID 1000:1000 with a NEW /dashboard-data volume and
// PRESENTATION_RELEASE_SMOKE=synthetic-new-volume-v2. Never run on an existing
// identity volume. No factory uid/path overrides, external network or secrets.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http'),Module=require('node:module'),{spawnSync}=require('node:child_process'),{DatabaseSync}=require('node:sqlite');
const READY='/tmp/crm-presentation-ready-v1.json',DATA='/dashboard-data',DB=DATA+'/dashboard.sqlite',RELEASE='/app/presentation-release',PORT=39073;
const HOST='gerencial.synthetic.invalid',EMAIL='master@synthetic.invalid',MANIFEST_SHA='191128958b9c7b299c8cc4d0fdc1c3f0fd6626ae2a42a0132b9556a9065baa11';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const same=(a,b)=>['dev','ino','size','nlink','uid','gid','mode','mtimeMs','ctimeMs'].every(k=>a[k]===b[k]);
const refused=code=>{const e=Error(code);e.closedCode=code;throw e;};
let stage='guard';
async function until(check,code,ms=5000){const end=Date.now()+ms;while(!check()){if(Date.now()>end)refused(code);await new Promise(r=>setTimeout(r,5));}}
function snapshot(){const db=new DatabaseSync(DB,{readOnly:true});try{const tables=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();return Object.fromEntries(tables.map(({name})=>[name,sha(Buffer.from(JSON.stringify(db.prepare('SELECT * FROM "'+name.replace(/"/g,'""')+'"').all().map(row=>JSON.stringify(row)).sort())))]));}finally{db.close();}}
function request(method,pathname,body,cookie=''){
 return new Promise(resolve=>{const req=http.request({host:'127.0.0.1',port:PORT,path:pathname,method,headers:{host:HOST,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json',origin:'https://'+HOST}:{}),'Sec-Fetch-Site':'same-origin','Sec-Fetch-Mode':'cors','Sec-Fetch-Dest':'empty'},agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('end',()=>{const bytes=Buffer.concat(chunks);let json;try{json=JSON.parse(bytes.toString('utf8'));}catch{}resolve({status:res.statusCode,headers:res.headers,bytes,json});});});req.on('error',e=>resolve({error:e.code}));req.setTimeout(2000,()=>req.destroy(Object.assign(Error('SMOKE_HTTP_TIMEOUT'),{code:'SMOKE_HTTP_TIMEOUT'})));req.end(body?JSON.stringify(body):undefined);});
}
function readReady(){
 const before=fs.lstatSync(READY);assert.equal(fs.realpathSync(READY),READY);assert.equal(before.isFile(),true);assert.equal(before.isSymbolicLink(),false);assert.equal(before.uid,1000);assert.equal(before.gid,1000);assert.equal(before.mode&0o777,0o600);assert.equal(before.nlink,1);assert.ok(before.size>0&&before.size<=2048);
 const fd=fs.openSync(READY,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let bytes;
 try{assert.equal(same(before,fs.fstatSync(fd)),true);bytes=fs.readFileSync(fd);assert.equal(bytes.length,before.size);assert.equal(same(before,fs.fstatSync(fd)),true);}finally{fs.closeSync(fd);}assert.equal(same(before,fs.lstatSync(READY)),true);return{bytes,stat:before,value:JSON.parse(bytes.toString('utf8')),sha256:sha(bytes)};
}
function writeReady(bytes){const fd=fs.openSync(READY,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_TRUNC|fs.constants.O_NOFOLLOW,0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.chmodSync(READY,0o600);}
function health(expected){
 const code="try{const r=require('/app/presentation-release/release.cjs').verifyReady();if(r.publicFilesChanged!==13||r.runtimeFilesUnchanged!==28||r.identityAccess!==false||r.manifestSha256!=='191128958b9c7b299c8cc4d0fdc1c3f0fd6626ae2a42a0132b9556a9065baa11')throw Error();process.stdout.write('READY_CONFIRMED');}catch{process.stdout.write('READY_REFUSED');process.exitCode=1;}";
 const run=spawnSync(process.execPath,['-e',code],{encoding:'utf8',timeout:15000,env:{PATH:process.env.PATH}});assert.equal(run.error,undefined);assert.equal(run.signal,null);assert.equal(run.status,expected?0:1);assert.equal(run.stdout,expected?'READY_CONFIRMED':'READY_REFUSED');assert.equal(run.stderr,'');
}
async function run(){
 // These guards precede image/runtime import, env changes, or volume writes.
 if(process.platform!=='linux'||process.getuid?.()!==1000||process.getgid?.()!==1000)refused('SMOKE_REAL_UID_1000_REQUIRED');
 if(process.version!=='v22.23.3')refused('SMOKE_NODE_22_23_3_REQUIRED');
 const tampered=process.env.PRESENTATION_RELEASE_SMOKE==='synthetic-tampered-manifest-v2';
 if(!tampered&&process.env.PRESENTATION_RELEASE_SMOKE!=='synthetic-new-volume-v2')refused('SMOKE_NEW_CI_VOLUME_REQUIRED');
 const initial=fs.lstatSync(DATA);if(!initial.isDirectory()||initial.isSymbolicLink()||initial.uid!==1000||initial.gid!==1000||fs.realpathSync(DATA)!==DATA)refused('SMOKE_NEW_CI_VOLUME_REQUIRED');
 const initialFiles=fs.readdirSync(DATA);if(initialFiles.some(name=>name!=='runtime-pack.json')||fs.existsSync(READY))refused('SMOKE_EXISTING_STATE_REFUSED');
 // Base image controls may be present. Any inherited private DASH material is
 // refused; the one encryption key/bootstrap credential below is generated CI.
 const safeInherited={DASHBOARD_MODE:['synthetic','operational'],DASHBOARD_UPSTREAM_PROFILE:['production'],DASHBOARD_UPSTREAMS:['{}'],DASHBOARD_UPSTREAM_HOSTS:['[]'],DASHBOARD_DB_PATH:[DB],DASHBOARD_EXPECT_UID:['1000'],DASHBOARD_EXPECT_GID:['1000'],DASHBOARD_PACK_SHA256:['c80ee2a8f2611b9cb17a5d24b9b1668a7fe4218a2a95e73cb706e5b6682980da']};
 for(const key of Object.keys(process.env).filter(k=>k.startsWith('DASHBOARD_')))if(!safeInherited[key]?.includes(process.env[key]))refused('SMOKE_INHERITED_DASH_MATERIAL_REFUSED');
 const Release=require(RELEASE+'/release.cjs'),canary=require('/app/canary-start.cjs'),policy=require('/app/artifact-policy.cjs'),sourceImage=Object.fromEntries(Object.keys(Release.IMAGE_FILES).map(name=>[name,sha(fs.readFileSync('/app/'+name))]));assert.deepEqual(sourceImage,Release.IMAGE_FILES);
 const immutable=file=>{const s=fs.lstatSync(file);assert.equal(s.uid,0);assert.equal(s.gid,0);assert.equal(s.mode&0o777,0o444);assert.equal(s.isFile(),true);assert.equal(s.nlink,1);assert.throws(()=>fs.accessSync(file,fs.constants.W_OK));};for(const name of Object.keys(sourceImage))immutable('/app/'+name);immutable(RELEASE+'/release.cjs');immutable(RELEASE+'/manifest.json');if(tampered)assert.notEqual(sha(fs.readFileSync(RELEASE+'/manifest.json')),MANIFEST_SHA);else assert.equal(sha(fs.readFileSync(RELEASE+'/manifest.json')),MANIFEST_SHA);
 const decoded=policy.decodePack(fs.readFileSync('/app/runtime-pack.json','utf8'),Release.BASE_PACK),original=new Map(decoded.files.map(f=>[f.path,Buffer.from(f.content,f.encoding)])),after=new Map(Release.FILES.map(name=>['public/'+name,fs.readFileSync(RELEASE+'/public/'+name)]));assert.equal(decoded.files.length,58);assert.equal(decoded.stats.runtimeFiles,28);assert.equal(decoded.stats.publicFiles,30);assert.equal(Release.FILES.length,13);
 const key=crypto.randomBytes(32),token=crypto.randomBytes(32).toString('base64url'),password='Synthetic default smoke '+crypto.randomBytes(24).toString('base64url')+'!';
 const synth={DASHBOARD_MODE:'synthetic',DASHBOARD_UPSTREAM_PROFILE:'production',DASHBOARD_MANAGER_HOST:HOST,DASHBOARD_AREA_HOSTS:JSON.stringify({growth:'crm.synthetic.invalid',organico:'organico.synthetic.invalid',influs:'influs.synthetic.invalid'}),DASHBOARD_EMAIL_DOMAINS:'["synthetic.invalid"]',DASHBOARD_ADMIN_EMAIL:EMAIL,DASHBOARD_BOOTSTRAP_SHA256:sha(Buffer.from(token)),DASHBOARD_ENCRYPTION_KEY:key.toString('hex'),DASHBOARD_UPSTREAMS:'{}',DASHBOARD_UPSTREAM_HOSTS:'[]',DASHBOARD_DYNAMIC_ROUTE_MANIFEST:'null',DASHBOARD_CRM_DRAFT_WRITE:'disabled',DASHBOARD_CRM_AUDIENCE_DRAFT:'disabled',DASHBOARD_CRM_CAMPAIGN_SUBMIT_WRITE:'disabled',DASHBOARD_CRM_CORPORATE_CREATE:'disabled',DASHBOARD_CRM_MANAGED_READ:'disabled',DASHBOARD_CRM_MANAGED_READ_UI:'disabled',DASHBOARD_CRM_MANAGED_WRITER:'disabled',DASHBOARD_CRM_MANAGED_AUDIENCE_READ:'disabled',DASHBOARD_CRM_MANAGED_TEMPLATE_READ:'disabled',HOST:'127.0.0.1',PORT:String(PORT)};
 Object.assign(process.env,synth);
 let externalAttempts=0;const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{externalAttempts++;refused('SMOKE_EXTERNAL_NETWORK_REFUSED');};
 // Observation only: each original frozen Auth method remains real. close
 // delegates to original SQLite finalization and increments a test counter.
 const load=Module._load,authObservers=[];Module._load=function(request,parent,isMain){const exported=load.call(this,request,parent,isMain);let name;try{name=Module._resolveFilename(request,parent);}catch{return exported;}if(!/^\/tmp\/shrigma-operational-[A-Za-z0-9]+\/artifact\/runtime\/auth\.cjs$/.test(name)||typeof exported.createAuth!=='function')return exported;return{...exported,createAuth(...args){const auth=exported.createAuth(...args),observer={closes:0};authObservers.push(observer);return Object.freeze({...auth,close(){observer.closes++;return auth.close();}});}};};
 const runs=[];let healthRefusals=0,cookie='';
 function verifyUnchanged(artifact){let runtimes=0,unchanged=0,changed=0;for(const [name,before]of original){const expected=after.get(name)||before;assert.equal(sha(fs.readFileSync(path.join(artifact.root,name))),sha(expected));if(name.startsWith('runtime/'))runtimes++;else if(after.has(name))changed++;else unchanged++;}assert.equal(runtimes,28);assert.equal(unchanged,17);assert.equal(changed,13);assert.deepEqual(Object.fromEntries(Object.keys(sourceImage).map(name=>[name,sha(fs.readFileSync('/app/'+name))])),sourceImage);assert.equal(sha(fs.readFileSync(DATA+'/runtime-pack.json')),sourceImage['runtime-pack.json']);}
 function begin(expectedSuccess=true){
  const observerAt=authObservers.length;let started,returned,listening=0,requests=0;
  const start=()=>{started=canary.start();started.server.on('listening',()=>{listening++;});started.server.on('request',()=>{requests++;});return started;};
  if(expectedSuccess){returned=Release.startWithPresentation(start);assert.equal(returned.server,started.server);assert.equal(returned.presentation.manifestSha256,MANIFEST_SHA);}else assert.throws(()=>Release.startWithPresentation(start),/PRESENTATION_RELEASE_REFUSED/);
  assert.ok(started);assert.equal(authObservers.length,observerAt+1);const observer=authObservers[observerAt],state={...started,observer,get requests(){return requests;},get listening(){return listening;}};runs.push(state);
  if(expectedSuccess){assert.equal(started.server.listening,false);assert.equal(requests,0);const verified=Release.verifyReady();assert.equal(verified.manifestSha256,MANIFEST_SHA);assert.equal(verified.publicFilesChanged,13);verifyUnchanged(started.artifact);}
  return state;
 }
 async function stop(state,failed=false){if(state.observer.closes===0)process.emit('SIGTERM');await until(()=>state.observer.closes===1&&!state.server.listening,'SMOKE_ORIGINAL_AUTH_DRAIN_REQUIRED');await new Promise(r=>setTimeout(r,30));assert.equal(state.observer.closes,1);assert.equal(state.server.address(),null);assert.equal(fs.existsSync(state.artifact.root),false);if(failed)assert.equal(process.exitCode,1);else assert.equal(process.exitCode,0);}
 try{
  if(tampered){stage='tampered-manifest-start';const failed=begin(false);await stop(failed,true);assert.equal(failed.listening,0);assert.equal(failed.requests,0);const probe=await request('GET','/organico.html');assert.equal(probe.status,undefined);assert.equal(probe.error,'ECONNREFUSED');assert.equal(externalAttempts,0);assert.equal(authObservers.length,1);assert.equal(authObservers[0].closes,1);process.exitCode=0;return{schema:'crm-presentation-default-smoke-v2',ok:true,scope:'synthetic-tampered-manifest',node:process.version,uid:1000,gid:1000,manifestTamperRefused:true,originalAuthDrains:[1],failedStartupHttpRequests:0,failedStartupSocket:'ECONNREFUSED',externalNetworkAttempts:0,operational:false};}
  stage='default-start';const first=begin();const initialReady=readReady();assert.equal(initialReady.value.artifact.root,first.artifact.root);assert.equal(initialReady.value.manifestSha256,MANIFEST_SHA);assert.throws(()=>Release.applyPresentationSync(first.artifact),/PRESENTATION_RELEASE_REFUSED/);health(true);await until(()=>first.server.listening,'SMOKE_HTTP_LISTENER_REQUIRED');
  stage='synthetic-identity';const bootstrap=await request('POST','/auth/bootstrap/complete',{email:EMAIL,token,password});assert.equal(bootstrap.status,200);const logged=await request('POST','/auth/login',{email:EMAIL,password});assert.equal(logged.status,200);assert.ok(Array.isArray(logged.headers['set-cookie']));cookie=logged.headers['set-cookie'][0].split(';')[0];
  stage='thirteen-public-http';const beforeRequests=first.requests;for(const name of Release.FILES){const reply=await request('GET','/'+name,undefined,cookie);assert.equal(reply.status,200);assert.equal(sha(reply.bytes),sha(after.get('public/'+name)));const csp=reply.headers['content-security-policy'];assert.equal(typeof csp,'string');assert.match(csp,/default-src 'self'/);assert.doesNotMatch(csp,/unsafe-eval/);if(name.endsWith('.css'))assert.match(reply.headers['content-type'],/text\/css/);if(name.endsWith('.js'))assert.match(reply.headers['content-type'],/javascript/);if(name.endsWith('.html')){const html=reply.bytes.toString('utf8'),meta=/<meta\s+http-equiv="Content-Security-Policy"\s+content="([^"]*)">/i.exec(html);assert.ok(meta);assert.equal(csp,meta[1]);for(const s of html.matchAll(/<script\s*>([\s\S]*?)<\/script>/gi))assert.ok(csp.includes("'sha256-"+crypto.createHash('sha256').update(s[1]).digest('base64')+"'"));}}assert.equal(first.requests-beforeRequests,13);assert.equal(Release.verifyReady().manifestSha256,MANIFEST_SHA);verifyUnchanged(first.artifact);
  stage='ready-manifest-negative';const readyValid=readReady().bytes;try{writeReady(Buffer.from(JSON.stringify({...JSON.parse(readyValid),manifestSha256:'0'.repeat(64)})));assert.throws(()=>Release.verifyReady());health(false);healthRefusals++;}finally{writeReady(readyValid);}health(true);
  stage='original-stop';const identity=snapshot(),oldReady=readReady();await stop(first);assert.deepEqual(snapshot(),identity);health(false);
  stage='default-restart';const second=begin(),newReady=readReady();assert.notEqual(second.artifact.root,first.artifact.root);assert.notEqual(newReady.stat.ino,oldReady.stat.ino);assert.notEqual(newReady.sha256,oldReady.sha256);assert.equal(newReady.value.artifact.root,second.artifact.root);assert.equal(newReady.value.artifact.sha256,Release.BASE_PACK);assert.deepEqual(snapshot(),identity);health(true);await until(()=>second.server.listening,'SMOKE_RESTART_LISTENER_REQUIRED');const restartReply=await request('GET','/growth.html',undefined,cookie);assert.equal(restartReply.status,200);assert.equal(sha(restartReply.bytes),sha(after.get('public/growth.html')));verifyUnchanged(second.artifact);const afterReadIdentity=snapshot();await stop(second);assert.deepEqual(snapshot(),afterReadIdentity);
  assert.equal(externalAttempts,0);assert.equal(authObservers.length,2);assert.ok(authObservers.every(a=>a.closes===1));process.exitCode=0;
  stage='complete';return{schema:'crm-presentation-default-smoke-v2',ok:true,node:process.version,uid:1000,gid:1000,mode:'synthetic',upstreamProfile:'production',manifestSha256:MANIFEST_SHA,defaultStartWithPresentation:true,defaultVerifyReady:true,readyFdInodeModeVerified:true,thirteenPublicHttpCspVerified:true,originalArtifactFiles:58,originalPublicFiles:30,publicFilesChanged:13,immutableImageFiles:6,runtimeFilesUnchanged:28,otherPublicFilesUnchanged:17,sameArtifactReplayRefused:true,freshArtifactRestartAccepted:true,identityAndSessionsPreserved:true,readyHealthRefusals:healthRefusals,originalAuthDrains:[1,1],externalNetworkAttempts:0,operational:false};
 }finally{
  for(const state of runs)if(state.observer.closes===0){process.emit('SIGTERM');await until(()=>state.observer.closes===1&&!state.server.listening,'SMOKE_CLEANUP_REFUSED');}
  Module._load=load;globalThis.fetch=oldFetch;key.fill(0);for(const name of Object.keys(synth))delete process.env[name];
 }
}
if(require.main===module)run().then(receipt=>{console.log(JSON.stringify(receipt));process.exitCode=0;},()=>{console.error(JSON.stringify({schema:'crm-presentation-default-smoke-v2',ok:false,stage,code:'DEFAULT_SMOKE_REFUSED',operational:false}));process.exitCode=1;});
module.exports={run};
