-- Synthetic schema and boundary fixture, never deploy to a live database.
CREATE TABLE subscribers(id integer PRIMARY KEY,email text,status text,attribs jsonb,updated_at timestamptz);
CREATE TABLE subscriber_lists(subscriber_id integer,list_id integer,status text,PRIMARY KEY(subscriber_id,list_id));
CREATE TABLE templates(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,type text,name text,body text,subject text,body_source text,is_default boolean NOT NULL DEFAULT false,created_at timestamptz DEFAULT clock_timestamp(),updated_at timestamptz DEFAULT clock_timestamp());
CREATE TABLE shrigma_template_email_registry(template_id integer PRIMARY KEY,brand text);
INSERT INTO templates(id,type,name,body,subject) VALUES(60,'tx','Fixture initial','Fixture','Fixture'),(61,'tx','Fixture next revision','Next','Next');
INSERT INTO shrigma_template_email_registry VALUES(60,'fish'),(61,'fish');
CREATE TABLE shrigma_flow_definition(key text PRIMARY KEY,brand text,published_version integer,published jsonb,binding jsonb,enabled boolean,runtime_ready boolean);
INSERT INTO shrigma_flow_definition VALUES('fish:carrinho','fish',1,
 '{"name":"Fixture cart","steps":[{"key":"email:carrinho-30min","channel":"email","flow":"carrinho","piece":"carrinho-30min","variant":"","enabled":true,"wait_min":30,"template_id":"60"}]}',
 '{"brand":"fish","steps":[{"key":"email:carrinho-30min","channel":"email","flow":"carrinho","piece":"carrinho-30min","variant":"","min_wait":30,"max_wait":45}]}',true,true);
CREATE TABLE shrigma_send_log(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,email text,brand text,kind text,flow text,channel text,piece text,template_id integer,ref text,subscriber_id integer);
CREATE TABLE shrigma_email_dispatch(dispatch_id uuid PRIMARY KEY,brand text,flow text,piece text,dedupe_key text,payload_sha256 text,account_id text,region text,configuration_set text,recipient_key text,recipient_key_version text,is_test boolean,transport_state text,reserved_at timestamptz DEFAULT clock_timestamp(),started_at timestamptz,accepted_at timestamptz,outcome_at timestamptz,claim_token uuid,error_code text,send_log_id bigint,UNIQUE(brand,flow,piece,dedupe_key));
CREATE TABLE shrigma_exposure_7d(subscriber_id integer PRIMARY KEY,marketing_7d integer);
CREATE FUNCTION digest(data bytea,algorithm text) RETURNS bytea LANGUAGE sql IMMUTABLE AS $$SELECT decode(md5(data),'hex')$$;
CREATE FUNCTION shrigma_email_recipient_key(email text) RETURNS TABLE(recipient_key text,key_version text) LANGUAGE sql IMMUTABLE AS $$SELECT md5(lower(email)),'fixture'$$;
CREATE FUNCTION shrigma_flow_slot(p_brand text,p_channel text,p_flow text,p_piece text,p_variant text DEFAULT '',p_source text DEFAULT '') RETURNS jsonb LANGUAGE sql STABLE AS $$
 SELECT coalesce((SELECT s||jsonb_build_object('_managed',true,'_allowed',f.enabled AND (s->>'enabled')::boolean,'_flow_key',f.key,'_version',f.published_version)
 FROM shrigma_flow_definition f CROSS JOIN LATERAL jsonb_array_elements(f.published->'steps')s WHERE f.brand=p_brand AND s->>'channel'=p_channel AND s->>'flow'=p_flow AND s->>'piece'=p_piece LIMIT 1),'{"_managed":false}')$$;
CREATE FUNCTION shrigma_flow_wait(p_brand text,p_channel text,p_piece text,p_default numeric) RETURNS interval LANGUAGE sql STABLE AS $$
 SELECT make_interval(secs=>60*coalesce((SELECT min((s->>'wait_min')::numeric) FROM shrigma_flow_definition f CROSS JOIN LATERAL jsonb_array_elements(f.published->'steps')s WHERE f.brand=p_brand AND s->>'channel'=p_channel AND s->>'piece'=p_piece),p_default)::double precision)$$;
CREATE FUNCTION shrigma_flow_stage_enabled(p_brand text,p_channel text,p_piece text) RETURNS boolean LANGUAGE sql STABLE AS $$
 SELECT coalesce((SELECT bool_or(f.enabled AND (s->>'enabled')::boolean) FROM shrigma_flow_definition f CROSS JOIN LATERAL jsonb_array_elements(f.published->'steps')s WHERE f.brand=p_brand AND s->>'channel'=p_channel AND s->>'piece'=p_piece),true)$$;
CREATE FUNCTION shrigma_email_claim_cart(b jsonb) RETURNS TABLE(should_send boolean,dispatch_id uuid,claim_token uuid,payload jsonb,context jsonb,reason text)
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $fixture$
DECLARE v_brand text=b->>'brand';v_stage text=b->>'toque';v_piece text=b->>'piece';v_template integer=(b->>'template_id')::integer;
 stage_config jsonb;v_tx jsonb=b->'tx';v_id integer;v_at timestamptz;v_ref text;v_key text;v_hash text;age interval;v_dispatch uuid;v_claim uuid;v_cfg text:='fixture';d shrigma_email_dispatch%ROWTYPE;
BEGIN
stage_config=shrigma_flow_slot(v_brand,'email','carrinho',v_piece);
IF (stage_config->>'_managed')::boolean THEN
 IF NOT (stage_config->>'_allowed')::boolean THEN RETURN QUERY SELECT false,NULL::uuid,NULL::uuid,NULL::jsonb,NULL::jsonb,'flow_paused';RETURN;END IF;
 v_template=(stage_config->>'template_id')::int;v_tx=jsonb_set(v_tx,'{template_id}',to_jsonb(v_template));b=b||jsonb_build_object('template_id',v_template,'tx',v_tx);
END IF;
IF coalesce(b->>'subscriber_id','') !~ '^[1-9][0-9]*$' OR coalesce(b->>'ref','') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' THEN RAISE EXCEPTION 'CART_IDENTITY_INVALID'; END IF;
v_id=(b->>'subscriber_id')::int;v_at=(b->>'ref')::timestamptz;age=now()-v_at;
v_ref=to_char(v_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');v_key=jsonb_build_array('email',v_ref,v_id,false)::text;v_hash=encode(digest(convert_to(jsonb_set(b-'marketing_7d','{ref}',to_jsonb(v_ref))::text,'UTF8'),'sha256'),'hex');
PERFORM pg_advisory_xact_lock(hashtextextended('fixture-claim:'||v_key,0));
SELECT * INTO d FROM shrigma_email_dispatch x WHERE x.brand=v_brand AND x.flow='carrinho' AND x.piece=v_piece AND x.dedupe_key=v_key FOR UPDATE;
IF FOUND THEN RETURN QUERY SELECT false,d.dispatch_id,NULL::uuid,NULL::jsonb,NULL::jsonb,d.transport_state;RETURN;END IF;
IF NOT (age>=shrigma_flow_wait(v_brand,'email','carrinho-30min',30) AND age<interval '1 hour') THEN RETURN QUERY SELECT false,NULL::uuid,NULL::uuid,NULL::jsonb,NULL::jsonb,'cadence_or_cap_changed';RETURN;END IF;
v_dispatch=gen_random_uuid();v_claim=gen_random_uuid();
INSERT INTO shrigma_email_dispatch(dispatch_id,brand,flow,piece,dedupe_key,payload_sha256,is_test,transport_state,claim_token) VALUES(v_dispatch,v_brand,'carrinho',v_piece,v_key,v_hash,false,'in_flight',v_claim);
v_tx=jsonb_set(v_tx,'{headers}',(v_tx->'headers')||jsonb_build_array(jsonb_build_object('X-Fixture','fixture')));
RETURN QUERY SELECT true,v_dispatch,v_claim,v_tx,b,'claimed';
END $fixture$;
CREATE FUNCTION shrigma_email_finish_cart(p_id uuid,p_claim uuid,p_outcome text,b jsonb) RETURNS TABLE(dispatch_id uuid,transport_state text,send_log_id bigint,error_code text)
LANGUAGE plpgsql AS $fixture$
DECLARE d shrigma_email_dispatch%ROWTYPE;
BEGIN
 SELECT * INTO STRICT d FROM shrigma_email_dispatch x WHERE x.dispatch_id=p_id FOR UPDATE;
 IF d.claim_token IS DISTINCT FROM p_claim THEN RAISE EXCEPTION 'DISPATCH_CLAIM_MISMATCH';END IF;
 IF d.transport_state<>'in_flight' AND d.transport_state<>p_outcome THEN RAISE EXCEPTION 'DISPATCH_OUTCOME_CONFLICT';END IF;
 UPDATE shrigma_email_dispatch x SET transport_state=p_outcome WHERE x.dispatch_id=p_id;
 RETURN QUERY SELECT p_id,p_outcome,NULL::bigint,NULL::text;
END $fixture$;
