-- Execute with olivas-nps.sql and private seed inside BEGIN ... ROLLBACK.
DO $test$
DECLARE sid int;p record;r record;r2 record;v record;job record;b jsonb;ctx jsonb;did uuid;token uuid;failed boolean=false;
BEGIN
 INSERT INTO subscribers(uuid,email,name,status,attribs) VALUES(gen_random_uuid(),'olivas-nps-fixture@example.invalid','Fixture','enabled','{"keep":"yes","nps":{"brand":"fish","score":4,"order":"other"}}') RETURNING id INTO sid;
 INSERT INTO subscriber_lists(subscriber_id,list_id,status) VALUES(sid,40,'confirmed');
 BEGIN PERFORM * FROM shrigma_olivas_nps_receive('{"brand":"olivas","k":"bad"}'); EXCEPTION WHEN OTHERS THEN failed=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Bad sender key accepted';END IF;
 SELECT * INTO p FROM shrigma_olivas_nps_prepare('{"brand":"olivas","email":"olivas-nps-fixture@example.invalid","order_number":"olivas-fixture","first_name":"Fixture"}','nps-d0');
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF r.should_send OR r.reason<>'flow_paused' THEN RAISE EXCEPTION 'Pause ignored';END IF;
 UPDATE shrigma_flow_definition SET enabled=true WHERE key='olivas:nps-d0';
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF NOT r.should_send OR r.payload->>'from_email'<>'Olivas do Campo <sac@olivasdocampo.com>' THEN RAISE EXCEPTION 'Claim/sender invalid';END IF;
 IF r.payload::text LIKE '%X-SES-CONFIGURATION-SET%' THEN RAISE EXCEPTION 'Unconfigured SES enabled';END IF;
 ctx=r.context;did=r.dispatch_id;token=r.claim_token;
 SELECT * INTO r2 FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF r2.should_send THEN RAISE EXCEPTION 'Duplicate send allowed';END IF;
 IF shrigma_olivas_nps_initial_confirmed('olivas','olivas-fixture','olivas-nps-fixture@example.invalid') THEN RAISE EXCEPTION 'Unaccepted initial confirmed';END IF;
 PERFORM * FROM shrigma_email_observe_engagement(did,token,'{"statusCode":200,"body":{"data":true}}',ctx);
 SELECT * INTO r2 FROM shrigma_olivas_nps_finish_http(did,token,'{"statusCode":200,"body":{"data":true}}',ctx);
 IF r2.transport_state<>'accepted' OR NOT shrigma_olivas_nps_initial_confirmed('olivas','olivas-fixture','olivas-nps-fixture@example.invalid') THEN RAISE EXCEPTION 'Acceptance not recorded';END IF;
 b=jsonb_build_object('n',9,'p','olivas-fixture','e','olivas-nps-fixture@example.invalid','m','olivas','s',shrigma_nps_sign('olivas|olivas-fixture','olivas-nps-fixture@example.invalid'));
 SELECT * INTO v FROM shrigma_olivas_nps_record_vote(b||'{"m":"fish"}');
 IF v.response->>'ok'<>'false' THEN RAISE EXCEPTION 'Foreign brand accepted';END IF;
 SELECT * INTO v FROM shrigma_olivas_nps_record_vote(b||'{"s":"bad"}');
 IF v.response->>'ok'<>'false' THEN RAISE EXCEPTION 'Bad signature accepted';END IF;
 SELECT * INTO v FROM shrigma_olivas_nps_record_vote(b||'{"n":"9oops"}');
 IF v.response->>'ok'<>'false' THEN RAISE EXCEPTION 'Malformed vote accepted';END IF;
 SELECT * INTO v FROM shrigma_olivas_nps_record_vote(b);
 IF v.response->>'ok'<>'true' OR v.response->>'bucket'<>'promotor' OR v.sync_id IS NULL THEN RAISE EXCEPTION 'Vote not stored';END IF;
 SELECT * INTO job FROM shrigma_olivas_nps_claim_vote_sync(v.sync_id);
 IF job.sync_id IS DISTINCT FROM v.sync_id THEN RAISE EXCEPTION 'Sync not claimed';END IF;
 IF EXISTS(SELECT 1 FROM shrigma_olivas_nps_claim_vote_sync(v.sync_id)) THEN RAISE EXCEPTION 'Sync claimed twice';END IF;
 PERFORM shrigma_olivas_nps_finish_vote_sync(v.sync_id,'{"ok":true,"task_id":"fixture-task"}');
 SELECT * INTO v FROM shrigma_olivas_nps_record_vote(b);
 IF v.response->>'repetido'<>'true' OR v.sync_id IS NOT NULL THEN RAISE EXCEPTION 'Duplicate vote created a job';END IF;
 SELECT * INTO v FROM shrigma_olivas_nps_comment(b||'{"comment":"Experiência ótima"}');
 IF v.response->>'ok'<>'true' THEN RAISE EXCEPTION 'Comment not saved';END IF;
 IF NOT EXISTS(SELECT 1 FROM subscribers WHERE id=sid AND attribs->>'keep'='yes' AND attribs->'nps'->>'score'='4' AND attribs->'nps_olivas'->>'score'='9' AND attribs->'nps_olivas'->>'comment'='Experiência ótima') THEN RAISE EXCEPTION 'Cross-brand attributes lost';END IF;
 SELECT * INTO p FROM shrigma_olivas_nps_prepare('{"brand":"olivas","email":"olivas-nps-fixture@example.invalid","order_number":"olivas-fixture"}','nps-d3');
 UPDATE subscribers SET attribs=jsonb_set(attribs,'{nps_sent_olivas,date}',to_jsonb((now()-interval '4 days')::text)) WHERE id=sid;
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF r.should_send OR r.reason<>'reminder_ineligible' THEN RAISE EXCEPTION 'Answered survey reminded';END IF;
 UPDATE subscribers SET attribs=attribs-'nps_olivas' WHERE id=sid;
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF NOT r.should_send THEN RAISE EXCEPTION 'Eligible reminder blocked: %',r.reason;END IF;
 PERFORM * FROM shrigma_olivas_nps_finish_http(r.dispatch_id,r.claim_token,'{"statusCode":200,"body":{"data":true}}',r.context);
 IF NOT EXISTS(SELECT 1 FROM subscribers WHERE id=sid AND attribs->'nps_sent_olivas'->>'reminded'='true') THEN RAISE EXCEPTION 'Reminder not marked';END IF;
 SELECT * INTO p FROM shrigma_olivas_nps_prepare('{"brand":"olivas","email":"olivas-nps-fixture@example.invalid","order_number":"olivas-next"}','nps-d0');
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF r.should_send OR r.reason<>'nps_cooldown' THEN RAISE EXCEPTION 'Cooldown ignored';END IF;
 UPDATE subscriber_lists SET status='unsubscribed' WHERE subscriber_id=sid AND list_id=40;
 SELECT * INTO r FROM shrigma_olivas_nps_claim(to_jsonb(p));
 IF r.should_send OR r.reason<>'olivas_subscription_unavailable' THEN RAISE EXCEPTION 'Unsubscribed recipient accepted';END IF;
END $test$;
