'use strict';
const {parentPort,workerData}=require('node:worker_threads'),crypto=require('node:crypto'),P=require('./protocol.cjs');
const control=new Int32Array(workerData.control),response=new Uint8Array(workerData.response),registry=P.registry(),byId=new Map(registry.statements.map(s=>[s.id,s]));
let db,opened=false,transaction=false,writerLock=false,poison=false,fixture=false,queue=Promise.resolve();
const stateError=(code,state)=>{const e=P.closedError(code,state);if(state)e.code=state;throw e;};
async function query(text,params=[]){return db.query(text,params);}
async function lock(){if(writerLock)throw P.closedError('DASHBOARD_PG_TRANSACTION_REFUSED');const r=await query('SELECT pg_catalog.pg_advisory_lock(20261005,8133)');if(r.command!=='SELECT')throw P.closedError('DASHBOARD_PG_LOCK_REFUSED');writerLock=true;}
async function unlock(){if(!writerLock)return;const r=await query('SELECT pg_catalog.pg_advisory_unlock(20261005,8133) AS released');if(r.command!=='SELECT'||r.rows[0]?.released!==true){poison=true;throw P.closedError('DASHBOARD_PG_LOCK_REFUSED');}writerLock=false;}
async function begin(){if(transaction)throw P.closedError('DASHBOARD_PG_TRANSACTION_REFUSED');await lock();try{const r=await query('BEGIN ISOLATION LEVEL SERIALIZABLE');if(r.command!=='BEGIN')throw P.closedError('DASHBOARD_PG_TRANSACTION_REFUSED');transaction=true;}catch(e){await unlock();throw e;}}
async function finish(command){if(!transaction)throw P.closedError('DASHBOARD_PG_TRANSACTION_REFUSED');try{if(fixture&&command==='COMMIT'&&workerData.fixtureTransport.rejectCommitSqlstate)stateError('DASHBOARD_PG_COMMIT_REFUSED',workerData.fixtureTransport.rejectCommitSqlstate);const r=await query(command);if(r.command!==command)throw P.closedError('DASHBOARD_PG_COMMIT_NOT_ACKNOWLEDGED');transaction=false;await unlock();
 if(fixture&&command==='COMMIT'){const f=workerData.fixtureTransport;if(f.metrics)Atomics.add(new Int32Array(f.metrics),0,1);if(Number.isInteger(f.delayAfterCommitMs)&&f.delayAfterCommitMs>0)await new Promise(resolve=>setTimeout(resolve,f.delayAfterCommitMs));}}
 catch(e){poison=true;throw e;}}
async function columnsVerified(){const actual=(await query("SELECT c.relname AS table_name,a.attname AS name,t.typname AS type,a.attnotnull AS not_null FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid JOIN pg_catalog.pg_type t ON t.oid=a.atttypid WHERE n.nspname='dashboard_identity' AND c.relkind='r' AND a.attnum>0 AND NOT a.attisdropped ORDER BY c.relname,a.attnum")).rows;
 for(const table of registry.tables){const cols=actual.filter(c=>c.table_name===table.name);if(cols.length!==table.columns.length||cols.some((c,i)=>c.name!==table.columns[i].name||c.type!==(table.columns[i].type==='INTEGER'?'int8':'text')||table.columns[i].notNull&&!c.not_null))throw P.closedError('DASHBOARD_PG_SCHEMA_REFUSED');}
 const ledger=await query("SELECT NOT EXISTS(SELECT 1 FROM dashboard_identity.crm_writer_bridge_op_v1 o LEFT JOIN dashboard_identity._sqlite_row_order_v1 r ON r.table_name='crm_writer_bridge_op_v1' AND r.row_key=o.operation_id WHERE r.row_key IS NULL) AS complete");if(ledger.rows[0]?.complete!==true)throw P.closedError('DASHBOARD_PG_ROW_ORDER_REFUSED');
}
function verifyReceipt(row,admission){const body=row.receipt_body;if(row.phase!=='confirmed'||row.operation_id!==admission.operationId||row.catalog_sha256!==registry.catalogSha256||row.source_data_sha256!==row.target_data_sha256||row.source_proof?.snapshotSha256!==admission.snapshotSha256||body?.schema!=='dashboard-identity-central-origin-confirmed-receipt-v1'||body.receipt?.operationId!==row.operation_id||body.receipt?.sourceDataSha256!==row.source_data_sha256||body.receipt?.sourceSchemaSha256!==row.source_schema_sha256||body.receipt?.catalogSha256!==registry.catalogSha256||body.receipt?.sourceProof?.snapshotSha256!==admission.snapshotSha256||body.nativeResultMac!==row.receipt_mac)throw P.closedError('DASHBOARD_PG_IMPORT_REFUSED');
 try{const key=crypto.createPublicKey({key:Buffer.from(admission.originPublicKey,'base64'),type:'spki',format:'der'});if(key.asymmetricKeyType!=='ed25519'||!crypto.verify(null,Buffer.from(P.canonical(body)),key,Buffer.from(row.receipt_signature,'base64')))throw 0;}catch{throw P.closedError('DASHBOARD_PG_IMPORT_REFUSED');}}
async function open(){if(opened)throw P.closedError('DASHBOARD_PG_OPEN_REFUSED');const {options,fixtureTransport}=workerData;
 if(fixtureTransport){if(fixtureTransport.kind!=='pglite-test-only'||process.env.NODE_ENV==='production')throw P.closedError('DASHBOARD_PG_FIXTURE_REFUSED');const {PGlite}=require(fixtureTransport.modulePath),pg=new PGlite();await pg.waitReady;await pg.exec(fixtureTransport.ddl);fixture=true;db={query:async(text,params)=>{const r=params.length?await pg.query(text,params):(await pg.exec(text))[0];return {...r,command:(text.startsWith('ROLLBACK')?'ROLLBACK':text.startsWith('COMMIT')?'COMMIT':text.startsWith('BEGIN')?'BEGIN':text.trimStart().startsWith('SELECT')?'SELECT':text.trimStart().split(/\s/)[0]),rowCount:r.affectedRows??r.rows?.length??0};},end:()=>pg.close()};
 }else{
  if(process.versions.node.split('.')[0]!=='22'||!options.connection||Object.keys(options.connection).sort().join(',')!=='database,host,password,port,user'||options.connection.database!=='listmonk'||options.connection.host!=='comunicacao_postgres'||options.connection.port!==5432||typeof options.connection.user!=='string'||!/^[-A-Za-z0-9_]{1,63}$/.test(options.connection.user)||typeof options.connection.password!=='string'||options.connection.password.length<1||options.connection.password.length>8192||/[\0\r\n]/.test(options.connection.password)||!options.admission||Object.keys(options.admission).sort().join(',')!=='operationId,originPublicKey,snapshotSha256'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(options.admission.operationId||'')||!/^[a-f0-9]{64}$/.test(options.admission.snapshotSha256||'')||typeof options.admission.originPublicKey!=='string')throw P.closedError('DASHBOARD_PG_CONFIG_REFUSED');
  try{if(crypto.createPublicKey({key:Buffer.from(options.admission.originPublicKey,'base64'),type:'spki',format:'der'}).asymmetricKeyType!=='ed25519')throw 0;}catch{throw P.closedError('DASHBOARD_PG_CONFIG_REFUSED');}
  const pg=require('pg');if(require('pg/package.json').version!=='8.13.1')throw P.closedError('DASHBOARD_PG_DRIVER_REFUSED');
  db=new pg.Client({...options.connection,application_name:'dashboard-central-identity',connectionTimeoutMillis:3000,query_timeout:6000,options:'-c search_path=pg_catalog -c statement_timeout=5000 -c lock_timeout=5000 -c idle_in_transaction_session_timeout=10000 -c log_statement=none -c log_min_messages=panic -c log_min_error_statement=panic -c log_parameter_max_length=0 -c log_parameter_max_length_on_error=0 -c log_min_duration_statement=-1 -c log_min_duration_sample=-1 -c log_transaction_sample_rate=0 -c client_min_messages=error'});db.on('error',()=>{poison=true;});await db.connect();
  const ctx=await query(require('./admission.cjs').contextSQL,[options.connection.user]);if(ctx.rows.length!==1||Object.values(ctx.rows[0]).some(x=>x!==true))throw P.closedError('DASHBOARD_PG_CONTEXT_REFUSED');
  const admissionRows=(await query('SELECT * FROM dashboard_identity._migration_v1 WHERE singleton=true')).rows;if(admissionRows.length!==1)throw P.closedError('DASHBOARD_PG_IMPORT_REFUSED');verifyReceipt(admissionRows[0],options.admission);options.connection.password=undefined;
 }
 await columnsVerified();opened=true;return {fixture,sourceRevision:registry.sourceRevision,registrySha256:registry.registrySha256,operational:false};
}
function normalize(rows,fields,s,big){return rows.map(row=>{const values=Array.isArray(row)?row:fields.map(f=>row[f.name]);if(values.length!==s.columns.length)throw P.closedError('DASHBOARD_PG_COLUMN_REFUSED');const out={};for(let i=0;i<values.length;i++){let value=values[i];if(value!==null&&[20,21,23].includes(fields[i].dataTypeID)){if(!/^-?[0-9]+$/.test(String(value)))throw P.closedError('DASHBOARD_PG_INTEGER_REFUSED');const n=BigInt(value);if(big)value=n;else{value=Number(n);if(!Number.isSafeInteger(value))throw P.closedError('DASHBOARD_PG_INTEGER_RANGE');}}out[s.columns[i]]=value;}return out;});}
async function statement(request){const s=byId.get(request.id);if(!s||s.api!=='prepare'||!Array.isArray(request.params)||request.params.length!==s.parameterCount)throw P.closedError('DASHBOARD_PG_SQL_NOT_ADMITTED');
 if(fixture&&workerData.fixtureTransport.metrics)Atomics.add(new Int32Array(workerData.fixtureTransport.metrics),1,1);
 if(s.ignore&&s.ignoreNullParameters.some(i=>request.params[i]===null))return {changes:0};
 if(s.kind==='table-info'){const table=registry.tables.find(t=>t.name===s.table),integer=n=>request.readBigInts?BigInt(n):n;return table.columns.map((c,i)=>({cid:integer(i),name:c.name,type:c.type,notnull:integer(c.notNull?1:0),dflt_value:c.default,pk:integer(c.primaryKeyOrder)}));}
 const auto=s.writes&&!transaction;let committing=false;if(auto)await begin();try{
  const r=await query(s.pgSql,request.params);let value;if(s.writes){if(!Number.isSafeInteger(r.rowCount)||r.rowCount<0)throw P.closedError('DASHBOARD_PG_COUNT_REFUSED');value={changes:r.rowCount};}else value=normalize(r.rows,r.fields,s,request.readBigInts);
  if(auto){committing=true;await finish('COMMIT');}return value;
 }catch(e){if(auto&&transaction&&!committing){try{await finish('ROLLBACK');}catch{poison=true;}}if(committing)poison=true;throw e;}}
async function action(request){if(request.action==='open')return open();if(!opened||poison)throw P.closedError('DASHBOARD_PG_UNAVAILABLE');if(request.action==='statement')return statement(request);
 if(request.action==='exec'){const s=byId.get(request.id);if(!s||s.api!=='exec')throw P.closedError('DASHBOARD_PG_SQL_NOT_ADMITTED');if(s.kind==='begin')await begin();else if(s.kind==='commit')await finish('COMMIT');else if(s.kind==='rollback')await finish('ROLLBACK');else if(s.kind==='schema-assertion')await columnsVerified();else throw P.closedError('DASHBOARD_PG_SQL_NOT_ADMITTED');return null;}
 if(request.action==='close'){if(transaction)await finish('ROLLBACK');await db.end();opened=false;return null;}throw P.closedError('DASHBOARD_PG_ACTION_REFUSED');}
parentPort.on('message',request=>{queue=queue.then(async()=>{try{const value=await action(request);if(fixture&&request.action==='statement'&&workerData.fixtureTransport.malformedResponseAfterStatement){Atomics.store(control,1,0);Atomics.store(control,0,P.DONE);Atomics.notify(control,0);}else P.writeResponse(control,response,{ok:true,value,transaction,poison});}catch(e){const state=P.safeState(e);if(!state&&!e?.code?.startsWith('DASHBOARD_PG_')||state?.startsWith('08')||e?.code==='DASHBOARD_PG_UNAVAILABLE')poison=true;P.writeResponse(control,response,{ok:false,code:e?.code?.startsWith('DASHBOARD_PG_')?e.code:'DASHBOARD_PG_STATEMENT_REFUSED',sqlstate:state,transaction,poison});}if(poison)try{await db?.end();}catch{}});});
