'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const {createManagerJournal}=require('./crm-manager-journal.cjs');
const {createManagerCoordinator}=require('./crm-manager-coordinator.cjs');
const CAPS=['read_content','list_history','submission'],TTL=600000,LIFETIME=1209600000,RAW='PRIVATE_ERROR_SENTINEL_NOT_PUBLIC';
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const gate=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(t){
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT,role TEXT,state TEXT);CREATE TABLE grants(user_id TEXT,area TEXT,can_read INTEGER,can_edit INTEGER);CREATE TABLE upstream_credentials(user_id TEXT,slot TEXT,encrypted_key TEXT,key_digest TEXT,updated_at INTEGER,PRIMARY KEY(user_id,slot));`);
 const key=Buffer.alloc(32,7);let clock=1770000000000;
 const encrypt=value=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv),b=Buffer.concat([c.update(value),c.final()]);return ['v1',iv.toString('base64url'),c.getAuthTag().toString('base64url'),b.toString('base64url')].join('.');};
 const decrypt=value=>{const[,iv,tag,bytes]=value.split('.'),d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(bytes,'base64url')),d.final()]).toString();};
 const issuerId=crypto.randomUUID(),namespaceId=crypto.randomUUID(),opts={db,issuerId,namespaceId,encrypt,decrypt,digest:v=>crypto.createHmac('sha256',key).update(v).digest('hex'),now:()=>clock};
 let journal=createManagerJournal(opts),client,coordinator;const events=[],ledger=new Map(),tombstones=new Set(),faults=new Map(),bearers=[];
 const fail=()=>{throw Error(RAW);};
 const hook=async label=>{const fn=faults.get(label);if(fn){faults.delete(label);await fn();}};
 const tracked=()=>Object.freeze(Object.fromEntries(Object.entries(journal).map(([name,fn])=>[name,(...args)=>{if(name!=='operationState'&&name!=='request'&&name!=='commitDescriptor')events.push({type:name});return fn(...args);}])));
 const tx=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
 const add=(role='manager')=>{const id=crypto.randomUUID();db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(id,'gestor+'+id+'@example.test',role,'invited');db.prepare('INSERT INTO grants VALUES(?,?,1,0)').run(id,'growth');return id;};
 const start=id=>tx(()=>{journal.createLifecycle(id);db.prepare("UPDATE users SET state='active' WHERE id=?").run(id);return journal.activateLifecycle(id).operationId;});
 const revoke=id=>tx(()=>{const op=journal.stageRevoke(id).operationId;db.prepare("UPDATE users SET state='disabled' WHERE id=?").run(id);db.prepare('DELETE FROM upstream_credentials WHERE user_id=?').run(id);return op;});
 const base=(action,args)=>({schema:'crm-manager-provision-receipt-v1',issuerId,namespaceId,operationId:args.operationId,action,userId:args.userId,lifecycleId:args.lifecycleId,owner:args.owner});
 const args=id=>{const r=journal.request(id);return r.expectedGeneration===0?Object.fromEntries(Object.entries(r).filter(([k])=>!['generation','expectedGeneration'].includes(k))):{...r};};
 function fakeClient(){
  const branded=new WeakMap();
  const proof=record=>{const value=structuredClone(record.receipt);if(['prepare_read','renew_read'].includes(value.action))branded.set(value,record.args);return value;};
  const remember=(action,args,receipt)=>{const prior=ledger.get(args.operationId);if(prior){assert.equal(prior.action,action);assert.equal(canonical(prior.args),canonical(args));return prior;}const record={action,args:structuredClone(args),receipt};ledger.set(args.operationId,record);return record;};
  const prepare=async(action,a)=>{assert.deepEqual(Object.keys(a).sort(),['operationId','userId','lifecycleId','owner','principalId','keySha256',...(action==='renew_read'?['generation','expectedGeneration']:[])].sort());events.push({type:action,args:structuredClone(a)});await hook('prepare:before');if(tombstones.has(a.lifecycleId))fail();let record=ledger.get(a.operationId);if(!record){const generation=a.generation??1,expectedGeneration=a.expectedGeneration??0;record=remember(action,a,{...base(action,a),state:'prepared',principalId:a.principalId,generation,expectedGeneration,area:'growth',slot:'crm-panel-read',role:'manager',caps:[...CAPS],issuedAt:clock,candidateExpiresAt:clock+TTL,expiresAt:clock+LIFETIME});}else{assert.equal(canonical(record.args),canonical(a));if(record.receipt.candidateExpiresAt<=clock)fail();}await hook('prepare:after');return proof(record);};
  return Object.freeze({
   prepareRead:a=>prepare('prepare_read',a),prepareRenewalRead:a=>prepare('renew_read',a),
   operationStatus:async d=>{assert.deepEqual(Object.keys(d).sort(),['action','args','requireFound'].sort());events.push({type:'status:'+d.action,args:structuredClone(d.args),requireFound:d.requireFound});await hook('status:before');const record=ledger.get(d.args.operationId);if(record){assert.equal(record.action,d.action);assert.equal(canonical(record.args),canonical(d.args));}await hook('status:after');return record?{found:true,receipt:proof(record)}:{found:false};},
   commitRead:async a=>{assert.deepEqual(Object.keys(a).sort(),['operationId','prepared']);assert.ok(branded.has(a.prepared),'client requires a proof branded in this instance');const p=a.prepared,r=branded.get(p),cmd={...r,generation:p.generation,expectedGeneration:p.expectedGeneration,operationId:a.operationId,prepareOperationId:p.operationId,issuedAt:p.issuedAt,candidateExpiresAt:p.candidateExpiresAt,expiresAt:p.expiresAt};events.push({type:'commit_read',args:structuredClone(cmd)});await hook('commit:before');if(tombstones.has(p.lifecycleId))fail();const record=remember('commit_read',cmd,{...p,action:'commit_read',operationId:a.operationId,state:'committed',prepareOperationId:p.operationId,committedAt:clock,revokedGeneration:p.expectedGeneration===0?null:p.expectedGeneration});await hook('commit:after');return proof(record);},
   revokeRead:async a=>{events.push({type:'revoke_read',args:structuredClone(a)});await hook('revoke:before');tombstones.add(a.lifecycleId);const record=remember('revoke_read',a,{...base('revoke_read',a),state:'revoked',allGenerationsRevoked:true,revocationMode:'lifecycle',effectiveAt:clock,revokedCount:1});await hook('revoke:after');return proof(record);}
  });
 }
 const defaultAttest=async input=>{assert.deepEqual(Object.keys(input).sort(),['bearer','owner','principalId']);bearers.push(input.bearer);events.push({type:'attest'});await hook('attest:before');return {owner:input.owner,principalId:input.principalId,caps:[...CAPS]};};
 const make=(extra={})=>createManagerCoordinator({journal:tracked(),client,attest:defaultAttest,getOperationState:id=>journal.operationState(id),now:()=>clock,...extra});
 client=fakeClient();coordinator=make();
 const restart=()=>{journal=createManagerJournal(opts);client=fakeClient();coordinator=make();};
 const stagePrepared=async id=>{journal.beginPrepare(id);const a=args(id),p=await (Object.hasOwn(a,'generation')?client.prepareRenewalRead(a):client.prepareRead(a));journal.recordPrepared(id,p);return p;};
 const stageAttested=async id=>{const p=await stagePrepared(id);journal.recordAttestation(id,{owner:p.owner,principalId:p.principalId,caps:p.caps});return p;};
 const stageCommitted=async id=>{const p=await stageAttested(id);journal.beginCommit(id);const c=await client.commitRead({operationId:journal.commitOperationId(id),prepared:p});journal.recordCommitted(id,c);return c;};
 return {db,events,ledger,faults,bearers,add,start,revoke,make,restart,stagePrepared,stageAttested,stageCommitted,advance:ms=>clock+=ms,clock:()=>clock,phase:id=>journal.operationState(id).phase,row:id=>db.prepare('SELECT * FROM crm_manager_operations_v1 WHERE operation_id=?').get(id),get j(){return journal;},get client(){return client;},get c(){return coordinator;}};
}
const publicResult=(value,state)=>assert.deepEqual(value,{state});

test('explicit issue records prepare intent before RPC, attests privately and promotes locally',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id),digest=f.j.request(op).keySha256;publicResult(await f.c.run(op),'ready');assert.equal(f.phase(op),'promoted');assert.equal(f.j.credentialReady(id),true);
 const types=f.events.map(e=>e.type);assert.ok(types.indexOf('beginPrepare')<types.indexOf('prepare_read'));assert.ok(types.indexOf('beginCommit')<types.indexOf('status:prepare_read'));assert.ok(types.indexOf('recordCommitted')<types.indexOf('promote'));assert.equal(f.bearers.length,1);assert.equal(crypto.createHash('sha256').update(f.bearers[0]).digest('hex'),digest);for(const e of f.events.filter(e=>e.args))assert.equal(JSON.stringify(e).includes(f.bearers[0]),false);
});
test('prepare failure before execution resumes with STATUS then repeats identical ID and digest',async t=>{
 const f=fixture(t),op=f.start(f.add()),original=f.j.request(op);f.faults.set('prepare:before',()=>{throw Error(RAW);});publicResult(await f.c.run(op),'pending');assert.equal(f.phase(op),'prepare_uncertain');assert.equal(f.ledger.size,0);f.restart();const index=f.events.length;publicResult(await f.c.run(op),'ready');assert.equal(f.events[index].type,'status:prepare_read');const repeated=f.events.filter(e=>e.type==='prepare_read');assert.equal(repeated.length,2);assert.deepEqual(repeated[0].args,repeated[1].args);assert.equal(repeated[1].args.keySha256,original.keySha256);assert.equal(Object.hasOwn(repeated[1].args,'generation'),false);
});
test('lost prepare ACK resumes by status without repeating prepare or changing dates',async t=>{
 const f=fixture(t),op=f.start(f.add());f.faults.set('prepare:after',()=>{throw Error(RAW);});publicResult(await f.c.run(op),'pending');const original=structuredClone(f.ledger.get(op).receipt);f.advance(1000);f.restart();publicResult(await f.c.run(op),'ready');assert.equal(f.events.filter(e=>e.type==='prepare_read').length,1);assert.equal(f.row(op).issued_at,original.issuedAt);assert.equal(f.row(op).expires_at,original.expiresAt);
});
test('expired prepare ACK is reconciled before local expiry, with no implicit new issue',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id);f.faults.set('prepare:after',()=>{throw Error(RAW);});await f.c.run(op);f.advance(TTL+1);f.restart();publicResult(await f.c.run(op),'expired');assert.equal(f.phase(op),'expired');assert.equal(f.row(op).candidate_ciphertext,null);assert.equal(f.events.filter(e=>e.type==='commit_read').length,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM crm_manager_operations_v1').get().n,1);assert.notEqual(f.j.retryIssue(id).operationId,op);
});
test('prepared restart restores the client-branded proof through STATUS before commit',async t=>{
 const f=fixture(t),op=f.start(f.add());await f.stagePrepared(op);f.restart();publicResult(await f.c.run(op),'ready');const s=f.events.find(e=>e.type==='status:prepare_read');assert.equal(s.requireFound,true);assert.equal(f.events.filter(e=>e.type==='prepare_read').length,1);
});
test('attested restart persists commit intent before restoring prepare proof',async t=>{
 const f=fixture(t),op=f.start(f.add());await f.stageAttested(op);f.restart();f.faults.set('status:before',()=>assert.equal(f.phase(op),'commit_uncertain'));publicResult(await f.c.run(op),'ready');assert.equal(f.events.filter(e=>e.type==='attest').length,0);
});
test('commit failure before execution consults commit STATUS then safely repeats same commit ID',async t=>{
 const f=fixture(t),op=f.start(f.add());f.faults.set('commit:before',()=>{throw Error(RAW);});publicResult(await f.c.run(op),'pending');assert.equal(f.phase(op),'commit_uncertain');const commitId=f.row(op).commit_operation_id;f.restart();const index=f.events.length;publicResult(await f.c.run(op),'ready');assert.equal(f.events[index].type,'status:commit_read');const commits=f.events.filter(e=>e.type==='commit_read');assert.equal(commits.length,2);assert.deepEqual(commits[0].args,commits[1].args);assert.equal(commits[1].args.operationId,commitId);
});
test('lost commit ACK recovers a historical committed receipt after candidate TTL',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id);f.faults.set('commit:after',()=>{throw Error(RAW);});publicResult(await f.c.run(op),'pending');f.advance(TTL+1);f.restart();publicResult(await f.c.run(op),'ready');assert.equal(f.j.credentialReady(id),true);assert.equal(f.events.filter(e=>e.type==='commit_read').length,1);assert.equal(f.events.filter(e=>e.type==='expireCandidate').length,0);
});
test('uncertain commit absent after TTL stays pending and keeps encrypted candidate intact',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id);f.faults.set('commit:before',()=>{throw Error(RAW);});await f.c.run(op);const cipher=f.row(op).candidate_ciphertext;f.advance(TTL+1);f.restart();publicResult(await f.c.run(op),'pending');assert.equal(f.phase(op),'commit_uncertain');assert.equal(f.row(op).candidate_ciphertext,cipher);assert.equal(f.events.filter(e=>e.type==='commit_read').length,1);assert.equal(f.events.filter(e=>e.type==='expireCandidate').length,0);assert.throws(()=>f.j.retryIssue(id),/OPERATION_PENDING/);
});
test('committed restart only promotes locally; promoted operation is a closed no-op',async t=>{
 const f=fixture(t),op=f.start(f.add());await f.stageCommitted(op);f.restart();const index=f.events.length;publicResult(await f.c.run(op),'ready');assert.deepEqual(f.events.slice(index).map(e=>e.type),['promote']);const after=f.events.length;publicResult(await f.c.run(op),'ready');assert.equal(f.events.length,after);
});
test('known prepared and attested expiry is closed locally before any remote work',async t=>{
 for(const attested of[false,true]){const f=fixture(t),op=f.start(f.add());await (attested?f.stageAttested(op):f.stagePrepared(op));f.advance(TTL);const index=f.events.length;publicResult(await f.c.run(op),'expired');assert.deepEqual(f.events.slice(index).map(e=>e.type),['expireCandidate']);}
});
test('attestation is exact: wrong owner, principal, capability CSV, widened caps or nested secrets refuse',async t=>{
 for(const patch of[{owner:'wrong@example.test'},{principalId:'dcrm-'+'f'.repeat(32)},{caps:[CAPS.join(',')]},{caps:[...CAPS,'crm_send']},{secret:{nested:RAW}}]){const f=fixture(t),op=f.start(f.add());await f.stagePrepared(op);const c=f.make({attest:async input=>({owner:input.owner,principalId:input.principalId,caps:[...CAPS],...patch})});publicResult(await c.run(op),'pending');assert.equal(f.phase(op),'prepared');assert.equal(f.events.filter(e=>e.type==='commit_read').length,0);}
});
test('attestation timeout returns a closed pending result and never retries automatically',async t=>{
 const f=fixture(t),op=f.start(f.add());f.faults.set('attest:before',()=>{throw Error(RAW);});const value=await f.c.run(op);publicResult(value,'pending');assert.equal(f.phase(op),'prepared');assert.equal(f.events.filter(e=>e.type==='attest').length,1);assert.equal(JSON.stringify(value).includes(RAW),false);publicResult(await f.c.run(op),'ready');assert.equal(f.events.filter(e=>e.type==='attest').length,2);
});
test('attestation finishing after candidate TTL expires locally without commit or getter capabilities',async t=>{
 const f=fixture(t),op=f.start(f.add());f.faults.set('attest:before',()=>f.advance(TTL));publicResult(await f.c.run(op),'expired');assert.equal(f.phase(op),'expired');assert.equal(f.events.filter(e=>e.type==='commit_read').length,0);assert.equal(f.events.filter(e=>e.type==='recordAttestation').length,0);
 const other=fixture(t),next=other.start(other.add());await other.stagePrepared(next);let reads=0;const badCaps=[...CAPS];Object.defineProperty(badCaps,'0',{enumerable:true,get(){reads++;return CAPS[0];}});const c=other.make({attest:async input=>({owner:input.owner,principalId:input.principalId,caps:badCaps})});publicResult(await c.run(next),'pending');assert.equal(reads,0);assert.equal(other.phase(next),'prepared');
});
test('revocation during prepare await blocks local receipt and outbox later compensates same lifecycle',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id),g=gate();f.faults.set('prepare:after',()=>g.promise);const run=f.c.run(op);await tick();const rev=f.revoke(id);g.resolve();publicResult(await run,'pending');assert.equal(f.phase(op),'prepare_uncertain');publicResult(await f.c.run(rev),'revoked');assert.equal(f.phase(op),'failed');assert.equal(f.j.credentialReady(id),false);
});
test('revocation during attestation await blocks attestation and commit',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id),g=gate();f.faults.set('attest:before',()=>g.promise);const run=f.c.run(op);await tick();const rev=f.revoke(id);g.resolve();publicResult(await run,'pending');assert.equal(f.phase(op),'prepared');assert.equal(f.events.filter(e=>e.type==='recordAttestation').length,0);assert.equal(f.events.filter(e=>e.type==='commit_read').length,0);publicResult(await f.c.run(rev),'revoked');
});
test('revocation during commit await prevents promotion and preserves another manager and administrator',async t=>{
 const f=fixture(t),other=f.add(),otherOp=f.start(other);await f.c.run(otherOp);const admin=f.add('superadmin');f.db.prepare('INSERT INTO upstream_credentials VALUES(?,?,?,?,?)').run(admin,'crm-panel-read','SYNTHETIC_ADMIN_CIPHER','SYNTHETIC_ADMIN_DIGEST',1);const baseline=f.db.prepare('SELECT * FROM upstream_credentials ORDER BY user_id').all();const id=f.add(),op=f.start(id),g=gate();f.faults.set('commit:after',()=>g.promise);const run=f.c.run(op);await tick();const rev=f.revoke(id);g.resolve();publicResult(await run,'pending');assert.equal(f.phase(op),'commit_uncertain');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM upstream_credentials WHERE user_id=?').get(id).n,0);publicResult(await f.c.run(rev),'revoked');assert.deepEqual(f.db.prepare('SELECT * FROM upstream_credentials ORDER BY user_id').all(),baseline);
});
test('revocation lost ACK resumes through STATUS using the durable revoke operation ID',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id);await f.stagePrepared(op);const rev=f.revoke(id);f.faults.set('revoke:after',()=>{throw Error(RAW);});publicResult(await f.c.run(rev),'pending');assert.equal(f.phase(rev),'revoke_pending');f.restart();publicResult(await f.c.run(rev),'revoked');assert.equal(f.events.filter(e=>e.type==='revoke_read').length,1);assert.equal(f.row(rev).candidate_ciphertext,null);assert.equal(f.events.filter(e=>e.type==='status:revoke_read').length,2);
});
test('historical revoke compensation ignores current=false and cannot touch a reinvited lifecycle',async t=>{
 const f=fixture(t),id=f.add(),old=f.start(id);await f.stagePrepared(old);const rev=f.revoke(id);await f.c.run(rev);f.db.prepare("UPDATE users SET state='invited' WHERE id=?").run(id);const next=f.start(id);await f.c.run(next);const baseline=f.db.prepare('SELECT * FROM upstream_credentials WHERE user_id=?').get(id),newLifecycle=f.j.request(rev).lifecycleId;assert.notEqual(f.row(next).lifecycle_id,newLifecycle);
 // Replay a historical outbox intent in a synthetic fixture after reinvite.
 f.db.prepare("UPDATE crm_manager_operations_v1 SET phase='revoke_pending' WHERE operation_id=?").run(rev);assert.equal(f.j.operationState(rev).current,false);publicResult(await f.c.run(rev),'revoked');assert.equal(f.j.credentialReady(id),true);assert.deepEqual(f.db.prepare('SELECT * FROM upstream_credentials WHERE user_id=?').get(id),baseline);
});
test('one operation in flight coalesces same ID and refuses another without automatic queueing',async t=>{
 const f=fixture(t),op=f.start(f.add()),other=f.start(f.add()),g=gate();f.faults.set('prepare:before',()=>g.promise);const a=f.c.run(op),b=f.c.run(op);assert.equal(a,b);await tick();publicResult(await f.c.run(other),'pending');assert.equal(f.phase(other),'queued');g.resolve();publicResult(await a,'ready');publicResult(await b,'ready');assert.equal(f.events.filter(e=>e.type==='prepare_read').length,1);publicResult(await f.c.run(other),'ready');
});
test('closed adapters, invalid IDs and clocks refuse without secret output or remote calls',async t=>{
 const f=fixture(t),op=f.start(f.add());for(const getOperationState of[()=>({...f.j.operationState(op),key:RAW}),async()=>f.j.operationState(op),()=>({...f.j.operationState(op),phase:'raw_sql'})]){const c=f.make({getOperationState});publicResult(await c.run(op),'pending');}publicResult(await f.c.run(undefined),'pending');publicResult(await f.c.run('unknown '+RAW),'pending');publicResult(await f.c.run(crypto.randomUUID()),'pending');publicResult(await f.make({now:()=>{throw Error(RAW);}}).run(op),'pending');assert.equal(f.events.length,0);assert.equal(f.phase(op),'queued');assert.throws(()=>f.make({scheduler:true}),e=>e.code==='MANAGED_COORDINATOR_REFUSED'&&!e.message.includes(RAW));
});
test('prepare proof restored for commit must match persisted scope and dates',async t=>{
 for(const patch of[{caps:[CAPS.join(',')]},{principalId:'dcrm-'+'e'.repeat(32)},{candidateExpiresAt:1770000000000+TTL+1},{secret:RAW}]){const f=fixture(t),op=f.start(f.add());await f.stageAttested(op);f.ledger.get(op).receipt={...f.ledger.get(op).receipt,...patch};publicResult(await f.c.run(op),'pending');assert.equal(f.phase(op),'commit_uncertain');assert.equal(f.events.filter(e=>e.type==='commit_read').length,0);}
});
test('renewal preserves identity and generation fields; ready slot swaps only after confirmed commit',async t=>{
 const f=fixture(t),id=f.add(),op=f.start(id);await f.c.run(op);const original=f.db.prepare('SELECT * FROM upstream_credentials WHERE user_id=?').get(id),renew=f.j.renew(id).operationId,g=gate();f.faults.set('commit:after',()=>g.promise);const run=f.c.run(renew);await tick();assert.deepEqual(f.db.prepare('SELECT * FROM upstream_credentials WHERE user_id=?').get(id),original);assert.equal(f.j.credentialReady(id),false);g.resolve();publicResult(await run,'ready');const request=f.events.find(e=>e.type==='renew_read').args;assert.equal(request.generation,2);assert.equal(request.expectedGeneration,1);assert.notEqual(f.db.prepare('SELECT * FROM upstream_credentials WHERE user_id=?').get(id).key_digest,original.key_digest);
});
test('rejected synchronous DI cannot crash Node or release raw errors through an unhandled promise',()=>{
 const {spawnSync}=require('node:child_process'),modulePath=require.resolve('./crm-manager-coordinator.cjs');
 const script=`'use strict';const assert=require('node:assert/strict'),{createManagerCoordinator}=require(${JSON.stringify(modulePath)}),NOW=1770000000000,CANARY='ASYNC_PRIVATE_CANARY_NOT_STDERR',uuid=n=>'123e4567-e89b-42d3-a456-'+String(n).padStart(12,'0'),op=uuid(1),r={operationId:op,userId:uuid(2),lifecycleId:uuid(3),owner:'manager@example.test',principalId:'dcrm-'+'a'.repeat(32),keySha256:'b'.repeat(64),generation:1,expectedGeneration:0},desc={action:'commit_read',args:{...r,operationId:uuid(4),prepareOperationId:op,issuedAt:NOW,candidateExpiresAt:NOW+600000,expiresAt:NOW+1209600000}};
 const targets=['getOperationState','now','request','beginPrepare','recordPrepared','candidateForAttestation','recordAttestation','commitDescriptor','beginCommit','recordCommitted','promote','expireCandidate','confirmRevoked'],seen=new Set();
 (async()=>{for(const target of targets){const kind=target==='confirmRevoked'?'revoke':'issue',phase=target==='promote'?'committed':target==='beginCommit'?'attested':['commitDescriptor','recordCommitted'].includes(target)?'commit_uncertain':['candidateForAttestation','recordAttestation','expireCandidate'].includes(target)?'prepared':target==='confirmRevoked'?'revoke_pending':['request','recordPrepared'].includes(target)?'prepare_uncertain':'queued',s={kind,phase,candidateExpiresAt:kind==='revoke'||['queued','prepare_uncertain'].includes(phase)?null:target==='expireCandidate'?NOW:NOW+600000,lifecycleState:kind==='revoke'?'revoking':'provisioning',current:true},journal={request:()=>kind==='revoke'?{operationId:op,userId:r.userId,lifecycleId:r.lifecycleId,owner:r.owner}:r,beginPrepare:()=>({ok:true}),recordPrepared:()=>({ok:true}),candidateForAttestation:()=>'c'.repeat(64),recordAttestation:()=>({ok:true}),commitDescriptor:()=>desc,beginCommit:()=>desc,recordCommitted:()=>({ok:true}),promote:()=>({ok:true}),expireCandidate:()=>({ok:true}),confirmRevoked:()=>({ok:true})},client={prepareRead:async()=>({}),prepareRenewalRead:async()=>({}),operationStatus:async()=>({found:true,receipt:{}}),commitRead:async()=>({}),revokeRead:async()=>({})},options={journal,client,attest:async()=>({owner:r.owner,principalId:r.principalId,caps:['read_content','list_history','submission']}),getOperationState:()=>s,now:()=>NOW};const rejected=()=>{seen.add(target);return Promise.reject(Error(CANARY));};if(['getOperationState','now'].includes(target))options[target]=rejected;else journal[target]=rejected;assert.deepEqual(await createManagerCoordinator(options).run(op),{state:'pending'});}assert.equal(seen.size,targets.length);await new Promise(resolve=>setImmediate(resolve));process.stdout.write('sync DI rejected safely');})().catch(()=>{process.exitCode=2;});`;
 const result=spawnSync(process.execPath,['-e',script],{env:{},encoding:'utf8',maxBuffer:4096});assert.equal(result.status,0,'invalid async private DI must fail closed without crashing');assert.equal(result.stdout,'sync DI rejected safely');assert.equal(result.stderr.includes('ASYNC_PRIVATE_CANARY'),false);
});
