'use strict';
// Entirely in-memory model. Public pins are replaced only in isolated VM test
// source; shipping module has no custom-pins/IO/SQLite verification bypass API.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),zlib=require('node:zlib');
const dir=path.resolve(__dirname,'../../services/dashboard-operational/native-continuity'),production=fs.readFileSync(dir+'/read-only.cjs','utf8'),publicPins=JSON.parse(fs.readFileSync(dir+'/pins.json','utf8'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),canon=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canon).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canon(x[k])).join(',')+'}';
function fixture(){const P=JSON.parse(JSON.stringify(publicPins)),key=Buffer.alloc(32,42),N=1791250900000;let now=N;const files=new Map(),stats=new Map(),fd=new Map(),calls=[],sqlCalls=[],dbs=[],imports=[];let serial=10,fdid=1;
 function put(file,bytes,mode=0o600,dir=false){bytes=Buffer.from(bytes);files.set(file,bytes);stats.set(file,{dev:1,ino:serial++,size:bytes.length,mtimeMs:1,ctimeMs:1,nlink:1,uid:1000,gid:1000,mode,isSymbolicLink:()=>false,isFile:()=>!dir,isDirectory:()=>dir});}
 const sign=(body,domain)=>Buffer.from(canon({body,mac:crypto.createHmac('sha256',key).update(domain+canon(body)).digest('hex')})+'\n');
 const encrypt=text=>{const iv=Buffer.alloc(12,5),c=crypto.createCipheriv('aes-256-gcm',key,iv),cipher=Buffer.concat([c.update(text),c.final()]);return ['v1',iv.toString('base64url'),c.getAuthTag().toString('base64url'),cipher.toString('base64url')].join('.');};
 const master={id:'synthetic-original-master',email:P.owner,role:'superadmin',state:'active',password_hash:'synthetic-hash',totp_secret:encrypt('synthetic-totp')},grants=['growth','organico','influs'].map(area=>({area,can_read:1,can_edit:area==='growth'?1:0}));
 const raw=[{type:'table',name:'sample',tbl_name:'sample',sql:'CREATE TABLE sample(id TEXT)'}],rows=[{id:1n,value:'original'}];const h=crypto.createHash('sha256');h.update(JSON.stringify(raw));h.update(JSON.stringify('sample'));for(const row of rows){h.update(JSON.stringify(Object.entries(row).map(([k,v])=>[k,typeof v==='bigint'?['integer',v.toString()]:v])));h.update('\n');}const fingerprint=h.digest('hex');
 const t=P.transitionHistoricalConfig;function pack(content){const b=Buffer.from(JSON.stringify(content)),wrapper={schema:'shrigma_dashboard_operational_pack_v1',sha256:sha(b),gzipBase64:zlib.gzipSync(b).toString('base64')};return Buffer.from(JSON.stringify(wrapper));}const old=pack(['old-synthetic-pack']),current=pack(['current-synthetic-pack']);t.oldPackSha256=JSON.parse(old).sha256;t.newPackSha256=JSON.parse(current).sha256;t.newPackBytes=current.length;t.newPackTransportSha256=sha(current);P.oldRuntimePackSha256=t.newPackSha256;P.originalConsumedPlan.packSha256=t.newPackSha256;
 const sealBody={schema:'crm-efc-prestart-parity-v2',bindingSha256:t.originalParityConfig.bindingSha256,guardSha256:t.originalParityConfig.guardSha256,paritySha256:fingerprint,sourceMasterId:master.id},seal=sign(sealBody,P.domains.parity);
 const transition={schema:'crm-owned-runtime-pack-transition-v1',originalSealSha256:sha(seal),originalBindingSha256:t.originalParityConfig.bindingSha256,upgradeGuardSha256:t.upgradeGuardSha256,sourceRevision:t.sourceRevision,oldPackSha256:t.oldPackSha256,oldPackTransportSha256:sha(old),newPackSha256:t.newPackSha256,newPackTransportSha256:t.newPackTransportSha256,newPackBytes:t.newPackBytes};
 const plan=P.originalConsumedPlan,observation={schema:'crm-own-master-original-runtime-observation-body-v1',operationId:plan.operationId,issuedAt:N-100000,expiresAt:plan.expiresAt,observerProgramSha256:P.historicalPublicDependencies.observerProgramSha256,attestationSha256:P.historicalPublicDependencies.attestationSha256,imageDigest:plan.imageDigest,nativeAdmissionSha256:plan.nativeAdmissionSha256,sourceOld:{commit:'710ffb49f6c065072c8c073ef8269f8c33b589b7',runtimePackSha256:t.oldPackSha256},sourceNew:{commit:t.sourceRevision,runtimePackSha256:t.newPackSha256,ciRuntimeBytes:t.newPackBytes,ciTransportSha256:t.newPackTransportSha256},master:{schema:'crm-own-master-original-runtime-observation-result-v1',profile:'original-owned-runtime-query-only-v1',queryOnly:true,fileSystemReadOnly:false,walAuxiliaryWritesMayOccur:true,state:'observed-compatible',reason:'REQUIRES_NATIVE_SOURCE_AND_INSTALLATION_ADMISSION',sqliteReadOnly:true,originalBindingValid:true,pendingClear:true,nativeAttemptAvailable:true,identityFourCaps:true,snapshotUnchanged:true,catalogs:{fish:{compatible:true},aristo:{compatible:true}},nativeSourcePinsVerified:false,templateBrandExclusivityProven:false,businessMutations:false,iamUsageTelemetryMayUpdate:true}};
 const custody={schema:'crm-own-master-original-runtime-observation-custody-v1',body:observation,bodySha256:sha(canon(observation)),custodyMac:crypto.createHmac('sha256',key).update(P.domains.proof+canon(observation)).digest('hex')},fence={schema:'crm-own-master-startup-fixed-fence-v1',plan,proofSha256:sha(canon(custody))},result={schema:'crm-own-master-startup-result-v1',fenceSha256:sha(canon(fence)),state:'confirmed',code:'NATIVE_WRITER_CONFIRMED',markerConsumed:true,writerVerified:true,confirmedAt:N-1000};
 const historic={'activation-once.json':sign(fence,P.domains.fence),'readonly-observation.json':sign(observation,P.domains.proof),'activation-result.json':sign(result,P.domains.result)};for(const p of P.preservedMasterFiles){const b=historic[p.name];p.bytes=b.length;p.sha256=sha(b);put(P.state+'/'+p.name,b,p.mode);}
 for(const d of [P.root,P.source,P.state])put(d,'',0o700,true);put(P.root+'/.efc-prestart-parity-v2.json',seal);put(P.root+'/runtime-pack.json',current);put(P.root+'/.runtime-pack-'+t.oldPackSha256+'.rollback.json',old);put(P.root+'/.runtime-pack-'+t.sourceRevision+'.transition.json',sign(transition,P.domains.transition));put(P.root+'/dashboard.sqlite','synthetic-target-db');put(P.source+'/dashboard.sqlite','synthetic-source-db');put('/proc/self/mountinfo','1 1 0:1 /src '+P.source+' ro - x x ro\n2 1 0:2 /dst '+P.root+' rw - x x rw\n');
 const marker=encrypt(JSON.stringify({schema:'CRM_NATIVE_OWN_MASTER_SQLITE_WRITER_V1',operationId:plan.operationId,owner:P.owner,action:'install-own-master-campaign-writer',programSha256:plan.programSha256,expiresAt:plan.expiresAt})),credential=encrypt('synthetic-bearer-value'),digest=crypto.createHmac('sha256',key).update('upstream-key:synthetic-bearer-value').digest('hex'),brand=v=>crypto.createHmac('sha256',key).update('identity-brand-v1:'+JSON.stringify(v)).digest('hex');
 const a={user_id:master.id,owner:P.owner,principal_id:'master-'+'a'.repeat(64),credential_mac:digest,key_digest:digest,encrypted_key:credential,attested_at:N-1000,expires_at:N+100000,master_proof_mac:null};a.master_proof_mac=brand(['campaign-master-writer-v1',master.id,master.email,'master','todos',a.principal_id,a.credential_mac,a.expires_at,a.attested_at,['read_content','draft','validate','submit']]);const binding={binding_mac:brand([master.id,master.email,'growth-campaign','all',null,digest,sha(credential)])};
 const state={master,sourceMaster:{...master},grants,attestation:a,binding,marker,sourceRows:rows,credentialReused:false};
 const missing=file=>Object.assign(Error('model missing'),{code:'ENOENT'}),fakeFS={constants:fs.constants,lstatSync:f=>{calls.push(['stat',f]);if(!stats.has(f))throw missing(f);return {...stats.get(f)};},realpathSync:f=>f,readFileSync:f=>{calls.push(['readFile',f]);if(!files.has(f))throw missing(f);return f==='/proc/self/mountinfo'?files.get(f).toString():Buffer.from(files.get(f));},openSync:(f,flags)=>{calls.push(['open',f,flags]);if(flags!==(fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW))throw Error('WRITE_ATTEMPT');if(!files.has(f))throw missing(f);const id=fdid++;fd.set(id,f);return id;},fstatSync:n=>({...stats.get(fd.get(n))}),readSync:(n,b,off,len)=>{const v=files.get(fd.get(n));v.copy(b,off,0,Math.min(v.length,len));return Math.min(v.length,len);},closeSync:n=>{calls.push(['close',fd.get(n)]);fd.delete(n);}};
 class DatabaseSync{constructor(uri,options){calls.push(['dbOpen',uri,options]);if(!uri.endsWith('?immutable=1')||options.readOnly!==true)throw Error('not immutable');this.source=uri.includes(P.source);this.closed=false;dbs.push(this);}close(){this.closed=true;}prepare(q){state.onQuery?.(q);sqlCalls.push(q);if(!/^(SELECT |PRAGMA (integrity_check|foreign_key_check)$)/.test(q))throw Error('SQL_WRITE_ATTEMPT');const self=this;const all=(...params)=>{if(q==='PRAGMA integrity_check')return [{integrity_check:'ok'}];if(q==='PRAGMA foreign_key_check')return [];if(q.startsWith('SELECT type,name'))return raw;if(q==="SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")return [{name:'sample'}];if(q==='SELECT * FROM "sample"')return state.sourceRows;if(q.startsWith('SELECT id,email'))return [self.source?state.sourceMaster:state.master];if(q.startsWith('SELECT area,can_read'))return state.grants;if(q.includes("name='identity_metadata'"))return [{name:'identity_metadata'}];if(q.includes("key='encryption_verifier'"))return [{encrypted_value:encrypt('shrigma-identity-v1')}];if(q==='SELECT encrypted_value FROM identity_metadata WHERE key=?')return state.marker?[{encrypted_value:state.marker}]:[];if(q.startsWith('SELECT a.*'))return state.attestation?[state.attestation]:[];if(q.startsWith('SELECT binding_mac'))return state.binding?[state.binding]:[];if(q.startsWith('SELECT 1 FROM upstream_credentials'))return state.credentialReused?[{n:1}]:[];throw Error('unknown SELECT');};return {all,get:(...params)=>all(...params)[0],iterate:(...params)=>all(...params),setReadBigInts:()=>{}};}}
 const pins=Buffer.from(JSON.stringify(P)),pinHash=sha(pins),code=production.replace(/const PINS_SHA='[a-f0-9]{64}'/,'const PINS_SHA=\''+pinHash+'\'');put(dir+'/pins.json',pins,0o400);put(dir+'/read-only.cjs',code,0o400);
 const context=vm.createContext({Buffer,TextDecoder,URL,console,process:{platform:'linux',arch:'x64',version:'v22.23.3',getuid:()=>1000,getgid:()=>1000,env:{}},module:{exports:{}},__dirname:dir,__filename:dir+'/read-only.cjs',require:name=>{imports.push(name);if(name==='node:fs')return fakeFS;if(name==='node:sqlite')return {DatabaseSync};if(['node:path','node:crypto','node:zlib'].includes(name))return require(name);throw Error('OLD_IMPORT_ATTEMPT');}});vm.runInContext(code,context,{filename:'new-read-only-product.cjs'});const module=context.module.exports,inRealm=v=>{context.wire=JSON.stringify(v);return vm.runInContext('JSON.parse(wire)',context);};const admission=async i=>inRealm({admitted:true,...i,newReleaseRevision:'b'.repeat(40),newReleaseImageDigest:'c'.repeat(64)});
 const create=(extra={})=>module.createReadOnlyContinuity({enabled:true,encryptionKey:key,clock:()=>now,admitNewSource:admission,...extra});const env=()=>inRealm({DASHBOARD_UPSTREAMS:JSON.stringify({'crm-read':P.routes.read}),DASHBOARD_UPSTREAM_HOSTS:JSON.stringify([new URL(P.routes.read).hostname]),SENTINEL_PRIVATE_RAM:'synthetic-only'});
 return {P,key,state,files,stats,calls,sqlCalls,dbs,imports,fd,module,create,env,inRealm,sign,put,sha,canon,advance:n=>{now+=n;},context,production};}
module.exports={fixture};
