'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{EventEmitter}=require('node:events');
const runtime=process.env.SOURCE_DIAGNOSTICS_TEST_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational'),file=path.join(runtime,'native-source-diagnostics.cjs'),D=require(file);
const inputRoot=process.env.SOURCE_DIAGNOSTICS_INPUT_ROOT||path.resolve(__dirname,'../../../..');
const id='c83ab812-d6d8-467e-97b3-02046bbbdcf5',other='66666666-6666-4666-8666-666666666666',raw={brand:'aristo',operationId:id},context={ownerId:'original-master'},password='SyntheticOnly.Password.NeverReturn',timestamp=Date.parse('2026-10-08T20:00:00Z');
const canonical=x=>JSON.stringify(x,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const baseEvidence=()=>({schema:'shrigma-original-last-chunk-read-v1',database:'listmonk',transactionReadOnly:true,operationFound:true,operationId:id,brand:'aristo',originalState:'chunk_uncertain',nextChunk:34,totalChunks:35,lastAttemptIndex:34,storedChunks:34,storedPrefixChunks:34,lastAttemptStored:false,lastAttemptHashMatches:null,productBatchReady:false,originalErrorCode:'CRM_SHOPIFY_CHUNK_UNKNOWN',originalUpdatedAt:'2026-10-08T19:00:00.123456+00:00',completedByOriginal:false,authorizesRecovery:false,authorizesAudienceRefresh:false,operational:false});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
function accelerated(closeBranch=false){const exports={},module={exports},delays=[];new Function('require','module','exports','setTimeout','clearTimeout',fs.readFileSync(file,'utf8'))(require,module,exports,(fn,ms)=>{delays.push(ms);return setTimeout(fn,closeBranch?(ms===60000?200:ms===15000?65:ms===12000?60:ms===5000?30:10):(ms===60000?100:ms===15000?60:10));},clearTimeout);return{D:module.exports,delays};}
function fixture(opts={}){
 const X=opts.D||D,clients=[],calls=[],trace=[],gates=[],profiles=[];let revision=1;
 const profile=()=>({schema:'shrigma-private-database-credential-v1',revision,ownerId:context.ownerId,username:'fixture_reader',password,resource:{...X.RESOURCE},transport:{mode:'admitted-private-network'}});
 class Client extends EventEmitter{
  constructor(config){super();this.config=config;this.connection=new EventEmitter();this.connection.stream={encrypted:opts.encrypted||false};this.processID=1234;this.ends=0;clients.push(this);trace.push('construct');}
  ack(status,sql){if(opts.missingAck===sql)return;this.connection.emit('readyForQuery',{status:opts.wrongAck===sql?'E':status});if(opts.doubleAck===sql)this.connection.emit('readyForQuery',{status});}
  async connect(){trace.push('connect');opts.connectEntered?.resolve();if(opts.connectThrow)throw Error(password);if(opts.connectWait)await opts.connectWait.promise;this.ack('I','connect');}
  async query(q){const sql=typeof q==='string'?q:q.text;calls.push(q);trace.push(sql===X.PEER?'peer':sql===X.BEGIN?'begin':sql===X.ROLLBACK?'rollback':'read');if(opts.queryHook)await opts.queryHook(q,this);if(opts.queryThrow===sql)throw Error(password);if(opts.holdRead&&sql===X.READ_SQL){opts.entered?.resolve();await opts.holdRead.promise;}if(opts.hang===sql)await new Promise(()=>{});
   let r,status;
   if(sql===X.PEER){status='I';r={command:'SELECT',rowCount:1,rows:[{database:'listmonk',sessionRole:'fixture_reader',currentRole:'fixture_reader',pid:1234,port:5432,engine:170005,ssl:false,read_only:'on',...(opts.peer||{})}]};}
   else if(sql===X.BEGIN){status='T';r={command:'BEGIN',rowCount:null,rows:[]};}
   else if(sql===X.ROLLBACK){status='I';r={command:'ROLLBACK',rowCount:null,rows:[]};}
   else{assert.equal(sql,X.READ_SQL);assert.deepEqual(q.values,[id,'aristo']);status='T';r={command:'SELECT',rowCount:1,rows:[{original_chunk_evidence:{...baseEvidence(),...(opts.evidence||{})},...(opts.rowExtra||{})}]};}
   if(opts.result)r=opts.result(sql,r);this.ack(status,sql);return r;
  }
  async end(){this.ends++;trace.push('end');if(opts.endHook)await opts.endHook();if(opts.endThrow)throw Error(password);if(opts.endHang)await new Promise(()=>{});if(!opts.noEndEvent)this.emit('end');}
 }
 const args={enabled:true,driver:{Client,version:opts.version||'8.23.1',packageSha256:'a'.repeat(64)},getPrivateCredential:async value=>{assert.deepEqual(value,context);profiles.push(value);if(opts.credentialThrow)throw Error(password);return{...profile(),...(opts.credential||{})};},admitDiagnostic:async input=>{gates.push(input);trace.push('gate:'+input.phase);const p=profile(),expected={admitted:true,ownerId:p.ownerId,profileRevision:p.revision,credentialBindingHash:sha(canonical({schema:p.schema,revision:p.revision,ownerId:p.ownerId,username:p.username,resource:p.resource,transport:p.transport})),resourceHash:sha(canonical(X.RESOURCE)),purpose:X.PURPOSE};if(opts.gateHook)await opts.gateHook(input);if(opts.deny===input.phase)throw Error(password);if(opts.badGate===input.phase)return{...expected,purpose:'read-only-migration-inventory'};return opts.gateResult?opts.gateResult(input,expected):expected;},now:()=>opts.clock===undefined?timestamp:opts.clock};
 const service=X.createSourceDiagnostics(args);return{X,service,args,opts,clients,calls,trace,gates,profiles,changeRevision:()=>revision++};
}
const inspect=f=>f.service.inspect(raw,context);
const refused=async(f,code)=>{await assert.rejects(inspect(f),e=>{assert(!String(e).includes(password));if(code)assert.equal(e.code,code);return true;});assert(f.clients.every(c=>c.ends===1));};
test('nine sealed public input pins match independently',()=>{const m=JSON.parse(fs.readFileSync(path.join(inputRoot,'SOURCE-INPUTS.json')));assert.equal(m.files.length,9);for(const f of m.files){const b=fs.readFileSync(path.join(inputRoot,'inputs',f.path));assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);}});
test('fixed SELECT only references existing operation/chunk/batch with parameters, internal hashes only',()=>{assert.equal(D.PURPOSE,'read-only-source-commit-diagnostics');assert.equal(D.BEGIN,'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');assert.equal(D.ROLLBACK,'ROLLBACK');assert(D.READ_SQL.startsWith('WITH original AS'));assert(D.READ_SQL.includes('operation_id = $1::uuid'));assert(D.READ_SQL.includes('brand = $2::text'));assert(D.READ_SQL.includes("kind = 'run'"));assert(!D.READ_SQL.includes(id));for(const forbidden of [/\b(?:UPDATE|DELETE|INSERT|CREATE|ALTER|DROP|CALL|SET|COMMIT)\b/i,/FOR\s+UPDATE/i,/chunk_status/i,/customers/i,/idempotency_key/i,/lease/i])assert(!forbidden.test(D.READ_SQL));assert(D.READ_SQL.includes('c.payload_sha256 = o.last_chunk_sha256'));assert(!D.READ_SQL.includes("'last_chunk_sha256'"));});
test('default OFF and wrong pinned version require no credential or session',async()=>{const f=fixture();const off=D.createSourceDiagnostics({...f.args,enabled:undefined});await assert.rejects(off.inspect(raw,context),{code:'DIAGNOSTIC_OFF'});assert.equal(f.profiles.length,0);assert.equal(f.clients.length,0);const wrong=fixture({version:'8.22.0'});await assert.rejects(inspect(wrong),{code:'DIAGNOSTIC_OFF'});assert.equal(wrong.clients.length,0);});
test('34 prefix /35 total with last absent yields compact evidence, no completion or recovery',async()=>{const f=fixture(),r=await inspect(f);assert.equal(r.operation.storedPrefixChunks,34);assert.equal(r.operation.totalChunks,35);assert.equal(r.operation.lastAttemptStored,false);assert.equal(r.operation.lastAttemptHashMatches,null);assert.equal(r.operation.completedByOriginal,false);assert.equal(r.checkedAt,'2026-10-08T20:00:00.000Z');assert.equal(r.authorizesRecovery,false);assert.equal(r.authorizesAudienceRefresh,false);assert.equal(r.operational,false);assert(Object.isFrozen(r)&&Object.isFrozen(r.operation));assert.deepEqual(f.trace,['gate:connect','construct','connect','peer','gate:read','begin','read','rollback','end','gate:release']);assert.equal(f.calls.length,4);assert.equal(f.clients[0].ends,1);assert(!JSON.stringify(r).includes(password));});
test('driver options fixed private peer and READ ONLY timeouts/search path; canonical gates exclude password',async()=>{const f=fixture();await inspect(f);const c=f.clients[0].config;assert.equal(c.password,password);assert.equal(c.host,D.RESOURCE.host);assert.equal(c.database,'listmonk');assert.equal(c.ssl,false);assert.equal(c.pipeline,false);assert.equal(c.query_timeout,12000);assert.equal(c.statement_timeout,8000);assert.equal(c.lock_timeout,2000);assert(c.options.includes('default_transaction_read_only=on'));assert(c.options.includes('search_path=pg_catalog'));assert.deepEqual(f.gates.map(g=>g.phase),['connect','read','release']);for(const g of f.gates){assert.equal(g.purpose,D.PURPOSE);assert.equal(g.ownerId,context.ownerId);assert(/^[a-f0-9]{64}$/.test(g.credentialBindingHash));assert.equal(g.resourceHash,sha(canonical(D.RESOURCE)));assert(!JSON.stringify(g).includes(password));assert.deepEqual(Object.keys(g).sort(),['phase','ownerId','profileRevision','credentialBindingHash','resourceHash','purpose',...(g.phase==='connect'?[]:['peer'])].sort());}assert(Object.isFrozen(f.gates[1].peer));});
for(const matches of [true,false])test('last present with hash '+matches+' does not complete chunk_uncertain',async()=>{const f=fixture({evidence:{storedChunks:35,lastAttemptStored:true,lastAttemptHashMatches:matches}}),r=await inspect(f);assert.equal(r.operation.lastAttemptHashMatches,matches);assert.equal(r.operation.originalState,'chunk_uncertain');assert.equal(r.operation.completedByOriginal,false);});
test('ready=true and next=total never manufactures completion',async()=>{const f=fixture({evidence:{nextChunk:35,storedChunks:35,storedPrefixChunks:35,lastAttemptStored:true,lastAttemptHashMatches:true,productBatchReady:true}}),r=await inspect(f);assert.equal(r.operation.completedByOriginal,false);assert.equal(r.operation.originalState,'chunk_uncertain');});
test('completion is only original completed state',async()=>{const f=fixture({evidence:{originalState:'completed',nextChunk:35,storedChunks:35,storedPrefixChunks:35,lastAttemptStored:true,lastAttemptHashMatches:true,productBatchReady:true,completedByOriginal:true,originalErrorCode:null}}),r=await inspect(f);assert.equal(r.operation.completedByOriginal,true);assert.equal(r.authorizesRecovery,false);});
test('unknown nullable evidence stays null, never false or fabricated zero',async()=>{const f=fixture({evidence:{originalState:'claimed',nextChunk:0,totalChunks:null,lastAttemptIndex:null,storedChunks:0,storedPrefixChunks:0,lastAttemptStored:false,lastAttemptHashMatches:null,productBatchReady:null,originalErrorCode:null}}),r=await inspect(f);assert.equal(r.operation.totalChunks,null);assert.equal(r.operation.lastAttemptIndex,null);assert.equal(r.operation.productBatchReady,null);assert.equal(r.operation.lastAttemptHashMatches,null);});
test('operation absent means fields null only and no inference about another brand',async()=>{const absent={operationFound:false,completedByOriginal:false};for(const k of ['operationId','brand','originalState','nextChunk','totalChunks','lastAttemptIndex','storedChunks','storedPrefixChunks','lastAttemptStored','lastAttemptHashMatches','productBatchReady','originalErrorCode','originalUpdatedAt'])absent[k]=null;const f=fixture({evidence:absent}),r=await inspect(f);assert.deepEqual(r.operation,absent);assert.equal(r.operational,false);});
for(const delta of [{operationId:other},{brand:'fish'},{nextChunk:-1},{nextChunk:51},{nextChunk:'34'},{totalChunks:0},{totalChunks:51},{nextChunk:36},{lastAttemptIndex:35},{lastAttemptIndex:-1},{storedChunks:51},{storedPrefixChunks:35},{storedPrefixChunks:33,storedChunks:32},{lastAttemptStored:false,lastAttemptHashMatches:true},{lastAttemptStored:true,storedChunks:0,storedPrefixChunks:0},{completedByOriginal:true},{originalState:'completed',completedByOriginal:true},{originalUpdatedAt:'2026-02-30T10:00:00Z'},{originalErrorCode:'raw error '+password},{originalErrorCode:'x'.repeat(81)},{transactionReadOnly:false},{authorizesRecovery:true},{operationFound:false},{privatePassword:password}])test('incoherent/extra/wrong identity evidence refused '+Object.keys(delta).join(','),async()=>{await refused(fixture({evidence:delta}));});
for(const phase of ['connect','read','release'])test('CURRENT admission refusal '+phase+' closes and suppresses result',async()=>{const f=fixture({deny:phase});await refused(f,'DIAGNOSTIC_ADMISSION_REFUSED');assert.equal(f.clients.length,phase==='connect'?0:1);assert.equal(f.calls.filter(q=>typeof q!=='string'&&q.text===D.READ_SQL).length,phase==='release'?1:0);if(phase==='release')assert(f.calls.includes(D.ROLLBACK));});
test('credential revision changed by release gate invalidates expected binding and suppresses result',async()=>{const f=fixture();f.opts.gateHook=g=>{if(g.phase==='read')f.changeRevision();};await refused(f,'DIAGNOSTIC_ADMISSION_REFUSED');assert(f.calls.includes(D.ROLLBACK));});
test('inventory purpose is not diagnostic admission',async()=>{await refused(fixture({badGate:'connect'}),'DIAGNOSTIC_ADMISSION_REFUSED');});
for(const p of [{read_only:'off'},{database:'other'},{sessionRole:'other'},{currentRole:'other'},{pid:5},{port:5433},{engine:160010},{ssl:true}])test('wrong fixed peer refuses '+JSON.stringify(p),async()=>{await refused(fixture({peer:p}),'DIAGNOSTIC_PEER_REFUSED');});
for(const location of ['connect','peer','begin','read','rollback'])test('ambiguous duplicate ACK refused at '+location,async()=>{const q=location==='connect'?'connect':D[location==='peer'?'PEER':location==='read'?'READ_SQL':location.toUpperCase()];await refused(fixture({doubleAck:q}));});
test('wrong transaction ACK closes before returning even valid rows',async()=>{await refused(fixture({wrongAck:D.READ_SQL}),'DIAGNOSTIC_SESSION_REFUSED');});
test('missing ACK times out and closes rather than trusting rows',async()=>{const fast=accelerated(),f=fixture({D:fast.D,missingAck:fast.D.READ_SQL});await refused(f,'DIAGNOSTIC_TIMEOUT');assert(fast.delays.includes(2000));});
test('query timeout closes, never repeats SELECT or yields partial progress',async()=>{const fast=accelerated(),f=fixture({D:fast.D,hang:fast.D.READ_SQL});await refused(f,'DIAGNOSTIC_QUERY_FAILED');assert.equal(f.calls.filter(q=>q.text===D.READ_SQL).length,1);assert(fast.delays.includes(12000));});
test('end failure suppresses otherwise valid result and blocks future sessions',async()=>{const f=fixture({endThrow:true});await refused(f,'DIAGNOSTIC_CLOSE_FAILED');await assert.rejects(inspect(f),{code:'DIAGNOSTIC_UNAVAILABLE'});await assert.rejects(f.service.close(),{code:'DIAGNOSTIC_CLOSE_UNCONFIRMED'});assert.equal(f.clients.length,1);});
test('end promise without end event is unconfirmed, never accepted',async()=>{await refused(fixture({noEndEvent:true}),'DIAGNOSTIC_CLOSE_UNCONFIRMED');});
test('hanging end times out and permanently closes admission',async()=>{const fast=accelerated(),f=fixture({D:fast.D,endHang:true});await refused(f,'DIAGNOSTIC_TIMEOUT');await assert.rejects(inspect(f),{code:'DIAGNOSTIC_UNAVAILABLE'});});
test('one active session refuses concurrency; close waits, is idempotent and prevents later inspect',async()=>{const holdRead=deferred(),entered=deferred(),f=fixture({holdRead,entered});const pending=inspect(f);await entered.promise;await assert.rejects(inspect(f),{code:'DIAGNOSTIC_BUSY'});const closing=f.service.close();assert.equal(f.service.close(),closing);await assert.rejects(inspect(f),{code:'DIAGNOSTIC_UNAVAILABLE'});holdRead.resolve();await pending;assert.deepEqual(await closing,{closed:true,operational:false});assert.equal(f.clients.length,1);assert.equal(f.clients[0].ends,1);});
for(const q of [{...raw,sql:'DROP TABLE users'},{...raw,url:'https://foreign.invalid'},{...raw,ownerId:'foreign'},{...raw,operationId:'not-a-uuid'},{...raw,brand:'other'}])test('raw input exact rejects extras/identity '+Object.keys(q).join(','),async()=>{const f=fixture();await assert.rejects(f.service.inspect(q,context));assert.equal(f.clients.length,0);assert.equal(f.profiles.length,0);});
test('hidden/accessor/symbol input and extra context refuse before credentials',async()=>{const f=fixture();const hidden={...raw};Object.defineProperty(hidden,'secret',{value:password});const accessor={brand:'aristo',get operationId(){assert.fail('getter must not execute');}};const symbol={...raw,[Symbol('actor')]:password};for(const q of [hidden,accessor,symbol])await assert.rejects(f.service.inspect(q,context));await assert.rejects(f.service.inspect(raw,{...context,actor:'other'}));assert.equal(f.profiles.length,0);});
for(const bad of [{password:''},{resource:{...D.RESOURCE,database:'other'}},{transport:{mode:'public'}},{revision:0},{secret:password}])test('private credential profile exact/refused '+Object.keys(bad).join(','),async()=>{await refused(fixture({credential:bad}),'DIAGNOSTIC_CREDENTIAL_REFUSED');});
test('driver SQL response extra fields/multiple rows/incorrect command rejected',async()=>{for(const result of [(sql,r)=>sql===D.READ_SQL?{...r,rows:[...r.rows,...r.rows],rowCount:2}:r,(sql,r)=>sql===D.READ_SQL?{...r,command:'UPDATE'}:r])await refused(fixture({result}));await refused(fixture({rowExtra:{password}}));});
test('clock invalid suppresses result despite successful read and release',async()=>{await refused(fixture({clock:NaN}),'DIAGNOSTIC_CLOCK_REFUSED');});
test('query/provider failures contain only fixed error code, never private error text',async()=>{for(const opts of [{queryThrow:D.READ_SQL},{credentialThrow:true},{connectThrow:true}])await refused(fixture(opts));});
test('forced close confirms end before pending peer timeout and never emits partial evidence',async()=>{const fast=accelerated(true),connectWait=deferred(),connectEntered=deferred(),f=fixture({D:fast.D,connectWait,connectEntered,hang:fast.D.PEER});const pending=inspect(f);const rejection=assert.rejects(pending);await connectEntered.promise;const closing=f.service.close();setTimeout(()=>connectWait.resolve(),15);assert.deepEqual(await closing,{closed:true,operational:false});assert.equal(f.clients[0].ends,1);await rejection;assert(fast.delays.includes(15000));assert.equal(f.calls.filter(q=>q===fast.D.PEER).length,1);assert.equal(f.calls.filter(q=>q.text===fast.D.READ_SQL).length,0);});
for(const phase of ['connect','read','release'])test('gate answer private extra/binding mismatch refused '+phase,async()=>{for(const change of [{password},{credentialBindingHash:'f'.repeat(64)},{resourceHash:'f'.repeat(64)},{ownerId:'other'}])await refused(fixture({gateResult:(input,expected)=>input.phase===phase?{...expected,...change}:expected}));});

test('credential revocation/change during end await is caught by final CURRENT release gate',async()=>{const f=fixture();f.opts.endHook=async()=>{await Promise.resolve();f.changeRevision();};await refused(f,'DIAGNOSTIC_ADMISSION_REFUSED');assert.equal(f.trace.at(-1),'gate:release');assert.equal(f.clients[0].ends,1);});
