'use strict';
const C=require('./catalog.cjs'),S=require('./sql.cjs'),physical=new WeakMap(),errors=new WeakSet();
const HASH=/^[a-f0-9]{64}$/,UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/,NAME=/^[a-z][a-z0-9_]{0,62}$/;
const flags={sourceOnly:true,operational:false,productionAdmitted:false,authorizesCRM:false,automaticReplay:false};
function fail(code='INSTALLER_REFUSED'){const e=Object.assign(new Error(code),{code});errors.add(e);return e;}
function capture(x){if(x===null||typeof x==='string'||typeof x==='boolean'||typeof x==='number'&&Number.isFinite(x))return x;if(Array.isArray(x)){if(x.length>1000)throw fail();return x.map(capture);}if(!x||typeof x!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(x)))throw fail();const o={};for(const k of Object.keys(x).sort()){const d=Object.getOwnPropertyDescriptor(x,k);if(!d||!Object.hasOwn(d,'value')||['__proto__','prototype','constructor'].includes(k))throw fail();o[k]=capture(d.value);}return o;}
const canonical=x=>JSON.stringify(capture(x)),digest=x=>C.hash(canonical(x));
function exact(x,keys){if(!x||Array.isArray(x)||typeof x!=='object'||Object.keys(x).sort().join(',')!==[...keys].sort().join(','))throw fail('INSTALLER_INPUT_REFUSED');}
function targetDTO(x){const t=capture(x);exact(t,['project','service','database','ownNamespace','installerRole','runtimeRole']);if(t.project!=='comunicacao'||t.service!=='postgres'||t.database!=='listmonk'||![t.ownNamespace,t.installerRole,t.runtimeRole].every(x=>typeof x==='string'&&NAME.test(x))||t.ownNamespace==='public'||t.ownNamespace.startsWith('pg_')||t.installerRole===t.runtimeRole)throw fail('INSTALLER_TARGET_REFUSED');return Object.freeze(t);}
const names=[...new Set(C.manifest().migrations.flatMap(m=>m.ownPublicObjects))].sort(),roles=[...new Set(C.manifest().migrations.flatMap(m=>m.creates.roles).concat('central_leitor'))].sort();
const columns=['operation_id:uuid:true','migration_id:text:true','source_sha256:text:true','request_sha256:text:true','target_sha256:text:true','manifest_sha256:text:true','state:text:true','attempted_at:timestamp with time zone:true','applied_at:timestamp with time zone:false'];
function ledgerOK(l,t){return l&&l.owner===t.installerRole&&l.kind==='r'&&l.persistent===true&&l.rls===false&&l.triggers===false&&l.inheritance===false&&l.otherAccess===false&&Array.isArray(l.columns)&&l.columns.map(c=>c.name+':'+c.type+':'+c.notNull).join('|')===columns.join('|')&&Array.isArray(l.constraints)&&l.constraints.length===3&&l.constraints.some(c=>c.kind==='p'&&c.sha256===C.hash('PRIMARY KEY (operation_id)'))&&l.constraints.some(c=>c.kind==='u'&&c.sha256===C.hash('UNIQUE (migration_id)'))&&l.constraints.some(c=>c.kind==='c'&&c.sha256===C.hash("CHECK ((state = ANY (ARRAY['attempted'::text, 'applied'::text])))"));}
// Closed metadata DTO: an unexpected driver field is never echoed as inventory.
function inventoryDTO(v){
 exact(v,['database','sessionRole','currentRole','engine','runtimeInstallationRights','installerSuper','installerCreateRole','databaseCreate','databaseOwner','ownSchema','publicCreate','publicCreateExposed','databaseCreateExposed','security','relations','functions','types','roles','defaultGrants','otherPublicRelationCount','ledger']);
 for(const k of ['database','sessionRole','currentRole','databaseOwner'])if(typeof v[k]!=='string'||!NAME.test(v[k]))throw fail('INSTALLER_INVENTORY_REFUSED');
 for(const k of ['runtimeInstallationRights','installerSuper','installerCreateRole','databaseCreate','publicCreate','publicCreateExposed','databaseCreateExposed'])if(typeof v[k]!=='boolean')throw fail('INSTALLER_INVENTORY_REFUSED');
 if(v.ownSchema!==null){exact(v.ownSchema,['name','owner','create','otherCreate']);if(!NAME.test(v.ownSchema.name)||!NAME.test(v.ownSchema.owner)||typeof v.ownSchema.create!=='boolean'||typeof v.ownSchema.otherCreate!=='boolean')throw fail('INSTALLER_INVENTORY_REFUSED');}
 exact(v.security,['tls','statementLoggingOff','parameterLoggingOff','errorParameterLoggingOff']);if(Object.values(v.security).some(x=>typeof x!=='boolean'))throw fail('INSTALLER_INVENTORY_REFUSED');
 const checkColumns=cols=>{if(!Array.isArray(cols))throw fail('INSTALLER_INVENTORY_REFUSED');for(const c of cols){exact(c,['name','type','notNull']);if(!NAME.test(c.name)||typeof c.type!=='string'||c.type.length>100||typeof c.notNull!=='boolean')throw fail('INSTALLER_INVENTORY_REFUSED');}};
 if(!Array.isArray(v.relations)||!Array.isArray(v.functions)||!Array.isArray(v.roles)||!Array.isArray(v.types)||!Array.isArray(v.defaultGrants)||v.types.some(n=>typeof n!=='string'||!NAME.test(n))||!Number.isSafeInteger(v.otherPublicRelationCount)||v.otherPublicRelationCount<0)throw fail('INSTALLER_INVENTORY_REFUSED');
 for(const r of v.relations){exact(r,['name','owner','kind','persistent','rls','partition','triggers','inheritance','publicAccess','columns']);if(!names.includes(r.name)||!NAME.test(r.owner)||typeof r.kind!=='string'||r.kind.length!==1||['persistent','rls','partition','triggers','inheritance','publicAccess'].some(k=>typeof r[k]!=='boolean'))throw fail('INSTALLER_INVENTORY_REFUSED');checkColumns(r.columns);}
 for(const f of v.functions){exact(f,['name','argumentTypes','owner','definer','bodySha256','safeSearchPath','configSha256','publicExecute']);if(!names.includes(f.name)||!NAME.test(f.owner)||typeof f.argumentTypes!=='string'||f.argumentTypes.length>100||!HASH.test(f.bodySha256)||!HASH.test(f.configSha256)||['definer','safeSearchPath','publicExecute'].some(k=>typeof f[k]!=='boolean'))throw fail('INSTALLER_INVENTORY_REFUSED');}
 for(const r of v.roles){exact(r,['name','login','super','createDB','createRole','inherit','replication','bypassRls','memberships']);if(!NAME.test(r.name)||['login','super','createDB','createRole','inherit','replication','bypassRls'].some(k=>typeof r[k]!=='boolean')||!Number.isSafeInteger(r.memberships)||r.memberships<0)throw fail('INSTALLER_INVENTORY_REFUSED');}
 for(const g of v.defaultGrants){exact(g,['schema','kind','grantee','privilege','grantable']);if(!NAME.test(g.schema)||g.grantee!=='PUBLIC'&&!NAME.test(g.grantee)||typeof g.kind!=='string'||g.kind.length!==1||!['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','EXECUTE','USAGE','CREATE','MAINTAIN'].includes(g.privilege)||typeof g.grantable!=='boolean')throw fail('INSTALLER_INVENTORY_REFUSED');}
 if(v.ledger!==null){exact(v.ledger,['owner','kind','persistent','rls','triggers','inheritance','otherAccess','columns','constraints']);if(!NAME.test(v.ledger.owner)||typeof v.ledger.kind!=='string'||v.ledger.kind.length!==1||['persistent','rls','triggers','inheritance','otherAccess'].some(k=>typeof v.ledger[k]!=='boolean')||!Array.isArray(v.ledger.constraints))throw fail('INSTALLER_INVENTORY_REFUSED');checkColumns(v.ledger.columns);for(const c of v.ledger.constraints){exact(c,['kind','sha256']);if(typeof c.kind!=='string'||c.kind.length!==1||!HASH.test(c.sha256))throw fail('INSTALLER_INVENTORY_REFUSED');}}
 return v;
}
function createInstaller({enabled=false,client,manifest,target,admission,withInstallerSession,poisonSession}={}){
 let t,ready=false;try{t=targetDTO(target);ready=enabled===true&&client&&typeof client.query==='function'&&[admission,withInstallerSession,poisonSession].every(f=>typeof f==='function')&&canonical(manifest)===canonical(C.manifest());}catch{}
 const th=t&&digest(t),sql=t&&S.ledger(t.ownNamespace),lock=t&&Buffer.from(th,'hex');let state;
 if(ready){state=physical.get(client);if(!state){state={busy:false,poisoned:false};physical.set(client,state);}}
 function poison(){state.poisoned=true;try{poisonSession();}catch{}}
 async function use(work){if(!ready)throw fail('INSTALLER_OFF');if(state.poisoned)throw fail('INSTALLER_SESSION_POISONED');if(state.busy)throw fail('INSTALLER_BUSY');state.busy=true;let calls=0,result,inner;try{const outer=await withInstallerSession(async()=>{if(++calls!==1)throw fail('INSTALLER_LEASE_REFUSED');try{result=await work();return result;}catch(e){inner=e;throw e;}});if(calls!==1||outer!==result){poison();throw fail('INSTALLER_LEASE_REFUSED');}return result;}catch(e){if(errors.has(inner||e))throw inner||e;throw fail('INSTALLER_DATABASE_REFUSED');}finally{state.busy=false;}}
 async function query(text,params,command,max=1){const r=await client.query(text,params);if(!r||r.command!==command||!Array.isArray(r.rows)||r.rowCount!==r.rows.length||r.rows.length>max||r.rows.some((_,n)=>!Object.hasOwn(r.rows,n)))throw fail('INSTALLER_PROTOCOL_REFUSED');return r.rows;}
 function ack(r,command){if(!r||r.command!==command||r.rowCount!==null||!Array.isArray(r.rows)||r.rows.length!==0)throw fail('INSTALLER_ACK_UNKNOWN');}
 async function tx(write,work){let started=false,finishing=false;try{started=true;ack(await client.query(write?S.BEGIN_WRITE:S.BEGIN_READ),'BEGIN');const limits=await client.query(S.LIMITS);if(!Array.isArray(limits)||limits.length!==4)throw fail('INSTALLER_PROTOCOL_REFUSED');for(const r of limits)ack(r,'SET');await query(S.LOCK,[lock.readInt32BE(0),lock.readInt32BE(4)],'SELECT');const result=await work();finishing=true;ack(await client.query(write?'COMMIT':'ROLLBACK'),write?'COMMIT':'ROLLBACK');return result;}catch(e){if(finishing){poison();throw fail('INSTALLER_ACK_UNKNOWN');}if(started){try{ack(await client.query('ROLLBACK'),'ROLLBACK');}catch{poison();throw fail('INSTALLER_ACK_UNKNOWN');}}if(e?.code==='INSTALLER_ACK_UNKNOWN'&&errors.has(e))poison();if(e?.code==='ECONNRESET'||e?.code==='ETIMEDOUT'||typeof e?.code==='string'&&e.code.startsWith('08'))poison();throw e;}}
 async function inventory(){const r=await query(S.INVENTORY,[t.ownNamespace,names,[...new Set(roles.concat(t.installerRole,t.runtimeRole))],t.runtimeRole],'SELECT');if(r.length!==1)throw fail('INSTALLER_INVENTORY_REFUSED');const v=inventoryDTO(capture(r[0].inventory));if(v.database!==t.database||v.sessionRole!==t.installerRole||v.currentRole!==t.installerRole||!Number.isInteger(v.engine)||Math.floor(v.engine/10000)!==17||!Array.isArray(v.relations)||!Array.isArray(v.functions)||!Array.isArray(v.roles)||!Array.isArray(v.types)||!Array.isArray(v.defaultGrants)||v.relations.length>names.length||v.functions.length>30)throw fail('INSTALLER_TARGET_REFUSED');return v;}
 async function authorize(action,v,m,op){const input=capture({action,target:t,targetHash:th,manifestHash:C.manifestHash,inventory:v,inventoryHash:digest(v),migrationId:m?.id||null,sourceSha256:m?.sha256||null,operationId:op||null});const p=capture(await admission(input));exact(p,['admitted','action','targetHash','manifestHash','inventoryHash','migrationId','operationId','ownNamespace','installerRole','runtimeRole','ownedPublicObjects','reviewedRoles','inputs','recoveryReady']);if(p.admitted!==true||p.action!==action||p.targetHash!==th||p.manifestHash!==C.manifestHash||p.inventoryHash!==input.inventoryHash||p.migrationId!==input.migrationId||p.operationId!==input.operationId||p.ownNamespace!==t.ownNamespace||p.installerRole!==t.installerRole||p.runtimeRole!==t.runtimeRole||!Array.isArray(p.ownedPublicObjects)||!Array.isArray(p.reviewedRoles)||!p.inputs||p.recoveryReady!==true)throw fail('INSTALLER_ADMISSION_REFUSED');return p;}
 function common(v){const reasons=[];if(!v.ownSchema||v.ownSchema.name!==t.ownNamespace||v.ownSchema.owner!==t.installerRole||v.ownSchema.create!==true||v.ownSchema.otherCreate!==false)reasons.push('OWN_NAMESPACE_NOT_EXCLUSIVE');if(v.ledger&&!ledgerOK(v.ledger,t))reasons.push('LEDGER_SHAPE_OR_OWNERSHIP');const runtime=v.roles.find(r=>r.name===t.runtimeRole);if(v.runtimeInstallationRights!==false||!runtime||runtime.super!==false||runtime.createDB!==false||runtime.createRole!==false||runtime.bypassRls!==false||runtime.replication!==false||Number(runtime.memberships)!==0)reasons.push('RUNTIME_INSTALLATION_SEPARATION');return reasons;}
 function prerequisites(v,p,m){const reasons=common(v);if(v.installerSuper!==true||v.installerCreateRole!==true||v.publicCreate!==true)reasons.push('HISTORICAL_INSTALLER_PRIVILEGES_NOT_PROVED');for(const key of m.requires)if(p.inputs[key]!==true)reasons.push('MISSING_'+key);for(const name of m.ownPublicObjects)if(!p.ownedPublicObjects.includes(name))reasons.push('OWNERSHIP_'+name);for(const name of m.creates.roles)if(!p.reviewedRoles.includes(name))reasons.push('ROLE_'+name);for(const name of ['crm_dash_chave','shrigma_panel_permission_v1']){const r=v.relations.find(r=>r.name===name);if(!r||r.owner!==t.installerRole||r.kind!=='r'||r.persistent!==true||r.rls!==false||r.partition!==false||r.triggers!==false||r.inheritance!==false||r.publicAccess!==false)reasons.push('AUTH_OBJECT_'+name);}
 if(v.publicCreateExposed!==false||v.databaseCreateExposed!==false)reasons.push('PUBLIC_CREATE_EXPOSED');
 if(m.id==='crm-writer-provision-v1'){const table=v.defaultGrants.filter(g=>g.kind==='r'&&g.grantee!=='PUBLIC');if(table.length!==1||table[0].schema!=='public'||table[0].grantee!=='central_leitor'||table[0].privilege!=='SELECT'||table[0].grantable!==false||v.defaultGrants.some(g=>g.kind==='f'&&g.grantee!=='PUBLIC'))reasons.push('WRITER_DEFAULT_ACL_MISMATCH');}
 else if(v.defaultGrants.some(g=>g.grantee!=='PUBLIC'&&(g.kind==='r'||g.kind==='f')))reasons.push('UNREVIEWED_DEFAULT_GRANT');
 if(m.id==='crm-read-role-install-v1'){const required=m.ownPublicObjects.filter(n=>!['crm_dash_chave','shrigma_panel_permission_v1'].includes(n));for(const n of required){const rows=[...v.relations,...v.functions].filter(o=>o.name===n);if(rows.length!==1||rows[0].owner!==t.installerRole)reasons.push('PREREQUISITE_OBJECT_'+n);}}
 else for(const n of [...m.creates.tables,...m.creates.indexes,...m.creates.functions])if([...v.relations,...v.functions].some(o=>o.name===n)||v.types.includes(n))reasons.push('EXISTING_OBJECT_'+n);
 for(const n of m.creates.roles)if(v.roles.some(r=>r.name===n))reasons.push('EXISTING_ROLE_'+n);return [...new Set(reasons)];}
 function request(raw,apply){const i=capture(raw);exact(i,apply?['migrationId','expectedSha256','operationId']:['migrationId','expectedSha256']);const m=typeof i.migrationId==='string'&&C.get(i.migrationId);if(!m||i.expectedSha256!==m.sha256||!HASH.test(i.expectedSha256)||apply&&!UUID.test(i.operationId))throw fail('INSTALLER_MIGRATION_REFUSED');return {i,m};}
 async function dependencies(v,m){if(!m.dependsOn.length)return [];if(!v.ledger)return m.dependsOn.map(x=>'DEPENDENCY_'+x);const rows=await query(sql.dependencies,[m.dependsOn],'SELECT',m.dependsOn.length);return m.dependsOn.filter(id=>!rows.some(r=>r.migration_id===id&&r.source_sha256===C.get(id).sha256&&r.state==='applied')).map(x=>'DEPENDENCY_'+x);}
 function row(r){exact(r,['operation_id','migration_id','source_sha256','request_sha256','target_sha256','manifest_sha256','state','attempted_at','applied_at']);const m=C.get(r.migration_id);if(!UUID.test(r.operation_id)||!m||r.source_sha256!==m.sha256||!HASH.test(r.request_sha256)||r.target_sha256!==th||r.manifest_sha256!==C.manifestHash||!['attempted','applied'].includes(r.state)||typeof r.attempted_at!=='string'||!/^\d{1,16}$/.test(r.attempted_at)||r.state==='attempted'&&r.applied_at!==null||r.state==='applied'&&(typeof r.applied_at!=='string'||!/^\d{1,16}$/.test(r.applied_at)))throw fail('INSTALLER_LEDGER_REFUSED');const expected=digest({targetHash:th,manifestHash:C.manifestHash,migrationId:m.id,sourceSha256:m.sha256,operationId:r.operation_id});if(expected!==r.request_sha256)throw fail('INSTALLER_LEDGER_REFUSED');return r;}
 const receipt=r=>Object.freeze({operationId:r.operation_id,migrationId:r.migration_id,sourceSha256:r.source_sha256,requestSha256:r.request_sha256,targetHash:th,manifestHash:C.manifestHash,state:r.state,attemptedAtMs:r.attempted_at,appliedAtMs:r.applied_at,action:'consult-original',...flags});
 async function inspect(){return use(()=>tx(false,async()=>{const v=await inventory();await authorize('inspect',v);return Object.freeze({target:t,manifestHash:C.manifestHash,inventoryHash:digest(v),inventory:v,blockers:common(v),migrations:C.manifest().migrations.map(({id,sha256,dependsOn,requires,activation})=>({id,sha256,dependsOn,requires,activation})),...flags});}));}
 async function preview(raw){const {m}=request(raw,false);return use(()=>tx(false,async()=>{const v=await inventory(),p=await authorize('preview',v,m),blockers=prerequisites(v,p,m).concat(await dependencies(v,m));return Object.freeze({migrationId:m.id,sourceSha256:m.sha256,executionSha256:m.executionSha256,manifestHash:C.manifestHash,targetHash:th,inventoryHash:digest(v),ready:blockers.length===0,blockers,creates:m.creates,ownPublicObjects:m.ownPublicObjects,requires:m.requires,dependsOn:m.dependsOn,activation:false,...flags});}));}
 async function status(raw){const i=capture(raw);exact(i,['operationId']);if(!UUID.test(i.operationId))throw fail('INSTALLER_INPUT_REFUSED');return use(()=>tx(false,async()=>{const v=await inventory();await authorize('status',v,null,i.operationId);if(common(v).length)throw fail('INSTALLER_LEDGER_REFUSED');if(!v.ledger)return Object.freeze({operationId:i.operationId,found:false,action:'consult-original',...flags});const rows=await query(sql.status,[i.operationId],'SELECT');return rows.length?Object.freeze({found:true,...receipt(row(rows[0]))}):Object.freeze({operationId:i.operationId,found:false,action:'consult-original',...flags});}));}
 async function apply(raw){const {i,m}=request(raw,true),rh=digest({targetHash:th,manifestHash:C.manifestHash,migrationId:m.id,sourceSha256:m.sha256,operationId:i.operationId});return use(async()=>{
  // Irreversible call-owned fence precedes DDL. Same existing database/lease;
  // no continuation token is accepted from API or recovered across processes.
  const prep=await tx(true,async()=>{let v=await inventory();const p=await authorize('apply',v,m,i.operationId);if(common(v).length)throw fail('INSTALLER_PREREQUISITE_REFUSED');if(v.ledger){const old=await query(sql.find,[i.operationId,m.id],'SELECT',2);if(old.length){if(old.length!==1)throw fail('INSTALLER_IDEMPOTENCY_CONFLICT');const r=row(old[0]);if(r.operation_id===i.operationId&&r.request_sha256!==rh)throw fail('INSTALLER_IDEMPOTENCY_CONFLICT');return {consult:receipt(r)};}}
   if(prerequisites(v,p,m).length||(await dependencies(v,m)).length)throw fail('INSTALLER_PREREQUISITE_REFUSED');
   if(!v.ledger){const ddl=await client.query(sql.create);if(!Array.isArray(ddl)||ddl.length!==2)throw fail('INSTALLER_PROTOCOL_REFUSED');ack(ddl[0],'CREATE');ack(ddl[1],'REVOKE');v=await inventory();if(!ledgerOK(v.ledger,t))throw fail('INSTALLER_LEDGER_REFUSED');}
   const rows=await query(sql.insert,[i.operationId,m.id,m.sha256,rh,th,C.manifestHash],'INSERT');if(rows.length!==1)throw fail();return {fence:receipt(row(rows[0]))};
  });if(prep.consult)return prep.consult;
  return tx(true,async()=>{const v=await inventory(),p=await authorize('apply',v,m,i.operationId);if(prerequisites(v,p,m).length||(await dependencies(v,m)).length)throw fail('INSTALLER_PREREQUISITE_REFUSED');const old=await query(sql.find,[i.operationId,m.id],'SELECT',2);if(old.length!==1||row(old[0]).request_sha256!==rh||old[0].state!=='attempted')throw fail('INSTALLER_IDEMPOTENCY_CONFLICT');
   const result=await client.query(m.sql);if(!Array.isArray(result)||!result.length||result.some(r=>!['SET','DO','CREATE','GRANT','ALTER','REVOKE'].includes(r.command)||r.rowCount!==null||!Array.isArray(r.rows)||r.rows.length))throw fail('INSTALLER_PROTOCOL_REFUSED');
   const after=await inventory();const owner=m.createdOwner==='installer'?t.installerRole:m.createdOwner;for(const n of [...m.creates.tables,...m.creates.indexes,...m.creates.functions]){const objs=[...after.relations,...after.functions].filter(o=>o.name===n);if(objs.length!==1||objs[0].owner!==owner)throw fail('INSTALLER_POSTCONDITION_REFUSED');}if(m.id==='crm-read-role-install-v1')for(const n of m.ownPublicObjects.filter(n=>!['crm_dash_chave','shrigma_panel_permission_v1'].includes(n))){const objs=[...after.relations,...after.functions].filter(o=>o.name===n);if(objs.length!==1||objs[0].owner!==owner)throw fail('INSTALLER_POSTCONDITION_REFUSED');}for(const f of after.functions.filter(f=>m.ownPublicObjects.includes(f.name)))if(f.safeSearchPath!==true||f.publicExecute!==false)throw fail('INSTALLER_POSTCONDITION_REFUSED');for(const n of m.creates.roles){const r=after.roles.find(r=>r.name===n);if(!r||r.super!==false||r.createDB!==false||r.createRole!==false||r.inherit!==false||r.replication!==false||r.bypassRls!==false||Number(r.memberships)!==0||r.login!==(n==='crm_manager_provisioner'))throw fail('INSTALLER_POSTCONDITION_REFUSED');}if(common(after).length)throw fail('INSTALLER_POSTCONDITION_REFUSED');if(!ledgerOK(after.ledger,t))throw fail('INSTALLER_POSTCONDITION_REFUSED');await authorize('apply',after,m,i.operationId);
   const rows=await query(sql.applied,[i.operationId,rh],'UPDATE');if(rows.length!==1)throw fail('INSTALLER_POSTCONDITION_REFUSED');return Object.freeze({...receipt(row(rows[0])),action:'applied'});
  });
 });}
 return Object.freeze({inspect,preview,apply,status,capabilities:Object.freeze({enabled:!!ready,arbitrarySQL:false,runtimeInstallation:false,issuerRegistration:false,...flags})});
}
module.exports=Object.freeze({createInstaller,manifest:C.manifest,manifestHash:C.manifestHash,ENABLED:false});
