'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const B=require('./build-compose.cjs');
const read=()=>Object.fromEntries(Object.keys(B.PINS).map(n=>[n,fs.readFileSync(path.join(__dirname,'../runtime',n),'utf8')]));
const input=()=>({suffix:'0123456789ab',sources:read()});
function model(){
 const objects=new Map(),descriptors=new Map(),trace=[];let fd=10,writes=0,syncs=0,errors='';
 const dir=(ino)=>({uid:0,gid:0,mode:0o40755,dev:1,ino,nlink:2,size:0,isDirectory:()=>true,isFile:()=>false,isSymbolicLink:()=>false});objects.set('/source-volume',dir(2));objects.set('/runtime-proof',dir(3));
 function access(p,bits){const q=objects.get(p);if(!q)throw Error('NO_OBJECT');const mode=q.uid===0?q.mode>>6:q.gid===0?q.mode>>3:q.mode;if((mode&bits)!==bits)throw Error('EACCES');}
 const f={constants:{O_WRONLY:1,O_CREAT:64,O_EXCL:128,O_NOFOLLOW:131072,O_RDONLY:0,O_DIRECTORY:65536},lstatSync:p=>{if(!objects.has(p))throw Error('NO_OBJECT');return objects.get(p);},realpathSync:p=>p,readdirSync(p){trace.push({kind:'readdir',path:p});if(p==='/sys/class/net')return ['lo'];access(p,5);return [...objects.keys()].filter(n=>path.dirname(n)===p).map(n=>path.basename(n));},openSync(p,flags,mode){trace.push({kind:'open',path:p});if(flags&1){access(path.dirname(p),3);if(objects.has(p))throw Error('OCCUPIED');const q={uid:0,gid:0,mode:0o100000|mode,dev:1,ino:objects.size+10,nlink:1,size:0,data:Buffer.alloc(0),isDirectory:()=>false,isFile:()=>true,isSymbolicLink:()=>false};objects.set(p,q);}else access(p,4);const n=++fd;descriptors.set(n,p);return n;},writeFileSync(n,b){writes++;const q=objects.get(descriptors.get(n));q.data=Buffer.from(b);q.size=b.length;},fsyncSync(n){assert.ok(descriptors.has(n));trace.push({kind:'fsync',path:descriptors.get(n)});syncs++;},closeSync(n){assert.ok(descriptors.has(n));trace.push({kind:'close',path:descriptors.get(n)});descriptors.delete(n);},readFileSync(p){access(p,4);return objects.get(p).data;},chmodSync(p,mode){const q=objects.get(p);q.mode=(q.mode&~0o7777)|mode;trace.push({kind:'chmod',path:p});},chownSync(p,uid,gid){const q=objects.get(p);q.uid=uid;q.gid=gid;trace.push({kind:'chown',path:p});}};
 const proc={getuid:()=>0,getgid:()=>0,env:{},stderr:{write:s=>{errors+=s;}},exitCode:undefined};
 return {objects,f,proc,trace,descriptors,writes:()=>writes,syncs:()=>syncs,errors:()=>errors,run(code){new vm.Script(code).runInNewContext({require:n=>n==='node:fs'?f:n==='node:crypto'?crypto:assert.fail('unexpected module'),process:proc,Buffer});}};
}
test('nine exact sources become pinned public argv bytes; altered sources fail closed',()=>{
 const i=input(),p=B.buildCompose(i),code=p.compose.services['init-volumes'].command[2];assert.equal(p.initializerArgumentBytes,Buffer.byteLength(code));assert.ok(p.initializerArgumentBytes<B.MAX_INITIALIZER_ARG_BYTES);assert.equal(code.includes('$'),false);new vm.Script(code);
 const m=model();m.run(code);assert.equal(m.proc.exitCode,undefined);assert.equal(m.writes(),9);assert.equal(m.syncs(),11);for(const [name,text]of Object.entries(i.sources)){const file=m.objects.get('/source-volume/'+name);assert.equal(file.data.toString('utf8'),text);assert.equal(file.uid,0);assert.equal(file.gid,0);assert.equal(file.mode&0o7777,0o444);assert.equal(crypto.createHash('sha256').update(file.data).digest('hex'),B.PINS[name]);}
 assert.equal(m.objects.get('/source-volume').mode&0o7777,0o555);assert.equal(m.objects.get('/runtime-proof').mode&0o7777,0o700);assert.equal(m.objects.get('/runtime-proof').uid,1000);assert.equal(m.objects.get('/runtime-proof').gid,1000);
 const chown=m.trace.findIndex(e=>e.kind==='chown'&&e.path==='/runtime-proof');assert.ok(chown>0);assert.ok(m.trace.findIndex(e=>e.kind==='open'&&e.path==='/runtime-proof')<chown);assert.ok(m.trace.every((e,n)=>e.path!=='/runtime-proof'||!['open','readdir'].includes(e.kind)||n<chown));assert.ok(m.trace.findIndex(e=>e.kind==='fsync'&&e.path==='/runtime-proof')>chown);assert.equal(m.descriptors.size,0);assert.throws(()=>m.f.openSync('/runtime-proof',m.f.constants.O_RDONLY|m.f.constants.O_DIRECTORY));assert.throws(()=>m.f.readdirSync('/runtime-proof'));
 for(const change of [v=>v.sources['runtime.cjs']+='\n',v=>v.sources.extra='unreviewed',v=>delete v.sources['health.cjs'],v=>v.suffix='invalid',v=>v.password='unrequested']){const bad=input();change(bad);assert.throws(()=>B.buildCompose(bad));}
});
test('empty private env, short aliases/domain and bounded executor mounts actual source volume read_only',()=>{
 const p=B.buildCompose(input()),g=p.compose.services.gateway;assert.equal(p.env,'');assert.equal(p.serviceName,'mgr-stage-0123456789ab');assert.equal(p.domain.host,'mgr-stage-0123456789ab.tazdb8.easypanel.host');assert.equal(p.domain.port,8099);assert.ok(g.networks.easypanel.aliases.every(x=>Buffer.byteLength(x)<=63));assert.deepEqual(g.environment,{NODE_PATH:'/app/node_modules'});assert.equal(g.user,'1000:1000');assert.equal(g.read_only,true);assert.deepEqual(g.cap_drop,['ALL']);assert.deepEqual(g.security_opt,['no-new-privileges:true']);assert.equal(g.cpus,0.35);assert.equal(g.mem_limit,335544320);assert.equal(g.memswap_limit,g.mem_limit);assert.equal(g.pids_limit,64);assert.equal(g.restart,'no');assert.equal(g.ports,undefined);assert.equal(g.build,undefined);assert.equal(g.configs,undefined);assert.equal(p.compose.configs,undefined);
 assert.deepEqual(g.entrypoint,['timeout','-s','KILL','600']);assert.deepEqual(g.command,['node','--max-old-space-size=96','/review/supervisor.cjs']);assert.deepEqual(g.depends_on,{'init-volumes':{condition:'service_completed_successfully'}});assert.ok(g.tmpfs.every(x=>x.startsWith('/tmp:')));assert.equal(g.volumes.length,2);assert.deepEqual(g.volumes[0],{type:'volume',source:'source',target:'/review',read_only:true,volume:{nocopy:true}});assert.equal(g.volumes[1].target,'/runtime-proof');
 assert.equal(p.limitations.deployApproved,false);assert.deepEqual(p.limitations.mutationActionsApproved,[]);assert.equal(p.deployability,'prepared_not_deployed');assert.equal(p.limitations.inlineConfigsAvoidedForRootReadOnlyCompatibility,true);assert.equal(p.limitations.actualSourceMountReadOnlyVerified,false);
});
test('both empty mounts and all source bytes are admitted before any writes; no partial reuse or secret reaches initializer',()=>{
 const p=B.buildCompose(input()),init=p.compose.services['init-volumes'],code=init.command[2];assert.equal(init.user,'0:0');assert.equal(init.network_mode,'none');assert.deepEqual(init.healthcheck,{disable:true});assert.equal(init.read_only,true);assert.deepEqual(init.cap_drop,['ALL']);assert.deepEqual(init.cap_add,['CHOWN']);assert.deepEqual(init.environment,{});assert.equal(init.env_file,undefined);assert.equal(init.cpus,0.1);assert.equal(init.mem_limit,67108864);assert.equal(init.memswap_limit,init.mem_limit);assert.equal(init.pids_limit,16);assert.equal(init.restart,'no');assert.equal(init.volumes.length,2);assert.ok(init.volumes.every(x=>x.volume.nocopy===true));assert.equal(p.compose.volumes.source.name,'shrigma-read-source-0123456789ab');assert.equal(p.compose.volumes.ledger.name,'shrigma-read-stage-0123456789ab');assert.equal(init.ports,undefined);
 for(const change of [m=>m.objects.set('/runtime-proof/occupied',{}),m=>m.objects.set('/source-volume/partial',{}),m=>m.objects.get('/runtime-proof').uid=1000,m=>m.objects.get('/source-volume').mode=0o40777,m=>m.objects.get('/runtime-proof').ino=2,m=>m.proc.env.PG_ADMIN_PASSWORD='SYNTHETIC_SENTINEL']){const m=model();change(m);m.run(code);assert.equal(m.proc.exitCode,1);assert.equal(m.writes(),0);assert.equal(m.errors(),'READ_PUBLIC_VOLUME_INITIALIZER_REFUSED\n');assert.equal(m.errors().includes('SYNTHETIC_SENTINEL'),false);}
 const corrupted=model();corrupted.run(code.replace('"base64":"','"base64":"A'));assert.equal(corrupted.proc.exitCode,1);assert.equal(corrupted.writes(),0);
 const done=model();done.run(code);assert.equal(done.writes(),9);done.run(code);assert.equal(done.proc.exitCode,1);assert.equal(done.writes(),9);
});
