'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const sourceRoot=process.env.DB_INVENTORY_SOURCE||path.join(__dirname,'sealed-view-inputs');
const runtime=process.env.DB_INVENTORY_RUNTIME||path.resolve(__dirname,'../../services/dashboard-operational');
const file=path.join(runtime,'native-database-inventory.cjs'),I=require(file),O=require(path.join(sourceRoot,'inputs/services/dashboard-operational/native-database-inventory.cjs'));
const canonical=x=>JSON.stringify(x,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const context={ownerId:'synthetic-current-owner'},secret='SYNTHETIC_PASSWORD_NOT_FOR_OUTPUT';
const fields=['oid','namespace','name','ownerRole','acl','definition_utf8_bytes','definition_sha256','fixed_fish_aristo_values_seed','empty_brands_literal','brands_jsonb_agg'];
const row=()=>({oid:'135626',namespace:'public',name:'shrigma_growth_email_ses_health_v1',ownerRole:'postgres',acl:null,definition_utf8_bytes:4096,definition_sha256:'a'.repeat(64),fixed_fish_aristo_values_seed:false,empty_brands_literal:false,brands_jsonb_agg:false});
const decode=s=>s.rows.map(r=>Object.fromEntries(s.fields.map((k,n)=>[k,r[n]])));
function fixture(options={}){
 const X=options.inventory||I;
 const calls=[],clients=[],gates=[],trace=[];
 const credential={schema:'shrigma-private-database-credential-v1',revision:1,ownerId:context.ownerId,username:'Synthetic Reader',password:secret,resource:{...X.RESOURCE},transport:{mode:'admitted-private-network'}};
 class Client extends EventEmitter{
  constructor(config){super();this.config=config;this.processID=101;this.connection=new EventEmitter();this.connection.stream={encrypted:false};this.ended=0;this.tx='I';clients.push(this);}
  ready(sql,state){if(options.missingAck===sql)return;this.tx=options.wrongAck===sql?'E':state;this.connection.emit('readyForQuery',{status:this.tx});}
  async connect(){trace.push('connect');this.ready('connect','I');}
  async query(sql){assert.equal(typeof sql,'string');calls.push(sql);trace.push(sql===X.PEER?'peer':sql===X.BEGIN?'begin':sql===X.ROLLBACK?'rollback':Object.keys(X.CATALOG).find(k=>X.CATALOG[k].sql===sql));
   if(options.queryHook)await options.queryHook(sql,this);
   if(options.queryThrow===sql)throw Error(secret);
   let result,state;
   if(sql===X.PEER){state='I';result={command:'SELECT',rowCount:1,rows:[{database:'listmonk',sessionRole:credential.username,currentRole:credential.username,pid:101,port:5432,engine:170012,ssl:false,read_only:'on'}]};}
   else if(sql===X.BEGIN||sql===X.ROLLBACK){state=sql===X.BEGIN?'T':'I';result={command:sql===X.BEGIN?'BEGIN':'ROLLBACK',rowCount:null,rows:[]};}
   else{state='T';const entry=Object.entries(X.CATALOG).find(([,d])=>d.sql===sql);assert(entry,'Only fixed catalog SQL');const rows=entry[0]==='healthView'?(options.rows||[row()]):[];result={command:'SELECT',rowCount:rows.length,rows};}
   if(options.result)result=options.result(sql,result);this.ready(sql,state);return result;
  }
  async end(){this.ended++;trace.push('end');if(options.endHook)await options.endHook();if(options.endThrow)throw Error(secret);if(!options.noEndEvent)this.emit('end');}
 }
 const args={enabled:true,driver:{Client,version:'8.23.1',packageSha256:'b'.repeat(64)},getPrivateCredential:()=>({...credential}),admitInspection:proof=>{gates.push(proof);trace.push('admit:'+proof.phase);if(options.deny===proof.phase)throw Error(secret);return {admitted:true,ownerId:credential.ownerId,profileRevision:credential.revision,credentialBindingHash:sha(canonical(Object.fromEntries(Object.entries(credential).filter(([k])=>k!=='password')))),resourceHash:sha(canonical(X.RESOURCE)),purpose:'read-only-migration-inventory',...(options.badPurpose?{purpose:'read-only-original-email-health'}:{})};}};
 const service=X.createDatabaseInventory(args);return {calls,clients,gates,trace,args,service,inspect:()=>service.inspect({},context)};
}
test('six sealed inputs exact bytes/SHA including TASK at package root',()=>{const m=JSON.parse(fs.readFileSync(path.join(sourceRoot,'INPUT-PINS.json')));assert.equal(m.files.length,6);for(const f of m.files){let p=path.join(sourceRoot,'inputs',f.path);if(!fs.existsSync(p))p=path.join(sourceRoot,f.path);const b=fs.readFileSync(p);assert.equal(b.length,f.bytes);assert.equal(sha(b),f.sha256);}});
test('additive13 catalog sections, prior12 SQL/limits/fields byte identical and session preserved',()=>{assert.equal(Object.keys(O.CATALOG).length,12);assert.equal(Object.keys(I.CATALOG).length,13);for(const [k,v] of Object.entries(O.CATALOG))assert.deepEqual(I.CATALOG[k],v);for(const k of ['RESOURCE','PEER','BEGIN','ROLLBACK','ENABLED'])assert.deepEqual(I[k],O[k]);const before=fs.readFileSync(path.join(sourceRoot,'inputs/services/dashboard-operational/native-database-inventory.cjs'),'utf8'),after=fs.readFileSync(file,'utf8');const begin='function createDatabaseInventory(',end='module.exports=';const expected=before.slice(before.indexOf(begin),before.indexOf(end)).replace("if(rows.length>def.limit+1)throw error('INVENTORY_PROTOCOL_REFUSED');","if(name==='healthView'&&rows.length>1)throw error('INVENTORY_VIEW_PROTOCOL_REFUSED');if(rows.length>def.limit+1)throw error('INVENTORY_PROTOCOL_REFUSED');").replace('const v=plain(row);exact(v,def.fields);',"const v=name==='healthView'?validateHealthViewRow(row):plain(row);exact(v,def.fields);");assert.equal(after.slice(after.indexOf(begin),after.indexOf(end)),expected);assert.equal(before.slice(before.indexOf('const own='),before.indexOf('function createDatabaseInventory(')),after.slice(after.indexOf('const own='),after.indexOf('function validateHealthViewRow(')));});
test('catalog SQL whitelist exactly one current original view, internal def hash only',()=>{const d=I.CATALOG.healthView;assert.equal(d.limit,1);assert.deepEqual(d.fields,fields);assert(d.sql.startsWith('SELECT '));assert(d.sql.endsWith(' LIMIT 2'));for(const text of ["n.nspname='public'","c.relname='shrigma_growth_email_ses_health_v1'","c.relkind='v'","pg_catalog.current_database()='listmonk'",'pg_catalog.pg_class','pg_catalog.pg_namespace','pg_catalog.pg_roles','pg_catalog.pg_get_viewdef(c.oid,false)',"pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(d.source,'UTF8')),'hex')"]){assert(d.sql.includes(text));}assert.doesNotMatch(d.sql,/\b(?:INSERT|UPDATE|DELETE|CREATE|DROP|ALTER|GRANT|COMMIT|md5|pgcrypto|payload)\b|\$[0-9]|FROM\s+public\./i);assert(!d.fields.some(k=>['source','definition','payload','config','body'].includes(k)));assert.equal((d.sql.match(/ BETWEEN 1 AND 65536/g)||[]).length,3);assert.equal((d.sql.match(/ELSE false END/g)||[]).length,3);});
function staticPatterns(){const sql=I.CATALOG.healthView.sql;return [...sql.matchAll(/E'((?:[^']|'')*)'/g)].map(m=>m[1].replace(/''/g,"'").replace(/\\\\/g,'\\')).map(p=>new RegExp(p.replaceAll('[[:space:]]','\\s').replaceAll('[:alnum:]','a-zA-Z0-9')));}
test('closed structural patterns recognize both normalized seed orders and whitespace, do not infer meaning',()=>{const [seed,empty,key,agg]=staticPatterns();assert(seed&&empty&&key&&agg);for(const text of [" FROM (VALUES ('fish'::text),('aristo'::text)) b(marca)","\nFROM ( VALUES\n ('aristo' :: text), ('fish'::text) ) b(marca)"]){assert(seed.test(text));}for(const text of ["FROM (VALUES ('fish'::text),('fish'::text))","FROM (VALUES ('foreign'::text),('aristo'::text))","FROM (VALUES ('fish'::text),('aristo'::text),('other'::text))"]){assert(!seed.test(text));}assert(empty.test("jsonb_build_object('brands'::text, '[]'::jsonb)"));assert(!empty.test("jsonb_build_object('other'::text, '[]'::jsonb)"));assert(!empty.test("jsonb_build_object('brands'::text, '[1]'::jsonb)"));assert(key.test("'brands'::text, (SELECT jsonb_agg(x))"));assert(agg.test('pg_catalog.jsonb_agg(x)'));assert(!agg.test('private_jsonb_agg(x)'));});
test('schema v4 preserved with READONLY I/T/I/end and flagsfalse never healthy',async()=>{const f=fixture(),v=await f.inspect();assert.equal(v.schema,'shrigma-database-inventory-v4');assert.equal(v.encoding,'fields-rows-v1');assert.equal(v.classification,'unknown');assert.equal(v.cutoverAdmitted,false);assert.equal(v.operational,false);assert.equal(v.productionAdmitted,false);assert(!('healthy' in v));assert.deepEqual(decode(v.data.healthView),[row()]);assert.deepEqual(v.completeness.healthView,{limit:1,returned:1,truncated:false});assert.deepEqual(f.calls,[I.PEER,I.BEGIN,...Object.values(I.CATALOG).map(d=>d.sql),I.ROLLBACK]);assert.equal(f.clients[0].ended,1);assert.equal(f.clients[0].config.ssl,false);assert(f.clients[0].config.options.includes('default_transaction_read_only=on'));assert(f.clients[0].config.options.includes('search_path=pg_catalog'));assert.deepEqual(f.gates.map(g=>g.phase),['connect','catalog']);assert(f.gates.every(g=>g.purpose==='read-only-migration-inventory'));assert(!JSON.stringify(v).includes(secret));assert(!JSON.stringify(f.gates).includes(secret));assert(!JSON.stringify(v).includes(' AS source'));await f.service.close();});
test('nullable owner/ACL and max bytes metadata preserved, flags remain independent',async()=>{const r={...row(),oid:'4294967295',ownerRole:null,acl:null,definition_utf8_bytes:65536,fixed_fish_aristo_values_seed:true,empty_brands_literal:true,brands_jsonb_agg:true};const f=fixture({rows:[r]}),v=await f.inspect();assert.deepEqual(decode(v.data.healthView),[r]);assert.equal(v.operational,false);assert.equal(v.classification,'unknown');assert.equal(v.cutoverAdmitted,false);await f.service.close();});
test('absent view remains empty, not installed or healthy',async()=>{const f=fixture({rows:[]}),v=await f.inspect();assert.deepEqual(v.data.healthView.rows,[]);assert.equal(v.completeness.healthView.returned,0);assert.equal(v.complete,true);assert.equal(v.cutoverAdmitted,false);assert.equal(v.operational,false);await f.service.close();});
for(const count of [2,3])test('limit+1/overflow '+count+' rows fail view protocol, no metadata prefix',async()=>{const f=fixture({rows:Array.from({length:count},row)});await assert.rejects(f.inspect(),{code:'INVENTORY_VIEW_PROTOCOL_REFUSED',status:503});assert.equal(f.calls.filter(x=>x===I.CATALOG.healthView.sql).length,1);assert.equal(f.clients[0].ended,1);await f.service.close();});
for(const change of [{oid:'0'},{oid:'01'},{oid:'4294967296'},{oid:135626},{namespace:'foreign'},{name:'foreign_view'},{definition_sha256:'md5'},{definition_sha256:'A'.repeat(64)},{definition_sha256:null},{definition_utf8_bytes:0},{definition_utf8_bytes:65537},{definition_utf8_bytes:'4096'},{definition_utf8_bytes:1.5},{definition_utf8_bytes:NaN},{fixed_fish_aristo_values_seed:null},{empty_brands_literal:'false'},{brands_jsonb_agg:1},{ownerRole:{}},{acl:['raw']},{ownerRole:'x'.repeat(16385)},{raw_definition:'SELECT private_data'},{payload:{email:'private@example.invalid'}}])test('strict view field rejects '+Object.keys(change),async()=>{const f=fixture({rows:[{...row(),...change}]});await assert.rejects(f.inspect(),e=>{assert.equal(e.code,'INVENTORY_VIEW_PROTOCOL_REFUSED');assert(!String(e).includes('private'));return true;});assert.equal(f.clients[0].ended,1);assert.equal(f.calls.filter(x=>x===I.CATALOG.healthView.sql).length,1);await f.service.close();});
test('hidden/symbol/getter/proxy metadata rejected without evaluating secrets',async()=>{let calls=0;const getter=()=>{calls++;throw Error(secret);};for(const modify of [v=>Object.defineProperty(v,'definition_sha256',{enumerable:true,get:getter}),v=>Object.defineProperty(v,'raw',{value:secret}),v=>Object.assign(v,{[Symbol('secret')]:secret}),v=>new Proxy(v,{get:getter,ownKeys:getter,getPrototypeOf:getter})]){const r=row(),result=modify(r);const f=fixture({rows:[result||r]});await assert.rejects(f.inspect(),{code:'INVENTORY_VIEW_PROTOCOL_REFUSED'});assert.equal(f.clients[0].ended,1);await f.service.close();}assert.equal(calls,0);});
for(const phase of ['connect','catalog'])test('CURRENT binding admission '+phase+' denies new metadata',async()=>{const f=fixture({deny:phase});await assert.rejects(f.inspect(),{code:'INVENTORY_ADMISSION_REFUSED'});assert.equal(f.calls.includes(I.CATALOG.healthView.sql),false);assert(f.clients.every(c=>c.ended===1));await f.service.close();});
test('health purpose cannot substitute existing inventory admission; OFF performs no credential/SQL',async()=>{const f=fixture({badPurpose:true});await assert.rejects(f.inspect(),{code:'INVENTORY_ADMISSION_REFUSED'});assert.equal(f.clients.length,0);const off=I.createDatabaseInventory({...f.args,enabled:false});await assert.rejects(off.inspect({},context),{code:'INVENTORY_OFF'});assert.equal(f.calls.length,0);await off.close();await f.service.close();});
for(const opt of ['wrongAck','queryThrow'])test('view '+opt+' refuses and closes once without retry',async()=>{const f=fixture({[opt]:I.CATALOG.healthView.sql});await assert.rejects(f.inspect());assert.equal(f.calls.filter(x=>x===I.CATALOG.healthView.sql).length,1);assert.equal(f.clients[0].ended,1);await f.service.close();});
test('malformed SELECT ACK and ROLLBACK ACK suppress metadata',async()=>{for(const sql of [I.CATALOG.healthView.sql,I.ROLLBACK]){const f=fixture({result:(q,r)=>q===sql?{...r,rowCount:q===I.ROLLBACK?0:0}:r});await assert.rejects(f.inspect(),{code:'INVENTORY_ACK_UNKNOWN'});assert.equal(f.clients[0].ended,1);assert.equal(f.calls.filter(x=>x===I.CATALOG.healthView.sql).length,1);await f.service.close();}});
for(const opt of ['noEndEvent','endThrow'])test('end '+opt+' refuses all metadata and further sessions',async()=>{const f=fixture({[opt]:true});await assert.rejects(f.inspect(),{code:opt==='endThrow'?'INVENTORY_CLOSE_FAILED':'INVENTORY_CLOSE_UNCONFIRMED'});await assert.rejects(f.inspect(),{code:'INVENTORY_UNAVAILABLE'});await assert.rejects(f.service.close(),{code:'INVENTORY_CLOSE_UNCONFIRMED'});assert.equal(f.clients[0].ended,1);});
test('caller cannot choose SQL/OID/view/destination',async()=>{const f=fixture();for(const q of [{sql:'SELECT 1'},{oid:'135626'},{name:'foreign_view'},{resource:{database:'other'}}])await assert.rejects(f.service.inspect(q,context));assert.equal(f.clients.length,0);assert.equal(f.calls.length,0);await f.service.close();});

function acceleratedInventory(){const mod={exports:{}};new Function('require','module','exports','setTimeout','clearTimeout',fs.readFileSync(file,'utf8'))(require,mod,mod.exports,(fn,ms)=>setTimeout(fn,ms===60000?200:ms===15000?100:ms===12000?50:ms===5000?40:10),clearTimeout);return mod.exports;}
test('missing view ACK times out, closes once and never retries metadata SELECT',async()=>{const X=acceleratedInventory(),f=fixture({inventory:X,missingAck:X.CATALOG.healthView.sql});await assert.rejects(f.inspect(),{code:'INVENTORY_TIMEOUT'});assert.equal(f.calls.filter(q=>q===X.CATALOG.healthView.sql).length,1);assert.equal(f.clients[0].ended,1);await f.service.close();});
test('view query timeout closes once, late completion cannot publish or retry',async()=>{const X=acceleratedInventory();let release;const gate=new Promise(r=>release=r);const f=fixture({inventory:X,queryHook:async q=>{if(q===X.CATALOG.healthView.sql)await gate;}});await assert.rejects(f.inspect(),{code:'INVENTORY_QUERY_FAILED'});assert.equal(f.calls.filter(q=>q===X.CATALOG.healthView.sql).length,1);assert.equal(f.clients[0].ended,1);release();for(let n=0;n<12;n++)await Promise.resolve();assert.equal(f.calls.includes(X.ROLLBACK),false);await f.service.close();});
